      SUBROUTINE ANOMALY(LAT, TOFYR, TIME, ANOM)
  
      COMMON/TEMP/INSOL 
  
      REAL INSOL, LAT, TIME, PRESVAL, ANOM
      INTEGER TOFYR 
  
      CALL ASTR (TIME)
      CALL YEAR(LAT, TOFYR) 
C     THE FIRST ARGUMENT IS THE LATITUDE TO COMPUTE FOR 
C     THE SECOND IS THE TIME OF YEAR. 1=VERNAL EQUINOX
C         46=THE AUTUMNAL EQUINOX 
      ANOM = INSOL - PRESVAL
  
      RETURN
  
      ENTRY ANOMSET (LAT, TOFYR, TIME, ANOM)
C     SUBTRACT THE PRESENT VALUE OF INSOLATION FROM COMPUTED VALUE
C       TO GET ANOMALY. 
      CALL ASTSET 
      CALL ASTR(0.0)
      CALL YEAR(LAT, TOFYR) 
      PRESVAL = INSOL 
  
      RETURN
      END 
