      SUBROUTINE QSEXT(QSS, QSD, H, NX, NY, TSTEP, LOY,
     1  XMIN, XMAX, YMIN, YMAX, QSFMAX, QSFREF, QSM,
     2  STRSPR, STRSUM, STRFLL, STRWIN               )
C     SUBROUTINE TO EXTRAPOLATE THE SALINIZATION FORCING TO THE NEXT
C       TIME STEP.  BG 3-25-88.
C     HIGH FORCING SPECIFICATION CHANGED TO A RECTANGLE 12-19-88, BG.
      INTEGER NX, NY, TSTEP
      REAL QSS(NX, NY), QSD(NX, NY), H(NX, NY)
      INTEGER I, J, T
      INTEGER XMIN, XMAX, YMIN, YMAX
C     FIND THE CENTER AND SIZE OF THE ENHANCED FREEZING REGION
C     FIND THE BOUNDS OF THE ENHANCED FREEZING RECTANGLE. 12-19-88.
      REAL QSFMAX, QSFREF
C     THE MAXIMUM AND NORMAL FREEZING RATES.
      REAL QSM
C     THE MELTING RATE (UNIFORM OVER DOMAIN)
      INTEGER STRSPR, STRSUM, STRFLL, STRWIN, LOY
C     START OF SPRING, SUMMER, FALL, WINTER, AND LENGTH OF THE YEAR
C       FOR NOW, DISCONTINUOUS BEHAVIOR - WINTER HAS FREEZING, FALL
C       SPRING HAVE NORE MELT OR FREEZE, AND SUMMER HAS MELTING
      REAL PI, TIME
      PARAMETER (PI = 3.141592654)
      T = MOD(TSTEP,LOY)
      IF ((T .GE. STRWIN) .AND. (T .LT. STRSPR)) THEN
C     NOTE THAT THIS ASSUMES THAT TIME IS TOLD WITHIN A YEAR.
C     WINTERTIME
CD      PRINT *,'WINTER'
        DO 1000 J = 1, NY
          DO 1010 I = 1, NX
            IF ((I .GE. XMIN .AND. I .LE. XMAX) .AND.
     1          (J .GE. YMIN .AND. J .LE. YMAX) ) THEN
C             IN ENHANCED AREA
              QSS(I,J) = QSFMAX
              QSD(I,J) = QSFMAX
             ELSE
              QSS(I,J) = QSFREF
              QSD(I,J) = QSFREF
            ENDIF
 1010     CONTINUE
 1000   CONTINUE
       ELSEIF (T .GE. STRSPR .AND. T .LT. STRSUM) THEN
C       SPRING, QSS = QSD = 0.0
        DO 1100 J = 1, NY
          DO 1110 I = 1, NX
            QSS(I,J) = 0.0
            QSD(I,J) = 0.0
 1110     CONTINUE
 1100   CONTINUE
       ELSEIF (T .GE. STRSUM .AND. T .LT. STRFLL) THEN
        DO 2000 J = 1, NY
          DO 2010 I = 1, NX
            QSS(I,J) = QSM
            QSD(I,J) = QSM
 2010     CONTINUE
 2000   CONTINUE
       ELSE
C       FALL, DO NOTHING
        DO 2100 J = 1, NY
          DO 2110 I = 1, NX
            QSS(I,J) = 0.0
            QSD(I,J) = 0.0
 2110     CONTINUE
 2100   CONTINUE
      ENDIF
C     NOTE THE LOGICALLY BIZARRE STRUCTURE, SOMETHING TO CHANGE.
C     FIXED 3-30-88
      RETURN
      ENTRY QSEXTS(QSS, QSD, H, NX, NY, TSTEP, LOY,
     1  XMIN, XMAX, YMIN, YMAX, QSFMAX, QSFREF, QSM,
     2  STRSPR, STRSUM, STRFLL, STRWIN               )
C     SUBROUTINE TO EXTRAPOLATE THE SALINIZATION FORCING TO THE NEXT
C       TIME STEP.  BG 3-25-88.
C     SINUSOIDAL VARIATION IN TIME VERSION. 3-30-88. BG
C     ADDED AS AN ENTRY TO QSEXT 5-26-88. BG
C     THE PERIOD OF THE OSCILLATION (IN TIME STEPS) IS TAKEN AS STRWIN
C        8-10-88. BG
C     LOGICALLY OUTDATED BY RECTANGLE FORCING VERSION.
      TIME = FLOAT(TSTEP)/FLOAT(STRWIN)
      DO 3000 J = 1, NY
        DO 3010 I = 1, NX
          IF ((I .LE. XMIN .AND. I .GE. XMAX) .AND.
     1        (J .LE. YMIN .AND. J .GE. YMAX) ) THEN
C           IN ENHANCED AREA
            IF (SIN(2.*TIME*PI) .GT. 0.0) THEN
              QSS(I,J) = QSFMAX * SIN(2.*PI*TIME)
              QSD(I,J) = QSFMAX * SIN(2.*PI*TIME)
             ELSE
              QSS(I,J) = QSFREF * SIN(2.*PI*TIME)
              QSD(I,J) = QSFREF * SIN(2.*PI*TIME)
            ENDIF
           ELSE
            QSS(I,J) = QSFREF * SIN(2.*PI*TIME)
            QSD(I,J) = QSFREF * SIN(2.*PI*TIME)
          ENDIF
 3010   CONTINUE
 3000 CONTINUE
      RETURN
      END
