#!/bin/sh

########################################
# Generates GEMPAK grids for NCEP sea-ice analysis
# Modified 11/19/01 J.L.Partain/MPC to add VG file creation of ice edge
# Modified 12/12/04 J. Carr/PMB to move processing into production from OPC
# Modified 03/12/13 C. Caruso Magee/PMB for WCOSS. Changing 
#    /com/mrf/prod/mrf.PDY to /com/omb/prod/sice.PDY to reflect new 
#    location of engice input file.
########################################

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
export pid=$$
export DATA=$DATAROOT/${job}.${pid}
mkdir -p $DATA
cd $DATA 

export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export NET=${NET:-omb}
export RUN=${RUN:-ice}
export RUN2=${RUN2:-sice}
export fend=00
export finc=12
export fstart=00
export model=eng
export GRIB=
export EXT=""
export DBN_ALERT_TYPE=ICE_GEMPAK

setpdy.sh
. ./PDY
env

#export com=${com:-${COMROOT}/${NET}/${envir}}
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN2}.${PDY}}
#XXW export COMOUT=${COMOUT:-${COMROOT}/nawips/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN2}.${PDY}/gempak}
#export WMOOUT=${WMOOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/wmo}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
#  mkdir -p -m 775 $WMOOUT
fi

cp ${HOMEseaice_analysis}/gempak/fix/*.tbl .

########################################################
# Execute the script.
$HOMEseaice_analysis/scripts/exice_nawips.sh.ecf
# Execute the META file generation scripts.
$HOMEseaice_analysis/gempak/ush/ice/ice_edge_vgf.sh

cd $DATA
#if [ "$KEEPDATA" != "YES" ] ; then
#  rm -rf $DATA
#fi

date
