      SUBROUTINE RDDICT(CALLS,ICAO,NSTA)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    RDDICT      READS STATION DICTIONARY FOR ICAO IDENTS.
C   PRGMMR: GILBERT          ORG: W/OSD211   DATE: 96-11-21
C
C ABSTRACT: THIS ROUTINE READS MDL'S STATION DICTIONARY AND RETURNS
C   CORRESPONDING ICAO STATION IDENTIFIERS FOR A GIVEN LIST OF MOS
C   STATIONS.
C
C PROGRAM HISTORY LOG:
C   96-11-21  GILBERT
C
C USAGE:    CALL PGM-NAME(INARG1, INARG2, WRKARG, OUTARG1, ... )
C   INPUT ARGUMENT LIST:
C     CALLS()   - LIST OF MOS STATIONS
C     NSTA      - NUMBER OF STATIONS
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     ICAO()    - CORRESPONDING LIST OF ICAO STATION IDENTIFIERS.
C
C   INPUT FILES:   
C     UNIT 30  - MDL'S STATION DICTIONARY.
C
C REMARKS: THIS ROUTINE IS TEMPORARY AND WILL BE REPLACED WITH THE
C          GENERIC STATION DICTIONARY READER, WHEN IT IS AVAILABLE.
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  CRAY
C
C$$$
      CHARACTER*8 CALLS(NSTA),ICAO(NSTA),CTEMP1
      CHARACTER*4 CTEMP2
 5    READ(30,100,END=900) CTEMP1,CTEMP2
 100  FORMAT(A8,1X,A4)
      DO 600 N=1,NSTA
        IF ( CTEMP2//'    '.EQ.CALLS(N) ) ICAO(N)=CTEMP1
 600  CONTINUE
      GOTO 5
 900  RETURN
      END
