C***********************************************************----------!!
      SUBROUTINE CONVEC(SS, SD, NX, NY, TSTEP)
C     SUBROUTINE TO LOOK FOR CONVECTIVE OVERTURNING AND CABBELING.
C     OVERTURN ADDED 3-9-88.
C     USES SHORT FORM ENTRY POINT TO RHO 5-26-88.

      INTEGER NX, NY, TSTEP
      REAL SS(NX, NY), SD(NX, NY)

      INTEGER I, J
      LOGICAL OVRTRN, OVRLST
      SAVE    OVRLST

      OVRTRN = .FALSE.
      DO 1000 J = 1, NY
        DO 1010 I = 1, NX
CF        RHO1 = RHOS1P(SS(I,J)+SD(I,J), 0.0, 0.)
CF        RHO2 = RHOS1P(SS(I,J)-SD(I,J), 0.0, 0.)
          IF (SD(I,J) .GT. 0.0) THEN
            SD(I,J) = 0.0
            OVRTRN = .TRUE.
          ENDIF
 1010   CONTINUE
 1000 CONTINUE

      IF (TSTEP .EQ. 1) GO TO 9999

      IF (OVRTRN .AND. (.NOT. OVRLST) ) THEN
        PRINT *,'STARTED CONVECTION AT TSTEP',TSTEP
       ELSE IF ((.NOT. OVRTRN)  .AND. OVRLST ) THEN
        PRINT *,'STOPPED CONVECTION AT TSTEP',TSTEP
      ENDIF

 9999 CONTINUE
      OVRLST = OVRTRN

      RETURN
      END
