#!/bin/ksh

cd /data/new
cp ~/john3/* .

for base in 9701 9703
do
  for pole in north south
  do
    p=`echo $pole | cut -c1`
    dy=01
    while [ $dy -le 31 ]
    do
      wgrib /data/sflux/${p}psg.$base | grep $base$dy | wgrib -i /data/sflux/${p}psg.$base -nh -o ${p}$dy
      dy=`expr $dy + 1`
      if [ $dy -lt 10 ] ; then
        dy=0$dy
      fi
    done
    ./avg${p} 31
    mv avgout avgout.$pole
  done
done


for base in 9702
do
  for pole in north south
  do
    p=`echo $pole | cut -c1`
    dy=01
    while [ $dy -le 28 ]
    do
      wgrib /data/sflux/${p}psg.$base | grep $base$dy | wgrib -i /data/sflux/${p}psg.$base -nh -o ${p}$dy
      dy=`expr $dy + 1`
      if [ $dy -lt 10 ] ; then
        dy=0$dy
      fi
    done
  done
  ./avg${p} 28
  mv avgout avgout.$pole
done
