#!/bin/sh

set -xae
# #### 05/18/99 #############################
# SETUP SEAICE CONCENTRATION ANALYSIS PROCESSING CONTROL SHELL VARIABLES
# ###########################################
export PS4='$SECONDS + '
date
echo cyc is ${cyc:?}
echo envir is ${envir:?}
echo seaice_analysis_ver is ${seaice_analysis_ver:?} 
export pid=$$

export DATA=$DATAROOT/${job}.${pid}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z
export NET=omb

#################################################
# Specify job's execution areas (directory paths)
#################################################
export EXECseaice_analysis=${EXECseaice_analysis:-$HOMEseaice_analysis/exec}
export FIXseaice_analysis=${FIXseaice_analysis:-$HOMEseaice_analysis/fix}
export PARMseaice_analysis=${PARMseaice_analysis:-$HOMEseaice_analysis/parm}
export USHseaice_analysis=${USHseaice_analysis:-$HOMEseaice_analysis/ush}

#########################################
# Run setpdy and initialize PDY variables
#########################################
setpdy.sh
. ./PDY

export RUN=${RUN:-sice}
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export WMOOUT=${WMOOUT:-${COMOUT}/wmo}

export COMINsst_base=${COMINsst_base:-$(compath.py gfs/prod/sst)}
export COMINsst=${COMINsst:-${COMINsst_base}.${PDY}}
export COMINsstm1=${COMINsstm1:-${COMINsst_base}.${PDYm1}}

export DCOM=${DCOM:-$DCOMROOT/prod/$PDY}
export DCOMm1=${DCOMm1:-$DCOMROOT/prod/$PDYm1}

#NCO request for this var to be defined in J
#phase1 export USHobsproc_dump=${NWROOTp1}/obsproc_dump.${obsproc_dump_ver}/ush
export HOMEobsproc_dump=${HOMEobsproc_dump:-$NWROOT/obsproc_dump.${obsproc_dump_ver}}
export USHobsproc_dump=${USHobsproc_dump:-${HOMEobsproc_dump}/ush}
export HOMEobsproc_shared_bufr_dumplist=${HOMEobsproc_shared_bufr_dumplist:-$NWROOT/obsproc_shared/bufr_dumplist.${obsproc_shared_bufr_dumplist_ver}}

mkdir -p $COMOUT $WMOOUT
env

#####################################
# Execute the script
$HOMEseaice_analysis/scripts/exseaice_analysis.sh.ecf >> $pgmout
export err=$?
err_chk
#####################################

cat $pgmout

#if [ "$KEEPDATA" != "YES" ] ; then
#  rm -rf $DATA
#fi

date
