      SUBROUTINE FTRC (F,C,BUFFER)
  
      INTEGER MXSB,IWKDIM 
      PARAMETER (MXSB    = 160) 
      PARAMETER (IWKDIM  = 3*MXSB+150)
  
      COMPLEX C(-MXSB-2:MXSB+1) 
      REAL F(-MXSB-2:MXSB+1),WK(IWKDIM) 
      INTEGER IWK(IWKDIM),I 
      REAL BUFFER 
  
      CALL FFTRC(F,2*MXSB+4,C,IWK,WK) 
      DO 1000 I=-MXSB-2,0 
C       USE -C(I) RATHER THAN CONJG(C(I)) BECAUSE THE REAL PART IS 0. 
        C(I)=CMPLX(0.0,-AIMAG(C(I)))/(2*MXSB+4) 
 1000 CONTINUE
      DO 1100 I=1,MXSB+1
        C(I)=-C(-I) 
 1100 CONTINUE
      RETURN
  
  
      ENTRY IFTRC(F,C,BUFFER) 
  
C     ENTER THE REAL PART OF A INTO X 
      CALL FFTCC(C,2*MXSB+4,IWK,WK) 
      DO 100 I=-MXSB-2,MXSB+1 
        F(I)=REAL(C(I)) 
        IF (ABS(AIMAG(C(I))).GT.BUFFER) STOP'NONZERO IMAGINARY' 
 100  CONTINUE
      RETURN
      END 
