      PROGRAM ISTEST 
  
C================================================================== 
C 
C             NAME: C99THRD 
C             FROM: C99SLI
C               DATE = 19 APR 85
C 
C                   THIS MODEL OF THE ICE SHEET USES THE
C                   REVISED NUMERICAL SCHEMA OF 10 FEB 84.
C                   MODIFIED ACCORDING TO 2-18-84 NOTES.
C                   VOLUME COMPUTATION CORRECTED 2-25-84. BG
C                   CHANGES IN NO ICE SHEET CASES MADE 3-25-84
C                   FIRN LINE CALCULATIONS CORRECTED 3/25 TO 4/2/84 BG
C                   TEMPERATURE DEPENDANT ACCUMULATION INTRODUCED 
C                       4-18-84 BG
C                   CORRECTIONS 4-23-84.  BG
C                   REDERIVED ISSB+1 PT CAL 4/27/84 
C         4-30-84   BEDROCK EXTRAP MOVED OUTSIDE ITERATION LOOP 
C                   EPSI FUDGE FACTOR AND XNAUT REMOVED 5-15-84 
C                   MOST PARAMETER STATEMENTS REMOVED 5-15-84 
C                   MOST CONSTANTS NOW INITIALIZED IN ISINIT 5-18-84
C                   CLEANUP OF ISHEET JUNE 6 84 
C                   REDERIVED BEDROCK EXTRAPOLATION 6-12-84 
C                   THICKNESSES REPLACED WITH MAX(0,H+H') 6-12-84 
C                   SMALL ICE SHEET CASE ADDED 6-12-84
C                   SPECIAL TREATMENT OF ACCUM AT ISSB+1 DROPPED 6-13 
C                   ALTERNATE SET-UP MODES DROPPED 6-13-84
C                   ISSB, ISNB COMPUTATIONS CORRECTED-USE BHAT 6-13 
C                   WHEN ICE SHEET MOVES, SET HVIRT=H(ISSB+1) 6-14-84 
C                   SET H(ISSB+1)=HVIRT JUST BEFORE BEDROCK EXTRAP. 
C                   THIS WILL ALLOW THE SHEET TO MOVE FORWARD DUE TO
C                   MASS FLUX. 6-14-84
C                   FORCING CORRECTED TO NOTES OF EB 6-7-84, ON 6-15-84 
C                   UJM1,VJM1 REMOVED 6-21-84 
C                   BEDROCK EXTRAPOLATION MOVED BEFORE THE H EXTRAP 6-21
C                   ZETA MULTIPLIER ADDED FOR MASS FLUX AT ISSB+1 6-28
C                   ACCUMULATION FOR T*>0 MODIFIED 6-29-84
C                   ITERATION LOOP CONTROL REINTRODUCED 7-1-84. 
C                   TWO-LAYER BEDROCK MODEL ADDED 7-5-84. 
C                   SINGLE VISCOUS LAYER IN FRONT OF THE ICE SHEET. 7-25
C     PARABOLIC SET UP. 
C     TEMPERATURE DEPENDANT FLOW RATE ADDED 2-23-85 
C     MASS FLUX DUE TO SLIDING ADDED 2-23-85
C     MASS FLUX DUE TO SLIDING REVISED FOR CONSTANT SLIDE VELOCITY 4-8
C     MASS FLUX DUE TO SLIDING PROPORTIONAL TO SHEAR STRESS**2 4-19 
C================================================================== 
  
      INTEGER MXSB
      PARAMETER (MXSB  = 160) 
  
      COMMON /ISCOM/ HGT(0:MXSB,0:1), H, HP,
     1      ACMRAT, SLOPE, TIMELP, OSCARG, TIMSTP, GRDSTP,
     2      SNLAMP, SNLMPT, SNLXIN, TRIPS, RNETAC, POLFLX,
     3      MSNAUT, MAPRIM, OUTDAT, DX, DT, DHPDT(0:MXSB),HPCALL, 
     4      ISSB
  
      COMMON /TEMCOM/ TEMP(0:MXSB)
      REAL TEMP 
  
      INTEGER I, J, H, HP, TRIPS, HPCALL, ISSB
      REAL HGT, ACMRAT, SLOPE, SNLXIN 
      REAL DX, DT, TIME, GRDSTP 
      REAL DHPDT, MSNAUT, MAPRIM
  
      LOGICAL  OUTHGT, OUTVOL, OUTDAT 
      REAL CALTIM, FNLTIM, TIMSTP 
      REAL SNLAMP, SNLMPT, OSCARG 
      REAL LENGTH, PEAK, MHP, A, B, C 
  
C------------------------------------------------------------------ 
      CALL PMDARRY(MXSB+1,4)
  
      TRIPS= -1 
  
      READ (*,9006) GRDSTP
      READ (*,9006) TIMSTP
      DX = GRDSTP * 111111.111111 
  
      READ (*,9007) OUTDAT
 9007 FORMAT(L14) 
      OUTHGT  = .TRUE.
      OUTVOL  = .TRUE.
  
      READ (*,9006) CALTIM
      READ (*,9006) FNLTIM
 9006 FORMAT (F14.4)
  
C     INITIALIZE THE ISHEET SUBROUTINE
      CALL ISHEET (0.0) 
C     INITIALIZE THE BEDROCK SUBROUTINE 
      CALL HPEXIN 
  
C------------------------------------------------------------------ 
  
C     INITIAL CONDITIONS FOR PARABOLIC ICE SHEET
      LENGTH = 2700000.0
      PEAK   = 4000.0 
      MHP    = 400.0
      I      = INT(LENGTH / DX )
      DO 100 J = 0,I
        HGT(J,H) = PEAK*SIN(3.1415926535898*J*DX / LENGTH)**.4
        HGT(J,HP)= .3*HGT(J,H)
 100  CONTINUE
      HGT(0,H)=MIN(MHP,HGT(1,H))
  
      DO 110 J=I+1,MXSB 
        HGT(J,H)=0.0
        HGT(J,HP)=0.0 
 110  CONTINUE
  
C     PRINT OUT THE INITIAL CONDITIONS
      IF (OUTDAT) THEN
        J=MXSB
 1000   IF ((HGT(J,0)+HGT(J,1).LE.0.0).AND.(J.GT.1)) THEN 
          J=J-1 
          GO TO 1000
        ENDIF 
        DO 1100 I=0,MIN(J+5,MXSB) 
          IF (MOD(I,50).EQ.0) WRITE (*,9001) 0
          WRITE (*,9002) I,(11.6+GRDSTP*I),(I*DX/1000.0),HGT(I,0),
     1        HGT(I,1),HGT(I,0)+HGT(I,1)
 1100   CONTINUE
      ENDIF 
C 
C     WRITE THE INITIAL HEIGHTS OUT TO TAPE 2 IF OUTHGT TRUE
      IF (OUTHGT) THEN
        WRITE(2,9005) 0.0 
        WRITE(2,9003) ((INT(HGT(I+J,0)),J=0,9),I=0,MXSB-10,10)
        WRITE(2,9003) ((INT(HGT(I+J,1)),J=0,9),I=0,MXSB-10,10)
      ENDIF 
  
C     CAL THE INITIAL VOLUME AND WRITE TO TAPE 4 IF OUTVOL TRUE 
C     USE THE TRAPEZOIDAL RULE TO COMPUTE THE 'VOLUME'. 
      IF (OUTVOL) THEN
        WRITE (4,9004) HINTEG(1),0.0,0.0,0.0,0.0,0.0
      ENDIF 
  
C------------------------------------------------------------------ 
  
C-----BEGIN MAIN TIME EXTRAPOLATION LOOP
C     CALL THE BEDROCK EXTRAPOLATION ROUTINE SINCE THERE IS A LOAD
C       AT THE BEGINNING OF THE RUN.
      CALL HPEXT
      DO 10000 TIME=CALTIM, FNLTIM, CALTIM
  
        CALL ISHEET ( CALTIM )
  
C       WRITE OUT HEIGHTS, ETC TO OUTPUT IF OUTDAT=TRUE.
        IF (OUTDAT) THEN
          J=MXSB
 1400     IF ((HGT(J,H)+HGT(J,HP).LE.0.0).AND.(J.GT.1)) THEN
            J=J-1 
            GO TO 1400
          ENDIF 
          DO 1500 I=0,MIN(J+5,MXSB) 
            IF (MOD(I,50).EQ.0) WRITE(*,9001) TIME
            WRITE (*,9002) I,(11.6+GRDSTP*I),(I*DX/1000.0),HGT(I,H),
     1        HGT(I,HP),HGT(I,H)+HGT(I,HP)
 1500     CONTINUE
        ENDIF 
  
C-------WRITE HEIGHT PROFILE OUT TO TAPE 2 IF OUTHGT TRUE 
        IF (OUTHGT) THEN
          WRITE (2,9005) SNLXIN 
          WRITE(2,9003) ((INT(HGT(I+J,H)),J=0,9),I=0,MXSB-10,10)
          WRITE(2,9003) ((INT(HGT(I+J,HP)),J=0,9),I=0,MXSB-10,10) 
        ENDIF 
  
C-------CAL ICE VOL AND WRITE TO TAPE 4 IF OUTVOL TRUE
C-------USE THE TRAPEZOIDAL RULE
        IF (OUTVOL) THEN
          WRITE (4,9004) HINTEG(1),POLFLX,MSNAUT,MAPRIM,RNETAC, 
     1    ISSB*DX/1000. 
  
        ENDIF 
  
  
10000 CONTINUE
C-----END OF MAIN TIME EXTRAPOLATION LOOP 
  
 9001 FORMAT ('1', 2X, 'TIME : ', F7.1, ' YRS', / 
     1  3X,'GRID',5X,'CLAT',3X,'DISTANCE',18X,'HEIGHT',19X,'DEPTH', 
     2  18X,'THICKNESS',/,3X,'POINT',4X,'DEGS',6X,'KM', 
     3  3(24X,'M')) 
  
 9002 FORMAT (3X,I3,6X,F4.1,3X,F8.3,3(5X,F20.10)) 
  
 9003 FORMAT (18(10(1X,I6),/))
  
 9004 FORMAT (E25.12) 
  
 9005 FORMAT (E20.12) 
  
 9008 FORMAT (11F8.2) 
      END 
