/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>


#define DATE_PROG ((u_long)0x31234567)
#define DATE_VERS ((u_long)1)
#define BIN_DATE ((u_long)1)
extern long *bin_date_1();
#define STR_DATE ((u_long)2)
extern char **str_date_1();
