      SUBROUTINE SPNORM(JGG,AVG,AVN,AVS,IB,IC)
      COMMON W(46,50) 
      COMMON/MINOR/NMINOR,JFM,JDUM(25)
      COMMON/CONST/M,MM,MP,MPP,N,DUM(42)
      COMMON/SPNCOM/MPSPN,SPN(3,3,2)
      REAL GG(46) 
      IF (MP.NE.MPSPN)CALL SPSET
C     JGG IS THE POINTER TO THE FIELD TO BE AVERAGED. 
C     PRODUCES VARIOUS SURFACE INTEGRALS ON A SPHERE
C     USING FM(LAND FRACTION) 
C     IB=1  BOTH LAND AND OCEAN 
C     IB=2  LAND
C     IB=3  OCEAN 
C     IC=1  NON-REAL WEIGHTS
C     IC=2  WEIGHTS HAVE REALS OF AREA
C             (IF JGG IS HEIGHT THIS GIVES VOLUME)
C     AVG GLOBAL
C     AVN NORTHERN HEMISPHERE 
C     AVS SOUTHERN HEMISPHERE 
      IF (IB.EQ.1) THEN 
        CALL SPHERE(JGG,AVG,AVN,AVS)
       ELSEIF (IB.EQ.2) THEN
         CALL SPLAND(JGG,AVG,AVN,AVS,JFM) 
        ELSE
         CALL SPSEA(JGG,AVG,AVN,AVS,JFM)
      ENDIF 
      AVG=AVG*SPN(1,IB,IC)
      AVN=AVN*SPN(2,IB,IC)
      AVS=AVS*SPN(3,IB,IC)
      RETURN
      END 
