#!/bin/ksh
base=9901

dy=01
count=0

CC=19
export CC base

set -x
while [ $dy -le 31 ] 
do
  count=`expr $count + 1`
  time ./ibm.sh ${base}$dy  > ${base}$dy 2> ${base}${dy}.2
  if [ $count -ge 4 ] ; then
    sync
  fi
  dy=`expr $dy + 1`
  if [ $dy -lt 10 ] ; then
    dy=0$dy
  fi
done
  
