#!/bin/ksh

#set -x
if [ $# -lt 1 ] ; then
  echo Fatal -- no month argument!
  exit -1
fi

HARDSTART=no
CC=19
TAROP=
#     TAROP is used for high resolution model versions, to compress on fly
#     The if test is used for very high resolution model version, to get
#        just the last fcst, valid 00Z next day.
ANUDGE=0.5     #Ice concentration nudging for 00Z
OFFNUDGE=0.00  #Ice concentration nudging for off times
export CC TAROP HARDSTART ANUDGE OFFNUDGE

base=$1
for base in 9901 9902 9903
do
  if [ $base -eq 9902 ] ; then
    HARDSTART=no
  fi

if [ -f /etc/linux ] ; then
  FBASE=/home/rmg3/icemodel/icemodel/forcing/${base}
  SSDIR=/home/rmg3/icemodel/icemodel/ssmi
  EXDIR=/home/rmg3/icemodel/icemodel/execs
  REFDIR=/home/rmg3/icemodel/icemodel/running
  RUNDIR=/data/forecasts/new/icetest
  OUTBASE=$RUNDIR
  HINDBASE=$RUNDIR/hind
  PATH=$PATH:/usr/local/bin/netpbm
  LANDDIR=/home/rmg3/ssmi/land
else
#Assumed to be ibm for now
  RUNDIR=/tmp/wd21rg
  FBASE=/u/wx21rg/icemodel/icemodel/forcing/${base}
  EXDIR=/u/wx21rg/icemodel/icemodel/execs
  REFDIR=/u/wx21rg/icemodel/icemodel/running
  SSDIR=/u/wx21rg/icemodel/icemodel/ssmi
  LANDDIR=/u/wx21rg/icemodel/land
  OUTBASE=/u/wx21rg/iceout2
  HINDBASE=/u/wx21rg/iceout2/hind
fi

#Nothing below this point should need changing -------------------------
#set -x
export tag tagm mm mdy RUNDIR REFDIR EXDIR OUTBASE FBASE HINDBASE SSDIR LANDDIR

tag=${base}01
tagm=`expr $tag - 1`
tagm=`dtgfix3 $tagm`
mm=`echo $tag | cut -c3-4`
#if [ $mm -eq 1 -o $mm -eq 3 -o $mm -eq 5 -o $mm -eq 7 -o $mm -eq 8 \
if [ $mm -eq 1 -o -o $mm -eq 5 -o $mm -eq 7 -o $mm -eq 8 \
                -o $mm -eq 10 -o $mm -eq 12 ] ; then
  mdy=31
else 
  if [ $mm -eq 09 -o $mm -eq 11 -o $mm -eq 04 ] ; then
    mdy=30
  elif [ $mm -eq 03 ] ; then
    mdy = 17
  else
    mdy=28
  fi
fi

echo mday = $mdy

for d in $RUNDIR $OUTBASE $HINDBASE
do
  if [ ! -d $d ] ; then
    mkdir -p $d
  fi
done
 
if [ ! -d $REFDIR ] ; then
  echo Cannot find the reference directory.  Cannot run.
  exit -1
fi 
if [ ! -d $EXDIR ] ; then
  echo Cannot find the executables directory.  Cannot run.
  exit -1
fi
if [ ! -d $SSDIR ] ; then
  echo Cannot find the SSMI directory.  Cannot run.
  exit -1
fi 

cd $RUNDIR

# Set up a restart file with initial ice thicknesses + concentrations
#Change arg list to sst, conc, restart, concweight, sstweight, hthick
#  restart = true means run from restart file
#
#set -x
if [ $HARDSTART = 'yes' ] ; then
  for pole in north south 
  do
    export pole
    OUTDIR=$OUTBASE/$pole
    export OUTDIR
    echo About to try to run the ic checker, $pole
    $EXDIR/ic.sh .TRUE. .TRUE. .FALSE.  $ANUDGE 0.5 0.5
    cp $OUTBASE/$pole/restart.$pole $HINDBASE/$pole
  done
fi
#exit

while [ $tag -le ${base}${mdy} ] 
#while [ $tag -le ${base}16 ] 
do
  export tag tagm
  for pole in north south 
  do
    cd $RUNDIR
    OUTDIR=$OUTBASE/$pole
    export pole OUTDIR
    rm *
  #Make sure the stossel model is here
    if [ ! -s stossel.${pole}.6 ] ; then
      cp ${EXDIR}/stossel.${pole}.6 .
    fi
    
    # the f option means force the link.  i.e., do it even if the file
    #  already exists
    ln -sf  ${REFDIR}/${pole}/MASK .
    ln -sf  ${REFDIR}/${pole}/tsdeep .
    ln -sf  ${REFDIR}/${pole}/tsshal .
    ln -sf  ${REFDIR}/${pole}/bathy.$pole bathy

  #If the hindcast stage has run, use that.  Otherwise, run from the
  #  last restart file present here
    if [ ! -d $HINDBASE/$pole ] ; then
      mkdir -p $HINDBASE/$pole 
    fi
    if [ -s $HINDBASE/$pole/restart.$pole ] ; then
      cp $HINDBASE/$pole/restart.$pole $OUTBASE/$pole
      echo working from restart file
     else
      echo Failed to find a hindcast restart file! 
      $EXDIR/ic.sh .TRUE. .TRUE. .FALSE.  0.875 0.5 0.6
      cp restart.$pole $OUTBASE/$pole
    fi  
  
    #Collect the forecast files
    for time in 00 06 12 18
    do
  
      # if there is not already a met file, create it.  If there is, link to it.
      if [ ! -s ${FBASE}/met.${pole}.${tag}${time} ] ; then
        #${EXDIR}/met.jcl ${FBASE}/${CC}${tag}${time}.fx6 
        ${EXDIR}/met.jcl ${FBASE}/flxf06.${CC}${tag}${time}
        cp metout.${pole} ${FBASE}/met.${pole}.${tag}$time 
        tagm2=`expr $tagm - 1`
        tagm2=`dtgfix3 $tagm2`
        if [ -s met.${pole}.${tagm}$time ] ; then
          ln -s met.${pole}.${tagm}$time metout
          cp met.${pole}.${tagm}$time $FBASE
        else 
          if [ -s met.${pole}.${tagm2}$time ] ; then
            ln -s met.${pole}.${tagm2}$time metout
            cp met.${pole}.${tagm2}$time $FBASE
          else 
            time ${EXDIR}/met.jcl ${FBASE}/${CC}${tag}${time}.fx6
            cp metout.${pole} met.${pole}.${tag}$time
            cp met.${pole}.${tag}$time $FBASE
            mv metout.${pole} metout
          fi
        fi
      else
        if [ -s metout ] ; then
          rm metout
        fi
        ln -s ${FBASE}/met.${pole}.${tag}$time metout
      fi
  
      chmod 644 metout
  
    #  set -x
      if [ -s $OUTBASE/$pole/restart.$pole ] ; then
        # Order is: concentration, SST, Restart file present
        if [ $time -eq 00 ] ; then
          echo calling time zero ic check
          $EXDIR/ic.sh .TRUE. .TRUE. .TRUE.  $ANUDGE 0.25 0.1
        else
          echo calling off time ic check
          $EXDIR/ic.sh .TRUE. .TRUE. .TRUE.  $OFFNUDGE 0.25 0.1
        fi
        cp $OUTBASE/$pole/restart.$pole RESTARTo
        echo ${REFDIR}/${pole}/runparm.${pole} > runin
       else
        touch RESTARTo
        echo calling in-line ic check and restart generation
        $EXDIR/ic.sh .TRUE. .TRUE. .FALSE.  0.875 0.5 0.1
        echo ${REFDIR}/${pole}/runzero.${pole} > runin
      fi
  
    #Note the following addition to distinguish between hindcast (6 hrs) and
    # forecast (12 hour dt) versions.  Inelegant.
      time ./stossel.${pole}.6 < runin
    
    #Fields for general use, to be overwritten
      cp conc     $OUTBASE/$pole/conc.$pole.$tag$time
      cp RESTARTn $OUTBASE/$pole/restart.$pole
      cp RESTARTn $OUTBASE/$pole/$tag/restart.$pole
      mv RESTARTn $HINDBASE/$pole/restart.$pole
  
    #Fields for archival
      if [ ! -d $OUTBASE/$pole ] ; then
        mkdir $OUTBASE/$pole
      fi
      FDIR=$OUTBASE/$pole/${tag}
      if [ ! -d $FDIR ] ; then
        mkdir $FDIR
      fi
#      if [ $time -eq 18 ] ; then
      tar c${TAROP}vf $FDIR/f$time.tar${TAROP} $HINDBASE/$pole/restart.$pole \
                               thick conc vels \
                               atm.flux oce.flux \
                               hml sml tml FORT.16 FORT.18 
#      fi
      rm  thick conc vels atm.flux oce.flux \
                           hml sml tml FORT.16 FORT.18

      done
    #above finishes run through time for a specific region
  
      cd $OUTBASE/$pole
      if [ -s $OUTBASE/$pole/conc.$pole.${tag}168 ] ; then
        if [ -s $OUTBASE/$pole/conc.$pole.${tagm}168 ] ; then
          rm $OUTBASE/$pole/conc.$pole.${tagm}?? 
          rm $OUTBASE/$pole/conc.$pole.${tagm}???
        fi
      fi

    done
  
    #finished all regions
    tagm=$tag
    tag=`expr $tag + 1`
    tag=`dtgfix3 $tag`

done 

done #Multiple months
