      DATA aadept(1) /3600./
      DATA nadept(1) /2600./
      DATA iwdept(1) /1600./
      DATA aasour(1) / 850./
      DATA nasour(1) / 650./
      DATA iwsour(1) / 850./

      DATA aadept(2) /3600./
      DATA nadept(2) /2600./
      DATA iwdept(2) /1600./
      DATA aasour(2) / 850./
      DATA nasour(2) / 650./
      DATA iwsour(2) / 850./

      DATA aadept(3) /3600./
      DATA nadept(3) /2600./
      DATA iwdept(3) /1600./
      DATA aasour(3) / 850./
      DATA nasour(3) / 650./
      DATA iwsour(3) / 850./
