C     Chronology
      table( 1,ptime) = -20700.0
      table( 2,ptime) = -19550.0
      table( 3,ptime) = -18400.0
      table( 4,ptime) = -17250.0
      table( 5,ptime) = -16100.0
      table( 6,ptime) = -14950.0
      table( 7,ptime) = -13800.0
      table( 8,ptime) = -12650.0
      table( 9,ptime) = -11500.0
      table(10,ptime) = -10350.0
      table(11,ptime) = - 9200.0
      table(12,ptime) = - 8050.0
      table(13,ptime) = - 6900.0
      table(14,ptime) = - 5750.0
      table(15,ptime) = - 4600.0
      table(16,ptime) = - 3450.0
      table(17,ptime) = - 2300.0
      table(18,ptime) = - 1150.0
      table(19,ptime) = - 0000.0
      table(20,ptime) = + 1000.0
      
C     NADW Flux through time, in m3/s
      table( 1,pfna ) = 00.E6 ! values from 17 to 0 are derived
      table( 2,pfna ) = 11.3E6 !   from Keir 1990, combined with
      table( 3,pfna ) = 11.35E6 !   Grumbine 1991 in prep expts.
      table( 4,pfna ) = 11.4E6
      table( 5,pfna ) = 10.8E6
      table( 6,pfna ) = 10.21E6
      table( 7,pfna ) = 10.59E6
      table( 8,pfna ) = 11.38E6
      table( 9,pfna ) = 11.25E6
      table(10,pfna ) = 11.13E6
      table(11,pfna ) = 11.65E6
      table(12,pfna ) = 12.18E6
      table(13,pfna ) = 14.12E6
      table(14,pfna ) = 16.07E6
      table(15,pfna ) = 16.46E6
      table(16,pfna ) = 16.84E6
      table(17,pfna ) = 17.23E6
      table(18,pfna ) = 17.62E6
      table(19,pfna ) = 18.0E6
      table(20,pfna ) = 18.E6

C     AABW Flux through time, in m3/s
      table( 1,pfaa ) = 0.E6
      table( 2,pfaa ) = 28.75E6  !expt
      table( 3,pfaa ) = 27.31E6  
      table( 4,pfaa ) = 25.86E6  !expt
      table( 5,pfaa ) = 23.16E6 
      table( 6,pfaa ) = 20.46E6  !expt
      table( 7,pfaa ) = 16.99E6
      table( 8,pfaa ) = 13.52E6  !expt
      table( 9,pfaa ) = 10.77E6
      table(10,pfaa ) = 8.03E6  !expt
      table(11,pfaa ) = 7.28E6
      table(12,pfaa ) = 6.53E6  !expt
      table(13,pfaa ) = 6.55E6
      table(14,pfaa ) = 6.56E6
      table(15,pfaa ) = 6.5E6
      table(16,pfaa ) = 6.5E6
      table(17,pfaa ) = 6.6E6
      table(18,pfaa ) = 6.6E6
      table(19,pfaa ) = 6.65E6  !expt
      table(20,pfaa ) = 6.65E6

