      INTEGER He, Ne, N2, O2, Ar, Kr, Xe, CO2, N2O
      PARAMETER (He  = 1)
      PARAMETER (Ne  = 2)
      PARAMETER (N2  = 3)
      PARAMETER (O2  = 4)
      PARAMETER (Ar  = 5)
      PARAMETER (Kr  = 6)
      PARAMETER (Xe  = 7)
      PARAMETER (CO2 = 8)
      PARAMETER (N2O = 9)
      INTEGER temp, salt, NO3, PO4, SiO2, dc14, tco2, alk
      PARAMETER (temp = 10)
      PARAMETER (salt = 11)
      PARAMETER (NO3  = 12)
      PARAMETER (PO4  = 13)
      PARAMETER (SiO2 = 14)
      PARAMETER (dc14 = 15)
      PARAMETER (tco2 = 16)
      PARAMETER (alk  = 17)

      INTEGER nchem
      PARAMETER (nchem = 17)