# Note that compiling with VERBOSE will provide substantial debugging output,
#   and VERBOSE2 will give an enormous amount.
# Robert Grumbine 19 August 2003
# -- directory path updates 23 Dec 2015

#IBM
CC=xlC
CFLAGS=-DIBM -O2 
#-pg 
#-DVERBOSE 
#-DVERBOSE2 
INCDIR=shorelines -Immab.include

#LINUX
CC=g++
#Flip is necessary for GMT shorelines running on linux
#CFLAGS=-Wall -DLINUX -O2 -DFLIP 
#  .. and necessarily must be removed for files you derive on the same platform
CFLAGS=-Wall -DLINUX -O2 
INCDIR=/usr1/allbathy/shorelines/ -I ~/svn/mmab/v3.4.2/include
LIBS=~/svn/mmab/v3.4.2/libombf_4.a


#Common
#  these should be exported by the calling script 
#FAMILY=resops
#TARGET=hycom
#If you want a resops grid, you must also export RESOPS=1
#LOW=low resolution grid if you're using telescope

# No changes below here -------------------------------------------
all : refill bathy paving

toab : toab.C makefile
	$(CC) $(CFLAGS) toab.C -DTARGET=$(TARGET) -I$(INCDIR) -o toab $(LIBS)

refill : refill.C geometry.C makefile
	$(CC) $(CFLAGS) refill.C -DFAMILY=$(FAMILY) -DRESOPS=$(RESOPS) -DTARGET=$(TARGET) -I$(INCDIR) -o refill $(LIBS)

bathy : bathy.C
	$(CC) $(CFLAGS) bathy.C -DRESOPS=$(RESOPS) -DTARGET=$(TARGET) -I$(INCDIR) -o bathy $(LIBS)

paving : paving.C geometry.C
	$(CC) $(CFLAGS) paving.C -DRESOPS=$(RESOPS) -DTARGET=$(TARGET) -DFAMILY=$(FAMILY) -I$(INCDIR) -o paving $(LIBS)

telescope : telescope.C geometry.C makefile
	$(CC) $(CFLAGS) telescope.C -DFAMILY=$(FAMILY) -DRESOPS=$(RESOPS) -DTARGET=$(TARGET) -DLOW=$(LOW) -I$(INCDIR) -o telescope $(LIBS) 
