#LINUX
CC=g++
CFLAGS=-Wall -DLINUX -O2 -DFLIP 
#-DVERBOSE 
#-DVERBOSE2 
INCDIR=shorelines
#IBM
CC=xlC
CFLAGS=-DIBM -DTRANSFER -O2 
#-pg 
#-DVERBOSE 
#-DVERBOSE2 
INCDIR=../shorelines -I../../include

#Common
TARGET=hycom
FAMILY=resops

# No changes below here -------------------------------------------
all : toab refill bathy paving

toab : toab.C resops2.h makefile
	$(CC) $(CFLAGS) toab.C -DTARGET=$(TARGET) -I$(INCDIR) -o toab

refill : refill.C geometry.C resops2.h makefile
	$(CC) $(CFLAGS) refill.C -DFAMILY=$(FAMILY) -DTARGET=$(TARGET) -I$(INCDIR) -o refill

bathy : bathy.C
	$(CC) $(CFLAGS) bathy.C -DTARGET=$(TARGET) -I$(INCDIR) -o bathy

paving : paving.C
	$(CC) $(CFLAGS) paving.C -DTARGET=$(TARGET) -DFAMILY=$(FAMILY) -I$(INCDIR) -o paving

