      PROGRAM INSOLS

      COMMON/TEMP/INSOL
      REAL INSOL

      REAL LAT
      REAL I, TSTART, TEND, DELTAT, FILSIZE

      COMMON /NORBIT/ AT, AXOB, AECC, APRE, APERH
      REAL AT, AXOB, AECC, APRE, APERH

      INTEGER TOFYR
      INTEGER FIRST, LAST, STEP
      INTEGER JDUM, K 
      REAL PRESVAL, ANOM

      OPEN (UNIT=2,FILE='INSOLS.OUT',STATUS='NEW')
      OPEN (UNIT=5,FILE='JINSOL.J',STATUS='OLD')

      READ (5,9002) TSTART
      READ (5,9002) TEND
      READ (5,9002) DELTAT
      READ (5,9002) LAT 
      READ (5,9003) FIRST 
      READ (5,9003) LAST
      READ (5,9003) STEP
  
C     SUBTRACT THE PRESENT VALUE OF INSOLATION FROM COMPUTED VALUE
C       TO GET ANOMALY. 
      CALL ASTSET(0.0)
      I      = TSTART + DELTAT
      JDUM   = INT((TSTART- TEND)/ DELTAT) + 1
      FILSIZE = (JDUM - 1)/5
      DO 10 K= 1, JDUM
        ANOM = 0.0
        I = I - DELTAT
       DO 100 TOFYR = FIRST, LAST, STEP 
  
        CALL ASTR(0.0)
        CALL YEAR(LAT, TOFYR) 
        PRESVAL = INSOL 
  
        CALL ASTR(-I)
        CALL YEAR(LAT,TOFYR)

C       THE FIRST ARGUMENT IS THE LATITUDE TO COMPUTE FOR
C       THE SECOND IS THE TIME OF YEAR. 1=VERNAL EQUINOX
C         31=THE AUTUMNAL EQUINOX
  
       ANOM = ANOM +INSOL -PRESVAL
  100  CONTINUE
      ANOM = ANOM/FLOAT(((LAST-FIRST)/STEP)+1)
      WRITE (*,9001) ANOM, APRE 
      WRITE (2,9001) ANOM, APRE
      
   10 CONTINUE
  
 9001 FORMAT (2E20.12)
  
 9002 FORMAT (F14.4)
  
 9003 FORMAT (I3) 
  
      END
