#!/bin/sh

yy=1998
for mo in 09 10 11 12
do
  time rcp ncos70bs:/hsmuser/g01/wx21rg/fluxtars/flux.${yy}${mo}.tar nfsb2n05:/emc1/ice/mrf/
done 

yy=1999
for mo in 01 02 03 04 05 06 07 08 09 10 11 12
do
  time rcp ncos70bs:/hsmuser/g01/wx21rg/fluxtars/flux.${yy}${mo}.tar nfsb2n05:/emc1/ice/mrf/
done 


yy=2000
for mo in 01 02 03 04 05 06 07 08 
do
  time rcp ncos70bs:/hsmuser/g01/wx21rg/fluxtars/flux.${yy}${mo}.tar nfsb2n05:/emc1/ice/mrf/
done 

