#!/bin/sh

yy=1998
for mo in 09 10 11 12
do
  if [ ! -f flux.${yy}${mo}.tar ] ; then
    time rcp ncos70bs:/hsmuser/g01/wx21rg/fluxtars/flux.${yy}${mo}.tar /emc1/ice/mrf/
  fi
done 

yy=1999
for mo in 01 02 03 04 05 06 07 08 09 10 11 12
do
  if [ ! -f flux.${yy}${mo}.tar ] ; then
    time rcp ncos70bs:/hsmuser/g01/wx21rg/fluxtars/flux.${yy}${mo}.tar /emc1/ice/mrf/
  fi
done 


yy=2000
for mo in 01 02 03 04 05 06 07 08 
do
  if [ ! -f flux.${yy}${mo}.tar ] ; then
    time rcp ncos70bs:/hsmuser/g01/wx21rg/fluxtars/flux.${yy}${mo}.tar /emc1/ice/mrf/
  fi
done 

