#!/bin/sh

export cmd='cp -p'
if [ $# -ne 0 ] ; then
  export cmd=$*
fi
echo $cmd

for ex in  \
seaice_icegrid.Cd/seaice_icegrid \
seaice_edge.Cd/seaice_edge \
seaice_xpm.Cd/seaice_globalxpm \
seaice_xpm.Cd/seaice_global5minxpm \
seaice_xpm.Cd/seaice_southxpm \
seaice_xpm.Cd/seaice_northxpm \
seaice_reduce.Cd/seaice_global_reduce \
seaice_xpm.Cd/seaice_south12xpm \
seaice_xpm.Cd/seaice_north12xpm \
seaice_blend.Cd/seaice_blend \
seaice_posteriori.Cd/seaice_posteriori_30min.x \
seaice_posteriori.Cd/seaice_posteriori_5min.x \
seaice_reduce.Cd/seaice_south_reduce \
seaice_reduce.Cd/seaice_north_reduce \
seaice_reduce.Cd/seaice_south2_reduce \
seaice_reduce.Cd/seaice_north2_reduce \
seaice_monitor.Cd/seaice_monitor_c12th \
seaice_regions.Cd/seaice_regions.south \
seaice_regions.Cd/seaice_regions.north \
seaice_regions.Cd/seaice_regions.southhigh \
seaice_regions.Cd/seaice_regions.northhigh \
seaice_filtanal.Cd/seaice_filtanal \
seaice_imsice.Cd/imsice \
seaice_noice.Cd/noice \
seaice_ice2grib.fd/seaice_ice2grib \
seaice_ice2grib.fd/seaice_ice2grib5min \
seaice_psgnorth.fd/seaice_psgnorth12 \
seaice_grib2.fd/seaice_grib2 \
seaice_psgsouth.fd/seaice_psgsouth12 \
seaice_psgnorth.fd/seaice_psgnorth \
seaice_psgsouth.fd/seaice_psgsouth 
do
  if [ -f $ex ] ; then
    $cmd $ex ../exec
  else
    echo could not find $ex ERROR
  fi
done

