.f.o:
	pgf90 -c -Mstandard $<

COBJS = sub.o subjohn.2.back.o subjohna.o subjohnb.o subjohn.bg.o subjohnc.o subjohnd.o subjohne.o subjohn.o subjohnf.o subjohng.o subjohn.mean.o subr1.o subr2.o subr3.o subr.o waldrop_mse.o
DOBJS = drift3.o getfcst.19991004.o getfcst6.o getfcst.o matscor.o sk1vs2.o

all : $(COBJS) $(DOBJS)
