      FUNCTION HINTEG(DX,ISNB)
C     THIS FUNCTION PERFORMS A TRAPEZIODAL RULE INTEGRATION FROM
C       ISNB-1 TO ISSB
      IMPLICIT none

      INTEGER MXSB
      PARAMETER (MXSB  = 160) 
      REAL HINTEG, DX, HGT, ACMRAT, SLOPE, TIMELP, OSCARG
      REAL TIMSTP, GRDSTP, SNLAMP, SNLMPT, SNLXIN, TRIPS
      REAL RNETAC, POLFLX, MSNAUT, MAPRIM
      INTEGER ISNB, ISSB, I,H, HP
      LOGICAL OUTDAT
      REAL VOL

      COMMON/ISCOM/HGT(0:MXSB,0:1),H, HP, ACMRAT, SLOPE, TIMELP, OSCARG,
     1    TIMSTP, GRDSTP, SNLAMP, SNLMPT, SNLXIN, TRIPS, RNETAC, POLFLX,
     3    MSNAUT, MAPRIM, OUTDAT, ISSB

      VOL = (HGT(ISNB-1,H)+HGT(ISNB-1,HP))/2.0
      VOL = VOL +(HGT(ISSB,H)+HGT(ISSB,HP))/2.0
      DO 100 I=ISNB,ISSB-1
        VOL = VOL + HGT(I,H)+HGT(I,HP)
 100  CONTINUE
      HINTEG=VOL*DX

      RETURN
      END
