      SUBROUTINE FTSC (A, ST, BUFFER) 
  
C      FOR MORE INFORMATION ABOUT THE FFT COMPUTATIONS, SEE THE 
C        IMSL DOCUMENTATION ON FFTSC. 
C      ALSO SEE BG NOTES FOR 8-15-85 THROUGH 8-19-85. 
      INTEGER MXSB, IWKDIM
      PARAMETER (MXSB    = 160) 
      PARAMETER (IWKDIM  = 3*MXSB+150)
  
      COMPLEX CWK(IWKDIM) 
      REAL CT(IWKDIM),  WK(IWKDIM)
      INTEGER IWK(IWKDIM), I
      REAL BUFFER 
      REAL A(-MXSB-2:MXSB+1), ST(-MXSB-2:MXSB+1)
  
C     COMPUTE THE TRANSFORM OF A, STORE THE COEFFICIENTS IN ST. 
      CALL FFTSC(A, 2*MXSB+4, ST, CT, IWK, WK, CWK) 
      DO 1000 I=1, MXSB+1 
        ST(I)  = ST(-I)/(2.*(2.*MXSB+4))
        ST(-I) =-ST(I)
 1000 CONTINUE
      ST(0)       = 0.0 
      ST(-MXSB-2) = 0.0 
  
      RETURN
  
  
      ENTRY IFTSC(A, ST, BUFFER)
  
C     COMPUTE THE INVERSE TRANSFORM.  IF ANY OF THE COSINE TRANS- 
C       FORM COEFFICIENTS ARE GREATER THAN BUFFER, PRINT A MESSAGE
C       AND STOP THE PROGRAM; IT WILL CRASH SOON ANYHOW.
  
      CALL FFTSC(ST, 2*MXSB+4, A, CT, IWK, WK, CWK) 
      DO 1100 I=1, MXSB+1 
        A(I)  = A(-I)/2.
        A(-I) =-A( I) 
 1100 CONTINUE
      A(0)      = 0.0 
      A(-MXSB-2)= 0.0 
  
      RETURN
      END 
