      SUBROUTINE FFT 192  (A, B, LOT, ISIGN)
      PARAMETER (LOTMIN=64,LOTMAX=64,NCPU=1)
      DIMENSION A( 192 ,LOT)
      DIMENSION B( 192 ,LOT)
C
      DIMENSION WORK( 192 ,LOTMAX,4), AL( 384 ,LOTMAX)
      COMMON /COM 192 /ITEST,JUMP,IFAX(20),TRIGS( 192 ,2)
C
       DATA ITEST/0/
CMIC$ GUARD 21
        IF (ITEST.EQ.0)  THEN
            ITEST=1
            JUMP = 192 *2
            CALL SET777 (TRIGS, IFAX,  192 )
            IF (IFAX(1) .EQ. -99)  PRINT 120
            IF (IFAX(1) .EQ. -99)  STOP
120         FORMAT (' ERROR IN FFT 192 .   192  NOT FACTORABLE. ')
            PRINT 140
140         FORMAT (' SET777 CALLED IN FFT 192 .  LONF =  192  ')
      ENDIF
CMIC$ END GUARD 21
C
C
      IF (ISIGN .EQ.  1)  THEN
C
C  MULTIPLE FAST FOURIER TRANSFORM - SYNTHESIS.  ISIGN=1
C  GOOD FOR ZONAL WAVE NUMBER  62 .
C
C     DIMENSION A( 192 ,LOT)
C
C   INPUT - LOT SETS OF COMPLEX COEFFICIENTS IN
C           A(1,J), A(2,J), ..., A( 63 *2,J), J=1,...,LOT.
C           A( 63 *2+1,J), ..., A( 192 ,J), J=1,...,LOT ARE NOT SET
C           BEFORE CALL FFT 192 .
C
C  OUTPUT - LOT SETS OF GRID VALUES IN
C           A(1,J), A(2,J), ..., A( 192 ,J), J=1,...,LOT.
C
      NLOT=MAX0(LOT/NCPU,LOTMIN)
      NLOT=MIN0(NLOT    ,LOTMAX)
CRAYCMIC$ DO ALL PRIVATE(AL,WORK,LOTS) SHARED(A,TRIGS,IFAX,JUMP) AUTOSCO
      DO 460 I=1,LOT,NLOT
      LOTS = MIN0(NLOT, LOT-I+1)
      DO 360 J=I,I+LOTS-1
      DO 320 L=1, 126
             AL(L,J-I+1) = A(L,J)
320   CONTINUE
      DO 340 L= 127 , 384
             AL(L,J-I+1) = 0.0
340   CONTINUE
360   CONTINUE
C
C     CALL CRAY FFT FOR SYSTHESIS.
      CALL FFT777 (AL,WORK,TRIGS,IFAX,1,JUMP, 192 ,LOTS,1)
C
      DO 440 J=I,I+LOTS-1
      DO 420 L=1, 192
             A(L,J) = AL(L,J-I+1)
420   CONTINUE
440   CONTINUE
460   CONTINUE
C
      ENDIF
C
C
      IF (ISIGN .EQ. -1)  THEN
C
C  MULTIPLE FAST FOURIER TRANSFORM - ANALYSIS.  ISIGN=-1
C  GOOD FOR ZONAL WAVE NUMBER  62 .
C
C     DIMENSION A( 192 ,LOT), B( 192 ,LOT)
C
C   INPUT - LOT SETS OF GRID VALUES IN
C           A(1,J), A(2,J), ..., A( 192 ,J), J=1,...,LOT.
C           A ARRAY IS NOT CHANGED BY SUBROUTINE FFT 192 .
C
C  OUTPUT - LOT SETS OF COMPLEX COEFFICIENTS IN
C           B(1,J), B(2,J), ..., B( 63 *2,J), J=1,...,LOT.
C           B( 63 *2+1,J), ..., B( 192 ,J), J=1,...,LOT ARE NOT SET.
C
      NLOT=MAX0(LOT/NCPU,LOTMIN)
      NLOT=MIN0(NLOT    ,LOTMAX)
CRAYCMIC$ DO ALL PRIVATE(AL,WORK,LOTS) SHARED(A,B,TRIGS,IFAX,JUMP) AUTOS
      DO 660 I=1,LOT,NLOT
      LOTS = MIN0(NLOT, LOT-I+1)
      DO 560 J=I,I+LOTS-1
      DO 520 L=1, 192
             AL(L,J-I+1) = A(L,J)
520   CONTINUE
      DO 540 L= 193 , 384
             AL(L,J-I+1) = 0.0
540   CONTINUE
560   CONTINUE
C
C     CALL CRAY FFT FOR ANALYSIS.
      CALL FFT777 (AL,WORK,TRIGS,IFAX,1,JUMP, 192 ,LOTS,-1)
C
      DO 640 J=I,I+LOTS-1
      DO 620 L=1, 126
             B(L,J) = AL(L,J-I+1)
620   CONTINUE
640   CONTINUE
660   CONTINUE
C
      ENDIF
C
      RETURN
      END
