      SUBROUTINE GAU2L(GAUIN ,IMXIN ,JMXIN ,
     1                 REGOUT,IMXOUT,JMXOUT)
C     LAST MODIFIED 7 April 1994
C
C  INTERPOLATION FROM LAT/LON GRID TO OTHER LAT/LON GRID
C
      DIMENSION GAUIN (IMXIN ,JMXIN )
      DIMENSION REGOUT(IMXOUT,JMXOUT)
C     BG addition 2/25/92.
      INTEGER BGSIZE
      PARAMETER (BGSIZE = 2000)

      DIMENSION GAUL(BGSIZE),REGL(BGSIZE)
      DIMENSION IINDX1(2*BGSIZE)
      DIMENSION IINDX2(2*BGSIZE)
      DIMENSION JINDX1(BGSIZE)
      DIMENSION JINDX2(BGSIZE)
      DIMENSION DDX(2*BGSIZE)
      DIMENSION DDY(BGSIZE)
      SAVE IINDX1, IINDX2, JINDX1, JINDX2, DDX, DDY
      SAVE GAUL, REGL, IFP
C
      DATA IFP/0/
C
      IF(IFP.NE.0) GO TO 111
      IFP=1
C
      CALL GAULAT(GAUL,JMXIN)
      DO 10 J=1,JMXIN
      GAUL(J)=90.-GAUL(J)
   10 CONTINUE
      DPHI=180./FLOAT(JMXOUT-1)
      DO 20 J=1,JMXOUT
      REGL(J)=90.-FLOAT(J-1)*DPHI
   20 CONTINUE
C
      DXIN =360./FLOAT(IMXIN )
      DXOUT=360./FLOAT(IMXOUT)
C
      DO 30 I=1,IMXOUT
      ALAMD=FLOAT(I-1)*DXOUT
      I1=ALAMD/DXIN+1.001
      IINDX1(I)=I1
      I2=I1+1
      IF(I2.GT.IMXIN) I2=1
      IINDX2(I)=I2
      DDX(I)=(ALAMD-FLOAT(I1-1)*DXIN)/DXIN
   30 CONTINUE
C
      J2=1
      DO 40 J=1,JMXOUT
      APHI=REGL(J)
      DO 50 JJ=1,JMXIN
      IF(APHI.LT.GAUL(JJ)) GO TO 50
      J2=JJ
      GO TO 42
   50 CONTINUE
   42 CONTINUE
      IF(J2.GT.2) GO TO 43
      J1=1
      J2=2
      GO TO 44
   43 CONTINUE
      IF(J2.LE.JMXIN) GO TO 45
      J1=JMXIN-1
      J2=JMXIN
      GO TO 44
   45 CONTINUE
      J1=J2-1
   44 CONTINUE
      JINDX1(J)=J1
      JINDX2(J)=J2
      DDY(J)=(APHI-GAUL(J1))/(GAUL(J2)-GAUL(J1))
   40 CONTINUE
C
CBG      PRINT *,'IINDX1'
CBG      PRINT *,(IINDX1(N),N=1,IMXOUT)
CBG      PRINT *,'IINDX2'
CBG      PRINT *,(IINDX2(N),N=1,IMXOUT)
CBG      PRINT *,'JINDX1'
CBG      PRINT *,(JINDX1(N),N=1,JMXOUT)
CBG      PRINT *,'JINDX2'
CBG      PRINT *,(JINDX2(N),N=1,JMXOUT)
CBG      PRINT *,'DDY'
CBG      PRINT *,(DDY(N),N=1,JMXOUT)
CBG      PRINT *,'DDX'
CBG      PRINT *,(DDX(N),N=1,JMXOUT)
C
  111 CONTINUE
C
CD      PRINT *,'Reached point of computing output fields'
      DO 60 J=1,JMXOUT
      Y=DDY(J)
      J1=JINDX1(J)
      J2=JINDX2(J)
CD      PRINT *,'I1, i2, j1, j2 ', I1, I2, J1, J2, X, Y
      DO 60 I=1,IMXOUT
      X=DDX(I)
      I1=IINDX1(I)
      I2=IINDX2(I)
CD      PRINT *,'I1, i2, j1, j2 ', I1, I2, J1, J2, X, Y
      REGOUT(I,J)=(1.-X)*(1.-Y)*GAUIN(I1,J1)+(1.-Y)*X*GAUIN(I2,J1)+
     1           (1.-X)*Y*GAUIN(I1,J2)+X*Y*GAUIN(I2,J2)
   60 CONTINUE
C
CD      PRINT *,'Reached 70 loop'
      SUM1=0.
      SUM2=0.
      DO 70 I=1,IMXIN
      SUM1=SUM1+GAUIN(I,1)
      SUM2=SUM2+GAUIN(I,JMXIN)
   70 CONTINUE
      SUM1=SUM1/FLOAT(IMXIN)
      SUM2=SUM2/FLOAT(IMXIN)
C
CD      PRINT *,'Reached 80 loop'
      DO 80 I=1,IMXOUT
      REGOUT(I,     1)=SUM1
      REGOUT(I,JMXOUT)=SUM2
   80 CONTINUE
C
      RETURN
      END
