      FUNCTION RNEWRAP(ALPHA, A,DNEW, MV, BETA) 
C     Robert Grumbine 1985.
  
      REAL ALPHA, A, D, MV, RNEWRAP, DNEW 
      INTEGER I, MAXIT
      REAL RELCHA, FOFD, FPOFD
  
      ALPHA=ALPHA*A 
      I    =0 
      MAXIT=10
      RELCHA=.01
  
 100  CONTINUE
  
        D=DNEW
        FOFD =ALPHA*D+5.*LOG10(D)-MV-5.+BETA
        FPOFD=ALPHA+5.*LOG10(EXP(1.))/D 
        DNEW =D-FOFD/FPOFD
  
        I=I+1 
      IF (I.LT.MAXIT.AND.(DNEW-D)/DNEW.GT.RELCHA) GOTO 100
      RNEWRAP=DNEW
      IF (I.EQ.MAXIT) WRITE (2,9001) D, DNEW
 9001 FORMAT (" NEWTON APPROX. TO DISTANCE STOPPED BY ITERATION LIMIT.
     1 THE LAST TWO ESTIMATES WERE:",2E20.10) 
  
      RETURN
      END
