
rot :
	ncepxlf rot.f -O2 -lessl -lm -o rot
vtopo :
	ncepxlf vtopo.f -O2 -lessl -lm -o vtopo
topo :
	ncepxlf topo.f -O2 -lessl -lm -o topo
eigen2 :
	ncepxlf eigen2.f -O2 -lessl -lm -o eigen2
eigen :
	ncepxlf eigen.f -O2 -lessl -lm -o eigen
