#Robert Grumbine 27 May 2016
SHELL=/bin/sh
        
# include ../makeall.mk
#work
#MMAB_LIB=-L/u/Robert.Grumbine/rgdev/mmablib/v3.5.0/
#MMAB_INC=-I/u/Robert.Grumbine/rgdev/mmablib/v3.5.0/include
#module load NetCDF
#module load bufr w3nco w3emc
NCEPLIB=$(BUFR_LIB4) $(W3EMC_LIB4) $(W3NCO_LIB4)
FC=ifort
#FOPTS=-c -std90 -O2 $(MMAB_INC)
FOPTS=-c -O2 $(MMAB_INC)

#home:
##MMAB_LIB=-L/Volumes/ncep/mmablib/v3.5.0/
##MMAB_INC=-I/Volumes/ncep/mmablib/v3.5.0/include
#NETCDF_INCLUDE=-I /Users/rmg3/usrlocal/include/
#NETCDF_LDFLAGS_C=-L /Users/rmg3/usrlocal/lib/
#NCEPLIB=/Volumes/ncep/nceplibs/*4.a
#FC=gfortran

#FOPTS=-c -std=f95 -O2 $(MMAB_INC) $(NETCDF_INCLUDE)
FOPTS=-c -O2 $(MMAB_INC) $(NETCDF_INCLUDE) 

#all -- makeall.mk suitable:  
LIBS=$(MMAB_LIB) -lombc_4 -lombf_4 -lm
CPP=g++
#CPPOPTS= -c -ansi -Wall -O2 -DLINUX -DCPLUS $(MMAB_INC)
CPPOPTS= -c -O2 -DLINUX -DCPLUS $(MMAB_INC) $(NETCDF_INCLUDE)
CPPLD=g++
CPPLDFLAGS=-lombf_4 -lombc_4

CC=gcc
#COPTS=-c -Wall -O2 -DLINUX $(MMAB_INC)
COPTS=-c -Wall -ansi -O2 -DLINUX $(MMAB_INC) $(NETCDF_INCLUDE)

#Building elements
%.o: %.C
	$(CPP) $(CPPOPTS) $< -o $(@)
%.o: %.c
	$(CC) $(COPTS) $< -o $(@)

%.o: %.f
	$(FC) $(FOPTS) $< -o $(@)
%.o: %.F
	$(FC) $(FOPTS) $< -o $(@)
%.o: %.F90
	$(FC) $(FOPTS) $< -o $(@)



#Should be no changes below this point---------------------------------

all : ssmis_tol2 bayes demo 

bayes : bayes.o
	g++ $< $(LIBS) -o $(@)

demo : demo.o
	g++ $< $(LIBS) -o $(@)

ssmis_tol2 : algorithm.o filter.o bufr.o skel.o ssmisu_decode.o
	$(FC) ssmisu_decode.o filter.o skel.o bufr.o algorithm.o  $(NETCDF_LDFLAGS_C) -lnetcdf  $(NCEPLIB) $(LIBS) -o $(@)


# ---------------------------------------------------------------------

clean :
	rm *.o

distclean : clean
	rm ssmis_tol2 bayes demo
