#! /bin/csh -x
#
# Script Name: cfscon-subsfc-init
#
# Purpose: Convert postscript files to gif format
#
# 5/23/96   JK  Add code for converting ship INITIAL ps files to gif files 
#
# Note:  Script executed remotely via remsh to polar via rsh to hp20
# ------------------------------------------------------------------------------
# Forecast PS PLOT Files 
/usr/local/bin/netpbm/pstogif /data/WWW/develop/cfs/ecofs-TBz-olndr-init.ps -page letter -rotate -90
#/usr/local/bin/netpbm/pstogif /data/WWW/develop/cfs/ecofs-TBz-shngstr-init.ps -rotate -90
#
# 
