#!/bin/ksh

COFSOUT=/dm/wd21rg/otis.cofs.z/
OTISIN=/dm/wd21rg/otis.grib/
export COFSOUT OTISIN
if [ ! -d $COFSOUT ] ; then
  mkdir -p $COFSOUT
fi

EXDIR=$HOME41/cpp
DATADIR=$HOME41/cfs.data
export EXDIR DATADIR

#tag=`date +"%y%m%d"`
tag=$1
echo $tag
base=`echo $tag | cut -c1-4`
dy=`echo $tag | cut -c5-6`

if [ ! -d /tmp/otis ] ; then
  mkdir -p /tmp/otis
fi
cd /tmp/otis
rm *

cp $EXDIR/hotis2 hotis
cp $DATADIR/* .
x=`ls -1 *gz  |wc -l`
if [ $x -gt 0 ] ; then
  gunzip *gz
fi
x=`ls -1 *Z | wc -l`
if [ $x -gt 0 ] ; then
  uncompress *Z
fi

if [ -f $OTISIN/otis.${tag}.grib ] ; then
  wgrib $OTISIN/otis.${tag}.grib > index
else
  echo No grib file for $tag
  exit -1
fi
#set -x

for level in 1 3 8 13 18 25 33 40 50 63 75 100 125 150 200 300 400 500 600 \
             700 800 900 1000 1100 1500 1750 2000 2500 3000 4000 5000
do
  x=`grep "kpds7=${level}:" index | grep TMP | wc -l`
  y=`grep "kpds7=${level}:" index | grep SALTY | wc -l`
  
    if [ $x -eq 1 ] ; then
      grep "kpds7=${level}:" index | grep TMP | wgrib $OTISIN/otis.${tag}.grib -i -o tmp.$level -nh > /dev/null
      ./hotis tmp.$level tmp $level
     else
      echo Should have found 1 field for level $level Temperatures, found $x
      echo cannot retrieve this for later use.  Create a dummy level.
    fi
  
    if [ $y -eq 1 ] ; then
      grep "kpds7=${level}:" index | grep SALTY | wgrib $OTISIN/otis.${tag}.grib -i -o salt.$level -nh > /dev/null
      ./hotis salt.$level salt $level
     else
      echo Should have found 1 field for level $level Salinities, found $y
      echo cannot retrieve this for later use.  Create a dummy level.
    fi
  
done

tar cvf $COFSOUT/otis.cofs.z.$tag.tar cfsout.*.* 

