#FC = cf77 -c -Zp 
#LD = cf77 -l prof -Zp
FC = cf77 -c 
LD = cf77 -l prof 
OTHDIR = /wd2/wd21/wd21rg/others
SDIR = /wd2/wd21/wd21rg/stossel/source

IO = FORFLD.o INITREL.o getflx.o INIT.o twoget.o output.o \
     DRUCKF.o BCSINIT.o thregt.o terp.o w3ft32.o
DYNAM = BCOEF.o DDX.o MADV.o OUTBCS.o RELAX.o RELCON.o STRAIN.o BCSFLX.o \
     PLAST.o PRESSB.o
THERM = ADJUEX.o GROWTH.o BUDGET.o OBUDGET.o ECMBUDI.o ECMBUDO.o EKMAH.o \
     EKMAO.o PMLEX.o RESIST.o STAB.o VAPOR.o RISTAB.o RWSTAB.o VERDIF.o
MISC = SDIFFUS.o SHDEF.o SADVECT.o OUTSM.o BCSV.o BCSH.o VECMAXC.o \
     VECMAX.o 


OBJ = ICEMODEL.o \
$(IO) \
$(DYNAM) \
$(THERM) \
$(MISC)

OTHERS = w3ai08.o GAU2L.o SPHERT.o w3fa09.o EQUALLAT.o GAULAT.o GAUSSLAT.o \
  BSSLZ1.o LEGENDRE.o

stossel : incs $(OBJ) $(OTHERS) \
	icegrid.inc mgrid.inc physical.inc rheology.inc oml.inc
	$(LD) $(OBJ) $(OTHERS) \
         -l/nwprod/w3lib -o stossel

radcomp : incs radcomp.o VAPOR.o getflx.o $(OTHERS) 
	$(LD) radcomp.o VAPOR.o getflx.o $(OTHERS) \
             -l/nwprod/w3lib -o radcomp
         
clean   :
	rm *.o */*.inc

incs    : icegrid.inc mgrid.inc physical.inc rheology.inc oml.inc
	cp *.inc $(SDIR)/io
	cp *.inc $(SDIR)/dynam
	cp *.inc $(SDIR)/misc
	cp *.inc $(SDIR)/therm

#Original stossel parts (output having been pulled bodily from ICEMODEL)
ICEMODEL.o : ICEMODEL.f icegrid.inc physical.inc rheology.inc oml.inc
	$(FC) ICEMODEL.f 

radcomp.o : radcomp.f icegrid.inc physical.inc mgrid.inc
	$(FC) radcomp.f

# IO routines
twoget.o : $(SDIR)/io/twoget.f icegrid.inc mgrid.inc physical.inc
	$(FC) $(SDIR)/io/twoget.f
getflx.o : $(SDIR)/io/getflx.f mgrid.inc
	$(FC) $(SDIR)/io/getflx.f
FORFLD.o   : $(SDIR)/io/FORFLD.f icegrid.inc physical.inc
	$(FC) $(SDIR)/io/FORFLD.f
INITREL.o  : $(SDIR)/io/INITREL.f icegrid.inc
	$(FC) $(SDIR)/io/INITREL.f 
INIT.o     : $(SDIR)/io/INIT.f icegrid.inc physical.inc rheology.inc oml.inc
	$(FC) $(SDIR)/io/INIT.f 
output.o : $(SDIR)/io/output.f icegrid.inc
	$(FC) $(SDIR)/io/output.f 
BCSINIT.o : $(SDIR)/io/BCSINIT.f icegrid.inc 
	$(FC) $(SDIR)/io/BCSINIT.f
DRUCKF.o  : $(SDIR)/io/DRUCKF.f
	$(FC) $(SDIR)/io/DRUCKF.f
thregt.o  : $(SDIR)/io/thregt.f icegrid.inc mgrid.inc physical.inc
	$(FC) $(SDIR)/io/thregt.f
terp.o  : $(SDIR)/io/terp.f icegrid.inc mgrid.inc
	$(FC) $(SDIR)/io/terp.f
w3ft32.o  : $(SDIR)/io/w3ft32.f
	$(FC) $(SDIR)/io/w3ft32.f

# Dynamics
BCOEF.o    : $(SDIR)/dynam/BCOEF.f icegrid.inc
	$(FC) $(SDIR)/dynam/BCOEF.f 
PLAST.o    : $(SDIR)/dynam/PLAST.f icegrid.inc rheology.inc
	$(FC) $(SDIR)/dynam/PLAST.f 
PRESSB.o    : $(SDIR)/dynam/PRESSB.f icegrid.inc rheology.inc
	$(FC) $(SDIR)/dynam/PRESSB.f 
DDX.o      : $(SDIR)/dynam/DDX.f icegrid.inc
	$(FC) $(SDIR)/dynam/DDX.f 
MADV.o     : $(SDIR)/dynam/MADV.f icegrid.inc
	$(FC) $(SDIR)/dynam/MADV.f 
STRAIN.o   : $(SDIR)/dynam/STRAIN.f icegrid.inc
	$(FC) $(SDIR)/dynam/STRAIN.f 
OUTBCS.o   : $(SDIR)/dynam/OUTBCS.f icegrid.inc
	$(FC) $(SDIR)/dynam/OUTBCS.f 
BCSFLX.o   : $(SDIR)/dynam/BCSFLX.f icegrid.inc 
	$(FC) $(SDIR)/dynam/BCSFLX.f
RELAX.o    : $(SDIR)/dynam/RELAX.f icegrid.inc rheology.inc
	$(FC) $(SDIR)/dynam/RELAX.f 
RELCON.o   : $(SDIR)/dynam/RELCON.f icegrid.inc physical.inc
	$(FC) $(SDIR)/dynam/RELCON.f 


#Thermodynamics, air and sea
GROWTH.o   : $(SDIR)/therm/GROWTH.f icegrid.inc physical.inc
	$(FC) $(SDIR)/therm/GROWTH.f 
ECMBUDI.o  : $(SDIR)/therm/ECMBUDI.f icegrid.inc physical.inc
	$(FC) $(SDIR)/therm/ECMBUDI.f 
ECMBUDO.o  : $(SDIR)/therm/ECMBUDO.f icegrid.inc physical.inc
	$(FC) $(SDIR)/therm/ECMBUDO.f 
BUDGET.o   : $(SDIR)/therm/BUDGET.f icegrid.inc physical.inc
	$(FC) $(SDIR)/therm/BUDGET.f 
OBUDGET.o  : $(SDIR)/therm/OBUDGET.f icegrid.inc physical.inc
	$(FC) $(SDIR)/therm/OBUDGET.f 
ADJUEX.o   : $(SDIR)/therm/ADJUEX.f icegrid.inc physical.inc oml.inc
	$(FC) $(SDIR)/therm/ADJUEX.f 
EKMAH.o    : $(SDIR)/therm/EKMAH.f icegrid.inc physical.inc
	$(FC) $(SDIR)/therm/EKMAH.f 
EKMAO.o    : $(SDIR)/therm/EKMAO.f icegrid.inc physical.inc
	$(FC) $(SDIR)/therm/EKMAO.f 
PMLEX.o    : $(SDIR)/therm/PMLEX.f icegrid.inc oml.inc physical.inc
	$(FC) $(SDIR)/therm/PMLEX.f 
STAB.o     : $(SDIR)/therm/STAB.f icegrid.inc
	$(FC) $(SDIR)/therm/STAB.f 
RISTAB.o   : $(SDIR)/therm/RISTAB.f icegrid.inc
	$(FC) $(SDIR)/therm/RISTAB.f 
RWSTAB.o   : $(SDIR)/therm/RWSTAB.f icegrid.inc
	$(FC) $(SDIR)/therm/RWSTAB.f 
VAPOR.o    : $(SDIR)/therm/VAPOR.f icegrid.inc
	$(FC) $(SDIR)/therm/VAPOR.f 
RESIST.o   : $(SDIR)/therm/RESIST.f icegrid.inc
	$(FC) $(SDIR)/therm/RESIST.f 
VERDIF.o   : $(SDIR)/therm/VERDIF.f icegrid.inc 
	$(FC) $(SDIR)/therm/VERDIF.f

# Miscellaneous files?
SHDEF.o    : $(SDIR)/misc/SHDEF.f icegrid.inc rheology.inc
	$(FC) $(SDIR)/misc/SHDEF.f 
SDIFFUS.o  : $(SDIR)/misc/SDIFFUS.f icegrid.inc physical.inc
	$(FC) $(SDIR)/misc/SDIFFUS.f
SADVECT.o  : $(SDIR)/misc/SADVECT.f icegrid.inc
	$(FC) $(SDIR)/misc/SADVECT.f
OUTSM.o    : $(SDIR)/misc/OUTSM.f icegrid.inc
	$(FC) $(SDIR)/misc/OUTSM.f
BCSV.o : $(SDIR)/misc/BCSV.f icegrid.inc
	$(FC) $(SDIR)/misc/BCSV.f
BCSH.o : $(SDIR)/misc/BCSH.f icegrid.inc
	$(FC) $(SDIR)/misc/BCSH.f
VECMAXC.o : $(SDIR)/misc/VECMAXC.f icegrid.inc
	$(FC) $(SDIR)/misc/VECMAXC.f
VECMAX.o  : $(SDIR)/misc/VECMAX.f icegrid.inc
	$(FC) $(SDIR)/misc/VECMAX.f


#Other NMC programs
w3ai08.o : $(OTHDIR)/w3ai08.f
	$(FC) $(OTHDIR)/w3ai08.f

GAU2L.o : $(OTHDIR)/GAU2L.f
	$(FC) $(OTHDIR)/GAU2L.f

SPHERT.o : $(OTHDIR)/SPHERT.f
	$(FC) $(OTHDIR)/SPHERT.f

w3fa09.o : /wd2/wd21/wd21rg/others/w3fa09.f
	$(FC) /wd2/wd21/wd21rg/others/w3fa09.f

EQUALLAT.o : $(OTHDIR)/EQUALLAT.f
	$(FC) $(OTHDIR)/EQUALLAT.f

GAULAT.o : $(OTHDIR)/GAULAT.f
	$(FC) $(OTHDIR)/GAULAT.f

GAUSSLAT.o : $(OTHDIR)/GAUSSLAT.f
	$(FC) $(OTHDIR)/GAUSSLAT.f

LEGENDRE.o : $(OTHDIR)/LEGENDRE.f
	$(FC) $(OTHDIR)/LEGENDRE.f

BSSLZ1.o : $(OTHDIR)/BSSLZ1.f
	$(FC) $(OTHDIR)/BSSLZ1.f

