      SUBROUTINE CULL (IF, FIELD, IMAX, JMAX, KMAX)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    CULL        CREATES 3-D FIELD FROM LOLA STRIP ARRAY
C   PRGMMR: JIM HOKE         ORG: W/NMC22    DATE: 85-03-27
C
C ABSTRACT: CREATES A 3-DIMENSIONAL FIELD FOR THE SPECIFIED
C   VARIABLE FROM THE SIGMA LATITUDE-LONGITUDE STRIPS.
C
C PROGRAM HISTORY LOG:
C   85-03-27  JIM HOKE
C   88-08-01  BRIAN SCHMIDT ADDED THE DOCBLOCK
C
C USAGE:    CALL CULL(IF, FIELD, IMAX, JMAX, KMAX)
C   INPUT ARGUMENT LIST:
C     IF       - FIRST INDICE OF THE LATITUDE-LONGITUDE STRIP
C                ARRAY WHICH WILL BE PUT IN OUTPUT ARRAY 'FIELD'
C     IMAX     - SIZE OF FIRST DIMENSION OF ARRAY 'FIELD'
C     JMAX     - SIZE OF SECOND DIMENSION OF ARRAY 'FIELD'
C     KMAX     - SIZE OF THIRD DIMENSION OF ARRAY 'FIELD'
C
C   OUTPUT ARGUMENT LIST:
C     FIELD    - 3-DIMENSIONAL ARRAY OF SPECIFIED VARIABLE
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C       COMMON   - CONSTS
C
C REMARKS: NEED TO KNOW HOW LAT-LONG STRIP ARRAY IS ORGANIZED
C          COMMON CONSTS CONTAINS THE LAT-LONG STRIP ARRAY
C
C ATTRIBUTES:
C   LANGUAGE: CYBER FORTRAN 77
C   MACHINE:  CYBER 205
C
C$$$
C
      IMPLICIT REAL (A-H, O-Z)
C
C
      INCLUDE 'parmodel'
C
C
      COMMON /CONSTS/ IH, IQ, IT, IU, IV, IZ,
     1                NLAT, LEVH, LEVS, LONF, NSIGSTP,
     2                SLAT( INLAT ), STRIPARA( INSIGSTP ,  INLAT )
C
C       *****   END OF INCLUDED COMMON BLK CONSTS   *****
C
C
      DIMENSION FIELD(IMAX, JMAX, KMAX)
C
      LBLOCK =  0
      IMAXM1 = IMAX - 1
C
      DO 300 J=1,JMAX
         LBLOCK = LBLOCK + 1
         LOC = IF - 1
C
         DO 200 K=1,KMAX
C
            DO 100 I=1,IMAXM1
               LOC = LOC + 1
               FIELD(I, J, K) = STRIPARA(LOC, LBLOCK)
  100       CONTINUE
C
            FIELD(IMAX, J, K) = FIELD(1, J, K)
C
  200    CONTINUE
C
  300 CONTINUE
C
      RETURN
C
      END
