      SUBROUTINE GRDSET (NG, INDEX, MADDRS, IM, JM, XPOL, YPOL,CMU,DLAM)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    GRDSET      SPECIFY THE CONSTANTS FOR GRID NG
C   PRGMMR: JIM HOKE         ORG: W/NMC22    DATE: 85-03-27
C
C ABSTRACT: SPECIFIES THE CONSTANTS FOR GRID NG, NOTE THAT
C   N=1 FOR GRID A, N=2 FOR GRID B, N=3 FOR GRID C, ...
C
C PROGRAM HISTORY LOG:
C   85-03-27  JIM HOKE
C   88-08-02  BRIAN SCHMIDT ADDED THE DOCBLOCK
C
C USAGE:    CALL GRDSET(NG,INDEX,MADDRS,IM,JM,XPOL,YPOL,CMU,DLAM)
C   INPUT ARGUMENT LIST:
C     NG       - SPECIFIES THE GRID TO BE USED
C     INDEX    - FIRST INDICE OF ARRAY IADDRG (WHICH CONTAINS
C                VBL ARRAY ADDRESSES) FOR A SPECIFIC MODEL VARIABLE
C
C   OUTPUT ARGUMENT LIST:
C     MADDRS   - ADDRESS OF SPECIFIC MODEL FIELD AS INDICATED BY
C                NG AND INDEX
C     IM       - NUMBER OF GRID POINTS IN THE X DIRECTION
C     JM       - NUMBER OF GRID POINTS IN THE Y DIRECTION
C     XPOL     - X INDICE OF THE NORTH POLE
C     YPOL     - Y INDICE OF THE NORTH POLE
C     CMU      - GRID INDEX PARAMETER
C     DLAM     - LONGITUDINAL ROTATION PARAMETER
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C       COMMON - CONSTN
C
C REMARKS: NOTE THAT IM AND JM ARE THE NUMBER OF GRID POINTS IN
C   THE X AND Y DIRECTIONS, RESPECTIVELY, AND NOT NECESSARILY
C   THE NUMBER OF POINTS USED DURING THE FORECAST.  FOR
C   INSTANCE, FOR H POINTS, COLUMN I=1 IS NOT USED EVEN AS
C   A BOUNDARY POINT.  ALL POINTS, WHETHER USED IN THE FORECAST
C   OR NOT, ARE INITIALLY DEFINED.  BOUNDARY POINTS ARE THEN
C   OVERWRITTEN AT THE BEGINNING OF THE FORECAST.
C
C ATTRIBUTES:
C   LANGUAGE: CYBER FORTRAN 200
C   MACHINE:  CYBER 205
C
C$$$
C
      IMPLICIT REAL (A-H, O-Z)
C
C
      INCLUDE 'parmodel'
C
C
      LOGICAL  BITSEA, BITSNO, BITWVL
C
      COMMON /CONSTN/ IMG( INGRDUSE ), JMG( INGRDUSE ),
     1                IAG( INGRDUS1 ), JAG( INGRDUS1 ),
     2                IBG( INGRDUS1 ), JBG( INGRDUS1 ),
     3                IADDRG( INIADDRS ,  INGRDUSE ),
     4                INDEXHU,  INDEXHV,  INDEXHTH, INDEXHQ,
     5                INDEXH,   INDEXST,  INDEXSQ,  INDEXALB,
     6                INDEXSLP, INDEXPSI, INDEXCD,  INDEXCC,  INDEXGSP,
     7                INDEXRAD, INDEXDLW, INDEXDSW, INDEXCPR, INDEXMA,
     8                INDEXSEC, INDEXZ0, INDEXTSS,  INDEXCG,  INDEXDHQ,
     9                INDEXTSD, KM, NH, NGRDUSE,
     1                SPECS( INSPECS ), DELSIG( IKM ),
     2                POVH( IKM ), PIOVHK( IKM ),
     3                CMUU  ( INGRDUSE ),
     4                XPOLEH( INGRDUSE ), YPOLEH( INGRDUSE ),
     5                XPOLEU( INGRDUSE ), YPOLEU( INGRDUSE ),
     6                XPOLEV( INGRDUSE ), YPOLEV( INGRDUSE ),
     7                DLAMNGM,
     8                BITSEA( IIJMAX ,  INGRDUSE ),
     9                BITSNO( IIJMAX ,  INGRDUSE ),
     1                BITWVL( IIJMAX ,  INGRDUSE )
C
C       ****   END OF INCLUDED COMMON BLOCK CONSTN   ***
C
C
C
C     ASSIGN THE FUNDAMENTAL GRID PARAMETERS.
      MADDRS  = IADDRG(INDEX, NG)
      IM    = IMG(NG)
      JM    = JMG(NG)
      CMU   = CMUU(NG)
      DLAM  = DLAMNGM
      XPOL  = XPOLEH(NG)
      YPOL  = YPOLEH(NG)
C
C     ADJUST XPOL AND YPOL FOR THE STAGGERED GRID USED WITH
C     THE U AND V FIELDS.
      IF(INDEX .NE. INDEXHU) GO TO 600
C     THE GRID PARAMETERS FOR THE U GRID POINTS ARE SPECIFIED.
      XPOL = XPOLEU(NG)
      YPOL = YPOLEU(NG)
      GO TO 700
C
  600 IF (INDEX .NE. INDEXHV) GO TO 700
C     THE GRID PARAMETERS FOR THE V GRID POINTS ARE SPECIFIED.
      XPOL = XPOLEV(NG)
      YPOL = YPOLEV(NG)
C
  700 CONTINUE
C
      RETURN
C
      END
