C
C
      SUBROUTINE TASKB (INDEXCD, INUDRAG)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    TASKB       INTERPOLATED DRAG COEFFICIENT TO NGM GRID
C   PRGMMR: JIM HOKE         ORG: W/NMC22    DATE: 85-03-27
C
C ABSTRACT: INTERPOLATES HORIZONTALLY THE DRAG COEFFICIENT TO
C   THE NGM FORECAST GRID POINTS FROM THE LATITUDE-LONGITUDE GRIDS
C
C PROGRAM HISTORY LOG:
C   85-03-27  JIM HOKE
C   88-08-03  BRIAN SCHMIDT ADDED THE DOCBLOCK
C
C USAGE:    CALL TASKB (INDEXCD, INUDRAG)
C   INPUT ARGUMENT LIST:
C     INDEXCD  - ADDRESS REFERENCE FOR THE POSITION WHERE THE
C                DRAG COEFFICIENTS ARE TO BE LOCATED IN ARRAY VBL
C     INUDRAG  - FILE NUMBER OF THE DRAG COEFFICIENTS
C
C   INPUT FILES:
C     INUDRAG  - DRAG COEFFICIENT FILE
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C       COMMON   - DUMMY2
C
C REMARKS: THE FIELD IS ASSUMED TO BE AN EVEN FUNCTION OF
C   LATITUDE (WITH BLENDING OF NORTHERN AND SOUTHERN HEMISPHERIC
C   VALUES ALREADY COMPLETED), SO THAT SOUTHERN HEMISPHERIC VALUES
C   ARE SET EQUAL TO THEIR NORTHERN HEMISPHERIC COUNTERPARTS.
C
C ATTRIBUTES:
C   LANGUAGE: CYBER FORTRAN 200
C   MACHINE:  CYBER 205
C
C$$$
C
      IMPLICIT REAL (A-H, O-Z)
C
C
      INCLUDE 'parmodel'
C
C
      COMMON /DUMMY2/ ANAL( ILONFP1 ,  INLAT ,  ILEVS )
C
      DIMENSION CD(361, 91)
      DIMENSION ALONG(361)
      DIMENSION ALAT(91)
C
      EQUIVALENCE (ANAL(1,1,1), CD(1,1))
C
C
C     INTERPOLATE THE DRAG COEFFICIENT ON A 1-DEGREE-BY-1-DEGREE
C     GRID TO THE NGM GRIDS.
C     I = 1 CORRESPONDS TO THE GREENWICH MERIDIAN.
      IMAX = 361
      JMAX = 91
      KMAX = 1
      ISYM = 2
      FACTOR = 1.0E0
C
C     FIRST, SPECIFY THE LOCATIONS OF THE GRID IN LATITUDE AND
C     LONGITUDE.
      DO 1100 I=1,IMAX
         ALONG(I) = REAL(I-1)
 1100 CONTINUE
C
      DO 1200 J=1,JMAX
         ALAT(J) = REAL(J-1)
 1200 CONTINUE
C
C     INPUT THE DRAG COEFFICIENTS.
      READ (INUDRAG) CD
C
      CALL STATS (CD, 1,IMAX,IMAX, 1,JMAX,JMAX, 1,KMAX,KMAX,
     1            'INPUT DRAG COEF ')
C
      CALL INTERP(CD, IMAX, JMAX, KMAX, ALONG, ALAT,
     1            ISYM, INDEXCD, FACTOR)
C
C
      RETURN
C
      END
