      SUBROUTINE QSEXT(QSS, QSD, H, NX, NY, TSTEP, LOY,
     1                 XCEN, XLEN, YCEN, YLEN,
     2                 QSFMAX, QSFREF, QSM, DELX, DELY,
     2                 STRSPR, STRSUM, STRFLL, STRWIN               )
C     SUBROUTINE TO EXTRAPOLATE THE SALINIZATION FORCING TO THE NEXT
C       TIME STEP.  BG 3-25-88.

      INTEGER NX, NY, TSTEP
      REAL QSS(NX, NY), QSD(NX, NY), H(NX, NY)
      REAL DELX, DELY

      INTEGER I, J, T

      INTEGER XCEN, YCEN, XLEN, YLEN
C     FIND THE CENTER AND SIZE OF THE ENHANCED FREEZING REGION,
C       ASSUMING A GAUSSIAN PROFILE IN X, Y  WITH POSSIBLY DIFFERENT
C         S.D.
      REAL QSFMAX, QSFREF
C     THE GAUSSIAN AND BACKGROUND FREEZING RATES.
      REAL QSM
C     THE MELTING RATE (UNIFORM OVER DOMAIN)
      INTEGER STRSPR, STRSUM, STRFLL, STRWIN, LOY
C     START OF SPRING, SUMMER, FALL, WINTER, AND LENGTH OF THE YEAR
C       FOR NOW, DISCONTINUOUS BEHAVIOR - WINTER HAS FREEZING, FALL
C       SPRING HAVE NORE MELT OR FREEZE, AND SUMMER HAS MELTING

      REAL PI
      PARAMETER (PI = 3.141592654)
      REAL XREF, YREF, DX, DY, SIGX, SIGY

      T = MOD(TSTEP,LOY)
      XREF = FLOAT(XCEN)
      YREF = FLOAT(YCEN)
      SIGX = FLOAT(XLEN)
      SIGY = FLOAT(YLEN)

      IF ((T .GE. STRWIN) .AND. (T .LT. STRSPR)) THEN
C     NOTE THAT THIS ASSUMES THAT TIME IS TOLD WITHIN A YEAR.
C     WINTERTIME
CD      PRINT *,'WINTER'
        DO 1000 J = 1, NY
          DO 1010 I = 1, NX
C           WITH THE ADVENT OF THE GAUSSIAN, DO NOT NEED TO LOOK AT
C             SEPARATE CASES.
            DX = DELX*FLOAT(I)
            DY = DELY*FLOAT(J)
            QSS(I,J) = QSFREF + QSFMAX*
     1   EXP((-1.)*(( DX-XREF )**2/2./SIGX**2
     2             +( DY-YREF )**2/2./SIGY**2 ))
            QSD(I,J) = QSS(I,J)
 1010     CONTINUE
 1000   CONTINUE
       ELSEIF (T .GE. STRSPR .AND. T .LT. STRSUM) THEN
C       SPRING, QSS = QSD = 0.0
        DO 1100 J = 1, NY
          DO 1110 I = 1, NX
            QSS(I,J) = 0.0
            QSD(I,J) = 0.0
 1110     CONTINUE
 1100   CONTINUE
       ELSEIF (T .GE. STRSUM .AND. T .LT. STRFLL) THEN
        DO 2000 J = 1, NY
          DO 2010 I = 1, NX
            QSS(I,J) = QSM
            QSD(I,J) = QSM
 2010     CONTINUE
 2000   CONTINUE
       ELSE
C       FALL, DO NOTHING
        DO 2100 J = 1, NY
          DO 2110 I = 1, NX
            QSS(I,J) = 0.0
            QSD(I,J) = 0.0
 2110     CONTINUE
 2100   CONTINUE
      ENDIF

      RETURN
      END
