       BLOCK DATA BLOCSP03
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    BLOCSP03    DEFINE COMMON/FIXSP03/
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 88-06-13
C
C ABSTRACT: ALL INTERNAL VARIABLES USED FOR VERTICAL
C   MODE TRANSFORMS ARE COLLECTED AND DEFINED HERE.
C
C PROGRAM HISTORY LOG:
C   88-06-13  PARRISH
C
C USAGE:    N-A  (BLOCK DATA STATEMENTS NOT EXECUTABLE)
C
C DEFINITION OF VARIABLES IN COMMON/FIXSP03/
C       INTEGER VARIABLES:
C     JCAP     - SPECTRAL TRUNCATION
C     NLATH    - NUMBER OF LATITUDES IN ONE HEMISPHERE
C     NLAT     - NUMBER OF LATITUDES ON LAT-LON GRID
C     NLON     - NUMBER OF LONGITUDES ON LAT-LON GRID
C     NLONEX   - EXTENDED NUMBER OF LONGITUDES ON LAT-LON GRID
C     NCOEFS   - NUMBER OF COEFFICIENTS
C     NFOP     - USED FOR OPERATOR "F"
C     IFOP     - DITTO
C       FULL PRECISION VARIABLES:
C     RFOP     - USED FOR OPERATOR "F"
C     RCINVOP  - INVERSE OF OPERATOR "F"
C       REAL VARIABLES:
C     SCALZD   - USED TO SCALE VARIABLES
C     UNSCLZD  - INVERSE OF SCALEZD
C     FOP      - REAL COPY OF RFOP
C     CINVOP   - REAL VERSION OF RCINVOP
C       BIT VARIABLES:
C     BFOP     - BIT ARRAYS USED FOR APPLICATION
C     BONES    - OF "F" OPERATOR
C ATTRIBUTES:
C   LANGUAGE: FORTRAN77
C   MACHINE:  CYBER
C
C$$$
         include "myparam"
C--------
         COMMON/FIXSP03/NSIG,NMODES,
     *      DELSIG(INSIG),
     *      HEINVT(INSIG),HEINV(INSIG,INSIG),
     *      HEINVG(INSIG,INSIG),
     *      HPIBINVE(INSIG),HTBINVE(INSIG,INSIG),
     *      HE(INSIG,INSIG),HDEPTHS(INMODES)
C--------
         DATA NSIG/0/,NMODES/0/,DELSIG/INSIG*9999./
       END
