       SUBROUTINE CHECKINV(E,EINV,N)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    CHECKINV    CHECK INVERSE OF A MATRIX
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 88-09-08
C
C ABSTRACT: CHECK ACCURACY OF MATRIX INVERSE.
C
C PROGRAM HISTORY LOG:
C   88-09-08  PARRISH
C
C USAGE:    CALL CHECKINV(E,EINV,N)
C   INPUT ARGUMENT LIST:
C     E        - MATRIX
C     EINV     - INVERSE OF MATRIX TO BE TESTED
C     N        - DIMENSION OF MATRICES
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN200
C   MACHINE:  CYBER
C
C$$$
         REAL E(N,N),EINV(N,N)
         ERMAX=0.
         DO 300 J=1,N
           DO 200 I=1,N
             PROD=0.
             IF(I.EQ.J) PROD=-1.
             DO 100 K=1,N
               PROD=PROD+E(I,K)*EINV(K,J)
100          CONTINUE
             ERMAX=AMAX1(ERMAX,ABS(PROD))
200        CONTINUE
300      CONTINUE
c        WRITE(6,400)N,ERMAX
 400     FORMAT(' CHECK MATRIX INVERSE, N,ERMAX=',I5,G12.4)
       RETURN
       END
