       SUBROUTINE FREECOEF(IV,NV)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    FREECOEF    FREE SPACE FOR COEFFICIENTS
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 88-07-07
C
C ABSTRACT: FREE SPACE AT ADDRESSES IV (NV OF THEM) IN BLANK COMMON
C
C PROGRAM HISTORY LOG:
C   88-07-07  PARRISH
C   90-07-05  PARRISH (CONVERT TO CRAY)
C
C USAGE:    CALL FREECOEF(IV,NV)
C   INPUT ARGUMENT LIST:
C     NV       - NUMBER OF COEF FIELDS TO FREE
C     IV       - STARTING INDICES OF EACH COEF FIELD.
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN77
C   MACHINE:  CRAY
C
C$$$
C--------
         include "myparam"
C--------
         COMMON/FIXSP00/HGRIDS(INUMGRID),HCOEFS(INUMCOEF)
C--------
         INTEGER IV(1)
C--------
         DO 100 I=1,NV
           HCOEFS(IV(I))=0.
100      CONTINUE
       RETURN
       END
