       SUBROUTINE GETACTT(T,H,Q,N,NMAX,KM)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    GETACTT     GET ACTUAL TEMP FROM VIRTUAL TEMP.
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 88-08-08
C
C ABSTRACT: CONVERT VIRTUAL TEMP TO ACTUAL TEMP
C
C PROGRAM HISTORY LOG:
C   88-08-08  PARRISH
C
C USAGE:    CALL GETACTT(T,H,Q,N,NMAX,KM)
C   INPUT ARGUMENT LIST:
C     T        - VIRTUAL TEMPERATURE
C     H        - SURFACE PRESSURE
C     Q        - MIXING RATIO
C     N        - NUMBER OF POINTS TO DO
C     NMAX     - MAX POINTS PER LEVEL
C     KM       - NUMBER OF LEVELS
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     T        - ACTUAL TEMPERATURE
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN200
C   MACHINE:  CYBER
C
C$$$
         include "myparam"
C--------
         REAL T(NMAX,1),H(1),Q(NMAX,1)
C--------
         DO 100 K=1,KM
           DO 50 I=1,N
             T(I,K)=T(I,K)/(1.+.609*Q(I,K)/H(I))
50         CONTINUE
100      CONTINUE
       RETURN
       END
