       SUBROUTINE GETGRID(IV,NV)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    GETGRID     ALLOCATE SPACE FOR GRIDS
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 88-07-07
C
C ABSTRACT: RETURN ADDRESSES OF NV USABLE GRID FIELDS IN BLANK COMMON
C
C PROGRAM HISTORY LOG:
C   88-07-07  PARRISH
C   90-07-05  PARRISH (CONVERT TO CRAY)
C
C USAGE:    CALL GETGRID(IV,NV)
C   INPUT ARGUMENT LIST:
C     NV       - NUMBER OF GRIDS NEEDED
C
C   OUTPUT ARGUMENT LIST:
C     IV       - STARTING INDICES OF EACH GRID.
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN77
C   MACHINE:  CRAY
C
C$$$
C--------
         include "myparam"
C--------
         COMMON/FIXSP00/HGRIDS(INUMGRID),HCOEFS(INUMCOEF)
C--------
         INTEGER IV(1)
C--------
         II=0
         DO 100 I=1,INUMGRID
           IF(HGRIDS(I).EQ.0.) THEN
             II=II+1
             IV(II)=I
             HGRIDS(I)=1.
             IF(II.GE.NV) RETURN
           END IF
100      CONTINUE
C--------
C-------- IF HERE, THEN MUST HAVE RUN OUT OF SPACE, SO NEED TO
C-------- INCREASE NUMGRID
C--------
C        STOP 'OUT OF SPACE FOR GRIDS.  INCREASE NUMGRID'
         WRITE(6,9899)
9899     FORMAT(' OUT OF SPACE FOR GRIDS.  INCREASE NUMGRID')
         RETURN
       END
