       SUBROUTINE HLLO2POL(F1,M1,N1,
     *                     F2,M2,N2,DX2,XPOLE2,YPOLE2,
     *                     RK,IK,BK,WORK,
     *     X1WORK,Y1WORK,X2WORK,Y2WORK,RKWORK,IKWORK,RLATH,DLON,
     *     IORDLP)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    HLLO2POL    LOLA TO POLA INTERPOLATION
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 88-08-08
C
C ABSTRACT: INTERPOLATE FROM LOLA TO POLA.
C
C PROGRAM HISTORY LOG:
C   88-08-08  PARRISH
C
C USAGE:    CALL HLLO2POL(F1,M1,N1,
C    *                     F2,M2,N2,DX2,XPOLE2,YPOLE2,
C    *                     RK,IK,BK,WORK,
C    *     X1WORK,Y1WORK,X2WORK,Y2WORK,RKWORK,IKWORK,RLATH,DLON,
C    *     IORDLP)
C   INPUT ARGUMENT LIST:
C     F1       - INPUT FIELD TO INTERPOLATE FROM.
C     M1       - INPUT FIELD FIRST DIMENSION
C     N1       - INPUT FIELD SECOND DIMENSION
C     M2       - OUTPUT FIELD FIRST DIMENSION
C     N2       - OUTPUT FIELD SECOND DIMENSION
C     DX2      - OUTPUT FIELD GRID INCREMENT
C     XPOLE2   - OUTPUT FIELD
C     YPOLE2   - POLE COORDINATES
C     RLATH    - GAUSSIAN LATITUDES
C     DLON     - LONGITUDE INCREMENT (BOTH IN RADIANS)
C     IORDLP   - ORDER OF INTERPOLATION ( 0 - 3 )
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     F2       - OUTPUT FIELD OF INTERPOLATED VALUES.
C     RK       - WORK ARRAY
C     IK       - WORK ARRAY
C     BK       - WORK ARRAY
C     WORK     - WORK ARRAY
C     X1WORK   - WORK ARRAY
C     Y1WORK   - WORK ARRAY
C     X2WORK   - WORK ARRAY
C     Y2WORK   - WORK ARRAY
C     RKWORK   - WORK ARRAY
C     IKWORK   - WORK ARRAY
C
C   SUBPROGRAMS CALLED: POLORXY,TWOPLATE
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN200
C   MACHINE:  CYBER
C
C$$$
C--------
         include "myparam"
         REAL F1(N1,M1),F2(1),WORK(M1,N1)
         REAL RK(1),X1WORK(1),Y1WORK(1),X2WORK(1)
         REAL Y2WORK(1),RKWORK(1),RLATH(1)
         INTEGER IK(1),IKWORK(1)
         LOGICAL BK(1)
C--------
         NKX=IORDLP+1
         ERAD=6371.22E3
         IORDER=NKX-1
         NF=1
         IZERO=0
         MNN1=M1*N1
         MNN2=M2*N2
         TPI=8.*ATAN(1.)
         DO 100 I=1,M1
           X1WORK(I)=(I-1.)*DLON
100      CONTINUE
         DO 200 I=1,N1
           Y1WORK(I)=RLATH(I)
200      CONTINUE
C        WRITE(6,8)M1,N1,DX1,DY1
C8       FORMAT(' IN HLLO2POL, M1,N1,DX1,DY1=',
C    *        2I5,2E12.4,' X1,Y1 FOLLOW')
C        WRITE(6,10)(X1WORK(I),I=1,M1)
C        WRITE(6,12)(Y1WORK(I),I=1,N12)
C10      FORMAT(1H ,10E12.4)
C12      FORMAT(1H ,5X,10E12.4)
         CALL POLORXY(X2WORK,Y2WORK,M2,N2,XPOLE2,YPOLE2,DX2,DX2,ERAD,
     *                                                     RK,IK)
         DO 600 J=1,N1
           DO 500 I=1,M1
             WORK(I,J)=F1(J,I)
500        CONTINUE
600      CONTINUE
         CALL TWOPLATE(WORK,M1,N1,X1WORK,Y1WORK,MNN1,
     *             F2,MNN2,X2WORK,Y2WORK,MNN2,
     *                   IORDER,NF,RK,IK,RKWORK,IKWORK,BK,IZERO)
       RETURN
       END
