      SUBROUTINE LATBND( NC, KHINTERP )
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    LATBND      INTERPOLATE BOUNDARY VALUES FOR THE NGM
C   PRGMMR:  JIM TUCCILLO       ORG: W/NMC4     DATE: 90-06-13
C
C ABSTRACT: INTERPOLATES INNER BNDRY VALUES FOR THE
C   .       COARSER AND OUTER BNDRY VALUES FOR THE
C   .       FINER MEMBERS OF AN OVERLAPPING
C   .       PAIR OF GRIDS IN THE NGM (NESTED
C   .       GRID MODEL).
C   .
C   BILINEAR INTERPOLATION ON THE COARSE GRID GIVES NEEDED
C   VALUES ON THE FINE GRID, AND VICE-VERSA.  DIFFERENT PROCEDURES
C   MUST BE USED FOR THREE VARIABLE TYPES--THE TWO VELOCITY
C   COMPONENTS U AND V, AND THE MASS VARIABLE TYPE DENOTED BY ''H''
C   BECAUSE THESE VARIABLE TYPES ARE AT STAGGERED LOCATIONS IN
C   THE HORIZONTAL.  ADDRESS INTEGERS AND INTERPOLATION
C   COEFFICIENTS ARE COMPUTED ON THE FIRST CALL.
C
C PROGRAM HISTORY LOG:
C   90-06-13  J TUCCILLO
C
C USAGE:  CALL LATBND( NC, KHINTERP)
C   INPUT ARGUMENT LIST:
C     NC       - GRID NUMBER OF THE COARSER GRID OF THE
C                PAIR (OUTER HEMISPHERIC GRID HAS NC=1).
C
C     KHINTERP - NUMBER OF HORIZONTAL ARRAYS OF H-TYPE VBLS
C                THAT NEED BNDRY VALUES.
C
C   OUTPUT FILES:
C     IOUTUPRT - FOR ERROR MESSAGE PRINTOUTS
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - ERRPRINT
C     LIBRARY:
C       COMMON   - COMCONST
C                  COMBLANK
C
C REMARKS: ALSO SEE COMMENTS AFTER DOCBLOCK
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES      MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----      ----------------------------------        ---------
C   VBL        ARRAY CONTAINING ALL VBLS FOR ALL GRIDS   COMMON
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   VBL         ARRAY OF ALL VBLS NOW HAS BNDRY VALUES    COMMON
C   .           ADDED FOR GRIDS NC AND NC+1.
C
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      include 'parmodel'
C
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:45:47
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C          PROGRAM TO INTERPOLATE LATERAL BOUNDARY VALUES BETWEEN
C          THE COARSE GRID  NC  , AND THE FINE GRID NF=NC+1.
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
      COMMON /COM1WAY/ ITIMSTEP, ITBOUND, INGLB
C
C     TEMPORARY SCRATCH ARRAYS
      DIMENSION X(IIJMAX),X1(IIJMAX),X2(IIJMAX),X3(IIJMAX),
     *          X4(IIJMAX),Y(IIJMAX)
      EQUIVALENCE (X(1),SCR(1,1) ), (Y(1), SCR(1,5) ),
     1 (X1(1), SCR(1,1) ),(X2(1),SCR(1,2) ), (X3(1),SCR(1,3) ),
     2 (X4(1),SCR(1,4) )
C
C     PERMANENT STORAGE
      DIMENSION CH(ILBCH,INGRDUS1,4)
      DIMENSION LGSUO(ILBUO,INGRDUS1,2), LGSVO(ILBVO,INGRDUS1,2),
     1          LGSHO(ILBCH,INGRDUS1,2), LGSUI(ILBUI,INGRDUS1,2),
     2          LGSVI(ILBVI,INGRDUS1,2), LGSHI(ILBHI,INGRDUS1,2)
C
      INTEGER I1X,I2X,I3X,I4X,I5X,I6X,I7X,I8X,I9X,I10X,I11X,I12X,I13X,I1
     .4X,I15X,I16X,I17X,I18X,I19X,I20X
      DATA ICALL /0/
C
C
C              SPECIFY THE UNIT NUMBER OF THE PRINTER.
C
C
C              SPECIFY THE UNIT NUMBER OF THE PRINTER.
      IOUTUPRT = 6
C
C          ON 1ST CALL, MUST COMPUTE INTERPOLATION ARRAYS
C
      IF( ICALL .GT. 0) GO TO 200
C
      ICALL=1
C
C          ARRAY SIZES
      LBCH=ILBCH
      LBHI=ILBHI
      LBUI=ILBUI
      LBUO=ILBUO
      LBVI=ILBVI
      LBVO=ILBVO
C
C
C          ENTER OUTER LOOP ON THE NGDUSE - 1 GRID PAIRS THAT EXIST
      NINTPR=NGRDUSE-1
C
      DO 120 NG=1,NINTPR
C
C          GET THE GRID DIMENSION NUMBERS FOR THE
C          COARSE AND FINE GRIDS,
      IMC=IMG(NG)
      JMC=JMG(NG)
      IJC=IMC*JMC
      IMF=IMG(NG+1)
      JMF=JMG(NG+1)
      IJF=IMF*JMF
      IA=IAG(NG)
      JA=JAG(NG)
      IB=IBG(NG)
      JB=JBG(NG)
C          MUST HAVE JB .GT. (JA+2) AND IB .GT. (IA+2).
      IF(JB .LE. (JA+2) ) GO TO 1
      IF(IB .LE. (IA+2) ) GO TO 1
      GO TO 5
C          ERROR
    1 WRITE (IOUTUPRT, 3) IA,IB,JA,JB,NG
    3 FORMAT(1H1,2X,'*****SR LATBND ENCOUNTERED IA,IB,JA,JB=',
     1 4I10,', ON GRID',I10)
C
      CALL EXIT(16)
C
    5 CONTINUE
C
CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C          L IS STORE INTEGER FOR FINE GRID U INTEGER ARRAYS.
      L=0
C          I AND J WILL BE FINE GRID PT INDICES FOR U
C          JODD(OR IODD) WILL BE +1 FOR EVEN J(OR I) AND -1 FOR
C          ODD J (OR I).
C
      JODD=1
      IRET=1
        J = 1
8884    IF ( J.GT.4) GOTO 9994
        JODD=-JODD
        IODD=1
          I = 1
8882      IF ( I .GT. IMF ) GOTO 9992
          GO TO 16
    2     I = I + 1
          GOTO 8882
9992      CONTINUE
    4   J = J + 1
        GOTO 8884
9994    CONTINUE
      J1=JMF-4
        J = 5
88810   IF ( J .GT. J1 ) GOTO 99910
        JODD=-JODD
        IODD=1
        IRET=2
          I = 1
8886      IF ( I .GT. 4 ) GOTO 9996
          GO TO 16
    6     I = I + 1
          GOTO 8886
9996      CONTINUE
C          IMF-2 IS ODD
        I1=IMF-2
        IRET=3
          I = I1
8888      IF ( I .GT. IMF ) GOTO 9998
          GO TO 16
    8     I = I + 1
          GOTO 8888
9998      CONTINUE
   10   J = J + 1
        GOTO 88810
99910   CONTINUE
      J1=JMF-3
      IRET=4
        J = J1
88814   IF ( J .GT. JMF ) GOTO 99914
        JODD=-JODD
        IODD=1
          I = 1
88812     IF ( I .GT. IMF ) GOTO 99912
          GO TO 16
   12     I = I + 1
          GOTO 88812
99912     CONTINUE
   14   J = J + 1
        GOTO 88814
99914   CONTINUE
C
C          DONE WITH OUTER U,, GO TO OUTER V INTEGER COMPNS.
      GO TO 20
C
C    *    *    *    *    *    *    *    *    *    *    *    *    *
C          COMPUTED GO TO ROUTINE FOR OUTER U GATHER-SCATTER INTEGERS
C
   16 IODD=-IODD
      L=L+1
      IF(L .LE. LBUO ) GO TO 18
C          ERROR
      WRITE (IOUTUPRT, 17) L,LBUO,NG
   17 FORMAT(1H1,2X,'**IN SR LATBND,L=',I8,' IS .GT. LBUO=',I8,
     1 '. COARSE GRID=',I8)
C
C*****  Code Expanded From Routine:  ERRPRINT
      PRINT 77052
77052 FORMAT (1H1, '  **********  PRINT FROM SUBROUTINE ERRPRINT ',
     1             'FOLLOWS. ***********')
C
      PRINT 77053, IJMAX, KM, LVLTOT, NGRDUSE, NH
77053 FORMAT (1H1, 2X, 'IJMAX, KM, LVLTOT, NGRDUSE, NH =', 5I10)
C
      PRINT 77054, NTIME, ITIME, NSTEPS
77054 FORMAT (1H0, 2X, 'NTIME, ITIME, NSTEPS= ', 3I10 /)
C*****  End of Code Expanded From Routine:  ERRPRINT
      CALL EXIT(16)
C
   18 CONTINUE
C          IJA WILL BE COARSE GRID ADDRESS OF U POINT IN LOWER LEFT
C          CORNER OF GRID BOX.
      JC=J/2 + JA-4
      IC=I/2 +IA -4
      IJA=IC+(JC-1)*IMC
C          L2 WILL BE 0,1,2,3 FOR FINE GRID U TO LOWER LEFT,LOWER
C          RIGHT,UPPER LEFT, OR UPPER RIGHT IN COARSE GRID U BOX
      L2=1-JODD + (1-IODD)/2
C          THE GATHER INTS FROM 4 SCRATCH ARRAYS TO VECTOR OF NEEDED
C          U VALUES
      LGSUO(L, NG, 1)=IJA+L2*IJC
C          SCATTER INTS FROM VECTOR OF NEEDED VALUES TO FINE U ARRAY
      LGSUO( L, NG, 2)=I+(J-1)*IMF
C
      GO TO ( 2, 6, 8, 12 ),IRET
C
CBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
C
C          L IS STORING INTEGER FOR FINE GRID OUTER V INTEGERS
   20 L=0
C          I,J WILL BE FINE GRID V INDICES
C          JODD(OR IODD) WILL BE +1 FOR EVEN J (OR I) AND -1 FOR
C          ODD J (OR I).
      JODD=1
      IRET=1
        J = 1
88824   IF ( J .GT. 4 ) GOTO 99924
        JODD=-JODD
        IODD=1
          I = 1
88822     IF ( I .GT. IMF ) GOTO 99922
          GO TO 36
   22     I = I + 1
          GOTO 88822
99922     CONTINUE
   24   J = J + 1
        GOTO 88824
99924   CONTINUE
      J1=JMF-3
        J = 5
88830   IF ( J .GT. J1 ) GOTO 99930
        JODD=-JODD
        IODD=1
        IRET=2
          I = 1
88826     IF ( I .GT. 4 ) GOTO 99926
          GO TO 36
   26     I = I + 1
          GOTO 88826
99926     CONTINUE
C          IMF - 3 WILL BE EVEN
        IODD=-1
        I1=IMF-3
        IRET=3
          I = I1
88828     IF ( I .GT. IMF ) GOTO 99928
          GO TO 36
   28     I = I + 1
          GOTO 88828
99928     CONTINUE
   30   J = J + 1
        GOTO 88830
99930   CONTINUE
      J1=JMF-2
      IRET=4
        J = J1
88834   IF ( J .GT. JMF ) GOTO 99934
        JODD=-JODD
        IODD=1
          I = 1
88832     IF ( I .GT. IMF ) GOTO 99932
          GO TO 36
   32     I = I + 1
          GOTO 88832
99932     CONTINUE
   34   J = J + 1
        GOTO 88834
99934   CONTINUE
C
C          DONE WITH OUTER V,, GO TO COMPUTATION OF OUTER H NUMBERS
C
      GO TO 40
C
C    *    *    *    *    *    *    *    *    *    *    *    *    *
C          COMPTD GO TO ROUTINE FOR FINE GRID V GATHER-SCATTER INTS.
C
   36 IODD=-IODD
      L=L+1
      IF(L .LE. LBVO ) GO TO 38
C          ERROR
      WRITE (IOUTUPRT, 37) L,LBVO,NG
   37 FORMAT(1H1,2X,'*****IN SR LATBND L=',I8,'IS  .GT. LBVO=',I8,
     1 '. COARSE GRID=',I8)
C
      CALL EXIT(16)
   38 CONTINUE
C          IJA WILL BE ADDRESS OF COARSE GRID V IN LOWER LEFT CORNER
C          OF GRID BOX.
      IC=IA-4+ (I/2)
      JC=JA-4+ (J/2)
      IJA=IC+(JC-1)*IMC
C          L2 WILL BE 0,1,2,3 FOR FINE GRID V IN LOWER LEFT,UPPER LEFT,
C          LOWER RIGHT, OR UPPER RIGHT WITHIN COARSE GRID V BOX.
      L2=1-IODD + (1-JODD)/2
C          THE GATHER INTS FROM 4 SCRATCH ARRAYS INTO A
C          VECTOR OF THE NEEDED V S.
      LGSVO( L,NG, 1)=IJA+L2*IJC
C          THE INTS FOR SCATTER INTO THE FINE GRID V ARRAY.
      LGSVO(L, NG, 2)=I+(J-1)*IMF
C
      GO TO ( 22, 26, 28, 32 ),IRET
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C          L IS STORE INTEGER FOR FINE GRID H INTEGERS AND COEFFS.
   40 L=0
C          SOME CONSTANTS FOR THE COEFFICIENT COMPUTATIONS.
      ONE=1.E0
      SIX=6.E0
      FOUR=4.E0
      SCALE=1.E0/32.E0
C          DJ(OR DI) WILL BE +1. FOR EVEN J(OR I) AND -1. FOR
C          ODD J(OR I).
      DJ=ONE
      IRET=1
        J = 1
88844   IF ( J .GT. 4 ) GOTO 99944
        DJ=-DJ
        DI=ONE
          I = 1
88842     IF ( I .GT. IMF ) GOTO 99942
          GO TO 56
   42     I = I + 1
          GOTO 88842
99942     CONTINUE
   44   J = J + 1
        GOTO 88844
99944   CONTINUE
      J1=JMF-3
        J = 5
88850   IF ( J .GT. J1 ) GOTO 99950
        DJ=-DJ
        DI=ONE
        IRET=2
          I = 1
88846     IF ( I .GT. 4 ) GOTO 99946
          GO TO 56
   46     I = I + 1
          GOTO 88846
99946     CONTINUE
C          IM-2 IS ODD
        I1=IMF-2
        IRET=3
          I = I1
88848     IF ( I .GT. IMF ) GOTO 99948
          GO TO 56
   48     I = I + 1
          GOTO 88848
99948     CONTINUE
   50   J = J + 1
        GOTO 88850
99950   CONTINUE
      J1=JMF-2
      IRET=4
        J = J1
88854   IF ( J .GT. JMF ) GOTO 99954
        DJ=-DJ
        DI=ONE
          I = 1
88852     IF ( I .GT. IMF ) GOTO 99952
          GO TO 56
   52     I = I + 1
          GOTO 88852
99952     CONTINUE
   54   J = J + 1
        GOTO 88854
99954   CONTINUE
C
C          SHUFFLE THESE TABLES TO ELIMINATE BANK CONFLICT.
C          L WAS THE NUMBER OF ENTRIES(SHOULD BE ODD).
      LL=L-4
CMIC$ DO ALL SHARED(LL, NG, LGSHO, CH) PRIVATE(M, MM, LSV, K, CHSV)
      DO 53 M=1,LL,2
      MM=M+3
      LSV=LGSHO(M,NG,1)
      LGSHO(M,NG,1)=LGSHO(MM,NG,1)
      LGSHO(MM,NG,1)=LSV
      LSV=LGSHO(M,NG,2)
      LGSHO(M,NG,2)=LGSHO(MM,NG,2)
      LGSHO(MM,NG,2)=LSV
        DO 51 K=1,4
        CHSV=CH(M,NG,K)
        CH(M,NG,K)=CH(MM,NG,K)
        CH(MM,NG,K)=CHSV
   51   CONTINUE
   53 CONTINUE
C
C          DONE WITH OUTER HS, GO TO COMPUTE INNER U BNDRY INTEGERS
C
      GO TO 60
C
C    *    *    *    *    *    *    *    *    *    *    *    *    *
C          COMPUTED GO TO ROUTINE FOR FINE GRID H INTEGERS AND COEFFS.
C
   56 L=L+1
      IF(L .LE. LBCH ) GO TO 58
C          ERROR
      WRITE (IOUTUPRT, 57) L,LBCH,NG
   57 FORMAT(1H1,2X,'*****IN SR LATBND L=',I8,' IS .GT. LBCH=',I8,
     1 '. COARSE GRID=',I8)
C
      CALL EXIT(16)
C
   58 CONTINUE
      DI=-DI
C          GET INTERPOLATION COEFFS INTO ARRAY CH
      SUM=DJ+DI
      DIF=DJ-DI
      CH(L,NG,1)=SCALE*(SIX+SUM*(FOUR+SUM) )
      CH(L,NG,2)=SCALE*(SIX+DIF*(FOUR+DIF) )
      CH(L,NG,3)=SCALE*(SIX-DIF*(FOUR-DIF) )
      CH(L,NG,4)=SCALE*(SIX-SUM*(FOUR-SUM) )
C          GATHER INTEGERS FOR LOWER LEFT COARSE GRID H POINTS.
      IC=IA-4+(I/2)
      JC=JA-4+(J/2)
      LGSHO(L,NG,1)=IC+(JC-1)*IMC
C          INTEGERS FOR SCATTER INTO FINE GRID H ARRAY
      LGSHO(L,NG,2)=I+(J-1)*IMF
C
      GO TO ( 42, 46, 48, 52 ),IRET
C
CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
C
C          L IS STORE INTEGER FOR COARSE GRID U INTEGERS.
   60 L=0
C          CONSTANTS FOR CONVERSION TO FINE GRID I AND J
      II=7-2*IA
      JJ=8-2*JA
C
C          I AND J NOW REPRESENT COARSE GRID INDEXES.
C
      J1=JA-1
        J = J1
88864   IF ( J .GT. JA ) GOTO 99964
        IRET=1
          I = IA
88862     IF ( I .GT. IB ) GOTO 99962
          GO TO 74
   62     I = I + 1
          GOTO 88862
99962     CONTINUE
   64   J = J + 1
        GOTO 88864
99964   CONTINUE
      J1=JA+1
      J2=JB-2
        J = J1
88868   IF ( J .GT. J2 ) GOTO 99968
        IRET=2
        I=IA
        GO TO 74
   66   I=IB
        IRET=3
        GO TO 74
   68   J = J + 1
        GOTO 88868
99968   CONTINUE
      J1=JB-1
        J = J1
88872   IF ( J .GT. JB ) GOTO 99972
        IRET=4
          I = IA
88870     IF ( I .GT. IB ) GOTO 99970
          GO TO 74
   70     I = I + 1
          GOTO 88870
99970     CONTINUE
   72   J = J + 1
        GOTO 88872
99972   CONTINUE
C
C          DONE WITH COARSE GRID U INTS,, GO TO COARSE GRID V INTS.
      GO TO 80
C
C    *    *    *    *    *    *    *    *    *    *    *    *    *
C          COMPUTED GO TO ROUTINE FOR COARSE GRID U INTEGERS
C
   74 L=L+1
      IF(L .LE. LBUI ) GO TO 76
C          ERROR
      WRITE (IOUTUPRT, 75) L,LBUI,NG
   75 FORMAT(1H1,2X,'*****IN SR LATBND,L=',I8,' IS .GT. LBUI=',I8,
     1 '. COARSE GRID=',I8)
C
C*****  Code Expanded From Routine:  ERRPRINT
      PRINT 77055
77055 FORMAT (1H1, '  **********  PRINT FROM SUBROUTINE ERRPRINT ',
     1             'FOLLOWS. ***********')
C
      PRINT 77056, IJMAX, KM, LVLTOT, NGRDUSE, NH
77056 FORMAT (1H1, 2X, 'IJMAX, KM, LVLTOT, NGRDUSE, NH =', 5I10)
C
      PRINT 77057, NTIME, ITIME, NSTEPS
77057 FORMAT (1H0, 2X, 'NTIME, ITIME, NSTEPS= ', 3I10 /)
C*****  End of Code Expanded From Routine:  ERRPRINT
C
      CALL EXIT(16)
C
   76 CONTINUE
C          (III,JJJ) IS INDEX OF FINE GRID U TO LEFT OF COARSE GRID U.
      III=2*I+II
      JJJ=2*J+JJ
C          GATHER INTEGER FOR THAT FINE GRID U.
      LGSUI(L,NG,1)=III+(JJJ-1)*IMF
C          INTEGERS FOR SCATTER INTO COARSE GRID U ARRAY.
      LGSUI(L,NG,2)=I+(J-1)*IMC
C
      GO TO ( 62, 66, 68, 70 ),IRET
C
CEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
C
C          L IS STORE INTEGER FOR COARSE GRID V GATHER-SCATTER OPNS.
   80 L=0
C          CONSTANTS FOR CONVERSION INTO FINE GRID I,J.
      II=8-2*IA
      JJ=7-2*JA
C
      J=JA
      I1=IA-1
      IRET=1
        I = I1
88882   IF ( I .GT. IB ) GOTO 99982
        GO TO 92
   82   I = I + 1
        GOTO 88882
99982   CONTINUE
      J1=JA+1
      J2=JB-1
        J = J1
88888   IF ( J .GT. J2 ) GOTO 99988
        IRET=2
        I1=IA-1
          I = I1
88884     IF ( I .GT. IA ) GOTO 99984
          GO TO 92
   84     I = I + 1
          GOTO 88884
99984     CONTINUE
        IRET=3
        I1=IB-1
          I = I1
88886     IF ( I .GT. IB ) GOTO 99986
          GO TO 92
   86     I = I + 1
          GOTO 88886
99986     CONTINUE
   88   J = J + 1
        GOTO 88888
99988   CONTINUE
      J=JB
      IRET=4
      I1=IA-1
        I = I1
88890   IF ( I .GT. IB ) GOTO 99990
        GO TO 92
   90   I = I + 1
        GOTO 88890
99990   CONTINUE
C
C          DONE WITH COARSE GRID V INTS,, GO TO COARSE GRID H INTS.
      GO TO 100
C
C    *    *    *    *    *    *    *    *    *    *    *    *    *
CC          COMPTD GO TO ROUTINE FOR COARSE GRID V GATHER-SCATTER INTS.
C
   92 L=L+1
      IF(L .LE. LBVI ) GO TO 94
C          ERROR
      WRITE (IOUTUPRT, 93) L,LBVI,NG
   93 FORMAT(1H1,2X,'*****IN SR LATBND L=',I8,' IS .GT. LBVI=',I8,
     1 '. COARSE GRID=',I8)
C
C*****  Code Expanded From Routine:  ERRPRINT
      PRINT 77058
77058 FORMAT (1H1, '  **********  PRINT FROM SUBROUTINE ERRPRINT ',
     1             'FOLLOWS. ***********')
C
      PRINT 77059, IJMAX, KM, LVLTOT, NGRDUSE, NH
77059 FORMAT (1H1, 2X, 'IJMAX, KM, LVLTOT, NGRDUSE, NH =', 5I10)
C
      PRINT 77060, NTIME, ITIME, NSTEPS
77060 FORMAT (1H0, 2X, 'NTIME, ITIME, NSTEPS= ', 3I10 /)
C*****  End of Code Expanded From Routine:  ERRPRINT
      CALL EXIT(16)
C
   94 CONTINUE
C          III,JJJ ARE INDEXES FOR FINE GRID V BELOW COARSE GRID V.
      III=2*I+II
      JJJ=2*J+JJ
C          INTS TO GATHER THAT FINE GRID V.
      LGSVI(L,NG,1)=III+(JJJ-1)*IMF
C          INTEGER TO SCATTER COARSE GRID V INTO ITS ARRAY.
      LGSVI(L,NG,2)=I+(J-1)*IMC
C
      GO TO ( 82, 84, 86, 90 ),IRET
C
CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
C          L IS STORE INTEGER FOR COARSE GRID H GATHER-SCATTER OPNS.
  100 L=0
C          CONSTANTS TO CONVERT TO FINE GRID I AND J.
      II=7-2*IA
      JJ=7-2*JA
C
      J=JA
      IRET=1
        I = IA
88102   IF ( I .GT. IB ) GOTO 99102
        GO TO 110
  102   I = I + 1
        GOTO 88102
99102   CONTINUE
      J1=JA+1
      J2=JB-1
        J = J1
88106   IF ( J .GT. J2 ) GOTO 99106
        IRET=2
        I=IA
        GO TO 110
  104   IRET=3
        I=IB
        GO TO 110
  106   J = J + 1
        GOTO 88106
99106   CONTINUE
      J=JB
      IRET=4
        I = IA
88108   IF ( I .GT. IB ) GOTO 99108
        GO TO 110
  108   I = I + 1
        GOTO 88108
99108   CONTINUE
C
C         DONE WITH COARSE GRID H NUMBERS,, SKIP TO END OF GRID LOOP.
      GO TO 120
C
C    *    *    *    *    *    *    *    *    *    *    *    *    *
C          COMPTD GO TO ROUTINE TO GET COARSE GRID H INTEGERS.
C
  110 L=L+1
      IF(L .LE. LBHI ) GO TO 112
C          ERROR
      WRITE (IOUTUPRT, 111) L,LBHI,NG
  111 FORMAT(1H1,2X,'*****IN SR LATBND, L=',I8,' IS .GT. LBHI=',I8,
     1 '. COARSE GRID=',I8)
C
      CALL EXIT(16)
C
  112 CONTINUE
C          III,JJJ ARE INDEXES FOR FINE GRID H TO LOWER LEFT OF
C          A COARSE GRID H POINT.
      III=2*I+II
      JJJ=2*J+JJ
C          INTEGER TO GATHER THAT FINE GRID H VALUE.
      LGSHI(L,NG,1)=III+(JJJ-1)*IMF
C          INTEGER TO SCATTER COARSE GRID H INTO ITS ARRAY.
      LGSHI(L,NG,2)=I+(J-1)*IMC
C
      GO TO ( 102, 104, 106, 108 ),IRET
C
CGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
C
C          END OF GRID LOOP IN COMPUTING INTERPOLATION NUMBERS.
  120 CONTINUE
C
C          GATHER-SCATTER INTEGERS AND COEFFS HAVE NOW BEEN
C          COMPUTED FOR ALL GRIDS.  PROCEED TO JOB AT HAND.
C
C         ENTRY FOR ACTUAL COMPUTATIONS ON BNDRYS.
C
  200 CONTINUE
      NF=NC+1
C
C          DO ONEWAY FROM GLOBAL WHEN NF .EQ. INGLB
C          0 MEANS REPLACE THE LATBND DATA, BUT NOT
C          UPDATE THE TENDENCY.
C
      IF( NF .EQ. INGLB ) THEN
         CALL ONEWAY (0)
         RETURN
      ENDIF
C
C          FIRST GET THE GRID DIMENSIONS FOR THE TWO GRIDS.
      IMC=IMG(NC)
      JMC=JMG(NC)
      IMF=IMG(NF)
      JMF=JMG(NF)
      IJC=IMC*JMC
      IJF=IMF*JMF
C
      IA=IAG(NC)
      IB=IBG(NC)
      JA=JAG(NC)
      JB=JBG(NC)
C
C
CHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
C          FIRST COMPUTE THE FINE GRID OUTER U VALUES.
C
C          GET THE BASE ADDRESSES FOR COARSE AND FINE GRID U.
      IADC=IADDRG(1,NC) - IJC
      IADF=IADDRG(1,NF) - IJF
C          NEEDUF IS NUMBER OF U VALUES NEEDED FOR FINE GRID.
      NEEDUF=8*IMF+7*JMF-56
C
      DO 210 K=1,KM
C
      IADC=IADC+IJC
      IADF=IADF+IJF
C          COMPUTE FULL COARSE GRID ARRAY OF LOWER LEFT FINE GRID U S.
CMIC$ DO ALL VECTOR SHARED(IJC, IADC, VBL, X) PRIVATE(IQ2W6E)
      DO 88891 IQ2W6E = 1, IJC
         X(IQ2W6E) = 0.75E0*VBL(IADC+IQ2W6E-1) + 0.25E0*VBL(IADC+IQ2W6E)
         X(IJC+IQ2W6E) = 0.25E0*VBL(IADC+IQ2W6E-1) + 0.75E0*VBL(IADC+
     1      IQ2W6E)
88891 CONTINUE
C          GET UPPER LEFT AND UPPER RIGHT U S BY J AVERAGING.
CMIC$ DO ALL VECTOR IF (ABS(IMC-2*IJC).GE.2*IJC .OR. IMC-2*IJC.EQ.0)
CMIC$1    SHARED(IJC, IMC, X) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E=1,2*IJC
         X(2*IJC+IQ2W6E)=0.5E0*(X(IQ2W6E)+X(IMC+IQ2W6E))
88910 CONTINUE
C          GATHER INTO ONE ARRAY OF NEEDED U VALUES.
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDUF, NC, LGSUO, X, Y) PRIVATE(I1X)
      DO 77061 I1X = 1, NEEDUF
         Y(I1X) = X(LGSUO(I1X,NC,1))
77061 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          CORRECT U ADDRESS AND DO SCATTER INTO FINE GRID U.
C
      IADF1=IADF-1
C*****  Code Expanded From Routine:  RDHSCATR
      DO 77062 I2X = 1, NEEDUF
         VBL(LGSUO(I2X,NC,2)+IADF-1) = Y(I2X)
77062 CONTINUE
C*****  End of Code Expanded From Routine:  RDHSCATR
C
  210 CONTINUE
C
CIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
C          COMPUTE THE FINE GRID V VALUES.
C
C          BASE ADDRESSES FOR COARSE AND FINE MESH V POINTS.
      IADC=IADDRG(2,NC)-IJC
      IADF=IADDRG(2,NF)-IJF
C          NEEDVF IS NUMBER OF FINE GRID V S NEEDED.
      NEEDVF=7*IMF+8*JMF-56
C
      DO 220 K=1,KM
C
      IADC=IADC+IJC
      IADF=IADF+IJF
C          COMPUTE FULL COARSE GRID ARRAY OF LOWER LEFT FINE GRID V S.
CMIC$ DO ALL VECTOR SHARED(IJC, IADC, IMC, VBL, X) PRIVATE(IQ2W6E)
      DO 88920 IQ2W6E = 1, IJC
         X(IQ2W6E) = 0.75E0*VBL(IADC+IQ2W6E-1) + 0.25E0*VBL(IADC+IMC+
     1      IQ2W6E-1)
         X(IJC+IQ2W6E) = 0.25E0*VBL(IADC+IQ2W6E-1) + 0.75E0*VBL(IADC+IMC
     1      +IQ2W6E-1)
88920 CONTINUE
C          GET LOWER RIGHT AND UPPER RIGHT V S BY I-AVERAGING.
CMIC$ DO ALL VECTOR IF (ABS(1-2*IJC).GE.2*IJC .OR. 1-2*IJC.EQ.0) SHARED(
CMIC$1   IJC, X) PRIVATE(IQ2W6E)
      DO 88940 IQ2W6E=1,2*IJC
         X(2*IJC+IQ2W6E)=0.5E0*(X(IQ2W6E)+X(IQ2W6E+1))
88940 CONTINUE
C          DO GATHER INTO Y OF THE NEEDED V VALUES.
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDVF, NC, LGSVO, X, Y) PRIVATE(I3X)
      DO 77063 I3X = 1, NEEDVF
         Y(I3X) = X(LGSVO(I3X,NC,1))
77063 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          CORRECT V ADDRESS AND SCATTER INTO FINE GRID V ARRAY
      IADF1=IADF-1
C*****  Code Expanded From Routine:  RDHSCATR
      DO 77064 I4X = 1, NEEDVF
         VBL(LGSVO(I4X,NC,2)+IADF-1) = Y(I4X)
77064 CONTINUE
C*****  End of Code Expanded From Routine:  RDHSCATR
C
  220 CONTINUE
C
CJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
C          COMPUTE THE FINE GRID OUTER H POINTS.
C
C          BASE ADDRESS FOR COARSE AND FINE GRID H POINTS.
      IADC=IADDRG(3,NC)-IJC
      IADF=IADDRG(3,NF)-IJF
C          NEEDHF IS THE NUMBER OF FINE GRID H S NEEDED.
      NEEDHF=7*(IMF+JMF-7)
C          KHINTERP FROM THE CALLING STATEMENT IS THE NUMBER OF
C          H ARRAYS TO BE PROCESSED.
C
      DO 230 K=1,KHINTERP
C
      IADC=IADC+IJC
      IADF=IADF+IJF
C          GATHER LOWER RIGHT COARSE H VALUES INTO X2.
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDHF,NC,IADC,LGSHO,VBL,X2)PRIVATE(I5X)
      DO 77065 I5X = 1, NEEDHF
         X2(I5X) = VBL(LGSHO(I5X,NC,1)+IADC)
77065 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          GATHER LOWER LEFT ONES INTO X1
      IADC1=IADC-1
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDHF,NC,IADC,LGSHO,VBL,X1)PRIVATE(I6X)
      DO 77066 I6X = 1, NEEDHF
         X1(I6X) = VBL(LGSHO(I6X,NC,1)+IADC-1)
77066 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          GET UPPER LEFT AND UPPER RIGHT VALUES, USING CORRECTED ADDR.
      IADC1=IADC1+IMC
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDHF,NC,IADC1,LGSHO,VBL,X3)PRIVATE(I7X)
      DO 77067 I7X = 1, NEEDHF
         X3(I7X) = VBL(LGSHO(I7X,NC,1)+IADC1)
77067 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
      IADC1=IADC1+1
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDHF,NC,IADC1,LGSHO,VBL,X4)PRIVATE(I8X)
      DO 77068 I8X = 1, NEEDHF
         X4(I8X) = VBL(LGSHO(I8X,NC,1)+IADC1)
77068 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          FORM LINEAR COMBINATION USING COEFF. ARRAY CH.
CMIC$ DO ALL VECTOR SHARED(NEEDHF, NC, X1, CH, X2, X3, X4) PRIVATE(
CMIC$1   IQ2W6E)
      DO 88950 IQ2W6E=1,NEEDHF
         X1(IQ2W6E)=X1(IQ2W6E)*CH(IQ2W6E,NC,1) +
     *              X2(IQ2W6E)*CH(IQ2W6E,NC,2) +
     *              X3(IQ2W6E)*CH(IQ2W6E,NC,3) +
     *              X4(IQ2W6E)*CH(IQ2W6E,NC,4)
88950 CONTINUE
C          SCATTER INTO THE FINE GRID H ARRAY
      IADF1=IADF-1
C*****  Code Expanded From Routine:  RDHSCATR
      DO 77069 I9X = 1, NEEDHF
         VBL(LGSHO(I9X,NC,2)+IADF-1) = X1(I9X)
77069 CONTINUE
C*****  End of Code Expanded From Routine:  RDHSCATR
C
  230 CONTINUE
C
C          DO LATBND FROM NGM COARSE GRID ONLY
C          SO NO UPDATE TO THE COARSE GRIDS,
C          I.E.  ONEWAY INFLENCE OF NGM.
C
C          DO TWO-WAY LATBND ONLY WHEN INGLB = 0
C
      IF( INGLB .NE. 0 ) RETURN
C
CKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
C          DO THE COARSE GRID U VALUES.
C
C          NEEDUC IS THE NUMBER OF COARSE GRID U VALUES NEEDED.
      NEEDUC=4*(IB-IA)+2*(JB-JA)
C          BASE ADDRESSES FOR COARSE AND FINE GRID U VBLS.
      IADC=IADDRG(1,NC)-IJC
      IADF=IADDRG(1,NF)-IJF
C
      DO 240 K=1,KM
C
      IADC=IADC+IJC
      IADF=IADF+IJF
C          GATHER FINE GRID U S TO RIGHT AND LEFT OF COARSE GRID U.
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDUC,NC,IADF,LGSUI,VBL,X2)PRIVATE(I10X)
      DO 77070 I10X = 1, NEEDUC
         X2(I10X) = VBL(LGSUI(I10X,NC,1)+IADF)
77070 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
      IADF1=IADF-1
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDUC,NC,IADF,LGSUI,VBL,X1)PRIVATE(I11X)
      DO 77071 I11X = 1, NEEDUC
         X1(I11X) = VBL(LGSUI(I11X,NC,1)+IADF-1)
77071 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          AVERAGE THEM TO GET COARSE GRID U S.
CMIC$ DO ALL VECTOR SHARED(NEEDUC, X1, X2, X3) PRIVATE(IQ2W6E)
      DO 89020 IQ2W6E=1,NEEDUC
         X3(IQ2W6E)=0.5E0*(X1(IQ2W6E)+X2(IQ2W6E))
89020 CONTINUE
C          SCATTER THEM INTO THE COARSE GRID U ARRAY.
      IADC1=IADC-1
C*****  Code Expanded From Routine:  RDHSCATR
      DO 77072 I12X = 1, NEEDUC
         VBL(LGSUI(I12X,NC,2)+IADC-1) = X3(I12X)
77072 CONTINUE
C*****  End of Code Expanded From Routine:  RDHSCATR
C
  240 CONTINUE
C
CLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
C          START ON COARSE GRID V VALUES.
C
C          NEEDVC IS THE NUMBER OF COARSE GRID V S NEEDED,
      NEEDVC=2*(IB-IA)+4*(JB-JA)
C          BASE ADDRESSES FOR THE V POINTS.
      IADC=IADDRG(2,NC)-IJC
      IADF=IADDRG(2,NF)-IJF
C
      DO 250 K=1,KM
C
      IADC=IADC+IJC
      IADF=IADF+IJF
C          GATHER FINE GRID V ABOVE AND BELOW THE COARSE GRID V POINT.
      IADF1=IADF-1
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDVC,NC,IADF,LGSVI,VBL,X1)PRIVATE(I13X)
      DO 77073 I13X = 1, NEEDVC
         X1(I13X) = VBL(LGSVI(I13X,NC,1)+IADF-1)
77073 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
      IADF1=IADF1+IMF
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDVC,NC,IADF1,LGSVI,VBL,X2)PRIVATE(I14X)
      DO 77074 I14X = 1, NEEDVC
         X2(I14X) = VBL(LGSVI(I14X,NC,1)+IADF1)
77074 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          AVERAGE THEM TO GET THE COARSE GRID V S.
CMIC$ DO ALL VECTOR SHARED(NEEDVC, X1, X2, X3) PRIVATE(IQ2W6E)
      DO 89030 IQ2W6E=1,NEEDVC
         X3(IQ2W6E)=0.5E0*(X1(IQ2W6E)+X2(IQ2W6E))
89030 CONTINUE
C          SCATTER THEM INTO THE COARSE GRID V ARRAY.
      IADC1=IADC-1
C*****  Code Expanded From Routine:  RDHSCATR
      DO 77075 I15X = 1, NEEDVC
         VBL(LGSVI(I15X,NC,2)+IADC-1) = X3(I15X)
77075 CONTINUE
C*****  End of Code Expanded From Routine:  RDHSCATR
C
  250 CONTINUE
C
CMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
C          START THE COARSE GRID H POINTS.
C
C          NEEDHC IS THE NEEDED NUMBER OF COARSE GRID H VALUES.
      NEEDHC=2*(IB-IA+JB-JA)
C          BASE ADDRESSES FOR THE H VBLS.
      IADC=IADDRG(3,NC)-IJC
      IADF=IADDRG(3,NF)-IJF
C          KHINTERP FROM THE CALLING STATEMENT IS THE TOTAL NUMBER OF
C          H ARRAYS TO BE PROCESSED.
C
      DO 260 K=1,KHINTERP
C
      IADC=IADC+IJC
      IADF=IADF+IJF
C     GATHER 4 SURROUNDING FINE GRID H VALUES.
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDHC,NC,IADF,LGSHI,VBL,X2)PRIVATE(I16X)
      DO 77076 I16X = 1, NEEDHC
         X2(I16X) = VBL(LGSHI(I16X,NC,1)+IADF)
77076 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
      IADF1=IADF-1
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDHC,NC,IADF,LGSHI,VBL,X1)PRIVATE(I17X)
      DO 77077 I17X = 1, NEEDHC
         X1(I17X) = VBL(LGSHI(I17X,NC,1)+IADF-1)
77077 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
      IADF1=IADF1+IMF
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDHC,NC,IADF1,LGSHI,VBL,X3)PRIVATE(I18X)
      DO 77078 I18X = 1, NEEDHC
         X3(I18X) = VBL(LGSHI(I18X,NC,1)+IADF1)
77078 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
      IADF1=IADF1+1
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(NEEDHC,NC,IADF1,LGSHI,VBL,X4)PRIVATE(I19X)
      DO 77079 I19X = 1, NEEDHC
         X4(I19X) = VBL(LGSHI(I19X,NC,1)+IADF1)
77079 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          AVERAGE THESE FOUR VALUES.
CMIC$ DO ALL VECTOR SHARED(NEEDHC, X1, X2, X3, X4) PRIVATE(IQ2W6E)
      DO 89040 IQ2W6E=1,NEEDHC
         X3(IQ2W6E)=0.25E0*(X1(IQ2W6E)+X2(IQ2W6E)+
     *              X3(IQ2W6E)+X4(IQ2W6E))
89040 CONTINUE
C          SCATTER THESE INTO THE COARSE GRID H ARRAY.
      IADC1=IADC-1
C*****  Code Expanded From Routine:  RDHSCATR
      DO 77080 I20X = 1, NEEDHC
         VBL(LGSHI(I20X,NC,2)+IADC-1) = X3(I20X)
77080 CONTINUE
C*****  End of Code Expanded From Routine:  RDHSCATR
C
  260 CONTINUE
C
C
      RETURN
      END
