      SUBROUTINE M1POLY(N,RAD,P)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    M1POLY      USED FOR COMPUTING GAUSSIAN LATS
C   PRGMMR: SELA             ORG: W/NMC22    DATE: 79-03-03
C
C ABSTRACT: COMPUTE LEGENDRE POLYNOMIAL OF ORDER N FOR USE BY
C   SUBROUTINE M1GLAT WHICH COMPUTES GAUSSIAN LATITUDES AND WEIGHTS.
C
C PROGRAM HISTORY LOG:
C   79-03-03  SELA
C   88-04-08  PARRISH   ADD DOCBLOCK
C
C USAGE:    CALL M1POLY(N,RAD,P)
C   INPUT ARGUMENT LIST:
C     N        - ORDER OF LEGENDRE POLYNOMIAL
C     RAD      - ARGUMENT FOR LEGENDRE POLYNOMIAL
C
C   OUTPUT ARGUMENT LIST:
C     P        - VALUE OF LEGENDRE POLYNOMIAL
C
C ATTRIBUTES:
C   LANGUAGE: FTN200
C   MACHINE:  CYBER
C
C$$$
      implicit double precision (a-h,o-z)
      X=  COS(RAD)
      Y1=1.d0
      Y2=X
      DO 1 I=2,N
      G=X*Y2
      Y3=G-Y1+G-(G-Y1)/FLOAT(I)
      Y1=Y2
      Y2=Y3
1     CONTINUE
      P=Y3
      RETURN
      END
