      SUBROUTINE ONEGRID ( NG , NPAIR, LASTSTEP )
C***  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    ONEGRID     ADVANCE GRID NG BY FULL LAX-WENDROFF STEP
C   PRGMMR: J TUCCILLO       ORG: W/NMC4      DATE: 90-06-25
C
C ABSTRACT:
C   .       ADVANCE THE SINGLE GRID NG IN TIME BY
C   .       ONE FULL LAX-WENDROFF TIME STEP.
C   .
C PROGRAM HISTORY LOG:
C   90-06-25  J TUCCILLO
C
C USAGE:  CALL ONEGRID( NG, NPAIR, LASTSTEP )
C   INPUT ARGUMENT LIST:
C     NG       - GRID NUMBER (OUTER HEMISPHERIC GRID HAS
C                NG EQUAL TO 1.)
C     NPAIR    - 1 FOR THE FIRST OF A PAIR OF CALLS TO
C                THIS GRID, 2 FOR THE SECOND OF A PAIR.
C     LASTSTEP - A FLAG WHICH WHEN EQUAL TO 1 INDICATES
C                THAT THIS IS THE LAST STEP FOR THIS
C                GRID WITHIN A COMPLETE (GRID A)
C                TIME STEP.
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - P2KAP
C     LIBRARY:
C       COMMON   - COMCONST
C                  COMBLANK
C                  COMDIAG
C
C REMARKS:
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES     MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----     ----------------------------------        ---------
C   VBL        ARRAY CONTAINING ALL VBLS FOR ALL GRIDS   COMMON
C   .
C   BITGRDX    (X = H, U, V) BIT VECTORS TO CONTROL      COMMON
C   .             STORAGE OF UPDATED VBLS ONLY AT
C   .             LEGITIMATE FORECAST POINTS.
C   .
C   BITSEA     BIT VECTOR (1 OVER WATER) TO ALLOW DIFF.  COMMON
C                 TREATMENTS OF SURFACE EXCHANGES.
C   .
C   IMG,JMG    HORIZONTAL DIMENSIONS OF ALL GRIDS.       COMMON
C   .
C   KM         NUMBER OF HORIZONTAL LVLS. FOR ALL GRIDS  COMMON
C   .
C   NH         NH + 0.5 IS THE NUMBER OF GRID INTERVALS  COMMON
C   .             ON GRID 1 BETWEEN POLE AND EQUATOR.
C   .
C   IAG,IBG,   GRID COORDINATES DEFINING THE 'HOLE' ON   COMMON
C   JAG,JBG    A COARSE GRID THAT IS COVERED BY THE      COMMON
C   .             NEXT FINER GRID.
C   .
C   IADDRG     INITIAL ADDRESSES IN VBL FOR EACH TYPE    COMMON
C   .             OF DATA FOR EACH GRID.
C   .
C   XPOLEH,    VALUES OF I AND J AT THE NORTH POLE FOR   COMMON
C   YPOLEH     H POINTS  ON ALL GRIDS.
C   .
C   DELSIG     VERTICAL SIGMA DIFFS. ACROSS EACH LAYER   COMMON
C   .
C   SIGINT     SIGMA VALUES AT THE KM + 1 INTERFACES.    COMMON
C   .
C   PR         HALF OF (1-SIGMA) TO THE KAPPA POWER.     COMMON
C   .
C   NTIME      TIME STEP(ADVANCES BY ONE FOR EACH STEP   COMMON
C   .             ON THE OUTER GRID(NG = 1) ).
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES     MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----     ----------------------------------        ---------
C   VBL        UPDATED VARIABLES.                         COMMON
C   .
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      include 'parmodel'
C
      PARAMETER ( P5 = 0.5, ZERO = 0.0, ONE = 1.0, P609 = 0.609,
     *            TWO = 2.0, ONEP5 = 1.5, IKMM1 = IKM - 1 )
      PARAMETER ( CSUBP = 1005.0E0 )
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:04:57
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      REAL C11U,C12U
C
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
      COMMON /COMDIAG/  KADIAB( IKM, INGRDUSE ),
     1                  NPTSDHQ (2, INGRDUSE),
     2                  KKCLOUD2(2, INGRDUSE), NPTSBUOY(2, INGRDUSE),
     3                  NPTSWATR(2, INGRDUSE), NPTSCC  (2, INGRDUSE),
     4                  KKGSP2  (2, INGRDUSE),
     5                  KKGSE2  (2, INGRDUSE),
     6                  NPTSSAT (IKM, 2, INGRDUSE),
     7                  NPTSEVAP(IKM, 2, INGRDUSE),
     8                  NPTSGSP (2, INGRDUSE), NUMPROF,
     9                  PPTCC   (2, INGRDUSE), PPTGSP  (2, INGRDUSE),
     1                  ALATPR  (IMAXPROF),    ALONPR  (IMAXPROF),
     2                  DESCRP  (IMAXPROF)
C
      CHARACTER*24 DESCRP
C
C              ARRAYS FOR MAP SCALE  AND CORIOLIS FACTORS,ETC.
      DIMENSION    DICOR(IIJMAX),  DJCOR(IIJMAX), SINLAT(IIJMAX),
     1             EM2C(IIJMAX),   EM2H(IIJMAX),  GRNDP(IIJMAX),
     2             EMU(IIJMAX),    EM2U(IIJMAX),  EMUIN(IIJMAX),
     3             EMV(IIJMAX),    EM2V(IIJMAX),  EMVIN(IIJMAX)
C
C              HORIZONTAL SCRATCH ARRAYS.
      DIMENSION    S1(IIJMAX),     S2(IIJMAX),    S3(IIJMAX),
     1             S4(IIJMAX),     S5(IIJMAX),    S6(IIJMAX),
     2             S7(IIJMAX),     S8(IIJMAX),    S9(IIJMAX) ,
     3             HP(IIJMAX),    S11(IIJMAX), S12(IIJMAX) ,
     4            S13(IIJMAX),    S14(IIJMAX), S15(IIJMAX) ,
     5            S16(IIJMAX),    S17(IIJMAX), S18(IIJMAX) ,
     6            S19(IIJMAX),    S20(IIJMAX), S21(IIJMAX) ,
     7            S22(IIJMAX),    S23(IIJMAX)
C
C              THREE-DIMENSIONAL SCRATCH ARRAYS.
      DIMENSION    U(IIJKMAX),     V(IIJKMAX),    TH(IIJKMAX),
     1             Q(IIJKMAX),
     2             UP(IIJKMAX),    VP(IIJKMAX),   THP(IIJKMAX),
     2             THPATH(IIJKMAX),
     3             QP(IIJKMAX),    QPATH(IIJKMAX),
     4             XDIS(IIJKMAX),  YDIS(IIJKMAX), ZDIS(IIJKMAX),
     5             W(IIJKMAX),     VT(IIJKMAX),   PSI(IIJKMAX),
     6             CORU(IIJKMAX),  CORV(IIJKMAX), FLX(IIJKMAX),
     7             CONV(IIJKMAX),  SBAR(IIJKMAX), FLY(IIJKMAX),
     8             DHQ(IIJKMAX),   FKS(IIJKMAX)
C
      DIMENSION   ABITGRDH(IIJMAX, 2, INGRDUSE),
     1            ABITGRDU(IIJMAX, 2, INGRDUSE),
     2            ABITGRDV(IIJMAX, 2, INGRDUSE)
C
      LOGICAL LFRST
      INTEGER I1X,I2X
      REAL COFD1,COFD2,COFD3,COFD4,COFN1,COFN2,COFN3
      PARAMETER (COFD1 = 1., COFD2 = 5.44053037, COFD3 = 2.27693825,
     1   COFD4 = -0.0869930591, COFN1 = 0.34757549, COFN2 = 4.36732956,
     2   COFN3 = 3.91557032)
      DATA LFRST / .TRUE. /
C
C              HORIZONTAL SCRATCH ARRAY EQUIVALENCES
      EQUIVALENCE  (SCR(1,1), S1   ),  (SCR(1,2), S2    ),
     1             (SCR(1,3), S3   ),  (SCR(1,4), S4    ),
     2             (SCR(1,5), S5   ),  (SCR(1,6), S6    ),
     3             (SCR(1,7), S7   ),  (SCR(1,8), S8    ),
     4             (SCR(1,9), S9   ),  (SCR(1,10),HP    ),
     5             (SCR(1,11),S11  ),   (SCR(1,12),S12   ),
     6             (SCR(1,13), S13  ),  (SCR(1,14),S14   ),
     7             (SCR(1,15), S15  ),  (SCR(1,16),S16   ),
     8             (SCR(1,17), S17  ),  (SCR(1,18),S18   ),
     9             (SCR(1,19), S19  ),  (SCR(1,20),S20   ),
     1             (SCR(1,21), S21  ),  (SCR(1,22),S22   ),
     2             (SCR(1,23), S23  )
C
C              GEOGRAPHY-RELATED HORIZONTAL SCRATCH ARRAYS.
      EQUIVALENCE  (SCRGEOG(1, 1),DICOR),
     1             (SCRGEOG(1, 2),DJCOR),  (SCRGEOG(1, 3),SINLAT),
     2             (SCRGEOG(1, 4),EM2C ),  (SCRGEOG(1, 5),EM2H  ),
     3             (SCRGEOG(1, 6),EMU  ),  (SCRGEOG(1, 7),EM2U  ),
     4             (SCRGEOG(1, 8),EMUIN),  (SCRGEOG(1, 9),EMV   ),
     5             (SCRGEOG(1,10),EM2V ),  (SCRGEOG(1,11),EMVIN ),
     6             (SCRGEOG(1,12),GRNDP)
C
C              THREE-DIMENSIONAL SCRATCH ARRAY EQUIVALENCES.
      EQUIVALENCE  (SCR3(1,1), U,          FLX               ),
     1             (SCR3(1,2), V,          FLY               ),
     2             (SCR3(1,3), TH,      SBAR                 ),
     3             (SCR3(1,4), Q,         DHQ                ),
     4             (SCR3(1,5), UP                            ),
     5             (SCR3(1,6), VP,  THPATH, QPATH            ),
     6             (SCR3(1,7), THP                           ),
     7             (SCR3(1,8), QP                            ),
     8             (SCR3(1,9), W,   XDIS, VT,  CORV          ),
     9             (SCR3(1,10),ZDIS,YDIS, PSI, CORU,CONV,FKS )
C
C
      IF ( LFRST ) THEN
C
        LFRST = .FALSE.
C
CMIC$ DO ALL VECTOR SHARED(BITGRDU, ABITGRDU, BITGRDV, ABITGRDV, BITGRDH
CMIC$1   , ABITGRDH) PRIVATE(IQ2)
        DO 5583 IQ2 = 1, IIJMAX * INGRDUSE * 2
         IF ( BITGRDU(IQ2,1,1) ) THEN
            ABITGRDU(IQ2,1,1) = ONE
         ELSE
            ABITGRDU(IQ2,1,1) = ZERO
         END IF
         IF ( BITGRDV(IQ2,1,1) ) THEN
            ABITGRDV(IQ2,1,1) = ONE
         ELSE
            ABITGRDV(IQ2,1,1) = ZERO
         END IF
         IF ( BITGRDH(IQ2,1,1) ) THEN
            ABITGRDH(IQ2,1,1) = ONE
         ELSE
            ABITGRDH(IQ2,1,1) = ZERO
         END IF
5583    CONTINUE
C
      END IF
C
CMIC$ DO ALL VECTOR SHARED(SCR) PRIVATE(IQ2)
      DO 2991 IQ2 = 1, IMAXSCR
         SCR(IQ2,1) = ZERO
 2991 CONTINUE
C
      SIGDOT = ZERO
C              GET THE GRID SIZE DIVIDED BY TWICE THE
C              EARTH RADIUS( = DXOV2R) FOR THIS GRID.
         DXOV2R = ONE / ((FLOAT(NH) + P5) * 2**(NG-1))
C
C              THE GRID SIZE IN METERS.
         DELX = TWO * RADIUS * DXOV2R
C
C              HALF THE RATIO OF DELTA TIME TO DELTA X.
         DTOV2DX = P5 * DTOVDX
C
C              ONE FULL TIME STEP IN SECONDS FOR THIS GRID.
         DTIME = DTOVDX * DELX
C
C              GRID ARRAY DIMENSIONS
         IM = IMG(NG)
         JM = JMG(NG)
         IJ = IM * JM
C
C              POLE COORDINATES IN I AND J FOR H POINTS.
         XIP = XPOLEH(NG)
         YJP = YPOLEH(NG)
C
C              ADDRESSES OF THE 1ST POINT(I,J,K)=(1,1,1) OF VBLS IN
C              ARRAY VBL.
         MADDU = IADDRG(1,NG)
         MADDV = IADDRG(2,NG)
         MADDT = IADDRG(3,NG)
         MADDQ = IADDRG(4,NG)
         MADDH = IADDRG(5,NG)
C
C              GET AVERAGED GROUND HEIGHT AT HP POINT.
C              GRNDP = G * GROUND-HEIGHT IN METER / CSUBP
      LEN22=IJ-3*IM
      LADD2 = 1 + IM
      JADD = IADDRG(10,NG)
CMIC$ PARALLEL SHARED(IJ, S20, GRNDP, JADD, IM, VBL) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 88980 IQ2=1,IJ
         S20(IQ2)=P5*(VBL(JADD+IQ2-1)+VBL(JADD+IM+IQ2-1))
88980 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89020 IQ2=1,IJ
         GRNDP(IQ2)=P5*(S20(IQ2)+S20(IQ2+1))
89020 CONTINUE
CMIC$ END PARALLEL
C
C--------------GET EM = SCALE FACTOR AT H, U, V, AND
C              H PRIME (DESIGNATED BY C) POINTS.
         C1 = (ONE   - XIP) * DXOV2R
         C2 = (ONEP5 - XIP) * DXOV2R
CMIC$ DO ALL VECTOR SHARED(IM, C1, DXOV2R, C2, S1, S2) PRIVATE(IQ2)
         DO 1001 IQ2 = 1, IM
            S1(IQ2) = ( C1 + DXOV2R*FLOAT(IQ2-1) ) ** 2
            S2(IQ2) = ( C2 + DXOV2R*FLOAT(IQ2-1) ) ** 2
1001     CONTINUE
         C1 = (ONE   - YJP) * DXOV2R
         C2 = (ONEP5 - YJP) * DXOV2R
CMIC$ DO ALL VECTOR SHARED(JM, C1, DXOV2R, C2, S3, S4) PRIVATE(IQ2)
         DO 1003 IQ2 = 1, JM
            S3(IQ2) = ( C1 + DXOV2R*FLOAT(IQ2-1) ) ** 2 + ONE
            S4(IQ2) = ( C2 + DXOV2R*FLOAT(IQ2-1) ) ** 2 + ONE
1003     CONTINUE
C
      I = 1 - IM
CMIC$ PARALLEL SHARED(IJ, EM2H, SINLAT, EMU, EM2U, EMV, EM2V, EMUIN,
CMIC$1   EMVIN, EM2C, JM, I, IM, S3, S1, S2, S4) PRIVATE(IQ2, J, C1,
CMIC$2   C11U)
CMIC$ DO PARALLEL
      DO 13 J = 1, JM
         C11U = S3(J)
         DO 77003 IQ2 = 1, IM
            EM2H(I+IQ2-1+J*IM) = C11U + S1(IQ2)
            EMV(I+IQ2-1+J*IM) = C11U + S2(IQ2)
77003    CONTINUE
         C11U = S4(J)
         DO 77004 IQ2 = 1, IM
            EMU(I+IQ2-1+J*IM) = C11U + S1(IQ2)
            EM2C(I+IQ2-1+J*IM) = C11U + S2(IQ2)
77004    CONTINUE
   13 CONTINUE
C
C--------------GET SINE OF THE LATITUDE AT H POINTS FROM THE
C              SCALE FACTOR.
CMIC$ DO PARALLEL VECTOR
      DO 89120 IQ2=1,IJ
         SINLAT(IQ2)=(TWO/EM2H(IQ2)) - ONE
C
C------------- GET EM SQUARED AT H, U, AND V POINTS.
         EM2H(IQ2)=EM2H(IQ2)*EM2H(IQ2)
         EM2U(IQ2)=EMU(IQ2)*EMU(IQ2)
         EM2V(IQ2)=EMV(IQ2)*EMV(IQ2)
C
C--------------GET RECIPROCAL OF EM AT U AND V POINTS
         EMUIN(IQ2)=ONE/EMU(IQ2)
         EMVIN(IQ2)=ONE/EMV(IQ2)
C
C------------- GET EM SQUARED AT THE H PRIME(C) POINT.
         EM2C(IQ2)=EM2C(IQ2)*EM2C(IQ2)
89120 CONTINUE
CMIC$ END PARALLEL
C
C--------------DTIME * (X - XP) / (2 * RADIUS**2) AT H PTS
C              IS PLACED INTO DICOR
C              AND  DTIME * (Y - YP) / (2 * RADIUS**2)
C              IS PLACED INTO DJCOR.
C
         C2 = TWO * DTOVDX * DXOV2R * DXOV2R
         C1 = C2 * (ONE - XIP)
CMIC$ DO ALL VECTOR SHARED(IM, C1, C2, S1) PRIVATE(IQ2)
         DO 2001 IQ2 = 1, IM
            S1(IQ2) = C1 + C2*FLOAT(IQ2-1)
2001     CONTINUE
         C1 = C2 * (ONE - YJP)
CMIC$ DO ALL VECTOR SHARED(JM, C1, C2, S3) PRIVATE(IQ2)
         DO 2002 IQ2 = 1, JM
            S3(IQ2) = C1 + C2*FLOAT(IQ2-1)
2002     CONTINUE
C
      I = 1 - IM
CMIC$ DO ALL SHARED(JM, I, IM, S3, DJCOR, S1, DICOR) PRIVATE(J, C1, IQ2)
      DO 14 J = 1, JM
         C1 = S3(J)
         DO 77005 IQ2 = 1, IM
            DJCOR(I+IQ2-1+J*IM) = C1
            DICOR(I+IQ2-1+J*IM) = S1(IQ2)
77005    CONTINUE
   14 CONTINUE
C
C--------------------- DETERMINE LIMITS ON J-ROWS
C
         J1 =  1
         J2 =  2
         J3 =  3
         JM0 = JM
         JM1 = JM - 1
         JM2 = JM - 2
C
C              IF THIS IS THE SECOND TIME STEP OF A PAIR, WE
C              MUST ADD (OR SUBTRACT) 2 .
      IF( NPAIR .LT. 2 ) GO TO 17
C
         J1  = J1 + 2
         J2  = J2 + 2
         J3  = J3 + 2
         JM0 = JM0 - 2
         JM1 = JM1 - 2
         JM2 = JM2 - 2
C
   17 CONTINUE
C
C------------- SET UP THE THREE STANDARD VECTOR INITIAL
C              ADDRESSES (RELATIVE TO A SINGLE HORIZONTAL
C              FIELD) THAT BEGIN WITH THE ROW.
C              J = J1,J2,J3
         LADD2 = IM * (J2 - 1) + 1
         LADD3 = IM * (J3 - 1) + 1
C
C------------- SET UP THE 6 POSSIBLE VECTOR LENGTHS FOR THE
C              BLOCKS OF J-ROWS J = JP THROUGH JMQ, WHERE
C              P STANDS FOR 1,2,OR 3 AND Q STANDS FOR
C              0,1, OR 2.
C
         LEN22 = IM * (JM2 - J2 + 1)
         LEN21 = IM * (JM1 - J2 + 1)
         LEN20 = IM * (JM0 - J2 + 1)
C
         LEN32 = IM * (JM2 - J3 + 1)
         LEN31 = IM * (JM1 - J3 + 1)
         LEN30 = IM * (JM0 - J3 + 1)
C
C================ CONVERGENCE FOR HALF TIME STEP =================
C
C              PRESET ADDRESSES FOR HU AND HV IN ARRAY VBL.
         JADDU = MADDU - 1 + LADD2 - IJ
         JADDV = MADDV - 1 + LADD2 - IJ
         JADD  = LADD2 - IJ
C
CFPP$ NODEPCHK L
CMIC$ DO ALL SHARED(JADDU, IJ, JADDV, JADD, LEN21, LADD2, LEN20, LADD3,
CMIC$1   DELSIG, VBL, EMUIN, EMVIN, EM2C, CONV) PRIVATE(S1, S2, K, C1,
CMIC$2   IQ2, C12U) SAVELAST
      DO 100 K = 1, 16
         C12U = -DELSIG(K)
C
         DO 77006 IQ2 = 1, LEN21
            S1(LADD2+IQ2-1) = VBL(JADDU+IJ*K+IQ2-1)*EMUIN(LADD2+IQ2-1)
77006    CONTINUE
C
         DO 77007 IQ2 = 1, LEN20
            S2(LADD2+IQ2-1) = VBL(JADDV+IJ*K+IQ2-1)*EMVIN(LADD2+IQ2-1)
77007    CONTINUE
C
C              PUT  - DELSIG TIMES FLUX DIFFS. * EM**2 INTO CONV
         DO 77008 IQ2 = 1, LEN21
            CONV(JADD+IJ*K+IQ2-1) = EM2C(LADD2+IQ2-1)*C12U*(S1(LADD2+IQ2
     1         )-S1(LADD2+IQ2-1)+S2(LADD3+IQ2-1)-S2(LADD2+IQ2-1))
77008    CONTINUE
  100 CONTINUE
C
C------------- COMPUTE THE VERTICAL SUM OF CONV, ACCUMULATING IT IN S1.
      JADD = LADD2 + IJ
CMIC$ DO ALL VECTOR SHARED(LEN21, LADD2, JADD, CONV, S1) PRIVATE(IQ2)
      DO 89320 IQ2=1,LEN21
         S1(LADD2+IQ2-1)=CONV(LADD2+IQ2-1)+CONV(JADD+IQ2-1)
89320 CONTINUE
C
      DO 105 K = 3,IKM
         JADD = JADD + IJ
CMIC$ DO ALL VECTOR SHARED(LEN21, LADD2, JADD, S1, CONV) PRIVATE(IQ2)
      DO 89330 IQ2=1,LEN21
         S1(LADD2+IQ2-1)=S1(LADD2+IQ2-1)+CONV(JADD+IQ2-1)
89330 CONTINUE
  105 CONTINUE
C
C              ARRAY S1 NOW HAS DDDH, WHICH EQUALS THE LOCAL
C              TIME DERIVATIVE OF SURFACE PRESSURE
C              AT C POINTS, J = J2,JM1.
C
      JADDH = LADD2 + MADDH - 1
CMIC$ PARALLEL SHARED(LEN21, DTOV2DX, LADD2, S1, S4, HP, JADDH, IM, VBL)
CMIC$1    PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 89340 IQ2=1,LEN21
         S4(LADD2+IQ2-1)=P5*(VBL(JADDH+IQ2-1)+VBL(JADDH+IM+IQ2-1))
89340 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89400 IQ2=1,LEN21
         HP(LADD2+IQ2-1)=DTOV2DX*S1(LADD2+IQ2-1)+
     *                   P5*(S4(LADD2+IQ2-1)+S4(LADD2+IQ2))
89400 CONTINUE
CMIC$ END PARALLEL
C
C------------- CONVERT CONV INTO W = H * DELX * D(SIGMA) / DT, J=J2,JM1.
      C1 = DELSIG(1)
CMIC$ DO ALL VECTOR SHARED(LEN21,LADD2,C1,IJ,CONV,S1,W)PRIVATE(IQ2)
      DO 89410 IQ2=1,LEN21
         W(LADD2+IJ+IQ2-1)=CONV(LADD2+IQ2-1)-C1*S1(LADD2+IQ2-1)
89410 CONTINUE
C
C              K = 2 ARRAY OF W NOW CONTAINS W FOR INTERFACE K = 2.
C              TOP NONZERO W,AT INTERFACE KM, WILL END UP AT LEVEL
C              KM OF ARRAY W.
      JADDW = LADD2 + IJ
      DO 110 K = 3,IKM
      C1    = DELSIG(K - 1)
      JADDW = JADDW + IJ
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN21 .OR. IJ.EQ.0) SHARED(LEN21,
CMIC$1   JADDW, IJ, C1, LADD2, CONV, W, S1) PRIVATE(IQ2)
      DO 89430 IQ2=1,LEN21
         W(JADDW+IQ2-1)=
     *   CONV(JADDW-IJ+IQ2-1)+W(JADDW-IJ+IQ2-1)-C1*S1(LADD2+IQ2-1)
89430 CONTINUE
  110 CONTINUE
C
C--------------GET RECIPROCAL OF H INTO S11, J = J2,JM0.
C
CMIC$ PARALLEL SHARED(LEN21, LADD2, S4, S3, LADD3, S11, LEN20, S2, JADDH
CMIC$1   , VBL) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 89440 IQ2=1,LEN20
         S11(LADD2+IQ2-1)=ONE/VBL(JADDH+IQ2-1)
89440 CONTINUE
C
C--------------AVERAGE IN I TO GET 1/H AT V PTS (S2, J = J2,JM0).
CMIC$ DO PARALLEL VECTOR
      DO 89450 IQ2=1,LEN20
         S2(LADD2+IQ2-1)=P5*(S11(LADD2+IQ2-1)+S11(LADD2+IQ2))
89450 CONTINUE
C
C--------------AVERAGE IN J FOR 1/H AT U  PTS (S4, J = J2,JM1).
CMIC$ DO PARALLEL VECTOR
      DO 89480 IQ2=1,LEN21
         S4(LADD2+IQ2-1)=P5*(S11(LADD2+IQ2-1)+S11(LADD3+IQ2-1))
89480 CONTINUE
C
C------------- GET I AVERAGE OF THESE FOR CENTER PT. (S3, J = J2,JM1).
CMIC$ DO PARALLEL VECTOR
      DO 89510 IQ2=1,LEN21
         S3(LADD2+IQ2-1)=P5*(S4(LADD2+IQ2-1)+S4(LADD2+IQ2))
89510 CONTINUE
CMIC$ END PARALLEL
C
C              WE CAN CHANGE HU,HV,HTH,AND HQ TO U,V,TH,AND Q WHERE
C              WE HAVE THE VALUES 1/H.
C
         JADDUH = MADDU - 1 + LADD2 - IJ
         JADDVH = MADDV - 1 + LADD2 - IJ
         JADDTH = MADDT - 1 + LADD2 - IJ
         JADDQH = MADDQ - 1 + LADD2 - IJ
         JADD   = LADD2 - IJ
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADDUH, IJ, JADDVH, JADDTH, JADDQH, JADD, LEN21,
CMIC$1   LADD2, LEN20, VBL, S4, U, S2, V, S11, TH, Q) PRIVATE(K, IQ2)
      DO 200 K = 1, 16
         DO 77009 IQ2 = 1, LEN21
            U(JADD+IJ*K+IQ2-1) = VBL(JADDUH+IJ*K+IQ2-1)*S4(LADD2+IQ2-1)
77009    CONTINUE
         DO 77010 IQ2 = 1, LEN20
            V(JADD+IJ*K+IQ2-1) = VBL(JADDVH+IJ*K+IQ2-1)*S2(LADD2+IQ2-1)
            TH(JADD+IJ*K+IQ2-1)=VBL(JADDTH+IJ*K+IQ2-1)*S11(LADD2+IQ2-1)
            Q(JADD+IJ*K+IQ2-1) = VBL(JADDQH+IJ*K+IQ2-1)*S11(LADD2+IQ2-1)
77010    CONTINUE
  200 CONTINUE
C
C--------------PUT AVERAGES OF TH, Q, AND V INTO HALF TIME ARRAYS,
C              FOR ROWS J2 THRU JM1.
      JADD  = LADD2 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN20, LADD2, LEN21, LADD3, TH, Q, V, THP
CMIC$1   , QP, VP) PRIVATE(S5, S6, S7, K, IQ2) SAVELAST
      DO 205 K = 1, 16
C            AVERAGE OF TH TO THP AT HP POINT
C              DITTO FOR Q.
C              FOR V WE NEED BACKWARD I AVERAGING.
         DO 77011 IQ2 = 1, LEN20
            S5(LADD2+IQ2-1)=0.5*(TH(JADD+IJ*K+IQ2-1)+TH(JADD+IJ*K+IQ2))
            S6(LADD2+IQ2-1) = 0.5*(Q(JADD+IJ*K+IQ2-1)+Q(JADD+IJ*K+IQ2))
            S7(LADD2+IQ2-1)=0.5*(V(JADD+IJ*K-2+IQ2)+V(JADD+IJ*K+IQ2-1))
77011    CONTINUE
         DO 77012 IQ2 = 1, LEN21
            THP(JADD+IJ*K+IQ2-1) = 0.5*(S5(LADD2+IQ2-1)+S5(LADD3+IQ2-1))
            QP(JADD+IJ*K+IQ2-1) = 0.5*(S6(LADD2+IQ2-1)+S6(LADD3+IQ2-1))
            VP(JADD+IJ*K+IQ2-1) = 0.5*(S7(LADD2+IQ2-1)+S7(LADD3+IQ2-1))
77012    CONTINUE
  205 CONTINUE
C
C------------- PUT HORIZONTAL AVG OF U INTO HALF TIME ARRAY,
C              FOR J3,JM1.
      JADD  = LADD2 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, LADD2, LEN31, LADD3, IM, U, UP)
CMIC$1    PRIVATE(S5, K, IQ2) SAVELAST
      DO 210 K = 1, 16
         DO 77013 IQ2 = 1, LEN21
            S5(LADD2+IQ2-1) = 0.5*(U(JADD+IJ*K+IQ2-1)+U(JADD+IJ*K+IQ2))
77013    CONTINUE
         DO 77014 IQ2 = 1, LEN31
            UP(JADD+IJ*K+IM+IQ2-1) = 0.5*(S5(LADD2+IQ2-1)+S5(LADD3+IQ2-1
     1         ))
77014    CONTINUE
  210 CONTINUE
C
C------------- CONVERT W INTO ZDIS USING 1/H AT CENTER POINT.
C              DO THIS FOR J2,JM1.  1/H IS IN S3.
C
      JADDW = LADD2
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADDW, IJ, DTOV2DX, LEN21, LADD2, DELSIG, W, S3,
CMIC$1   ZDIS) PRIVATE(K, C1, IQ2)
      DO 215 K = 1, 15
         C1 = -DTOV2DX/(DELSIG(1+K)+DELSIG(K))
         DO 77015 IQ2 = 1, LEN21
            ZDIS(JADDW+IJ*K+IQ2-1) = W(JADDW+IJ*K+IQ2-1)*C1*S3(LADD2+IQ2
     1         -1)
77015    CONTINUE
  215 CONTINUE
C
C              NONZERO VALUES OF ZDIS(K = 2,KM) ARE AT THE
C              CORRECT PLACE IN THE ZDIS ARRAY.
C
C---VER TH---- DO VERTICAL ADVECTION OF THETA.  FIRST
C              COMPUTE ZDIS(K) * (TH(K) - TH(K-1) ) FOR K=2,KM,
C              AND STORE IN W.
      JADD  = LADD2
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, ZDIS, THP, W) PRIVATE(K, IQ2)
      DO 220 K = 1, 15
         DO 77016 IQ2 = 1, LEN21
            W(JADD+IJ*K+IQ2-1) = ZDIS(JADD+IJ*K+IQ2-1)*(THP(JADD+IJ*K+
     1         IQ2-1)-THP(JADD+IJ*(K-1)+IQ2-1))
77016    CONTINUE
  220 CONTINUE
      JADD = 15*IJ + JADD
CMIC$ PARALLEL SHARED(LEN21, JADD, THP, W, LADD2, IJ) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 89860 IQ2=1,LEN21
         THP(LADD2+IQ2-1)=THP(LADD2+IQ2-1)+W(LADD2+IJ+IQ2-1)
89860 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89861 IQ2=1,LEN21
         THP(JADD+IQ2-1)=THP(JADD+IQ2-1)+W(JADD+IQ2-1)
89861 CONTINUE
CMIC$ END PARALLEL
C
      JADD  = LADD2
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, THP, W) PRIVATE(K, IQ2)
      DO 225 K = 1, 14
         DO 77017 IQ2 = 1, LEN21
            THP(JADD+IJ*K+IQ2-1) = THP(JADD+IJ*K+IQ2-1) + W(JADD+IJ*K+
     1         IQ2-1) + W(JADD+IJ*(K+1)+IQ2-1)
77017    CONTINUE
  225 CONTINUE
C
C---VER Q------DO THE VERTICAL ADVECTION OF THE SPECIFIC HUMIDITY.
      JADD  = LADD2
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, ZDIS, QP, W) PRIVATE(K, IQ2)
      DO 230 K = 1, 15
         DO 77018 IQ2 = 1, LEN21
            W(JADD+IJ*K+IQ2-1) = ZDIS(JADD+IJ*K+IQ2-1)*(QP(JADD+IJ*K+IQ2
     1         -1)-QP(JADD+IJ*(K-1)+IQ2-1))
77018    CONTINUE
  230 CONTINUE
      JADD = 15*IJ + JADD
CMIC$ PARALLEL SHARED(LEN21, JADD, QP, W, LADD2, IJ) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 12920 IQ2=1,LEN21
         QP(LADD2+IQ2-1)=QP(LADD2+IQ2-1)+W(LADD2+IJ+IQ2-1)
12920 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 12921 IQ2=1,LEN21
         QP(JADD+IQ2-1)=QP(JADD+IQ2-1)+W(JADD+IQ2-1)
12921 CONTINUE
CMIC$ END PARALLEL
C
      JADD  = LADD2
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, QP, W) PRIVATE(K, IQ2)
      DO 235 K = 1, 14
         DO 77019 IQ2 = 1, LEN21
            QP(JADD+IJ*K+IQ2-1) = QP(JADD+IJ*K+IQ2-1) + W(JADD+IJ*K+IQ2-
     1         1) + W(JADD+IJ*(K+1)+IQ2-1)
77019    CONTINUE
  235 CONTINUE
C
C---VER U------THE VERTICAL ADVECTION OF U IS SIMILAR EXCEPT THAT A
C              BACKWARD J-AVERAGING OF ZDIS IS NECESSARY.
      JADD  = LADD3
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, IM, UP, ZDIS, W) PRIVATE(K, IQ2)
      DO 240 K = 1, 15
         DO 77020 IQ2 = 1, LEN31
            W(JADD+IJ*K+IQ2-1) = (UP(JADD+IJ*K+IQ2-1)-UP(JADD+IJ*(K-1)+
     1         IQ2-1))*(0.5*(ZDIS(JADD+IJ*K-IM+IQ2-1)+ZDIS(JADD+IJ*K+IQ2
     2         -1)))
77020    CONTINUE
  240 CONTINUE
      JADD = 15*IJ + JADD
CMIC$ PARALLEL SHARED(LEN31, JADD, UP, W, LADD3, IJ) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 89990 IQ2=1,LEN31
         UP(LADD3+IQ2-1)=UP(LADD3+IQ2-1)+W(LADD3+IJ+IQ2-1)
89990 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89991 IQ2=1,LEN31
         UP(JADD+IQ2-1)=UP(JADD+IQ2-1)+W(JADD+IQ2-1)
89991 CONTINUE
CMIC$ END PARALLEL
C
      JADD  = LADD3
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, UP, W) PRIVATE(K, IQ2)
      DO 245 K = 1, 14
         DO 77021 IQ2 = 1, LEN31
            UP(JADD+IJ*K+IQ2-1) = UP(JADD+IJ*K+IQ2-1) + W(JADD+IJ*K+IQ2-
     1         1) + W(JADD+IJ*(K+1)+IQ2-1)
77021    CONTINUE
  245 CONTINUE
C
C---VER V----- THE VERTICAL ADVECTION OF V NEEDS BACKWARD
C              I-AVERAGE OF ZDIS.
      JADD  = LADD2
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, VP, ZDIS, W) PRIVATE(K, IQ2)
      DO 250 K = 1, 15
         DO 77022 IQ2 = 1, LEN21
            W(JADD+IJ*K+IQ2-1) = (VP(JADD+IJ*K+IQ2-1)-VP(JADD+IJ*(K-1)+
     1         IQ2-1))*(0.5*(ZDIS(JADD+IJ*K-2+IQ2)+ZDIS(JADD+IJ*K+IQ2-1)
     2         ))
77022    CONTINUE
  250 CONTINUE
      JADD = 15*IJ + JADD
CMIC$ PARALLEL SHARED(LEN21, JADD, VP, W, LADD2, IJ) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 90060 IQ2=1,LEN21
         VP(LADD2+IQ2-1)=VP(LADD2+IQ2-1)+W(LADD2+IJ+IQ2-1)
90060 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 90061 IQ2=1,LEN21
         VP(JADD+IQ2-1)=VP(JADD+IQ2-1)+W(JADD+IQ2-1)
90061 CONTINUE
CMIC$ END PARALLEL
C
      JADD  = LADD2
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, VP, W) PRIVATE(K, IQ2)
      DO 255 K = 1, 14
         DO 77023 IQ2 = 1, LEN21
            VP(JADD+IJ*K+IQ2-1) = VP(JADD+IJ*K+IQ2-1) + W(JADD+IJ*K+IQ2-
     1         1) + W(JADD+IJ*(K+1)+IQ2-1)
77023    CONTINUE
  255 CONTINUE
C
C=====================HORIZONTAL ADVECTION===========================
C
      JADD  = LADD2 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, LADD2, LEN20, EMU, U, XDIS, EMV, V
CMIC$1   , YDIS) PRIVATE(K, IQ2)
      DO 260 K = 1, 16
         DO 77024 IQ2 = 1, LEN21
            XDIS(JADD+IJ*K+IQ2-1) = -EMU(LADD2+IQ2-1)*U(JADD+IJ*K+IQ2-1)
77024    CONTINUE
         DO 77025 IQ2 = 1, LEN20
            YDIS(JADD+IJ*K+IQ2-1) = -EMV(LADD2+IQ2-1)*V(JADD+IJ*K+IQ2-1)
77025    CONTINUE
  260 CONTINUE
C
C---ADV TH AND Q
C
      JADD  = LADD2 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, IM, LADD2, LEN20, DTOV2DX, LADD3,
CMIC$1   TH, Q, XDIS, YDIS, QP, THP) PRIVATE(S6, S9, S7, S8, K, IQ2, S5S
CMIC$2   , S6S) SAVELAST
      DO 270 K = 1, 16
C
         DO 77026 IQ2 = 1, LEN21
            S6(LADD2+IQ2-1) = 0.5*(TH(JADD+IJ*K+IM+IQ2-1)+TH(JADD+IJ*K+
     1         IQ2-1))
            S9(LADD2+IQ2-1) = 0.5*(Q(JADD+IJ*K+IM+IQ2-1)+Q(JADD+IJ*K+IQ2
     1         -1))
77026    CONTINUE
         DO 77027 IQ2 = 1, LEN20
            S7(LADD2+IQ2-1)=0.5*(TH(JADD+IJ*K+IQ2)+TH(JADD+IJ*K+IQ2-1))
            S8(LADD2+IQ2-1) = 0.5*(Q(JADD+IJ*K+IQ2)+Q(JADD+IJ*K+IQ2-1))
77027    CONTINUE
C
         DO 77028 IQ2 = 1, LEN21
            S5S = 0.5*(XDIS(JADD+IJ*K+IQ2-1)+XDIS(JADD+IJ*K+IQ2))
            S6S = 0.5*(YDIS(JADD+IJ*K+IQ2-1)+YDIS(JADD+IJ*K+IM+IQ2-1))
C
            QP(JADD+IJ*K+IQ2-1) = QP(JADD+IJ*K+IQ2-1) + DTOV2DX*((S9(
     1         LADD2+IQ2)-S9(LADD2+IQ2-1))*S5S+S6S*(S8(LADD3+IQ2-1)-S8(
     2         LADD2+IQ2-1)))
C
            THP(JADD+IJ*K+IQ2-1) = THP(JADD+IJ*K+IQ2-1) + DTOV2DX*((S6(
     1         LADD2+IQ2)-S6(LADD2+IQ2-1))*S5S+S6S*(S7(LADD3+IQ2-1)-S7(
     2         LADD2+IQ2-1)))
77028    CONTINUE
  270 CONTINUE
C
C
C---ADV U
C
      JADD  = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN21, IM, LADD2, LEN31, LADD3, DTOV2DX, U
CMIC$1   , XDIS, UP, YDIS) PRIVATE(S8, S6, S7, K, IQ2) SAVELAST
      DO 280 K = 1, 16
C
         DO 77029 IQ2 = 1, LEN21
            S8(LADD2+IQ2-1) = 0.5*(U(JADD+IJ*K-IM+IQ2-1)+U(JADD+IJ*K-IM+
     1         IQ2))
77029    CONTINUE
         DO 77030 IQ2 = 1, LEN31
            S6(LADD3+IQ2-1) = 0.5*(XDIS(JADD+IJ*K+IQ2-1)+XDIS(JADD+IJ*K-
     1         IM+IQ2-1))
            S7(LADD3+IQ2-1) = 0.5*(U(JADD+IJ*K+IQ2-1)+U(JADD+IJ*K-IM+IQ2
     1         -1))
77030    CONTINUE
C
         DO 77031 IQ2 = 1, LEN31
C              ADD XDIS TIMES I DIFFERENCE OF U TERM TO UP.
C              ADD YDIS TIMES J DIFFERENCE OF U TERM TO UP.
            UP(JADD+IJ*K+IQ2-1) = UP(JADD+IJ*K+IQ2-1) + DTOV2DX*((S7(
     1         LADD3+IQ2)-S7(LADD3+IQ2-1))*0.5*(S6(LADD3+IQ2)+S6(LADD3+
     2         IQ2-1))+YDIS(JADD+IJ*K+IQ2-1)*(S8(LADD3+IQ2-1)-S8(LADD2+
     3         IQ2-1)))
77031    CONTINUE
  280 CONTINUE
C
C
C---ADV V
C
      JADD  = LADD2 - IJ
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN20, LADD2, LEN21, IM, DTOV2DX, LADD3,
CMIC$1   YDIS, V, VP, XDIS) PRIVATE(S8, S7, S6, K, IQ2) SAVELAST
      DO 290 K = 1, 16
         DO 77032 IQ2 = 1, LEN20
            S8(LADD2+IQ2-1) = 0.5*(YDIS(JADD+IJ*K+IQ2-1)+YDIS(JADD+IJ*K-
     1         2+IQ2))
            S7(LADD2+IQ2-1)=0.5*(V(JADD+IJ*K+IQ2-1)+V(JADD+IJ*K-2+IQ2))
77032    CONTINUE
C
         DO 77033 IQ2 = 1, LEN21
            S6(LADD2+IQ2-1) = 0.5*(V(JADD+IJ*K+IQ2-1)+V(JADD+IJ*K+IM+IQ2
     1         -1))
77033    CONTINUE
C
         DO 77034 IQ2 = 1, LEN21
            VP(JADD+IJ*K+IQ2-1) = VP(JADD+IJ*K+IQ2-1) + DTOV2DX*((S6(
     1         LADD2+IQ2-1)-S6(LADD2-2+IQ2))*XDIS(JADD+IJ*K+IQ2-1)+(S7(
     2         LADD3+IQ2-1)-S7(LADD2+IQ2-1))*0.5*(S8(LADD3+IQ2-1)+S8(
     3         LADD2+IQ2-1)))
77034    CONTINUE
  290 CONTINUE
C
C
C
C================= HYDROSTATIC FOR HALF TIME STEP ==============
C
C------------- DO THE HYDROSTATIC COMPUTATIONS,J = J2,JM0.
C              MAKE VIRTUAL TEMPERATURE CORRECTION TO THETA.
      JADD  = LADD2 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN20, Q, TH, VT) PRIVATE(K, IQ2)
      DO 300 K = 1, 16
         DO 77035 IQ2 = 1, LEN20
            VT(JADD+IJ*K+IQ2-1) = (1.0+0.609*Q(JADD+IJ*K+IQ2-1))*TH(JADD
     1         +IJ*K+IQ2-1)
77035    CONTINUE
  300 CONTINUE
C
C-------------- GET SFC PRESS(H) **KAPPA INTO S9(J2,JM0)
      LADKAPPA = MADDH - 1 + LADD2
C
C*****  Code Expanded From Routine:  P2KAP
CMIC$ DO ALL VECTOR SHARED(LEN20, LADKAPPA, LADD2, VBL, S9) PRIVATE(I1X)
      DO 77001 I1X = 1, LEN20
         S9(I1X+LADD2-1) = (0.34757549+VBL(I1X+LADKAPPA-1)*(4.36732956+
     1      VBL(I1X+LADKAPPA-1)*3.91557032))/(1.+VBL(I1X+LADKAPPA-1)*(
     2      5.44053037+VBL(I1X+LADKAPPA-1)*(2.27693825+VBL(I1X+LADKAPPA-
     3      1)*(-0.0869930591))))
77001 CONTINUE
C*****  End of Code Expanded From Routine:  P2KAP
C
C------------- COMPUTE PSI FOR K = 1,(J2,JM0).
      C1 = ONE - TWO * PR(1)
      JADD = IADDRG(10,NG) - 1 + LADD2
CMIC$ DO ALL VECTOR SHARED(LEN20, C1, LADD2, JADD, VT, S9, VBL, PSI)
CMIC$1    PRIVATE(IQ2)
      DO 90960 IQ2=1,LEN20
         PSI(LADD2+IQ2-1)= C1 * VT(LADD2+IQ2-1) *
     *             S9(LADD2+IQ2-1) + VBL(JADD+IQ2-1)
90960 CONTINUE
C
C              NOW EXTEND TO PSI AT K = 2,KM
      JADD  = LADD2
      DO 320 K = 2,IKM
         JADD  = JADD + IJ
         C1 = PR(K - 1) - PR(K)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN20 .OR. IJ.EQ.0) SHARED(LEN20,
CMIC$1   JADD, IJ, C1, LADD2, PSI, VT, S9) PRIVATE(IQ2)
      DO 90990 IQ2=1,LEN20
         PSI(JADD+IQ2-1)=PSI(JADD-IJ+IQ2-1)+
     *         C1*(VT(JADD+IQ2-1)+VT(JADD-IJ+IQ2-1))*
     *         S9(LADD2+IQ2-1)
90990 CONTINUE
  320 CONTINUE
C
C========================PRESSURE GRADIENT FORCE======================
C
C---PGF U----- COMPUTE U ACCEL. TERM AND ADD TO UP(J3,JM1).
C
      C2 = CSUBP * DTOV2DX
C
CMIC$ DO ALL VECTOR SHARED(LEN31, LADD3, S9, S6) PRIVATE(IQ2)
      DO 91020 IQ2=1,LEN31
         S6(LADD3+IQ2-1)=S9(LADD3+IQ2)-S9(LADD3+IQ2-1)
91020 CONTINUE
C
      JADD  = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ PARALLEL SHARED(LEN21, LADD3, LADD2, S9, S6, JADD, IJ, LEN31, C2,
CMIC$1   PR, UP, VT, PSI, EMV) PRIVATE(IQ2, K, C1)
CFPP$ NODEPCHK
CMIC$ DO PARALLEL
      DO 330 K = 1, 16
         C1 = PR(K)*2.E0
         DO 77036 IQ2 = 1, LEN31
            UP(JADD+IJ*K+IQ2-1) = UP(JADD+IJ*K+IQ2-1) - C2*(C1*0.5*(VT(
     1         JADD+IJ*K+IQ2-1)+VT(JADD+IJ*K+IQ2))*S6(LADD3+IQ2-1)+PSI(
     2         JADD+IJ*K+IQ2)-PSI(JADD+IJ*K+IQ2-1))*EMV(LADD3+IQ2-1)
77036    CONTINUE
  330 CONTINUE
C
C---PGF V------COMPUTE V ACCELERATION TERM AND ADD TO VP(J2,JM1).
CMIC$ DO PARALLEL VECTOR
      DO 91150 IQ2=1,LEN21
         S6(LADD2+IQ2-1)=S9(LADD3+IQ2-1)-S9(LADD2+IQ2-1)
91150 CONTINUE
CMIC$ END PARALLEL
C
      JADD  = LADD2 - IJ
CFPP$ NODEPCHK
CMIC$ PARALLEL SHARED(LEN20, LADD2, MADDH, SINLAT, VBL, S5, JADD, IJ,
CMIC$1   LEN21, C2, IM, PR, VP, VT, S6, PSI, EMU) PRIVATE(IQ2, K, C1)
CFPP$ NODEPCHK
CMIC$ DO PARALLEL
      DO 340 K = 1, 16
         C1 = PR(K)*2.0
         DO 77037 IQ2 = 1, LEN21
            VP(JADD+IJ*K+IQ2-1) = VP(JADD+IJ*K+IQ2-1) - C2*(C1*0.5*(VT(
     1         JADD+IJ*K+IQ2-1)+VT(JADD+IJ*K+IM+IQ2-1))*S6(LADD2+IQ2-1)+
     2         PSI(JADD+IJ*K+IM+IQ2-1)-PSI(JADD+IJ*K+IQ2-1))*EMU(LADD2+
     3         IQ2-1)
77037    CONTINUE
  340 CONTINUE
C
C ======================= CORIOLIS FORCE ===========================
C
C              FIRST PUT SINE LATITUDE TIMES H INTO S5(J2,JM0).
CMIC$ DO PARALLEL VECTOR
      DO 91280 IQ2=1,LEN20
         S5(LADD2+IQ2-1)=SINLAT(LADD2+IQ2-1)*VBL(MADDH+LADD2+IQ2-2)
91280 CONTINUE
CMIC$ END PARALLEL
         C1 = TWO * ANGVEL * DTIME
C
C
         JADD  = LADD2 - IJ
         JADDU = MADDU - 1 + JADD
         JADDV = MADDV - 1 + JADD
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, JADDU, JADDV, LEN20, IM, LADD2, C1, LEN21
CMIC$1   , LADD3, VBL, DJCOR, DICOR, S5, CORU, CORV) PRIVATE(S6, S7, K,
CMIC$2   IQ2) SAVELAST
      DO 400 K = 1, 16
C
         DO 77038 IQ2 = 1, LEN20
            S6(LADD2+IQ2-1) = 0.5*(VBL(JADDU+IJ*K+IQ2-1)+VBL(JADDU+IJ*K-
     1         IM+IQ2-1))
            S7(LADD2+IQ2-1) = 0.5*(VBL(JADDV+IJ*K-2+IQ2)+VBL(JADDV+IJ*K+
     1         IQ2-1))
            S6(LADD2+IQ2-1) = DJCOR(LADD2+IQ2-1)*S6(LADD2+IQ2-1) - DICOR
     1         (LADD2+IQ2-1)*S7(LADD2+IQ2-1) + C1*S5(LADD2+IQ2-1)
77038    CONTINUE
C
C              S6 NOW CONTAINS THE QUANTITY (H * DTIME) TIMES
C              ( 2 * ANGVEL * SIN(LATITUDE)
C              + (U * Y - V * X) / (2 * RADIUS * RADIUS)),
C              AT H POINTS.
C              AVERAGE S6 IN J TO GET CORU(J2,JM1).
         DO 77039 IQ2 = 1, LEN21
            CORU(JADD+IJ*K+IQ2-1)=0.5*(S6(LADD2+IQ2-1)+S6(LADD3+IQ2-1))
            CORV(JADD+IJ*K+IQ2-1) = 0.5*(S6(LADD2+IQ2-1)+S6(LADD2+IQ2))
77039    CONTINUE
  400 CONTINUE
C
C
C--------------DO THE CORIOLIS ACCELERATIONS FOR THE HALF TIME STEP.
C              FIRST FOR UP(J3,JM1).
C              S2 STILL HAS 1/H AT V POINTS.
      JADD  = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD,IJ,LEN31,LADD3,UP,CORV,V,S2)PRIVATE(K,IQ2)
      DO 410 K = 1, 16
         DO 77040 IQ2 = 1, LEN31
            UP(JADD+IJ*K+IQ2-1) = UP(JADD+IJ*K+IQ2-1) + 0.5*CORV(JADD+IJ
     1         *K+IQ2-1)*V(JADD+IJ*K+IQ2-1)*S2(LADD3+IQ2-1)
77040    CONTINUE
  410 CONTINUE
C
C--------------DO CORIOLIS ACCEL. FOR THE HALF TIME STEP VP(J2,JM1).
C              S4 STILL HAS 1/H AT U POINTS.
      JADD = LADD2 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD,IJ,LEN21,LADD2,VP,CORU,U,S4)PRIVATE(K,IQ2)
      DO 420 K = 1, 16
         DO 77041 IQ2 = 1, LEN21
            VP(JADD+IJ*K+IQ2-1) = VP(JADD+IJ*K+IQ2-1) - 0.5*CORU(JADD+IJ
     1         *K+IQ2-1)*U(JADD+IJ*K+IQ2-1)*S4(LADD2+IQ2-1)
77041    CONTINUE
  420 CONTINUE
C
C************* START THE FULL TIME STEP **************************
C
C--------------PRESET ADDRESSES FOR (VP,THP,QP) AND FOR UP.
C              (J3,JM1) FOR UP, (J=J2,JM1) FOR VP, THP, AND QP.
C
C------------- FIX THE PRESET ADDRESSES IN VBL FOR ENTRY INTO K-LOOPS
C              THAT STORE MODIFIED VARIABLE BACK INTO ARRAY VBL.
         III = LADD3 - 1 - IJ
         NADDU = MADDU + III
         NADDV = MADDV + III
         NADDT = MADDT + III
         NADDQ = MADDQ + III
C
C------------- DO CORIOLIS FORCE FOR HU(J3,JM2) AND HV(J3,JM1),
      JADDU = NADDU
      JADDV = NADDV
      JADD  = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ PARALLEL SHARED(LEN31, LADD2, LADD3, HP, S2, EMVIN, S5, LEN21, S1
CMIC$1   , EMUIN, S6, JADDU, IJ, JADDV, JADD, LEN32, NPAIR, NG, VBL,
CMIC$2   ABITGRDU, CORU, VP, ABITGRDV, CORV, UP) PRIVATE(IQ2, K)
CFPP$ NODEPCHK
CMIC$ DO PARALLEL
      DO 600 K = 1, 16
         DO 77042 IQ2 = 1, LEN32
            VBL(JADDU+IJ*K+IQ2-1) = VBL(JADDU+IJ*K+IQ2-1) + ABITGRDU(
     1         LADD3+IQ2-1,NPAIR,NG)*CORU(JADD+IJ*K+IQ2-1)*VP(JADD+IJ*K+
     2         IQ2-1)
77042    CONTINUE
         DO 77043 IQ2 = 1, LEN31
            VBL(JADDV+IJ*K+IQ2-1) = VBL(JADDV+IJ*K+IQ2-1) - ABITGRDV(
     1         LADD3+IQ2-1,NPAIR,NG)*CORV(JADD+IJ*K+IQ2-1)*UP(JADD+IJ*K+
     2         IQ2-1)
77043    CONTINUE
  600 CONTINUE
C
C              PLACE HP AT HU PTS INTO S1(J2,JM1).
C              HP / EM AT VP PTS(J2,JM1) INTO S6.
CMIC$ DO PARALLEL VECTOR
      DO 91550 IQ2=1,LEN21
         S1(LADD2+IQ2-1)=P5*(HP(LADD2+IQ2-2)+HP(LADD2+IQ2-1))
         S6(LADD2+IQ2-1)=S1(LADD2+IQ2-1)*EMUIN(LADD2+IQ2-1)
91550 CONTINUE
C
C              PLACE HP AT HV PTS(J3,JM1) INTO S2.
C              HP / EM AT UP PTS(J3,JM1) INTO S5.
CMIC$ DO PARALLEL VECTOR
      DO 91560 IQ2=1,LEN31
         S2(LADD3+IQ2-1)=P5*(HP(LADD2+IQ2-1)+HP(LADD3+IQ2-1))
         S5(LADD3+IQ2-1)=S2(LADD3+IQ2-1)*EMVIN(LADD3+IQ2-1)
91560 CONTINUE
CMIC$ END PARALLEL
C
         JADD2 = LADD2 - IJ
         JADD3 = LADD3 - IJ
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD2, IJ, JADD3, LEN31, LADD3, LEN21, LADD2, S5, UP
CMIC$1   , FLX, S6, VP, FLY) PRIVATE(K, IQ2)
      DO 630 K = 1, 16
         DO 77044 IQ2 = 1, LEN31
            FLX(JADD3+IJ*K+IQ2-1) = S5(LADD3+IQ2-1)*UP(JADD3+IJ*K+IQ2-1)
77044    CONTINUE
         DO 77045 IQ2 = 1, LEN21
            FLY(JADD2+IJ*K+IQ2-1) = S6(LADD2+IQ2-1)*VP(JADD2+IJ*K+IQ2-1)
77045    CONTINUE
  630 CONTINUE
C
C============= CONVERGENCE FOR FULL TIME STEP ======================
C
C------------- EVALUATE CONV AT H POINTS(J3,JM1), PUT IN ARRAY CONV.
      JADD = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, LADD3, IM, DELSIG, EM2H, FLX, FLY,
CMIC$1   CONV) PRIVATE(K, C1, IQ2)
      DO 640 K = 1, 16
C               DELX HUP/M
         C1 = -DELSIG(K)
         DO 77046 IQ2 = 1, LEN31
            CONV(JADD+IJ*K+IQ2-1) = EM2H(LADD3+IQ2-1)*C1*(FLX(JADD+IJ*K+
     1         IQ2-1)-FLX(JADD+IJ*K-2+IQ2)+FLY(JADD+IJ*K+IQ2-1)-FLY(JADD
     2         +IJ*K-IM+IQ2-1))
77046    CONTINUE
  640 CONTINUE
C
C------------- ACCUMULATE VERT. SUM OF CONV IN S7,(J3,JM1)
      JADD = LADD3 + IJ
CMIC$ DO ALL VECTOR SHARED(LEN31, LADD3, JADD, CONV, S7) PRIVATE(IQ2)
      DO 91730 IQ2=1,LEN31
         S7(LADD3+IQ2-1)=CONV(LADD3+IQ2-1)+CONV(JADD+IQ2-1)
91730 CONTINUE
C
      DO 650 K = 3,IKM
         JADD = JADD + IJ
CMIC$ DO ALL VECTOR SHARED(LEN31, LADD3, JADD, S7, CONV) PRIVATE(IQ2)
      DO 91740 IQ2=1,LEN31
         S7(LADD3+IQ2-1)=S7(LADD3+IQ2-1)+CONV(JADD+IQ2-1)
91740 CONTINUE
  650 CONTINUE
C
C              ARRAY S7 NOW HAS DELX * (THE LOCAL TIME DERIVATIVE
C              OF SURFACE PRESSURE, WHICH EQUALS THE VERTICAL
C              SUM OF CONV) AT H POINTS.
C
C------------- COMPUTE NEW VALUE OF H IN ARRAY VBL(J3,JM1)
C
      JADD = MADDH - 1 + LADD3
CMIC$ DO ALL VECTOR SHARED(LEN31, JADD, LADD3, NPAIR, NG, DTOVDX, VBL,
CMIC$1   ABITGRDH, S7) PRIVATE(IQ2)
      DO 91750 IQ2=1,LEN31
         VBL(JADD+IQ2-1)=VBL(JADD+IQ2-1)+
     *               ABITGRDH(LADD3+IQ2-1, NPAIR, NG) *
     *               DTOVDX*S7(LADD3+IQ2-1)
91750 CONTINUE
C
C--------------COMPUTE INTERFACE W(K) AT H PTS(J3,JM1),(K = 2,KM).
      C1 =  - DELSIG(1)
CMIC$ DO ALL VECTOR SHARED(LEN31,LADD3,C1,IJ,CONV,S7,W)PRIVATE(IQ2)
      DO 91760 IQ2=1,LEN31
         W(LADD3+IJ+IQ2-1)=CONV(LADD3+IQ2-1)+C1*S7(LADD3+IQ2-1)
91760 CONTINUE
      JADD = LADD3
C
      DO 660 K = 3,IKM
         JADD = JADD + IJ
         C1   =  - DELSIG(K - 1)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN31 .OR. IJ.EQ.0) SHARED(LEN31,
CMIC$1   JADD, C1, LADD3, IJ, W, CONV, S7) PRIVATE(IQ2)
      DO 91770 IQ2=1,LEN31
         W(JADD+IJ+IQ2-1)=W(JADD+IQ2-1)+
     *           CONV(JADD+IQ2-1)+C1*S7(LADD3+IQ2-1)
91770 CONTINUE
  660 CONTINUE
C
C============== FULL ADVECTION FOR FULL TIME STEP =====================
C
C--ADV HU----- DO FULL TIME STEP ADVECTION OF HU.
C              PUT UP AT H PTS INTO SBAR(J3,JM1)
      JADD = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, UP, SBAR) PRIVATE(K, IQ2)
      DO 700 K = 1, 16
         DO 77047 IQ2 = 1, LEN31
            SBAR(JADD+IJ*K+IQ2-1) = 0.5*(UP(JADD+IJ*K-2+IQ2)+UP(JADD+IJ*
     1         K+IQ2-1))
77047    CONTINUE
  700 CONTINUE
C
C              PUT W * UP AT H INTERFACE PTS INTO
C              FKS(K = 2,KM),J = J3,JM1.
      JADD = LADD3
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, W, SBAR, FKS) PRIVATE(K, IQ2)
      DO 710 K = 1, 15
C
C              UP(H PTS) AT INTERFACE K INTO S8.
         DO 77048 IQ2 = 1, LEN31
            FKS(JADD+IJ*K+IQ2-1) = W(JADD+IJ*K+IQ2-1)*0.5*(SBAR(JADD+IJ*
     1         K+IQ2-1)+SBAR(JADD+IJ*(K-1)+IQ2-1))
77048    CONTINUE
  710 CONTINUE
C
C              AVERAGE THIS TO HU POINTS(J3,JM2) TO GET FKU.
      JADD = LADD3
      DO 720 K = 2,IKM
         JADD = JADD + IJ
CMIC$ PARALLEL SHARED(LEN32, JADD, S23, FKS, IM) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 91870 IQ2=1,LEN32
         S23(IQ2)=P5*(FKS(JADD+IQ2-1)+FKS(JADD+IM+IQ2-1))
91870 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 91871 IQ2 = 1, LEN32
         FKS(JADD+IQ2-1) = S23(IQ2)
91871 CONTINUE
CMIC$ END PARALLEL
  720 CONTINUE
C
C              TAKE THE VERTICAL DIFFS AND ACCUMULATE D(HU) IN FKS
C              FOR J = J3,JM2.
         C1  =  - DTOVDX / DELSIG(1)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN32 .OR. IJ.EQ.0) SHARED(LEN32, C1
CMIC$1   , LADD3, IJ, FKS) PRIVATE(IQ2)
      DO 91890 IQ2=1,LEN32
         FKS(LADD3+IQ2-1)=C1*FKS(LADD3+IJ+IQ2-1)
91890 CONTINUE
         JADD = LADD3
      DO 730 K = 2,IKMM1
         JADD = JADD + IJ
         C1   =  - DTOVDX / DELSIG(K)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN32 .OR. IJ.EQ.0) SHARED(LEN32, C1
CMIC$1   , JADD, IJ, FKS) PRIVATE(IQ2)
      DO 91900 IQ2=1,LEN32
         FKS(JADD+IQ2-1)=C1*(FKS(JADD+IJ+IQ2-1)-FKS(JADD+IQ2-1))
91900 CONTINUE
  730 CONTINUE
C
         C1 = DTOVDX / DELSIG(KM)
         JADD = JADD + IJ
CMIC$ DO ALL VECTOR SHARED(LEN32, C1, JADD, FKS) PRIVATE(IQ2)
      DO 91910 IQ2=1,LEN32
         FKS(JADD+IQ2-1)=C1*FKS(JADD+IQ2-1)
91910 CONTINUE
C
C  --HOR ADV-- GET CONTRIBUTIONS FROM HORIZONTAL FLUXES(J3,JM2)
      JADD = LADD3 - IJ
      JADDU = NADDU
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, JADDU, LEN31, LADD3, LEN32, IM, NPAIR, NG
CMIC$1   , DTOVDX, FLX, UP, FLY, SBAR, VBL, ABITGRDU, FKS, EM2U)
CMIC$2    PRIVATE(S23, S22, S21, K, IQ2) SAVELAST
      DO 740 K = 1, 16
C
         DO 77049 IQ2 = 1, LEN31
            S23(LADD3+IQ2-1) = FLX(JADD+IJ*K+IQ2-1)*UP(JADD+IJ*K+IQ2-1)
77049    CONTINUE
C
C     (HP)     FIU AT CENTER OF GRID SQUARE.
         DO 77050 IQ2 = 1, LEN32
            S22(LADD3+IQ2-1)=0.5*(S23(LADD3+IQ2-1)+S23(LADD3+IM+IQ2-1))
77050    CONTINUE
C
C        FJU AT H PTS(J3,JM1)
         DO 77051 IQ2 = 1, LEN31
            S21(LADD3+IQ2-1) = 0.5*(FLY(JADD+IJ*K+IQ2-1)+FLY(JADD+IJ*K-
     1         IM+IQ2-1))*SBAR(JADD+IJ*K+IQ2-1)
77051    CONTINUE
C
C         X-DIFF. CENTERED AT HU PTS(J3,JM2)
C         Y-DIFF. CENTERED AT HU PTS(J3,JM2)
         DO 77052 IQ2 = 1, LEN32
C              COMBINE WITH X-DIFF, MULT BY EM**2,
C              AND ADD TO VERTICAL TERM ALREADY IN FKS.
C              STORE NEW HU VALUE IN VBL WHERE ALLOWED.
            VBL(JADDU+IJ*K+IQ2-1) = VBL(JADDU+IJ*K+IQ2-1) + ABITGRDU(
     1         LADD3+IQ2-1,NPAIR,NG)*(FKS(JADD+IJ*K+IQ2-1)-DTOVDX*(S21(
     2         LADD3+IM+IQ2-1)-S21(LADD3+IQ2-1)+S22(LADD3+IQ2-1)-S22(
     3         LADD3-2+IQ2))*EM2U(LADD3+IQ2-1))
77052    CONTINUE
  740 CONTINUE
C
C
C---ADV HV-----DO FULL TIME STEP ADVECTION OF HV.
C              PUT VP AT H PTS INTO SBAR(J3,JM1)
      JADD = LADD3 - IJ
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, IM, VP, SBAR) PRIVATE(K, IQ2)
      DO 750 K = 1, 16
         DO 77053 IQ2 = 1, LEN31
            SBAR(JADD+IJ*K+IQ2-1) = 0.5*(VP(JADD+IJ*K+IQ2-1)+VP(JADD+IJ*
     1         K-IM+IQ2-1))
77053    CONTINUE
  750 CONTINUE
C
C              PUT W * VP (H, INTERFACE PTS) INTO
C              FKS(K = 2,KM AND J = J3,JM1).
      JADD = LADD3
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, W, SBAR, FKS) PRIVATE(K, IQ2)
      DO 760 K = 1, 15
         DO 77054 IQ2 = 1, LEN31
            FKS(JADD+IJ*K+IQ2-1) = W(JADD+IJ*K+IQ2-1)*0.5*(SBAR(JADD+IJ*
     1         K+IQ2-1)+SBAR(JADD+IJ*(K-1)+IQ2-1))
77054    CONTINUE
  760 CONTINUE
C
C              AVERAGE THIS TO HV POINTS (J = J3,JM1).
      JADD = LADD3
      DO 770 K = 2,IKM
         JADD = JADD + IJ
CMIC$ PARALLEL SHARED(LEN31, JADD, S23, FKS) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 92160 IQ2=1,LEN31
         S23(IQ2)=P5*(FKS(JADD+IQ2-1)+FKS(JADD+IQ2))
92160 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 92161 IQ2 = 1, LEN31
         FKS(JADD+IQ2-1) = S23(IQ2)
92161 CONTINUE
CMIC$ END PARALLEL
  770 CONTINUE
C
C              TAKE VERTICAL DIFFS AND ACCUMULATE D(HV) IN FKS(J3,JM1).
         C1   =  - DTOVDX / DELSIG(1)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN31 .OR. IJ.EQ.0) SHARED(LEN31, C1
CMIC$1   , LADD3, IJ, FKS) PRIVATE(IQ2)
      DO 92180 IQ2=1,LEN31
         FKS(LADD3+IQ2-1)=C1*FKS(LADD3+IJ+IQ2-1)
92180 CONTINUE
      JADD = LADD3
      DO 780 K = 2,IKMM1
         JADD = JADD + IJ
         C1   =  - DTOVDX / DELSIG(K)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN31 .OR. IJ.EQ.0) SHARED(LEN31, C1
CMIC$1   , JADD, IJ, FKS) PRIVATE(IQ2)
      DO 92190 IQ2=1,LEN31
         FKS(JADD+IQ2-1)=C1*(FKS(JADD+IJ+IQ2-1)-FKS(JADD+IQ2-1))
92190 CONTINUE
  780 CONTINUE
C
         C1   = DTOVDX / DELSIG(KM)
         JADD = JADD + IJ
CMIC$ DO ALL VECTOR SHARED(LEN31, C1, JADD, FKS) PRIVATE(IQ2)
      DO 92200 IQ2=1,LEN31
         FKS(JADD+IQ2-1)=C1*FKS(JADD+IQ2-1)
92200 CONTINUE
C
C --HOR ADV--  GET CONTRIBUTIONS FROM HORIZONTAL FLUXES AND COMBINE
C              WITH THE VERTICAL TERM.(J3,JM1).
      JADD  = LADD3 - IJ
      JADDV = NADDV
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, JADDV, LEN31, LADD3, LEN21, IM, LADD2,
CMIC$1   NPAIR, NG, DTOVDX, FLX, SBAR, FLY, VP, VBL, ABITGRDV, FKS, EM2V
CMIC$2   ) PRIVATE(S23, S21, S22, K, IQ2) SAVELAST
      DO 790 K = 1, 16
C              FIV AT H PTS (J = J3,JM1).
         DO 77055 IQ2 = 1, LEN31
            S23(LADD3+IQ2-1) = 0.5*(FLX(JADD+IJ*K-2+IQ2)+FLX(JADD+IJ*K+
     1         IQ2-1))*SBAR(JADD+IJ*K+IQ2-1)
77055    CONTINUE
C
C      (HP)    FJV IN CENTER OF GRID SQUARE(J2,JM1)
         DO 77056 IQ2 = 1, LEN21
            S21(LADD2+IQ2-1) = FLY(JADD+IJ*K-IM+IQ2-1)*VP(JADD+IJ*K-IM+
     1         IQ2-1)
77056    CONTINUE
         DO 77057 IQ2 = 1, LEN21
            S22(LADD2+IQ2-1) = 0.5*(S21(LADD2+IQ2-1)+S21(LADD2+IQ2))
77057    CONTINUE
C
C      (HV)    X-DIFF. CENTERED AT HV PTS(J3,JM1)
C      (HV)    Y-DIFF. CENTERED AT HV PTS(J3,JM1)
         DO 77058 IQ2 = 1, LEN31
C              COMBINE WITH X-DIFF,MULT. BY M**2 AND ADD TO VERT.TERM.
C              STORE NEW HV VALUE IN VBL WHERE ALLOWED.
            VBL(JADDV+IJ*K+IQ2-1) = VBL(JADDV+IJ*K+IQ2-1) + ABITGRDV(
     1         LADD3+IQ2-1,NPAIR,NG)*(FKS(JADD+IJ*K+IQ2-1)-DTOVDX*(S23(
     2         LADD3+IQ2)-S23(LADD3+IQ2-1)+S22(LADD3+IQ2-1)-S22(LADD2+
     3         IQ2-1))*EM2V(LADD3+IQ2-1))
77058    CONTINUE
  790 CONTINUE
C
C              ARRAYS UP AND VP ARE NO LONGER NEEDED.
C              THEREFORE, THE SPACE USED BY VP IS AVAILABLE FOR USE
C              AS THPATH AND THEN QPATH.
C
C---ADV HTH---- DO FULL TIME STEP ADVECTION OF HTH (H * THETA).
C              CALCULATE THP AT HV PTS AND PUT IT INTO SBAR(J=J3,JM1).
C              CALCULATE THP AT H PTS AND PUT IT INTO THPATH (J3,JM1).
      JADD  = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD,IJ,LEN31,IM,THP,SBAR,THPATH)PRIVATE(K,IQ2)
      DO 800 K = 1, 16
         DO 77059 IQ2 = 1, LEN31
            SBAR(JADD+IJ*K+IQ2-1) = 0.5*(THP(JADD+IJ*K+IQ2-1)+THP(JADD+
     1         IJ*K-IM+IQ2-1))
77059    CONTINUE
         DO 77060 IQ2 = 1, LEN31
            THPATH(JADD+IJ*K+IQ2-1) = 0.5*(SBAR(JADD+IJ*K-2+IQ2)+SBAR(
     1         JADD+IJ*K+IQ2-1))
77060    CONTINUE
  800 CONTINUE
C
C              PUT W * THP(H INTERFACE PTS) INTO
C              FKS(K = 2,KM AND J = J3,JM1).
      JADD  = LADD3
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, W, THPATH, FKS) PRIVATE(K, IQ2)
      DO 810 K = 1, 15
         DO 77061 IQ2 = 1, LEN31
            FKS(JADD+IJ*K+IQ2-1) = W(JADD+IJ*K+IQ2-1)*0.5*(THPATH(JADD+
     1         IJ*K+IQ2-1)+THPATH(JADD+IJ*(K-1)+IQ2-1))
77061    CONTINUE
  810 CONTINUE
C
C              TAKE VERTICAL DIFFS AND ACCUMULATE D(HT) IN FKS.
         C1   = - DTOVDX / DELSIG(1)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN31 .OR. IJ.EQ.0) SHARED(LEN31, C1
CMIC$1   , LADD3, IJ, FKS) PRIVATE(IQ2)
      DO 92470 IQ2=1,LEN31
         FKS(LADD3+IQ2-1)=C1*FKS(LADD3+IJ+IQ2-1)
92470 CONTINUE
         JADD = LADD3
C
      DO 820 K = 2,IKMM1
         JADD = JADD + IJ
         C1   =  - DTOVDX / DELSIG(K)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN31 .OR. IJ.EQ.0) SHARED(LEN31, C1
CMIC$1   , JADD, IJ, FKS) PRIVATE(IQ2)
      DO 92480 IQ2=1,LEN31
         FKS(JADD+IQ2-1)=C1*(FKS(JADD+IJ+IQ2-1)-FKS(JADD+IQ2-1))
92480 CONTINUE
  820 CONTINUE
C
         C1   = DTOVDX / DELSIG(KM)
         JADD = JADD + IJ
CMIC$ DO ALL VECTOR SHARED(LEN31, C1, JADD, FKS) PRIVATE(IQ2)
      DO 92490 IQ2=1,LEN31
         FKS(JADD+IQ2-1)=C1*FKS(JADD+IQ2-1)
92490 CONTINUE
C
C              GET CONTRIBUTIONS FROM X AND Y FLUX.
         JADD  = LADD3 - IJ
         JADDT = NADDT
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, JADDT, LEN31, LADD3, LEN21, IM, LADD2,
CMIC$1   NPAIR, NG, DTOVDX, FLX, SBAR, THP, FLY, VBL, ABITGRDH, FKS,
CMIC$2   EM2H) PRIVATE(S22, S23, K, IQ2) SAVELAST
      DO 830 K = 1, 16
C
C              FIT AT HV PTS(J3,JM1)
         DO 77062 IQ2 = 1, LEN31
            S22(LADD3+IQ2-1)=FLX(JADD+IJ*K+IQ2-1)*SBAR(JADD+IJ*K+IQ2-1)
77062    CONTINUE
C
C        FJT AT HU PTS(J2,JM1)
         DO 77063 IQ2 = 1, LEN21
            S23(LADD2+IQ2-1) = 0.5*(THP(JADD+IJ*K-IM-2+IQ2)+THP(JADD+IJ*
     1         K-IM+IQ2-1))*FLY(JADD+IJ*K-IM+IQ2-1)
77063    CONTINUE
C
C          X-DIFF CENTERED AT H PTS(J3,JM1)
C          Y-DIFF CENTERED AT H PTS(J3,JM1)
         DO 77064 IQ2 = 1, LEN31
C              COMBINE WITH X-DIFF, MULT BY M**2 AND ADD TO VERT. TERM.
C              PUT NEW H * THETA IN VBL WHERE ALLOWED TO.
            VBL(JADDT+IJ*K+IQ2-1) = VBL(JADDT+IJ*K+IQ2-1) + ABITGRDH(
     1         LADD3+IQ2-1,NPAIR,NG)*(FKS(JADD+IJ*K+IQ2-1)-DTOVDX*(S22(
     2         LADD3+IQ2-1)-S22(LADD3-2+IQ2)+S23(LADD3+IQ2-1)-S23(LADD2+
     3         IQ2-1))*EM2H(LADD3+IQ2-1))
77064    CONTINUE
  830 CONTINUE
C
C---ADV HQ---- DO FULL TIME STEP ADVECTION OF HQ
C              PUT QP AT HV PTS INTO SBAR(J3,JM1)
C              AND QP AT H PTS INTO QPATH (J = J3, JM1).
         JADD = LADD3 - IJ
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD,IJ,LEN31,IM,QP,SBAR,QPATH)PRIVATE(K,IQ2)
      DO 850 K = 1, 16
         DO 77065 IQ2 = 1, LEN31
            SBAR(JADD+IJ*K+IQ2-1) = 0.5*(QP(JADD+IJ*K+IQ2-1)+QP(JADD+IJ*
     1         K-IM+IQ2-1))
77065    CONTINUE
         DO 77066 IQ2 = 1, LEN31
            QPATH(JADD+IJ*K+IQ2-1) = 0.5*(SBAR(JADD+IJ*K-2+IQ2)+SBAR(
     1         JADD+IJ*K+IQ2-1))
77066    CONTINUE
  850 CONTINUE
C
C              PUT W * QP(H INTERFACE PTS) INTO
C              FKS(K = 2,KM AND J = J3,JM1).
      JADD = LADD3
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, LEN31, W, QPATH, FKS) PRIVATE(K, IQ2)
      DO 860 K = 1, 15
         DO 77067 IQ2 = 1, LEN31
            FKS(JADD+IJ*K+IQ2-1) = W(JADD+IJ*K+IQ2-1)*0.5*(QPATH(JADD+IJ
     1         *K+IQ2-1)+QPATH(JADD+IJ*(K-1)+IQ2-1))
77067    CONTINUE
  860 CONTINUE
C
C              TAKE VERTICAL DIFFS AND ACCUMULATE DHQ IN FKS.
         C1   =  - DTOVDX / DELSIG(1)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN31 .OR. IJ.EQ.0) SHARED(LEN31, C1
CMIC$1   , LADD3, IJ, FKS) PRIVATE(IQ2)
      DO 92730 IQ2=1,LEN31
         FKS(LADD3+IQ2-1)=C1*FKS(LADD3+IJ+IQ2-1)
92730 CONTINUE
      JADD = LADD3
      DO 870 K = 2,IKMM1
         JADD = JADD + IJ
         C1   = - DTOVDX / DELSIG(K)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN31 .OR. IJ.EQ.0) SHARED(LEN31, C1
CMIC$1   , JADD, IJ, FKS) PRIVATE(IQ2)
      DO 92740 IQ2=1,LEN31
         FKS(JADD+IQ2-1)=C1*(FKS(JADD+IJ+IQ2-1)-FKS(JADD+IQ2-1))
92740 CONTINUE
  870 CONTINUE
C
         C1   = DTOVDX / DELSIG(KM)
         JADD = JADD + IJ
CMIC$ DO ALL VECTOR SHARED(LEN31, C1, JADD, FKS) PRIVATE(IQ2)
      DO 92750 IQ2=1,LEN31
         FKS(JADD+IQ2-1)=C1*FKS(JADD+IQ2-1)
92750 CONTINUE
C
C              GET CONTRIBUTIONS FROM X AND Y FLUX.
         JADD  = LADD3 - IJ
         JADDQ = NADDQ
C
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, JADDQ, LEN31, LADD3, LEN21, IM, LADD2,
CMIC$1   NPAIR, NG, DTOVDX, FLX, SBAR, QP, FLY, VBL, ABITGRDH, FKS, EM2H
CMIC$2   ) PRIVATE(S22, S23, K, IQ2) SAVELAST
      DO 880 K = 1, 16
C
C              FIQ AT HV PTS(J3,JM1).
         DO 77068 IQ2 = 1, LEN31
            S22(LADD3+IQ2-1)=FLX(JADD+IJ*K+IQ2-1)*SBAR(JADD+IJ*K+IQ2-1)
77068    CONTINUE
C
C        FJQ AT HU PTS(J2,JM1).
         DO 77069 IQ2 = 1, LEN21
            S23(LADD2+IQ2-1) = 0.5*(QP(JADD+IJ*K-IM-2+IQ2)+QP(JADD+IJ*K-
     1         IM+IQ2-1))*FLY(JADD+IJ*K-IM+IQ2-1)
77069    CONTINUE
C
C        X-DIFF CENTERED AT H PTS(J3,JM1).
C        Y-DIFF CENTERED AT H PTS(J3,JM1).
         DO 77070 IQ2 = 1, LEN31
C              COMBINE WITH X-DIFF, MULT BY M**2 AND ADD TO VERT. TERM.
            VBL(JADDQ+IJ*K+IQ2-1) = VBL(JADDQ+IJ*K+IQ2-1) + ABITGRDH(
     1         LADD3+IQ2-1,NPAIR,NG)*(FKS(JADD+IJ*K+IQ2-1)-DTOVDX*(S22(
     2         LADD3+IQ2-1)-S22(LADD3-2+IQ2)+S23(LADD3+IQ2-1)-S23(LADD2+
     3         IQ2-1))*EM2H(LADD3+IQ2-1))
77070    CONTINUE
  880 CONTINUE
C
C
C============== HYDROSTATIC COMPUTATION FOR FULL TIME STEP ===========
C
C--------------DO THE HYDROSTATIC COMPUTATIONS (J = J2,JM1).
C              FIRST MAKE VIRTUAL TEMP CORRN TO THETA PRIME (THP).
      JADD  = LADD2 - IJ
CFPP$ NODEPCHK
CMIC$ PARALLEL SHARED(LEN21, LADD2, HP, S4, JADD, IJ, THP, QP, VT)
CMIC$1    PRIVATE(I2X, K, IQ2)
CFPP$ NODEPCHK
CMIC$ DO PARALLEL
      DO 900 K = 1, 16
         DO 77071 IQ2 = 1, LEN21
            VT(JADD+IJ*K+IQ2-1) = THP(JADD+IJ*K+IQ2-1)*(1.0+0.609*QP(
     1         JADD+IJ*K+IQ2-1))
77071    CONTINUE
  900 CONTINUE
C*****  Code Expanded From Routine:  P2KAP
CMIC$ DO PARALLEL VECTOR
      DO 77002 I2X = 1, LEN21
         S4(I2X+LADD2-1) = (0.34757549+HP(I2X+LADD2-1)*(4.36732956+HP(
     1      I2X+LADD2-1)*3.91557032))/(1.+HP(I2X+LADD2-1)*(5.44053037+HP
     2      (I2X+LADD2-1)*(2.27693825+HP(I2X+LADD2-1)*(-0.0869930591))))
77002 CONTINUE
CMIC$ END PARALLEL
C*****  End of Code Expanded From Routine:  P2KAP
C
C              COMPUTE PSI PRIME FOR K = 1 IN ARRAY PSI(J = J2,JM1).
C           A SIMPLE HYDROSTATIC EQUATION FOR LAYER ONE
      C1 = ONE - TWO * PR(1)
CMIC$ DO ALL VECTOR SHARED(LEN21, LADD2, C1, GRNDP, VT, S4, PSI)
CMIC$1    PRIVATE(IQ2)
      DO 92950 IQ2=1,LEN21
         PSI(LADD2+IQ2-1)=GRNDP(LADD2+IQ2-1)+
     *         C1*VT(LADD2+IQ2-1)*S4(LADD2+IQ2-1)
92950 CONTINUE
C
         JADD = LADD2
      DO 920 K = 2,IKM
         JADD = JADD + IJ
         C1   = PR(K - 1) - PR(K)
CMIC$ DO ALL VECTOR IF (ABS(IJ).GE.LEN21 .OR. IJ.EQ.0) SHARED(LEN21,
CMIC$1   JADD, IJ, C1, LADD2, PSI, VT, S4) PRIVATE(IQ2)
      DO 92980 IQ2=1,LEN21
         PSI(JADD+IQ2-1)=PSI(JADD-IJ+IQ2-1)+
     *       C1*(VT(JADD+IQ2-1)+VT(JADD-IJ+IQ2-1))*
     *       S4(LADD2+IQ2-1)
92980 CONTINUE
  920 CONTINUE
C
C============== PRESSURE GRADIENT FORCE FOR FULL TIME STEP ===========
C
C---PGF HU-----THE PRESSURE FORCE CHANGE TO HU(N + 1) FOR J = J3,JM2.
C
      C2 = CSUBP * DTOVDX
C
CMIC$ DO ALL VECTOR SHARED(LEN32, LADD3, NPAIR, NG, C2, S4, S3, S1, EMU
CMIC$1   , ABITGRDU) PRIVATE(IQ2)
      DO 93010 IQ2=1,LEN32
         S3(LADD3+IQ2-1)=(S4(LADD3+IQ2-1)-S4(LADD3+IQ2-2))*P5
         S1(LADD3+IQ2-1)=S1(LADD3+IQ2-1)*EMU(LADD3+IQ2-1)*
     *     ABITGRDU(LADD3+IQ2-1, NPAIR, NG)*C2
93010 CONTINUE
C
      JADDU = NADDU
      JADD  = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ PARALLEL SHARED(LEN31, LADD3, LADD2, NPAIR, NG, C2, S4, S3, S2,
CMIC$1   EMV, ABITGRDV, JADD, IJ, JADDU, LEN32, PR, VBL, PSI, VT, S1)
CMIC$2    PRIVATE(IQ2, K, C1)
CFPP$ NODEPCHK
CMIC$ DO PARALLEL
      DO 930 K = 1, 16
         C1 = 2.0*PR(K)
         DO 77072 IQ2 = 1, LEN32
            VBL(JADDU+IJ*K+IQ2-1) = VBL(JADDU+IJ*K+IQ2-1) - (PSI(JADD+IJ
     1         *K+IQ2-1)-PSI(JADD+IJ*K-2+IQ2)+S3(LADD3+IQ2-1)*C1*(VT(
     2         JADD+IJ*K-2+IQ2)+VT(JADD+IJ*K+IQ2-1)))*S1(LADD3+IQ2-1)
77072    CONTINUE
  930 CONTINUE
C
C---PGF HV---- GET THE PRESSURE FORCE CHANGE TO HV (J = J3,JM1).
C
CMIC$ DO PARALLEL VECTOR
      DO 93150 IQ2=1,LEN31
         S3(LADD3+IQ2-1)=(S4(LADD3+IQ2-1)-S4(LADD2+IQ2-1))*P5
         S2(LADD3+IQ2-1)=S2(LADD3+IQ2-1)*EMV(LADD3+IQ2-1)*
     *     ABITGRDV(LADD3+IQ2-1, NPAIR, NG) * C2
93150 CONTINUE
CMIC$ END PARALLEL
C
      JADDV = NADDV
      JADD  = LADD3 - IJ
CFPP$ NODEPCHK
CMIC$ DO ALL SHARED(JADD, IJ, JADDV, LEN31, IM, LADD3, PR, VBL, PSI, S3
CMIC$1   , VT, S2) PRIVATE(K, C1, IQ2)
      DO 940 K = 1, 16
         C1 = 2.0E0*PR(K)
         DO 77073 IQ2 = 1, LEN31
            VBL(JADDV+IJ*K+IQ2-1) = VBL(JADDV+IJ*K+IQ2-1) - (PSI(JADD+IJ
     1         *K+IQ2-1)-PSI(JADD+IJ*K-IM+IQ2-1)+S3(LADD3+IQ2-1)*C1*(VT(
     2         JADD+IJ*K+IQ2-1)+VT(JADD+IJ*K-IM+IQ2-1)))*S2(LADD3+IQ2-1)
77073    CONTINUE
  940 CONTINUE
C
      RETURN
      END
