       SUBROUTINE TWOPLATE(F1,NX1,NY1,X1,Y1,M1,
     *                     F2,NXY2,X2,Y2,M2,
     *            IORDER,NF,RK,IK,RKWORK,IKWORK,BITK,IZERO)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    TWOPLATE    INTERPOLATE IN TWO-DIMENSIONS
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 88-08-08
C
C ABSTRACT: INTERPOLATE FROM ONE TWO-DIM FIELD TO ANOTHER.
C
C PROGRAM HISTORY LOG:
C   88-08-08  PARRISH
C
C USAGE:    CALL TWOPLATE(F1,NX1,NY1,X1,Y1,M1,
C    *                     F2,NXY2,X2,Y2,M2,
C    *            IORDER,NF,RK,IK,RKWORK,IKWORK,BITK,IZERO)
C   INPUT ARGUMENT LIST:
C     F1       - TWO-DIM REGULAR GRID FIELD TO INTERPOLATE FROM.
C     NX1      - X-DIMENSION OF INPUT GRID FIELD
C     NY1      - Y-DIMENSION OF INPUT GRID FIELD
C     X1       - X-COORDINATES OF INPUT GRID FIELD
C     Y1       - Y-COORDINATES OF INPUT GRID FIELD
C     M1       - TOTAL NUMBER OF POINTS IN EACH LEVEL OF F1
C     F2       - ON INPUT, CONTAINS VALUES THAT INTERPOLATES ARE
C              - ADDED TO.
C     NXY2     - NUMBER OF OUTPUT INTERPOLATED POINTS
C     X2       - X-COORDINATES OF OUTPUT GRID FIELD
C     Y2       - Y-COORDINATES OF OUTPUT GRID FIELD
C     M2       - TOTAL NUMBER OF POINTS IN EACH LEVEL OF F2
C     IORDER   - =1 FOR LINEAR INTERPOLATION.
C              - =2 FOR QUADRATIC INTERPOLATION.
C     NF       - NUMBER OF LEVELS TO INTERPOLATE.
C     IZERO    - =0, THEN ZERO OUT F2, BEFORE INTERPOLATING.
C              - =1, THEN ADD INTERPOLATED RESULT TO CURRENT
C              -      CONTENTS OF F2.
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     F2       - OUTPUT INTERPOLATED VALUES
C     RK       - WORK ARRAY
C     IK       - WORK ARRAY
C     RKWORK   - WORK ARRAY
C     IKWORK   - WORK ARRAY
C     BITK     - WORK ARRAY
C
C   SUBPROGRAMS CALLED: GINTERP0,INTERP1
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN200
C   MACHINE:  CYBER
C
C$$$
C--------
         include "myparam"
         REAL F1(M1,1),F2(M2,1)
         REAL X1(1),X2(1),Y1(1),Y2(1),RK(1),RKWORK(1)
         INTEGER IK(1),IKWORK(1)
         LOGICAL BITK(1)
         NZ=1
         NVR=1
         NKX=IORDER+1
         NKY=IORDER+1
         NKZ=1
         EXTRAPX=.001
         EXTRAPY=EXTRAPX
         CALL GINTERP0(RK,IK,BITK,NXY2,X2,Y2,Y2,Y2,NX1,NY1,NZ,NVR,NKX,
     *      NKY,NKZ,X1,Y1,Y1,EXTRAPX,EXTRAPY,EXTRAPY,RKWORK,IKWORK)
C--------
C-------- NOW DO INTERPOLATION
C--------
         DO 300 I=1,NF
           CALL INTERP1(F2(1,I),F1(1,I),RK,IK,BITK,NXY2,NX1,NY1,NKX,
     *        NKY,NKZ,IZERO)
300      CONTINUE
       RETURN
       END
