       SUBROUTINE VTRANSFR(RDEPTHS,REINVT,REINV,REINVG,
     *                       RPIBINVE,RTBINVE,RE)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    VTRANSFR    EXTRACT VERTICAL FUNCTIONS FROM COMMON
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 88-08-08
C
C ABSTRACT: EXTRACT VERTICAL FUNCTIONS FROM COMMON BLOCK /FIXSP03/
C
C PROGRAM HISTORY LOG:
C   88-08-08  PARRISH
C
C USAGE:    CALL VTRANSFR(RDEPTHS,REINVT,REINV,REINVG,
C    *                       RPIBINVE,RTBINVE,RE)
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     RDEPTHS  - SCALE DEPTHS
C     REINVT   - INVERSE OF EIGENVECTOR MATRIXMULTIPLIED BY TAU MATRX
C     REINV    - INVERSE OF EIGENVECTOR MATRIX
C     REINVG   - REINV * G MATRIX
C     RPIBINVE - PI * BINV * E
C     RTBINVE  - TAU * BINV * E
C     RE       - E (EIGENVECTOR ARRAY)
C
C   SUBPROGRAMS CALLED: SETSP03
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN200
C   MACHINE:  CYBER
C
C$$$
C--------
         include "myparam"
         REAL RDEPTHS(IKM),REINVT(IKM),
     *       REINV(IKM,IKM),REINVG(IKM,IKM),RPIBINVE(IKM),
     *       RTBINVE(IKM,IKM),RE(IKM,IKM)
         COMMON/FIXSP03/NSIG,NMODES,DELSIG(IKM),HEINVT(IKM),
     *       HEINV(IKM,IKM),HEINVG(IKM,IKM),HPIBINVE(IKM),
     *       HTBINVE(IKM,IKM),HE(IKM,IKM),HDEPTHS(INMODES)
C--------
         IF(NSIG.NE.INSIG) CALL SETSP03
         KM=NSIG
         KM2=KM*KM
         DO 100 I=1,KM
           RDEPTHS(I)=HDEPTHS(I)
           REINVT(I)=HEINVT(I)
           RPIBINVE(I)=HPIBINVE(I)
100      CONTINUE
         DO 200 I=1,KM2
           REINV(I,1)=HEINV(I,1)
           REINVG(I,1)=HEINVG(I,1)
           RTBINVE(I,1)=HTBINVE(I,1)
           RE(I,1)=HE(I,1)
200      CONTINUE
       RETURN
       END
