      SUBROUTINE WRTDAT (DATSET, AYEAR0, AMNTH0, ADAY0, AGMT0,
     1                    IRUNMK, IVERSN, ITUPRT, ITUOUT,
     2                    ITIME,  NSTEPS)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    WRTDAT       CREATES NCEP DATE WORD, WRITES IT TO DISK
C   PRGMMR:  ERIC ROGERS      ORG: W/NMC22    DATE: 98-11-19
C
C ABSTRACT: CREATES THE NCEP DATE WORD FOR THE FILE
C   BEING PROCESSED, AND WRITES IT TO DISK.
C
C PROGRAM HISTORY LOG:
C   98-11-19  ERIC ROGERS : BASED ON SUBROUTINE OUTOPN
C
C USAGE:    CALL WRTDAT (DATSET, AYEAR0, AMNTH0, ADAY0, AGMT0,
C    1                    IRUNMK, IVERSN, ITUPRT, ITUOUT,
C    2                    ITIME,  NSTEPS)
C   INPUT ARGUMENT LIST:
C     DATSET   - DATA SET NAME
C     AYEAR0   - FOUR-DIGIT YEAR AT MODEL TIME
C     AMNTH0   - MONTH OF THE INITIAL MODEL TIME
C     ADAY0    - DAY OF THE INITIAL MODEL TIME
C     AGMT0    - GMT HOUR OF THE INITIAL MODEL TIME
C     IRUNMK   - EXPLAIN COMPLETELY IF ERROR RETURN
C     IVERSN   - VERSION OF THE MODEL
C     ITUPRT   - UNIT NUMBER FOR PRINTOUT
C     ITUOUT   - UNIT NUMBER OF THE DISK THAT THE O.N. 85 LABEL
C                IS BEING WRITTEN
C     ITIME    - MODEL INTEGRATION TIME IN SECONDS FOR THE DATA
C                SET BEING OPENED
C     NSTEPS   - NUMBER OF MODEL TIME STEPS WHEN THIS DATA SET IS
C                BEING OPENED
C
C   OUTPUT FILES:
C     ITUOUT   - UNIT FOR OUTPUT DATA SET THAT THIS ROUTINE
C                IS WRITING AN O.N. 85 LABEL TO
C     ITUPRT   - UNIT FOR PRINTOUT OF ERROR MESSAGE
C
C ATTRIBUTES:
C   LANGUAGE: STANDARD FORTRAN
C   MACHINE:
C
C$$$
C
C              SUBROUTINE TO CREATE THE NMC OFFICE NOTE 85 LABEL
C              FOR THE FILE BEING PROCESSED, AND WRITE
C              IT TO DISK.
C
C     COMMON BLOCK /COMPARIT/ CONTAINS QUANTITIES ASSOCIATED WITH
C          PARITY CHECKING.
      COMMON /COMPARIT/ IPARITY, KOUNTPAR
C
C     ******* END OF INCLUDED COMMON BLK COMPARIT  **********
C
      CHARACTER*6  DATSET
C
      DIMENSION INPDAT(8),JTIME(8)
C
      DO I = 1, 8
        INPDAT(I) = 0
      ENDDO
C
      IYEAR0 = NINT ( AYEAR0 )
      IMNTH0 = NINT ( AMNTH0 )
      IDAY0  = NINT ( ADAY0  )
      IGMT0  = NINT ( AGMT0  )
C
      INPDAT(1) = IYEAR0
      INPDAT(2) = IMNTH0
      INPDAT(3) = IDAY0
      INPDAT(5) = IGMT0
C
C              SPECIFY THE SET INITIATE TIME.
C              SINCE THIS CODE IS NOT F90 HARDWIRE
C              SET INITIATE TIME TO CYCLE TIME
C     CALL W3UTCDAT(JTIME)
C
c     ISETIM = NINT(100.*(FLOAT(JTIME(5))
c    1                   + FLOAT(JTIME(6)) / 60.0
c    2                   + FLOAT(JTIME(7)) / 3600.))
      ISETIM = NINT(100.*FLOAT(IGMT0))
C
C              WRITE THE DATE WORD TO DISK
C
      WRITE (ITUOUT) INPDAT
C
C              PRINT THE FACT THAT WE HAVE OPENED THIS FILE.
C
      TIMEHRS = REAL(ITIME) / 3600.0E0
C
      WRITE (ITUPRT, 300) NSTEPS, ITIME, TIMEHRS, DATSET, ITUOUT,
     1                      KOUNTPAR, IPARITY
C
  300       FORMAT('0', 'FOR NSTEPS =', I5,
     1                  ', ITIME =', I8, ' S, TIMEHRS =',
     2                  F8.4, ' H AFTER I.C.:' /
     3             ' ', 4X, 'DATA SET ', A6,
     4                  ' WAS OPENED ON OUTPUT UNIT',
     5                  I3, ' FOR POSTPROCESSING.  ',
     6                  '  TOTAL NO. OF PACKED FIELDS =', I5,
     7                  ',  PARITY CHECK =', I8, '.')
C
C              PRINT THE FACT THAT WE HAVE OPENED THIS FILE.
C         AND  PRINT THE OFFICE NOTE 85 LABEL.
C
      WRITE (ITUPRT, 400) DATSET, ITUOUT
  400 FORMAT ('0     NCEP DATE WORD FOR FILE ',A6,
     1             ' WAS WRITTEN TO THE DISK WITH UNIT NUMBER ',I2,
     2             '.  THE DATE IS:')
c
      WRITE (ITUPRT, 500) DATSET, IGMT0, IDAY0,
     1                IMNTH0, IYEAR0, IRUNMK, 
     2                ISETIM, IVERSN
c
  500 FORMAT (' FILE=',A6,' INITIAL TIME=',I3,' GMT',I3,'/',
     2             I3,'/',I5,/,25X,'RUN MARKER=',I3,
     4             ', SET INITIATE TIME=',I5,
     5             '  MODEL VERSION=',I10)
C
      RETURN
      END
