C$$$  MAIN PROGRAM DOCUMENTATION BLOCK
C
C MAIN PROGRAM:  TERRAIN  TERRAIN MAKER FOR GLOBAL SPECTRAL MODEL
C   PRGMMR: IREDELL       ORG: W/NMC23       DATE: 92-04-16
C
C ABSTRACT: THIS PROGRAM CREATES 4 TERRAIN-RELATED FILES
C   COMPUTED FROM THE NAVY 10-MINUTE TERRAIN DATASET.
C   THE MODEL PHYSICS GRID PARAMETERS AND SPECTRAL TRUNCATION
C   ARE READ BY THIS PROGRAM AS INPUT.
C   THE 4 FILES PRODUCED ARE RESPECTIVELY:
C     1) SEA-LAND MASK ON MODEL PHYSICS GRID USED BY ASFC PROGRAM
C     2) GRIDDED OROGRAPHY ON MODEL PHYSICS GRID USED BY ASFC PROGRAM
C     3) MOUNTAIN VARIANCE ON MODEL PHYSICS GRID USED BY FCST PROGRAM
C     4) SPECTRAL OROGRAPHY IN SPECTRAL DOMAIN USED BY CHGR PROGRAM
C
C PROGRAM HISTORY LOG:
C   92-04-16  IREDELL
C
C USAGE:
C
C   INPUT FILES:
C     UNIT5      - PHYSICS LONGITUDES (IM), PHYSICS LATITUDES (JM),
C                  SPECTRAL TRUNCATION (NM) AND RHOMBOIDAL FLAG (NR)
C                  RESPECTIVELY READ IN FREE FORMAT.
C     UNIT11     - PACKED NAVY 10-MINUTE TERRAIN DATASET.
C
C   OUTPUT FILES:
C     UNIT51     - SEA-LAND MASK (IM,JM)
C     UNIT52     - GRIDDED OROGRAPHY (IM,JM)
C     UNIT53     - MOUNTAIN VARIANCE (IM,JM)
C     UNIT54     - SPECTRAL OROGRAPHY ((NM+1)*((NR+1)*NM+2))
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:
C     TERSUB     - MAIN SUBPROGRAM
C     SPHERT     - SPHERICAL TRANSFORM
C     GAUSSLAT   - COMPUTE GAUSSIAN LATITUDES
C     EQUALLAT   - COMPUTE EQUALLY-SPACED LATITUDES
C     LEGENDRE   - COMPUTE LEGENDRE POLYNOMIALS
C     FFTFAX     - FFT (LIBRARY CALL CAN BE SUBSTITUTED)
C     RFFTMLT    - FFT (LIBRARY CALL CAN BE SUBSTITUTED)
C     LIBRARY:
C     GBYTES     - UNPACK BITS
C     QPASS      - FFT UTILITY
C     RPASS      - FFT UTILITY
C
C   REMARKS: FORTRAN 9X EXTENSIONS ARE USED.
C
C ATTRIBUTES:
C   CRAY YMP.
C
C$$$
CFPP$ NOCONCUR F
      READ(5,*) IM,JM,NM,NR
      NW=(NM+1)*((NR+1)*NM+2)
      CALL TERSUB(IM,JM,NM,NR,NW)
      STOP
      END
