      SUBROUTINE BIGCHG( NPAIR, NGG, NPOINT )
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    BIGCHG      DETECTS LARGE CHANGES IN NGM ARRAYS
C   PRGMMR: JIM TUCCILLO         ORG: W/NMC4    DATE: 90-06-13
C
C ABSTRACT: DETECTS LARGE CHANGES IN AN NGM ARRAY
C     AND STOP IF THEY ARE DETECTED
C
C PROGRAM HISTORY LOG:
C   90-06-13  JIM TUCCILLO
C
C USAGE:    CALL BIGCHG (NPAIR, NGG, NPOINT)
C   INPUT ARGUMENT LIST:
C     NPAIR    - SOMETHING OR OTHER
C     NGG      - GRID NUMBER
C     NPOINT   - POINT NUMBER
C
C   OUTPUT FILES:
C     IOUTUPRT - FOR PRINTOUT
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - ERRPRINT
C                  PRT
C     LIBRARY:
C       COMMON   - COMCONST
C                  COMBLANK
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:43:47  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      REAL R1S,R2S
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
      DIMENSION FMAXOLD(71,INGRDUSE), FMAXNEW(71,INGRDUSE),
     1          FMINOLD(71,INGRDUSE), FMINNEW(71,INGRDUSE),
     2             KREM(71,INGRDUSE),    NFAIL(INGRDUSE)
C
C
      DATA ICALL /0/
      DATA JFAIL /0/
C
C     SPECIFY THE UNIT NUMBER OF THE PRINTER.
C
C     SPECIFY THE UNIT NUMBER OF THE PRINTER.
      IOUTUPRT = 6
C
      IF( ICALL .GT. 0 ) GO TO 100
C
CMIC$ DO ALL SHARED(NGRDUSE, FMAXNEW, FMINNEW) PRIVATE(NG, K)
      DO 10 NG = 1, 71*NGRDUSE
C
         FMAXNEW(NG,1) = 0.E0
         FMINNEW(NG,1) = 0.E0
   10 CONTINUE
C
  100 CONTINUE
C
      ICALL=ICALL+1
CMIC$ DO ALL SHARED(NGRDUSE, IADDRG, IMG, JMG, FMAXNEW, FMAXOLD, FMINNEW
CMIC$1   , FMINOLD, VBL) PRIVATE(NG, IAD, IJ, K, FMIN, FMAX, I)
      DO 110 NG=1,NGRDUSE
      IAD=IADDRG(1,NG) - 1
      IJ=IMG(NG) * JMG(NG)
C
        DO 105 K=1,71
        FMAXOLD(K,NG)=FMAXNEW(K,NG)
        FMINOLD(K,NG)=FMINNEW(K,NG)
        FMIN = VBL(IAD+1)
        FMAX = VBL(IAD+1)
        DO 286 I = 1, IJ
           FMIN = AMIN1 ( FMIN, VBL ( I + IAD ) )
           FMAX = AMAX1 ( FMAX, VBL ( I + IAD ) )
286     CONTINUE
        FMINNEW(K,NG)= FMIN
        FMAXNEW(K,NG)= FMAX
        IAD=IAD+IJ
  105   CONTINUE
  110 CONTINUE
C
C          TEST THE DIFFERENCES
      IF( ICALL .LE. 1 ) RETURN
C
CMIC$ DO ALL SHARED(NGRDUSE, KM, NFAIL, KREM, FMAXOLD, FMAXNEW, FMINOLD
CMIC$1   , FMINNEW) PRIVATE(NG, DENOM, K, X, Y, D1, D2, F1, F2)
      DO 120 NG=1,NGRDUSE
      NFAIL(NG)=0
C
        DO 115 K=1,71
        KREM(K,NG)=0
        X=ABS(FMAXOLD(K,NG) )
        Y=ABS(FMAXNEW(K,NG) )
        IF( Y .GT. X ) X=Y
        Y=ABS(FMINOLD(K,NG) )
        IF( Y .GT. X ) X=Y
        Y=ABS(FMINNEW(K,NG) )
        IF( Y .GT. X ) X=Y
C       AVOID TOO SMALL A DENOMINATOR FOR HQ FIELD
           DENOM=.001E0
C       AVOID TOO SMALL A VELOCITY IN LOWEST LAYERS
        IF( K .LE. 2*KM) X=50.E0
        IF( X .LT. DENOM ) X=DENOM
        D1=ABS(FMINNEW(K,NG)-FMINOLD(K,NG) )
        D2=ABS(FMAXNEW(K,NG)-FMAXOLD(K,NG) )
        F1=D1/X
        F2=D2/X
        IF(F1 .GT. 0.1E0 )  THEN
          NFAIL(NG)=NFAIL(NG)+1
          KREM(K,NG)=1
        END IF
        IF( F2 .GT. 0.1E0 )  THEN
          NFAIL(NG)=NFAIL(NG)+1
          KREM(K,NG)=KREM(K,NG)+2
        END IF
  115   CONTINUE
  120 CONTINUE
C
C          LOOK FOR THE FAILURES
      NTOTAL=0
      DO 125 NG=1,NGRDUSE
      NTOTAL=NTOTAL+NFAIL(NG)
  125 CONTINUE
           IF( NTOTAL .LE. 0 ) RETURN
C
      JFAIL=JFAIL+1
C
      WRITE (IOUTUPRT, 130) NPOINT,NGG,NPAIR,NTOTAL
  130 FORMAT(1H1,2X,'******LARGE CHANGE AT NPOINT=',I3,' WHEN',
     1 ' FORECASTING GRID',I3,',NPAIR=',I3,'. NTOTAL=',I5)
      WRITE (IOUTUPRT, 132)
  132 FORMAT(1H0,20X,'(0,1,2,3=NO FAIL,MIN FAIL,MAX FAIL,BOTH FAIL)' )
      WRITE (IOUTUPRT, 135)
  135 FORMAT(1H0,12X,'K',2X,'GRID 1',2X,'GRID 2',2X,'GRID 3')
C
      DO 145 K=1,71
      WRITE (IOUTUPRT, 140) K,(KREM(K,N), N=1,NGRDUSE )
  140 FORMAT(1H ,5X,4I8)
  145 CONTINUE
C
C      PRINT OUT FIRST FAILED ARRAY OF EACH GRID
      DO 170 NG=1,NGRDUSE
      IF( NFAIL(NG) .EQ. 0 ) GO TO 170
      IM=IMG(NG)
      JM=JMG(NG)
      IJ=IM*JM
        DO 160 K=1,71
        IF( KREM(K,NG) .LE. 0 ) GO TO 160
        IAD=IADDRG(1,NG) + (K-1)*IJ
        WRITE (IOUTUPRT, 150) K,NG
  150   FORMAT(1H1,25X,'VBL OF LEVEL',I3,' OF GRID',I3)
        XMIN = VBL(IAD)
        XMAX = VBL(IAD)
CMIC$ PARALLEL SHARED(IJ, XMIN, IAD, XMAX, VBL) PRIVATE(I, R1S, R2S)
      R1S = XMIN
      R2S = XMAX
CMIC$ DO PARALLEL VECTOR
      DO 673 I = 1, IJ
         R1S = AMIN1(R1S,VBL(IAD+I-1))
         R2S = AMAX1(R2S,VBL(IAD+I-1))
  673 CONTINUE
CMIC$ GUARD
      XMAX = AMAX1(XMAX,R2S)
CMIC$ END GUARD
CMIC$ GUARD
      XMIN = AMIN1(XMIN,R1S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
        WRITE (IOUTUPRT, 155) XMIN,XMAX
  155   FORMAT(1H0,10X,'NEW MIN AND MAX VALUES ARE',2E14.6)
        WRITE (IOUTUPRT, 156) FMINOLD(K,NG),FMAXOLD(K,NG)
  156   FORMAT(1H0,10X,'OLD MIN AND MAX VALUES ARE',2E14.6)
C
             CALL PRT( VBL(IAD),IM,JM)
        GO TO 170
C
  160   CONTINUE
C
  170 CONTINUE
C
C          WE DONT STOP UNTIL JFAIL HAS REACHED SET VALUE
      IF (JFAIL .GE. 2 ) THEN
C*****  Code Expanded From Routine:  ERRPRINT
      PRINT 77053
77053 FORMAT (1H1, '  **********  PRINT FROM SUBROUTINE ERRPRINT ',
     1             'FOLLOWS. ***********')
C
      PRINT 77054, IJMAX, KM, LVLTOT, NGRDUSE, NH
77054 FORMAT (1H1, 2X, 'IJMAX, KM, LVLTOT, NGRDUSE, NH =', 5I10)
C
      PRINT 77055, NTIME, ITIME, NSTEPS
77055 FORMAT (1H0, 2X, 'NTIME, ITIME, NSTEPS= ', 3I10 /)
C*****  End of Code Expanded From Routine:  ERRPRINT
C
         WRITE(IOUTUPRT,8881)
8881     FORMAT(' IN BIGCHG, JFAIL IS GREATER THAN OR EQUAL TO 2')
C
         CALL EXIT(16)
C
      END IF
C
      RETURN
      END
