      SUBROUTINE BITHOLE( BITH, BITU, BITV, IM, IA, IB, JA, JB )
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    BITHOLE     INSERTS ZEROS FOR HOLE ON BIT VECTORST
C   PRGMMR: JIM TUCCILLO         ORG: W/NMC4    DATE: 90/06/13
C
C ABSTRACT: TAKES THE PARTIALLY CONSTRUCTED CONTROL
C   .       STORE BIT VECTORS BITH,BITU,BITV AND INSERT
C   .       ZEROS FOR AN INTERIOR HOLE ON GRIDS NG=1,2,
C   .       THROUGH NGRDUSE-1.
C   .       THE I-RANGES FOR A HOLE ARE AS FOLLOWS.
C   .         BITU     I=IA THROUGH IB
C   .         BITH     I=IA THROUGH IB
C   .         BITV     I=(IA-1) THROUGH IB.
C   .       THESE ARE APPLIED FOR THE FOLLOWING J-RANGES.
C   .         BITU     J=(JA-1) THROUGH JB
C   .         BITH     J=JA THROUGH JB
C   .         BITV     J=JA THROUGH JB.
C   .
C   .       THE HOLE OF ZEROS IS THE SAME FOR BOTH TIME STEPS
C   .       ( AS REPRESENTED BY THE SECOND DIMENSION IN THE
C   .         BIT ARRAYS. )
C
C PROGRAM HISTORY LOG:
C   90-06-13  J TUCCILLO
C
C USAGE:  CALL BITHOLE(BITH,BITU,BITV,IM,IA,IB,JA,JB )
C   INPUT ARGUMENT LIST:
C     IM       - DIMENSION OF
C                I-ROW FOR THIS GRID.
C     .
C     IA,IB    - LOCATION OF HOLE BOUNDARIES
C     JA,JB
C     .
C     BITH,    - CONTROL STORE BIT VECTORS FOR
C     BITU,        THIS GRID.
C     BITV
C
C   OUTPUT ARGUMENT LIST:
C     BITH,    - CONTROL STORE BIT VECTORS
C     BITU,
C     BITV
C
C   OUTPUT FILES:
C     IOUTUPRT - FOR PRINTOUT OF ERROR MESSAGE
C
C   SUBPROGRAMS CALLED:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:44:15  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
      LOGICAL BITH(IIJMAX, 2), BITU(IIJMAX, 2), BITV(IIJMAX, 2)
C
C              LENGTH FOR I-RANGE OF BITU AND BITH
        LEN1=IB-IA+1
C              LENGTH FOR I-RANGE OF BITV
        LEN2=LEN1+1
C
CMIC$ DO ALL SHARED(JA, IM, IA, LEN1, JB, LEN2, BITU, BITH, BITV)
CMIC$1    PRIVATE(IADD, NPAIR, IQ2W6E, J)
      DO 400 NPAIR=1,2
C              ADDRESS FOR I=IA ON ROW JA-1.
        IADD=(JA-2)*IM + IA
C              PUT IN ZEROS FOR ROW JA-1 IN BITU
      DO 88890 IQ2W6E=1,LEN1
         BITU(IADD+IQ2W6E-1,NPAIR)= .FALSE.
88890 CONTINUE
C
C              DO ROWS JA THRU JB FOR ALL BIT VECTORS.
C
      DO 300 J=JA,JB
        IADD=IADD+IM
      DO 88900 IQ2W6E=1,LEN1
         BITU(IADD+IQ2W6E-1,NPAIR) = .FALSE.
         BITH(IADD+IQ2W6E-1,NPAIR) =.FALSE.
88900 CONTINUE
      DO 88920 IQ2W6E=1,LEN2
         BITV(IADD+IQ2W6E-2,NPAIR) = .FALSE.
88920 CONTINUE
  300 CONTINUE
C
  400 CONTINUE
C
      RETURN
      END
