      SUBROUTINE BLEND(A,IM,JM,LTBN)
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:45:34  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      DIMENSION A(1)
C
      DATA FI/0.5E0/,FO/0.5E0/,NGO/1/,NGI/1/
C
      LTBNP1 = LTBN + 1
      LTBNP2 = LTBN + 2
C
C          DEFINE FACTOR
C SOUTH ROW
      LENX= IM - 2 * LTBNP1
      N = LTBN * IM + LTBNP2
      NN = N + IM
      NS = N - IM
CMIC$ DO ALL VECTOR IF ((ABS(NN-N).GE.LENX .OR. NN-N.EQ.0) .AND. (ABS(NS
CMIC$1   -N).GE.LENX .OR. NS-N.EQ.0)) SHARED(LENX, NN, FI, NS, FO, N, A)
CMIC$2    PRIVATE(IQ2W6E)
      DO 88890 IQ2W6E=1,LENX
         A(N+IQ2W6E-1)=A(NN+IQ2W6E-1)*FI+A(NS+IQ2W6E-1)*FO
88890 CONTINUE
C NORTH ROW (LAST ROW IS USED, BLEND NEXT TO LAST ROW)
      N = (JM-LTBNP1) * IM + LTBNP2
      NN = N + IM
      NS = N - IM
CMIC$ DO ALL VECTOR IF ((ABS(NN-N).GE.LENX .OR. NN-N.EQ.0) .AND. (ABS(NS
CMIC$1   -N).GE.LENX .OR. NS-N.EQ.0)) SHARED(LENX, NN, FO, NS, FI, N, A)
CMIC$2    PRIVATE(IQ2W6E)
      DO 88900 IQ2W6E=1,LENX
         A(N+IQ2W6E-1)=A(NN+IQ2W6E-1)*FO+A(NS+IQ2W6E-1)*FI
88900 CONTINUE
C
      IWEST = LTBNP1
      IEAST = IM - LTBN
C
      DO 100 J = LTBNP2,JM-LTBNP1
      M = (J-1) * IM
C
C WEST COLUMN (1ST COLUMN IS UN-USED, KEEP 2ND COLUMN, BLEND 3RD COLUMN)
      N = M + IWEST
      NE = N + NGI
      NW = N - NGO
      A(N) = A(NE)*FI + A(NW)*FO
C
C EAST COLUMN
      N = M + IEAST
      NE = N + NGO
      NW = N - NGI
      A(N) = A(NE)*FO + A(NW)*FI
C
 100  CONTINUE
C
C FOUR CORNERS
C (SOUTH-WEST)
      N = LTBN*IM + LTBNP1
      A(N) = 0.25E0 * (A(N+1) + A(N-1) + A(N+IM) + A(N-IM))
C (SOUTH-EAST)
      N = LTBNP1*IM - LTBN
      A(N) = 0.25E0 * (A(N+1) + A(N-1) + A(N+IM) + A(N-IM))
C (NORTH-WEST)
      N = (JM-LTBNP1)*IM + LTBNP1
      A(N) = 0.25E0 * (A(N+1) + A(N-1) + A(N+IM) + A(N-IM))
C (NORTH-EAST)
      N = (JM-LTBN)*IM - LTBN
      A(N) = 0.25E0 * (A(N+1) + A(N-1) + A(N+IM) + A(N-IM))
C
      RETURN
      END
