      SUBROUTINE CONVRT(IQ,GRID,NPTS,gridout)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .     
C SUBPROGRAM:    CONVRT      CONVERT ON84 TO GRIB1 UNITS
C   PRGRMMR: TREADON         ORG: W/NMC2     DATE: 93-06-17
C     
C ABSTRACT:
C     THIS ROUTINE CONVERTS ON84 UNITS TO GRIB1 UNITS.
C     THE ROUTINE KEYS ON THE ON Q INTEGER OF THE ON84
C     LABEL TO DETERMINE THE UNIT CONVERSION (IF 
C     NECESSARY.
C   .     
C     
C PROGRAM HISTORY LOG:
C   93-06-17  RUSS TREADON
C     
C USAGE:    CALL CONVRT(IQ,GRID,NPTS)
C   INPUT ARGUMENT LIST:
C     IQ       - ON84 Q INTEGER (IE, FIELD IDENTIFIER)
C     GRID     - ARRAY OF DATA IN ON84 UNITS
C     NPTS     - DIMENSION OF ARRAY
c     gridout  - grid values properly scaled for grib
C
C   OUTPUT ARGUMENT LIST: 
C     GRID     - ARRAY OF DATA IN GRIB1 UNITS
C     
C   OUTPUT FILES:
C     NONE
C     
C   SUBPROGRAMS CALLED:
C     UTILITIES:
C       NONE
C     LIBRARY:
C       NONE
C     
C   ATTRIBUTES:
C     LANGUAGE: FORTRAN
C     MACHINE : CRAY Y-MP
C$$$  
C     
C     
C     DELCARE PARAMETERS
      PARAMETER ( RHOWAT=1.E3 )
C
C     DECLARE VARIABLES
      INTEGER IQ,NPTS
      REAL GRID(NPTS),gridout(npts)
C     
C**********************************************************************
C     START CONVRT HERE.
C     
C     ASSUMUE NO CONVERSION NECESSARY.
      SCALE = 1.
      do k=1,npts
      gridout(k) = grid(k)
      end do
C
C     CONVERT PRESSURE OR PRESSURE VERTICAL VELOCITY FROM MB TO PA.  
      IF ( (IQ.EQ.8) .OR. (IQ.EQ.40) ) SCALE = 100.
C     
C     CONVERT PRECIPITATION IN M TO KG/M2.
      IF ( (IQ.EQ.105).OR.(IQ.EQ.094).OR.
     X     (IQ.EQ.090).OR.(IQ.EQ.093) ) SCALE = RHOWAT
C     
C     CONVERT CLOUD FRACTIONS TO PERCENT
      IF ( (IQ.EQ.512).OR.(IQ.EQ.513).OR.(IQ.EQ.514) ) SCALE=100.
C     
C     CONVERT MOISTURE CONVERGENCE TO MOISTURE DIVERGENCE.
      IF ( (IQ.EQ.103) ) SCALE = -1.
C     
C     RESCALE FROM ON84 TO GRIB (IF NECESSARY).
      IF (INT(SCALE).NE.1) THEN
         DO 10 K = 1,NPTS
            GRIDout(K) = SCALE*GRID(K)
 10      CONTINUE
      ENDIF
C     
C     END OF ROUTINE.
      RETURN
      END
