      SUBROUTINE COSZEN (NG,GCT,DAYJUL,W,X,Y,Z,ZZ,CZEN,NOONALL)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    COSZEN      COMPUTE COSINE OF THE SOLAR ZENITH ANGLE
C   PRGMMR: JIM TUCCILLO         ORG: W/NMC4    DATE: 90-06-13
C
C ABSTRACT: COMPUTES COSINE OF THE SOLAR ZENITH ANGLE
C   THROUGH THE FOLLOWING SIMPLIFIED FORMULA
C   .
C   .      COS(ZEN ANG) = SIN(LAT) * SIN(DECLIN)  +
C   .
C   .                     COS(LAT) * COS(DECLIN) * COS(HRANG)
C   .      WHERE
C   .                 LAT = LATITUDE
C   .                 DECLIN IS SOLAR DECLINATION ANGLE
C   .                 HRANG IS THE SOLAR HOUR ANGLE-----THE
C   .                 RADIANS OF LONGITUDE BETWEEN A POINT AND
C   .                 THE LONGITUDE OF THE SUN.
C   .
C
C PROGRAM HISTORY LOG:
C   90-06-13  J TUCCILLO
C
C USAGE:    CALL COSZEN (NG,GCT,DAYJUL,W,X,Y,Z,ZZ,CZEN,NOONALL)
C   INPUT ARGUMENT LIST:
C     NG       - NGM GRID NUMBER
C     GCT      - GREENWICH TIME IN HOURS
C     DAYJUL   - JULIAN DAY
C     X,Y,Z,ZZ - FOUR WORK AREAS EACH OF SIZE AT LEAST
C                EQUAL TO THE NUMBER OF GRID POINTS OF NG
C     NOONALL  - A FLAG:
C                NOONALL .EQ. 0:    COMPUTE WITH PROPER LONGITUDE
C                NOONALL .NE. 0:    PRETEND IT IS NOON EVERYWHERE
C
C   OUTPUT ARGUMENT LIST:
C     CZEN     - COSINE OF ZENITH ANGLE
C        W     - LATITUDE  IN DEGREES (-90 S.P. TO +90 N.P.)
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C       COMMON   - COMCONST
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:48:06  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      DIMENSION   W(IIJMAX),X(IIJMAX),Y(IIJMAX),
     1            Z(IIJMAX),ZZ(IIJMAX),CZEN(IIJMAX),BITT(IIJMAX)
C
      LOGICAL BITT
C
C
C       GET ARRAYS OF X-X(POLE) AND Y-Y(POLE)
C      (THESE ARE NORMALIZED BY 2*RADIUS SO AS TO EQUAL 1 AT EQUATOR)
      IM = IMG(NG)
      JM = JMG(NG)
      IJ = IM * JM
      XP = XPOLEH(NG)
      YP = YPOLEH(NG)
C        GET DMAP = DELTA(NG) / 2* EARTH RADIUS
      DMAP = FLOAT(NH) + 0.5E0
      IF( NG .GT. 1 ) DMAP = DMAP * (2.E0 ** (NG-1) )
C        REALLY NEED THE RECIPROCAL
      DMAP = 1.E0 / DMAP
C
      XX = (1.E0 - XP ) * DMAP
      DO 5 I = 1,IM
      X(I) = XX
      XX = XX + DMAP
    5 CONTINUE
      IAD = IM + 1
CMIC$ DO ALL SHARED(JM, IM, IAD, X) PRIVATE(J, IQ2W6E)
      DO 10 J = 1, JM - 1
         DO 77001 IQ2W6E = 1, IM
            X(IAD+IQ2W6E-1+(J-1)*IM) = X(IQ2W6E)
77001    CONTINUE
   10 CONTINUE
      YY = (1.E0 -YP) * DMAP
      IAD = 1
      DO 15 J = 1,JM
CMIC$ DO ALL VECTOR SHARED(IM, YY, IAD, Y) PRIVATE(IQ2W6E)
      DO 88900 IQ2W6E=1,IM
         Y(IAD+IQ2W6E-1)=YY
88900 CONTINUE
      YY = YY + DMAP
      IAD = IAD + IM
   15 CONTINUE
C            DONE COMPUTING  X   AND   Y   .
C           PUT SINE OF LATITUDE INTO SIND(ARRAY CZEN USED FOR WORK)
CMIC$ DO ALL VECTOR SHARED(IJ, X, ZZ, Y, W, Z, BITT) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E = 1, IJ
         ZZ(IQ2W6E) = X(IQ2W6E)*X(IQ2W6E)
         W(IQ2W6E) = Y(IQ2W6E)*Y(IQ2W6E)
         W(IQ2W6E) = W(IQ2W6E) + ZZ(IQ2W6E)
         ZZ(IQ2W6E) = 1.E0 + W(IQ2W6E)
         W(IQ2W6E) = 1.E0 - W(IQ2W6E)
         ZZ(IQ2W6E) = W(IQ2W6E)/ZZ(IQ2W6E)
         Z(IQ2W6E) = SQRT(1.E0-ZZ(IQ2W6E)*ZZ(IQ2W6E))
         BITT(IQ2W6E) = Z(IQ2W6E) .GE. 0.0001E0
         IF (BITT(IQ2W6E)) THEN
            W(IQ2W6E) = 1.E0 + ZZ(IQ2W6E)
            W(IQ2W6E) = W(IQ2W6E)/Z(IQ2W6E)
            X(IQ2W6E) = X(IQ2W6E)*W(IQ2W6E)
            Y(IQ2W6E) = Y(IQ2W6E)*W(IQ2W6E)
         ENDIF
         IF (.NOT.BITT(IQ2W6E)) THEN
            X(IQ2W6E) = 1.E0
            Y(IQ2W6E) = 0.E0
         ENDIF
88910 CONTINUE
C
C        GET THE LONGITUDE OF THE SUN WITH RESPECT TO GREENWICH
      PI = 3.1415926E0
      SUNLONG = PI * (1.E0 - (GCT/12.E0 ) )
C        IF NOONALL .EQ. 0,  COMPUTE HOURANGLE AS IT SHOULD BE .
C        IF NOONALL .NE. 0,  PRETEND THAT IT IS NOON EVERYWHERE.
C
      IF( NOONALL .EQ. 0 ) THEN
C         HOURANGLE DEPENDS ON LONGITUDE.  FIRST GET THE
C         COSINE AND SINE OF THE SUN LONGITUDE ON THE GRID.
        ANGLE = - (PI*DLAMNGM / 180.E0 ) + SUNLONG
        COSG = COS(ANGLE)
        SING = SIN(ANGLE)
C        GET COSINE OF SUN HOUR ANGLE (FOR EACH GRID POINT) INTO RHOD
CMIC$ DO ALL VECTOR SHARED(IJ, COSG, SING, X, W, Y) PRIVATE(IQ2W6E)
      DO 89070 IQ2W6E=1,IJ
         W(IQ2W6E)=COSG*X(IQ2W6E)
         W(IQ2W6E)=W(IQ2W6E)+SING*Y(IQ2W6E)
89070 CONTINUE
      ELSE
C               PRETEND THAT IT IS NOON EVERYWHERE
CMIC$ DO ALL VECTOR SHARED(IJ, W) PRIVATE(IQ2W6E)
      DO 89090 IQ2W6E=1,IJ
         W(IQ2W6E)=1.E0
89090 CONTINUE
      END IF
C        GET THE DECLINATION ANGLE
      ANGLE1 = (DAYJUL - 173.E0 ) * 2.E0 * PI / 365.E0
      DECLIN = 0.40928E0 * COS(ANGLE1)
C        FINALLY GET COSINE OF THE ZENITH ANGLE
      SINDEC = SIN(DECLIN)
      COSDEC = COS(DECLIN)
CMIC$ DO ALL VECTOR SHARED(IJ, SINDEC, COSDEC, ZZ, CZEN, W, Z) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89100 IQ2W6E = 1, IJ
         CZEN(IQ2W6E) = SINDEC*ZZ(IQ2W6E)
         W(IQ2W6E) = W(IQ2W6E)*Z(IQ2W6E)
         CZEN(IQ2W6E) = CZEN(IQ2W6E) + COSDEC*W(IQ2W6E)
         W(IQ2W6E) = 57.29578*ASIN(ZZ(IQ2W6E))
89100 CONTINUE
C
      RETURN
      END
