C
C
      SUBROUTINE DIAGFCST
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    DIAGFCST    CALCULATES AND PRINTS DIAGNOSTICS
C   PRGMMR: JIM TUCCILLO          ORG: W/NMC4    DATE: 90-06-13
C
C ABSTRACT: CALCULATES AND PRINTS OUT SOME DIAGNOSTICS FOR
C     THE NGM FIELDS AND PRINTS PART OF A REPRESENTATIVE ROW FOR
C     EACH FIELD.
C
C PROGRAM HISTORY LOG:
C   90-06-13  JIM TUCCILLO
C
C USAGE:    CALL DIAGFCST
C   OUTPUT FILES:
C     FT06F001 - FOR PRINTOUT OF DIAGNOSTICS AND PARTS OF FIELDS
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - STATS
C     LIBRARY:
C       COMMON   - COMBLANK
C                  COMCONST
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:51:30  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL  BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      DIMENSION FIELD(IIJKMAX)
C
      EQUIVALENCE (SCR3(1, 10), FIELD(1))
C
      CHARACTER*8 LABEL(2)
      CHARACTER*8 LVAR(10)
C     LGRID IS DIMENSIONED TO BE BIGGER THAN THE NUMBER OF
C     GRIDS WILL EVER BE.
      CHARACTER*8 LGRID(9)
C
C
      DATA LVAR/'NGM U   ','NGM V   ','NGM THET','NGM Q   ','NGM P*  ',
     1          'NGM Z*  ','NGM T*  ','NGM DRAG','NGM Q*  ','NGM ALB '/
      DATA LGRID /' -GRID 1', ' -GRID 2', ' -GRID 3', ' -GRID 4',
     1            ' -GRID 5', ' -GRID 6', ' -GRID 7', ' -GRID 8',
     2            ' -GRID 9'/
C
C              SPECIFY THE POINTERS IN ARRAY IADDRS FOR THE
C              VARIOUS MODEL VARIABLES.
      INDEXHU  =  1
      INDEXHV  =  2
      INDEXHTH =  3
      INDEXHQ  =  4
      INDEXH   =  5
      INDEXST  =  6
      INDEXSQ  =  7
      INDEXALB =  8
      INDEXSNO =  9
      INDEXPSI = 10
      INDEXCD  = 11
      INDEXCC  = 12
      INDEXGSP = 13
      INDEXRAD = 14
C
C     ENSURE THAT THE VALUE OF NGRDUSE IS NOT TOO LARGE
C     FOR THIS SUBROUTINE.
      IF (NGRDUSE .LE. 9) GO TO 60
      PRINT 30
   30 FORMAT('0', 'THE VALUE OF NGRDUSE IS TOO LARGE FOR ',
     1            'SUBROUTINE DIAG.  EXECUTION TERMINATED.')
      CALL EXIT(16)
C
   60 CONTINUE
C
C     NOW THE U COMPONENT IS PROCESSED.
C
      DO 1200 NG=1,NGRDUSE
      IM = IMG(NG)
      JM = JMG(NG)
C
C     SPECIFY THE POINTERS FOR VARIOUS VARIABLES IN ARRAY VBL.
      IJ     = IM * JM
      MADDHU = IADDRG(INDEXHU, NG) -1 -IM -IJ
      MADDH  = IADDRG(INDEXH , NG) -1 -IM
C
CMIC$ DO ALL SHARED(JM,KM,IM,MADDHU,IJ,MADDH,VBL,FIELD)PRIVATE(J,K,I)
      DO 1100 J=1,JM
C
      DO 1000 K=1,KM
C
      DO 900 I=1,IM
         IF (J .LT. JM) THEN
            FIELD(I + (J-1)*IM + (K-1)*IJ)
     1               = VBL(MADDHU + IM*J +IJ*K + I) * 2.0E0
     2               / (VBL(MADDH+I+IM*J) + VBL(MADDH+I+IM+IM*J))
         ELSE
C
C     IF THIS IS THE LAST ROW, WE ASSUME THAT
C     THE SURFACE PRESSURE OF THE NONEXISTENT NEXT ROW IS THE
C     SAME AS THE CURRENT ROW.
            FIELD(I + (J-1)*IM + (K-1)*IJ)
     1                   = VBL(MADDHU + IM*J +IJ*K + I)
     2                   / VBL(MADDH+I+IM*J)
         END IF
  900 CONTINUE
C
 1000 CONTINUE
C
 1100 CONTINUE
C
      LABEL(1) = LVAR(1)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,KM,KM, LABEL)
C
 1200 CONTINUE
C
C
C     PROCESS THE V COMPONENT.
      DO 2200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
C
C     SPECIFY THE POINTERS FOR VARIOUS VARIABLES IN ARRAY VBL.
      IJ     = IM * JM
      MADDHV = IADDRG(INDEXHV, NG) -1 -IM -IJ
      MADDH  = IADDRG(INDEXH , NG) -1 -IM
C
      DO 2100 J=1,JM
C
      DO 2050 K=1,KM
CMIC$ DO ALL VECTOR SHARED(IM, MADDHV, J, IJ, K, MADDH, VBL, FIELD)
CMIC$1    PRIVATE(I)
      DO 2000 I=1,IM-1
      FIELD(I + (J-1)*IM +(K-1)*IJ)
     1             = VBL(MADDHV + IM*J+IJ*K +I) * 2.0E0
     2             /(VBL(MADDH + I + IM*J) + VBL(MADDH + I + 1 + IM*J))
 2000 CONTINUE
C
      FIELD(IM +(J-1)*IM +(K-1)*IJ)
     1              = VBL(MADDHV +IM*J +IJ*K+IM) / VBL(MADDH+IM+IM*J)
C
 2050 CONTINUE
C
 2100 CONTINUE
C
      LABEL(1) = LVAR(2)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,KM,KM, LABEL)
C
 2200 CONTINUE
C
C
C     PROCESS THE POTENTIAL TEMPERATURE FIELD.
      DO 3200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
C
C     SPECIFY THE POINTERS FOR VARIOUS VARIABLES IN ARRAY VBL.
      IJ     = IM * JM
      MADDHTH = IADDRG(INDEXHTH, NG) -1 -IM -IJ
      MADDH   = IADDRG(INDEXH  , NG) -1 -IM
C
CMIC$ DO ALL SHARED(JM,KM,IM,MADDHTH,IJ,MADDH,VBL,FIELD)PRIVATE(J,K,I)
      DO 3100 J=1,JM
C
      DO 3000 K=1,KM
      DO 3000 I=1,IM
      FIELD(I + (J-1)*IM +(K-1)*IJ)
     1             = VBL(MADDHTH +IM*J + IJ*K +I) / VBL(MADDH+IM*J + I)
 3000 CONTINUE
C
 3100 CONTINUE
C
      LABEL(1) = LVAR(3)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,KM,KM, LABEL)
C
 3200 CONTINUE
C
C
C     PROCESS THE SPECIFIC HUMIDITY FIELD.
      DO 4200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
C
C     SPECIFY THE POINTERS FOR VARIOUS VARIABLES IN ARRAY VBL.
      IJ     = IM * JM
      MADDHQ = IADDRG(INDEXHQ, NG) -1 -IM -IJ
      MADDH  = IADDRG(INDEXH , NG) -1 -IM
C
CMIC$ DO ALL SHARED(JM,KM,IM,MADDHQ,IJ,MADDH,VBL,FIELD)PRIVATE(J,K,I)
      DO 4100 J=1,JM
C
      DO 4000 K=1,KM
      DO 4000 I=1,IM
      FIELD(I + (J-1)*IM +(K-1)*IJ)
     1             = VBL(MADDHQ +IM*J + IJ*K +I) / VBL(MADDH+IM*J + I)
 4000 CONTINUE
C
 4100 CONTINUE
C
      LABEL(1) = LVAR(4)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,KM,KM, LABEL)
C
 4200 CONTINUE
C
C
C     PROCESS THE SURFACE PRESSURE.
      DO 5200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
      MADDRS = IADDRG(INDEXH, NG)
C
C     SPECIFY THE POINTER FOR SURFACE PRESSURE IN ARRAY VBL.
      MADDH  = MADDRS -1 -IM
C
CMIC$ DO ALL SHARED(JM, IM, MADDH, VBL, FIELD) PRIVATE(J, I)
      DO 5100 J=1,JM
C
      DO 5000 I=1,IM
      FIELD(I + (J-1)*IM) = VBL(MADDH + IM*J + I)
 5000 CONTINUE
C
 5100 CONTINUE
C
      LABEL(1) = LVAR(5)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,1,KM, LABEL)
C
 5200 CONTINUE
C
C
C     PROCESS THE GROUND HEIGHT.
      FACTOR = 1005.E0 / 9.8E0
      DO 6200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
      MADDRS = IADDRG(INDEXPSI, NG)
C
C     SPECIFY THE POINTER FOR PSI (RELATED TO GROUND HEIGHT)
C     IN ARRAY VBL.
      MADDPSI  = MADDRS -1 -IM
C
CMIC$ DO ALL SHARED(JM, IM, MADDPSI, FACTOR, VBL, FIELD) PRIVATE(J, I)
      DO 6100 J=1,JM
C
      DO 6000 I=1,IM
      FIELD(I + (J-1)*IM) = VBL(MADDPSI + IM*J + I) * FACTOR
 6000 CONTINUE
C
 6100 CONTINUE
C
      LABEL(1) = LVAR(6)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,1,KM, LABEL)
C
 6200 CONTINUE
C
C
C     PROCESS THE SURFACE TEMPERATURE.
      DO 7200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
      MADDRS = IADDRG(INDEXST, NG)
C
C     SPECIFY THE POINTER FOR SURFACE TEMPERATURE IN ARRAY VBL.
      MADDST   = MADDRS -1 -IM
C
CMIC$ DO ALL SHARED(JM, IM, MADDST, VBL, FIELD) PRIVATE(J, I)
      DO 7100 J=1,JM
C
      DO 7000 I=1,IM
      FIELD(I + (J-1)*IM) = VBL(MADDST +IM*J + I)
 7000 CONTINUE
C
 7100 CONTINUE
C
      LABEL(1) = LVAR(7)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,1,KM, LABEL)
C
 7200 CONTINUE
C
C
C     PROCESS THE DRAG COEFFICIENT.
      DO 8200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
      MADDRS = IADDRG(INDEXCD, NG)
C
C     SPECIFY THE POINTER FOR THE DRAG COEFFICIENT IN ARRAY VBL.
      MADDCD  = MADDRS -1 -IM
C
CMIC$ DO ALL SHARED(JM, IM, MADDCD, VBL, FIELD) PRIVATE(J, I)
      DO 8100 J=1,JM
C
      DO 8000 I=1,IM
      FIELD(I + (J-1)*IM) = VBL(MADDCD + IM*J + I)
 8000 CONTINUE
C
 8100 CONTINUE
C
      LABEL(1) = LVAR(8)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,1,KM, LABEL)
C
 8200 CONTINUE
C
C
C     PROCESS THE SURFACE MOISTURE.
      DO 9200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
      MADDRS = IADDRG(INDEXSQ, NG)
C
C     SPECIFY THE POINTER FOR SURFACE MOISTURE IN ARRAY VBL.
      MADDSQ   = MADDRS -1 -IM
C
CMIC$ DO ALL SHARED(JM, IM, MADDSQ, VBL, FIELD) PRIVATE(J, I)
      DO 9100 J=1,JM
C
      DO 9000 I=1,IM
      FIELD(I + (J-1)*IM) = VBL(MADDSQ + IM*J + I)
 9000 CONTINUE
C
 9100 CONTINUE
C
      LABEL(1) = LVAR(9)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,1,KM, LABEL)
C
 9200 CONTINUE
C
C
C     PROCESS THE ALBEDO.
      DO 10200 NG=1,NGRDUSE
C
      IM = IMG(NG)
      JM = JMG(NG)
      MADDRS = IADDRG(INDEXALB, NG)
C
C     SPECIFY THE POINTER FOR THE ALBEDO IN ARRAY VBL.
      MADDALB  = MADDRS -1 -IM
C
CMIC$ DO ALL SHARED(JM, IM, MADDALB, VBL, FIELD) PRIVATE(J, I)
      DO 10100 J=1,JM
C
      DO 10000 I=1,IM
      FIELD(I + (J-1)*IM) = VBL(MADDALB +IM*J + I)
10000 CONTINUE
C
10100 CONTINUE
C
      LABEL(1) = LVAR(10)
      LABEL(2) = LGRID(NG)
      CALL STATS(FIELD, 1,IM,IM, 1,JM,JM, 1,1,KM, LABEL)
C
10200 CONTINUE
C
      RETURN
      END
