      SUBROUTINE JULDAY ( ID , IM , IY , JD )
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    JULDAY      COMPUTES THE JULIAN DAY
C   PRGMMR: J TUCCILLO       ORG: W/NMC22    DATE: 90-06-13
C
C ABSTRACT:  COMPUTES THE JULIAN DAY FROM THE DAY OF THE MONTH
C   .        WITH CONSIDERATION OF WHETHER ITS A LEAP YEAR.
C   .
C
C PROGRAM HISTORY LOG:
C   90-06-13  J TUCCILLO
C   98-09-14  HANN-MING HENRY JUANG for Y2K
C
C USAGE:  CALL JULDAY ( ID , IM , IY , JD )
C   INPUT ARGUMENT LIST:
C     ID       - THE DAY OF THE MONTH
C     IM       - THE MONTH OF THE YEAR
C     IY       - THE YEAR (FULL DIGITS)
C
C   OUTPUT ARGUMENT LIST:
C     JD       - THE JULIAN DAY
C
C REMARKS:
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   IMONTH      NUMBER OF DAYS IN EACH MONTH              /MONTH/
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP 
C
C$$$
C
      COMMON/MONTH/IMONTH(0:12)
C
      DATA IMONTH/31,31,28,31,30,31,30,31,31,30,31,30,31/
C
C     LEAP YEAR EVERY 4 YEARS EXCEPT FOR EVERY 400 YEARS 
C
CHMHJ
      IF (MOD(IY,4).EQ.0 .AND. MOD(IY,400).NE.0) THEN
         IMONTH(2)=29
      ELSE
         IMONTH(2)=28
      END IF
      JD=ID
      DO 2 K=1,IM-1
           JD=JD+IMONTH(K)
2     CONTINUE
C
C
      RETURN
      END
