      SUBROUTINE LWRADIAT(DTC3,NOZ,PL,PL2,TL,TG,TSA,QL,O3L,CLD,CLU,
     *                    ATLX,RS,ULWBOT,DLWBOT,ULWTOP,RSCLR,ULTCLR)
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    LWRADIAT    PERFORMS LONGWAVE RADIATION COMPUTATIONS
C   PRGMMR: J TUCCILLO       ORG: W/NMC22    DATE: 90-06-17
C
C ABSTRACT:  COMPUTES ATMOSPHERIC TEMPERATURE TENDENCIES FROM
C   .        LONGWAVE RADIATION AND THE NET LONGWAVE RADIATIVE FLUX
C   .        AT THE SURFACE OF THE EARTH FOR THE SURFACE ENERGY
C   .        BUDGET.
C   .        ( GLA LONGWAVE CODE FROM HARSHVARDHAN )
C   .
C
C PROGRAM HISTORY LOG:
C   90-06-17  J TUCCILLO
C   88-09-01  B SCHMIDT REVISED THE DOCBLOCK
C
C USAGE:  CALL LWRADIAT(DTC3,NOZ,PL,PL2,TL,TG,TSA,QL,O3L,CLD,CLU
C                       ATLX,RS,ULWBOT,DLWBOT,ULWTOP,RSCLR,ULTCLR)
C   INPUT ARGUMENT LIST:
C     DTC3     -  TIMESTEP IN SECS ( 1 IS USED )
C     NOZ      -  LOGICAL FOR WHETHER TO DO OZONE
C                 ( TRUE FOR NO OZONE CALCULATIONS )
C     PL       -  PRESSURE AT MID POINTS OF LAYERS ( MBS )
C     PL2      -  PRESSURE AT INTERFACES OF LAYERS ( MBS )
C     TL       -  TEMPERATURE OF LAYERS ( DEGS K )
C     TG       -  SKIN TEMPERATURE ( DEGS K )
C     TSA      -  AIR TEMPERATURE ( DEGS K )
C     QL       -  SPECIFIC HUMIDITY OF LAYERS ( GRMS/GRM )
C     O3L      -  OZONE OF LAYERS ( MIXING RATIO )
C     CLD      -  RANDOM OVERLAP CLOUD AMOUNTS ( 0 - 1 )
C     CLU      -  MAXIMUM OVERLAP CLOUD AMOUNTS ( 0 - 1 )
C
C   OUTPUT ARGUMENT LIST:
C     ATLX     -  ATMOSPHERIC TEMPERATURE TENDENCIES FROM
C                 LONGWAVE RADIATION ( DEGS K / DTC3 )
C     RS       -  DIAGNOSTIC QUANTITY
C     ULWBOT   -  UPWARD LONGWAVE FLUX AT THE SURFACE
C                 OF THE EARTH ( WATTS / M**2 )
C     DLWBOT   -  DOWNWARD LONGWAVE FLUX AT THE SURFACE
C                 OF THE EARTH ( WATTS / M**2 )
C     ULWTOP   -  DIAGNOSTIC QUANTITY
C     RSCLR    -  DIAGNOSTIC QUANTITY
C     ULTCLR   -  DIAGNOSTIC QUANTITY
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - LWCRUNCH
C                  RDEXP83
C                  LWFLUX      RDEXP6
C                  LWCLDSLW    RDEXP56
C                  RDHGATHR    RDEXP57
C     LIBRARY:
C       COMMON   - BLANK
C                  H2O
C
C REMARKS:  SEE COMMENTS AFTER THE DOCBLOCK
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
C
C     LONG-WAVE RADIATION PARAMETERIZATION DEVELOPED BY HARSHVARDHAN,
C     1983. BASED ON THE FOLLOWING REFERENCES:
C     1. "BROADBAND WATER VAPOR TRANSMISSION FUNCTIONS FOR ATMOSPHERIC
C         I.R. FLUX COMPUTATIONS", MING-DAH CHOU ; SUBMITTED TO JAS
C         (1983).
C     2. "A PARAMETERIZATION OF THE ABSORPTION IN THE 15 MICRON CO2
C         SPECTRAL REGION WITH APPLICATION TO CLIMATE SENSITIVITY
C         STUDIES", MING-DAH CHOU AND LI PENG ; TO APPEAR IN JAS (1983).
C     3. "SOME EXTENSIONS AND APPLICATIONS OF THE NEW RANDOM MODEL FOR
C         MOLECULAR BAND TRANSMISSION", C.D. ROGERS ; QJRMS, 94, 99-102
C         (1968).
C
C
C     INPUT VARIABLES
C
C     DTC3,  NOZ,  PL,  PL2,  TL,  TG,  TSA,    QL,  O3L,  CLD
C     CLU
C
C     OUTPUT VARIABLES
C
C     ATLX,  RS,   ULWTOP,  DLWBOT
C
C     PARAMETER LIST VARIABLES
C
C     NIM......NUMBER OF GRID POINTS AROUND A LATITUDE CIRCLE.
C     NLM......NUMBER OF MODEL LAYERS.
C     NLMP1....NLM PLUS ONE.
C     NNP......NLM PLUS TWO.
C     NLS......NUMBER OF LAYERS IN THE STRATOSPHERE.
C
C     LOCAL VARIABLES
C
C     B250.....PLANCK FUNCTION TABLE FOR WATER VAPOR BANDS; CENTER AND
C              WING.
C     NTM1.....NUMBER OF ROWS IN B250 - 1.
C     TEMP1....LOWEST TEMPERATURE FOR WHICH B250 IS TABULATED.
C     DTB......TEMPERATURE INCREMENT IN B250.
C     NUP1.....NUMBER OF COLUMNS IN GL AND COEFF.
C     UBAR.....SCALED WATER VAPOR PATH LENGTH IN WINDOW.
C     VBAR.....SCALED WATER VAPOR PATH LENGTH IN CENTER.
C     WBAR.....SCALED WATER VAPOR PATH LENGTH IN WING.
C     RAWI.....WATER VAPOR AMOUNT IN LAYER.
C     OZAI.....OZONE AMOUNT IN LAYER.
C     SHH......PLANCK FUNCTION AT LEVEL TEMPERATURE FOR WATER VAPOR
C              BANDS.
C     SHI......G-FUNCTION FOR A PATH FROM LEVEL TO TOP OF ATMOSPHERE.
C     TXUF.....1.USED AS MATRIX OF G-FUNCTIONS FOR PATHS FROM EACH LEVEL
C                TO ALL OTHER LAYERS.
C              2.USED FOR TRANSMISSION IN CO2 BAND.
C              3.USED FOR TRANSMISSION IN OZONE BAND.
C              4.IN LWCLDSLW USED FOR PROBABILITY OF CLEAR LINE-OF-SIGHT
C                FROM EACH LEVEL TO ALL OTHER LAYERS FOR MAX OVERLAP.
C     WV,WW....INTERPOLATED VALUE OF GL FOR BAND CENTER AND WING
C              RESPECTIVELY.
C     YV,YW....LINEAR TERM IN TEMPERATURE CORRECTION FOR BAND CENTER
C              AND WING RESPECTIVELY.
C     ZV,ZW....QUADRATIC TERM IN TEMPERATURE CORRECTION FOR BAND CENTER
C              AND WING RESPECTIVELY.
C     BLKCO2...PLANCK FUNCTION TABLE FOR CO2 BANDS.
C     BLKWIN...PLANCK FUNCTION TABLE FOR OZONE BAND.
C     CC.......PLANCK FUNCTION AT LEVEL TEMPERATURE FOR CO2 BANDS.
C     VBARM....PLANCK FUNCTION AT LEVEL TEMPERATURE FOR OZONE BAND.
C     PP.......DOPPLER BROADENING CUT-OFF.
C     PSCALV...SCALED CO2 AMOUNT IN BAND CENTER.
C     PSCALW...SCALED CO2 AMOUNT IN BAND WING.
C     DX.......PARAMETERIZED OPTICAL DEPTH OF WATER VAPOR LINE IN CO2
C              BAND WING.
C     DY.......PARAMETERIZED OPTICAL DEPTH OF WATER VAPOR CONTINUUM IN
C              CO2 BAND WING, ALSO USED FOR OZONE BAND WING.
C     SV,SW....MINIMUM IN TABLE OF LOG WATER VAPOR AMOUNT IN BAND CENTER
C              AND WING RESPECTIVELY.
C     CS.......PROBABILITY OF CLEAR LINE-OF-SIGHT FROM EACH LEVEL TO
C              ALL OTHER LAYERS.
C     CH.......PROBABILITY OF CLEAR LINE-OF-SIGHT FROM LEVEL TO TOP OF
C              THE ATMOSPHERE.
C     CC.......PROBABILITY OF CLEAR LINE-OF-SIGHT FROM LEVEL TO SURFACE.
C     CT.......PROBABILITY OF CLEAR LINE-OF-SIGHT FROM LEVEL TO TOP OF
C              ATMOSPHERE FOR MAXIMUN OVERLAP.
C     CU.......PROBABILITY OF CLEAR LINE-OF-SIGHT FROM LEVEL TO SURFACE
C              FOR MAXIMUM OVERLAP.
C
C
C*****************************************************************
C
C
      INCLUDE 'parmodel'
C
      PARAMETER (NIM= IIJRAD, NJM=46, NLM= IKM, NLS=02)
      PARAMETER (NNQFDS=5, NOFDS=2, NQIFDS=5, NOIFDS=8
     *,      NNQP3=21, NNQP2=59, N2DFDS=29, NEQO3O=01)
      PARAMETER (NIMP1=NIM+1,NIMP2=NIM+2,NIMP3=NIM+3,NIMD2=NIM/2+1/NIM
     *,     NLMM2=NLM-2, NLSP1=NLS+1, LMM1T2=(NLM-1)*2
     *,     IMD2P1=NIM/2+1, NJMM2=NJM-2, NLMP1=NLM+1, NLMM1=NLM-1
     *,     N1=NLM*NQIFDS+NOIFDS
     *,     N2=NLM*NNQFDS+NOFDS, N3=NIMP2*N2
     *,     NIMT2=NIM*2,N6=NIMP2*N1,NILPT=NIM*NLM
     *,     NNQPFD = NNQP3 + (NNQP2-1)/NLM + 1
     *,     NN5= NNQP3+ (NNQP2+(N2DFDS*NIM-1)/NIMP2)/NLM + 3
     *,     NN6 = NN5*NLM,NN1 = N1 - 1
     *,     N5= NIMP2*NN6, NTDSG =NLM-NLSP1
     *,     NNBITX=NIMP2*NLM
     *,     NPG=(NN1*NIMP2*NJMM2-1)/131072 + 1
     *,     N55=N5-2*NLM*NIMP2
     *,     NTL=(N55*NJMM2-1)/131072 + 1)
      PARAMETER (NNP=NLM+2, NNPP1=NNP+1, NNPBIT=NIM*NNPP1)
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:54:07  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C
      DIMENSION PL(NIM,NLM),PL2(NIM,NLMP1),TL(NIM,NLM),TG(NIM)
     *,QL(NIM,NLM),O3L(NIM,NLM),CLD(NIM,NLM)
     *,ATLX(NIM,NLM),RS(NIM),ULWTOP(NIM),DLWBOT(NIM),ULWBOT(NIM)
     *,CLU(NIM,NLM),TSA(NIM)
     *,ULTCLR(NIM),RSCLR(NIM)
CCC  *,CLU(NIM,NLM),TSA(NIM),CNVERT,DTC3,CON1,RONE,RZERO
C
      DIMENSION PRE(2)
C
      COMMON  TXUF(NIM,NNP,NNP),CS(NIM,NNP,NNP)
     *,X1(NIM,NNPP1),X2(NIM,NNPP1),TV1(NIM,NNPP1),DP(NIM,NNP)
     *,CSS(NIM,NNP),CCU(NIM,NNP),CH(NIM,NNP),WDEL(NIM,NLMP1)
     *,ZW(NIM,NLMP1),IT(NIM,NNPP1),X4(NIM,NNP),X3(NIM,NNP)
     *,CC(NIM,NNPP1),TV2(NIM,NNPP1),TUI2(NIM,NNPP1),SHI(NIM,NNP)
     *,RAWI(NIM,NNPP1),WV(NIM,NLMP1),YV(NIM,NLMP1),TUI(NIM,NNPP1)
     *,ZV(NIM,NLMP1),WW(NIM,NLMP1),YW(NIM,NLMP1),SHU(NIM,NLMP1)
     *,SHH(NIM,NNP),SUM(NIM),FU(NIM,NLMP1),FW(NIM,NLMP1)
     *,ADEL(NIM,NLMP1),BDEL(NIM,NLMP1),SUMSAV(NIM)
C
      DIMENSION PAI(NIM,NNP),FLUXU(NIM,NNP),UBAR(NIM,NNP),VBAR(NIM,NNP)
     *,WBAR(NIM,NNP),UBARM(NIM,NNP),OZAI(NIM,NNP),WBARM(NIM,NNP)
     *,TAI(NIM,NNP),FLUXD(NIM,NNP),VBARM(NIM,NNP)
C
      EQUIVALENCE (PAI(1,1)  ,CS(1,1,1)),    (FLUXU(1,1),CS(1,1,2))
     *,           (UBAR(1,1) ,CS(1,1,3)),    (VBAR(1,1) ,CS(1,1,4))
     *,           (WBAR(1,1) ,CS(1,1,5)),    (UBARM(1,1),CS(1,1,6))
     *,           (OZAI(1,1) ,CS(1,1,7)),    (WBARM(1,1),CS(1,1,8))
     *,           (TAI(1,1)  ,CS(1,1,9)),    (FLUXD(1,1),CS(1,1,10))
     *,           (VBARM(1,1),CS(1,1,11))
C
      COMMON /H2O/ NP,LM,IM,LMP1,LS,IMNP,IMLMP1,H1P,H0P,H1P5,HP5
     *,IMLM,IMNPNP,NPP1,IMNPP1,NTM1,DTB,DTBINV,PR(2),OZONE,DUM
C
      LOGICAL FIRST,NOZ,OZONE
C
      LOGICAL BITX(NNPBIT)
C
      DATA FIRST /.TRUE./
C
      DATA H1P02/1.02E0/, H6P08/6.0811E0/
C
C
      IF (FIRST) THEN
C
      FIRST=.FALSE.
C
C     COPY PARAMETERS INTO LOCAL VARIABLES
C
      IM     = NIM
      IMP2   = NIMP2
      LM     = NLM
      LMP1   = NLMP1
      NP     = NNP
      NPP1   = NNPP1
      LS     = NLS
      LS1    = NLS+1
      LS2    = NLS+2
      LS2P2  = LS2+2
      IMLS1  = NIM*LS1
      IMLSM1 = NIM*(LS-1)
      IMNP   = NIM*NNP
      IMNPP1 = NIM*NNPP1
      IMNPNP = NNP*IMNP
      IMLMP1 = NIM*NLMP1
      IMLM2  = NIM*(NLM-1)
C
      IMLM   = NIM*NLM
      IMT2   = 2*IM
      NPMLS2 = NIM*(NNP-LS2)
      LML2P2 = IM * (NP - LS2P2)
C
C     FAC CONVERTS TO DEGREES / TIME STEP
C
      FAC    = 9.8E-1 * DTC3 / (1.0030E04)
C
C     CNVERT INCLUDES STEFAN BOLTZMAN CONSTANT FOR CALCULATION OF DRB
C
      CNVERT = 1.171E-7*420.0/864.0
      RONE   = 1.0E0
      RZERO  = 0.0E0
      H1P    = 1.0E0
      H0P    = 0.0E0
      H1P5   = 1.5E0
      HP5    = 0.5E0
      H3PPM  = 3.0E-6
C
      NTM1   = 31
      DTB    = 5.0E0
      DTBINV = H1P / DTB
      PRE(1) = H1P / 2.75E02
      PRE(2) = H1P / 5.5E02
      D642   = H1P / 6.426E02
      PR(1)  = H1P / 3.0E01
      PR(2)  = H1P / 3.0E02
C
C     SET OZONE LOGICAL VARIABLE
C
      IF ( NOZ ) THEN
         OZONE = .FALSE.
      ELSE
         OZONE = .TRUE.
      END IF
C
      END IF
C
C     PTOP AND DP AT TOP DON'T CHANGE
C
CMIC$ PARALLEL SHARED(LM, LS, IM, QL, RAWI, H0P, HP5, DP, PL2, PAI)
CMIC$1    PRIVATE(L, IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 88890 IQ2W6E=1,IM
         DP(IQ2W6E,1)=H0P
         PAI(IQ2W6E,1)=PL2(IQ2W6E,1)
         DP(IQ2W6E,2)=PAI(IQ2W6E,1)
         PAI(IQ2W6E,1)=PAI(IQ2W6E,1)*HP5
88890 CONTINUE
C
CMIC$ DO PARALLEL
      DO 25 L=LS,LM
      DO 88930 IQ2W6E=1,IM
         RAWI(IQ2W6E,L+2)=QL(IQ2W6E,L)
88930 CONTINUE
   25 CONTINUE
CMIC$ END PARALLEL
      IF (LS .GT. 1)THEN
CMIC$ DO ALL VECTOR SHARED(IMLSM1, H3PPM, RAWI) PRIVATE(IQ2W6E)
      DO 88940 IQ2W6E=1,IMLSM1
         RAWI(IQ2W6E,3)=H3PPM
88940 CONTINUE
      END IF
CFPP$ NOCONCUR L
      DO 30 J=1,LM
CMIC$ DO ALL VECTOR SHARED(IM,J,PL,PAI,TL,TAI,PL2,X1)PRIVATE(IQ2W6E)
      DO 88950 IQ2W6E=1,IM
         PAI(IQ2W6E,J+1)=PL(IQ2W6E,J)
         TAI(IQ2W6E,J+2)=TL(IQ2W6E,J)
         X1(IQ2W6E,J+1)=PL2(IQ2W6E,J+1)
88950 CONTINUE
      IF (OZONE) THEN
CMIC$ DO ALL VECTOR SHARED(IM, J, O3L, OZAI) PRIVATE(IQ2W6E)
      DO 88980 IQ2W6E=1,IM
         OZAI(IQ2W6E,J+2)=O3L(IQ2W6E,J)
88980 CONTINUE
      END IF
   30 CONTINUE
C
CMIC$ PARALLEL SHARED(IM, LMP1, NP, X1, PAI, IMLM, RAWI, NPP1, TSA, TUI
CMIC$1   , TG, DP) PRIVATE(IQ2W6E, I)
CMIC$ DO PARALLEL VECTOR
      DO 88990 IQ2W6E=1,IM
         X1(IQ2W6E,1)=DP(IQ2W6E,2)
88990 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89000 IQ2W6E=1,IMLM
         DP(IQ2W6E,3)=X1(IQ2W6E,2)-X1(IQ2W6E,1)
89000 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89010 IQ2W6E=1,IM
         TUI(IQ2W6E,NP)=TSA(IQ2W6E)
         TUI(IQ2W6E,NPP1)=TG(IQ2W6E)
89010 CONTINUE
C
C     TEMPERATURE AND HUMIDITY INTERPOLATIONS
C
CMIC$ DO PARALLEL VECTOR
      DO 1001 I = 1, IMLM
         IF ( RAWI(I,3) .LT. 0.1E-22 ) RAWI(I,3)= 0.1E-22
1001  CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89040 IQ2W6E=1,IM
         PAI(IQ2W6E,NP)=X1(IQ2W6E,LMP1)
89040 CONTINUE
CMIC$ END PARALLEL
C
      IF (OZONE) THEN
CMIC$ PARALLEL SHARED(IMLM, H1P02, OZAI, DP, IM, H0P) PRIVATE(IQ2W6E, I)
CMIC$ DO PARALLEL VECTOR
      DO 1002 I = 1, IMLM
         IF ( OZAI(I,3) .LT. 0.1E-9 ) OZAI(I,3)= 0.1E-9
1002  CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89060 IQ2W6E=1,IM
         OZAI(IQ2W6E,1)=H0P
         OZAI(IQ2W6E,2)=OZAI(IQ2W6E,3)*DP(IQ2W6E,2)*H1P02
89060 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89080 IQ2W6E=1,IMLM
         OZAI(IQ2W6E,3)=OZAI(IQ2W6E,3)*DP(IQ2W6E,3)*H1P02
89080 CONTINUE
CMIC$ END PARALLEL
      END IF
   20 CONTINUE
C
C     DO TEMPERATURE INTERPOLATION
C
CMIC$ PARALLEL SHARED(IMLM2, TAI, X2, X4, TUI, IMLM, H1P02, RAWI, DP, X1
CMIC$1   , PAI, IM, H0P, H3PPM) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89090 IQ2W6E=1,IM
         RAWI(IQ2W6E,1)=H0P
         RAWI(IQ2W6E,2)=H3PPM*DP(IQ2W6E,2)*H1P02
89090 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89110 IQ2W6E = 1, IMLM
         RAWI(IQ2W6E,3) = RAWI(IQ2W6E,3)*DP(IQ2W6E,3)*H1P02
         X2(IQ2W6E,1) = ALOG(X1(IQ2W6E,2)/PAI(IQ2W6E,2))
         X4(IQ2W6E,1) = ALOG(PAI(IQ2W6E,3)/PAI(IQ2W6E,2))
89110 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89140 IQ2W6E=1,IMLM2
         TUI(IQ2W6E,3)=TAI(IQ2W6E,3)+X2(IQ2W6E,1)/X4(IQ2W6E,1)*(T
     *   AI(IQ2W6E,4)-TAI(IQ2W6E,3))
89140 CONTINUE
CMIC$ END PARALLEL
CCCC  TUI(1,LMP1;IM) = TBMN(1;IM)
C     DO 7621 KKK=1,LMP1
C             PRINT 7622 , KKK , TUI(1,KKK)
7621  CONTINUE
C7622 FORMAT(' KKK , TUI(1,KKK) =' , 2X , I5 , E15.5 )
C
CMIC$ PARALLEL SHARED(IMLMP1, D642, H6P08, RAWI, PAI, PRE, TAI, VBAR, 
CMIC$1   WBAR, DP, X2, IM, H0P, UBAR, IMT2, TUI) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89150 IQ2W6E=1,IM
         TAI(IQ2W6E,1)=TAI(IQ2W6E,3)
         TAI(IQ2W6E,2)=TAI(IQ2W6E,3)
89150 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89170 IQ2W6E=1,IMT2
         TUI(IQ2W6E,1)=TAI(IQ2W6E,1)
89170 CONTINUE
C
C     COMPUTE SCALED WATER VAPOR AMOUNTS
C
CMIC$ DO PARALLEL VECTOR
      DO 89180 IQ2W6E=1,IM
         UBAR(IQ2W6E,1)=H0P
         VBAR(IQ2W6E,1)=H0P
         WBAR(IQ2W6E,1)=H0P
89180 CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89210 IQ2W6E = 1, IMLMP1
         VBAR(IQ2W6E,2) = RAWI(IQ2W6E,2)*(PAI(IQ2W6E,1)*PRE(1))*EXP(
     1      0.5E-2*(TAI(IQ2W6E,2)-225.0E0))
         WBAR(IQ2W6E,2) = RAWI(IQ2W6E,2)*(PAI(IQ2W6E,1)*PRE(2))*EXP(
     1      1.6E-2*(TAI(IQ2W6E,2)-256.0E0))
         X2(IQ2W6E,1) = PAI(IQ2W6E,1)*D642*EXP(1.8E03/TAI(IQ2W6E,2)-
     1      H6P08)*RAWI(IQ2W6E,2)*RAWI(IQ2W6E,2)/DP(IQ2W6E,2)
89210 CONTINUE
CMIC$ END PARALLEL
CMIC$ PARALLEL SHARED(IM, UBAR, X2, VBAR, WBAR, NP) PRIVATE(IQ2W6E, IP)
      DO 80 IP=2,NP
CMIC$ DO PARALLEL VECTOR
      DO 89280 IQ2W6E=1,IM
         UBAR(IQ2W6E,IP)=UBAR(IQ2W6E,IP-1)+X2(IQ2W6E,IP-1)
         VBAR(IQ2W6E,IP)=VBAR(IQ2W6E,IP-1)+VBAR(IQ2W6E,IP)
         WBAR(IQ2W6E,IP)=WBAR(IQ2W6E,IP-1)+WBAR(IQ2W6E,IP)
89280 CONTINUE
   80 CONTINUE
CMIC$ END PARALLEL
C
CMIC$ DO ALL VECTOR SHARED(IMLMP1, HP5, UBAR, UBARM, VBAR, VBARM, WBAR, 
CMIC$1   WBARM) PRIVATE(IQ2W6E)
      DO 89310 IQ2W6E=1,IMLMP1
         UBARM(IQ2W6E,2)=(UBAR(IQ2W6E,2)+UBAR(IQ2W6E,1))*HP5
         VBARM(IQ2W6E,2)=(VBAR(IQ2W6E,2)+VBAR(IQ2W6E,1))*HP5
         WBARM(IQ2W6E,2)=(WBAR(IQ2W6E,2)+WBAR(IQ2W6E,1))*HP5
89310 CONTINUE
C
      CALL LWFLUX
C
C     COMPUTE CLEAR SKY FLUXES ONLY FOR CLOUD RADIATIVE FORCING
C
C     ZERO OUT DOWNWARD FLUX ACCUMULATORS AT L=1
C
CMIC$ DO ALL VECTOR SHARED(IM, H0P, NP, FLUXD, SUMSAV, FLUXU) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89340 IQ2W6E = 1, IM
         FLUXD(IQ2W6E,1) = H0P
         FLUXU(IQ2W6E,NP) = SUMSAV(IQ2W6E)
89340 CONTINUE
C
C     COMPUTE DOWNWARD FLUXES
C
      DO 100 IP=2,NP
C
CMIC$ DO ALL VECTOR SHARED(IM, H0P, SUM) PRIVATE(IQ2W6E)
      DO 89360 IQ2W6E=1,IM
         SUM(IQ2W6E)=H0P
89360 CONTINUE
C
      IPM1 = IP - 1
C
CMIC$ PARALLEL SHARED(IM, IP, SUM, TXUF, IPM1) PRIVATE(IQ2W6E, IX)
      DO 110 IX=1,IPM1
CMIC$ DO PARALLEL VECTOR
      DO 89370 IQ2W6E=1,IM
         SUM(IQ2W6E)=SUM(IQ2W6E)+TXUF(IQ2W6E,IX,IP)
89370 CONTINUE
  110 CONTINUE
CMIC$ END PARALLEL
C
CMIC$ DO ALL VECTOR SHARED(IM, IP, SUM, SHI, SHH, FLUXD) PRIVATE(IQ2W6E)
      DO 89380 IQ2W6E=1,IM
         FLUXD(IQ2W6E,IP)=SUM(IQ2W6E)-SHI(IQ2W6E,IP)+SHH(IQ2W6E,IP)
89380 CONTINUE
  100 CONTINUE
C
C     COMPUTE UPWARD FLUXES
C
      DO 120 IP=1,LMP1
C
      IPP1      = IP + 1
CMIC$ DO ALL VECTOR SHARED(IM, H0P, SUM) PRIVATE(IQ2W6E)
      DO 89390 IQ2W6E=1,IM
         SUM(IQ2W6E)=H0P
89390 CONTINUE
C
CMIC$ PARALLEL SHARED(IM, IP, SUM, TXUF, NP, IPP1) PRIVATE(IQ2W6E, IX)
      DO 130 IX=IPP1,NP
CMIC$ DO PARALLEL VECTOR
      DO 89400 IQ2W6E=1,IM
         SUM(IQ2W6E)=SUM(IQ2W6E)+TXUF(IQ2W6E,IX,IP)
89400 CONTINUE
  130 CONTINUE
CMIC$ END PARALLEL
C
CMIC$ DO ALL VECTOR SHARED(IM, IP, SUM, SHU, SHH, FLUXU) PRIVATE(IQ2W6E)
      DO 89410 IQ2W6E=1,IM
         FLUXU(IQ2W6E,IP)=SUM(IQ2W6E)+SHU(IQ2W6E,IP)+SHH(IQ2W6E,IP)
89410 CONTINUE
C
  120 CONTINUE
C
C
CMIC$ PARALLEL SHARED(NPMLS2, LS2, H1P, TV1, TV2, CSS, LMP1, IM, TL, DP
CMIC$1   , CCU, LM, LS1, CLD, CLU, IMLS1, H0P, NP, X1, ULTCLR, RSCLR, 
CMIC$2   IMNP, FLUXD, FLUXU) PRIVATE(IQ2W6E, L)
CMIC$ DO PARALLEL VECTOR
      DO 89420 IQ2W6E=1,IMNP
         X1(IQ2W6E,1)=FLUXD(IQ2W6E,1)-FLUXU(IQ2W6E,1)
89420 CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89430 IQ2W6E=1,IM
         ULTCLR(IQ2W6E)=-X1(IQ2W6E,2)
         RSCLR(IQ2W6E)=-X1(IQ2W6E,NP)
89430 CONTINUE
C
C
C     WE DON'T ALLOW CLOUDS BETWEEN GCM LEVELS IN THE STRATOSPHERE
C
CMIC$ DO PARALLEL VECTOR
      DO 89450 IQ2W6E=1,IMLS1
         CSS(IQ2W6E,1)=H0P
         CCU(IQ2W6E,1)=H0P
89450 CONTINUE
C
CMIC$ DO PARALLEL
      DO 35 L=LS1,LM
      DO 89470 IQ2W6E=1,IM
         CSS(IQ2W6E,L+1)=CLD(IQ2W6E,L)
         CCU(IQ2W6E,L+1)=CLU(IQ2W6E,L)
89470 CONTINUE
   35 CONTINUE
C
C     FOR WATER AND CUMULUS ANVILS EMISSIVITY IS 1 - EXP(-.05*DP)
C     FOR ICE EMISSIVITY IS 1 - EXP(-.01*DP) *** CHANGED HERE ***
C
CMIC$ DO PARALLEL VECTOR
      DO 89490 IQ2W6E = 1, NPMLS2
         TV1(IQ2W6E,LS2) = -.05E0*DP(IQ2W6E,LS2+1)
         TV2(IQ2W6E,LS2) = EXP(TV1(IQ2W6E,LS2))
         CCU(IQ2W6E,LS2) = CCU(IQ2W6E,LS2)*(H1P-TV2(IQ2W6E,LS2))
89490 CONTINUE
C
CMIC$ DO PARALLEL
      DO 40 L=LS2,LMP1
      DO 89510 IQ2W6E=1,IM
         IF(TL(IQ2W6E,L-1).LT.253.0)  THEN
            TV1(IQ2W6E,L)=-.01E0*DP(IQ2W6E,L+1)
         END IF
89510 CONTINUE
   40 CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89520 IQ2W6E=1,NPMLS2
         TV2(IQ2W6E,LS2) = EXP(TV1(IQ2W6E,LS2))
         CSS(IQ2W6E,LS2)=CSS(IQ2W6E,LS2)*(H1P-TV2(IQ2W6E,LS2))
89520 CONTINUE
CMIC$ END PARALLEL
C
C     GET THE CONTRIBUTION FROM CLOUDINESS
C
      CALL LWCLDSLW
C
CMIC$ PARALLEL SHARED(IM, H0P, NP, FLUXD, SUMSAV, FLUXU, IMLMP1, SHU, CC
CMIC$1   , SHH, IMNP, SHI, CH, IMNPNP, TXUF, CS) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89530 IQ2W6E=1,IMNPNP
         TXUF(IQ2W6E,1,1)=TXUF(IQ2W6E,1,1)*CS(IQ2W6E,1,1)
89530 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89540 IQ2W6E=1,IMNP
         SHI(IQ2W6E,1)=SHI(IQ2W6E,1)*CH(IQ2W6E,1)
89540 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89550 IQ2W6E=1,IMLMP1
         SHU(IQ2W6E,1)=SHU(IQ2W6E,1)*CC(IQ2W6E,1) + SHH(IQ2W6E,1)
89550 CONTINUE
C
C     ZERO OUT DOWNWARD FLUX ACCUMULATORS AT L=1
C
CMIC$ DO PARALLEL VECTOR
      DO 89570 IQ2W6E = 1, IM
         FLUXD(IQ2W6E,1) = H0P
         FLUXU(IQ2W6E,NP) = SUMSAV(IQ2W6E)
89570 CONTINUE
CMIC$ END PARALLEL
C
C     UPWARD FLUX AT THE SURFACE WAS COMPUTED BEFORE CALL TO LWCLDSLW
C
C     COMPUTE DOWNWARD FLUXES
C
      DO 300 IP=2,NP
C
CMIC$ DO ALL VECTOR SHARED(IM, H0P, SUM) PRIVATE(IQ2W6E)
      DO 89590 IQ2W6E=1,IM
         SUM(IQ2W6E)=H0P
89590 CONTINUE
C
      IPM1 = IP - 1
C
CMIC$ PARALLEL SHARED(IM, IP, SUM, TXUF, IPM1) PRIVATE(IQ2W6E, IX)
      DO 310 IX=1,IPM1
CMIC$ DO PARALLEL VECTOR
      DO 89600 IQ2W6E=1,IM
         SUM(IQ2W6E)=SUM(IQ2W6E)+TXUF(IQ2W6E,IX,IP)
89600 CONTINUE
  310 CONTINUE
CMIC$ END PARALLEL
C
CMIC$ DO ALL VECTOR SHARED(IM, IP, SUM, SHI, SHH, FLUXD) PRIVATE(IQ2W6E)
      DO 89610 IQ2W6E=1,IM
         FLUXD(IQ2W6E,IP)=SUM(IQ2W6E)-SHI(IQ2W6E,IP)+SHH(IQ2W6E,IP)
89610 CONTINUE
  300 CONTINUE
C
C     COMPUTE UPWARD FLUXES
C
      DO 320 IP=1,LMP1
C
      IPP1      = IP + 1
CMIC$ DO ALL VECTOR SHARED(IM, H0P, SUM) PRIVATE(IQ2W6E)
      DO 89620 IQ2W6E=1,IM
         SUM(IQ2W6E)=H0P
89620 CONTINUE
C
CMIC$ PARALLEL SHARED(IM, IP, SUM, TXUF, NP, IPP1) PRIVATE(IQ2W6E, IX)
      DO 330 IX=IPP1,NP
CMIC$ DO PARALLEL VECTOR
      DO 89630 IQ2W6E=1,IM
         SUM(IQ2W6E)=SUM(IQ2W6E)+TXUF(IQ2W6E,IX,IP)
89630 CONTINUE
  330 CONTINUE
CMIC$ END PARALLEL
C
CMIC$ DO ALL VECTOR SHARED(IM, IP, SUM, SHU, FLUXU) PRIVATE(IQ2W6E)
      DO 89640 IQ2W6E=1,IM
         FLUXU(IQ2W6E,IP)=SUM(IQ2W6E)+SHU(IQ2W6E,IP)
89640 CONTINUE
C
  320 CONTINUE
C
C
CMIC$ PARALLEL SHARED(LM, IM, X2, ATLX, IMLM, FAC, X1, DP, NP, ULWTOP, 
CMIC$1   FLUXD, DLWBOT, FLUXU, ULWBOT, RS, IMNP) PRIVATE(L, IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89650 IQ2W6E=1,IMNP
         X1(IQ2W6E,1)=FLUXD(IQ2W6E,1)-FLUXU(IQ2W6E,1)
89650 CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89660 IQ2W6E=1,IM
         ULWTOP(IQ2W6E)=-X1(IQ2W6E,2)
         DLWBOT(IQ2W6E)=FLUXD(IQ2W6E,NP)
         ULWBOT(IQ2W6E)=FLUXU(IQ2W6E,NP)
         RS(IQ2W6E)=-X1(IQ2W6E,NP)
89660 CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89700 IQ2W6E=1,IMLM
         X2(IQ2W6E,1)=(X1(IQ2W6E,2)-X1(IQ2W6E,3))*FAC/DP(IQ2W6E,3)
89700 CONTINUE
CMIC$ DO PARALLEL
      DO 190 L=1,LM
      DO 89710 IQ2W6E=1,IM
         ATLX(IQ2W6E,L)=X2(IQ2W6E,L)
89710 CONTINUE
  190 CONTINUE
CMIC$ END PARALLEL
C
C
      RETURN
      END
