      SUBROUTINE OUTABVOR ( NU, NV, NCARD )
C$$$  SUBPROGRAM DOCUMENTATION  BLOCK
C
C SUBPROGRAM:    OUTABVOR    COMPUTE THE ABSOLUTE VORTICITY
C   PRGMMR: N. PHILLIPS      ORG: W/NMC22    DATE: 84-08-05
C
C ABSTRACT:   AFTER DETERMINING THAT THIS PRODUCT IS WANTED BY THE
C   OUTPUT DATA CARDS, THIS CODE USES INPUT VALUES OF U AND V TO
C   COMPUTE, FOR EACH OUTPUT PRESSURE LEVEL THAT IS DESIRED,
C   THE  ABSOLUTE VORTICITY.  SECOND-ORDER CENTERED DIFFERENCES
C   ARE USED.  ON THE LATERAL BOUNDARIES, THE RELATIVE VORTICITY
C   IS SET TO ZERO.
C   .
C   3-DIMENSIONAL ARRAYS OF U AND V ON THE OUTPUT GRID MUST BE
C   AVAILABLE IN THE ARRAYS S(JSCR3OUT(NU)) AND S(JSCR3OUT(NV)).
C
C PROGRAM HISTORY LOG:
C   84-08-05  N PHILLIPS
C   88-08-26  B SCHMIDT REVISED THE DOCBLOCK
C
C USAGE:    CALL OUTABVOR(NU,NV,NCARD)
C   INPUT ARGUMENT LIST:
C     NU       - INDICE OF ARRAY 'JSCR3OUT' THAT IN TURN POINTS TO
C                THE U VELOCITY IN ARRAY 'S'
C     NV       - INDICE OF ARRAY 'JSCR3OUT' THAT IN TURN POINTS TO
C                THE V VELOCITY IN ARRAY 'S'
C     NCARD    - NUMBER OF THE DATA CARD FOR ABSOLUTE VORTICITY
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - OUTNULAB
C                  OUTPACK
C     LIBRARY:
C       COMMON   - COMBLANK
C                  COMCONST
C                  COMOUT
C
C REMARKS:
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES         MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----         ----------------------------------        ---------
C   U             GRID-ORIENTED U VELOCITY                   COMMON
C   .             IN ARRAY  S(JSCR3OUT(NU) ).
C   .
C   V             DITTO FOR V IN ARRAY S(JSCR3OUT(NV) )      COMMON
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES         MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----         ----------------------------------        ---------
C   .
C   ABSOLUTE VORTICITY    SECONDS **(-1)                     SUBROUTINE
C   .                                                        OUTPACK
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:13:20  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
C
C
C          REFERENCE SCRATCH ARRAY
      DIMENSION S(INSUMG)
      EQUIVALENCE (SCR(1,1), S(1) )
C
      DATA LABABSV/72/, LABPRES/8/
C
C          IS THIS REALLY NECESSARY?
C
      NWANT = 0
      DO 4772 IQ2 = 1, LMOUT
         NWANT = NWANT + LEVELS(IQ2,NCARD)
4772  CONTINUE
      IF( NWANT .EQ. 0 ) RETURN
C
C          SCRATCH ADDRESSES AND DESCRIPTORS
      I1=JSCR2(1)
      I2=JSCR2(2)
      I3=JSCR2(3)
      I4=JSCR2(4)
      I5=JSCR2(5)
C
C          PUT SCALE FACTOR INTO S(I1)
      C1=1.E0-XIPOUT
CMIC$ DO ALL VECTOR SHARED(IMOUT, C1, I1, S) PRIVATE(IQ2)
      DO 4883 IQ2 = 1, IMOUT
         S(I1+IQ2-1) = C1 + FLOAT(IQ2-1)
4883  CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I1-I2).GE.IMOUT .OR. I1-I2.EQ.0) SHARED(
CMIC$1   IMOUT, I1, I2, S) PRIVATE(IQ2W6E)
      DO 88890 IQ2W6E=1,IMOUT
         S(I2+IQ2W6E-1)=S(I1+IQ2W6E-1)*S(I1+IQ2W6E-1)
88890 CONTINUE
      C1=-YJPOUT
      IAD=I1-IMOUT
      DO 30 J=1,JMOUT
      IAD=IAD+IMOUT
      C1=C1+1.E0
      C2=C1*C1
CMIC$ DO ALL VECTOR IF (ABS(I2-IAD).GE.IMOUT .OR. I2-IAD.EQ.0) SHARED(
CMIC$1   IMOUT, C2, I2, IAD, S) PRIVATE(IQ2W6E)
      DO 88900 IQ2W6E=1,IMOUT
         S(IAD+IQ2W6E-1)=C2+S(I2+IQ2W6E-1)
88900 CONTINUE
   30 CONTINUE
      C1=1.E0/(DNPEQOUT * DNPEQOUT )
CMIC$ DO ALL VECTOR IF (ABS(I1-I2).GE.IJOUT .OR. I1-I2.EQ.0) SHARED(
CMIC$1   IJOUT, C1, I1, I2, S) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E=1,IJOUT
         S(I2+IQ2W6E-1)=C1*S(I1+IQ2W6E-1)
88910 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I2-I1).GE.IJOUT .OR. I2-I1.EQ.0) SHARED(
CMIC$1   IJOUT, I2, I1, S) PRIVATE(IQ2W6E)
      DO 88920 IQ2W6E=1,IJOUT
         S(I1+IQ2W6E-1)=1.E0+S(I2+IQ2W6E-1)
88920 CONTINUE
C          1 / SCALE FACTOR INTO S(I2)
CMIC$ DO ALL VECTOR IF (ABS(I1-I2).GE.IJOUT .OR. I1-I2.EQ.0) SHARED(
CMIC$1   IJOUT, I1, I2, S) PRIVATE(IQ2W6E)
      DO 88930 IQ2W6E=1,IJOUT
         S(I2+IQ2W6E-1)=1.E0/S(I1+IQ2W6E-1)
88930 CONTINUE
C          CORIOLIS PARAMETER INTO S(I3)
      TWOOMEGA = 2.E0 * 7.292116E-5
      C1=2.E0 * TWOOMEGA
CMIC$ DO ALL VECTOR IF (ABS(I2-I3).GE.IJOUT .OR. I2-I3.EQ.0) SHARED(
CMIC$1   IJOUT, C1, I2, I3, S) PRIVATE(IQ2W6E)
      DO 88940 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=C1*S(I2+IQ2W6E-1)
88940 CONTINUE
CMIC$ PARALLEL SHARED(IMOUT, I1, S, IJOUT, I3, TWOOMEGA) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 88950 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=S(I3+IQ2W6E-1)-TWOOMEGA
88950 CONTINUE
C          REPLACE SCALE FACTOR BY ITS SQUARE
CMIC$ DO PARALLEL VECTOR
      DO 88960 IQ2W6E=1,IJOUT
         S(I1+IQ2W6E-1)=S(I1+IQ2W6E-1)*S(I1+IQ2W6E-1)
88960 CONTINUE
C          MAKE THIS ZERO ON THE BOUNDARIES TO ZERO OUT
C          INCORRECT VORTICITY VALUES THERE.
CMIC$ DO PARALLEL VECTOR
      DO 88970 IQ2W6E=1,IMOUT
         S(I1+IQ2W6E-1)=0.E0
88970 CONTINUE
CMIC$ END PARALLEL
      IAD = I1 + IJOUT - IMOUT
CMIC$ DO ALL VECTOR SHARED(IMOUT, IAD, S) PRIVATE(IQ2W6E)
      DO 88980 IQ2W6E=1,IMOUT
         S(IAD+IQ2W6E-1)=0.E0
88980 CONTINUE
      IAD = I1 + IMOUT
      JLIMIT = JMOUT - 1
CMIC$ DO ALL VECTOR IF (ABS(1-IMOUT).GE.(JLIMIT-1)*ABS(IMOUT) .OR. 1-
CMIC$1   IMOUT.EQ.0) SHARED(JLIMIT, IAD, IMOUT, S) PRIVATE(J)
      DO 40 J = 1, JLIMIT - 1
         S(IAD+(J-1)*IMOUT) = 0.E0
         S(IAD-1+J*IMOUT) = 0.E0
   40 CONTINUE
C
C          1 / TWICE THE OUTPUT GRID SPACING
      CDEL = DNPEQOUT / (4.E0 * 6.371E6 )
C
C          FIND THE LEVELS THAT ARE WANTED
      DO 100 L=1,LMOUT
      IF( LEVELS(L,NCARD) .EQ. 0 ) GO TO 100
C          THE U AND V ADDRESSES
      IADU = JSCR3OUT(NU) + (L-1)*IJOUT
      IADV = JSCR3OUT(NV) + (L-1)*IJOUT
C               U / SCALE FACTOR
CMIC$ DO ALL VECTOR IF ((ABS(IADU-I4).GE.IJOUT .OR. IADU-I4.EQ.0) .AND. 
CMIC$1   (ABS(I2-I4).GE.IJOUT .OR. I2-I4.EQ.0)) SHARED(IJOUT, IADU, I2, 
CMIC$2   I4, S) PRIVATE(IQ2W6E)
      DO 88990 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=S(IADU+IQ2W6E-1)*S(I2+IQ2W6E-1)
88990 CONTINUE
C          MINUS J-DIFFERENCE / TWICE GRID INCREMENT
      IAD1 = I4 + IMOUT
      IAD2 = I4 - IMOUT
CMIC$ DO ALL VECTOR IF ((ABS(IAD2-I5).GE.IJOUT .OR. IAD2-I5.EQ.0) .AND. 
CMIC$1   (ABS(IAD1-I5).GE.IJOUT .OR. IAD1-I5.EQ.0)) SHARED(IJOUT, CDEL, 
CMIC$2   IAD2, IAD1, I5, S) PRIVATE(IQ2W6E)
      DO 89000 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=CDEL*(S(IAD2+IQ2W6E-1)-S(IAD1+IQ2W6E-1))
89000 CONTINUE
C          ADD THE CORRESPONDING I-DIFFERENCE OF V/SCALE FACTOR
CMIC$ DO ALL VECTOR IF ((ABS(IADV-I4).GE.IJOUT .OR. IADV-I4.EQ.0) .AND. 
CMIC$1   (ABS(I2-I4).GE.IJOUT .OR. I2-I4.EQ.0)) SHARED(IJOUT, IADV, I2, 
CMIC$2   I4, S) PRIVATE(IQ2W6E)
      DO 89010 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=S(IADV+IQ2W6E-1)*S(I2+IQ2W6E-1)
89010 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I5-1-I4).GE.IJOUT .OR. I5-1-I4.EQ.0) SHARED(
CMIC$1   IJOUT, I5, CDEL, I4, S) PRIVATE(IQ2W6E)
      DO 89020 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=S(I5+IQ2W6E-1)+CDEL*S(I4+IQ2W6E)
89020 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I5+1-I4).GE.IJOUT .OR. I5+1-I4.EQ.0) SHARED(
CMIC$1   IJOUT, I5, CDEL, I4, S) PRIVATE(IQ2W6E)
      DO 89030 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=S(I5+IQ2W6E-1)-CDEL*S(I4+IQ2W6E-2)
89030 CONTINUE
C           MULTIPLY BY SQUARE OF SCALE FACTOR( ZERO ON BNDRYS)
CMIC$ DO ALL VECTOR IF (ABS(I5-I1).GE.IJOUT .OR. I5-I1.EQ.0) SHARED(
CMIC$1   IJOUT, I5, I1, S) PRIVATE(IQ2W6E)
      DO 89040 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=S(I5+IQ2W6E-1)*S(I1+IQ2W6E-1)
89040 CONTINUE
C           ADD CORIOLIS TERM
CMIC$ DO ALL VECTOR IF (ABS(I5-I3).GE.IJOUT .OR. I5-I3.EQ.0) SHARED(
CMIC$1   IJOUT, I5, I3, S) PRIVATE(IQ2W6E)
      DO 89050 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=S(I5+IQ2W6E-1)+S(I3+IQ2W6E-1)
89050 CONTINUE
C
C          PREPARE FOR OUTPUT
      S1VALUE = ANINT( 1000.E0 * PLOUT(L) )
      LABQTYPE = LABABSV
      LABSSUB1 = LABPRES
C              UPDATE THE LABEL84 TABLE
      CALL OUTNULAB
C              SEND IT AWAY
      CALL OUTPACK(S(I5),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
     1    LABEL84, IOUTUNIT )
      CALL GRIBIT (S(I5),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
     1    LABEL84, IOUTGRIB )
C
C
C         THE END OF THE LEVEL LOOP
  100 CONTINUE
C
      RETURN
      END
