      SUBROUTINE OUTFIXED (CENYEAR0, AMONTH0, DAY0, GMT0,
     1                     IRUNMARK, LABEL84)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    OUTFIXED    SETS UP O.N. 84 LABEL
C   PRGMMR: JIM HOKE         ORG: W/NMC22    DATE: 85-03-25
C
C ABSTRACT: SETS UP THE COMPONENTS OF THE OFFICE
C   NOTE 84 LABEL THAT ARE THE SAME FOR ALL FIELDS
C   ON ALL THE OUTPUT DISK FILES FOR THIS FORECAST.
C
C PROGRAM HISTORY LOG:
C   85-03-25  JIM HOKE
C   88-08-26  BRIAN SCHMIDT ADDED THE DOCBLOCK
C
C USAGE:    CALL OUTFIXED (CENYEAR0, AMONTH0, DAY0, GMT0,
C                          IRUNMARK, LABEL84)
C   INPUT ARGUMENT LIST:
C     CENYEAR0 - YEAR OF THE INITIAL MODEL TIME
C     AMONTH0  - MONTH OF THE INITIAL MODEL TIME
C     DAY0     - DAY OF THE INITIAL MODEL TIME
C     GMT0     - GMT HOUR OF THE INITAIL MODEL TIME
C     IRUNMARK - RUN MARKER FOR O.N. 84 LABEL
C
C   OUTPUT ARGUMENT LIST:
C     LABEL84  - O.N. 84 LABEL FOR THE MODEL RUN
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      DIMENSION LABEL84(27)
C
C              SPECIFY THE EXCEPTION MARKER X (TABLE 4).
      LABEL84(8) = 0
C
C              SPECIFY THE MISCELLANEOUS MARKER N (TABLE 5).
      LABEL84(11) = 0
C
C              SPECIFY THE CLIMATE MARKERS CD AND CM (TABLE 6).
      LABEL84(14) = 0
      LABEL84(15) = 0
C
C              SPECIFY THE DERIVATION MARKER KS (TABLE 8) INDICATING
C              THAT THE FIELD IS NOT EXPRESSED IN A DEVIATION FROM
C              A CLIMATOLOGICAL NORM.
      LABEL84(16) = 0
C
C              SPECIFY THE GUESS FLAG.
      LABEL84(18) = 0
C
C              INITIALIZE LOCATIONS RN AND NW FOR INTERNAL USE
C              BY THE I/O ROUTINES ONLY.
      LABEL84(19) = 0
      LABEL84(20) = 0
C
C              SPECIFY THE YEAR OF THE CENTURY, THE MONTH, THE DAY OF
C              THE MONTH, AND THE GMT ALL OF THE INITIAL TIME.
      LABEL84(21) = NINT (CENYEAR0)
      LABEL84(22) = NINT (AMONTH0)
      LABEL84(23) = NINT (DAY0)
      LABEL84(24) = NINT (GMT0)
C
C              SPECIFY THE RUN MARKER (TABLE 9).
      LABEL84(25) = IRUNMARK
C
C              SPECIFY THE GENERATING PROGRAM (TABLE 10).
C              THE NGM IS INDICATED BY A DECIMAL 39.
      LABEL84(26) = 39
C
      RETURN
      END
