      SUBROUTINE OUTGRWD
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    OUTGRWD     OUTPUT GRAVITY WAVE STRESSES AND ST DEV
C   PRGMMR: N. PHILLIPS      ORG: W/NMC22    DATE: 88-02-04
C
C ABSTRACT: OUTPUT FIELDS OF
C   .       1) GROUND STANDARD DEVIATION
C   .       2) X COMPONENT OF GRAVITY
C   .          WAVE STRESS AT THE GROUND
C   .       3) Y COMPONENT OF GRAVITY
C   .          WAVE STRESS AT THE GROUND
C   .
C PROGRAM HISTORY LOG:
C   88-02-04  N PHILLIPS
C   88-08-25  B SCHMIDT REVISED THE DOCBLOCK
C
C USAGE: CALL OUTGRWD
C   SUBPROGRAMS CALLED:
C      UNIQUE:   - OUTHORIZ
C                  OUTNULAB
C                  OUTPACK
C      LIBRARY:
C        COMMON  - COMBLANK
C                  COMCONST
C                  COMOUT
C
C REMARKS:
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   S             SCRATCH ARRAY                              COMMON
C   .
C   SD,GRX,       STD DEV OF GRND HEIGHT, X AND Y COMPONENTS COMMON
C   GRY           OF GRAVITY WAVE DRAG
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   .
C   SD            STD DEV OF GRND HEIGHT (METERS)         SUBROUTINE
C   .                                                         OUTPACK
C   GRX           X-COMPONENT OF GRAVITY WAVE DRAG        SUBROUTINE
C   .             AT THE GROUND ( TON/METER SEC**2)       OUTPACK
C   GRY           Y-COMPONENT OF GRAVITY WAVE DRAG        SUBROUTINE
C   .             AT THE GROUND ( TON/METER SEC**2)       OUTPACK
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:46:38  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
CER
      INTEGER IDGRBE(25)
C
      COMMON/ADDRS/MIILL,MIIUL,MSA,MSB,MSC,MSD
C
      DIMENSION S(INSUMG),LABGW(3),MARVBL(3),IN(INSUMG)
      EQUIVALENCE( SCR(1,1), S(1), IN(1) )
C              QTYPES IN LABGW AND ARRAY NUMBERS IN VBL
      DATA LABGW/218,86,87/, MARVBL/42,43,44/
C
C         OUTER LOOP IS ON THE THREE VARIABLES
C
C         OUTER LOOP IS ON THE THREE VARIABLES
      DO 100 NLOOP = 1,3
C          SET UP THE LABEL AND THE ARRAY NUMBER IN VBL
      LABX = LABGW(NLOOP)
      MARRAY = MARVBL(NLOOP)
C          SEARCH FOR OUTPUT CARD
        DO 1 N=1,NOUTVBLS
        NCARD=N
        IF(LQTYPE(N).EQ.LABX) GO TO 2
    1   CONTINUE
C          NO DATA CARD FOR THIS VARIABLE
      GO TO 100
C           IS THE FLAG TURNED ON??
    2 IF(LEVELS(1,NCARD).NE.1) GO TO 100
C         THIS VARIABLE IS WANTED, GET IT FROM THE FORECAST GRIDS
C
        DO 50 NN=1,NUMGDREQ
        NG = NGRIDATA(NN)
        IM = IMG(NG)
        JM = JMG(NG)
        IJ = IM * JM
C
C        ADDRESS FOR INPUT FIELD FOR HORIZONTAL INTERPOLATION
         IADF = JADDFNGM(NG)
C            ADDRESS FOR VARIABLE IN ARRAY VBL
        IADV = IADDRG(MARRAY,NG)
C            PUT INTO ARRAY FNGM FOR HORIZONTAL INTERPOLATION
C            MUST CHANGE DRAG VALUES INTO NEWTONS PER SQ METER
        IF(NLOOP .EQ. 1 )THEN
CMIC$ DO ALL VECTOR SHARED(IJ, IADV, IADF, VBL, S) PRIVATE(IQ2W6E)
      DO 88890 IQ2W6E=1,IJ
         S(IADF+IQ2W6E-1)=VBL(IADV+IQ2W6E-1)
88890 CONTINUE
      END IF
        SCALE = 1000.E0
        IF(NLOOP .GT. 1 )THEN
CMIC$ DO ALL VECTOR SHARED(IJ,SCALE,IADV,IADF,VBL,S)PRIVATE(IQ2W6E)
      DO 88900 IQ2W6E=1,IJ
         S(IADF+IQ2W6E-1)=SCALE*VBL(IADV+IQ2W6E-1)
88900 CONTINUE
      END IF
C
C            END OF DO-LOOP ON THE REQUIRED GRIDS
   50   CONTINUE
C
C            INTERPOLATE TO OUTPUT GRID
      CALL OUTHORIZ(IN(MIILL),IN(MIIUL),S(MSA),S(MSB),S(MSC),
     *              S(MSD),S(MSOUT1),S(MSOUT2))
C
      LABQTYPE = LABX
C          VARIABLE IS ON THE GROUND SURFACE
      LABSSUB1 = 129
      S1VALUE = 0.E0
C
             CALL OUTNULAB
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IF(NLOOP.EQ.1) IDGRBE(8) = 9
      IF(NLOOP.EQ.2) IDGRBE(8) = 147
      IF(NLOOP.EQ.3) IDGRBE(8) = 148
      IDGRBE(9) =   1
      IDGRBE(10) =  0
      IDGRBE(11) =  0
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0

c            CALL OUTPACK(S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
c    1         LABEL84, IOUTUNIT )
             CALL GRIBITN (S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
     1         IDGRBE,IOUTGRIB,LABEL84 )
C
  100 CONTINUE
C
      RETURN
      END
