      SUBROUTINE OUTHYDRO( NCARDH, NCARD, NCARDA )
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    OUTHYDRO    COMPUTE SLP, AND HGTS ON P AND SIGMA
C   PRGMMR: N PHILLIPS       ORG: W/NMC22    DATE: 84-02-01
C
C PROGRAM HISTORY LOG:
C   84-02-01  N PHILLIPS
C   85-05-15  N PHILLIPS ADDED SEA LEVEL PRESSURE ADJUSTMENT
C   85-07-01  N PHILLIPS CORRECTED SHUELL METHOD
C   88=08-25  B SCHMIDT REVISED THE DOCBLOCK
C
C ABSTRACT: THE FUNDAMENTAL HYDROSTATIC EQUATION IS
C   .
C   .    D(HEIGHT)
C   .    ---------  =  TAU = VIRTUAL TEMPERATURE * (RGAS/GRAVITY)
C   .    D (Z)
C   .
C   AND  Z IS EQUAL TO MINUS LOG OF PRESSURE.
C   .
C   SEA-LEVEL PRESSURE IS COMPUTED FROM THE FORMULA
C   .
C   PRESS(MSL) = PRESS(GROUND) * EXP( F)
C   .
C   WHERE      F = HEIGHT OF GROUND / MEAN TAU
C   .
C   AND  MEAN TAU = ( TAU(GRND) + TAU(SL) ) / 2
C   .
C   TAU(GRND) AND TAU(SL) ARE FIRST SET BY THE 6.5DEG/KM LAPSE
C   RATE FROM SIGMA LEVEL K=1, BUT THIS IS MODIFIED BY THE
C   CORRECTION BASED ON THE CRITICAL TAU OF THE SHUELL CORRECTION:
C   .
C   .               TAUCR=(RGASD/GRAVITY) * 290.66
C   .
C   1) WHERE ONLY TAU(SL) EXCEEDS TAUCR, CHANGE TAU(SL) TO TAUCR.
C   .
C   2) WHERE BOTH TAU(SL) AND TAU(GRND) EXCEED TAUCR,
C   .    CHANGE TAU(SL) TO TAUCR-CONST*(TAU(GRND)-TAUCR  )**2
C   .    WHERE CONST = .005 (GRAVITY/RGASD)
C   .
C   .   THE AVERAGE OF TAU(SL) AND TAU(GRND) IS THEN USED TOGETHER
C   WITH THE GROUND HEIGHT AND PRESSURE TO DERIVE THE PRESSURE
C   AT SEA LEVEL.
C   .   TWO TYPES OF SEA LEVEL PRESSURE CAN BE ASKED FOR BY AN
C   OUTPUT MENU CARD-- EITHER THE VALUE JUST COMPUTED ( IN WHICH CASE
C   NCARD WILL BE GREATER THAN ZERO) OR THAT VALUE 'CORRECTED' BY
C   ADDING THE DIFFERENCE BETWEEN AN ANALYSIS OF SEA LEVEL PRESSURE
C   OBSERVATIONS AT T=0 AND THE VALUE OF THE ABOVE PRESSURE FIELD
C   AT T=0( IN WHICH CASE NCARDA WILL BE GREATER THAN ZERO).
C   .   IT IS ASSUMED THAT ONLY ONE OF THESE TWO SEA LEVEL PRESSURE
C   FIELDS IS ASKED FOR ON A SINGLE CALL TO   OUTPUT  .
C   .    HEIGHT OF THE 1000-MB SURFACE IS THEN COMPUTED FROM THE
C   MSL PRESSURE FIELD USING THE FORMULA:
C   .
C   .    P(MSL) - P(1000MBS) = MEAN DENSITY * GRAVITY * HGT(1000MBS).
C   .
C   WHERE P(MSL) IS THE FIELD THAT HAS JUST BEEN CHOSEN.
C   .
C   . THE HEIGHT OF ALL SIGMA SFCS ON ALL NEEDED NGM GRIDS IS THEN
C   COMPUTED IN THE ARRAYS  S( JSCR3NGM( NN,2) ).  THIS ASSUMES A
C   LAPSE RATE OF 6.5DEG/KM BETWEEN GROUND AND THE FIRST SIGMA LEVEL,
C   AND A LINEAR VARIATION OF TAU BETWEEN HIGHER SIGMA LEVELS.  FOR
C   POSSIBLE LATER USE ( BY OTHER ROUTINES ) THESE ARE THEN INTER-
C   POLATED HORIZONTALLY TO THE OUTPUT GRID IN ARRAY S(JSCR3OUT(4) ).
C   .
C   .  IF ISOBARIC HEIGHTS ARE DESIRED AT OUTPUT PRESSURE PLOUT(L),
C   WHERE PLOUT(L) IS LESS THAN 1000 MBS (I.E. L IS .GT. 1 ),
C   THEY ARE COMPUTED ON EACH NGM GRID BY FIRST INTERPOLATING TAU TO
C   THE Z-VALUE:   ZL=-LOG(PLOUT(L) ), AND THEN INTEGRATING THE
C   HYDROSTATIC EQUATION FROM THE SIGMA LEVEL BELOW ZL TO ZL.  THESE
C   VALUES ARE THEN INTERPOLATED HORIZONTALLY TO THE OUTPUT GRID, AND
C   SENT TO THE PACKER CODE.  ISOTHERMAL CONDITIONS IN THE VERTICAL
C   ARE ASSUMED IN GETTING HGT(Z) ABOVE THE TOPMOST SIGMA SURFACE.
C   THE HEIGHT OF PRESSURE SURFACES BELOW THE BOTTOM SIGMA LEVEL IS
C   COMPUTED WITH A LAPSE RATE OF 6.5 DEG/KM.
C   .
C USAGE:    CALL OUTHYDRO( NCARDH, NCARD, NCARDA  )
C   INPUT ARGUMENT LIST:
C     NCARDH   - NUMBER OF DATA CARD FOR ISOBARIC HEIGHTS
C     NCARD    - NUMBER OF DATA CARD FOR UNADJUSTED SEA LEVEL
C                PRESSURE
C     NCARDA   - NUMBER OF DATA CARD FOR ADJUSTED SEA LEVEL
C                PRESSURE
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - OUTHORIZ
C                  OUTNULAB
C                  OUTPACK
C                  OUTSMOO
C     LIBRARY:
C       COMMON   - COMBLANK
C                  COMCONST
C                  COMOUT
C
C REMARKS:
C   .
C   THE ROUTINE  OUTSIG2P IS NOT USED BECAUSE THAT ROUTINE SIMPLY
C   INTERPOLATES LINEARLY WITH Z=-LOG(P), PAYING NO ATTENTION TO
C   THE HYDROSTATIC EQUATION.  THE PROCEDURE IN THIS CODE IN EFFECT
C   INTERPOLATES TAU ( THE DERIVATIVE OF HEIGHT ) LINEARLY IN Z.
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   .
C   SPECIFIC       ON NGM GRIDS IN S(JSCR3NGM(NN,2) )         COMMON
C   HUMIDITY
C   .
C   TEMPERATURE    ON NGM GRIDS IN S(JSCR3NGM(NN,1) )         COMMON
C   .
C   SURFACE        ON NGM GRIDS, IN VBL                       COMMON
C   PRESSURE
C   .
C   SURFACE        ON NGM GRIDS, IN VBL                       COMMON
C   HEIGHT
C   .
C   MSL PRESS      ON NGM GRIDS, IN VBL                       COMMON
C   CORRECTION
C   (IN BARS)
C   .
C   Z=-LOG(PRESS)  ON NGM GRIDS IN S(JSCR3NGM(NN,3)           COMMON
C   .
C   LTYPE(L,NG)    ARRAY OF FLAGS PREPARED BY SR  OUTPREP     COMMON
C   .              THAT DEFINE THE TYPE OF PRESSURE SURFACE
C   .              L ON NGM GRID NG
C   .           -1:  SFC HAS AT LEAST ONE POINT BELOW K=1
C   .            0:  SFC HAS NO PTS BELOW K=1 OR ABOVE K=KM
C   .            1:  SFC HAS AT LEAST ONE POINT ABOVE K=KM
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   .
C   HEIGHT         ON SIGMA LEVELS OF OUTPUT GRID, IN         COMMON
C                  S( JSCR3OUT(4) )
C   .
C   ALL OTHER OUTPUT FROM THIS ROUTINE TAKES PLACE THROUGH CALLS
C   TO THE SUBROUTINES  OUTNULAB  AND OUTPACK
C   .
C   FOR OUTNULAB, THE FOLLOWING LABEL INFORMATION IS PREPARED, FOR
C   ISOBARIC HEIGHTS OR FOR SEA-LEVEL PRESSURE
C   .
C   LABQTYPE       =1 FOR HEIGHT OR 8 FOR PRESSURE           COMMON
C   .
C   LABSSUB1       =8 FOR PRESSURE OR 128 FOR SEA-LEVEL      COMMON
C   .
C   S1VALUE        =PRESS(L) OR ZERO                         COMMON
C   .
C   FOR OUTPACK THE FOLLOWING INFORMATION IS SUPPLIED, FOR ISOBARIC
C   HEIGHTS OR FOR SEA-LEVEL PRESSURE.
C   .
C   S(MSOUT2)      THE ARRAY OF ISOBARIC HEIGHTS OR SEA-    ARGUMENT
C                  LEVEL PRESSURE(MBS)
C   .
C   IJOUT          THE SIZE OF THE OUTPUT GRID              ARGUMENT
C   .
C   S(MSOUT1)      SCRATCH SPACE FOR PACKER CODE(SIZE IJOUT)ARGUMENT
C   .
C   DESCRIPT       20 CHARACTER STRING TO DESCRIBE OUTPUT   ARGUMENT
C   .
C   LABEL84        ARRAY IN COMOUT CONTAINING LABEL INFO.   ARGUMENT
C   .
C   IOUTUNIT       DISK UNIT NUMBER FOR PACKER TO WRITE ON. ARGUMENT
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:49:48  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C           COMPUTE SEA-LEVEL PRESSURE, ISOBARIC
C           HEIGHTS AND HEIGHTS OF SIGMA SURFACES
C           ON OUTPUT GRIDS.
C           SUBROUTINE IS CALLED ONLY
C           IF ONE OF THESE 3 RESULTS IS WANTED.
C
      REAL GAMEXP,PKEQ1
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
CER
      INTEGER IDGRBE(25)
C
      COMMON/ADDRS/MIILL,MIIUL,MSA,MSB,MSC,MSD
C
      LOGICAL BITS,BIT1D,BIT2D
C
      DIMENSION FNGM(INSUMG),S(INSUMG),IN(INSUMG),BITS(INSUMG)
C
      EQUIVALENCE ( SCR(1,1),S(1),IN(1),BITS(1),FNGM(1) )
C
      INTEGER I,I1X,I2X,I3X
      DATA LABHGT/1/,LABPRES/8/,LABMSL/128/
C
C
C---------------------------------------------------------------
C ENTRANCE
      GRAVITY =    9.8  E0
      RGASD   =  287.05 E0
      RGASV   =  461.5  E0
      CSUBP   = 1005.   E0
C
      EPS     = RGASD/RGASV
C
      C1 = (1.E0-EPS) /EPS
      C2 = RGASD/GRAVITY
      C1 = C1 * C2
C
C          PUT  TAU  INTO S( JSCR3NGM(NN,1) ).
C
      DO 20 NN=1,NUMGDREQ
      NG=NGRIDATA(NN)
      IM=IMG(NG)
      JM=JMG(NG)
      IJ=IM*JM
      LEN=LENGD(NG)
      JJ1=J1(NG)
      JADDM1=(JJ1-1)*IM
C          INITIAL ADDRESS OF Q IN S,,MINUS IJ
      IADQ=JSCR3NGM(NN,2) + JADDM1 - IJ
C          INITIAL ADDRESS OF TEMP IN S,, MINUS IJ
      IADT=JSCR3NGM(NN,1) + JADDM1 -IJ
C          A SCRATCH ARRAY ADDRESS
      IADSCR = JSCR2(1)
C
        DO 10 K=1,KM
        IADQ=IADQ + IJ
        IADT = IADT + IJ
CMIC$ DO ALL VECTOR IF ((ABS(IADT-IADQ).GE.LEN .OR. IADT-IADQ.EQ.0)
CMIC$1    .AND. (ABS(IADT-IADSCR).GE.LEN .OR. IADT-IADSCR.EQ.0) .AND. (
CMIC$2   ABS(IADQ-IADSCR).GE.LEN .OR. IADQ-IADSCR.EQ.0)) SHARED(LEN, C1
CMIC$3   , IADT, IADQ, IADSCR, C2, S) PRIVATE(IQ2W6E)
      DO 88890 IQ2W6E=1,LEN
         S(IADSCR+IQ2W6E-1)=C1*S(IADT+IQ2W6E-1)*S(IADQ+IQ2W6E-1)
         S(IADT+IQ2W6E-1)=C2*S(IADT+IQ2W6E-1)+S(IADSCR+IQ2W6E-1)
88890 CONTINUE
   10   CONTINUE
   20 CONTINUE
C
C          UNADJUSTED SEA LEVEL PRESSURE IS NEEDED IF
C          IT IS WANTED FOR ITS OWN SAKE
       IF( LEVELS(1,NCARD) .EQ. 1 ) GO TO 100
C          OR THE ADJUSTED SEA LEVEL PRESSURE IS WANTED
       IF( LEVELS(1,NCARDA) .EQ. 1 ) GO TO 100
C          OR IF THE HEIGHT OF THE 1000-MB SFC IS WANTED
       IF( LEVELS(1,NCARDH) .EQ. 1 ) GO TO 100
C
C         NEITHER MSL PRESSURE OR 1000 MB HEIGHT IS WANTED.  CAN
C         SKIP SEA-LEVEL PRESSURE COMPUTATION AND 1000-MB HGT
C         COMPUTATION.
C
           GO TO 300
C
C--------------------------------------------------------------
C MSL PRESSURE AND/OR 1000-MB HEIGHT
  100 CONTINUE
C
C          BETWEEN K=1 AND THE GROUND WE ASSUME A CONSTANT
C          LAPSE RATE (-D(TAU)/D(HGT) ) CORRESPONDING TO
C            0.0065 DEGREES PER METER IN VIRTUAL TEMPERATURE.
C
      GAMEXP= C2 * .0065E0
      PKEQ1 =  PRESS(1)
      CTAU12G=1.E0/(PKEQ1**GAMEXP )
C          (THIS WILL GIVE TAU(GRND) = CTAU12G * TAU(K=1)   )
C
C
      DO 250 NN=1,NUMGDREQ
      NG=NGRIDATA(NN)
      IM=IMG(NG)
      JM=JMG(NG)
      IJ=IM*JM
      LEN=LENGD(NG)
      JJ1=J1(NG)
      JADDM1=(JJ1-1)*IM
C          FIRST GET THE VALUE OF TAU AT THE GROUND.
      IADTG=JSCR2(1)+JADDM1
      IADT1=JSCR3NGM(NN,1)+JADDM1
CMIC$ DO ALL VECTOR IF (ABS(IADT1-IADTG).GE.LEN .OR. IADT1-IADTG.EQ.0)
CMIC$1    SHARED(LEN, CTAU12G, IADT1, IADTG, S) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E=1,LEN
         S(IADTG+IQ2W6E-1)=CTAU12G*S(IADT1+IQ2W6E-1)
88910 CONTINUE
C          THE CRITICAL TAU VALUE FOR THE SHUELL METHOD.
C
      TAUCR=(RGASD/GRAVITY) * (273.16E0 + 17.5E0 )
C
C          A SCRATCH ARRAY
      IADSCR=JSCR2(3)+JADDM1
C
C          PUT THE TENTATIVE TAU AT SEA-LEVEL INTO JSCR2(2).
      CTAUG20=(RGASD/GRAVITY)*(CSUBP/GRAVITY)*(.0065E0)
C          ADDRESS OF SURFACE PSI IN ARRAY   VBL  .
      IADOROG=IADDRG(10,NG)+JADDM1
C          ADDRESS FOR TAU AT SEA-LEVEL
      IADTSL=JSCR2(2)+JADDM1
CMIC$ DO ALL VECTOR IF (ABS(IADTG-IADTSL).GE.LEN .OR. IADTG-IADTSL.EQ.0)
CMIC$1    SHARED(LEN, CTAUG20, IADOROG, IADTG, IADTSL, VBL, S) PRIVATE(
CMIC$2   IQ2W6E)
      DO 88920 IQ2W6E=1,LEN
         S(IADTSL+IQ2W6E-1)=CTAUG20*VBL(IADOROG+IQ2W6E-1)+S(IADTG
     *   +IQ2W6E-1)
88920 CONTINUE
C
C          ENTER THE SHUELL TESTS TO REDEFINE TAU AT SEA-LEVEL.
CMIC$ DO ALL VECTOR IF (ABS(MB1-MB2).GE.LEN .OR. MB1-MB2.EQ.0) SHARED(
CMIC$1   LEN, IADTSL, TAUCR, MB1, IADTG, MB2, S, BITS) PRIVATE(IQ2W6E)
      DO 88930 IQ2W6E=1,LEN
         BITS(MB1+IQ2W6E-1)=S(IADTSL+IQ2W6E-1).GT.TAUCR
         BITS(MB2+IQ2W6E-1)=S(IADTG+IQ2W6E-1).GT.TAUCR
88930 CONTINUE
C
C               CONSTANT FOR SHUELL CORRECTION
         CONST = 0.005E0 * GRAVITY / RGASD
C          (FOR WHERE BOTH TAUS EXCEED TAUCR---)
CMIC$ DO ALL VECTOR IF ((ABS(IADTG-IADSCR).GE.LEN .OR. IADTG-IADSCR.EQ.0
CMIC$1   ) .AND. (ABS(IADTG-IADTSL).GE.LEN .OR. IADTG-IADTSL.EQ.0)
CMIC$2    .AND. (ABS(IADSCR-IADTSL).GE.LEN .OR. IADSCR-IADTSL.EQ.0))
CMIC$3    SHARED(LEN, MB1, MB2, IADTG, TAUCR, IADSCR, CONST, IADTSL, 
CMIC$4   BITS, S) PRIVATE(IQ2W6E)
      DO 88950 IQ2W6E=1,LEN
       IF ( BITS(MB1+IQ2W6E-1) .AND. BITS(MB2+IQ2W6E-1) ) THEN
         S(IADSCR+IQ2W6E-1)=S(IADTG+IQ2W6E-1)-TAUCR
         S(IADSCR+IQ2W6E-1)=S(IADSCR+IQ2W6E-1)*S(IADSCR+IQ2W6E-1)
         S(IADTSL+IQ2W6E-1)=TAUCR-CONST*S(IADSCR+IQ2W6E-1)
       END IF
88950 CONTINUE
C
CMIC$ PARALLEL SHARED(LEN, MB1, MB2, TAUCR, IADTSL, BITS, S) PRIVATE(
CMIC$1   IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 88980 IQ2W6E=1,LEN
         BITS(MB2+IQ2W6E-1)=.NOT.BITS(MB2+IQ2W6E-1)
88980 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 88990 IQ2W6E=1,LEN
       IF ( BITS(MB1+IQ2W6E-1) .AND. BITS(MB2+IQ2W6E-1) ) THEN
         S(IADTSL+IQ2W6E-1)=TAUCR
       END IF
88990 CONTINUE
CMIC$ END PARALLEL
C
C         CAN NOW COMPUTE THE MEAN TAU FROM GROUND TO SEA-LEVEL
CMIC$ DO ALL VECTOR IF ((ABS(IADTSL-IADSCR).GE.LEN .OR. IADTSL-IADSCR
CMIC$1   .EQ.0) .AND. (ABS(IADTG-IADSCR).GE.LEN .OR. IADTG-IADSCR.EQ.0))
CMIC$2    SHARED(LEN, IADTSL, IADTG, IADSCR, S) PRIVATE(IQ2W6E)
      DO 89000 IQ2W6E=1,LEN
         S(IADSCR+IQ2W6E-1)=.5E0*(S(IADTSL+IQ2W6E-1)+S(IADTG+IQ2W6E-1)
     *   )
89000 CONTINUE
C          PUT HEIGHT OF THE GROUND INTO PLACE OF TAU(GRND)
      C3=CSUBP/GRAVITY
CMIC$ DO ALL VECTOR SHARED(LEN, C3, IADOROG, IADTG, VBL, S) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89010 IQ2W6E=1,LEN
         S(IADTG+IQ2W6E-1)=C3*VBL(IADOROG+IQ2W6E-1)
89010 CONTINUE
C          THE EXPONENT = GROUND HGT / MEAN TAU
CMIC$ DO ALL VECTOR IF (ABS(IADTG-IADSCR).GE.LEN .OR. IADTG-IADSCR.EQ.0)
CMIC$1    SHARED(LEN, IADTG, IADSCR, S) PRIVATE(IQ2W6E)
      DO 89020 IQ2W6E=1,LEN
         S(IADSCR+IQ2W6E-1)=S(IADTG+IQ2W6E-1)/S(IADSCR+IQ2W6E-1)
89020 CONTINUE
C
CMIC$ DO ALL VECTOR IF (ABS(IADSCR-IADTG).GE.LEN .OR. IADSCR-IADTG.EQ.0)
CMIC$1    SHARED(LEN, IADSCR, IADTG, S) PRIVATE(IQ2W6E)
      DO 89030 IQ2W6E=1,LEN
         S(IADTG+IQ2W6E-1)=EXP(S(IADSCR+IQ2W6E-1))
89030 CONTINUE
C          ADDRESS OF SURFACE PRESSURE(DIVIDED BY 1000 MBS)
      IADH=IADDRG(5,NG) + JADDM1
C          SEA-LEVEL PRESS IN BARS INTO ITS PLACE IN  FNGM  .
      IADF=JADDFNGM(NG) + JADDM1
CMIC$ DO ALL VECTOR IF (ABS(IADTG-IADF).GE.LEN .OR. IADTG-IADF.EQ.0)
CMIC$1    SHARED(LEN, IADH, IADTG, IADF, VBL, S) PRIVATE(IQ2W6E)
      DO 89040 IQ2W6E=1,LEN
         S(IADF+IQ2W6E-1)=VBL(IADH+IQ2W6E-1)*S(IADTG+IQ2W6E-1)
89040 CONTINUE
C
C            CONSIDER THE PRESSURE TENDENCY CORRECTION METHOD.
C            UNITS ARE CHANGED TO MILLIBARS.
C            ADDRESS OF ADJUSTMENT VALUES IS CALCULATED FIRST.
      IADPAD = IADDRG( 9,NG) + (JJ1-1) * IM
C
      IF(LEVELS(1,NCARDA) .GT. 0 ) THEN
CMIC$ DO ALL VECTOR SHARED(LEN, IADF, IADPAD, S, VBL) PRIVATE(IQ2W6E)
      DO 89050 IQ2W6E=1,LEN
         S(IADF+IQ2W6E-1)=(S(IADF+IQ2W6E-1)+VBL(IADPAD+IQ2W6E-1))*1000
     *   .E0
89050 CONTINUE
      ELSE
CMIC$ DO ALL VECTOR SHARED(LEN, IADF, S) PRIVATE(IQ2W6E)
      DO 89060 IQ2W6E=1,LEN
         S(IADF+IQ2W6E-1)=S(IADF+IQ2W6E-1)*1000.E0
89060 CONTINUE
      END IF
C
C
C          END OF THE NG LOOP
  250 CONTINUE
C          DO THE HORIZONTAL INTERPOLATION TO OUTPUT GRID
        CALL OUTHORIZ(IN(MIILL),IN(MIIUL),S(MSA),S(MSB),S(MSC),
     *         S(MSD),S(MSOUT1),S(MSOUT2))
C              SMOOTH THIS FIELD
        CALL OUTSMOO(MSOUT2)
C
C             BUT , IS SEA-LEVEL PRESSURE WANTED FOR ITS OWN SAKE???
      IF( LEVELS(1,NCARD) .EQ. 1 ) GO TO 260
      IF( LEVELS(1,NCARDA) .EQ. 1 ) GO TO 260
C            NEITHER FORM OF SEA LEVEL PRESSURE IS WANTED
      GO TO 270
C
  260 CONTINUE
C                SEA LEVEL PRESSURE IS WANTED
C          PREPARE FOR PACKING
      LABQTYPE=LABPRES
      LABSSUB1=LABMSL
      S1VALUE=0.E0
         CALL OUTNULAB
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IDGRBE(8) =   2
      IDGRBE(9) = 102
      IDGRBE(10) =  0
      IDGRBE(11) =  0
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0
      IDGRBE(20) =  0

c        CALL OUTPACK(S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
c    1   LABEL84, IOUTUNIT)
         CALL GRIBITN (S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
     1   IDGRBE,IOUTGRIB,LABEL84)
C
  270 CONTINUE
C
C
C               THE 1000-MB HEIGHT, IF WANTED, WILL BE DERIVED FROM
C           THIS SEA-LEVEL PRESSURE FIELD.  THIS IS DONE SO THAT
C           ISOLINES OF THE 1000-500 MB THICKNESS FIELD WILL BE
C           CONSISTENT WITH THE SEA-LEVEL PRESSURE AND 500-MB HEIGHT
C           FIELDS.
C
      IF( LEVELS(1,NCARDH) .NE. 1 ) GO TO 300
C
CMIC$ DO ALL VECTOR SHARED(IJOUT, MSOUT2, S) PRIVATE(IQ2W6E)
      DO 89070 IQ2W6E=1,IJOUT
         S(MSOUT2+IQ2W6E-1)=S(MSOUT2+IQ2W6E-1)-1000.E0
89070 CONTINUE
      C1 = 0.1E0 / ( GRAVITY * 1.25E-3 )
CMIC$ DO ALL VECTOR SHARED(IJOUT, C1, MSOUT2, S) PRIVATE(IQ2W6E)
      DO 89080 IQ2W6E=1,IJOUT
         S(MSOUT2+IQ2W6E-1)=C1*S(MSOUT2+IQ2W6E-1)
89080 CONTINUE
C
      SVALU = 1000.E0
      S1VALUE = NINT( SVALU )
      LABQTYPE = LABHGT
      LABSSUB1 = LABPRES
C
            CALL OUTNULAB
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IDGRBE(8) =   7
      IDGRBE(9) = 100
      IDGRBE(10) =  0
      IARG = LABEL84(6)
      IDGRBE(11) =  LABEL84(5) * 10.**IARG
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0
      IDGRBE(20) =  0
c     do k = 1, 25
c       print *,"heights at 1000 mb ",label84(k),idgrbe(k)
c     enddo
C
c     CALL OUTPACK( S(MSOUT2),IJOUT, S(MSOUT1), DESCRIPT(NCARDH),
c    1              LABEL84, IOUTUNIT )
      CALL GRIBITN ( S(MSOUT2),IJOUT, S(MSOUT1), DESCRIPT(NCARDH),
     1              IDGRBE,IOUTGRIB,LABEL84 )
CC
C
C-------------------------------------------------------------
C HEIGHT OF SIGMA LEVELS
  300 CONTINUE
C
C            WILL POSTPONE REMAINING ISOBARIC HEIGHTS BECAUSE THEY
C            WILL NOT REFLECT THE AD-HOC TREATMENT OF MSL PRESSURE.
C
C          THE FIRST MAJOR TASK NOW WILL BE TO COMPUTE  HGT OF ALL
C          K-LEVELS IN THE ARRAY  S(JSCR3NGM(NN,2)
C            (REPLACING THE SPECIFIC HUMIDITY)
C          THE FIRST PART OF THIS TASK IS TO GET  HGT  AT K=1.
C
      DO 340 NN=1,NUMGDREQ
      NG=NGRIDATA(NN)
      IM=IMG(NG)
      JM=JMG(NG)
      IJ=IM*JM
      LEN=LENGD(NG)
      JJ1=J1(NG)
      JADDM1=(JJ1-1)*IM
C          FIRST COMPUTE TAU AT THE GROUND IN JSCR2(1)
      IADTG=JSCR2(1) + JADDM1
      IADT=JSCR3NGM(NN,1) + JADDM1
CMIC$ DO ALL VECTOR IF (ABS(IADT-IADTG).GE.LEN .OR. IADT-IADTG.EQ.0)
CMIC$1    SHARED(LEN, CTAU12G, IADT, IADTG, S) PRIVATE(IQ2W6E)
      DO 89090 IQ2W6E=1,LEN
         S(IADTG+IQ2W6E-1)=CTAU12G*S(IADT+IQ2W6E-1)
89090 CONTINUE
C
C          START NOW TO COMPUTE  HGT  FOR LAYER K=1.
C       HGT(1)=HGT(GND) +.5(TAU(1)+TAU(GND) )*(Z(1)-Z(GND) )
C          FIRST PUT THE MEAN TAU IN JSCR2(2)
      IADS=JSCR2(2) + JADDM1
CMIC$ DO ALL VECTOR IF ((ABS(IADTG-IADS).GE.LEN .OR. IADTG-IADS.EQ.0)
CMIC$1    .AND. (ABS(IADT-IADS).GE.LEN .OR. IADT-IADS.EQ.0)) SHARED(LEN
CMIC$2   , IADTG, IADT, IADS, S) PRIVATE(IQ2W6E)
      DO 89100 IQ2W6E=1,LEN
         S(IADS+IQ2W6E-1)=.5E0*(S(IADTG+IQ2W6E-1)+S(IADT+IQ2W6E-1))
89100 CONTINUE
C           THEN PUT HGT(GND) INTO JSCR2(3)
      IADHGTG=JSCR2(3)+JADDM1
C          ADDRESS OF GROUND HEIGHT(TIMES G/CSUBP) IN VBL
      IADVBL=IADDRG(10,NG) + JADDM1
      C4=CSUBP/GRAVITY
CMIC$ DO ALL VECTOR SHARED(LEN, C4, IADVBL, IADHGTG, VBL, S) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89110 IQ2W6E=1,LEN
         S(IADHGTG+IQ2W6E-1)=C4*VBL(IADVBL+IQ2W6E-1)
89110 CONTINUE
C          CAN NOW GET  HGT  FOR K=1
      C1=ZSIGLYR(1)
C          ADDRESS FOR  HGT  IN S
      IADHGT=JSCR3NGM(NN,2) + JADDM1
CMIC$ DO ALL VECTOR IF ((ABS(IADHGTG-IADHGT).GE.LEN .OR. IADHGTG-IADHGT
CMIC$1   .EQ.0) .AND. (ABS(IADS-IADHGT).GE.LEN .OR. IADS-IADHGT.EQ.0))
CMIC$2    SHARED(LEN, IADHGTG, C1, IADS, IADHGT, S) PRIVATE(IQ2W6E)
      DO 89120 IQ2W6E=1,LEN
         S(IADHGT+IQ2W6E-1)=S(IADHGTG+IQ2W6E-1)+C1*S(IADS+IQ2W6E-1)
89120 CONTINUE
C
C          GET THE SIGMA LEVEL HEIGHTS NOW FOR K=2,KM.
C          HGT ADDRESS ALREADY SET FOR K=1.
C          TAU ADDRESS FOR K=1
      IADT=JSCR3NGM(NN,1) + JADDM1
      DO 330 K=2,KM
      C1=.5E0*(ZSIGLYR(K)-ZSIGLYR(K-1) )
      IADT=IADT + IJ
      IADHGT=IADHGT + IJ
C          THE  TAU  TERM
CMIC$ DO ALL VECTOR IF ((ABS(IADT-IADS).GE.LEN .OR. IADT-IADS.EQ.0)
CMIC$1    .AND. (ABS(IADT-IADHGT).GE.LEN .OR. IADT-IADHGT.EQ.0) .AND. (
CMIC$2   ABS(IADT-IJ-IADS).GE.LEN .OR. IADT-IJ-IADS.EQ.0) .AND. (ABS(
CMIC$3   IADT-IJ-IADHGT).GE.LEN .OR. IADT-IJ-IADHGT.EQ.0) .AND. (ABS(
CMIC$4   IADS+IJ-IADHGT).GE.LEN .OR. IADS+IJ-IADHGT.EQ.0) .AND. (ABS(
CMIC$5   IADS-IADHGT).GE.LEN .OR. IADS-IADHGT.EQ.0) .AND. (ABS(IJ).GE.
CMIC$6   LEN .OR. IJ.EQ.0)) SHARED(LEN, C1, IADT, IJ, IADS, IADHGT, S)
CMIC$7    PRIVATE(IQ2W6E)
      DO 89130 IQ2W6E=1,LEN
         S(IADS+IQ2W6E-1)=C1*(S(IADT+IQ2W6E-1)+S(IADT-IJ+IQ2W6E-1))
         S(IADHGT+IQ2W6E-1)=S(IADHGT-IJ+IQ2W6E-1)+S(IADS+IQ2W6E-1)
89130 CONTINUE
  330 CONTINUE
C
C
  340 CONTINUE
C
C          WILL NEED HGT(SIGMA) ON OUTPUT GRID FOR USE IN COMPUTING
C          HGT OF ANY SURFACE TYPE (EXCEPT PRESSURE). PUT IT IN
C          S( JSCR3OUT(4) ).
      DO 350 K=1,KM
C          ADDRESS FOR OUTPUT GRID TARGET POINT
      IADTO=JSCR3OUT(4) + (K-1)*IJOUT
      DO 345 NN=1,NUMGDREQ
      NG=NGRIDATA(NN)
      IM=IMG(NG)
      JM=JMG(NG)
      IJ=IM*JM
      JJ1=J1(NG)
      JADDM1=(JJ1-1)*IM
      LEN=LENGD(NG)
C          THE FETCH ADDRESS FOR  HGT  ON NGM GRID
      IADFROM=JSCR3NGM(NN,2) + JADDM1 +IJ*(K-1)
C          THE TARGET ADDRESS IN ARRAY FNGM
      IADF=JADDFNGM(NG) + JADDM1
C          PUT IT IT ARRAY FNGM
CMIC$ DO ALL VECTOR IF (ABS(IADFROM-IADF).GE.LEN .OR. IADFROM-IADF.EQ.0)
CMIC$1    SHARED(LEN, IADFROM, IADF, S) PRIVATE(IQ2W6E)
      DO 89150 IQ2W6E=1,LEN
         S(IADF+IQ2W6E-1)=S(IADFROM+IQ2W6E-1)
89150 CONTINUE
  345 CONTINUE
C
C
        CALL OUTHORIZ(IN(MIILL),IN(MIIUL),S(MSA),S(MSB),
     *                S(MSC),S(MSD),S(MSOUT1),S(IADTO))
  350 CONTINUE
C
C-----------------------------------------------------------
C
C          RETURN TO THE NGM GRID DATA AND THE TASK OF PREPARING
C          ISOBARIC HEIGHT DATA.
C
C
C          ENTER THE L - LOOP FOR ISOBARIC HEIGHT OUTPUT
C            ( NOTE THAT OUTPUT OF 1000-MB HEIGHT (L=1) HAS ALREADY
C              BEEN TAKEN CARE OF, SINCE IT IS DERIVED FROM THE
C              FIELD OF MSL PRESSURE. )
C
      DO 450 L=2,LMOUT
      LVL=LEVELS(L,NCARDH)
      IF( LVL .NE. 1 ) GO TO 450
C
      ZL=ZLOUT(L)
C          GET EACH NGM HGT(PRESS(L) ) INTO ITS PLACE IN ARRAY  FNGM.
        DO 400  NN=1,NUMGDREQ
        NG=NGRIDATA(NN)
        IM=IMG(NG)
        JM=JMG(NG)
        IJ=IM*JM
        JJ1=J1(NG)
        LEN=LENGD(NG)
        JADDM1=(JJ1-1)*IM
C          SCRATCH ARRAYS
C          GATHER ORIGIN FOR Z
        IADZ=JSCR3NGM(NN,3)-1
C          GATHER ORIGIN FOR TAU
        IADT=JSCR3NGM(NN,1)-1
C          GATHER ORIGIN FOR HGT
        IADH=JSCR3NGM(NN,2)-1
C          ADDRESS OF GATHER INTEGERS (K SFC BELOW P SFC )
        IADG=JADDK2L(NG,1) + (L-1)*LEN
C          ADDRESS OF COEFFICIENT FOR INTERPOLATION
        IADC=JADDK2L(NG,2) + (L-1)*LEN
C          THE TARGET ADDRESS IN ARRAY FNGM
        IADF=JADDFNGM(NG) + JADDM1
C          COMPUTE( VIA GATHERS ) TAU VALUE AT PRESSURE SFC L.
C         TAU AT K-SFC BELOW PRESSURE SFC INTO S1D.
C*****  Code Expanded From Routine:  RDHGATHR
      DO 77053 I = 1, LEN
         S(I+JSCR2(1)-1) = S(IN(I+IADG-1)+IADT)
77053 CONTINUE
      DO 77054 I1X = 1, LEN
         S(I1X+JSCR2(2)-1) = S(IN(I1X+IADG-1)+IADT+IJ)
77054 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR IF ((ABS(JSCR2(2)-JSCR2(1)).GE.LEN .OR. JSCR2(2)-
CMIC$1   JSCR2(1).EQ.0) .AND. (ABS(JSCR2(2)-IADC).GE.LEN .OR. JSCR2(2)-
CMIC$2   IADC.EQ.0)) SHARED(LEN, IADC, JSCR2, S) PRIVATE(IQ2W6E)
      DO 89160 IQ2W6E=1,LEN
         S(JSCR2(2)+IQ2W6E-1)=S(JSCR2(2)+IQ2W6E-1)-S(JSCR2(1)+IQ2W6E-1
     *   )
         S(JSCR2(2)+IQ2W6E-1)=S(JSCR2(2)+IQ2W6E-1)*S(IADC+IQ2W6E-1)
89160 CONTINUE
C          PUT TAUBAR=( TAU(L) + TAU(K) )/2 INTO S2D
CMIC$ DO ALL VECTOR IF (ABS(JSCR2(1)-JSCR2(2)).GE.LEN .OR. JSCR2(1)-
CMIC$1   JSCR2(2).EQ.0) SHARED(LEN, JSCR2, S) PRIVATE(IQ2W6E)
      DO 89180 IQ2W6E=1,LEN
         S(JSCR2(2)+IQ2W6E-1)=S(JSCR2(1)+IQ2W6E-1)+.5E0*S(JSCR2(2
     *   )+IQ2W6E-1)
89180 CONTINUE
C
C          MODIFY TAUBAR IF THERE ARE POINTS ABOVE K=KM.
        IF(LTYPE(L,NG) .NE. 1 ) GO TO 390
C          SOME POINTS ARE ABOVE K=KM.
CMIC$ DO ALL VECTOR SHARED(LEN, IADG, MB1, IN, BITS) PRIVATE(IQ2W6E)
      DO 89190 IQ2W6E=1,LEN
         BITS(MB1+IQ2W6E-1)=IN(IADG+IQ2W6E-1).EQ.0
89190 CONTINUE
C          AT THESE POINTS WE SET TAU = TAU(K=KM).
        IADTKM=JSCR3NGM(NN,1)+JADDM1+(KM-1)*IJ
CMIC$ DO ALL VECTOR IF (ABS(IADTKM-JSCR2(2)).GE.LEN .OR. IADTKM-JSCR2(2)
CMIC$1   .EQ.0) SHARED(LEN, MB1, IADTKM, BITS, S, JSCR2) PRIVATE(IQ2W6E)
      DO 89200 IQ2W6E=1,LEN
       IF ( BITS(MB1+IQ2W6E-1) ) THEN
         S(JSCR2(2)+IQ2W6E-1)=S(IADTKM+IQ2W6E-1)
       END IF
89200 CONTINUE
C
  390 CONTINUE
C
C          PROCEED NOW,,ALL COMPUTATIONS WILL BE OKEH EXCEPT
C          FOR ANY POINTS BELOW K=1.
C
C            GATHER Z(K) BELOW PRESSURE SURFACE
C*****  Code Expanded From Routine:  RDHGATHR
      DO 77055 I2X = 1, LEN
         S(I2X+JSCR2(1)-1) = S(IN(I2X+IADG-1)+IADZ)
77055 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          ZL MINUS Z(K BELOW)
CMIC$ DO ALL VECTOR SHARED(LEN, ZL, JSCR2, S) PRIVATE(IQ2W6E)
      DO 89210 IQ2W6E=1,LEN
         S(JSCR2(1)+IQ2W6E-1)=ZL-S(JSCR2(1)+IQ2W6E-1)
89210 CONTINUE
C          MULTIPLY THIS WITH TAUBAR
CMIC$ DO ALL VECTOR IF (ABS(JSCR2(2)-JSCR2(1)).GE.LEN .OR. JSCR2(2)-
CMIC$1   JSCR2(1).EQ.0) SHARED(LEN, JSCR2, S) PRIVATE(IQ2W6E)
      DO 89220 IQ2W6E=1,LEN
         S(JSCR2(2)+IQ2W6E-1)=S(JSCR2(2)+IQ2W6E-1)*S(JSCR2(1)+IQ2W6E-1
     *   )
89220 CONTINUE
C          NOW WE NEED  HGT  AT K(BELOW).
C*****  Code Expanded From Routine:  RDHGATHR
      DO 77056 I3X = 1, LEN
         S(I3X+JSCR2(1)-1) = S(IN(I3X+IADG-1)+IADH)
77056 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
C          PUT THE ISOBARIC HEIGHT FIELD INTO ITS PLACE IN FNGM.
CMIC$ DO ALL VECTOR IF ((ABS(JSCR2(1)-IADF).GE.LEN .OR. JSCR2(1)-IADF
CMIC$1   .EQ.0) .AND. (ABS(JSCR2(2)-IADF).GE.LEN .OR. JSCR2(2)-IADF.EQ.0
CMIC$2   )) SHARED(LEN, IADF, JSCR2, S) PRIVATE(IQ2W6E)
      DO 89230 IQ2W6E=1,LEN
         S(IADF+IQ2W6E-1)=S(JSCR2(1)+IQ2W6E-1)+S(JSCR2(2)+IQ2W6E-1)
89230 CONTINUE
C
C
C          WE ARE DONE UNLESS THERE ARE POINTS BELOW K=1.
        IF( LTYPE(L,NG) .GE. 0 ) GO TO 400
C          WE HAVE SUCH POINTS.
C          WE NOW INTEGRATE DOWNWARD FROM Z AT K=1.
C
CMIC$ DO ALL VECTOR SHARED(LEN, IADG, MB1, IN, BITS) PRIVATE(IQ2W6E)
      DO 89240 IQ2W6E=1,LEN
         BITS(MB1+IQ2W6E-1)=IN(IADG+IQ2W6E-1).EQ.0
89240 CONTINUE
C          ADDRESS OF Z(K=1) POINT
        IADZ1=JSCR3NGM(NN,3)+JADDM1
C          ADDRESS OF TAU(K=1) POINT
        IADT1=JSCR3NGM(NN,1) + JADDM1
C          ADDRESS OF HGT(K=1) POINT
        IADH1=JSCR3NGM(NN,2) + JADDM1
C          ASSUME D(TEMP)/D(HGT)=-.0065 DEG/METER.
        C1=-(RGASD/GRAVITY)*.0065E0*.5E0
CMIC$ DO ALL VECTOR IF (ABS(IADZ1-JSCR2(1)).GE.LEN .OR. IADZ1-JSCR2(1)
CMIC$1   .EQ.0) SHARED(LEN, ZL, IADZ1, S, JSCR2) PRIVATE(IQ2W6E)
      DO 89250 IQ2W6E=1,LEN
         S(JSCR2(1)+IQ2W6E-1)=ZL-S(IADZ1+IQ2W6E-1)
89250 CONTINUE
        C5=2.E0*C1*C1/3.E0
CMIC$ DO ALL VECTOR IF ((ABS(JSCR2(1)-JSCR2(2)).GE.LEN .OR. JSCR2(1)-
CMIC$1   JSCR2(2).EQ.0) .AND. (ABS(JSCR2(2)-IADT1).GE.LEN .OR. JSCR2(2)-
CMIC$2   IADT1.EQ.0)) SHARED(LEN, C5, C1, IADT1, JSCR2, S) PRIVATE(
CMIC$3   IQ2W6E)
      DO 89260 IQ2W6E=1,LEN
         S(JSCR2(2)+IQ2W6E-1)=C5*S(JSCR2(1)+IQ2W6E-1)
         S(JSCR2(2)+IQ2W6E-1)=S(JSCR2(1)+IQ2W6E-1)*(C1+S(JSCR2(2)
     *   +IQ2W6E-1))
         S(JSCR2(2)+IQ2W6E-1)=S(JSCR2(1)+IQ2W6E-1)*(1.E0+S(JSCR2(
     *   2)+IQ2W6E-1))
         S(JSCR2(2)+IQ2W6E-1)=S(JSCR2(2)+IQ2W6E-1)*S(IADT1+IQ2W6E-1)
89260 CONTINUE
C
C          PUT THE CORRECTED HEIGHTS INTO FNGM POSITION.
CMIC$ DO ALL VECTOR IF ((ABS(IADH1-IADF).GE.LEN .OR. IADH1-IADF.EQ.0)
CMIC$1    .AND. (ABS(JSCR2(2)-IADF).GE.LEN .OR. JSCR2(2)-IADF.EQ.0))
CMIC$2    SHARED(LEN, MB1, IADH1, IADF, BITS, S, JSCR2) PRIVATE(IQ2W6E)
      DO 89300 IQ2W6E=1,LEN
       IF ( BITS(MB1+IQ2W6E-1)) THEN
         S(IADF+IQ2W6E-1)=S(IADH1+IQ2W6E-1)+S(JSCR2(2)+IQ2W6E-1)
       END IF
89300 CONTINUE
C
C            END OF THE GRID NG LOOP FOR THIS L OUTPUT SURFACE.
  400   CONTINUE
C
C          CAN NOW DO THE HORIZONTAL INTERPOLATION
         CALL OUTHORIZ(IN(MIILL),IN(MIIUL),S(MSA),S(MSB),S(MSC),
     *                S(MSD),S(MSOUT1),S(MSOUT2))
C              SMOOTH THIS FIELD
         CALL OUTSMOO(MSOUT2)
C
C
      SVALU=1000.E0*PLOUT(L)
      S1VALUE=NINT( SVALU )
      LABQTYPE=LABHGT
      LABSSUB1=LABPRES
C          FIRST UPDATE THE LABEL ARRAY
        CALL OUTNULAB
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IDGRBE(8) =   7
      IF(LABEL84(2).EQ.8) IDGRBE(9) = 100
      IF(LABEL84(2).EQ.148) IDGRBE(9) = 107
      ALEV1 = REAL(LABEL84(5))
      ARGL1 = REAL(LABEL84(6))
      XLEV1 = ALEV1 * 10.**ARGL1
      IDGRBE(10) = 0
      IDGRBE(11) =  INT(XLEV1)
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0
      IDGRBE(20) =  0
c     do k = 1, 25
c       print *,"heights on p ",label84(k),idgrbe(k)
c     enddo 
C
c       CALL OUTPACK( S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARDH),
c    1  LABEL84,IOUTUNIT)
        CALL GRIBITN ( S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARDH),
     1  IDGRBE,IOUTGRIB,LABEL84)
C
  450 CONTINUE
C
      RETURN
      END
