      SUBROUTINE OUTHORIZ(ILL,IUL,AHOR,BHOR,CHOR,DHOR,SCRHOR,OUTHOR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    OUTHORIZ     INTERPOLATE FROM NGM TO OUTPUT GRID
C   PRGMMR: N PHILLIPS        ORG: W/NMC22    DATE: 83-12-01
C
C ABSTRACT: ARRAY FNGM HAS THE NEEDED DATA FROM THE NGM GRIDS.
C   SUBROUTINE  OUTPREP  HAS SET UP THE DESCRIPTORS
C   AHORD, BHORD, CHORD, AND DHORD  FOR THE FOUR ARRAYS OF
C   INTERPOLATION COEFFICIENTS(EACH ARRAY OF LENGTH  IJOUT  ),
C   AND
C   TWO ARRAYS OF GATHER INTEGERS WITH THE DESCRIPTORS
C   ILLD(FOR THE LOWER LEFT POINT) AND IULD(UPPER LEFT POINT).
C   THE INTERPOLATED RESULT IS PLACED IN THE ARRAY GIVEN BY
C   DESCRIPTOR   OUTHORD  .
C   (OUTHORD IS NORMALLY SET TO POINT TO ARRAY S(MSOUT2), BUT
C   IT CAN BE REDIRECTED PRIOR TO CALLING THIS SUBROUTINE IF IT IS
C   ASSIGNED BACK TO ARRAY S(MSOUT2) FOR THE NEXT (NORMAL) CALL TO
C   THIS ROUTINE.  THE OTHER DESCRIPTORS CANNOT BE CHANGED.
C   .
C   THIS SUBROUTINE CAN ONLY BE SUCCESSFULLY EXECUTED AFTER:
C   1)  SUBROUTINE OUTPREP HAS PREPARED THE GATHER INTEGERS AND
C   .   INTERPOLATION COEFFICIENTS
C   2)  THE VARIABLE TO BE INTERPOLATED HAS BEEN PLACED IN THE
C   .   PROPER LOCATIONS FOR EACH NEEDED NGM GRID IN ARRAY FNGM.
C   .   THE POINT I,J=1,1 FOR THE NGM GRID  NGG  IS LOCATED IN
C   .   FNGM( JADDFNGM(NGG) ).
C   .   THE J-ROWS NEEDED FOR THIS GRID  NGG  ARE J=J1(NGG) THRU
C   .   J=J2(NGG).
C   .   THE GRID NUMBERS ( E.G.  NGG ) THAT ARE NEEDED ARE GIVEN
C   .   BY  NGRIDATA(N), WHERE N=1,NUMGDREQ.
C .
C
C PROGRAM HISTORY LOG:
C   83-12-01  N PHILLIPS
C   88-08-24  BRIAN SCHMIDT REVISED THE DOCBLOCK
C
C USAGE:  CALL OUTHORIZ
C   INPUT ARGUMENT LIST: (REALLY INPUT VARIABLES)
C     AHORD   -
C     BHORD   -   DESCRIPTORS FOR BILINEAR INTERPOLATION
C     CHORD   -   COEFFICIENTS (FROM COMMON)
C     DHORD   -
C     .
C     ILLD    -   DESCRIPTORS FOR GATHER INTEGERS
C     IULD    -   (FROM COMMON)
C     IULD    -   (FROM COMMON)
C     .
C     SCRHORD -   DESCRIPTOR FOR SCRATCH ARRAY S(MSOUT1) (FROM COMMON)
C
C   OUTPUT ARGUMENT LIST: (REALLY OUTPUT VARIABLES)
C     OUTHORD -   DESCRIPTOR POINTING TO ARRAY(SIZE IJOUT)
C     .           CONTAINING INTERPOLATED RESULTS.  (FROM COMMON)
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C       COMMON   - COMOUT
C                  COMBLANK
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:48:35  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C               DO A HORIZONTAL BILINEAR INTERPOLATION
C               ONTO THE OUTPUT GRID OF THE GRIDS OF DATA
C               FROM NGM GRIDS THAT ARE LOCATED IN ARRAY
C               FNGM.
C
      DIMENSION ILL(1),IUL(1),AHOR(1),BHOR(1),CHOR(1),DHOR(1),
     *          SCRHOR(1),OUTHOR(1)
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
C
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
      DIMENSION FNGM(INSUMG)
      EQUIVALENCE (SCR(1,1), FNGM(1) )
      INTEGER I,I1X,I2X,I3X
C
C          GATHER THE LOWER LEFT VALUES INTO SCRHORD AND MULT. WITH COEF
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(IJOUT, ILL, FNGM, SCRHOR) PRIVATE(I)
      DO 77001 I = 1, IJOUT
         SCRHOR(I) = FNGM(ILL(I))
77001 CONTINUE
C*****  End of Code Expanded From Routine:  RDHGATHR
CMIC$ PARALLEL SHARED(IJOUT, ILL, FNGM, SCRHOR, AHOR, OUTHOR) PRIVATE(
CMIC$1   I1X, IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 88890 IQ2=1,IJOUT
         OUTHOR(IQ2)=SCRHOR(IQ2)*AHOR(IQ2)
88890 CONTINUE
C          ADD THE LOWER RIGHT CONTRIBUTION
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO PARALLEL VECTOR
      DO 77002 I1X = 1, IJOUT
         SCRHOR(I1X) = FNGM(ILL(I1X)+1)
77002 CONTINUE
CMIC$ END PARALLEL
C*****  End of Code Expanded From Routine:  RDHGATHR
CMIC$ PARALLEL SHARED(IJOUT, IUL, FNGM, SCRHOR, CHOR, OUTHOR) PRIVATE(
CMIC$1   I2X, IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 88900 IQ2=1,IJOUT
         SCRHOR(IQ2)=SCRHOR(IQ2)*CHOR(IQ2)
         OUTHOR(IQ2)=OUTHOR(IQ2)+SCRHOR(IQ2)
88900 CONTINUE
C          ADD THE UPPER LEFT CONTRIBUTION
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO PARALLEL VECTOR
      DO 77003 I2X = 1, IJOUT
         SCRHOR(I2X) = FNGM(IUL(I2X))
77003 CONTINUE
CMIC$ END PARALLEL
C*****  End of Code Expanded From Routine:  RDHGATHR
CMIC$ PARALLEL SHARED(IJOUT, IUL, FNGM, SCRHOR, BHOR, OUTHOR) PRIVATE(
CMIC$1   I3X, IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 88920 IQ2=1,IJOUT
         SCRHOR(IQ2)=SCRHOR(IQ2)*BHOR(IQ2)
         OUTHOR(IQ2)=OUTHOR(IQ2)+SCRHOR(IQ2)
88920 CONTINUE
C          FINALLY THE UPPER RIGHT CONTRIBUTION
C*****  Code Expanded From Routine:  RDHGATHR
CMIC$ DO PARALLEL VECTOR
      DO 77004 I3X = 1, IJOUT
         SCRHOR(I3X) = FNGM(IUL(I3X)+1)
77004 CONTINUE
CMIC$ END PARALLEL
C*****  End of Code Expanded From Routine:  RDHGATHR
CMIC$ DO ALL VECTOR SHARED(IJOUT, SCRHOR, DHOR, OUTHOR) PRIVATE(IQ2)
      DO 88940 IQ2=1,IJOUT
         SCRHOR(IQ2)=SCRHOR(IQ2)*DHOR(IQ2)
         OUTHOR(IQ2)=OUTHOR(IQ2)+SCRHOR(IQ2)
88940 CONTINUE
C
      RETURN
      END
