      SUBROUTINE OUTLOLA
CFPP$ NOCONCUR R
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    OUTLOLA     OUTPUTS LONGITUDE AND LATITUDE
C   PRGMMR: N PHILLIPS       ORG: W/NMC22    DATE: 84-06-12
C
C ABSTRACT: OUTPUT DATA CARDS ARE EXAMINED TO SEE IF LONGITUDE
C   AND/OR LATITUDE ARE DESIRED AS OUTPUT FOR THE CURRENT OUTPUT
C   GRID.  THE FOLLOWING FORMULAS FOR A STEREOGRAPHIC PROJECTION
C   ARE USED.
C   .     ( X , Y )  =  D * ( COSINE LONGITUDE, SINE LONGITUDE )
C   .
C   .                     2 * EARTH RADIUS * COSINE(LATITUDE)
C   WHERE       D     =  --------------------------------------
C   .                        ( 1 + SINE(LATITUDE)  )
C   .
C   WHEN SOLVED FOR LONGITUDE, THE LONGITUDE VALUE IS THEN CORRECTED
C   TO GIVE GREENWICH LONGITUDE INSTEAD OF THAT FOR THE OUTPUT GRID.
C   .
C   BOTH OUTPUTS ARE IN DEGREES.  THE LONGITUDE VALUES RANGE FROM
C   0 TO 180 FOR LONGITUDES EAST OF GREENWICH, AND FROM 0 TO -180
C   FOR LONGITUDES WEST OF GREENWICH.
C   .
C PROGRAM HISTORY LOG:
C   85-06-12  N PHILLIPS
C   88-08-25  B SCHMIDT REVISED THE DOCBLOCK
C
C USAGE:  CALL OUTLOLA
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - OUTNULAB
C                  OUTPACK
C     LIBRARY:
C       COMMON   - COMBLANK
C                  COMCONST
C                  COMOUT
C
C REMARKS:
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES         MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----         ----------------------------------        ---------
C   XIPOLE,YJPOLE  GRID-POINT VALUES OF THE NORTH POLE.       COMMON
C   .
C   DNPEQOUT       NUMBER OF GRID INCREMENTS BETWEEN POLE     COMMON
C   .              AND EQUATOR.
C   .
C   DLAMOUT        LONGITUDE EASTWARD FROM GREENWICH OF THE   COMMON
C   .              POSITIVE X-AXIS OF THE OUTPUT GRID.
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES         MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----         ----------------------------------        ---------
C   ALL OUTPUT FROM THIS ROUTINE TAKES PLACE THROUGH CALLS
C   TO THE SUBROUTINES  OUTNULAB  AND OUTPACK
C   .
C   FOR OUTNULAB, THE FOLLOWING LABEL INFORMATION IS PREPARED.
C   .
C   LABSSUB1       = 0 (SURFACE TYPE IS IRRELEVANT)          COMMON
C   .
C   S1VALUE        = 0.E0                                    COMMON
C   .
C   LABQTYPE       =176 FOR LATITUDE, 177 FOR LONGITUDE.     COMMON
C   .
C   FOR OUTPACK THE FOLLOWING INFORMATION IS SUPPLIED.
C   .
C   S(MSOUT2)      THE ARRAY OF LATITUDE OR LONGITUDE       ARGUMENT
C   .
C   IJOUT          THE SIZE OF THE OUTPUT GRID              ARGUMENT
C   .
C   S(MSOUT1)      SCRATCH SPACE FOR PACKER CODE(SIZE IJOUT)ARGUMENT
C   .
C   DESCRIPT       20 CHARACTER STRING TO DESCRIBE OUTPUT   ARGUMENT
C   .
C   LABEL84        ARRAY IN COMOUT CONTAINING LABEL INFO.   ARGUMENT
C   .
C   IOUTUNIT       DISK UNIT NUMBER FOR PACKER TO WRITE ON. ARGUMENT
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C          DESCRIPTORS USED IN SR  OUTHORIZ
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
CER
      INTEGER IDGRBE(25)
C
      LOGICAL BITS,B1D,B2D
      DIMENSION S(IIJMAX),BITS(IIJMAX)
C
      EQUIVALENCE ( SCR(1,1), S(1), BITS(1) )
C
      DATA LABLAT/176/,LABLON /177/
C
      NCARLAT=0
      NCARLON=0
      DO 10 N=1,NOUTVBLS
      IF( LQTYPE(N) .NE. LABLAT ) GO TO 5
      NCARLAT=N
      GO TO 10
    5 IF( LQTYPE(N) .NE. LABLON ) GO TO 10
      NCARLON=N
   10 CONTINUE
C
      IDOLAT=0
      IF( NCARLAT .EQ. 0 ) GO TO 15
      IF( LEVELS(1,NCARLAT) .EQ. 1 ) IDOLAT=1
   15 IDOLON=0
      IF( NCARLON .EQ. 0 ) GO TO 20
      IF( LEVELS(1,NCARLON) .EQ. 1 ) IDOLON =1
   20 CONTINUE
C           RETURN IF THERE IS NO DEMAND
      IDO = IDOLAT + IDOLON
      IF( IDO .EQ. 0 ) RETURN
C
C      PUT XI = (X(I)-X(POLE) )/(2*RADIUS) IN ARRAY S(JSCR2(1) )
C
      A=(1.E0 - XIPOUT ) /DNPEQOUT
      B=1.E0 / DNPEQOUT
      DO 1001 IQ2 = 1, IMOUT
         S(JSCR2(1)+IQ2-1) = A + B*FLOAT(IQ2-1)
1001  CONTINUE
C
C          PUT A FULL GRID OF XI INTO S(JSCR2(2) ) AND A FULL GRID OF
C
C       ETA   = ( Y(J) -Y(POLE) ) /(2*RADIUS)   INTO S(JSCR2(3) )
C
      I2=JSCR2(2)-IMOUT
      I3=JSCR2(3)-IMOUT
      ETA=-YJPOUT/DNPEQOUT
      DO 30 J=1,JMOUT
      ETA=ETA+B
      I2=I2+IMOUT
      I3=I3+IMOUT
      DO 88890 IQ2=1,IMOUT
         S(I2+IQ2-1)=S(JSCR2(1)+IQ2-1)
         S(I3+IQ2-1)=ETA
88890 CONTINUE
   30 CONTINUE
C
C          PUT ETA**2 +XI**2 = RHO**2 IN S(JSCR2(1) ).
      DO 88910 IQ2=1,IJOUT
         S(JSCR2(4)+IQ2-1)=S(JSCR2(2)+IQ2-1)*S(JSCR2(2)+IQ2-1)
         S(JSCR2(1)+IQ2-1)=S(JSCR2(3)+IQ2-1)*S(JSCR2(3)+IQ2-1)
         S(JSCR2(1)+IQ2-1)=S(JSCR2(1)+IQ2-1)+S(JSCR2(4)+IQ2-1)
88910 CONTINUE
C
C          IS THE LATITUDE WANTED???
      IF( IDOLAT .NE. 1 ) GO TO 40
C
C         SINE OF LATITUDE TO S4D
      DO 88940 IQ2=1,IJOUT
         S(JSCR2(4)+IQ2-1)=1.E0+S(JSCR2(1)+IQ2-1)
         S(MSOUT2+IQ2-1)=1.E0-S(JSCR2(1)+IQ2-1)
         S(JSCR2(4)+IQ2-1)=S(MSOUT2+IQ2-1)/S(JSCR2(4)+IQ2-1)
88940 CONTINUE
C       PUT THE LATITUDE IN THE RESULT ARRAY S(MSOUT2)
      IRET=1
      IAD1=JSCR2(4)-1
      GO TO 100
C
   98 CONTINUE
C
C
      LABQTYPE=LABLAT
      LABSSUB1=0
      S1VALUE=0.E0
C
            CALL OUTNULAB
C
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IDGRBE(8) = 176
      IF(LABEL84(1).EQ.177) IDGRBE(8) = 177
      IDGRBE(9) =   1
      IDGRBE(10) =  0
      IDGRBE(11) =  0
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0
      IDGRBE(20) =  0
C
c     CALL OUTPACK(S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARLAT),
c    1 LABEL84,IOUTUNIT )
      CALL GRIBITN (S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARLAT),
     1 IDGRBE,IOUTGRIB,LABEL84 )
C
C          IS LONGITUDE DESIRED?????
   40 IF ( IDOLON .NE. 1 ) RETURN
C
C        GUARD AGAINST ZERO DISTANCE FROM THE POLE.
C          DISTANCE FROM POLE ON STEREOGRAPHIC GRID.
      DO 88970 IQ2=1,IJOUT
         S(JSCR2(4)+IQ2-1)=SQRT( S(JSCR2(1)+IQ2-1) )
88970 CONTINUE
C        SET B1D = 1 AWAY FROM POLE
      DO 88980 IQ2=1,IJOUT
         BITS(MB1+IQ2-1)=S(JSCR2(4)+IQ2-1).GE.0.0001E0
88980 CONTINUE
C        SINE OF GRID LONGITUDE TO S1D
      DO 88990 IQ2=1,IJOUT
         S(JSCR2(1)+IQ2-1)=0.E0
88990 CONTINUE
      DO 89000 IQ2=1,IJOUT
       IF ( BITS(MB1+IQ2-1) ) THEN
         S(JSCR2(1)+IQ2-1)=S(JSCR2(3)+IQ2-1)/S(JSCR2(4)+IQ2-1)
       END IF
89000 CONTINUE
C       GRID LONGITUDE(DEGREES) TO S5D
      IRET=2
      IAD1=JSCR2(1)-1
      GO TO 100
C
   99 CONTINUE
C
C         -90 .LE. ANGLE .LE. +90
C          BIT VECTOR FOR THE 2ND AND 3RD QUADRANTS
      DO 89010 IQ2=1,IJOUT
         BITS(MB1+IQ2-1)=S(JSCR2(2)+IQ2-1).LT.0.E0
89010 CONTINUE
C          BIT VECTOR FOR THE 3RD AND 4TH QUADRANTS
      DO 89020 IQ2=1,IJOUT
         BITS(MB2+IQ2-1)=S(JSCR2(3)+IQ2-1).LT.0.E0
89020 CONTINUE
C          CORRECT THE SECOND QUADRANT
      DO 89030 IQ2=1,IJOUT
       IF ( BITS(MB1+IQ2-1) .AND. .NOT.BITS(MB2+IQ2-1) ) THEN
         S(MSOUT2+IQ2-1)=180.E0-S(MSOUT2+IQ2-1)
       END IF
89030 CONTINUE
C          CORRECT THE THIRD QUADRANT
      DO 89040 IQ2=1,IJOUT
       IF ( BITS(MB1+IQ2-1) .AND. BITS(MB2+IQ2-1) ) THEN
         S(MSOUT2+IQ2-1)=-S(MSOUT2+IQ2-1)-180.E0
       END IF
89040 CONTINUE
C        CUT IS NOW ON THE NEGATIVE X-AXIS OF GRID.
C        CONVERT TO GEOGRAPHIC(GREENWICH) LONGITUDE
      DO 89050 IQ2=1,IJOUT
         S(MSOUT2+IQ2-1)=S(MSOUT2+IQ2-1)+DLAMOUT
89050 CONTINUE
C
C        MUST CORRECT ANY VALUES OUTSIDE OF + OR - 180.
C
      IF( DLAMOUT .LT. 0.E0 ) GO TO 50
C         MAYBE WE HAVE VALUES MORE THAN 180
      DO 89060 IQ2=1,IJOUT
         BITS(MB1+IQ2-1)=S(MSOUT2+IQ2-1).GT.180.E0
89060 CONTINUE
      DO 89070 IQ2=1,IJOUT
       IF ( BITS(MB1+IQ2-1) ) THEN
         S(MSOUT2+IQ2-1)=S(MSOUT2+IQ2-1)-360.E0
       END IF
89070 CONTINUE
      GO TO 60
C
C         MAYBE WE HAVE SOME VALUES LESS THAN -180
   50 CONTINUE
      DO 89080 IQ2=1,IJOUT
         BITS(MB1+IQ2-1)=S(MSOUT2+IQ2-1).LT.-180.E0
89080 CONTINUE
      DO 89090 IQ2=1,IJOUT
       IF ( BITS(MB1+IQ2-1) ) THEN
         S(MSOUT2+IQ2-1)=S(MSOUT2+IQ2-1)+360.E0
       END IF
89090 CONTINUE
C
   60 CONTINUE
      LABQTYPE=LABLON
      LABSSUB1=0
      S1VALUE=0.E0
C
               CALL OUTNULAB
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IDGRBE(8) = 177
      IDGRBE(9) =   1
      IDGRBE(10) =  0
      IDGRBE(11) =  0
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0
      IDGRBE(20) =  0
C
c     CALL OUTPACK(S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARLON),
c    1 LABEL84,IOUTUNIT )
      CALL GRIBITN (S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARLON),
     1 IDGRBE,IOUTGRIB,LABEL84 )
C
      RETURN
C
C------------------------------------------------------------------
C        COMPUTED GO TO ROUTINE TO GET ARCSINE
  100 CONTINUE
      IA=MSOUT2-1
      DO 105 N=1,IJOUT
      IA=IA+1
      IAD1=IAD1+1
      S(IA)=57.29578E0 * ASIN( S(IAD1) )
  105 CONTINUE
C
      GO TO ( 98, 99 ) , IRET
C
C------------------------------------------------------------
C
      END
