      SUBROUTINE OUTLIFT
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    OUTLIFT     COMPUTE LIFTED STABILITY INDEXES
C   PRGMMR: N PHILLIPS       ORG: W/NMC22    DATE: 84-02-01
C
C ABSTRACT: OUTPUT MENU CARDS ARE EXAMINED TO SEE IF THE LFM
C   .       AND/OR BEST LIFTED INDEX IS DESIRED. FOR EACH OF THESE
C   .       (WHEN DESIRED) THE FOLLOWING PROCEDURE IS PERFORMED.
C   1)  FOR EACH OF THE SIGMA LAYERS FROM K=1 THROUGH K=KTOP,
C   .   A)  MULTIPLY THE SPECIFIC HUMIDITY BY THE FACTOR
C   .       ( 1. + SATDEL ), AND LIFT THIS MODIFIED
C   .       PARCEL TO ITS LIFTING CONDENSATION LEVEL.
C   .   B)  CONTINUE TO LIFT IT MOIST-ADIABATICALLY TO THE PRESSURE
C   .       VALUE GIVEN BY THE CONSTANT  PLIFTTO.
C   .   C)  DETERMINE THE TEMPERATURE OF THE PARCEL AT THIS LEVEL.
C   2)  WHEN PARCELS FROM MORE THAN ONE LAYER ARE CONSIDERED(KTOP .GT.
C   .   1 ), SAVE THE WARMEST SUCH TEMPERATURE FOR EACH COLUMN.
C   3)  INTERPOLATE VERTICALLY ( IN Z=-LOG(PRESS) ) TO GET THE VALUE
C   .     OF THE ORIGINAL COLUMN TEMPERATURE AT PRESSURE  PLIFTTO.
C   4)  SEND THE RESULTS OF STEP 3 MINUS STEP 2 TO THE PACKER CODE.
C   .     ( LABEL AND SCALING INFORMATION IS SET IN THE
C   .       OUTERMOST LOOP FOR TWO SELECTIONS OF KTOP.  )
C   .
C   FOR THE 'BEST LIFTED INDEX', REFER TO THE OUTLINE GIVEN UNDER
C   'BEST LIFTED INDEX' ON PAGE 2 OF N.W.S.  TECH. PROC. BULL. 207,
C   SEPT. 1977.
C   .
C PROGRAM HISTORY LOG:
C   84-02-01  N PHILLIPS
C   84-11-01  N PHILLIPS REVISED SUBROUTINE
C   86-03-11  N PHILLIPS REVISED SINCE SATDEL WAS PUT IN COMCONST
C
C USAGE:    CALL OUTLIFT
C   OUTPUT FILES:
C     FT06F001 - FOR PRINTOUT
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - DUMPBIT
C                  PRT
C                  OUTNULAB
C                  OUTPACK
C     LIBRARY:
C       COMMON   - COMBLANK
C                  COMCONST
C                  COMOUT
C
C REMARKS:
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES          MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----          ----------------------------------        ---------
C   TEMPERATURE     (DEG K ) ON OUTPUT GRID (SIGMA)            COMMON
C                   IN  S( JSCR3OUT(1) )
C   .
C   Z =-LOG(PRESS)  ON OUTPUT GRID (SIGMA) IN S( JSCR3OUT(2) ) COMMON
C   .
C   SPECIFIC        ON OUTPUT GRID (SIGMA) IN S( JSCR3OUT(3) ) COMMON
C   HUMIDITY
C   .
C   SURFACE PRESS.  ON OUTPUT GRID IN S( MHOUT)                COMMON
C   .
C   SATDEL          PARAMETER DESCRIBING RANGE OF SATURATION   COMMON
C   .               IN A GRID BOX.
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES          MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----          ----------------------------------        ---------
C   .
C   ALL OUTPUT FROM THIS ROUTINE TAKES PLACE THROUGH CALLS
C   TO THE SUBROUTINES  OUTNULAB  AND OUTPACK
C   .
C   FOR OUTNULAB, THE FOLLOWING O.N. 84 LABEL INFORMATION IS PREPARED
C   .
C   LABQTYPE       = VARIABLE TYPE                           COMMON
C   .
C   LABSSUB1 AND   =  TYPE OF VARIABLE WHOSE CONSTANT        COMMON
C   LABSSUB2          VALUE DEFINES THE 'OUTPUT' SURFACES.
C   .
C   S1VALUE        =  VALUES OF LABSSUB1 AND LABSSUB2        COMMON
C   S2VALUE
C   .
C   LABMLDIF       = 2 FOR LEVEL DIFFERENCE ENTRY OF O.N.84. COMMON
C   .
C   FOR OUTPACK THE FOLLOWING INFORMATION IS SUPPLIED.
C   .
C   S(I6)          THE ARRAY OF LIFTED INDEX(SIZE=IJOUT)    ARGUMENT
C   .
C   IJOUT          THE SIZE OF THE OUTPUT GRID(SIZE=IJOUT)  ARGUMENT
C   .
C   S(I1)          SCRATCH SPACE FOR PACKER CODE(SIZE=IJOUT)ARGUMENT
C   .
C   DESCRIPT(NCARD)20 CHARACTER STRING TO DESCRIBE OUTPUT   ARGUMENT
C   .
C   LABEL84        ARRAY IN COMOUT CONTAINING LABEL INFO.   ARGUMENT
C   .
C   IOUTUNIT       DISK UNIT NUMBER FOR PACKER TO WRITE ON. ARGUMENT
C   .
C   ***NOTE-- LABMLDIF, LABSSUB2 AND S2VALUE ARE RESTORED TO THEIR
C   .         NORMAL ZERO VALUES BEFORE THE RETURN TO SR  OUTPUT
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:52:11  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      REAL R1S,R2S,R3S
C
C               COMPUTE LIFTED STABILITY INDEXES, USING
C               THE MOST BUOYANT PARCEL FROM ONE OR MORE
C               OF THE BOTTOM SIGMA LAYERS IN EACH COLUMN
C               OF THE OUTPUT GRID.
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
Cer
      INTEGER IDGRBE(25)
C
      LOGICAL BITS,BIT1D,BIT2D
C
C          ARRAYS FOR EQUIVALENCED SCRATCH SPACE
      DIMENSION S(INSUMG),FNGM(INSUMG),IN(INSUMG),BITS(INSUMG)
C
      EQUIVALENCE (SCR(1,1), S(1), FNGM(1), IN(1), BITS(1) )
C
C          CONSTANTS FOR COMPUTING TEMPERATURE AT LIFTING
C          CONDENSATION LEVEL.
      INTEGER I,I1X(50),NHDG,N2,N1,IQ2W1X,LEN,M,I2X(50),NHDG1X,N21X,N11X
     .,IQ2W2X,LEN1X,M1X
      REAL COFD1,COFD2,COFD3,COFD4,COFN1,COFN2,COFN3
      PARAMETER (COFD1 = 1., COFD2 = 5.44053037, COFD3 = 2.27693825, 
     1   COFD4 = -0.0869930591, COFN1 = 0.34757549, COFN2 = 4.36732956, 
     2   COFN3 = 3.91557032)
      DATA CL1/0.9544425E0/,CL2/0.967772E-3/,
     1     CL3/-0.710321E-3/,CL4/-0.270742E-5/
C
C
C          THE PRESSURE SURFACE(UNITS=100CBS) TO WHICH THE
C          PARCELS ARE LIFTED.
      DATA PLIFTTO/.5E0/
C
C
C           COUNT FOR PRINTING ERROR STOP INFORMATION
      DATA IERROR/0/
C
C          SCRATCH ARRAY ADDRESSES
      I1=JSCR2(1)
      I2=JSCR2(2)
      I3=JSCR2(3)
      I4=JSCR2(4)
      I5=JSCR2(5)
      I6=JSCR2(6)
      I7=JSCR2(7)
C
C         THE OUTERMOST LOOP IS ON THE TWO TYPES OF LIFTED INDEX
C   FOR LIFTIN  = 1, THE PRODUCT WILL BE THE STANDARD 'LFM' INDEX.
C   FOR LIFTIN  = 2, THE PRODUCT WILL BE THE 'BEST LIFTED INDEX'.
C
C          ONLY PARCELS FROM BOTTOM LAYER FOR LFM INDEX
      KTOP = 1
C         TEMPERATURE ORIGIN FACTOR
      TSCALE = 273.16E0
C         LFM INDEX LABEL INFORMATION
      LABQTYPE = 112
      LABSSUB1 = 8
      LABSSUB2 = 129
      S1VALUE = 500.E0
      S2VALUE = 0.E0
      LABMLDIF = 2
C
C
      DO 1000 LIFTIN = 1,2
C
C
C           IS THIS PRODUCT DESIRED,,,,,
        DO 10 N=1,NOUTVBLS
        NCARD = N
        IF(LQTYPE(N).EQ.LABQTYPE .AND. LSTYPE(N).EQ.LABSSUB1) GO TO 15
   10   CONTINUE
C
C              NO DATA CARD PRESENT FOR THIS PRODUCT
      GO TO 999
C
   15  CONTINUE
C              CHECK FOR A ONE IN LEVELS(NCARD)
      ISUM = 0
      DO 1001 IQ2 = 1 , LMOUT
         ISUM = ISUM + LEVELS(IQ2,NCARD)
1001  CONTINUE
C
      IF( ISUM .LE. 0 ) GO TO 999
C
C           YES, THIS PRODUCT IS WANTED
C
C
C          SOME CONSTANTS
      RGASD=287.05E0
      RGASV=461.5E0
      CSUBP=1005.E0
      EPS=RGASD/RGASV
      CSATDEL=(1.E0 + SATDEL)
C          CONSTANTS TO COMPUTE LATENT HEAT / CSUBP .
C     LAT. HT. / CSUB P =  C5  + C6 * TEMPERATURE.
C
      T3=273.16E0
      CPV=1876.5E0
      CL=4187.E0
      EL3=2.501E6
      C6=(CPV-CL)/CSUBP
      C5=(EL3/CSUBP)-C6*T3
C          NEED  (PLIFTTO**KAPPA)
      Z1=PLIFTTO
      Z2=RGASD/CSUBP
      Z3=Z1**Z2
      ZZ3 =Z3
C
C          PUT SURFACE PRESSURE TO KAPPA POWER IN S(MSOUT2).
C*****  Code Expanded From Routine:  P2KAP
CMIC$ DO ALL VECTOR IF (ABS(MHOUT-MSOUT2).GE.IJOUT .OR. MHOUT-MSOUT2.EQ.
CMIC$1   0) SHARED(IJOUT, MHOUT, MSOUT2, S) PRIVATE(I)
      DO 77052 I = 1, IJOUT
         S(I+MSOUT2-1) = (0.34757549+S(I+MHOUT-1)*(4.36732956+S(I+MHOUT-
     1      1)*3.91557032))/(1.+S(I+MHOUT-1)*(5.44053037+S(I+MHOUT-1)*(
     2      2.27693825+S(I+MHOUT-1)*(-0.0869930591))))
77052 CONTINUE
C*****  End of Code Expanded From Routine:  P2KAP
C          REPLACE THIS WITH ITS RECIPROCAL
CMIC$ DO ALL VECTOR SHARED(IJOUT, MSOUT2, S) PRIVATE(IQ2W6E)
      DO 88890 IQ2W6E=1,IJOUT
         S(MSOUT2+IQ2W6E-1)=1.E0/S(MSOUT2+IQ2W6E-1)
88890 CONTINUE
C
C          ARRAY TO ACCUMULATE THE WARMEST PARCEL TEMP AT PLIFTTO
C
C          ENTER THE LOOP ON ORIGINATING LAYER OF PARCEL
      DO 400 K=1,KTOP
C          ADDRESSES FOR T AND Q IN LAYER K
      IADT=JSCR3OUT(1) + (K-1)*IJOUT
      IADQ=JSCR3OUT(3) + (K-1)*IJOUT
C          PUT SAT VAP PRESS (CBS) IN S(I1)
C          SAT VAP PRESS = (P * Q ) / (EPS +(1-EPS)*Q ),P IN CBS.
CMIC$ DO ALL VECTOR IF (ABS(IADQ-I3).GE.IJOUT .OR. IADQ-I3.EQ.0) SHARED(
CMIC$1   IJOUT, CSATDEL, IADQ, I3, S) PRIVATE(IQ2W6E)
      DO 88900 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=CSATDEL*S(IADQ+IQ2W6E-1)
88900 CONTINUE
      C1=(100.E0/(1.E0-EPS) ) * PRESS(K)
CMIC$ DO ALL VECTOR IF ((ABS(I3-I1).GE.IJOUT .OR. I3-I1.EQ.0) .AND. (
CMIC$1   ABS(MHOUT-I1).GE.IJOUT .OR. MHOUT-I1.EQ.0)) SHARED(IJOUT, C1, 
CMIC$2   I3, MHOUT, I1, S) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E=1,IJOUT
         S(I1+IQ2W6E-1)=C1*S(I3+IQ2W6E-1)*S(MHOUT+IQ2W6E-1)
88910 CONTINUE
      C1=EPS/(1.E0-EPS)
CMIC$ DO ALL VECTOR IF (ABS(I1-I3).GE.IJOUT .OR. I1-I3.EQ.0) SHARED(
CMIC$1   IJOUT, I1, C1, I3, S) PRIVATE(IQ2W6E)
      DO 88920 IQ2W6E=1,IJOUT
         S(I1+IQ2W6E-1)=S(I1+IQ2W6E-1)/
     *               (C1+S(I3+IQ2W6E-1))
88920 CONTINUE
C          GET DEWPOINT TEMP INTO ARRAY S(I2)
      CALL DEWPOINT(S(I1), S(I2), IJOUT)
C
C          DEWPOINT DEPRESSION INTO S(I1)
CMIC$ DO ALL VECTOR IF ((ABS(IADT-I1).GE.IJOUT .OR. IADT-I1.EQ.0) .AND. 
CMIC$1   (ABS(I2-I1).GE.IJOUT .OR. I2-I1.EQ.0)) SHARED(IJOUT, IADT, I2, 
CMIC$2   I1, S) PRIVATE(IQ2W6E)
      DO 88940 IQ2W6E=1,IJOUT
         S(I1+IQ2W6E-1)=S(IADT+IQ2W6E-1)-S(I2+IQ2W6E-1)
88940 CONTINUE
C          TEMP AT LIFTING COND. LVL. INTO S(I1)
CMIC$ DO ALL VECTOR IF ((ABS(IADT-I3).GE.IJOUT .OR. IADT-I3.EQ.0) .AND. 
CMIC$1   (ABS(IADT-I1).GE.IJOUT .OR. IADT-I1.EQ.0) .AND. (ABS(I3-I1).GE.
CMIC$2   IJOUT .OR. I3-I1.EQ.0)) SHARED(IJOUT, CL3, CL4, IADT, I3, I1, 
CMIC$3   CL2, CL1, S) PRIVATE(IQ2W6E)
      DO 88950 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=CL3+CL4*S(IADT+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(I1+IQ2W6E-1)*S(I3+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(I3+IQ2W6E-1)+CL2*S(IADT+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(I1+IQ2W6E-1)*(CL1+S(I3+IQ2W6E-1))
         S(I1+IQ2W6E-1)=S(IADT+IQ2W6E-1)-S(I3+IQ2W6E-1)
88950 CONTINUE
C
C          GET PRESSURE(100CBS) INTO ARRAY S(I2)
CMIC$ DO ALL VECTOR IF ((ABS(I1-I3).GE.IJOUT .OR. I1-I3.EQ.0) .AND. (
CMIC$1   ABS(IADT-I3).GE.IJOUT .OR. IADT-I3.EQ.0)) SHARED(IJOUT, I1, 
CMIC$2   IADT, I3, S) PRIVATE(IQ2W6E)
      DO 89000 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=ALOG(S(I1+IQ2W6E-1)/S(IADT+IQ2W6E-1))
89000 CONTINUE
      C1=PRESS(K)
CMIC$ DO ALL VECTOR IF (ABS(MHOUT-I4).GE.IJOUT .OR. MHOUT-I4.EQ.0)
CMIC$1    SHARED(IJOUT, K, MHOUT, I4, PRESS, S) PRIVATE(IQ2W6E)
      DO 89020 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=ALOG(PRESS(K)*S(MHOUT+IQ2W6E-1))
89020 CONTINUE
      C1=CSUBP/RGASD
C          LOG OF PRESS(LCL) INTO S(I4)
CMIC$ DO ALL VECTOR IF (ABS(I4-I3).GE.IJOUT .OR. I4-I3.EQ.0) SHARED(
CMIC$1   IJOUT, I4, C1, I3, S) PRIVATE(IQ2W6E)
      DO 89040 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=S(I4+IQ2W6E-1)+C1*S(I3+IQ2W6E-1)
89040 CONTINUE
C
CMIC$ DO ALL VECTOR IF (ABS(I4-I2).GE.IJOUT .OR. I4-I2.EQ.0) SHARED(
CMIC$1   IJOUT, I4, I2, S) PRIVATE(IQ2W6E)
      DO 89050 IQ2W6E=1,IJOUT
         S(I2+IQ2W6E-1)=EXP( S(I4+IQ2W6E-1) )
89050 CONTINUE
C          S(I2) NOW CONTAINS PRESS(100 CBS) AT LCL.
C          GET SATN MIXING RATIO AT LCL INTO S3D
      C1=1.E0/CSATDEL
CMIC$ DO ALL VECTOR IF (ABS(IADQ-I3).GE.IJOUT .OR. IADQ-I3.EQ.0) SHARED(
CMIC$1   IJOUT, C1, IADQ, I3, S) PRIVATE(IQ2W6E)
      DO 89060 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=C1-S(IADQ+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(IADQ+IQ2W6E-1)/S(I3+IQ2W6E-1)
89060 CONTINUE
C          SAT VAP PRESS(100 CBS) INTO S4D
CMIC$ DO ALL VECTOR IF ((ABS(I3-I4).GE.IJOUT .OR. I3-I4.EQ.0) .AND. (
CMIC$1   ABS(I3-I5).GE.IJOUT .OR. I3-I5.EQ.0) .AND. (ABS(I4-I2).GE.IJOUT
CMIC$2    .OR. I4-I2.EQ.0) .AND. (ABS(I4-I5).GE.IJOUT .OR. I4-I5.EQ.0)
CMIC$3    .AND. (ABS(I2-I5).GE.IJOUT .OR. I2-I5.EQ.0)) SHARED(IJOUT, EPS
CMIC$4   , I3, I4, I2, I5, S) PRIVATE(IQ2W6E)
      DO 89080 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=EPS+S(I3+IQ2W6E-1)
         S(I5+IQ2W6E-1)=S(I2+IQ2W6E-1)*S(I3+IQ2W6E-1)
         S(I4+IQ2W6E-1)=S(I5+IQ2W6E-1)/S(I4+IQ2W6E-1)
89080 CONTINUE
C         PRESS(DRY) INTO S4D
CMIC$ DO ALL VECTOR IF (ABS(I2-I4).GE.IJOUT .OR. I2-I4.EQ.0) SHARED(
CMIC$1   IJOUT, I2, I4, S) PRIVATE(IQ2W6E)
      DO 89110 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=S(I2+IQ2W6E-1)-S(I4+IQ2W6E-1)
89110 CONTINUE
C          IDENTIFY POINTS WITH PRESS(LCL) .GT. PLIFTTO
C          (THESE WILL BE SATURATED AT P=PLIFTTO)
CMIC$ DO ALL VECTOR SHARED(IJOUT, I2, PLIFTTO, MB1, S, BITS) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89120 IQ2W6E=1,IJOUT
         BITS(MB1+IQ2W6E-1)=S(I2+IQ2W6E-1).GT.PLIFTTO
89120 CONTINUE
C
C          COMPUTE
C           F = LOG OF ROSSBY'S THETAE AT THE LCL
C          AND PUT IT (FINALLY) IN S(I1).
C               PUT (LATENT HEAT/ CSUBP ) INTO S5D.
CMIC$ DO ALL VECTOR IF (ABS(I1-I5).GE.IJOUT .OR. I1-I5.EQ.0) SHARED(
CMIC$1   IJOUT, C5, C6, I1, I5, S) PRIVATE(IQ2W6E)
      DO 89130 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=C5+C6*S(I1+IQ2W6E-1)
89130 CONTINUE
C          TIMES SAT MIXING RATIO AND DVDED BY T(LCL)
CMIC$ DO ALL VECTOR IF ((ABS(I5-I3).GE.IJOUT .OR. I5-I3.EQ.0) .AND. (
CMIC$1   ABS(I5-I1).GE.IJOUT .OR. I5-I1.EQ.0)) SHARED(IJOUT, I5, I3, I1
CMIC$2   , S) PRIVATE(IQ2W6E)
      DO 89140 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=S(I5+IQ2W6E-1)*S(I3+IQ2W6E-1)
         S(I5+IQ2W6E-1)=S(I5+IQ2W6E-1)/S(I1+IQ2W6E-1)
89140 CONTINUE
C          ADD LOG OF T(LCL)
CMIC$ DO ALL VECTOR IF ((ABS(I1-I2).GE.IJOUT .OR. I1-I2.EQ.0) .AND. (
CMIC$1   ABS(I1-I5).GE.IJOUT .OR. I1-I5.EQ.0) .AND. (ABS(I2-I5).GE.IJOUT
CMIC$2    .OR. I2-I5.EQ.0)) SHARED(IJOUT, I1, I2, I5, S) PRIVATE(IQ2W6E)
      DO 89160 IQ2W6E=1,IJOUT
         S(I2+IQ2W6E-1)=ALOG( S(I1+IQ2W6E-1) )
         S(I5+IQ2W6E-1)=S(I5+IQ2W6E-1)+S(I2+IQ2W6E-1)
89160 CONTINUE
C         FINALLY SUBTRACT KAPPA * LOG OF PRESS(DRY)
CMIC$ DO ALL VECTOR IF (ABS(I4-I2).GE.IJOUT .OR. I4-I2.EQ.0) SHARED(
CMIC$1   IJOUT, I4, I2, S) PRIVATE(IQ2W6E)
      DO 89180 IQ2W6E=1,IJOUT
         S(I2+IQ2W6E-1)=ALOG( S(I4+IQ2W6E-1) )
89180 CONTINUE
      C1=RGASD/CSUBP
CMIC$ DO ALL VECTOR IF ((ABS(I5-I1).GE.IJOUT .OR. I5-I1.EQ.0) .AND. (
CMIC$1   ABS(I2-I1).GE.IJOUT .OR. I2-I1.EQ.0)) SHARED(IJOUT, I5, C1, I2
CMIC$2   , I1, S) PRIVATE(IQ2W6E)
      DO 89190 IQ2W6E=1,IJOUT
         S(I1+IQ2W6E-1)=S(I5+IQ2W6E-1)-C1*S(I2+IQ2W6E-1)
89190 CONTINUE
C
C          S1D NOW CONTAINS THE PARCEL VALUE OF LOG(THETAE)
C     S2D,S3D,,,,,,,,S7D ARE NOW FREE
C
C          BUT WE IMMEDIATELY ASSIGN S2D FOR THE TEMPERATURE AT
C          P=PLIFTTO FOR THIS BATCH OF PARCELS.
C
C          FIRST FILL UP S2D  WITH DRY-ADIABATIC VALUES
      C1=ZZ3 / (2.E0 * PR(K) )
CMIC$ DO ALL VECTOR IF ((ABS(MSOUT2-I2).GE.IJOUT .OR. MSOUT2-I2.EQ.0)
CMIC$1    .AND. (ABS(IADT-I2).GE.IJOUT .OR. IADT-I2.EQ.0)) SHARED(IJOUT
CMIC$2   , C1, MSOUT2, IADT, I2, S) PRIVATE(IQ2W6E)
      DO 89200 IQ2W6E=1,IJOUT
         S(I2+IQ2W6E-1)=C1*S(MSOUT2+IQ2W6E-1)*S(IADT+IQ2W6E-1)
89200 CONTINUE
C          (THESE WILL NOT CHANGE FOR PARCELS WITH P(LCL) .LT. PLIFTTO )
C
C     NOW ENTER THE NEWTON-RAPHSON ITERATION TO GET PARCEL TEMPERATURE
C          AT THE PRESSURE PLIFTTO.
C          THE NUMBER OF ITERATION CYCLES BEFORE CONVERGENCE TEST.
      NTEST=3
C          THE NUMBER OF CONVERGENCE TESTS ALLOWED
      NCONV=10
C          THE CONVERGENCE CRITERION
      TCRIT=0.1E0
C
        DO 200 NOUTER=1,NCONV
          DO 100 NINNER=1,NTEST
C          COMPUTE LOG(THETAE) USING PLIFTTO AND THE TEMP IN S2D.
C          DO THIS IN S3D. FIRST THE LOG OF THE TEMPERATURE
CMIC$ DO ALL VECTOR IF (ABS(I2-I3).GE.IJOUT .OR. I2-I3.EQ.0) SHARED(
CMIC$1   IJOUT, I2, I3, S) PRIVATE(IQ2W6E)
      DO 89210 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=ALOG( S(I2+IQ2W6E-1) )
89210 CONTINUE
C          SAT VAP PRESS(CBS) INTO S4D
      CALL VAPTAB( S(I2), S(I4), IJOUT, 1 )
C
C         THE DRY PRESSURE(100 CBS) INTO S6D
CMIC$ DO ALL VECTOR IF (ABS(I4-I6).GE.IJOUT .OR. I4-I6.EQ.0) SHARED(
CMIC$1   IJOUT, PLIFTTO, I4, I6, S) PRIVATE(IQ2W6E)
      DO 89220 IQ2W6E=1,IJOUT
         S(I6+IQ2W6E-1)=PLIFTTO-.01E0*S(I4+IQ2W6E-1)
89220 CONTINUE
C          SUBTRACT KAPPA TIMES THE LOG( PRESS(DRY) )
CMIC$ DO ALL VECTOR IF (ABS(I6-I5).GE.IJOUT .OR. I6-I5.EQ.0) SHARED(
CMIC$1   IJOUT, I6, I5, S) PRIVATE(IQ2W6E)
      DO 89230 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=ALOG( S(I6+IQ2W6E-1) )
89230 CONTINUE
          C1=-RGASD/CSUBP
CMIC$ DO ALL VECTOR IF (ABS(I3-I5).GE.IJOUT .OR. I3-I5.EQ.0) SHARED(
CMIC$1   IJOUT, I3, C1, I5, S) PRIVATE(IQ2W6E)
      DO 89240 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=S(I3+IQ2W6E-1)+C1*S(I5+IQ2W6E-1)
89240 CONTINUE
C          LATENT HEAT/CSUBP INTO S5D
CMIC$ DO ALL VECTOR IF (ABS(I2-I5).GE.IJOUT .OR. I2-I5.EQ.0) SHARED(
CMIC$1   IJOUT, C5, C6, I2, I5, S) PRIVATE(IQ2W6E)
      DO 89250 IQ2W6E=1,IJOUT
         S(I5+IQ2W6E-1)=C5+C6*S(I2+IQ2W6E-1)
89250 CONTINUE
C          SATN MIXING RATIO INTO S4D
CMIC$ DO ALL VECTOR IF (ABS(I4-I6).GE.IJOUT .OR. I4-I6.EQ.0) SHARED(
CMIC$1   IJOUT, I4, I6, S) PRIVATE(IQ2W6E)
      DO 89260 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=S(I4+IQ2W6E-1)/S(I6+IQ2W6E-1)
89260 CONTINUE
          C1=0.01E0 * EPS
CMIC$ DO ALL VECTOR SHARED(IJOUT, C1, I4, S) PRIVATE(IQ2W6E)
      DO 89270 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=C1*S(I4+IQ2W6E-1)
89270 CONTINUE
C             ADD ( L* M.RATIO ) / (T * CSUBP ) TO S3D
CMIC$ DO ALL VECTOR IF ((ABS(I4-I7).GE.IJOUT .OR. I4-I7.EQ.0) .AND. (
CMIC$1   ABS(I4-I3).GE.IJOUT .OR. I4-I3.EQ.0) .AND. (ABS(I5-I7).GE.IJOUT
CMIC$2    .OR. I5-I7.EQ.0) .AND. (ABS(I5-I3).GE.IJOUT .OR. I5-I3.EQ.0)
CMIC$3    .AND. (ABS(I7-I2).GE.IJOUT .OR. I7-I2.EQ.0) .AND. (ABS(I7-I3)
CMIC$4   .GE.IJOUT .OR. I7-I3.EQ.0) .AND. (ABS(I2-I3).GE.IJOUT .OR. I2-
CMIC$5   I3.EQ.0)) SHARED(IJOUT, I4, I5, I7, I2, I3, S) PRIVATE(IQ2W6E)
      DO 89280 IQ2W6E=1,IJOUT
         S(I7+IQ2W6E-1)=S(I4+IQ2W6E-1)*S(I5+IQ2W6E-1)
         S(I7+IQ2W6E-1)=S(I7+IQ2W6E-1)/S(I2+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(I3+IQ2W6E-1)+S(I7+IQ2W6E-1)
89280 CONTINUE
C          SUBTRACT THE PARCELS ORIGINAL VALUE OF LOG(THETAE)
C          FROM THE TENTATIVE VALUE AT PLIFTTO JUST COMPUTED IN S3D.
CMIC$ DO ALL VECTOR IF (ABS(I3-I1).GE.IJOUT .OR. I3-I1.EQ.0) SHARED(
CMIC$1   IJOUT, I3, I1, S) PRIVATE(IQ2W6E)
      DO 89310 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=S(I3+IQ2W6E-1)-S(I1+IQ2W6E-1)
89310 CONTINUE
C          NOW COMPUTE T**3 TIMES THE T DERIVATIVE OF LOG(THETAE)
C          AND PUT IT INTO S4D
CMIC$ DO ALL VECTOR IF (ABS(I4-I6).GE.IJOUT .OR. I4-I6.EQ.0) SHARED(
CMIC$1   IJOUT, I4, I6, S) PRIVATE(IQ2W6E)
      DO 89320 IQ2W6E=1,IJOUT
         S(I6+IQ2W6E-1)=S(I4+IQ2W6E-1)/S(I6+IQ2W6E-1)
89320 CONTINUE
          C1=EPS*( CSUBP/RGASD ) * PLIFTTO
CMIC$ DO ALL VECTOR IF ((ABS(I6-I5).GE.IJOUT .OR. I6-I5.EQ.0) .AND. (
CMIC$1   ABS(I6-I4).GE.IJOUT .OR. I6-I4.EQ.0) .AND. (ABS(I6-I2).GE.IJOUT
CMIC$2    .OR. I6-I2.EQ.0) .AND. (ABS(I5-I4).GE.IJOUT .OR. I5-I4.EQ.0)
CMIC$3    .AND. (ABS(I4-I2).GE.IJOUT .OR. I4-I2.EQ.0)) SHARED(IJOUT, C1
CMIC$4   , I6, I5, C6, I4, I2, S) PRIVATE(IQ2W6E)
      DO 89330 IQ2W6E=1,IJOUT
         S(I6+IQ2W6E-1)=C1*S(I6+IQ2W6E-1)*S(I5+IQ2W6E-1)
         S(I6+IQ2W6E-1)=S(I6+IQ2W6E-1)*S(I5+IQ2W6E-1)
         S(I4+IQ2W6E-1)=C6*S(I4+IQ2W6E-1)
         S(I4+IQ2W6E-1)=S(I2+IQ2W6E-1)*(1.E0+S(I4+IQ2W6E-1))
         S(I4+IQ2W6E-1)=S(I4+IQ2W6E-1)*S(I2+IQ2W6E-1)
         S(I4+IQ2W6E-1)=S(I4+IQ2W6E-1)+S(I6+IQ2W6E-1)
89330 CONTINUE
C
C          COMPUTE THE DESIRED CHANGE IN T IN S3D
CMIC$ DO ALL VECTOR IF ((ABS(I2-I3).GE.IJOUT .OR. I2-I3.EQ.0) .AND. (
CMIC$1   ABS(I3-I4).GE.IJOUT .OR. I3-I4.EQ.0)) SHARED(IJOUT, I2, I3, I4
CMIC$2   , S) PRIVATE(IQ2W6E)
      DO 89390 IQ2W6E=1,IJOUT
         S(I3+IQ2W6E-1)=-S(I2+IQ2W6E-1)*S(I3+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(I3+IQ2W6E-1)*S(I2+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(I3+IQ2W6E-1)*S(I2+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(I3+IQ2W6E-1)/S(I4+IQ2W6E-1)
89390 CONTINUE
C          ADD THIS CORRECTION TO T(PLIFTTO) AT POINTS WHOSE
C          PRESS(LCL) WAS GREATER THAN PLIFTTO
CMIC$ DO ALL VECTOR IF (ABS(I2-I3).GE.IJOUT .OR. I2-I3.EQ.0) SHARED(
CMIC$1   IJOUT, MB1, I2, I3, BITS, S) PRIVATE(IQ2W6E)
      DO 89430 IQ2W6E=1,IJOUT
       IF ( BITS(MB1+IQ2W6E-1) ) THEN
         S(I2+IQ2W6E-1)=S(I2+IQ2W6E-1)+S(I3+IQ2W6E-1)
       END IF
89430 CONTINUE
C
C          END OF AN INDIVIDUAL ITERATION
  100    CONTINUE
C           FINISHED NTEST ITERATIONS,, HAVE WE CONVERGED???
CMIC$ DO ALL VECTOR IF (ABS(I3-I4).GE.IJOUT .OR. I3-I4.EQ.0) SHARED(
CMIC$1   IJOUT, I3, I4, S) PRIVATE(IQ2W6E)
      DO 89440 IQ2W6E=1,IJOUT
         S(I4+IQ2W6E-1)=ABS( S(I3+IQ2W6E-1) )
89440 CONTINUE
        CMAX = -1.E+35
CMIC$ PARALLEL SHARED(IJOUT, MB1, CMAX, I4, BITS, S) PRIVATE(IQ2, R1S)
      R1S = CMAX
CMIC$ DO PARALLEL VECTOR
      DO 7001 IQ2 = 1, IJOUT
         IF (BITS(MB1+IQ2-1)) R1S = AMAX1(R1S,S(I4+IQ2-1))
 7001 CONTINUE
CMIC$ GUARD
      CMAX = AMAX1(CMAX,R1S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
        IF( CMAX .LE. TCRIT ) GO TO 300
C          NEED MORE ITERATIONS
  200   CONTINUE
C
C      -----------------PROBLEM------------------------------
C
C          NEEDED MORE ITERATIONS THAN ALLOWED
C
      PRINT 210,NTEST,NCONV,CMAX,TCRIT,LIFTIN
  210 FORMAT(1H0,2X,'****** IN SR OUTLIFT, DID NOT GET CONVERGENCE.',
     1 '  NTEST,NCONV,CMAX,TCRIT=',2I6,2E14.6,'LIFTIN=',I4)
      PRINT 211
  211 FORMAT(1H ,2X,'  WILL ABORT THIS OUTPUT OF LIFTED INDEX')
C
C                  GO TO END OF LOOP ON LIFTIN
      GO TO 999
C
C------------------END OF PROBLEM TREATMENT--------------------
C
C
  300 CONTINUE
C
C          SAVE THE WARMEST SET OF PARCEL TEMPERATURES
      IF( K .GT. 1 ) GO TO 350
C          FIRST PARCEL LAYER, USE TEMPS IN S2D AS IS.
CMIC$ DO ALL VECTOR IF (ABS(I2-MSOUT1).GE.IJOUT .OR. I2-MSOUT1.EQ.0)
CMIC$1    SHARED(IJOUT, I2, MSOUT1, S) PRIVATE(IQ2W6E)
      DO 89450 IQ2W6E=1,IJOUT
         S(MSOUT1+IQ2W6E-1)=S(I2+IQ2W6E-1)
89450 CONTINUE
      GO TO 400
C
  350 CONTINUE
CMIC$ DO ALL VECTOR SHARED(IJOUT, I2, MSOUT1, MB1, S, BITS) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89460 IQ2W6E=1,IJOUT
         BITS(MB1+IQ2W6E-1)=S(I2+IQ2W6E-1).GT.S(MSOUT1+IQ2W6E-1)
89460 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I2-MSOUT1).GE.IJOUT .OR. I2-MSOUT1.EQ.0)
CMIC$1    SHARED(IJOUT, MB1, I2, MSOUT1, BITS, S) PRIVATE(IQ2W6E)
      DO 89470 IQ2W6E=1,IJOUT
       IF ( BITS(MB1+IQ2W6E-1) ) THEN
         S(MSOUT1+IQ2W6E-1)=S(I2+IQ2W6E-1)
       END IF
89470 CONTINUE
C
C           GO TO NEXT PARCEL ORIGIN LAYER
  400 CONTINUE
C
C
C          GET INPUT TEMPERATURES AT P=PLIFTTO
C
      ZTO=-LOG(PLIFTTO)
C          USE Z ( AT SIGMA) STORED IN S( JSCR3OUT(2) ).
C
C          THE SIGMA SURFACES THAT LIE AT OR JUST ABOVE Z=ZTO
C          RANGE FROM K=K1 THROUGH K2,  WHERE
C            K1 IS THE FIRST K FOR WHICH MAX(Z) .GE. ZTO,
C            K2 IS THE FIRST K FOR WHICH MIN(Z) .GE. ZTO.
C
      IAD=JSCR3OUT(2)-IJOUT
      DO 500 K=1,KM
      K1=K
      IAD=IAD+IJOUT
      ZMAX = S(IAD)
CMIC$ PARALLEL SHARED(IJOUT, ZMAX, IAD, S) PRIVATE(IQ2, R2S)
      R2S = ZMAX
CMIC$ DO PARALLEL VECTOR
      DO 2001 IQ2 = 1, IJOUT
         R2S = AMAX1(R2S,S(IAD+IQ2-1))
 2001 CONTINUE
CMIC$ GUARD
      ZMAX = AMAX1(ZMAX,R2S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
      IF( ZMAX .GE. ZTO ) GO TO 510
  500 CONTINUE
C
  510 IAD=JSCR3OUT(2)+(K1-2)*IJOUT
      DO 520 K=K1,KM
      K2=K
      IAD=IAD+IJOUT
      ZMIN = S(IAD)
CMIC$ PARALLEL SHARED(IJOUT, ZMIN, IAD, S) PRIVATE(IQ2, R3S)
      R3S = ZMIN
CMIC$ DO PARALLEL VECTOR
      DO 3001 IQ2 = 1, IJOUT
         R3S = AMIN1(R3S,S(IAD+IQ2-1))
 3001 CONTINUE
CMIC$ GUARD
      ZMIN = AMIN1(ZMIN,R3S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
      IF( ZMIN .GE. ZTO ) GO TO 530
  520 CONTINUE
C
  530 CONTINUE
C
C          A ONE IN BIT1D WILL DENOTE A POINT(I.E.COLUMN) FOR WHICH THE
C          TEMPERATURE AT P=PLIFTTO HAS NOT YET BEEN DETERMINED.
CMIC$ DO ALL VECTOR SHARED(IJOUT, MB1, I1, BITS, S) PRIVATE(IQ2, IQ2W6E)
      DO 5001 IQ2 = 1, IJOUT
         BITS(MB1+IQ2-1) = .TRUE.
         S(I1+IQ2-1) = 0.E0
 5001 CONTINUE
C
      INCAD=(K1-2) * IJOUT
      IADZ=JSCR3OUT(2) + INCAD
      IADT=JSCR3OUT(1) + INCAD
C
      DO 540 K=K1,K2
      IADZ=IADZ + IJOUT
      IADT=IADT + IJOUT
C        1'S FOR Z(K) .GE. ZTO
CMIC$ DO ALL VECTOR SHARED(IJOUT, IADZ, ZTO, MB2, S, BITS) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89490 IQ2W6E=1,IJOUT
         BITS(MB2+IQ2W6E-1)=S(IADZ+IQ2W6E-1).GE.ZTO
89490 CONTINUE
C         ELIMINATE 1'S IN BIT2D WHERE BIT1D ALREADY ZERO.
CMIC$ DO ALL VECTOR IF (ABS(MB2-MB1).GE.IJOUT .OR. MB2-MB1.EQ.0) SHARED(
CMIC$1   IJOUT, MB2, MB1, BITS) PRIVATE(IQ2W6E)
      DO 89500 IQ2W6E=1,IJOUT
         BITS(MB2+IQ2W6E-1)=BITS(MB2+IQ2W6E-1).AND.BITS(MB1+IQ2W6E-1)
89500 CONTINUE
C
C           DO VERTICAL INTERPOLATION ARITHMETIC
C
      C1=1.E0/ ( ZSIGLYR(K) - ZSIGLYR(K-1) )
      DO 89510 IQ2W6E=1,IJOUT
         S(I2+IQ2W6E-1)=ZTO-S(IADZ-IJOUT+IQ2W6E-1)
         S(I3+IQ2W6E-1)=S(IADT+IQ2W6E-1)-S(IADT-IJOUT+IQ2W6E-1)
         S(I4+IQ2W6E-1)=C1*S(I2+IQ2W6E-1)*S(I3+IQ2W6E-1)
89510 CONTINUE
C           STORE THIS WHERE BIT2D HAS ONES
CMIC$ DO ALL VECTOR IF ((ABS(I4-I1).GE.IJOUT .OR. I4-I1.EQ.0) .AND. (
CMIC$1   ABS(IADT-IJOUT-I1).GE.IJOUT .OR. IADT-IJOUT-I1.EQ.0)) SHARED(
CMIC$2   IJOUT, MB2, I4, IADT, I1, BITS, S) PRIVATE(IQ2W6E)
      DO 89540 IQ2W6E=1,IJOUT
       IF ( BITS(MB2+IQ2W6E-1) ) THEN
         S(I1+IQ2W6E-1)=S(I4+IQ2W6E-1)+S(IADT-IJOUT+IQ2W6E-1)
       END IF
89540 CONTINUE
C          UPDATE BIT1D BY ELIMINATING POINTS JUST STORED.
CMIC$ DO ALL VECTOR IF (ABS(MB1-MB2).GE.IJOUT .OR. MB1-MB2.EQ.0) SHARED(
CMIC$1   IJOUT, MB1, MB2, BITS) PRIVATE(IQ2W6E)
      DO 89550 IQ2W6E=1,IJOUT
         BITS(MB1+IQ2W6E-1)=BITS(MB1+IQ2W6E-1).AND..NOT.BITS(MB2+
     *   IQ2W6E-1)
89550 CONTINUE
C
  540 CONTINUE
C
C          CHECK THAT ALL POINTS ARE DONE
CMIC$ DO ALL VECTOR SHARED(IJOUT, I1, MB2, S, BITS) PRIVATE(IQ2W6E)
      DO 89560 IQ2W6E=1,IJOUT
         BITS(MB2+IQ2W6E-1)=S(I1+IQ2W6E-1).GT.0.E0
89560 CONTINUE
      ICNT = 0
      DO 6002 IQ2 = 1, IJOUT
         IF ( BITS(MB2+IQ2-1) ) ICNT = ICNT + 1
6002  CONTINUE
      IF( ICNT .EQ. IJOUT ) GO TO 560
C
C             ------------------------------
      IF(IERROR .LE. 0 ) GO TO 549
C          ZERO OUT THE ARRAY OF LIFTED INDEX
CMIC$ DO ALL VECTOR SHARED(IJOUT, I6, S) PRIVATE(IQ2W6E)
      DO 89570 IQ2W6E=1,IJOUT
         S(I6+IQ2W6E-1)=0.E0
89570 CONTINUE
      GO TO 561
C
  549 CONTINUE
C          PRINT DIAGNOSTIC INFO THE FIRST TIME THIS HAPPENS.
      IERROR=1
      PRINT 550,IJOUT,ICNT
  550 FORMAT(1H1,2X,'*****IN SR OUTLIFT DID NOT GET ALL TEMPS',
     1 ' AT PLIFTO. IJOUT AND ICNT=',2I8)
      PRINT 551
  551 FORMAT(1H0,30X,'BIT2D')
C*****  Code Expanded From Routine:  DUMPBIT
      PRINT 77053
77053 FORMAT(1H0,12X,'N1',17X,'(10)',16X,'(20)',16X,'(30)',
     1 16X,'(40)',16X,'(50)',6X,'N2')
C       NHDG WILL COUNT FOR PRINTING COLUMN HEADINGS.
      NHDG = 0
      N2 = 50
77054 CONTINUE
      N1 = N2 - 49
      IF (N1 .GT. IJOUT) GO TO 77055
CMIC$ DO ALL VECTOR SHARED(I1X) PRIVATE(IQ2W1X)
      DO 77058 IQ2W1X = 1, 50
         I1X(IQ2W1X) = -1
77058 CONTINUE
      N2 = MIN0(IJOUT,N2)
      LEN = N2 - N1 + 1
CMIC$ DO ALL VECTOR SHARED(LEN, N1, MB2, I1X, BITS) PRIVATE(IQ2W1X)
      DO 77059 IQ2W1X = 1, LEN
         I1X(IQ2W1X) = 0
         IF (BITS(N1-2+MB2+IQ2W1X)) I1X(IQ2W1X) = 1
77059 CONTINUE
C     END WHERE
      PRINT 77056, N1, (I1X(M), M = 1, 50), N2
77056 FORMAT(1H ,2X,I12,50I2,I12 )
      NHDG = NHDG + 1
      IF (NHDG .LT. 10) GO TO 77057
      PRINT 77053
      NHDG = 0
77057 CONTINUE
      N2 = N2 + 50
      GO TO 77054
C
77055 CONTINUE
      PRINT 77053
C*****  End of Code Expanded From Routine:  DUMPBIT
      PRINT 552,K1,K2,ZMIN,ZMAX
  552 FORMAT(1H0,10X,'K1,K2,ZMIN,ZMAX=',2I5,2E14.6)
      PRINT 553
  553 FORMAT(1H0,30X,'BIT1D')
C*****  Code Expanded From Routine:  DUMPBIT
      PRINT 77061
77061 FORMAT(1H0,12X,'N1',17X,'(10)',16X,'(20)',16X,'(30)',
     1 16X,'(40)',16X,'(50)',6X,'N2')
C       NHDG WILL COUNT FOR PRINTING COLUMN HEADINGS.
      NHDG1X = 0
      N21X = 50
77062 CONTINUE
      N11X = N21X - 49
      IF (N11X .GT. IJOUT) GO TO 77063
CMIC$ DO ALL VECTOR SHARED(I2X) PRIVATE(IQ2W2X)
      DO 77066 IQ2W2X = 1, 50
         I2X(IQ2W2X) = -1
77066 CONTINUE
      N21X = MIN0(IJOUT,N21X)
      LEN1X = N21X - N11X + 1
CMIC$ DO ALL VECTOR SHARED(LEN1X, N11X, MB1, I2X, BITS) PRIVATE(IQ2W2X)
      DO 77067 IQ2W2X = 1, LEN1X
         I2X(IQ2W2X) = 0
         IF (BITS(N11X-2+MB1+IQ2W2X)) I2X(IQ2W2X) = 1
77067 CONTINUE
C     END WHERE
      PRINT 77064, N11X, (I2X(M1X), M1X = 1, 50), N21X
77064 FORMAT(1H ,2X,I12,50I2,I12 )
      NHDG1X = NHDG1X + 1
      IF (NHDG1X .LT. 10) GO TO 77065
      PRINT 77061
      NHDG1X = 0
77065 CONTINUE
      N21X = N21X + 50
      GO TO 77062
C
77063 CONTINUE
      PRINT 77061
C*****  End of Code Expanded From Routine:  DUMPBIT
      PRINT 554
  554 FORMAT(1H0,40X,'INPUT T AT PLIFTTO')
      CALL PRT(S(I1),IMOUT,JMOUT)
      PRINT 555
  555 FORMAT(1H0,2X,'WILL NOT PRINT ABOVE DIAGNOSTICS FOR',
     1 ' FUTURE OCCURENCES, BUT WILL ZERO THE OUTPUT')
C
CMIC$ DO ALL VECTOR SHARED(IJOUT, I6, S) PRIVATE(IQ2W6E)
      DO 89580 IQ2W6E=1,IJOUT
         S(I6+IQ2W6E-1)=0.E0
89580 CONTINUE
      GO TO 561
C
C                 ---------------------------
C
  560 CONTINUE
C
C          T(INPUT AT PLIFTTO) MINUS WARMEST PARCEL TEMPERATURE
CMIC$ DO ALL VECTOR IF ((ABS(I1-I6).GE.IJOUT .OR. I1-I6.EQ.0) .AND. (
CMIC$1   ABS(MSOUT1-I6).GE.IJOUT .OR. MSOUT1-I6.EQ.0)) SHARED(IJOUT, I1
CMIC$2   , MSOUT1, I6, S) PRIVATE(IQ2W6E)
      DO 89590 IQ2W6E=1,IJOUT
         S(I6+IQ2W6E-1)=S(I1+IQ2W6E-1)-S(MSOUT1+IQ2W6E-1)
89590 CONTINUE
C
C          (ENTER HERE WHEN ERROR WAS DETECTED AND S6D WAS ZEROED)
  561 CONTINUE
C           APPLY A CORRECTION ( +273.16 FOR LFM PRODUCT, 0 FOR THE
C           BEST LIFTED INDEX )  TO ACCOMODATE ANCIENT NMC CUSTOM.
C
CMIC$ DO ALL VECTOR SHARED(IJOUT, I6, TSCALE, S) PRIVATE(IQ2W6E)
      DO 89600 IQ2W6E=1,IJOUT
         S(I6+IQ2W6E-1)=S(I6+IQ2W6E-1)+TSCALE
89600 CONTINUE
C
      CALL OUTNULAB
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IF(LIFTIN.EQ.1) THEN 
        IDGRBE(8) = 131
        IDGRBE(9) = 101
        ALEV1 = REAL(LABEL84(5))
        ARGL1 = REAL(LABEL84(6))
        XLEV1 = ALEV1 * 10.**ARGL1
        IDGRBE(10) =  INT(XLEV1 * 0.1)
        IDGRBE(11) = 100
      ELSE
        IDGRBE(8) = 132
        IDGRBE(9) = 108
        ALEV1 = REAL(LABEL84(5))
        ARGL1 = REAL(LABEL84(6))
        XLEV1 = ALEV1 * 10.**ARGL1
        IDGRBE(10) =  INT(XLEV1 * 100.)
        ALEV2 = REAL(LABEL84(12))
        ARGL2 = REAL(LABEL84(13))
        XLEV2 = ALEV2 * 10.**ARGL2
        IDGRBE(11) =  INT(XLEV2 * 100.)
      ENDIF
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0
      IDGRBE(20) =  0
C
c     CALL OUTPACK( S(I6),IJOUT,S(I1), DESCRIPT(NCARD),
c    1     LABEL84, IOUTUNIT )
      CALL GRIBITN ( S(I6),IJOUT,S(I1), DESCRIPT(NCARD),
     1     IDGRBE,IOUTGRIB,LABEL84 )
C
C
C              PREPARE FOR THE BEST LIFTED INDEX
C
  999 CONTINUE
C
      KTOP = 4
      TSCALE = 0.E0
C             LABEL CHANGES
      LABQTYPE = 116
      LABSSUB1 = 148
      LABSSUB2 = 148
      S2VALUE = PRESS(1)
C
C
C
C**********************************************************************
C**********************************************************************
C***************                                              *********
C***************     BEWARE OF THE AD HOC CODE HERE IF THE    *********
C***************     VERTICAL STRUCTURE OF THE NGM IS         *********
C***************     CHANGED.  THIS HARD WIRING WAS NECESSARY *********
C***************     TO KEEP THE OFFICE NOTE 84 LABEL FOR     *********
C***************     THE 4-LAYER LIFTED INDEX FROM CHANGING   *********
C***************     WHEN THE OPERATIONAL NGM WAS CONVERTED   *********
C***************     FROM FORTRAN-66 TO FORTRAN-77 ON 3 DEC   *********
C***************     1986.  IF THE LABEL WERE CHANGED MANY    *********
C***************     OPERATIONAL CODES OF AUTOMATION DIVISION *********
C***************     WOULD NEED TO BE CHANGED AS WELL.        *********
C
      S1VALUE = PRESS(KTOP)
C*****S1VALUE = 0.8436723 E0   THE VALUE GIVEN BY THE PREVIOUS CARD.
      S1VALUE = 0.8436774 E0
C
C***************                                              *********
C**********************************************************************
C**********************************************************************
C
C
C
C
C
 1000 CONTINUE
C
C
C          RESTORE NORMAL VALUES OF FOLLOWING 3 QUANTITIES
      LABMLDIF = 0
      LABSSUB2 = 0
      S2VALUE = 0.E0
C
C
C
      RETURN
      END
