      SUBROUTINE OUTNULAB
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    OUTNULAB    UPDATE THE INTEGER ARRAY  LABEL84(27)
C   PRGMMR: N PHILLIPS       ORG: W/NMC22    DATE: 84-01-20
C
C ABSTRACT: THE 12 MOST VARIABLE PARTS OF THE 27 ITEM OFFICE NOTE
C   84 LABEL ARE UPDATED IN THE INTEGER ARRAY  LABEL84(27).  THE
C   INFORMATION TO ACCOMPLISH THIS IS GIVEN BY 8 INTEGERS AND 2
C   HALF PRECISION WORDS STORED INDIVIDUALLY IN LABELED COMMON
C   COMOUT  .
C   .
C PROGRAM HISTORY LOG:
C   84-01-20  N PHILLIPS
C   88-08-24  BRIAN SCHMIDT ADDED THE DOCBLOCK
C
C USAGE:    CALL OUTNULAB
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - OUTSVALU (FROM NGMTEMP2)
C     LIBRARY:
C       COMMON   - COMOUT
C
C REMARKS: THIS SUBROUTINE CAN BE SUCCESSFULLY EXECUTED ONLY AFTER
C   THE SIX INTEGERS AND TWO HALF-PRECISION WORDS LISTED BELOW HAVE
C   BEEN SET UP BY THE CALLING CODE.
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   . NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C   LABQTYPE      VARIABLE TYPE                              COMMON
C   .
C   LABSSUB1      UPPERMOST SURFACE TYPE                     COMMON
C   .
C   LABTMARK      TIME MARKER                                COMMON
C   .
C   LABMLDIF      LEVEL DIFFERENCE MARKER                    COMMON
C   .
C   LABSSUB2      LOWERMOST SURFACE TYPE                     COMMON
C   .
C   LABFSUB2      F2 FROM TABLE 2 OF OFFICE NOTE 84.         COMMON
C   .
C   LABKGRID      GRID TYPE( TABLE 7 OF O.NOTE 84).          COMMON
C   .
C   LABNUMPT      NUMBER OF POINTS ON OUTPUT GRID            COMMON
C   .
C   S1VALUE       VALUE OF THE VARIABLE DEFINING THE         COMMON
C   .             UPPERMOST SURFACE.
C   .
C   S2VALUE       VALUE OF THE VARIABLE DEFINING THE         COMMON
C   .             LOWER SURFACE.
C
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   . NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C   .
C   LABEL84       ARRAY OF INTEGERS IN LABELLED COMMON       COMMON
C   .             COMOUT  THAT IS USED BY THE PACKER
C   .             CODE TO CONSTRUCT THE O.NOTE 84 LABEL
C   .             ACCOMPANYING EACH OUTPUT ARRAY.
C   .
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:00:39  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
      REAL EXPON,AMANTISS,EXPO1X,AMAN1X
C
      LABEL84(1)  = LABQTYPE
      LABEL84(2)  = LABSSUB1
      LABEL84(4)  = LABTMARK
      LABEL84(7)  = LABMLDIF
      LABEL84(9)  = LABSSUB2
      LABEL84(10) = LABFSUB2
      LABEL84(17) = LABKGRID
      LABEL84(27) = LABNUMPT
C
C          MUST CONVERT THE TWO SURFACE VALUES (S1VALUE AND S2VALUE)
C          INTO THE 'C' AND 'E' INTEGERS DEFINED IN O. NOTE 84.
C
C*****  Code Expanded From Routine:  OUTSVALU
      IF (S1VALUE .EQ. 0.0E0) THEN
C
C              THE SPECIAL CASE.
         IC = 0
         IE = 0
C
      ELSE
C              THE CASE WHEN SURFACE IS NONZERO.
         EXPON = LOG10(ABS(S1VALUE))
         IF (EXPON .GE. 0.0E0) THEN
C
C              THE VALUE OF SURFACE IS GREATER THAN OR EQUAL TO 1.
            IE = INT(EXPON) - 4
C
         ELSE
C              THE VALUE OF SURFACE IS LESS THAN 1.
            IE = INT(EXPON) - 5
         ENDIF
C
         AMANTISS = S1VALUE*10.0E0**(-IE)
C
C              ROUND THE MANTISSA TO THE NEAREST (SIGNED) INTEGER.
         IC = NINT(AMANTISS)
C
C              ENSURE THAT THE MANTISSA IS WITHIN RANGE.
77001    CONTINUE
         IF (ABS(IC) .GE. 100000) THEN
            IE = IE + 1
            AMANTISS = S1VALUE*10.0E0**(-IE)
C
C              ROUND THE MANTISSA TO THE NEAREST (SIGNED) INTEGER.
            IC = NINT(AMANTISS)
            GO TO 77001
C
         ENDIF
C
77002    CONTINUE
         IF (ABS(IC) .LE. 9999) THEN
            IE = IE - 1
            AMANTISS = S1VALUE*10.0E0**(-IE)
C
C              ROUND THE MANTISSA TO THE NEAREST (SIGNED) INTEGER.
            IC = NINT(AMANTISS)
            GO TO 77002
         ENDIF
C
      ENDIF
C*****  End of Code Expanded From Routine:  OUTSVALU
C
      LABEL84(5)=IC
      LABEL84(6)=IE
C
C*****  Code Expanded From Routine:  OUTSVALU
      IF (S2VALUE .EQ. 0.0E0) THEN
C
C              THE SPECIAL CASE.
         IC = 0
         IE = 0
C
      ELSE
C              THE CASE WHEN SURFACE IS NONZERO.
         EXPO1X = LOG10(ABS(S2VALUE))
         IF (EXPO1X .GE. 0.0E0) THEN
C
C              THE VALUE OF SURFACE IS GREATER THAN OR EQUAL TO 1.
            IE = INT(EXPO1X) - 4
C
         ELSE
C              THE VALUE OF SURFACE IS LESS THAN 1.
            IE = INT(EXPO1X) - 5
         ENDIF
C
         AMAN1X = S2VALUE*10.0E0**(-IE)
C
C              ROUND THE MANTISSA TO THE NEAREST (SIGNED) INTEGER.
         IC = NINT(AMAN1X)
C
C              ENSURE THAT THE MANTISSA IS WITHIN RANGE.
77003    CONTINUE
         IF (ABS(IC) .GE. 100000) THEN
            IE = IE + 1
            AMAN1X = S2VALUE*10.0E0**(-IE)
C
C              ROUND THE MANTISSA TO THE NEAREST (SIGNED) INTEGER.
            IC = NINT(AMAN1X)
            GO TO 77003
C
         ENDIF
C
77004    CONTINUE
         IF (ABS(IC) .LE. 9999) THEN
            IE = IE - 1
            AMAN1X = S2VALUE*10.0E0**(-IE)
C
C              ROUND THE MANTISSA TO THE NEAREST (SIGNED) INTEGER.
            IC = NINT(AMAN1X)
            GO TO 77004
         ENDIF
C
      ENDIF
C*****  End of Code Expanded From Routine:  OUTSVALU
C
      LABEL84(12)=IC
      LABEL84(13)=IE
C
      RETURN
      END
