      SUBROUTINE OUTOPEN (DATSET, AYEAR0, AMNTH0, ADAY0, AGMT0,
     1                    IRUNMK, IVERSN, ITUPRT, ITUOUT, IOPEN)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    OUTOPEN       CREATES NCEP DATE WORD, WRITES IT TO DISK
C   PRGMMR: ERIC ROGERS         ORG: W/NP22    DATE: 98-11-19
C
C ABSTRACT: CREATES THE NCEP DATE WORD FOR THE FILE
C   BEING PROCESSED, AND WRITES IT TO DISK.
C
C PROGRAM HISTORY LOG:
C   98-11-19 ERIC ROGERS : BASED ON OLD SUBROUTINE OUTOPEN
C
C USAGE:    CALL OUTOPEN (DATSET, IYEAR0, IMNTH0, IDAY0, IGMT0,
C                         IRUNMK, IVERSN, ITUPRT, ITUOUT)
C   INPUT ARGUMENT LIST:
C     DATSET   - DATA SET NAME
C     AYEAR0   - FULL - DIGIT YEAR AT MODEL TIME
C     AMNTH0   - MONTH OF THE INITIAL MODEL TIME
C     ADAY0    - DAY OF THE INITIAL MODEL TIME
C     AGMT0    - GMT HOUR OF THE INITIAL MODEL TIME
C     IRUNMK   - EXPLAIN COMPLETELY IF ERROR RETURN
C     IVERSN   - VERSION OF THE MODEL
C     ITUPRT   - UNIT NUMBER FOR PRINTOUT
C     ITUOUT   - UNIT NUMBER OF THE DISK THAT THE O.N. 85 LABEL
C                IS BEING WRITTEN
C
C   OUTPUT FILES:
C     ITUOUT   - UNIT FOR OUTPUT DATA SET THAT THIS ROUTINE
C                IS WRITING AN O.N. 85 LABEL TO
C     ITUPRT   - UNIT FOR PRINTOUT OF ERROR MESSAGE
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C       W3LIB    - W3UTCDAT W3FI48
C
C ATTRIBUTES:
C   LANGUAGE: STANDARD FORTRAN
C   MACHINE:
C
C$$$
C
      CHARACTER*6  DATSET
      character*50 envar
      character*70 filgr
C
      DIMENSION INPDAT(8),JTIME(8)
C
      DO I = 1, 8
        INPDAT(I) = 0
      ENDDO
C
      IYEAR0 = NINT ( AYEAR0 )
      IMNTH0 = NINT ( AMNTH0 )
      IDAY0  = NINT ( ADAY0  )
      IGMT0  = NINT ( AGMT0  )
C
      INPDAT(1) = IYEAR0
      INPDAT(2) = IMNTH0
      INPDAT(3) = IDAY0
      INPDAT(5) = IGMT0
C
C              SPECIFY THE SET INITIATE TIME.
C 
      CALL W3UTCDAT(JTIME)
C
      ISETIM = NINT(100.*(FLOAT(JTIME(4))
     1                   + FLOAT(JTIME(5)) / 60.0
     2                   + FLOAT(JTIME(6)) / 3600.))
C
C     OPEN THE FILE
C
      IF ( IOPEN .EQ. 1 ) THEN
         ENVAR = ' '
         CALL GETENV ("COMSP",ENVAR)
         K = INDEX(ENVAR,' ') - 1
         IF (K.LE.0) K = LEN(ENVAR)
         FILGR  = ENVAR(1:K) // DATSET
c        OPEN(UNIT=ITUOUT,FILE=FILGR,STATUS='NEW',FORM='UNFORMATTED')
      END IF
C              WRITE THE DATE WORD TO DISK.
c     WRITE (ITUOUT) INPDAT
C
C              PRINT THE FACT THAT WE HAVE OPENED THIS FILE.
C         AND  PRINT THE OFFICE NOTE 85 LABEL.
C
      WRITE (ITUPRT, 400) DATSET, ITUOUT
  400 FORMAT ('0     NCEP DATE WORD FOR FILE ',A6,
     1             ' WAS WRITTEN TO THE DISK WITH UNIT NUMBER ',I2,
     2             '.  THE DATE IS:')
c
      WRITE (ITUPRT, 500) DATSET, IGMT0, IDAY0,
     1                IMNTH0, IYEAR0, IRUNMK, 
     2                ISETIM, IVERSN
c
  500 FORMAT (' FILE=',A6,' INITIAL TIME=',I3,' GMT',I3,'/',
     2             I3,'/',I5,25X,'RUN MARKER=',I3,
     4             ' SET INITIATE TIME=',I5,
     5             '  MODEL VERSION=',I10)
C
      RETURN
      END
