      SUBROUTINE OUTOPENGB (ITUOUT, DATSET, ITUPRT)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    OUTOPENGB        ASSIGNS AND OPENS UNIT FOR GRIB FILE
C   PRGMMR: RUSS TREADON          ORG: W/NMC22    DATE: 93-12-21
C
C ABSTRACT:  INTERNALLY ASSIGNS AND OPENS A UNIT TO RECEIVE GRIB DATA
C
C PROGRAM HISTORY LOG:
C   93-12-21  RUSS TREADON - CODED ROUTINE BASED ON SUBROUTINE OUTOPEN
C   98-12-03  ERIC ROGERS - MOVED ISHELLS OF JOBS TO MAKE GRIB INDEX 
C             FILES FROM MAIN PROGRAM TO ENSURE THAT THE GRIB INDEX
C             JOB IS TRIGGERED AFTER ALL THE NEEDED GRIBFILES ARE CLOSED
C
C USAGE:    CALL OUTOPENGB (ITUOUT, DATSET, ITUPRT)
C   INPUT ARGUMENT LIST:
C     ITUOUT   - UNIT NUMBER OF THE DISK THAT THE GRIB DATA
C                IS BEING WRITTEN
C     DATSET   - DATA SET NAME
C     ITUPRT   - UNIT TO RECEIVE RUN-TIME MESSAGES
C
C   OUTPUT FILES:
C     ITUOUT   - UNIT FOR OUTPUT DATA SET THAT THIS ROUTINE
C                IS WRITING GRIB TO
C     ITUPRT   - STANDARD OUT
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C
C ATTRIBUTES:
C   LANGUAGE: STANDARD FORTRAN
C   MACHINE:
C
C$$$
C
C
      CHARACTER*6  DATSET
      CHARACTER*2  CHR
      CHARACTER*8  NMCGR
      CHARACTER*9  NMCGRI
      CHARACTER*50 ENVAR
      CHARACTER*61 FILGRB, filgrbi
      CHARACTER FINFIL*50,DONE*10
      INTEGER IHR
      common /comgrb/ filgrb, filgrbi
C
C     INITIALIZE GRIB1 DECIMAL SCALINGS.
c     CALL IDSDEF(1,IDS)
C
C     SET STANDARD NMC GRIB DATA FILE NAME.
C
c     K = INDEX(DATSET,' ') - 1
c     IF (K.LE.0) K = LEN(DATSET)	
c     NMCGR = DATSET(1:K) // '.PGRB'
      NMCGR = 'pgrb.f' // DATSET(3:4)
      NMCGRI = 'pgrbi.f' // DATSET(3:4)
C     
C     CONSTRUCT FULL PATH-FILENAME TO OUTPUT GRIB FILE.
C     THE PATH IS SET IN ENVIRONEMNT VARIABLE COMSP WHICH
C     IS SET IN THE SCRIPT RUNNING THE NGM. 
      ENVAR = ' '
      CALL GETENV ("COMSP",ENVAR)
      K = INDEX(ENVAR,' ') - 1
      IF (K.LE.0) K = LEN(ENVAR)
      FILGRB = ENVAR(1:K) // NMCGR
      FILGRBI = ENVAR(1:K) // NMCGRI
C
C     ASSIGN AND OPEN UNIT FOR GRIB DATA FILE.
C     
C     ***WARNING*** THE ATTRIBUTE '-s unblocked' MUST BE IN LOWER CASE!!!
C
      CLOSE(ITUOUT)
C
C  AFTER THE PREVIOUS GRIB FILE IS CLOSED FIGURE OUT THE
C  CURRENT FORECAST HOUR SEE IF WE NEED TO TRIGGER THE
C  GRIB INDEX JOB
C
      CHR = DATSET(3:4)
      WRITE(99,10)CHR
10    FORMAT(A2)
      REWIND 99
      READ(99,20)IHR
20    FORMAT(I2)
      REWIND 99
C
      WRITE(6,*)' IN OUTOPENGB FCST HR = ',CHR,IHR,ITUOUT
C
      DONE='DONE'
      IF(IHR.EQ.15.OR.IHR.EQ.27.OR.IHR.EQ.39) THEN
        WRITE(FINFIL,1190)IHR
 1190   FORMAT('fcstdone',I2.2)
        LFINFIL=91
        CLOSE(LFINFIL)
        OPEN(UNIT=LFINFIL,FILE=FINFIL,FORM='UNFORMATTED',IOSTAT=IER)
        WRITE(LFINFIL)DONE
        CLOSE(LFINFIL)
        IF(IER.NE.0)WRITE(6,*)' SIGNAL SENT TO FINFIL:  DONE'
      ENDIF
C
c     CALL ASNUNIT(ITUOUT,'-s unblocked',IER)
      CALL BAOPEN(ITUOUT,FILGRB,IER)
c     IF (IER.NE.0) WRITE(ITUPRT,*)
c    X     'OUTOPENGB:  BAOPEN ERROR FOR GRIB DATA ',
c    X     'FILE.  IER=',IER
c     OPEN(ITUOUT,FILE=FILGRB,FORM='UNFORMATTED')
c     REWIND(ITUOUT)
C     
C     ECHO MESSAGE TO ITUPRT.
C
      WRITE(ITUPRT,*)'GRIBIT:  OPENED ',ITUOUT,
     X     ' FOR GRIB DATA ',FILGRB
C
      RETURN
      END
