      SUBROUTINE OUTOMEGA( NCARDS )
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    OUTOMEGA    COMPUTE OMEGA=D(PRES)/D(TIME), SFC P TEND
C   PRGMMR: N PHILLIPS       ORG: W/NMC22    DATE: 84-01-10
C
C ABSTRACT: AFTER DETERMINING THAT AT LEAST ONE ARRAY OF THESE FIELDS
C   IS WANTED, THIS CODE USES THE BASIC NGM FIELDS OF HU, HV, AND H,
C   ALL STORED IN THE ARRAY  VBL  , TO COMPUTE
C   .  A) OMEGA VALUES ON SIGMA SURFACES OF THE NEEDED NGM GRIDS.
C   .  B) SURFACE PRESSURE TENDENCY.
C   .
C   THE FORMULAS USED ARE
C   .
C   OMEGA = (OMEGA PRIME) + (1-SIGMA)*VELOCITY TIMES(H GRADIENT),
C   .
C   WHERE (OMEGA PRIME) SATISFIES THE EQUATION
C   .
C   D(OMEGA PRIME)
C   -------------   =  DIVERGENCE OF ( H * HORIZONTAL VELOCITY)
C   D( SIGMA )
C   .            AND
C   SIGMA DENOTES THE NGM DEFINITION = 1 -(PRESSURE/SFC PRESS.)
C   .
C   (OMEGA PRIME)  =  ZERO AT P=0 ( SIGMA = 1)
C   .              =  PRESSURE TENDENCY AT GROUND AT SIGMA=0.
C   .
C   AFTER THESE VALUES HAVE BEEN COMPUTED FOR THE NUMGDREQ NGM
C   GRIDS, THE ROUTINE WILL, AS INSTRUCTED BY 'DATA CARDS',
C   .  A) UPDATE THE LABEL AND SEND THE SFC PRESSURE TENDENCY TO
C   .     THE PACKER CODE
C   .  B) CALL  OUTSIG2P  FOR OUTPUT OF OMEGA ON PRESSURE SURFACES
C   .  C) RETURN A VALUE FOR  NCARDS  EQUAL TO
C   .        THE NUMBER (.GE. 1) OF THE OUTPUT DATA CARD FOR OMEGA
C   .          ON SIGMA SFCS IF THAT CARD ASKS FOR THAT DATA,
C   .                       OR,
C   .        ZERO IF THAT OUTPUT DATA CARD DOES NOT ASK FOR DATA,
C   .          OR IF THAT DATA CARD DOES NOT EXIST.
C   .
C PROGRAM HISTORY LOG:
C   84-12-10  N PHILLIPS
C   88-08-25  B SCHMIDT REVISED THE DOCBLOCK
C
C USAGE:  CALL OUTOMEGA( NCARDS )
C   OUTPUT ARGUMENT LIST:
C     NCARDS   - NUMBER OF THE OUTPUT DATA CARD FOR OMEGA ON SIGMA
C                SFCS IF THAT CARD ASKS FOR THAT DATA, OR
C                ZERO IF THAT OUTPUT DATA CARD DOES NOT ASK FOR DATA,
C                OR IF THAT DATA CARD DOES NOT EXIST
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - OUTNULAB
C                  OUTPACK
C                  OUTSIG2P
C     LIBRARY:
C       COMMON   - COMBLANK
C                  COMCONST
C                  COMOUT
C
C REMARKS:
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES         MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----         ----------------------------------        ---------
C   H, HU, HV      BASIC FIELDS OF THE NGM GRIDS LOCATED      COMMON
C   .              IN THE ARRAY  VBL  .
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES         MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----         ----------------------------------        ---------
C   ANY OUTPUT OF SURFACE PRESSURE TENDENCY OCCURS BY CALLS
C   TO THE SUBROUTINES  OUTNULAB  AND OUTPACK
C   .
C   FOR OUTNULAB, THE FOLLOWING LABEL INFORMATION IS PREPARED.
C   .
C   LABSSUB1       =129 FOR OUTPUT ON EARTHS SURFACE          COMMON
C   .
C   S1VALUE        = ZERO                                     COMMON
C   .
C   LABQTYPE       =9 (NEW ENTRY FOR VBL TYPE IN O.N.84)      COMMON
C   .
C   FOR OUTPACK THE FOLLOWING INFORMATION IS SUPPLIED.
C   .
C   S(MSOUT2)      THE ARRAY OF TEMPERATURE, U, OR V         ARGUMENT
C   .
C   IJOUT          THE SIZE OF THE OUTPUT GRID               ARGUMENT
C   .
C   S(MSOUT1)      SCRATCH SPACE FOR PACKER CODE(SIZE IJOUT) ARGUMENT
C   .
C   DESCRIPT(NCARDT)20 CHARACTER STRING TO DESCRIBE OUTPUT   ARGUMENT
C   .
C   LABEL84        ARRAY IN COMOUT CONTAINING LABEL INFO.    ARGUMENT
C   .
C   IOUTUNIT       DISK UNIT NUMBER FOR PACKER TO WRITE ON.  ARGUMENT
C   .
C   FOR OUTPUT OF OMEGA ON PRESSURE SFCS, THE FOLLOWING INFO IS
C   SUPPLIED TO SUBROUTINE  OUTSIG2P
C   .
C   NDATA          OMEGA ON THE NGM SIGMA GRIDS IS IN        ARGUMENT
C   .              THE ARRAY SETS S( JSCR3NGM(NN,NDATA) )
C   .
C   NWORK          S( JSCR2(NWORK) ) CAN BE USED FOR A       ARGUMENT
C   .              HORIZONTAL SCRATCH AREA(HALF-PREC.)
C   .
C   MB             BITS(MB) CAN BE USED FOR A BIT SCRATCH    ARGUMENT
C   .              ARRAY
C   .
C   LABVVEL        =40 TO IDENTIFY OMEGA OUTPUT              ARGUMENT
C   .
C   GAMBOT,GAMTOP  =0 AS EXTRAPOLATION COEFFICIENTS FOR      ARGUMENT
C   .              PRESSURE SURFACES ABOVE SIGMA SFC K=KM
C   .              OR BELOW SIGMA SFC K=1.
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:02:57  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C          DESCRIPTORS USED IN SR  OUTHORIZ
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
CER
      INTEGER IDGRBE(25)
C
      COMMON/ADDRS/MIILL,MIIUL,MSA,MSB,MSC,MSD
C
      DIMENSION S(INSUMG), FNGM(INSUMG), IN(INSUMG)
C
      EQUIVALENCE ( SCR(1,1),S(1),FNGM(1), IN(1) )
C
C          NECESSARY OFFICE NOTE 84 LABEL VALUES
      DATA LABPRES/8/,LABVVEL/40/,LABSIG/148/,LABSFC/129/,
     1     LABPTEN/9/
C
C          BECAUSE OF THE LARGE COMPUTATION INVOLVED, FIRST SEE
C          WHETHER IT IS DESIRED.
C
C
C          BECAUSE OF THE LARGE COMPUTATION INVOLVED, FIRST SEE
C          WHETHER IT IS DESIRED.
C
      NANY=0
C          OMEGA ON PRESSURE SURFACES?????
      NCARDP=0
      DO 1 N=1,NOUTVBLS
      NCARD=N
      IF(LQTYPE(N).EQ.LABVVEL .AND. LSTYPE(N).EQ.LABPRES) GO TO 2
    1 CONTINUE
C          NO DATA CARD FOR OMEGA ON PRESSURE SURFACES
      GO TO 3
2     CONTINUE
      ISUM = 0
      DO 1003 IQ2 = 1, LMOUT
         ISUM = ISUM + LEVELS(IQ2,NCARD)
1003  CONTINUE
      IF(ISUM .LE. 0 ) GO TO 3
C          YES, WE MUST SUPPLY OMEGA ON PRESSURE SURFACES
      NCARDP=NCARD
      NANY=NANY+1
C
C          OMEGA ON SIGMA SURFACES???????
    3 NCARDS=0
      DO 4 N=1,NOUTVBLS
      NCARD=N
      IF(LQTYPE(N).EQ.LABVVEL .AND. LSTYPE(N).EQ.LABSIG) GO TO 5
    4 CONTINUE
C          NO DATA CARD FOR OMEGA ON SIGMA SURFACES
      GO TO 6
C
5     CONTINUE
      ISUM = 0
      DO 1001 IQ2 =1, KM
         ISUM = ISUM + LEVELS ( IQ2, NCARD )
1001   CONTINUE
      IF(ISUM .LE. 0 ) GO TO 6
C          OMEGA ON SIGMA SURFACES IS WANTED,,,
      NCARDS=NCARD
      NANY=NANY+1
C           MAYBE THE SURFACE PRESSURE TENDENCY IS WANTED
    6 NCARDT=0
      DO 7 N=1,NOUTVBLS
      NCARD=N
      IF(LQTYPE(N).EQ.LABPTEN .AND. LSTYPE(N).EQ.LABSFC) GO TO 8
    7 CONTINUE
C          NO DATA CARD FOR SURFACE PRESSURE TENDENCY
      GO TO 9
8     CONTINUE
      ISUM = 0
      DO 1002 IQ2 = 1, LMOUT
         ISUM = ISUM + LEVELS(IQ2, NCARD )
1002  CONTINUE
      IF(ISUM .LE. 0 ) GO TO 9
C
      NCARDT=NCARD
      NANY=NANY+1
C
    9 IF( NANY .EQ. 0 ) RETURN
C
C          GRID SPACING FOR GRID A (NG=1)
      DXGDA=2.E0*RADIUS/( FLOAT(NH) + .5E0 )
C
      DO 100 NN=1,NUMGDREQ
      NG=NGRIDATA(NN)
      IM=IMG(NG)
      JM=JMG(NG)
      IJ=IM*JM
C          GRID SPACING FOR THIS GRID
      DX=DXGDA
        DO 30 N=1,NGRDUSE
        IF(N .EQ. NG ) GO TO 35
        DX=.5E0 * DX
   30   CONTINUE
C
   35 CONTINUE
C
C
C          INITIAL ADDRESSES FOR HU,HV,AND H
      IADHU=IADDRG(1,NG)
      IADHV=IADDRG(2,NG)
      IADH=IADDRG(5,NG)
C          SCRATCH ADDRESSES
      I1=JSCR2(1)
      I2=JSCR2(2)
      I3=JSCR2(3)
C
C          PUT THE DIVERGENCE OF ( H * VELOCITY ) AT CENTER OF
C          INTO ARRAY S(MNGM3).
C
C          FIRST PUT (1/DX) TIMES 1/SCALE FACTOR AT HU AND HV
C          POINTS INTO ARRAYS S(I1) AND S(I2).
C
      CALL OUTSCALE( NG, 1, S(I1),S(I3) )
      C1=1.E0 / DX
CMIC$ DO ALL VECTOR SHARED(IJ, C1, I1, S) PRIVATE(IQ2W6E)
      DO 88890 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=C1/S(I1+IQ2W6E-1)
88890 CONTINUE
C
      CALL OUTSCALE( NG, 2, S(I2), S(I3) )
CMIC$ DO ALL VECTOR SHARED(IJ, C1, I2, S) PRIVATE(IQ2W6E)
      DO 88900 IQ2W6E=1,IJ
         S(I2+IQ2W6E-1)=C1/S(I2+IQ2W6E-1)
88900 CONTINUE
C
      IADU=IADHU-IJ
      IADV=IADHV-IJ
      IAD = MNGM3-IJ
        DO 40 K=1,KM
        IADU=IADU+IJ
        IADV=IADV+IJ
        IAD=IAD+IJ
CMIC$ DO ALL VECTOR IF (ABS(I1-I3).GE.IJ .OR. I1-I3.EQ.0) SHARED(IJ, I1
CMIC$1   , IADU, I3, S, VBL) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=S(I1+IQ2W6E-1)*VBL(IADU+IQ2W6E-1)
88910 CONTINUE
CMIC$ DO ALL VECTOR IF ((ABS(I3+1-IAD).GE.IJ .OR. I3+1-IAD.EQ.0) .AND. (
CMIC$1   ABS(I3-IAD).GE.IJ .OR. I3-IAD.EQ.0)) SHARED(IJ, I3, IAD, S)
CMIC$2    PRIVATE(IQ2W6E)
      DO 88911 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(I3+IQ2W6E)-S(I3+IQ2W6E-1)
88911 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I2-I3).GE.IJ .OR. I2-I3.EQ.0) SHARED(IJ, I2
CMIC$1   , IADV, I3, S, VBL) PRIVATE(IQ2W6E)
      DO 88912 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=S(I2+IQ2W6E-1)*VBL(IADV+IQ2W6E-1)
88912 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IAD-IM-I3).GE.IJ .OR. IAD-IM-I3.EQ.0)
CMIC$1    SHARED(IJ, IAD, I3, IM, S) PRIVATE(IQ2W6E)
      DO 88913 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)+S(I3+IM+IQ2W6E-1)
88913 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IAD-I3).GE.IJ .OR. IAD-I3.EQ.0) SHARED(IJ, 
CMIC$1   IAD, I3, S) PRIVATE(IQ2W6E)
      DO 88914 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)-S(I3+IQ2W6E-1)
88914 CONTINUE
   40   CONTINUE
C          NEED SCALE FACTOR IN CENTER OF GRID SQUARE
C
      CALL OUTSCALE( NG, 4, S(I1), S(I3) )
C
C          SQUARE IT (IN S(I2) ) AND MULTIPLY THE S(MNGM3) ARRAY
C          WITH IT.
CMIC$ DO ALL VECTOR IF (ABS(I1-I2).GE.IJ .OR. I1-I2.EQ.0) SHARED(IJ, I1
CMIC$1   , I2, S) PRIVATE(IQ2W6E)
      DO 88960 IQ2W6E=1,IJ
         S(I2+IQ2W6E-1)=S(I1+IQ2W6E-1)*S(I1+IQ2W6E-1)
88960 CONTINUE
      IAD=MNGM3-IJ
        DO 50 K=1,KM
        IAD=IAD+IJ
CMIC$ DO ALL VECTOR IF (ABS(IAD-I2).GE.IJ .OR. IAD-I2.EQ.0) SHARED(IJ, 
CMIC$1   IAD, I2, S) PRIVATE(IQ2W6E)
      DO 88970 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)*S(I2+IQ2W6E-1)
88970 CONTINUE
   50   CONTINUE
C
C          STARTING AT THE TOP(KM) PUT OMEGA PRIME IN S(MNGM3).
      C1=-DELSIG(KM)
      IAD=MNGM3 + (KM-1)*IJ
CMIC$ DO ALL VECTOR SHARED(IJ, C1, IAD, S) PRIVATE(IQ2W6E)
      DO 88980 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=C1*S(IAD+IQ2W6E-1)
88980 CONTINUE
        DO 60 KK=2,KM
        K=-KK + KM + 1
        IAD=IAD-IJ
        C1=-DELSIG(K)
CMIC$ DO ALL VECTOR SHARED(IJ, IAD, C1, S) PRIVATE(IQ2W6E)
      DO 88990 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IJ+IQ2W6E-1)+C1*S(IAD+IQ2W6E-1)
88990 CONTINUE
   60   CONTINUE
C
C          OMEGA PRIME IN LAYER K=1 EQUALS THE TIME TENDENCY OF H.
C          AVERAGE IT TO H POINTS, CONVERT TO MILLIBARS AND PUT IN
C          ARRAY FNGM FOR POSSIBLE OUTPUT LATER.
CMIC$ DO ALL VECTOR IF ((ABS(MNGM3-1-I3).GE.IJ .OR. MNGM3-1-I3.EQ.0)
CMIC$1    .AND. (ABS(MNGM3-I3).GE.IJ .OR. MNGM3-I3.EQ.0)) SHARED(IJ, 
CMIC$2   MNGM3, I3, S) PRIVATE(IQ2W6E)
      DO 89000 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=.5E0*(S(MNGM3+IQ2W6E-2)+S(MNGM3+IQ2W6E-1))
89000 CONTINUE
      C1=500.E0
      IADF=JADDFNGM(NG)
CMIC$ DO ALL VECTOR SHARED(IJ,C1,I3,IM,IADF,S,FNGM)PRIVATE(IQ2W6E)
      DO 89010 IQ2W6E=1,IJ
         FNGM(IADF+IQ2W6E-1)=C1*(S(I3-IM+IQ2W6E-1)+S(I3+IQ2W6E-1))
89010 CONTINUE
C
C          AVERAGE OMEGA PRIME VERTICALLY TO MIDDLE OF LAYERS.
       IAD=MNGM3-IJ
        KMM1=KM-1
      IF (KMM1 .GT. 0) THEN
CMIC$    DO ALL IF (ABS(IJ).GE.KMM1*ABS(IJ) .OR. IJ.EQ.0) SHARED(KMM1, 
CMIC$1      IAD, IJ, S) PRIVATE(K, IQ2W6E)
         DO 70 K = 1, KMM1
            DO 77001 IQ2W6E = 1, IJ
               S(IAD+IQ2W6E-1+K*IJ) = .5E0*(S(IAD+IQ2W6E-1+K*IJ)+S(IAD+(
     1            K+1)*IJ+IQ2W6E-1))
77001       CONTINUE
   70    CONTINUE
         IAD = KMM1*IJ + IAD
      ENDIF
C          FINISH OFF THE TOP LAYER
      IAD=IAD+IJ
CMIC$ PARALLEL SHARED(IJ, IADH, IM, I3, VBL, S, IAD) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89030 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=.5E0*S(IAD+IQ2W6E-1)
89030 CONTINUE
C
C          CONVERT OMEGA PRIME TO OMEGA BY ADDING (1 - SIGMA)
C          TIMES ( VELOCITY DOT GRADIENT OF H ).
C
C          FIRST PUT SCALE FACTOR * DH/DX INTO S(I2)
CMIC$ DO PARALLEL VECTOR
      DO 89040 IQ2W6E=1,IJ
      S(I3+IQ2W6E-1)=.5E0*(VBL(IADH+IQ2W6E-1)+VBL(IADH+IM+IQ2W6E-1))
89040 CONTINUE
CMIC$ END PARALLEL
CMIC$ DO ALL VECTOR IF ((ABS(I3+1-I2).GE.IJ .OR. I3+1-I2.EQ.0) .AND. (
CMIC$1   ABS(I3-I2).GE.IJ .OR. I3-I2.EQ.0)) SHARED(IJ, I3, I2, S)
CMIC$2    PRIVATE(IQ2W6E)
      DO 89041 IQ2W6E=1,IJ
      S(I2+IQ2W6E-1)=S(I3+IQ2W6E)-S(I3+IQ2W6E-1)
89041 CONTINUE
      C1=1.E0/DX
CMIC$ DO ALL VECTOR IF (ABS(I2-I1).GE.IJ .OR. I2-I1.EQ.0) SHARED(IJ, C1
CMIC$1   , I2, I1, S) PRIVATE(IQ2W6E)
      DO 89060 IQ2W6E=1,IJ
         S(I2+IQ2W6E-1)=C1*S(I2+IQ2W6E-1)*S(I1+IQ2W6E-1)
89060 CONTINUE
C
C          THEN PUT SCALE FACTOR * DH/DY INTO S(I3)
CMIC$ DO ALL VECTOR SHARED(IJ, IADH, I3, VBL, S) PRIVATE(IQ2W6E)
      DO 89070 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=.5E0*(VBL(IADH+IQ2W6E-1)+VBL(IADH+IQ2W6E))
89070 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IM).GE.IJ .OR. IM.EQ.0) SHARED(IJ, I3, IM, S
CMIC$1   ) PRIVATE(IQ2W6E)
      DO 89071 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=S(I3+IM+IQ2W6E-1)-S(I3+IQ2W6E-1)
89071 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I3-I1).GE.IJ .OR. I3-I1.EQ.0) SHARED(IJ, C1
CMIC$1   , I3, I1, S) PRIVATE(IQ2W6E)
      DO 89072 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=C1*S(I3+IQ2W6E-1)*S(I1+IQ2W6E-1)
89072 CONTINUE
C
C          USE U ( AT HU POINTS, IN S(JSCR3NGM(NN,1) ) ) AND
C          V ( AT HV POINTS, IN S(JSCR3NGM(NN,2) ) ) FOR THE
C          ADVECTING VELOCITIES.
C
      IADU=JSCR3NGM(NN,1)-IJ
      IADV=JSCR3NGM(NN,2)-IJ
      IAD=MNGM3-IJ
        DO 80 K=1,KM
        IADU=IADU+IJ
        IADV=IADV+IJ
        IAD=IAD + IJ
C          THE 1-SIGMA FACTOR TIMES 0.5
        C1=PRESS(K) * .5E0
C          THE MEAN U TIMES THE DH/DX TERM
CMIC$ DO ALL VECTOR IF ((ABS(IADU-1-I1).GE.IJ .OR. IADU-1-I1.EQ.0)
CMIC$1    .AND. (ABS(IADU-I1).GE.IJ .OR. IADU-I1.EQ.0)) SHARED(IJ, C1, 
CMIC$2   IADU, I1, S) PRIVATE(IQ2W6E)
      DO 89100 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=C1*(S(IADU+IQ2W6E-2)+S(IADU+IQ2W6E-1))
89100 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I2-I1).GE.IJ .OR. I2-I1.EQ.0) SHARED(IJ, I2
CMIC$1   , I1, S) PRIVATE(IQ2W6E)
      DO 89101 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=S(I2+IQ2W6E-1)*S(I1+IQ2W6E-1)
89101 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IAD-I1).GE.IJ .OR. IAD-I1.EQ.0) SHARED(IJ, 
CMIC$1   IAD, I1, S) PRIVATE(IQ2W6E)
      DO 89102 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)+S(I1+IQ2W6E-1)
89102 CONTINUE
C          THE MEAN V TIMES THE DH/DY TERM
CMIC$ DO ALL VECTOR IF ((ABS(IADV-I1).GE.IJ .OR. IADV-I1.EQ.0) .AND. (
CMIC$1   ABS(IADV+IM-I1).GE.IJ .OR. IADV+IM-I1.EQ.0)) SHARED(IJ, C1, 
CMIC$2   IADV, IM, I1, S) PRIVATE(IQ2W6E)
      DO 89130 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=C1*(S(IADV+IQ2W6E-1)+S(IADV+IM+IQ2W6E-1))
89130 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I1-I3).GE.IJ .OR. I1-I3.EQ.0) SHARED(IJ, I1
CMIC$1   , I3, S) PRIVATE(IQ2W6E)
      DO 89131 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=S(I1+IQ2W6E-1)*S(I3+IQ2W6E-1)
89131 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IAD-I1).GE.IJ .OR. IAD-I1.EQ.0) SHARED(IJ, 
CMIC$1   IAD, I1, S) PRIVATE(IQ2W6E)
      DO 89132 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)+S(I1+IQ2W6E-1)
89132 CONTINUE
   80   CONTINUE
C
C          WE NOW HAVE OMEGA VALUES IN MIDDLE OF LAYERS, BUT
C          THEY ARE IN THE MIDDLE OF THE GRID SQUARES.
C          INTERPOLATE THEM HORIZONTALLY TO THE H POINTS.
C
      IAD1=MNGM3-IJ
      IAD2=JSCR3NGM(NN,3)-IJ
        DO 90 K=1,KM
        IAD1=IAD1+IJ
        IAD2=IAD2+IJ
C          AVERAGE AT HU POINTS
CMIC$ DO ALL VECTOR IF ((ABS(IAD1-I1).GE.IJ .OR. IAD1-I1.EQ.0) .AND. (
CMIC$1   ABS(IAD1-1-I1).GE.IJ .OR. IAD1-1-I1.EQ.0)) SHARED(IJ, IAD1, I1
CMIC$2   , S) PRIVATE(IQ2W6E)
      DO 89160 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=.5E0*(S(IAD1+IQ2W6E-1)+S(IAD1+IQ2W6E-2))
89160 CONTINUE
C          INCLUDE CONVERSION OF H TO MILLIBARS IN LAST STEP.
        C1=500.E0
CMIC$ DO ALL VECTOR IF ((ABS(I1-IAD2).GE.IJ .OR. I1-IAD2.EQ.0) .AND. (
CMIC$1   ABS(I1-IM-IAD2).GE.IJ .OR. I1-IM-IAD2.EQ.0)) SHARED(IJ, C1, I1
CMIC$2   , IM, IAD2, S) PRIVATE(IQ2W6E)
      DO 89170 IQ2W6E=1,IJ
         S(IAD2+IQ2W6E-1)=C1*(S(I1+IQ2W6E-1)+S(I1-IM+IQ2W6E-1))
89170 CONTINUE
   90 CONTINUE
C
C          END OF THE NG LOOP,,GO TO NEXT GRID
  100 CONTINUE
C
C          IS THE SURFACE PRESSURE TENDENCY WANTED?????
      IF( NCARDT .EQ. 0 ) GO TO 200
C
C           GIVE IT TO THEM,,,,
      CALL OUTHORIZ(IN(MIILL),IN(MIIUL),S(MSA),S(MSB),S(MSC),S(MSD),
     *              S(MSOUT1),S(MSOUT2))
C
      LABQTYPE=LABPTEN
      LABSSUB1=LABSFC
      S1VALUE=0.E0
C
      CALL OUTNULAB
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IDGRBE(8) =   3
      IDGRBE(9) =   1
      IDGRBE(10) =  0
      IDGRBE(11) =  0
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0
      IDGRBE(20) =  0
C
c     CALL OUTPACK(S(MSOUT2),IJOUT,S(MSOUT1), DESCRIPT(NCARDT),
c    1 LABEL84,IOUTUNIT)
      CALL GRIBITN (S(MSOUT2),IJOUT,S(MSOUT1), DESCRIPT(NCARDT),
     1 IDGRBE,IOUTGRIB,LABEL84)
C
  200 CONTINUE
C           IS OMEGA ON PRESSURE SURFACES WANTED???
      IF( NCARDP .EQ. 0 ) RETURN
C
      NDATA=3
      NWORK=1
      MB=MB1
      GAMTOP=0.E0
      GAMBOT=0.E0
C          DO NOT SMOOTH
      ISM=0
C
      CALL OUTSIG2P( NDATA, NWORK,MB,LABVVEL,GAMBOT,GAMTOP,ISM)
C
      RETURN
      END
