      SUBROUTINE OUTPHYS
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    OUTPHYS     OUTPUT RADIATION AND MISC GND FIELDS
C   PRGMMR: N PHILLIPS       ORG: W/NMC22    DATE: 85-12-07
C
C ABSTRACT: WHEN CALLED BY SR OUTPUT, THIS PROGRAM LOOKS AT THE
C   .       OUTPUT MENU CARD INFORMATION, AND ARRANGES THAT THE
C   .       REQUESTED FIELDS ARE INTERPOLATED TO THE CURRENT
C   .       OUTPUT GRID, GIVEN THE CORRECT O.N. 84 UNITS AND
C   .       LABEL. AND SENT TO BE PACKED FOR LATER SHIPMENT
C   .       TO THE FRONT END
C   .
C   .
C   CALLED ONLY BY SUBROUTINE OUTPUT ANY TIME AFTER
C   ARRAYS 1.0 / H  AND  H**KAPPA HAVE BEEN FILLED OUT
C
C PROGRAM HISTORY LOG:
C   85-12-07  N PHILLIPS
C   86-05-27  N PHILLIPS CHANGED BOWEN RATION TO MOISTURE
C                        AVAILABILITY
C   86-06-01  N PHILLIPS ADDED OUTPUT OF ACCUMULATED EVAPORATION
C   88-08-25  B SCHMIDT  REVISED THE DOCBLOCK
C
C USAGE:    CALL OUTPHYS
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - OUTHORIZ
C                  OUTNULAB
C                  OUTPACK
C     LIBRARY:
C       COMMON   - COMBLANK
C                  COMCONST
C                  COMOUT
C
C REMARKS:
C   THE OUTPUT FIELDS CONSIDERED ARE AS FOLLOWS
C   FIRST MENU CARD, WITH LQTYPE = 169, DOES OUTPUT FROM 'VBL'.
C   .  LEVELS(1,MCARD): ALBEDO
C   .  LEVELS(2,MCARD): DWNWARD LW RADIATION AT THE GROUND
C   .  LEVELS(3,MCARD): DWNWARD SW RADIATION ABSORBED AT GROUND
C   .  LEVELS(4,MCARD): CONVECTIVE PRECIPITATION RATE
C   .  LEVELS(5,MCARD): MOISTURE AVAILABILITY
C   .  LEVELS(6,MCARD): SURFACE EXCHANGE COEFFICIENT
C   .  LEVELS(7,MCARD): SUBSOIL TEMPERATURE
C   .  LEVELS(8,MCARD): SOIL THERMAL COEFFICIENT
C   .     LEVELS 9-20 ARE IGNORED
C   SECOND MENU CARD, WITH LQTYPE = 189, DOES OUTPUT FROM 'PHYSDIAG'
C   .  LEVELS(1,MCARD): NUMBER OF MIXED LAYERS FROM SFCMIX
C   .  LEVELS(2,MCARD): UPWARD LW RADIATION AT THE GROUND
C   .  LEVELS(3,MCARD): UPWARD LW RADIATION AT TOP OF ATMOSPHERE
C   .  LEVELS(4,MCARD): CONVECTIVE CLOUD AMOUNT
C   .  LEVELS(5,MCARD): LOW LEVEL CLOUD AMOUNT
C   .  LEVELS(6,MCARD): MIDDLE LEVEL CLOUD AMOUNT
C   .  LEVELS(7,MCARD): HIGH LEVEL CLOUD AMOUNT
C   .  LEVELS(8,MCARD): PRESSURE AT BASE OF LOW CLOUD
C   .  LEVELS(9,MCARD): PRESSURE AT BASE OF MIDDLE CLOUD
C   .  LEVELS(10,MCARD): PRESSURE AT BASE OF HIGH CLOUD
C   .  LEVELS(11,MCARD): PRESSURE AT BASE OF CONVECTIVE CLOUD
C   .  LEVELS(12,MCARD): PRESSURE AT TOP OF CONVECTIVE CLOUD
C   .  LEVELS(13,MCARD): UPWARD TURB. FLUX OF SENSIBLE HEAT AT GRND
C   .  LEVELS(14,MCARD): UPWRD TRB. FLX OF WTR AT THE GRND (=EVAP RATE)
C   .  LEVELS(15,MCARD): ACCUMULATED EVAPORATION FROM THE GROUND
C   .       LEVELS 16-20 ARE IGNORED
C   THIRD MENU CARD, WITH LQTYPE = 198:
C   .    TEMPERATURE TENDENCY DUE TO ALL RADIATION
C   .       AT SIGMA LEVELS DEFINED IN ARRAY LEVELS FOR THIS CARD
C   FOURTH MENU CARD, WITH LQTYPE = 196:
C   .    TEMPERATURE TENDENCY DUE TO LONG WAVE RADIATION
C   .       AT SIGMA LEVELS DEFINED IN ARRAY LEVELS FOR THIS CARD
C   FIFTH MENU CARD, WITH LQTYPE = 197:
C   .    TEMPERATURE TENDENCY DUE TO SHORT WAVE RADIATION
C   .       AT SIGMA LEVELS DEFINED IN ARRAY LEVELS FOR THIS CARD
C   .
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES        MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----        ----------------------------------        ---------
C   .
C   LOFCLDS      SIGMA LAYERS FOR                          COMCONST
C                CONVECTIVE, LOW, MIDDLE, AND HIGH CLDS
C   .
C   LQTYPE AND   ARRAYS DEFINING DESIRED OUTPUT FIELDS     COMOUT
C   LEVELS
C   .
C   VBL  AND     CONTAINS ARRAYS WITH DATA TO BE           BLANK
C   PHYSDIAG     OUTPUT BY THIS ROUTINE                    COMMON
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   .
C   .           ALL OUTPUT FROM THIS PROGRAM IS FUNNELED
C   .           THROUGH THE SUBROUTINE OUTPACK, AFTER
C   .           THE HORIZONTAL INTERPOLATION ROUTINE
C   .           OUTHORIZ HAS PUT THE FIELD INTO ARRAY
C   .           S(MSOUT2).   LABEL INFORMATION IS
C   .           PASSED INTO  COMOUT  BY THE SUBROUTINE
C   .           OUTNULAB
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C
C             OUTPUT THE FIELDS ASSOCIATED WITH
C             CLOUD COVER, SURFACE ALBEDO, HEAT FLUX AND
C             EVAPORATION, RADIATION FLUXES,
C             RADIATION HEATING RATES, MOISTURE AVAIL.
C             AND MISCELLANEOUS GROUND PROPERTIES
C
C            LACEV IS ARRAY NUMBER FOR ACCUM'D EVAP. IN ARRAY PHYSDIAG
C
      PARAMETER ( LACEV = 15 + IKM )
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:07:11  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
CER
      INTEGER IDGRBE(25),MGVBL(20),MG1VBL(20),MGPHY(20),MG1PHY(20)
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
      COMMON/ADDRS/MIILL,MIIUL,MSA,MSB,MSC,MSD
C
C$$$$$$$$$$$$$$$ FOR TEST PRINT OUTS
      DATA NDID/0/
C$$$$$$$$$$$$$$$
      DIMENSION S(INSUMG),FNGM(INSUMG),SIGCLDS(2,4),IN(INSUMG),
     1   CONVBL(20), MQVBL(20),   MS1VBL(20),   MS2VBL(20),
     2   C1VBL(20),  C2VBL(20),     MVBL(20),    NXVBL(20),
     3   CONPHY(20), MQPHY(20),   MS1PHY(20),   MS2PHY(20),
     4   C1PHY(20),  C2PHY(20),     MPHY(20),    NXPHY(20),
     5   CON(20,2),   MQ(20,2),    MS1(20,2),    MS2(20,2),
     6    C1(20,2),   C2(20,2),      M(20,2),     NX(20,2),
     7    MQ3(3)
      EQUIVALENCE (CON(1,1),CONVBL), (CON(1,2),CONPHY),
     1            (MQ(1,1),MQVBL  ), ( MQ(1,2),MQPHY ),
     2            (MS1(1,1),MS1VBL), (MS1(1,2),MS1PHY),
     3            (MS2(1,1),MS2VBL), (MS2(1,2),MS2PHY),
     4            (C1(1,1), C1VBL ), (C1(1,2),C1PHY),
     5            (C2(1,1),C2VBL  ), (C2(1,2),C2PHY),
     6            (M(1,1), MVBL   ), (M(1,2),  MPHY),
     7            (NX(1,1),NXVBL),  (NX(1,2),NXPHY)
C                MESSAGE FOR AN ERROR
      CHARACTER*35 ERRMSG(4)
C                O.N. 84 LABEL NUMBERS
C                FOR SINGLE LEVEL FIELDS IN VBL
      DATA MQVBL  /169, 190 ,204 ,108 ,199 ,216,  22, 209,12*0 /
      DATA MS1VBL /129, 129 ,129 ,129 ,129 ,129,   7, 129, 12*0 /
C
C                GRIB PDS LABEL NUMBERS
C                FOR SINGLE LEVEL FIELDS IN VBL
      DATA MGVBL  / 84, 205, 255, 214, 207, 208,  85, 255, 12*0/
      DATA MG1VBL /  1,   1, 255,   1,   1,   1, 111, 255, 12*0/
      DATA  C1VBL /20*0.E0/
      DATA MS2VBL /20*0/
      DATA  C2VBL /20*0.E0/
      DATA   MVBL /20*0/
      DATA  NXVBL /8,15,16,17,18,19,21,22,12*1/
      DATA CONVBL /1.E0,3*1.E3,1.E0,1.E3,1.E0,1.E3,12*0.E0/
C
C                O.N. 84 LABEL NUMBERS
C                FOR SINGLE LEVEL FIELDS IN PHYSDIAG
      DATA MQPHY  /189,191,191,211,210,210,210,212,212,212,214,
     1             215,194,195,117,5*0/
      DATA MS1PHY /2*129,10*148,3*129,5*0/
C
C                GRIB LABEL NUMBERS
C                FOR SINGLE LEVEL FIELDS IN PHYSDIAG
      DATA MGPHY  /209,212,212, 72,213,213,213,  1,  1,  1,  1,
     1               1,122,121, 57,5*0/
      DATA MG1PHY /  1,  1,107,108,108,108,108,108,115,115,115,
     1             115,  1,  1,  1,5*0/
      DATA  C1PHY /20*0.E0/
      DATA MS2PHY /3*0,9*148,8*0/
      DATA  C2PHY /20*0.E0/
      DATA   MPHY /3*0,9*2,8*0/
      DATA  NXPHY /24,25,26,27,28,29,30,31,32,33,34,35,36,37,39,5*1/
      DATA CONPHY /1.E0,2*1.E3,4*1.E0,7*1.E3,1.E0,5*0.E0/
C
C      NUMBER OF SINGLE LEVEL FIELDS FROM VBL AND FROM PHYSDIAG
      DATA NUMBVBL/8/,NUMBPHY/15/
C          Q TYPES FOR 3-DIMENSIONAL ARRAYS
      DATA MQ3/198,196,197/
C           OUTPUT CODE WORKING SPACE IN ARRAYS  S  AND  FNGM  .
      EQUIVALENCE (SCR(1,1),S(1),FNGM(1),IN(1) )
C
      DATA ICALL/0/
C
C------ENTRANCE
C
C------ENTRANCE
      IF(ICALL .GT. 0 ) GO TO 2
C
C                NOMINAL DEPTH FOR SUBSOIL TEMPERATURE
C     C1VBL(7) = 999.E0
      C1VBL(7) = 1.E0
C
C            ESTABLISH SIGMA VALUES (1 AT GRND, 0 AT TOP OF ATMOS)
C            FOR CLOUD LAYERS
CMIC$ DO ALL VECTOR SHARED(LOFCLDS, SIGINT, SIGCLDS) PRIVATE(NCLD, LYR)
      DO 1 NCLD = 1,4
C            SIGMA AT BOTTOM OF BOTTOM CLOUD LAYER
      LYR = LOFCLDS(1,NCLD)
      SIGCLDS(1,NCLD) = 1.E0- SIGINT(LYR)
C            SIGMA AT TOP OF TOP CLOUD LAYER
      LYR = LOFCLDS(2,NCLD)
      SIGCLDS(2,NCLD) = 1.E0 - SIGINT(LYR+1)
    1 CONTINUE
C            DISTRIBUTE TO C1PHY AND C2PHY TABLES
C                CONVECTIVE CLOUDS
      C1PHY(4) = SIGCLDS(2,1)
      C1PHY(11) = C1PHY(4)
      C1PHY(12) = C1PHY(4)
      C2PHY(4) = SIGCLDS(1,1)
      C2PHY(11) = C2PHY(4)
      C2PHY(12) = C2PHY(4)
C
C                LOW CLOUDS
      C1PHY(5) = SIGCLDS(2,2)
      C1PHY(8) = C1PHY(5)
      C2PHY(5) = SIGCLDS(1,2)
      C2PHY(8) = C2PHY(5)
C
C                MIDDLE CLOUDS
      C1PHY(6) = SIGCLDS(2,3)
      C1PHY(9) = C1PHY(6)
      C2PHY(6) = SIGCLDS(1,3)
      C2PHY(9) = C2PHY(6)
C
C                HIGH CLOUDS
      C1PHY(7) = SIGCLDS(2,4)
      C1PHY(10) = C1PHY(7)
      C2PHY(7) = SIGCLDS(1,4)
      C2PHY(10) = C2PHY(7)
C-------------------------------------------------------------
C-------------------------------------------------------------
    2 CONTINUE
C                     SAVE EXISTING LABELS FROM MAIN OUTPUT CODE
      LABQT9 = LABQTYPE
      LABS19 = LABSSUB1
      LABS29 = LABSSUB2
      S1SAVE = S1VALUE
      S2SAVE = S2VALUE
      LMSAVE = LABMLDIF
C
C             ENTER LOOP FOR MENU CARDS FROM VBL AND FROM
C                PHYSDIAG ARRAYS
C              THE NUMBER OF SINGLE ARRAYS FROM ARRAY VBL
      NUMSING = NUMBVBL
      DO 90 NZ= 1,2
C              FIND MENU CARD FOR SINGLE ARRAYS
      LQLOOK = MQ(1,NZ)
      DO 5 N = 1,NOUTVBLS
      NCARD = N
      IF( LQTYPE(N) .EQ. LQLOOK ) GO TO 10
    5 CONTINUE
C
C              NO MENU CARD,, GO TO END OF NZ LOOP
      GO TO 90
C
   10 CONTINUE
C            ENTER LOOP ON THE SEQUENCE OF SINGLE FIELDS
      DO 40 N = 1,NUMSING
C
      IF( LEVELS(N,NCARD) .LE. 0 ) GO TO 40
C                  THIS ARRAY IS DESIRED
        DO 30 NN = 1,NUMGDREQ
        NG = NGRIDATA(NN)
        IM = IMG(NG)
        JM = JMG(NG)
        IJ = IM * JM
C            ADDRESS FOR THIS GRID IN STAGING ARRAY FNGM
        IADF = JADDFNGM(NG)
C             DO WE FETCH FROM ARRAY VBL OR FROM ARRAY PHYSDIAG?
        IF( NZ .EQ. 2 ) GO TO 25
C
C               FETCH FROM VBL AND MULTIPLY BY CONSTANT FOR
C                 O.N. 84 UNITS
C               ADDRESS IN VBL
             IADVBL = IADDRG(NX(N,1),NG)
CMIC$ DO ALL VECTOR SHARED(IJ, N, IADVBL, IADF, CON, VBL, FNGM) PRIVATE(
CMIC$1   IQ2W6E)
      DO 88890 IQ2W6E=1,IJ
         FNGM(IADF+IQ2W6E-1)=CON(N,1)*VBL(IADVBL+IQ2W6E-1)
88890 CONTINUE
             GO TO 30
C
C
C              FETCH FROM ARRAY PHYSDIAG
C              ARRAY IN PHYSDIAG
   25        NARRAY = NX(N,2)
             IADXXX = IADDRG(NX(N,2),NG)
CMIC$ DO ALL VECTOR SHARED(IJ, N, IADXXX, IADF, CON, VBL, FNGM) PRIVATE(
CMIC$1   IQ2W6E)
      DO 88900 IQ2W6E=1,IJ
         FNGM(IADF+IQ2W6E-1)=CON(N,2)*VBL(IADXXX+IQ2W6E-1)
88900 CONTINUE
C
   30   CONTINUE
C                 HAVE DATA FROM ALL NEEDED ARRAYS,,,,
C                 DO HORIZONTAL INTERPOLATION TO OUTPUT GRID
            CALL OUTHORIZ(IN(MIILL),IN(MIIUL),S(MSA),S(MSB),
     *              S(MSC),S(MSD),S(MSOUT1),S(MSOUT2))
C               UPDATE THE LABEL
      LABQTYPE = MQ(N,NZ)
      LABSSUB1 = MS1(N,NZ)
      S1VALUE  = C1(N,NZ)
      LABSSUB2 = MS2(N,NZ)
      S2VALUE  = C2(N,NZ)
      LABMLDIF = M(N,NZ)
C               ACCUMULATED EVAP REQUIRES LABTMARK = 3
      IF( NZ.EQ.2 .AND. N.EQ.15 ) LABTMARK = 3
C
            CALL OUTNULAB
C
C  SET UP PDS INFO
C
      CALL LAB2PDS(LABEL84,IDGRBE)
C
      IDGRBE(7) =    0
      IF(NZ.EQ.1) THEN
        IDGRBE(8) = MGVBL(N)
        IDGRBE(9) = MG1VBL(N)
      ELSE
        IDGRBE(8) = MGPHY(N)
        IDGRBE(9) = MG1PHY(N)
      ENDIF
C
      IF(IDGRBE(9).EQ.1) THEN
        IDGRBE(10) =   0
        IDGRBE(11) =   0
      ELSEIF(IDGRBE(9).EQ.107) THEN
        IDGRBE(10) = 0
        ALEV1 = REAL(LABEL84(5))
        ARGL1 = REAL(LABEL84(6))
        XLEV1 = ALEV1 * 10.**ARGL1
        IDGRBE(11) =  INT((XLEV1*10000.)+0.5)
      ELSEIF(IDGRBE(9).EQ.108) THEN
        ALEV1 = REAL(LABEL84(5))
        ARGL1 = REAL(LABEL84(6))
        XLEV1 = ALEV1 * 10.**ARGL1
        IDGRBE(10) =  INT((XLEV1*100.)+0.5)
        ALEV2 = REAL(LABEL84(12))
        ARGL2 = REAL(LABEL84(13))
        XLEV2 = ALEV2 * 10.**ARGL2
        IDGRBE(11) =  INT((XLEV2*100.)+0.5)
      ELSEIF(IDGRBE(9).EQ.111) THEN
        IDGRBE(10) = 0
        IDGRBE(11) = 100
      ENDIF
C
      IF(IDGRBE(8).EQ.57) THEN
       IDGRBE(18) =  LABEL84(3) - LABEL84(10)
       IDGRBE(19) =  LABEL84(3)
       IDGRBE(20) =  5
      ELSE
       IDGRBE(18) =  LABEL84(3)
       IDGRBE(19) =  0
       IDGRBE(20) =  0
      ENDIF
C
C  SKIP ANY ON84 VARIABLE NOT DEFINED IN GRIB
C
      IF(IDGRBE(8).EQ.255) GO TO 40
C
C                SEND TO PACKER
c       CALL OUTPACK(S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
c    1               LABEL84,IOUTUNIT )
        CALL GRIBITN (S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
     1               IDGRBE,IOUTGRIB,LABEL84 )
C          DONE WITH THIS OUTPUT FIELD, RESTORE LABTMARK TO ZERO
      LABTMARK = 0
   40 CONTINUE
C             DONE WITH THIS MENU CARD OF SINGLE ARRAYS
C             SET UP FOR NUMBER OF SINGLE ARRAYS FROM ARRAY PHYSDIAG
      NUMSING = NUMBPHY
C              END OF LOOP ON THE TWO SINGLE ARRAY MENU CARDS
   90 CONTINUE
C
C           START ON THE RADIATIVE RATES OF TEMPERATURE CHANGE
C---------------------------------------------------------------
  100 CONTINUE
C           START ON 3-DIMENSIONAL TEMPERATURE TENDENCY ARRAYS
C                ADDRESS FOR A SCRATCH ARRAY
      IADSC = JSCR2(1)
C
C   A DO-LOOP TO GET D(TEMP)/D(TIME) DUE TO FOLLOWING RADIATION
C              N=1: ALL RADIATION
C              N=2: LONG WAVE RADIATION
C              N=3: SHORT WAVE RADIATION
      DO 120 N=1,3
      LQLOOK = MQ3(N)
        DO 102 NW = 1,NOUTVBLS
        NCARD = NW
        IF(LQTYPE(NW) .EQ. LQLOOK ) GO TO 104
  102   CONTINUE
C               NO CARD FOR THIS FIELD
      GO TO 120
C
  104 CONTINUE
      LWANT = 0
      DO 1001 IQ2 = 1, 20
         LWANT = LWANT + LEVELS(IQ2,NCARD)
1001  CONTINUE
      IF( LWANT .LE. 0 ) GO TO 120
C                 SOME LEVELS ARE WANTED FOR THIS FIELD
        DO 115 L = 1,KM
        IF( LEVELS(L,NCARD) .LE. 0 ) GO TO 115
C              WANT LEVEL L, GET IT FROM ALL NECESSARY NGM GRIDS
          DO 110 NN = 1,NUMGDREQ
          NG = NGRIDATA(NN)
          IM = IMG(NG)
          JM = JMG(NG)
          IJ = IM*JM
C            ADDRESS FOR STAGING AREA FNGM
          IADF = JADDFNGM(NG)
C            ADDRESS FOR  1 / H
          IADREC = JHREC(NG)
C            ADDRESS FOR  H**KAPPA
          IADKAP = JHKAP(NG)
C            ADDRESS OF LEVEL L IN D(H*THETA)/D(TIME) ARRAY IN VBL
          IADSWR = IADDRG(14,NG) + (L-1)*IJ
          IADLWR = IADDRG(38,NG) + (L-1)*IJ
C             LEVEL L ARRAY IN D(H*THETA)/D(TIME) ARRAY
C            (DUE TO LONG-WAVE RADN) IN PHYSDIAG
          NARRAY = 14 + L
C             CONSTANT TO GIVE P**KAPPA IN LAYER L
          CONST = 2.E0 * PR(L)
C               PUT  PRESS**KAPPA   /   H   INTO S(IADSC)
CMIC$ DO ALL VECTOR IF ((ABS(IADKAP-IADSC).GE.IJ .OR. IADKAP-IADSC.EQ.0)
CMIC$1    .AND. (ABS(IADSC-IADREC).GE.IJ .OR. IADSC-IADREC.EQ.0))
CMIC$2    SHARED(IJ, CONST, IADKAP, IADSC, IADREC, S) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E=1,IJ
         S(IADSC+IQ2W6E-1)=CONST*S(IADKAP+IQ2W6E-1)
         S(IADSC+IQ2W6E-1)=S(IADSC+IQ2W6E-1)*S(IADREC+IQ2W6E-1)
88910 CONTINUE
C              ALL RADIATION
          IF ( N .EQ. 1 ) THEN
CMIC$ DO ALL VECTOR SHARED(IJ, IADSWR, IADLWR, IADF, IADSC, VBL, FNGM, S
CMIC$1   ) PRIVATE(IQ2W6E)
      DO 88930 IQ2W6E=1,IJ
         FNGM(IADF+IQ2W6E-1)=VBL(IADSWR+IQ2W6E-1)+VBL(IADLWR+IQ2W6E-1)
         FNGM(IADF+IQ2W6E-1)=S(IADSC+IQ2W6E-1)*FNGM(IADF+IQ2W6E-1)
88930 CONTINUE
          END IF
C              LONG WAVE RADIATION
          IF( N.EQ.2 )THEN
CMIC$ DO ALL VECTOR SHARED(IJ, IADSC, IADLWR, IADF, S, VBL, FNGM)
CMIC$1    PRIVATE(IQ2W6E)
      DO 88950 IQ2W6E=1,IJ
         FNGM(IADF+IQ2W6E-1)=S(IADSC+IQ2W6E-1)*VBL(IADLWR+IQ2W6E-1)
88950 CONTINUE
      END IF
C              SHORT WAVE RADIATION
          IF( N.EQ.3 )THEN
CMIC$ DO ALL VECTOR SHARED(IJ, IADSC, IADSWR, IADF, S, VBL, FNGM)
CMIC$1    PRIVATE(IQ2W6E)
      DO 88960 IQ2W6E=1,IJ
         FNGM(IADF+IQ2W6E-1)=S(IADSC+IQ2W6E-1)*VBL(IADSWR+IQ2W6E-1)
88960 CONTINUE
      END IF
C
  110     CONTINUE
C             STAGING ARRAY FNGM IS NOW COMPLETE, INTERPOLATE
        CALL OUTHORIZ(IN(MIILL),IN(MIIUL),S(MSA),S(MSB),S(MSC),
     *                S(MSD),S(MSOUT1),S(MSOUT2))
C              UPDATE THE LABEL
        LABQTYPE = LQLOOK
        LABSSUB1 = 148
        S1VALUE = PRESS(L)
        LABSSUB2 = 0
        S2VALUE = 0.E0
        LABMLDIF = 0
        CALL OUTNULAB
C
C  SET UP PDS INFO
C
C  HARDWIRE IDGRBE(8)=216 (TEMP TENDENCY BY ALL RADIATION) SINCE
C  TEMP TENDENCY DUE TO SHORT WAVE AND LONG WAVE RADIATION IS NOT
C  DEFINED IN GRIB AND NOT POSTED BY THE NGM ANYWAY
C
      CALL LAB2PDS(LABEL84,IDGRBE)
      IDGRBE(7) =   0
      IDGRBE(8) =   216
      IDGRBE(9) =   107
      IDGRBE(10) =  0
      ALEV1 = REAL(LABEL84(5))
      ARGL1 = REAL(LABEL84(6))
      XLEV1 = ALEV1 * 10.**ARGL1
      IDGRBE(11) =  INT((XLEV1*10000.)+0.5)
      IDGRBE(18) =  LABEL84(3)
      IDGRBE(19) =  0
      IDGRBE(20) =  0

C                SEND TO PACKER
c       CALL OUTPACK(S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
c    1               LABEL84,IOUTUNIT )
        CALL GRIBITN(S(MSOUT2),IJOUT,S(MSOUT1),DESCRIPT(NCARD),
     1               IDGRBE,IOUTGRIB,LABEL84 )
C
C           DONE WITH THIS LEVEL FOR THIS CARD
  115   CONTINUE
C           DONE WITH ALL LEVELS FOR THIS CARD
  120 CONTINUE
C           DONE WITH ALL THREE D(TEMP)/D(TIME) ARRAYS
C
C             RESTORE ORIGINAL LABEL VALUES
      LABQTYPE = LABQT9
      LABSSUB1 = LABS19
      LABSSUB2 = LABS29
      S1VALUE  = S1SAVE
      S2VALUE  = S2SAVE
      LABMLDIF = LMSAVE
C
      ICALL = ICALL + 1
C
C
      RETURN
      END
