      SUBROUTINE PHYSICS ( NG , NPAIR, LASTSTEP,LADD3,LEN31, DTIME )
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    PHYSICS     DO THE PHYSICS FOR A SINGLE GRID NG
C   PRGMMR: J.J. TUCCILLO    ORG:W/NMC4     DATE: 90-06-22
C
C ABSTRACT: THIS ROUTINE DOES THE PHYSICS FOR A SINGLE GRID.
C
C PROGRAM HISTORY LOG:
C   90-06-22  J.J. TUCCILLO
C
C USAGE:    CALL PHYSICS( NG, NPAIR, LASTSTEP )
C   INPUT ARGUMENT LIST:
C     NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C      NG         GRID NUMBER (OUTER HEMISPHERIC GRID HAS   ARGUMENT
C                 NG EQUAL TO 1.)
C      NPAIR      1 FOR THE FIRST OF A PAIR OF CALLS TO     ARGUMENT
C                 THIS GRID, 2 FOR THE SECOND OF A PAIR.
C
C      LASTSTEP   A FLAG WHICH WHEN EQUAL TO 1 INDICATES
C                 THAT THIS IS THE LAST STEP FOR THIS
C                 GRID WITHIN A COMPLETE (GRID A)
C                 TIME STEP.                                ARGUMENT
C
C       LADD3,    STARTING ADDRESS AND VECTOR LENGTH        ARGUMENT
C       LEN31     FOR COMPUTATIONS TO BE MADE BY PRECIP
C
C      DTIME      LENGTH OF TIME STEP IN SECONDS FOR THIS   ARGUMENT
C                                                    GRID
C
C      VBL        ARRAY CONTAINING ALL VBLS FOR ALL GRIDS   COMMON
C
C      BITGRDX    (X = H, U, V) BIT VECTORS TO CONTROL      COMMON
C                 STORAGE OF UPDATED VBLS ONLY AT
C                 LEGITIMATE FORECAST POINTS.
C
C      BITSEA     BIT VECTOR (1 OVER WATER) TO ALLOW DIFF.  COMMON
C                 TREATMENTS OF SURFACE EXCHANGES.
C
C      IMG,JMG    HORIZONTAL DIMENSIONS OF ALL GRIDS.       COMMON
C
C      KM         NUMBER OF HORIZONTAL LVLS. FOR ALL GRIDS  COMMON
C
C      NH         NH + 0.5 IS THE NUMBER OF GRID INTERVALS  COMMON
C                 ON GRID 1 BETWEEN POLE AND EQUATOR.
C
C      IADDRG     INITIAL ADDRESSES IN VBL FOR EACH TYPE    COMMON
C                 OF DATA FOR EACH GRID.
C
C      DELSIG     VERTICAL SIGMA DIFFS. ACROSS EACH LAYER   COMMON
C
C      SIGINT     SIGMA VALUES AT THE KM + 1 INTERFACES.    COMMON
C
C      PR         HALF OF (1-SIGMA) TO THE KAPPA POWER.     COMMON
C
C      NTIME      TIME STEP(ADVANCES BY ONE FOR EACH STEP   COMMON
C                 ON THE OUTER GRID(NG = 1) ).
C
C     BLKDR       LENGTH USED IN BLACKADAR PROFILE OF       COMMON
C                  MIXING LENGTH
C
C   OUTPUT ARGUMENT LIST:
C     NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C       VBL        UPDATED VARIABLES.                        COMMON
C
C   SUBPROGRAMS CALLED:
C     NAME(S)                                               LIBRARY
C     -------                                               -------
C     DRYADB
C     P2KAP
C     PRECIP
C     SFCEXCH
C     SFCMIX
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C
C     PROGRAM TO DO PHYSICS FOR GRID NG
C
C
C        PARAMETER VALUES FOR EQUIVALENCING
      PARAMETER(NAME2 = 1 + IIJMAX, NAME3 = 1 + 2 * IIJMAX ,
     1      NAME4 = 1 + 3 * IIJMAX, NAME5 = 1 + 4 * IIJMAX ,
     2      NAME6 = 1 + 5 * IIJMAX, NAME7 = 1 + 6 * IIJMAX ,
     3      NAME8 = 1 + 7 * IIJMAX, NAME9 = 1 + 8 * IIJMAX ,
     4      NAME10= 1 + 9 * IIJMAX, NAME11= 1 + 10* IIJMAX ,
     5      NAME12= 1 + 11* IIJMAX, NAME13= 1 + 12* IIJMAX ,
     6      NAME14= 1 + 13* IIJMAX )
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:53:30  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      REAL R1S
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMDIAG/ CONTAINS QUANTITIES SAVED FOR
C          DIAGNOSTIC PURPOSES.
      COMMON /COMDIAG/  KADIAB( IKM, INGRDUSE ),
     1                  NPTSDHQ (2, INGRDUSE),
     2                  KKCLOUD2(2, INGRDUSE), NPTSBUOY(2, INGRDUSE),
     3                  NPTSWATR(2, INGRDUSE), NPTSCC  (2, INGRDUSE),
     4                  KKGSP2  (2, INGRDUSE),
     5                  KKGSE2  (2, INGRDUSE),
     6                  NPTSSAT (IKM, 2, INGRDUSE),
     7                  NPTSEVAP(IKM, 2, INGRDUSE),
     8                  NPTSGSP (2, INGRDUSE), NUMPROF,
     9                  PPTCC   (2, INGRDUSE), PPTGSP  (2, INGRDUSE),
     1                  ALATPR  (IMAXPROF),    ALONPR  (IMAXPROF),
     2                  DESCRP  (IMAXPROF)
C
      CHARACTER*24 DESCRP
C
C              HORIZONTAL SCRATCH ARRAYS.
      DIMENSION  S1(IIJMAX),  S2(IIJMAX),  S3(IIJMAX),  S5(IIJMAX),
     1           DENSITY(IIJMAX),
     2           SPD(IIJMAX),    HREC(IIJMAX),  HKAPPA(IIJMAX) ,
     3           PSKAPR(IIJMAX), CD(IIJMAX),    T1(IIJMAX),
     4           TAUXC(IIJMAX),  TAUYC(IIJMAX), KMIX(IIJMAX)
C
      DIMENSION D1(IIJKMAX),D2(IIJKMAX),D3(IIJKMAX),DHQ(IIJKMAX),
     1D5(IIJKMAX),D7(IIJKMAX),D8(IIJKMAX),D9(IIJKMAX),D10(IIJKMAX)
C
C              LOCAL ARRAYS
      DIMENSION ZLYR(IKM), ELSQ(IKM),DSIGMIN(IKM)
C
      LOGICAL BITAUS(IIJMAX)
C
      DIMENSION ABITGRDU(IIJMAX, 2, INGRDUSE),
     *          ABITGRDV(IIJMAX, 2, INGRDUSE),
     *          ABITGRDH(IIJMAX, 2, INGRDUSE)
C
C--------------THREE-DIMENSIONAL SCRATCH ARRAY EQUIVALENCES FOR
C     (D1,----D10) PLUS ARRAY DHQ (WHICH IS IN SCR3(1,4). )
C           NOTE SCR3(N,6) IS USED FOR 2-DIMENSIONAL SCRATCH ARRAYS.
      EQUIVALENCE  (SCR3(1,1),D1), (SCR3(1,2),D2), (SCR3(1,3),D3),
     1             (SCR3(1,4),DHQ), (SCR3(1,5),D5),
     2             (SCR3(1,7),D7),  (SCR3(1,8),D8),(SCR3(1,9),D9),
     3             (SCR3(1,10),D10)
C
C--------------HORIZONTAL SCRATCH ARRAY EQUIVALENCES
C         FCST CODE ASSUMES THERE ARE AT LEAST 15 LAYERS IN THE
C         THE VERTICAL.  THEREFORE IT IS SAFE TO USE THE FIRST
C         15 HORIZONTAL ARRAYS IN THE UNUSED 3-D  ARRAY SCR3(1,6).
      EQUIVALENCE (SCR3(1,6   ), S1   ), (SCR3(NAME2,6), S2    ),
     1          (SCR3(NAME3,6), S3   ),  (SCR3(NAME4,6),TAUXC),
     2          (SCR3(NAME5,6),TAUYC),(SCR3(NAME6,6), DENSITY),
     3          (SCR3(NAME7,6),SPD     ),(SCR3(NAME8,6), HREC   ),
     4          (SCR3(NAME9,6), HKAPPA), (SCR3(NAME10,6),PSKAPR),
     5          (SCR3(NAME11,6),CD    ), (SCR3(NAME12,6), T1    ),
     6          (SCR3(NAME13,6),S5),     (SCR3(NAME14,6),KMIX  )
C************* NOTE THAT KMIX IS AN INTEGER ARRAY *****************
C
C          ARRAYS USED IN CALCULATING VISCOUS TIME STEP LIMITS
      DIMENSION NUMSTEP(INGRDUSE), AMAX(IKM,INGRDUSE)
C
C        INTEGERS FOR PRINTING OUT AUSTAUSCH ON POINT IEX,JEX OF
C               FINEST GRID
      INTEGER I
      REAL COFD1,COFD2,COFD3,COFD4,COFN1,COFN2,COFN3
      PARAMETER (COFD1 = 1., COFD2 = 5.44053037, COFD3 = 2.27693825, 
     1   COFD4 = -0.0869930591, COFN1 = 0.34757549, COFN2 = 4.36732956, 
     2   COFN3 = 3.91557032)
      DATA ITEX/0/,IDTEX/10800/,IEX/87/,JEX/37/
C
C           FLAG FOR DIAGNOSTIC PRINTS OF AUSTAUSCH  (0 TO SKIP )
      DATA IPAUST/0/
C          VON KARMAN CONSTANT ( NON-DIMENSIONAL )
      DATA VONK/ 0.4E0 /
C
C          FLAG TO USE CONSTANT OR PRANDTL-V KARMAN NEUTRAL
C           AUSTAUSCH PROFILE   (IPVK=1 FOR LATTER)
      DATA IPVK /0/
C
C          FLAG FOR DOING EXCHANGE COEFF ADJUSTMENT AT TOP OF MIXED
C               LAYER( 0 = DON'T,  1 = DO IT )
      DATA MIXADJ /0/
C
      DATA ICALL /0/
C
C
C------------------------------------------------------------------
C
C
C
C------------------------------------------------------------------
C
      IF( ICALL .GT. 0 ) GO TO 35
C
CMIC$ DO ALL VECTOR SHARED(BITGRDU, ABITGRDU, BITGRDV, ABITGRDV, BITGRDH
CMIC$1   , ABITGRDH) PRIVATE(IQ2)
      DO 1234 IQ2 = 1, IIJMAX * 2 * INGRDUSE
         IF ( BITGRDU(IQ2,1,1) ) THEN
              ABITGRDU(IQ2,1,1) = 1.
         ELSE
              ABITGRDU(IQ2,1,1) = 0.
         END IF
         IF ( BITGRDV(IQ2,1,1) ) THEN
              ABITGRDV(IQ2,1,1) = 1.
         ELSE
              ABITGRDV(IQ2,1,1) = 0.
         END IF
         IF ( BITGRDH(IQ2,1,1) ) THEN
              ABITGRDH(IQ2,1,1) = 1.
         ELSE
              ABITGRDH(IQ2,1,1) = 0.
         END IF
1234  CONTINUE
C
C
C       CHECK THAT 3-DIM ARRAYS ARE BIG ENOUGH FOR EQUIVALENCING
C              THE TWO DIMENSIONAL SCRATCH ARRAYS
      IF( KM .LT. 15) THEN
         PRINT 1,KM
1        FORMAT(1H0,2X,'**** MUST STOP IN PHYSICS BECAUSE KM =',I5,
     *   ' AND THIS IS LESS THAN 15')
         CALL EXIT(16)
      END IF
C
C            INITIALIZE NUMBER OF STEPS IN ARRAY NUMSTEP TO ONE
CMIC$ PARALLEL SHARED(KM, DELSIG, DSIGMIN, NGRDUSE, NUMSTEP) PRIVATE(K, 
CMIC$1   DB, DL, N)
CMIC$ DO PARALLEL VECTOR
      DO 5 N = 1,NGRDUSE
      NUMSTEP(N) = 1
    5 CONTINUE
C
C-------------------COMPUTE VERTICAL FUNCTIONS
C
C                WILL NEED SQUARE OF SMALLEST DELTA SIGMA ADJACENT
C                    TO EACH INTERFACE FOR K=2,KM
CMIC$ DO PARALLEL VECTOR
      DO 19 K = 2,KM
      DB = DELSIG(K-1)
      DL = DELSIG(K)
      IF(DL.LT.DB) DB = DL
      DSIGMIN(K) = DB*DB
   19 CONTINUE
CMIC$ END PARALLEL
C
C--------- COMPUTE ZLYR(K) = APPROX HEIGHT ABOVE GROUND OF LYRS.
C            USE A SIMPLE STANDARD ATMOSPHERE FOR TEMP AND HEIGHT
C
C            TEMPERATURE AT 1000 MBS
      T0 = 288.E0
C            TROPOPAUSE PRESSURE / 1000 MBS
      PTR = 0.25E0
C             ZTR= -LOG(P/1000MBS) AT TROPOPAUSE
      ZTR = - ALOG(PTR)
C             TEMPERATURE AT TROPOPAUSE
      TTR = T0 - 70.E0
C             LAPSE RATE IN TROPOSPHERE W/R TO  Z = -LOG(P/1000)
      BB = (T0 - TTR) / ZTR
      CONST = 287.05E0 / 9.81E0
C            TROPOPAUSE HEIGHT IN METERS
      HTR = CONST * ZTR * (T0 - 0.5E0 * BB * ZTR )
C
C             ELSQ IS SQUARE OF MIXING LENGTH
      ELSQ(1 ) = 0.E0
C
      DO 30 K=1,KM
C          PUT HEIGHT OF LEVEL K INTO ZLYR
      Z = - ALOG( PRESS(K) )
      IF( Z .LT. ZTR ) ZLYR(K) = CONST * Z * ( T0 - 0.5E0 * BB * Z )
      IF( Z .GE. ZTR ) ZLYR(K) = HTR + CONST * TTR * ( Z - ZTR )
C
C           COMPUTE SQUARE OF MIXING LENGTH AT INTERFACES K=2,KM
      IF( K .EQ. 1 ) GO TO 20
      Z = -ALOG(1.E0 - SIGINT(K) )
      IF( Z .LT. ZTR ) HGT = CONST * Z * ( T0 - 0.5E0 * BB * Z )
      IF( Z .GE. ZTR ) HGT = HTR + CONST * TTR * ( Z - ZTR )
      EL1 = VONK * HGT
C               BLKDR IS THE BLACKADAR LENGTH ( METERS )
C               DEFINING A LIMITING HEIGHT FOR A PROFILE OF
C               MIXING LENGTH
      EL = EL1 / ( 1.E0 + (EL1/BLKDR) )
      ELSQ(K) = EL * EL
   20 CONTINUE
C
   30 CONTINUE
C                 END OF SET UP WORK ON FIRST ENTRANCE
   35 CONTINUE
      ICALL = ICALL + 1
C------------------------------------------------------------
C
C
      IM = IMG(NG)
      JM = JMG(NG)
      IJ = IM * JM
C
C------------- APPLY RADIATIVE HEATING IF AVAILABLE
C
      IADSWR = IADDRG(14,NG)
      IADLWR = IADDRG(38,NG)
      IADHTH = IADDRG(3,NG)
C
      IF( ICALLRAD .NE. 1 ) GO TO 45
C
      DO 40 K=1,KM
CMIC$ DO ALL VECTOR IF ((ABS(IADHTH-IADSWR).GE.IJ .OR. IADHTH-IADSWR.EQ.
CMIC$1   0) .AND. (ABS(IADHTH-IADLWR).GE.IJ .OR. IADHTH-IADLWR.EQ.0))
CMIC$2    SHARED(IJ, IADHTH, NPAIR, NG, DTIME, IADSWR, IADLWR, VBL, 
CMIC$3   ABITGRDH) PRIVATE(IQ2)
      DO 88890 IQ2=1,IJ
         VBL(IADHTH+IQ2-1)=VBL(IADHTH+IQ2-1)+
     *   ABITGRDH(IQ2,NPAIR,NG)*
     *   DTIME*(VBL(IADSWR+IQ2-1)+VBL(IADLWR+IQ2-1))
88890 CONTINUE
      IADSWR = IADSWR+IJ
      IADLWR = IADLWR+IJ
      IADHTH = IADHTH + IJ
   40 CONTINUE
C
   45 CONTINUE
C
C------------- NOW START ON THE VERTICAL MIXING AND TURBULENCE
C
C               NEED THE RECIPROCAL OF SFC PRESS "H"
C
      CONST = 100.E0 / 287.05E0
      IADH = IADDRG(5,NG)
      IADU = IADDRG(1,NG)
      IADV = IADDRG(2,NG)
      IADT = IADDRG(3,NG)
C*****  Code Expanded From Routine:  P2KAP
CMIC$ DO ALL VECTOR SHARED(IJ, IADH, VBL, HKAPPA) PRIVATE(I)
      DO 77052 I = 1, IJ
         HKAPPA(I) = (0.34757549+VBL(I+IADH-1)*(4.36732956+VBL(I+IADH-1)
     1      *3.91557032))/(1.+VBL(I+IADH-1)*(5.44053037+VBL(I+IADH-1)*(
     2      2.27693825+VBL(I+IADH-1)*(-0.0869930591))))
77052 CONTINUE
C*****  End of Code Expanded From Routine:  P2KAP
CMIC$ DO ALL VECTOR SHARED(IJ, IADH, IADU, IM, IADV, IADT, CONST, VBL, 
CMIC$1   HREC, S2, SPD, HKAPPA, T1, DENSITY) PRIVATE(IQ2)
      DO 88900 IQ2=1,IJ
         HREC(IQ2)=1.E0/VBL(IADH+IQ2-1)
C              GET U-VELOCITY IN BOTTOM LAYER AT H POINTS
         S2(IQ2)=
     *  (0.5E0*(VBL(IADU+IQ2-1)+VBL(IADU-IM+IQ2-1))*
     *   HREC(IQ2)) **2 +
C              GET V-VELOCITY IN BOTTOM LAYER AT H POINTS
     *   (0.5E0*(VBL(IADV+IQ2-1)+VBL(IADV+IQ2-2))*
     *   HREC(IQ2)) ** 2
C          WILL SAVE SQUARE OF SPEED IN ARRAY S2
         SPD(IQ2) = SQRT( S2 ( IQ2 ) )
         T1(IQ2)=VBL(IADT+IQ2-1)*HREC(IQ2)*
     *      HKAPPA(IQ2)
C            GET SURFACE DENSITY
         DENSITY(IQ2)=CONST*VBL(IADH+IQ2-1)/
     *      T1(IQ2)
88900 CONTINUE
C
C---------------USE SR SFCEXCH TO GET THE SURFACE EXCHANGE
C                  AND THE DRAG COEFFICIENT
C
        CALL SFCEXCH( NG, SPD, DENSITY, CD )
C
C           WILL WANT ADDRESS OF SURFACE EXCHANGE COEFFICIENT
      IADEX = IADDRG(19,NG)
C
C          PREPARE TO CALL SFC MIXING PROGRAM
C
C---------MECHANICAL WORK TERM IS DENSITY TIMES CUBE OF
C           FRICTION VELOCITY, AND LATTER IS SQUARE ROOT OF
C           DRAG COEFFICIENT TIMES SPEED.
C               SQ ROOT OF CD
C           MULTIPLY BY EXCH COEFF ( = DENSITY * CD * SPD )
      IADTG = IADDRG(6,NG)
      CONST = 1005.E0
CMIC$ DO ALL VECTOR SHARED(IJ, IADEX, CONST, IADTG, CD, VBL, S2, S1, T1)
CMIC$1    PRIVATE(IQ2)
      DO 89020 IQ2=1,IJ
         S1(IQ2) = SQRT( CD ( IQ2) ) *
     *        VBL(IADEX+IQ2-1) * S2(IQ2)
C           S2 HAS SQUARE OF SPEED
C         ( ARRAY S1 NOW CONTAINS THE MECHANICAL WORK TERM )
C
C---------- PUT SFC TURBULENT HEAT FLUX INTO ARRAY 13 OF PHYSDIAG
C
C              REPLACE T1 (SFC AIR TEMP) WITH CSUBP TIMES
C                 TEMPERATURE DIFFERENCE ( GND MINUS AIR)
         T1(IQ2)=CONST*(VBL(IADTG+IQ2-1)-T1(IQ2))
89020 CONTINUE
C
C
      IADSHF = IADDRG(36,NG)
      IADLHF = IADDRG(37,NG)
C         CAN DO HEAT FLUX OVER LAND ONLY IF RADIATION CODE IS
C             BEING USED
      IF( ICALLRAD .EQ. 1 ) GO TO 50
C         ZERO HEAT FLUX OVER LAND
CMIC$ DO ALL VECTOR SHARED(IJ, IADSHF, VBL) PRIVATE(IQ2)
      DO 89050 IQ2=1,IJ
         VBL(IADSHF+IQ2-1)=0.E0
89050 CONTINUE
C              CAN COMPUTE HEAT FLUX OVER OCEAN
CMIC$ DO ALL VECTOR IF (ABS(IADEX-IADSHF).GE.IJ .OR. IADEX-IADSHF.EQ.0)
CMIC$1    SHARED(IJ, NG, IADEX, IADSHF, BITSEA, T1, VBL) PRIVATE(IQ2)
      DO 89060 IQ2=1,IJ
       IF ( BITSEA(IQ2,NG) ) THEN
         VBL(IADSHF+IQ2-1)=T1(IQ2)*VBL(IADEX+IQ2-1)
       END IF
89060 CONTINUE
      GO TO 55
C           CAN COMPUTE HEAT FLUX EVERYWHERE
   50 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IADEX-IADSHF).GE.IJ .OR. IADEX-IADSHF.EQ.0)
CMIC$1    SHARED(IJ, IADEX, IADSHF, T1, VBL) PRIVATE(IQ2)
      DO 89070 IQ2=1,IJ
         VBL(IADSHF+IQ2-1)=T1(IQ2)*VBL(IADEX+IQ2-1)
89070 CONTINUE
C
   55 CONTINUE
C
C------------ PUT WATER FLUX (EVAPORATION) INTO ARRAY 14 OF PHYSDIAG
C       FIRST GET THE  SPEC HUMIDITY DIFFERENCE INTO ARRAY S3
      IADQG = IADDRG(7,NG)
      IADQ = IADDRG(4,NG)
CMIC$ DO ALL VECTOR SHARED(IJ, IADQG, IADQ, VBL, HREC, S3) PRIVATE(IQ2)
      DO 89080 IQ2=1,IJ
         S3(IQ2)=VBL(IADQG+IQ2-1)-
     *              VBL(IADQ+IQ2-1)*HREC(IQ2)
89080 CONTINUE
C           SEPARATE CASE OF RADIATION FROM NO RADIATION
      IF ( ICALLRAD .NE. 1 ) THEN
C          NO RADIATION, THEREFORE ZERO EVAPORATION OVER LAND
CMIC$ DO ALL VECTOR SHARED(IJ, IADLHF, VBL) PRIVATE(IQ2)
      DO 89100 IQ2=1,IJ
         VBL(IADLHF+IQ2-1)=0.E0
89100 CONTINUE
C          EVAPORATION OVER OCEAN
CMIC$ DO ALL VECTOR IF (ABS(IADEX-IADLHF).GE.IJ .OR. IADEX-IADLHF.EQ.0)
CMIC$1    SHARED(IJ, NG, IADEX, IADLHF, BITSEA, S3, VBL) PRIVATE(IQ2)
      DO 89110 IQ2=1,IJ
       IF ( BITSEA(IQ2,NG) ) THEN
         VBL(IADLHF+IQ2-1)=S3(IQ2)*VBL(IADEX+IQ2-1)
       END IF
89110 CONTINUE
      ELSE
        IADAVL = IADDRG(18,NG)
C           HAVE RADIATION,  AND CAN EVAPORATE OVER LAND
C               SFC EXCHANGE COEFF TIMES SPEC HUMID DIFFERENCE
C               MULTIPLY BY MOISTURE AVAILABILITY (=1 OVER WATER)
CMIC$ DO ALL VECTOR IF ((ABS(IADEX-IADLHF).GE.IJ .OR. IADEX-IADLHF.EQ.0)
CMIC$1    .AND. (ABS(IADAVL-IADLHF).GE.IJ .OR. IADAVL-IADLHF.EQ.0))
CMIC$2    SHARED(IJ, IADEX, IADAVL, IADLHF, S3, VBL) PRIVATE(IQ2)
      DO 89120 IQ2=1,IJ
         VBL(IADLHF+IQ2-1)=S3(IQ2)*VBL(IADEX+IQ2-1)*
     *         VBL(IADAVL+IQ2-1)
89120 CONTINUE
C
      END IF
C
C$$$$$     CUT EVAP IN HALF TO REDUCE SHOWERS IN COLD AIR OVER WATER
C             UNTIL CLOUD TOP MIXING IS INTRODUCED
CMIC$ DO ALL VECTOR SHARED(IJ, NG, IADLHF, BITSEA, VBL) PRIVATE(IQ2)
      DO 89140 IQ2=1,IJ
       IF ( BITSEA(IQ2,NG) ) THEN
         VBL(IADLHF+IQ2-1)=0.5E0*VBL(IADLHF+IQ2-1)
       END IF
89140 CONTINUE
C$$$$$
       IADAEV = IADDRG(39,NG)
C      ACCUMULATE EVAPORATION (IN METERS) IN PHYSDIAG ARRAY 15+KM
CMIC$ DO ALL VECTOR IF (ABS(IADAEV-IADLHF).GE.IJ .OR. IADAEV-IADLHF.EQ.0
CMIC$1   ) SHARED(IJ, IADAEV, DTIME, IADLHF, VBL, HKAPPA, PSKAPR)
CMIC$2    PRIVATE(IQ2)
      DO 89150 IQ2=1,IJ
         VBL(IADAEV+IQ2-1)=VBL(IADAEV+IQ2-1)+DTIME*VBL(IADL
     *   HF+IQ2-1)
C           SFCMIX WILL NEED RECIPROCAL OF H**KAPPA
         PSKAPR(IQ2)=1.E0/HKAPPA(IQ2)
89150 CONTINUE
C
C        CAN NOW CALL SFCMIX (NOTE S1 CONTAINS MECHANICAL WORK TERM)

      CALL SFCMIX( NG, NPAIR, HREC, PSKAPR, DTIME, S1, DHQ,
     1  KMIXMAX, KMIX )
C
C------------ PERFORM A DRY ADIABATIC ADJUSTMENT
        CALL DRYADB( NG, NPAIR )
C
C---------- COMPUTE SURFACE EXCH COEFFS TIMES (GRAV/100*H)
C---------- FOR USE LATER IN GETTING SFC STRESSES FROM HU AND HV
C
CMIC$ DO ALL VECTOR SHARED(IJ, IADEX, HREC, VBL, S1) PRIVATE(IQ2)
      DO 89170 IQ2=1,IJ
         S1(IQ2)=HREC(IQ2)*VBL(IADEX+IQ2-1)
89170 CONTINUE
C           AVERAGE AND MULT WITH (G/100)FOR VALUE AT HU POINTS
      CONST = 0.5E0 * 9.81E0 * 0.01E0
CMIC$ PARALLEL SHARED(IJ, IADH, VBL, HKAPPA, S1, CONST, IM, TAUXC, TAUYC
CMIC$1   ) PRIVATE(IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 89180 IQ2=1,IJ
         TAUXC(IQ2)=CONST*(S1(IQ2)+S1(IM+IQ2))
C           REPEAT PROCEDURE TO GET TAUYC AT HV POINTS
         TAUYC(IQ2)=CONST*(S1(IQ2)+S1(IQ2+1))
89180 CONTINUE
C
C
C------ PUT THE FACTOR H * H**KAPPA INTO S1D FOR USE IN RICHARDSON NO.
CMIC$ DO PARALLEL VECTOR
      DO 89200 IQ2=1,IJ
         S1(IQ2)=VBL(IADH+IQ2-1)*HKAPPA(IQ2)
89200 CONTINUE
CMIC$ END PARALLEL
C
C--------PUT VERTICAL DIFFERENCES (K) MINUS (K-1) FOR K=2,KM
C           H*THETA, H*U, AND H*V INTO ARRAYS D1,D2,AND D3
      IADST = 1
      IADU1 = IADU
      IADV1 = IADV
      IADT1 = IADT
C
CMIC$ DO ALL SHARED(KM, IADST, IJ, IADU1, IADV1, IADT1, VBL, D1, D2, D3)
CMIC$1    PRIVATE(K, IQ2)
      DO 60 K = 1, KM - 1
         DO 77053 IQ2 = 1, IJ
            D1(IADST+IQ2-1+K*IJ) = VBL(IADT1+IQ2-1+K*IJ) - VBL(IADT1+IQ2
     1         -1+(K-1)*IJ)
            D2(IADST+IQ2-1+K*IJ) = VBL(IADU1+IQ2-1+K*IJ) - VBL(IADU1+IQ2
     1         -1+(K-1)*IJ)
            D3(IADST+IQ2-1+K*IJ) = VBL(IADV1+IQ2-1+K*IJ) - VBL(IADV1+IQ2
     1         -1+(K-1)*IJ)
77053    CONTINUE
   60 CONTINUE
C
C
C--------- PUT SIGMA EXCHANGE COEFFICIENT INTO ARRAY D5 FOR H PTS
C
      IADST = 1
      GRTSQ = 9.81E0 / (287.04E0 * 288.E0 )
      GRTSQ = GRTSQ * GRTSQ
C
CMIC$ DO ALL SHARED(KM, GRTSQ, CONAUST, IADST, IJ, IM, PR, SIGINT, PRESS
CMIC$1   , D2, D3, D1, S1, D5) PRIVATE(K, CONST0, CONST1, CONST2, IQ2, 
CMIC$2   S2S, S3S)
      DO 75 K = 1, KM - 1
C          CONSTANT FOR THIS LEVEL TO GET  RICHARDSON NUMBER
         CONST0 = 2.E0*1005.E0*(PR(K)-PR(1+K))
         CONST1 = 1.E0 - SIGINT(1+K)
         CONST2 = CONST1*CONST1*GRTSQ*CONAUST/(PRESS(K)-PRESS(1+K))
C          PUT SQUARE OF  H * VERTICAL SHEAR (LVL K MINUS LVL K-1)
C              ( AT H-POINTS ) INTO ARRAY S2
         DO 77054 IQ2 = 1, IJ
            S2S = (0.5E0*(D2(IADST+IQ2-1+K*IJ)+D2(IADST-IM+IQ2-1+K*IJ)))
     1         **2 + (0.5E0*(D3(IADST+IQ2-1+K*IJ)+D3(IADST-2+IQ2+K*IJ)))
     2         **2
C             (   MUST SAVE THIS  )
C           ADD 1 FOR SAFETY
C           DIVIDE INTO THETA DIFFERENCE
C           MULTIPLY BY H*(H**KAPPA)
C           ADD 1 TO RI FOR DENOMINATOR OF EXCHANGE COEFFICIENT
            S3S = ABS(D1(IADST+IQ2-1+K*IJ)/(S2S+1.E0))*S1(IQ2)*CONST0 + 
     1         1.E0
C           COMPUTE VALUE OF NEUTRAL EXCHANGE COEFFICIENT
C            DIVIDED BY SIGMA DIFFERENCE BETWEEN LEVELS
C
C      PUT THE EXCHANGE COEFFICIENT (DIVIDED BY SIGMA DIFF)
C      AT H PTS  INTO ARRAY D5
C                     ( S3 HAS   1 PLUS RICHARDSON NUMBER)
            D5(IADST+IQ2-1+K*IJ) = CONST2/S3S
77054    CONTINUE
   75 CONTINUE
C
C
C------------- ADJUST EX COEFF AT TOP OF MIXED LAYERS IF DESIRED
      IF(MIXADJ.EQ.0 ) GO TO 85
      IF( KMIXMAX .LT. 3 ) GO TO 85
C
CMIC$ DO ALL IF (ABS(IJ).GE.(KMIXMAX-2)*ABS(IJ) .OR. IJ.EQ.0) SHARED(
CMIC$1   KMIXMAX, IJ, KMIX, D5) PRIVATE(BITAUS, K, KAD, KADB, IQ2)
      DO 80 K = 3,KMIXMAX
      KAD = 1 + (K-1)*IJ
      KADB = KAD - IJ
      DO 89390 IQ2=1,IJ
         BITAUS(IQ2)=KMIX(IQ2).EQ.K
89390 CONTINUE
CDIR$ IVDEP
      DO 89400 IQ2=1,IJ
       IF ( BITAUS(IQ2) ) THEN
         D5(KAD+IQ2-1)=D5(KADB+IQ2-1)
       END IF
89400 CONTINUE
   80 CONTINUE
C
   85 CONTINUE
C
C------INTERPOLATE EXCH COEF TO HU PTS AND HV PTS IN ARRAYS D7 AND D8
      IADST = 1
CMIC$ DO ALL SHARED(KM, IADST, IJ, IM, D5, D7, D8) PRIVATE(K, IQ2)
      DO 86 K = 1, KM - 1
         DO 77055 IQ2 = 1, IJ
            D7(IADST+IQ2-1+K*IJ) = 0.5E0*(D5(IADST+IQ2-1+K*IJ)+D5(IADST+
     1         IM+IQ2-1+K*IJ))
            D8(IADST+IQ2-1+K*IJ) = 0.5E0*(D5(IADST+IQ2-1+K*IJ)+D5(IADST+
     1         IQ2+K*IJ))
77055    CONTINUE
   86 CONTINUE
C
C------------- CHECK SIZE OF TIME STEP ALLOWED----------------------
C             FIND THE MINIMUM VALUE OF DTMAX FROM AUSTAUSCH VALUES
      DTMAX = 100000.0
      IADST = 1
      DO 90 K = 2,KM
      IADST = IADST + IJ
      EXMAX = -1.E+35
CMIC$ PARALLEL SHARED(IJ,NG,EXMAX,IADST,BITGRDH,D5)PRIVATE(IQ2,R1S)
      R1S = EXMAX
CMIC$ DO PARALLEL VECTOR
      DO 3881 IQ2 = 1, IJ
         IF (BITGRDH(IQ2,1,NG)) R1S = AMAX1(R1S,D5(IADST+IQ2-1))
 3881 CONTINUE
CMIC$ GUARD
      EXMAX = AMAX1(EXMAX,R1S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
      AMAX(K,NG) = EXMAX*( PRESS(K-1)-PRESS(K) )
C            USE THE MINIMUM DELTA SIGMA ADJACENT TO THIS INTERFACE
      DTMAX1 = DSIGMIN(K) / AMAX(K,NG)
      IF(DTMAX1 .GE. DTMAX ) GO TO 90
 
C            THIS LAYER HAS A SMALLER VALUE OF DTMAX
      DTMAX = DTMAX1
      K4MIN = K
   90 CONTINUE
C             INTRODUCE A 10 PERCENT SAFETY FACTOR
      DTMAX = 0.9E0 * DTMAX
C              HOW MANY TIME STEPS ARE NEEDED TO ADVANCE BY DTIME?
      NUMSTP = 1
      COURANT = DTIME/DTMAX
      IF(COURANT.GE. 1.E0) NUMSTP = INT(COURANT)  + 1
C              IS THIS A CHANGE?
      IF(NUMSTP .EQ. NUMSTEP(NG) ) GO TO 120
      PRINT 100,ITIME,NG,NUMSTEP(NG),NUMSTP
  100 FORMAT(1H0,2X,'**** AT ITIME=',I8,' GRID',I4,' HAS NUMSTEP',
     1 ' IN PHYSICS CHANGED FROM',I4,' TO',I4)
      NUMSTEP(NG) = NUMSTP
      PRINT 105,DTMAX,K4MIN
  105 FORMAT(1H ,2X,'A VALUE OF ',F12.4,' WAS REACHED FOR DTMAX AT K=',
     1 I4)
C
  120 CONTINUE
C--------- DO WE PRINT OUT AUSTAUSCH INFORMATION-------------------
      IF( IPAUST.EQ. 0 ) GO TO 140
      IF( NG .NE. NGRDUSE ) GO TO 140
      IF( ITIME .LT. ITEX ) GO TO 140
C           RIGHT GRID AND RIGHT TIME
      IADX = (JEX-1)*IM + IEX
C         ADD FOR POT TEMP, H, HU AND HV
      IADP = IADDRG(3,NG) + IADX - 1
      IADPH = IADDRG(5,NG) + IADX - 1
      IADPU = IADDRG(1,NG) + IADX - 1
      IADPV = IADDRG(2,NG) + IADX - 1
      PRINT 125,ITEX,IEX,JEX,BLKDR
  125 FORMAT(1H0,20X,'AUSTAUSCH PRINT FOR ITEX=',I8,' I,J=',2I4,
     1 ' BLKDR =',E14.6)
      PRINT 126
  126 FORMAT(1H0,4X,'K',4X,'EX(K)',7X,'AUST(K)',3X,'TH(K-1)',
     1 3X,'VEL(K-1)')
      ITEX = ITEX + IDTEX
C
      DO 135 KK = 2,KM
      K = KM+2-KK
      INC = (K-2)*IJ
      IAD = IADX+IJ+INC
      X = D5(IAD)
      CONST1 = (1.E0 - SIGINT(K) )
      CONST2 = CONST1*CONST1*GRTSQ
      AUS = X*(PRESS(K-1)-PRESS(K) ) / CONST2
C      WANT THETA AND SPEED FOR LEVEL BELOW THIS INTERFACE
      THETA = VBL(IADP+INC) / VBL(IADPH)
      UVEL = VBL(IADPU+INC)
      VVEL = VBL(IADPV+INC)
      SPEED = SQRT(  UVEL*UVEL+VVEL*VVEL  ) / VBL(IADPH)
      PRINT 130,K,X,AUS,THETA,SPEED
  130 FORMAT(1H ,2X,I3,E14.6,3F10.3)
C
  135 CONTINUE
C--------------------------------------------------------
  140 CONTINUE
C
C
C             MUST ACCOMPLISH TIME STEP IN NUMSTEP STEPS
      NNSTEP = NUMSTEP(NG)
      DNSTEP = FLOAT(NNSTEP)
      DTUSE = DTIME/DNSTEP
C
      DO 200 N = 1,NNSTEP
C
C-----NEED  VERTICAL DIFFERENCES (K) MINUS (K-1) FOR K=2,KM
C           OF H*U, AND H*V IN ARRAYS D2 AND D3. THEY ARE ALREADY
C           THERE ONLY IF N = 1
      IF( N . EQ. 1 ) GO TO 155
      IADST = 1
      IADU1 = IADU
      IADV1 = IADV
CMIC$ DO ALL SHARED(KM,IADU1,IJ,IADV1,IADST,VBL,D2,D3)PRIVATE(K,IQ2)
      DO 150 K = 1, KM - 1
         DO 77056 IQ2 = 1, IJ
            D2(IADST+IQ2-1+K*IJ) = VBL(IADU1+IQ2-1+K*IJ) - VBL(IADU1+IQ2
     1         -1+(K-1)*IJ)
            D3(IADST+IQ2-1+K*IJ) = VBL(IADV1+IQ2-1+K*IJ) - VBL(IADV1+IQ2
     1         -1+(K-1)*IJ)
77056    CONTINUE
  150 CONTINUE
C
C
  155 CONTINUE
C
C          PUT STRESSES INTO ARRAYS D9 AND D10
C                    ( AT INTERFACES K=2,KM)
      IADST = 1 + IJ
CMIC$ PARALLEL SHARED(IJ, IADU, IADV, TAUXC, VBL, D9, TAUYC, D10, KM, 
CMIC$1   IADST, D2, D7, D3, D8) PRIVATE(IQ2, K)
CMIC$ DO PARALLEL
      DO 160 K = 1, KM - 1
         DO 77057 IQ2 = 1, IJ
            D9(IADST+IQ2-1+(K-1)*IJ) = D2(IADST+IQ2-1+(K-1)*IJ)*D7(IADST
     1         +IQ2-1+(K-1)*IJ)
            D10(IADST+IQ2-1+(K-1)*IJ) = D3(IADST+IQ2-1+(K-1)*IJ)*D8(
     1         IADST+IQ2-1+(K-1)*IJ)
77057    CONTINUE
  160 CONTINUE
C       FILL IN INTERFACE K=1 (THE GROUND) WITH SURFACE STRESS * (G/100)
C       (TAUXC AND TAUYC CONTAIN THE PROPER EXCHANGE COEFFS)
C
CMIC$ DO PARALLEL VECTOR
      DO 89470 IQ2=1,IJ
         D9(IQ2)=TAUXC(IQ2)*VBL(IADU+IQ2-1)
         D10(IQ2)=TAUYC(IQ2)*VBL(IADV+IQ2-1)
89470 CONTINUE
CMIC$ END PARALLEL
C
C            CAN NOW ADD FRICTIONAL CHANGES TO HU AND HV
      IADST = 1
      IADU1 = IADU
      IADV1 = IADV
C          FIRST DO LAYERS K=1 THRU KM-1
      DO 165 KK=2,KM
      K = KK - 1
      CONST = DTUSE / DELSIG(K)
CMIC$ DO ALL VECTOR IF (ABS(IADU1-IADV1).GE.IJ .OR. IADU1-IADV1.EQ.0)
CMIC$1    SHARED(IJ, IADU1, NPAIR, NG, CONST, IADST, IADV1, VBL, 
CMIC$2   ABITGRDU, D9, ABITGRDV, D10) PRIVATE(IQ2)
      DO 89500 IQ2=1,IJ
         VBL(IADU1+IQ2-1)=VBL(IADU1+IQ2-1)+
     *              ABITGRDU(IQ2,NPAIR,NG)*
     *              CONST*(D9(IADST+IJ+IQ2-1)-D9(IADST+IQ2-1))
         VBL(IADV1+IQ2-1)=VBL(IADV1+IQ2-1)+
     *              ABITGRDV(IQ2,NPAIR,NG)*
     *              CONST*(D10(IADST+IJ+IQ2-1)-D10(IADST+IQ2-1))
89500 CONTINUE
      IADST = IADST + IJ
      IADU1 = IADU1 + IJ
      IADV1 = IADV1 + IJ
  165 CONTINUE
C                SPECIAL TREATMENT OF TOP LAYER (=KM )
      CONST = DTUSE / DELSIG(KM)
CMIC$ DO ALL VECTOR IF (ABS(IADU1-IADV1).GE.IJ .OR. IADU1-IADV1.EQ.0)
CMIC$1    SHARED(IJ, CONST, IADST, NPAIR, NG, IADU1, IADV1, D9, ABITGRDU
CMIC$2   , VBL, D10, ABITGRDV) PRIVATE(IQ2)
      DO 89530 IQ2=1,IJ
         VBL(IADU1+IQ2-1)=-CONST*D9(IADST+IQ2-1)*
     *     ABITGRDU(IQ2,NPAIR,NG)+
     *     VBL(IADU1+IQ2-1)
         VBL(IADV1+IQ2-1)=-CONST*D10(IADST+IQ2-1)*
     *     ABITGRDV(IQ2,NPAIR,NG)+
     *     VBL(IADV1+IQ2-1)
89530 CONTINUE
C
C           END OF SPECIAL TIME LOOP
  200 CONTINUE
C
C------------- NOW PERFORM THE PRECIPITATION CALCULATIONS
C
      CALL PRECIP(DHQ, NPAIR, NG, LADD3, LEN31, DTIME )
C
C
      RETURN
      END
