      SUBROUTINE PRINTTIM
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PRINTTIM    PRINTS THE CURRENT WALL TIME
C   PRGMMR: JIM TUCCILLO     ORG: W/NMC4     DATE: 90-06-21
C
C ABSTRACT: PRINTS CURRENT WALL TIME
C
C PROGRAM HISTORY LOG:
C   90-06-21  JIM TUCCILLO
C   98-11-24  ERIC ROGERS MADE Y2K COMPLIANT BY SWITCHING TO 
C             CALL OF W3LOCDAT
C
C USAGE:    CALL PRINTTIM
C   OUTPUT FILES:
C     FT06F001 - FOR PRINTOUT OF TIME
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:
C     W3LIB : W3LOCDAT
C
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      DIMENSION IWCDAT(8)
C
      CALL W3LOCDAT(IWCDAT)
C
      WRITE (6, 100) IWCDAT(1),IWCDAT(2),IWCDAT(3),IWCDAT(5),
     1   IWCDAT(6),IWCDAT(7)    
  100 FORMAT (5X,'THE CURRENT DAY IS ',I4,'/',I2,'/',I2,
     1                 ' AND THE LOCAL WALL TIME IS ',
     2                 I2,':',I2,':',I2)
      RETURN
      END
