      SUBROUTINE PRINTBIT (BITS, IDIM, JDIM, IMAX, JMAX, NG, LABEL)
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:59:19  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PRINTBIT    PRINTS THE BIT ARRAY CALLED BITS
C   PRGMMR: JIM TUCCILLO     ORG: W/NMC4     DATE: 90-06-21
C
C ABSTRACT: PRINTS THE BIT ARRAY CALLED BITS
C
C PROGRAM HISTORY LOG:
C   90-06-21  J TUCCILLO
C
C USAGE:    CALL PRINTBIT (BITS, IDIM, JDIM, IMAX, JMAX, NG, LABEL)
C   INPUT ARGUMENT LIST:
C     BITS     - BIT ARRAY TO BE PRINTED
C     IDIM     - FIRST DIMENSION OF ARRAY BITS
C     JDIM     - SECOND DIMENSION OF ARRAY BITS
C     IMAX     - UPPER BOUND OF FIRST DIMENSION TO BE PRINTED
C     JMAX     - UPPER BOUND OF SECOND DIMENSION TO BE PRINTED
C     NG       - GRID NUMBER FOR BIT ARRAY TO BE PRINTED
C     LABEL    - LABEL DESCRIBING GRID NG
C
C   OUTPUT FILES:
C     FT06F001 - FOR PRINTOUT
C
C REMARKS: THE LABEL CAN HAVE UP TO 24 CHARACTERS
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      LOGICAL BITS
C
      DIMENSION BITS(IDIM, JDIM)
      DIMENSION LABEL(3)
      DIMENSION ILABEL1(110), ILABEL2(110)
C
C
C     ONLY UP TO 110 BITS IN THE I DIRECTION CAN BE PRINTED BY
C     SUBROUTINE DUMPBIT.
      ITOT = MIN (IMAX, 110)
      IF (ITOT .NE. IMAX) PRINT 50
   50 FORMAT ('0', 'NOTE ***** ONLY THE FIRST 110 BITS IN THE ',
     1             'I DIRECTION CAN BE PRINTED BY SUBROUTINE ',
     2             'DUMPBIT.')
C
CMIC$ DO ALL VECTOR SHARED(ITOT, ILABEL1, ILABEL2) PRIVATE(I)
      DO 100 I=1,ITOT
      ILABEL1(I) = I / 10
      ILABEL2(I) = MOD (I, 10)
  100 CONTINUE
C
      PRINT 200, NG, (LABEL(I), I=1,3)
  200 FORMAT (// '0', 'BIT VECTOR FOR GRID', I2, ' -- ', 3A8)
C
C     PRINT THE NUMBER OF BITS AND THE NUMBER OF 1 BITS.
      IJ     = IMAX * JMAX
      NUMONES = 0
      DO 1001 IQ2 = 1, IJ
         IF ( BITS(IQ2,1)) NUMONES = NUMONES + 1
1001  CONTINUE
      PRINT 250, IJ, NUMONES
  250 FORMAT (' ', 'THERE ARE', I6, ' BITS DISPLAYED, OF WHICH',
     1             I6, ' ARE 1 BITS.')
C
      PRINT 300, (ILABEL1(I), I=1,ITOT)
  300 FORMAT('0', 7X, 'I= ', 11(10I1, 1X))
C
      PRINT 400, (ILABEL2(I), I=1,ITOT)
  400 FORMAT(' ', 10X, 11(10I1, 1X) )
C
      PRINT 500
  500 FORMAT (' ')
C
      DO 700 J=1,JMAX
         JJ = JMAX + 1 - J
         IF (MOD(JJ,10) .EQ. 0) PRINT 500
C
         PRINT 600, JJ, (BITS(I, JJ), I=1,ITOT)
  600    FORMAT (' ', 'J=', I3, 5X, 11(10L1, 1X))
C
  700 CONTINUE
C
      PRINT 500
C
      RETURN
      END
