      SUBROUTINE PRT(X, IM, JM )
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:03:38  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      REAL R1S,R2S
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PRT         PRINT  GRID AS 4-DIGIT INTEGER.
C   PRGMMR: JIM TUCCILLO     ORG: W/NMC4     DATE: 90-06-22
C
C ABSTRACT: PRINTS OUT A GRID OF HALF PRECISION DATA IN ARRAY X
C   .       HAVING DIMENSIONS IM,JM AS 4-DIGIT INTEGERS.
C
C PROGRAM HISTORY LOG:
C   90-06-21  JIM HOKE
C
C USAGE:    CALL PRT ( X, IM, JM )
C   INPUT ARGUMENT LIST:
C     X   - ARRAY TO BE PRINTED
C     IM  - FIRST DIMENSION OF ARRAY X
C     JM  - SECOND DIMENSION OF ARRAY X
C
C   OUTPUT FILES:
C     FT06F001 - FOR PRINTOUT
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      DIMENSION X(1),IP(21),Y(20)
      IJ=IM*JM
      XMAX = X(1)
      XMIN = X(1)
CMIC$ PARALLEL SHARED(IJ, XMAX, XMIN, X) PRIVATE(IQ2, R1S, R2S)
      R1S = XMAX
      R2S = XMIN
CMIC$ DO PARALLEL VECTOR
      DO 1001 IQ2 = 1, IJ
         R1S = AMAX1(R1S,X(IQ2))
         R2S = AMIN1(R2S,X(IQ2))
 1001 CONTINUE
CMIC$ GUARD
      XMIN = AMIN1(XMIN,R2S)
CMIC$ END GUARD
CMIC$ GUARD
      XMAX = AMAX1(XMAX,R1S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
C          ALLOW FOR A FIELD OF ZEROS.
      IF( XMAX .NE. 0.E0 ) GO TO 3
      IF( XMIN .NE. 0.E0 ) GO TO 3
C        THE FIELD IS IDENTICALLY = TO ZERO.
      NSCALE=0
      SCALE=1.E0
      GO TO 4
C
C       THE FIELD IS NOT IDENTICALLY ZERO.
    3 CONTINUE
      IF(XMIN .LT. 0.E0) XMIN=-XMIN
      IF(XMIN .GT. XMAX) XMAX=XMIN
      XX=LOG10(XMAX)
      NSCALE=3-INT(XX)
      IF(XX .LT. 0.E0) NSCALE=4+INT(-XX)
      SCALE=10.0**NSCALE
C
    4 CONTINUE
C
C          ENTER PAGING LOOP FOR PRINTING IN PAGES OF
C          20 I-COLUMNS WITH I=L1,L2
      L1=1
    5 L2=L1+19
      IF(L2 .GT. IM) L2=IM
CMIC$ PARALLEL SHARED(L2, L1, IP) PRIVATE(L, LL, IQ2)
CMIC$ DO PARALLEL VECTOR
      DO 88890 IQ2=1,21
         IP(IQ2)=0
88890 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 10 L=L1,L2
      LL=L-L1+2
      IP(LL)=L
   10 CONTINUE
CMIC$ END PARALLEL
      PRINT 15,NSCALE
   15 FORMAT(1H ,20X,'OUTPUT WAS MULTIPLIED BY 10 TO THE POWER',I10)
      PRINT 16,IP
   16 FORMAT(1H0,2X,I3,20I6)
CMIC$ DO ALL VECTOR SHARED(IP) PRIVATE(IQ2)
      DO 88900 IQ2=1,21
         IP(IQ2)=0
88900 CONTINUE
      M=L2-L1+1
        DO 20 JJ=1,JM
        J=JM-JJ+1
        IP(1)=J
        IADD=L1+(J-1)*IM
CMIC$ DO ALL VECTOR SHARED(M, SCALE, IADD, X, Y, IP) PRIVATE(IQ2)
      DO 88910 IQ2=1,M
         Y(IQ2)=SCALE*X(IADD+IQ2-1)
         IP(IQ2+1)=NINT(Y(IQ2))
88910 CONTINUE
        PRINT 16,IP
   20   CONTINUE
      L1=L2+1
      IF(L1 .LE. IM ) GO TO 5
      RETURN
      END
