      SUBROUTINE PRT25(X, IM, JM )
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:04:28  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      REAL R1S,R2S
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PRT25       PRINTS GRID AS INTEGER DATA 25 TO A ROW
C   PRGMMR: JIM TUCCILLO     ORG: W/NMC4    DATE: 90-06-22
C
C ABSTRACT: PRINTS OUT A GRID OF HALF PRECISION DATA IN ARRAY X
C   HAVING DIMENSIONS IM,JM AS 4-DIGIT INTEGERS------25 TO THE ROW
C
C PROGRAM HISTORY LOG:
C   90-06-22  JIM TUCCILLO
C
C USAGE:    CALL PRT25 (X, IM, JM)
C   INPUT ARGUMENT LIST:
C     X        - ARRAY OF HALF PRECISION REALS
C     IM       - FIRST DIMENSION OF THE ARRAY X
C     JM       - SECOND DIMENSION OF THE ARRAY X
C
C   OUTPUT FILES:
C     FT06F001 - INCLUDE IF ANY PRINTOUT
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      DIMENSION X(1),IP(26),Y(25)
C
      IJ=IM*JM
      XMAX = X(1)
      XMIN = X(1)
CMIC$ PARALLEL SHARED(IJ, XMAX, XMIN, X) PRIVATE(IQ2, R1S, R2S)
      R1S = XMAX
      R2S = XMIN
CMIC$ DO PARALLEL VECTOR
      DO 1001 IQ2 = 1, IJ
         R1S = AMAX1(R1S,X(IQ2))
         R2S = AMIN1(R2S,X(IQ2))
 1001 CONTINUE
CMIC$ GUARD
      XMIN = AMIN1(XMIN,R2S)
CMIC$ END GUARD
CMIC$ GUARD
      XMAX = AMAX1(XMAX,R1S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
C
C          ALLOW FOR A FIELD OF ZEROS.
      IF( XMAX .NE. 0.E0 ) GO TO 3
      IF( XMIN .NE. 0.E0 ) GO TO 3
C        THE FIELD IS IDENTICALLY = TO ZERO.
      NSCALE=0
      SCALE=1.E0
      GO TO 4
C
C       THE FIELD IS NOT IDENTICALLY ZERO.
    3 CONTINUE
C
      IF(XMIN .LT. 0.E0) XMIN=-XMIN
      IF(XMIN .GT. XMAX) XMAX=XMIN
      XX=LOG10(XMAX)
      NSCALE=3-INT(XX)
      IF(XX .LT. 0.E0) NSCALE=4+INT(-XX)
      SCALE=10.0E0**NSCALE
C
    4 CONTINUE
C
C          ENTER PAGING LOOP FOR PRINTING IN PAGES OF
C          25 I-COLUMNS WITH I=L1,L2
C
      NPAGE=1
C
      L1=1
    5 L2=L1+24
      IF(L2 .GT. IM) L2=IM
CMIC$ PARALLEL SHARED(L2, L1, IP) PRIVATE(L, LL, IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 88890 IQ2W6E=1,26
         IP(IQ2W6E)=0
88890 CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 10 L=L1,L2
      LL=L-L1+2
      IP(LL)=L
   10 CONTINUE
CMIC$ END PARALLEL
C
      PRINT 15,NSCALE
   15 FORMAT(1H ,20X,'OUTPUT WAS MULTIPLIED BY 10 TO THE POWER',I10)
      PRINT 16,IP
   16 FORMAT(1H0,2X,I3,1X,25I5)
   17 FORMAT(1H0,40X)
C
CMIC$ DO ALL VECTOR SHARED(IP) PRIVATE(IQ2W6E)
      DO 88900 IQ2W6E=1,26
         IP(IQ2W6E)=0
88900 CONTINUE
      M=L2-L1+1
C
        DO 20 JJ=1,JM
        J=JM-JJ+1
        IP(1)=J
        IADD=L1+(J-1)*IM
CMIC$ DO ALL VECTOR SHARED(M, SCALE, IADD, X, Y, IP) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E=1,M
         Y(IQ2W6E)=SCALE*X(IADD+IQ2W6E-1)
         IP(IQ2W6E+1)=NINT(Y(IQ2W6E))
88910 CONTINUE
        PRINT 16,IP
        PRINT 17
   20   CONTINUE
C
      L1=L2+1
      IF(L1 .GT. IM ) RETURN
C
      NPAGE=NPAGE+1
      PRINT 21,NPAGE
   21 FORMAT(1H1,40X,'PAGE',I3)
      GO TO 5
C
C
      END
