      SUBROUTINE RDCLDGEN ( TL, QL, PL, PRCN, CLD, CLU, ICLDW, ICLUW,
     *           CST , ES , LOFCLDS , NX , NZ , LPRINT )
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:09:51  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    RDCLDGEN    COMPUTE CLOUD AMOUNTS
C   PRGMMR: J TUCCILLO       ORG: W/NMC40    DATE: 90-06-16
C
C ABSTRACT:  COMPUTES CLOUD AMOUNTS FOR A RADIATION BLOCK
C
C PROGRAM HISTORY LOG:
C   90-06-16 J TUCCILLO
C
C USAGE:  CALL RDCLDGEN ( TL, QL, PL, PRCN, CLD, CLU, ICLDW, ICLUW,
C                CST , ES , LOFCLDS , NX , NZ , LPRINT )
C   INPUT ARGUMENT LIST:
C     NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C
C     TL          TEMPERATURES OF LAYERS ( DEGS K )         ARGUMENT
C
C     QL          SPECIFIC HUMIDITY OF LAYERS ( GRMS/GRM)   ARGUMENT
C
C     PL          PRESSURE OF MID POINTS OF LAYERS ( MBS )  ARGUMENT
C
C     PRCN        CONVECTIVE PRECIP. RATE                   ARGUMENT
C                 ( DORMANT RIGHT NOW )
C
C     CST         WORK SPACE                                ARGUMENT
C
C     ES          WORK SPACE                                ARGUMENT
C
C     LOFCLDS     SIGMA LIMITS FOR CLOUDS                   ARGUMENTS
C
C     NX          NUMBER OF COLUMNS IN RADIATION BLOCK      ARGUMENT
C
C     NZ          NUMBER OF LAYERS                          ARGUMENT
C
C     LPRINT      LOGICAL FOR DEBUG PRINTS                  ARGUMENTS
C
C
C
C   OUTPUT ARGUMENT LIST:
C     NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C
C     CLD         RANDOM OVERLAP CLOUD AMOUNTS ( 0 - 1 )    ARGUMENT
C                 ( HI , MID , AND LO )
C
C     CLU         MAXIMUM OVERLAP CLOUD AMOUNT ( 0 - 1 )   ARGUMENT
C                 ( CURRENTLY ZERO )
C
C     ICLDW       LAYERS WITH HI, MID AND LO RANDOM        ARGUMENT
C                 OVERLAP CLOUD AMOUNTS
C
C     ICLUW       LAYERS WITH MAXIMUM OVERLAP              ARGUMENT
C                 CLOUD AMOUNTS
C
C
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C   SUBPROGRAMS CALLED:
C     NAME(S)                                               LIBRARY
C     -------                                               -------
C
C     VAPTAB                                                FORECAST
C
C REMARKS:
C    ALL FLOATING POINT INPUT AND OUTPUT VALUES ARE IN HALF PRECISION
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   SOURCE STATEMENTS: XXXX
C
C$$$
C
      DIMENSION TL(NX,1),QL(NX,1),PL(NX,1),PRCN(1),CLD(NX,3),CLU(NX),
     *          ICLDW(NX,3),ICLUW(NX,2),CST(NX,1),ES(NX,1),
     *          LOFCLDS(2,4)
C
      LOGICAL LPRINT
C
      PARAMETER (
     *     EPS      = 0.622E0  ,
     *     ONEMEPS  = 0.378E0  ,
     *     PRCONV   = 1.000E0  ,
     *     CCACOEF  = 0.000E0  ,
     *     CCBCOEF  = 0.000E0  ,
     *     CCMAX    = 0.80E0   ,
     *     CCMINCH  = 0.40E0   ,
     *     CCPMIN   = 400.E0   ,
     *     CHACOEF  = 2.E0     ,
     *     CHBCOEF  = 0.3E0    ,
     *     HMLACOEF = 5.E0     ,
     *     HMLBCOEF = 0.8E0   )
C
      NZP1  = NZ + 1
      KSTLO = NZP1 - LOFCLDS(1,2)
      KSPLO = NZP1 - LOFCLDS(2,2)
      KSTMD = NZP1 - LOFCLDS(1,3)
      KSPMD = NZP1 - LOFCLDS(2,3)
      KSTHI = NZP1 - LOFCLDS(1,4)
      KSPHI = NZP1 - LOFCLDS(2,4)
C
      LENXZ = NX * NZ
C
C
C====>COMPUTE RH
C
      CALL VAPTAB(TL,ES,LENXZ,1)
CMIC$ DO ALL VECTOR SHARED(LENXZ,NX,ES,PL,QL,CST)PRIVATE(IQ2,ESS,CSTS)
      DO 88890 IQ2=1,LENXZ
         ESS=ES(IQ2,1)*10.E0
         CSTS=(PL(IQ2,1)-ONEMEPS*ESS)*QL(IQ2,1)/(ESS*EPS)
         CST(IQ2,1)=AMAX1(AMIN1(CSTS,1.0), 0.0 )
88890 CONTINUE
      IF (LPRINT) THEN
          DO 1010 K=1,NZ
             PRINT 1020 , K , CST(1,K)
1020         FORMAT(' K,RH(K)=',2X,I5,2X,F10.5)
1010      CONTINUE
      END IF
C
C====>COMPUTE CONVECTIVE CLOUD AMOUNT
C
C       CURRENTLY ZERO
C
CMIC$ PARALLEL SHARED(NX, KSTLO, CST, CLD, ICLDW, KSTHI, KSPHI, CLU, PL
CMIC$1   , ICLUW, NZ, LENXZ, KSTMD, KSPMD, PRCN) PRIVATE(IQ2, K)
CMIC$ DO PARALLEL VECTOR
      DO 88960 IQ2=1,NX
         CLU(IQ2)=AMIN1((CCACOEF+CCBCOEF*ALOG(PRCONV*PRCN(IQ2))),
     *            CCMAX )
88960 CONTINUE
C
C====>COMPUTE HI,MID AND LO CLOUD AMOUNTS ( RANDOM OVERLAP )
C
CMIC$ DO PARALLEL
      DO 100 K=KSTMD,KSPMD,-1
      DO 89000 IQ2=1,NX
         CST(IQ2,K)=CST(IQ2,K)-CLU(IQ2)
89000 CONTINUE
100   CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89010 IQ2=1,LENXZ
         CST(IQ2,1)=AMAX1((HMLACOEF*(CST(IQ2,1)-HMLBCOEF)),0.)
     *    ** 2
89010 CONTINUE
C
C     NO CLOUDS IN LAYER 1
C
CMIC$ DO PARALLEL VECTOR
      DO 89040 IQ2=1,NX
         CST(IQ2,NZ)=0.E0
89040 CONTINUE
C
CMIC$ DO PARALLEL
      DO 200 K=KSTHI,KSPHI,-1
      DO 89050 IQ2=1,NX
       IF ( CLU(IQ2).GT.CCMINCH .AND.
     *      PL(IQ2,K).LT.CCPMIN .AND.
     *      ICLUW(IQ2,2).LE. K ) THEN
           CST(IQ2,K)=CHACOEF*(CLU(IQ2)-CHBCOEF)
       END IF
89050 CONTINUE
200   CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89060 IQ2=1,NX
         CLD(IQ2,1)=CST(IQ2,KSTLO)
         ICLDW(IQ2,1)=KSTLO
89060 CONTINUE
CMIC$ END PARALLEL
CMIC$ PARALLEL SHARED(NX, CST, CLD, ICLDW, KSTLO, KSPLO) PRIVATE(IQ2, K)
      DO 300 K=KSTLO-1,KSPLO,-1
CMIC$ DO PARALLEL VECTOR
      DO 89080 IQ2=1,NX
        IF ( CST(IQ2,K).GT.CLD(IQ2,1) ) THEN
         CLD(IQ2,1)=CST(IQ2,K)
         ICLDW(IQ2,1)=K
        END IF
89080 CONTINUE
300   CONTINUE
CMIC$ END PARALLEL
C
CMIC$ DO ALL VECTOR SHARED(NX, KSTMD, CST, CLD, ICLDW) PRIVATE(IQ2)
      DO 89100 IQ2=1,NX
         CLD(IQ2,2)=CST(IQ2,KSTMD)
         ICLDW(IQ2,2)=KSTMD
89100 CONTINUE
CMIC$ PARALLEL SHARED(NX, CST, CLD, ICLDW, KSTMD, KSPMD) PRIVATE(IQ2, K)
      DO 500 K=KSTMD-1,KSPMD,-1
CMIC$ DO PARALLEL VECTOR
      DO 89120 IQ2=1,NX
        IF ( CST(IQ2,K).GT.CLD(IQ2,2) ) THEN
         CLD(IQ2,2)=CST(IQ2,K)
         ICLDW(IQ2,2)=K
        END IF
89120 CONTINUE
500   CONTINUE
CMIC$ END PARALLEL
C
CMIC$ DO ALL VECTOR SHARED(NX, KSTHI, CST, CLD, ICLDW) PRIVATE(IQ2)
      DO 89140 IQ2=1,NX
         CLD(IQ2,3)=CST(IQ2,KSTHI)
         ICLDW(IQ2,3)=KSTHI
89140 CONTINUE
CMIC$ PARALLEL SHARED(NX, CST, CLD, ICLDW, KSTHI, KSPHI) PRIVATE(IQ2, K)
      DO 700 K=KSTHI-1,KSPHI,-1
CMIC$ DO PARALLEL VECTOR
      DO 89160 IQ2=1,NX
        IF ( CST(IQ2,K).GT.CLD(IQ2,3) ) THEN
         CLD(IQ2,3)=CST(IQ2,K)
         ICLDW(IQ2,3)=K
        END IF
89160 CONTINUE
700   CONTINUE
CMIC$ END PARALLEL
C
C
      RETURN
      END
