      SUBROUTINE RDHSCATR(AIN,IT,AOUT,LEN)
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:48:52  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    RDHGATHR    TO SCATTER ACCORDING TO INDEX VECTOR
C   PRGMMR: J TUCCILLO       ORG: W/NMC4     DATE: 90-05-19
C
C ABSTRACT: SCATTER AIN ACCORDING TO IT
C   .
C
C PROGRAM HISTORY LOG:
C   90-05-19  J TUCCILLO
C
C USAGE:  CALL RDHSCATR ( AIN, IT, AOUT, LEN )
C   INPUT ARGUMENT LIST:
C     AIN      - VECTOR TO SCATTER FROM
C     IT       - INDEX VECTOR TO AIN
C     LEN      - LENGTH OF AIN, IT, AOUT
C
C   OUTPUT ARGUMENT LIST:
C     AOUT     - SCATTERED ELEMENTS OF AIN
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      DIMENSION AIN ( * ), AOUT ( * ), IT ( * )
CFPP$ PERMUTATION ( IT )
CMIC$ DO ALL VECTOR SHARED(LEN, AIN, IT, AOUT) PRIVATE(I)
      DO 1 I = 1, LEN
         AOUT ( IT ( I ) ) = AIN ( I )
1     CONTINUE
C
      RETURN
      END
