      SUBROUTINE SFCMIX( NG, NPAIR, HREC, PSKAPR, DT, WORK,
     1     CHGHQ,    LVLMAX , KLVL  )
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    SFCMIX      MIX THETA AND SPEC HUMIDITY IN NGM
C   PRGMMR: N PHILLIPS       ORG: W/NMC22    DATE: 86-12-26
C
C ABSTRACT: MIX POTENTIAL TEMPERATURE AND SPECIFIC HUMIDITY
C   .       IN THE BOTTOM LAYERS OF THE NGM, AS FORCED BY
C   .       THE UPWARD FLUX OF BUOYANCY FROM THE GROUND
C   .       ( DUE TO EVAPORATION AND SENSIBLE HEAT FLUX)
C   .       AND BY MECHANICAL STIRRING.
C   .       REFERENCE:  NMC OFFICE NOTE 318.
C   .
C  (CANCELLED   SR 'MIXDIAG' IS CALLED TO PRODUCE COLUMN DIAGS
C   SEPT 1987)  ACCORDING TO AN INTERVAL SET BY 'IDTDIAG'
C   .                   IN A DATA STATEMENT
C
C   CALLED BY ONEGRID IN FORECASTING.
C   .     A FLAG 'IFLSAT' IS SET BY A DATA STMNT. A ZERO VALUE
C   .          MEANS THAT SATURATION WILL NOT BE CONSIDERED
C   .          IN THE TOP MIXED LAYER.  A NON-ZERO VALUE MEANS
C   .          THAT SATURATION WILL BE CONSIDERED.
C   .     A DATA STMNT ALSO SETS THE VALUE 'SATMIX' THAT
C   .          SETS THE APPROX REL HUMID AT WHICH SATN
C   .          EFFECT WILL BE ALLOWED FOR.
C
C PROGRAM HISTORY LOG:
C   86-12-26  N PHILLIPS
C   86-05-27  N PHILLIPS ADDED OPTION FOR SATURATION AT
C                        TOP OF MIXED LAYERS
C   86-09-05  N PHILLIPS SET IFLSAT TO 0 TO CANCEL ABOVE
C                        COMPUTATION.
C   86-09-15  N PHILLIPS EXTENDED USE OF B3D IN IFLSAT LOOP
C                        TO CORRECT POSSIBLE ACCESS TO
C                        INDEFINITES
C                        (IN CASE THIS IS REACTIVATED)
C   87-10-31  J TUCCILLO PUT IN RESTRUCTURING OF VBL
C   88-02-14  N PHILLIPS CORRECTED CODE--TO USE BITGRDH WHEN
C                        STORING IN VBL FOR CASES OF NEGATIVE
C                        HEAT OR MOISTURE FLUX.
C   88-09-02  B SCHMIDT  REVISED THE DOCBLOCK
C
C USAGE:  CALL SFCMIX( NG, NPAIR, HREC, PSKAPR, DT, WORK,
C    1     CHGHQ,    LVLMAX , KLVL  )
C   INPUT ARGUMENT LIST:
C     NG       -   GRID NUMBER
C     NPAIR    -   FIRST OR SECOND CALL TO THIS GRID
C     HREC     -   ARRAY CONTAINING RECIPROCAL OF
C                    SURFACE PRESSURE  ( 1/H )
C     PSKAPR   -   ARRAY CONTAINING  1 / H**KAPPA
C     DT       -   TIME INCREMENT IN SECONDS
C     WORK     -   ARRAY CONTAINING DENSITY TIMES CUBE
C                    OF FRICTION VELOCITY R
C
C   OUTPUT ARGUMENT LIST:
C     CHGHQ    -  CHANGE IN  H * SPECIFIC HUMIDITY
C     LVLMAX   -  MAXIMUM LAYER HEIGHT AFFECTED BY MIXING
C     KLVL     -  K-VALUE OF LAYER ABOVE MIXED LAYERS
C                 ( EQUAL TO ONE PLUS HMIXED ) (INTEGER FORMAT)
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    -
C                  PRINTBIT
C                  VAPTAB
C                  MIXDIAG
C     LIBRARY:
C       COMMON   - COMCONST
C                  COMBLANK
C
C REMARKS:
C   .
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES        MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----        ----------------------------------        ---------
C   HF AND EV    HEAT FLUX AND EVAPORATION                 COMMON
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE         INTERFACE
C   -----       ----------------------------------         ---------
C   .
C   H*THETA     ADJUSTED FIELD OF SFC PRESSURE(H) TIMES    COMMON
C   .           POTENTIAL TEMPERATURE
C   .
C   HMIXED      NUMBER OF LAYERS THAT ARE COMPLETELY       COMMON
C   .           MIXED (HALF PRECISION FORMAT)
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:12:28  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      REAL R1S,R2S
      LOGICAL L1S
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C
C             ARGUMENT ARRAYS
      DIMENSION HREC(1),PSKAPR(1),WORK(1),CHGHQ(1),KLVL(1)
C
C
C               LOCAL ARRAYS FOR MIXING COEFFICIENTS
C
      DIMENSION S(IKM),   SR(IKM),    SIGDLK(IKM),    DELR(IKM),
     1         RB(IKM),   RR(IKM),     RSTAR(IKM),   ALPHA(IKM),
     2       BETA(IKM),    A(IKM),         B(IKM),       C(IKM),
     3          D(IKM),   AC(IKM),      ABCD(IKM),   NKLVL( 20)
C
C                J-LIMITS FOR DIFFERENT GRIDS AND VALUES OF NPAIR
      DIMENSION J1(INGRDUSE,2), J2(INGRDUSE,2)
C                 ARRAYS FOR PRINTING KLEVEL-1 AT THE END
      DIMENSION KPRT(IIJMAX),KLP(120)
C
C               BIT ARRAYS FOR COMPUTATION POINTS FOR THIS PROGRAM
      LOGICAL BITEX(IIJMAX,2,INGRDUSE)
C
C             SCRATCH BIT ARRAY AND BIT DESCRIPTORS
      LOGICAL BBSCR(IIJMAX,3) , B1D,B2D,B3D
C
C             SCRATCH INTEGER ARRAY
      DIMENSION IINT(IIJMAX)
C              NOMINAL STORAGE SPACE FOR ALL DESCRIPTORS
C                (A TOTAL OF 22 HALF PRECISION ARRAYS)
      DIMENSION       Z1(IIJMAX),   Z2(IIJMAX),   Z3(IIJMAX),
     1  Z4(IIJMAX),   Z5(IIJMAX),   Z6(IIJMAX),   Z7(IIJMAX),
     2  Z8(IIJMAX),   Z9(IIJMAX),  Z10(IIJMAX),  Z11(IIJMAX),
     3 Z12(IIJMAX),  Z13(IIJMAX),  Z14(IIJMAX),  Z15(IIJMAX),
     4 Z16(IIJMAX),  Z17(IIJMAX),  Z18(IIJMAX),  Z19(IIJMAX),
     5 Z20(IIJMAX),  Z21(IIJMAX), Z22(IIJMAX)
C
C                EQUIVALENCES OF THESE TO AVAILABLE SCRATCH SPACE
C                        IN BLANK COMMON
C        THE HORIZONTAL SCRATCH ARRAYS SCR(1,N) UP TO N=22 ARE USED
C               FROM THE UNLABELLED COMMON BLOCK IN MEMBER COMBLANK.
      EQUIVALENCE ( SCR(1, 1), Z1 ), ( SCR(1, 2), Z2),
     1            ( SCR(1, 3), Z3 ), ( SCR(1, 4), Z4),
     2            ( SCR(1, 5), Z5 ), ( SCR(1, 6), Z6),
     3            ( SCR(1, 7), Z7 ), ( SCR(1, 8), Z8),
     4            ( SCR(1, 9), Z9 ), ( SCR(1,10), Z10),
     5            ( SCR(1,11), Z11), ( SCR(1,12), Z12),
     6            ( SCR(1,13), Z13), ( SCR(1,14), Z14),
     7            ( SCR(1,15), Z15), ( SCR(1,16), Z16),
     8            ( SCR(1,17), Z17), ( SCR(1,18), Z18),
     9            ( SCR(1,19), Z19), ( SCR(1,20), Z20),
     1            ( SCR(1,21), Z21), ( SCR(1,22), Z22),
     2            ( SCR(1, 7),IINT)
C
C
      DATA ICALL /0/
C         FLAG TO ACTIVATE CONSIDERATION OF SATURATION
      DATA IFLSAT /0/
C         PERCENT OF SATN FOR ACTIVATING SATN BUOYANCY EFFECT
      DATA SATMIX /0.9E0/
C
C            TIME PARAMETERS FOR CALLING SR MIXDIAG
      DATA ITDIAG/9999999/,IDTDIAG/3600/
C-----------------------------------------------------------------
C
C              SPECIFY THE UNIT NUMBER OF THE PRINTER.
C-----------------------------------------------------------------
C
C              SPECIFY THE UNIT NUMBER OF THE PRINTER.
      IOUTUPRT = 6
C
C                   ENTRANCE
C       ON FIRST CALL WE MUST SET UP SOME TABLES FOR EFFICIENCY
      IF( ICALL .NE. 0 ) GO TO 100
C
C
      CSUBP = 1005.E0
      CKAPPA = 287.05E0 / CSUBP
C
C            GRAVITY
      GR = 9.8E0
C            SPECIFIC HEAT AT CONSTANT PRESSURE
C           GRAVITY DIVIDED BY C SUB P
      GOVCP = GR / CSUBP
C
C             COMPUTE MIXING COEFFICIENTS
C
CMIC$ DO ALL VECTOR SHARED(KM, DELSIG, DELR, PR, RR, SIGDLK) PRIVATE(K)
      DO 4 K=1,KM
C             RECIPROCAL OF DELTA SIGMA
      DELR(K) = 1.E0 / DELSIG(K)
C             RR  =   ( 1 - SIGMA IN LAYER K )**KAPPA
      RR(K) =  2.E0 * PR(K)
C
C             SAME THING TIMES DELTA SIGMA
      SIGDLK(K) = RR(K) * DELSIG(K)
C
    4 CONTINUE
C
C            RSTAR  =  (1 - SIGMA AT INTERFACES) TO KAPPA POWER
CMIC$ PARALLEL SHARED(RSTAR, RB, S, SR, KM, CKAPPA, DELSIG, SIGDLK)
CMIC$1    PRIVATE(K, SIGMA) MAXCPUS(2)
CMIC$ CASE
      SIGMA = 0.
      DO 9 K=1,KM
      RSTAR(K) =  (1.E0 - SIGMA)**CKAPPA
C
C                 ADVANCE SIGMA
      SIGMA = SIGMA + DELSIG(K)
    9 CONTINUE
C
C              S AND RB  =  SUMS OF DELSIG(K) AND SIGDLK(K)
C                 THROUGH LAYER  K-1 .
CMIC$ CASE
      RB(1) = 0.E0
      S(1) = 0.E0
CDIR@ NEXTSCALAR
      DO 10 K=2,KM
      S(K) = S(K-1) + DELSIG(K-1)
      RB(K) = RB(K-1) + SIGDLK(K-1)
C              RECIPROCAL OF S
      SR(K) = 1.E0 / S(K)
   10 CONTINUE
C
C                    CONSTANT FOR COOLING BOTTOM LAYER WHEN
C                    HEAT FLUX (HF) IS NEGATIVE
CMIC$ END CASE
CMIC$ END PARALLEL
C
C                    CONSTANT FOR COOLING BOTTOM LAYER WHEN
C                    HEAT FLUX (HF) IS NEGATIVE
      CNEGHF = 1.E0 / ( RR(1) * DELSIG(1) )
C
C                    CONVERT  RB(K) TO RB(K)/S(K).
CMIC$ DO ALL VECTOR SHARED(KM, RB, SR) PRIVATE(K)
      DO 12 K=2,KM
      RB(K) = RB(K) * SR(K)
C
   12 CONTINUE
C                 K-FUNCTIONS TO COMPUTE BUOYANCY CHANGES
      A(1) = 0.E0
      B(1) = 0.E0
      C(1) = 0.E0
      D(1) = 0.E0
      AC(1) = 0.E0
      ABCD(1) = 0.E0
C
CMIC$ DO ALL VECTOR SHARED(KM, DDORF, RB, RR, DELR, A, RSTAR, B, SR, C, 
CMIC$1   D, AC, ABCD) PRIVATE(K, DEN, CONST)
      DO 15 K=2,KM
      DEN = 1.E0 / ( RB(K) - RR(K) )
      A(K) = DEN * DELR(K)
C       DEARDORFF-WILLIS NUMBER TIMES HEIGHT FACTOR
      CONST = -DDORF * RSTAR(K)
      B(K) =  RB(K) + CONST
      C(K) = DEN * SR(K)
      D(K) =  RR(K) + CONST
      AC(K) = A(K)  +  C(K)
      ABCD(K) = A(K) * B(K)   +   C(K) * D(K)
C
   15 CONTINUE
C
C           FACTORS TO COMPUTE MEAN BUOYANCYS
C         MN BUOY(K) = S(K)*MN BUOY(K-1) + DEL(K)*BUOY(K)
C               ALL DIVIDED BY S(K+1)
C
      KMM1 = KM - 1
CMIC$ PARALLEL SHARED(NGRDUSE, IJMAX, IMG, JMG, BITEX, BITGRDH, J1, J2, 
CMIC$1   KMM1, S, SR, ALPHA, DELSIG, BETA) PRIVATE(NGG, IM, JM, IJ, LENU
CMIC$2   , NPS, IQ2, IQ2W6E, NNG, K)
CMIC$ DO PARALLEL VECTOR
      DO 20 K=2,KMM1
      ALPHA(K) = S(K) * SR(K+1)
      BETA(K) = DELSIG(K) * SR(K+1)
C
   20 CONTINUE
C
C       SET UP J-LIMITS TO INCLUDE ENOUGH H POINTS TO
C           ALLOW INTERPOLATION OF MIXING AMOUNT TO ALL HU FCST PTS.
CMIC$ DO PARALLEL VECTOR
      DO 30 NNG = 1,NGRDUSE
      JM = JMG(NNG)
      J1(NNG,1) = 3
      J2(NNG,1) = JM-1
      J1(NNG,2) = 5
      J2(NNG,2) = JM-3
C
   30 CONTINUE
C
C             SET UP BIT VECTORS FOR POINTS AT WHICH MASS
C        EXCHANGE MUST BE COMPUTED.  THIS INCLUDES ALL H FCST
C        POINTS PLUS H-POINTS ABOVE AND BELOW HU FCST PTS, AND
C        H-POINTS TO RIGHT AND TO LEFT OF HV FCST POINTS.
C       (NOTE THAT THE INCLUSION OF THE EXTRA POINTS IS CURRENTLY
C        BYPASSED.)
C
CMIC$ DO PARALLEL
      DO 50 NGG =1,NGRDUSE
      IM = IMG(NGG)
      JM = JMG(NGG)
      IJ = IM * JM
C            LENU = LENGTH OF REQUIRED J-ROWS ( SET BY U )
      LENU = IJ - IM
C
        DO 40 NPS = 1,2
C                 ZERO IT
C            NOW INCLUDE ALL FORECAST POINTS
      DO 1001 IQ2 = 1, IJMAX
         BITEX(IQ2,NPS,NGG) = .FALSE.
1001  CONTINUE
      DO 88890 IQ2W6E=1,IJ
         BITEX(IQ2W6E,NPS,NGG)=BITGRDH(IQ2W6E,NPS,NGG)
88890 CONTINUE
C
   40   CONTINUE
C
   50 CONTINUE
CMIC$ END PARALLEL
C           SOME CONSTANTS USED IN THE SATURATION COMPUTATION
      EPS = 287.05 / 461.5E0
      C6 = EPS * CKAPPA
C
C     IF( IFLSAT .EQ. 0 ) PRINT 51
C  51 FORMAT(1H0,2X,'******** SR SFCMIX WILL IGNORE SATURATION' )
C     IF( IFLSAT .NE. 0 ) PRINT 52
C  52 FORMAT(1H0,2X,'******** SR SFCMIX WILL ALLOW FOR SATURATION')
C
C
CCCCCCCCCCCCCCCCC  DONE WITH ALL PREPARATORY WORK CCCCCCCCCCCCCCCCCC
C
C---------------------------------------------------------------
C
C                      ENTRANCE TO DO THE MIXING
  100 ICALL = ICALL + 1
C
C-----------------------------------------------------------------
C
C                  DIMENSIONS FOR CURRENT GRID
      IM = IMG(NG)
      JM = JMG(NG)
      IJ = IM*JM
C
C                   CLEAR ARRAY NKLVL
CMIC$ DO ALL VECTOR SHARED(NKLVL) PRIVATE(K)
      DO 101 K=1,20
          NKLVL(K) = 0
  101 CONTINUE
C       (NKLVL RECORDS NUMBER OF POINTS TO ADJUST AT EACH LVL)
C
C               CORRECT DT TO INCORPORATE THE SPECIAL NGM
C               UNIT OF 100 CBS FOR SURFACE PRESSURE(I.E.H )
C               IN COMPUTING THE CHANGE OF H*THETA(VIRT),
C               AND    H*THETA WHEN  HF  IS NEGATIVE,
C               AND    H*Q     WHEN  EV  IS NEGATIVE.
C
      DT1 = DT * 0.01
C
C               SET UP THE VECTOR ADDRESS AND LENGTH FOR
C               COMPUTING BUOYANCY PARAMETERS ( 1ST K-LOOP )
      JJ1 = J1(NG,NPAIR)
      JJ2 = J2(NG,NPAIR)
      IM = IMG(NG)
      IAD = (JJ1-1) * IM + 1
      LEN = (JJ2 - JJ1 + 1 ) * IM
C
C           THE INPUT FIELDS
      IADHF = IADDRG(36,NG) + IAD - 1
      IADMF = IADDRG(37,NG) + IAD - 1
C           ARRAYS FOR BOTH OUTPUT AND COMPUTATION
C       (INTEGER FOR 1ST STABLE LAYER, HALF-PRECISION FOR NUMBER
C                OF MIXED LAYERS )
      IADDML = IADDRG(24,NG) + IAD - 1
C                 THE BIT VECTORS
C           B1D WILL KEEP TRACK OF POINTS THAT NEED TO BE COMPUTED
C              COPY THE BIT VECTOR FOR THIS PASS
CMIC$ DO ALL VECTOR SHARED(LEN, IAD, NPAIR, NG, BITEX, BBSCR) PRIVATE(
CMIC$1   IQ2W6E)
      DO 88920 IQ2W6E=1,LEN
         BBSCR(IAD+IQ2W6E-1,1)=BITEX(IAD+IQ2W6E-1,NPAIR,NG)
88920 CONTINUE
C
C            ADDRESSES FOR H*THETA(K=1), H*Q(K=1), AND H  .
      IADT1 = IADDRG(3,NG) + IAD - 1
      IADQ1 = IADDRG(4,NG) + IAD - 1
      IADH  = IADDRG(5,NG) + IAD - 1
C
C           NEEDED CONSTANTS TO CONVERT FROM INPUT  HF  AND  EV
      BOYF1 = DT1 * GOVCP
      BOYF2 = DT1 * GR
C                ADDITIONAL CONSTANTS
      DORFM1 = 1.E0 - DDORF
      CW = PKATO * GOVCP * DT1
      CWW = CW * (1.125E-3) * (8.0E-6)
C            FIRST COMPUTE DHTH = INPUT OF H*THETA FROM GROUND
C                     AND  DHQ  = INPUT OF WATER FROM GROUND
C           DO THIS ONLY AT NEEDED POINTS
CMIC$ PARALLEL SHARED(LEN, IAD, DORFM1, CW, CWW, IADT1, IADQ1, BBSCR, Z1
CMIC$1   , Z3, Z2, Z4, Z5, WORK, Z6, VBL, Z7, DELSIG, Z8, Z9, NPAIR, NG
CMIC$2   , BITGRDH, DELR, CNEGHF, IADHF, BOYF1, BOYF2, IADMF, PSKAPR, 
CMIC$3   HREC) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 88930 IQ2W6E=1,LEN
       IF ( BBSCR(IAD+IQ2W6E-1,1) ) THEN
         Z1(IAD+IQ2W6E-1)=PSKAPR(IAD+IQ2W6E-1)*VBL(IADHF+IQ2W6E-1)*
     *                    BOYF1
         Z2(IAD+IQ2W6E-1)=BOYF2*VBL(IADMF+IQ2W6E-1)
         Z3(IAD+IQ2W6E-1)=0.609E0*VBL(IADQ1+IQ2W6E-1)*HREC(IAD+IQ2W6E-
     *   1) + 1.E0
         Z4(IAD+IQ2W6E-1)=0.609E0*VBL(IADT1+IQ2W6E-1)*HREC(IAD+IQ2W6E-
     *   1)
       END IF
88930 CONTINUE
C
C                 CHECK FOR NEGATIVE HEAT FLUX
CMIC$ DO PARALLEL VECTOR
      DO 88990 IQ2W6E=1,LEN
         BBSCR(IAD+IQ2W6E-1,2)=Z1(IAD+IQ2W6E-1).LT.0.E0
C        B3D FOR NEGATIVE HT FLUX AT FORECAST POINTS
         BBSCR(IAD+IQ2W6E-1,3)=BBSCR(IAD+IQ2W6E-1,2).AND.BITGRDH(
     *   IAD+IQ2W6E-1,NPAIR,NG)
C               AT THESE POINTS SUBTRACT HEAT FLUX FROM
C               H*THETA FOR K=1.
       IF ( BBSCR(IAD+IQ2W6E-1,3) ) THEN
         VBL(IADT1+IQ2W6E-1)=VBL(IADT1+IQ2W6E-1)+CNEGHF*Z1(IAD+IQ2W6E-
     *   1)
       END IF
C       NOW MAKE ALL NEGATIVE HEAT FLUX VALUES EQUAL TO ZERO.
       IF ( BBSCR(IAD+IQ2W6E-1,2) ) THEN
         Z1(IAD+IQ2W6E-1)=0.E0
       END IF
88990 CONTINUE
C
C        CHECK FOR NEGATIVE EVAPORATION, AND REPEAT ABOVE PROCESS
CMIC$ DO PARALLEL VECTOR
      DO 89030 IQ2W6E=1,LEN
         BBSCR(IAD+IQ2W6E-1,2)=Z2(IAD+IQ2W6E-1).LT.0.E0
C        B3D FOR NEGATIVE EVAPORATION AT FORECAST POINTS
         BBSCR(IAD+IQ2W6E-1,3)=BBSCR(IAD+IQ2W6E-1,2).AND.BITGRDH(
     *   IAD+IQ2W6E-1,NPAIR,NG)
C               AT THESE POINTS SUBTRACT EVAP FROM H*Q(K=1)
       IF ( BBSCR(IAD+IQ2W6E-1,3) ) THEN
         VBL(IADQ1+IQ2W6E-1)=VBL(IADQ1+IQ2W6E-1)+DELR(1)*Z2(IAD+IQ2W6E
     *   -1)
       END IF
C               NOW ZERO OUT ALL NEGATIVE EVAPORATION VALUES
       IF ( BBSCR(IAD+IQ2W6E-1,2) ) Z2(IAD+IQ2W6E-1)=0.E0
89030 CONTINUE
C
C            COMPUTE THE BUOYANCY FORCING TERM  (X)
C         FIRST THE HEAT FLUX CONTRIBUTION
CMIC$ DO PARALLEL VECTOR
      DO 89070 IQ2W6E=1,LEN
       IF ( BBSCR(IAD+IQ2W6E-1,1) ) THEN
         Z5(IAD+IQ2W6E-1)=Z1(IAD+IQ2W6E-1)*Z3(IAD+IQ2W6E-1) +
     *                    Z2(IAD+IQ2W6E-1)*Z4(IAD+IQ2W6E-1)
         Z6(IAD+IQ2W6E-1)=DORFM1*Z5(IAD+IQ2W6E-1) +
     *                    CW*WORK(IAD+IQ2W6E-1) + CWW
         Z7(IAD+IQ2W6E-1)=Z3(IAD+IQ2W6E-1)*VBL(IADT1+IQ2W6E-1)+
     *                    Z4(IAD+IQ2W6E-1)*VBL(IADQ1+IQ2W6E-1)
         Z8(IAD+IQ2W6E-1)=VBL(IADT1+IQ2W6E-1)*DELSIG(1)
         Z9(IAD+IQ2W6E-1)=VBL(IADQ1+IQ2W6E-1)*DELSIG(1)
       END IF
89070 CONTINUE
CMIC$ END PARALLEL
C
C
C                PREPARE NOW TO ENTER THE MAIN K-LOOP
C    TO COMPUTE MIXING LEVELS, AND THE ADJUSTED  H*THETA AND H*Q
C
      KMM1 = KM - 1
C--------------------------------------------------------
      DO 200 K = 2,KMM1
C
C          RECORD THE TOP LEVEL REACHED
      LVLMAX = K
C          ADDRESSES FOR H*THETA AND H*Q AT LEVEL K
      IADT = IADT1 + (K-1)*IJ
      IADQ = IADQ1 + (K-1)*IJ
C          BUOYANCY AT LEVEL K ASSUMING NO SATURATION AT LEVEL K-1
CMIC$ DO ALL VECTOR SHARED(LEN, IAD, IADT, IADQ, K, Z3, VBL, Z4, Z10, AC
CMIC$1   , Z6, ABCD, Z5, Z17, Z7, Z18, BBSCR) PRIVATE(IQ2W6E)
      DO 89180 IQ2W6E=1,LEN
         Z10(IAD+IQ2W6E-1)=Z3(IAD+IQ2W6E-1)*VBL(IADT+IQ2W6E-1) +
     *                     Z4(IAD+IQ2W6E-1)*VBL(IADQ+IQ2W6E-1)
C
C          COMPUTE CRITICAL VERTICAL CHANGE IN BUOYANCY IN Z17
         Z17(IAD+IQ2W6E-1)=AC(K)*Z6(IAD+IQ2W6E-1)
     *                     -ABCD(K)*Z5(IAD+IQ2W6E-1)
C               (NOTE THAT THIS WILL BE GREATER THAN ZERO,
C                EVEN FOR ZERO VALUES OF HF,EV, AND WORK,
C                BECAUSE OF THE  CWW  TERM ADDED TO FXD EARLIER.)
C          PUT THE VERTICAL BUOYANCY DIFFERENCE INTO Z18
         Z18(IAD+IQ2W6E-1)=Z10(IAD+IQ2W6E-1)-Z7(IAD+IQ2W6E-1)
C
C       ESTABLISH PTS WHERE CRITERION IS SATISFIED AND NEEDED
         BBSCR(IAD+IQ2W6E-1,2)=Z18(IAD+IQ2W6E-1).GT.Z17(IAD+IQ2W6E-1)
     *                       .AND.BBSCR(IAD+IQ2W6E-1,1)
89180 CONTINUE
C             COUNT THEM
      NXXX = 0
      DO 9002 IQ2 = 1, LEN
         IF ( BBSCR(IAD+IQ2-1,2)) NXXX = NXXX + 1
9002  CONTINUE
      NKLVL(K) = NXXX
C            IF NO POINTS ON THIS LEVEL, SKIP TO PREPARE FOR NEXT LVL
      IF( NKLVL(K) .EQ. 0 ) GO TO 150
C            HAVE POINTS,  DO THE WORK FOR THESE
      TWOPR = 2.E0 * PR(K-1)
C
CMIC$ DO ALL VECTOR SHARED(LEN, IAD, K, IADT, IADQ, TWOPR, BBSCR, Z6, B
CMIC$1   , Z5, Z17, A, Z11, KLVL, PRESS, WORK, Z12, SR, Z8, Z14, VBL, 
CMIC$2   Z13, Z9, Z16, Z15, Z19, DELSIG, Z20, PSKAPR, Z21, Z18, Z22)
CMIC$3    PRIVATE(IQ2W6E)
      DO 89260 IQ2W6E=1,LEN
       IF ( BBSCR(IAD+IQ2W6E-1,2) ) THEN
         Z17(IAD+IQ2W6E-1)=Z6(IAD+IQ2W6E-1)-B(K)*Z5(IAD+IQ2W6E-1)
         Z11(IAD+IQ2W6E-1)=A(K)*Z17(IAD+IQ2W6E-1)
         KLVL(IAD+IQ2W6E-1)=K
         WORK(IAD+IQ2W6E-1)=PRESS(K)
         Z12(IAD+IQ2W6E-1)=PRESS(K-1)
         Z14(IAD+IQ2W6E-1)=SR(K)*Z8(IAD+IQ2W6E-1)
         Z13(IAD+IQ2W6E-1)=VBL(IADT+IQ2W6E-1)
         Z16(IAD+IQ2W6E-1)=SR(K)*Z9(IAD+IQ2W6E-1)
         Z15(IAD+IQ2W6E-1)=VBL(IADQ+IQ2W6E-1)
         Z19(IAD+IQ2W6E-1)=SR(K)
         Z20(IAD+IQ2W6E-1)=DELSIG(K)
         Z21(IAD+IQ2W6E-1)=TWOPR/PSKAPR(IAD+IQ2W6E-1)
         Z22(IAD+IQ2W6E-1)=Z18(IAD+IQ2W6E-1)
       END IF
C            ELIMINATE THE NEWLY SATISFIED POINTS FROM B1D
         BBSCR(IAD+IQ2W6E-1,1)=BBSCR(IAD+IQ2W6E-1,1).AND..NOT.BBSCR(IA
     *   D+IQ2W6E-1,2)
89260 CONTINUE
C             DO WE HAVE ANY POINTS LEFT?
      NB1  = 0
      DO 9003 IQ2 = 1, LEN
         IF ( BBSCR(IAD+IQ2-1,1)) NB1 = NB1 + 1
9003  CONTINUE
C             EXIT THIS K-LOOP IF NO POINTS LEFT
      IF( NB1 .EQ. 0 ) GO TO 300
C           HAVE MORE LEVELS TO CONSIDER
C
  150 CONTINUE
C                  AT THE REMAINING  POINTS,
C            UPDATE SUMTH, SUMQ, AND BOYM BEFORE GOING TO NEXT LEVEL
CMIC$ DO ALL VECTOR SHARED(LEN, IAD, K, IADT, IADQ, BBSCR, Z8, DELSIG, 
CMIC$1   VBL, Z9, ALPHA, Z7, BETA, Z10) PRIVATE(IQ2W6E)
      DO 89400 IQ2W6E=1,LEN
       IF ( BBSCR(IAD+IQ2W6E-1,1) ) THEN
         Z8(IAD+IQ2W6E-1)=Z8(IAD+IQ2W6E-1)+DELSIG(K)*VBL(IADT+IQ2W6E-1
     *   )
         Z9(IAD+IQ2W6E-1)=Z9(IAD+IQ2W6E-1)+DELSIG(K)*VBL(IADQ+IQ2W6E-1
     *   )
         Z7(IAD+IQ2W6E-1)=ALPHA(K)*Z7(IAD+IQ2W6E-1) +
     *                     BETA(K)*Z10(IAD+IQ2W6E-1)
       END IF
89400 CONTINUE
C
C              END OF FIRST K-LOOP
C
  200 CONTINUE
C----------------------------------------------------------------
C            INSERT AN ERROR STOP HERE.
C
      WRITE (IOUTUPRT, 205) NG,NPAIR,NB1,ITIME
  205 FORMAT(1H1,2X,'******* WENT THROUGH 1ST K-LOOP IN SR ',
     1   'SFCMIX.  NG, NPAIR, NB1,ITIME =',4I10 )
C
      CALL PRINTBIT( BBSCR(1,1),IM,JM,IM,JM,NG,
     1  'BIT MAP AFTER 1ST KLOOP ')
C
      CALL EXIT(16)
C
C--------------------------------------------------------------
C
  300 CONTINUE
C                      EXIT WHEN BUOYANCY LEVEL HAS BEEN
C                      DETERMINED FOR ALL DESIRED POINTS
C
C                 RESET B1D TO THE FORECAST POINTS
CMIC$ DO ALL VECTOR SHARED(LEN, IAD, NPAIR, NG, BITEX, BBSCR) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89440 IQ2W6E=1,LEN
         BBSCR(IAD+IQ2W6E-1,1)=BITEX(IAD+IQ2W6E-1,NPAIR,NG)
89440 CONTINUE
C
C             ARE WE TO CONSIDER POSSIBILITY OF SATURATION IN THE
C       LEVEL KLVL - 1  ( IN THE TOPMOST COMPLETELY MIXED LAYER )
C
      IF( IFLSAT .EQ. 0 ) GO TO 310
C            DO SO.  FIRST COMPUTE TEMP(K-1) AND PUT IN Z3
      C3 = SATMIX * EPS / 100.E0
      C4 = CSUBP / ( EPS*2.5E6 )
      C5 = 2.E0 * CKAPPA
CMIC$ DO ALL VECTOR SHARED(LEN, IAD, Z21, Z14, HREC, Z3) PRIVATE(IQ2W6E)
      DO 89450 IQ2W6E=1,LEN
         Z3(IAD+IQ2W6E-1)=Z21(IAD+IQ2W6E-1)*Z14(IAD+IQ2W6E-1)*
     *                        HREC(IAD+IQ2W6E-1)
89450 CONTINUE
C              GET SAT VAPOR PRESS (CBS) INTO Z4
C
      CALL VAPTAB( Z3(IAD),Z4(IAD), LEN, 1 )
C
C            PUT  SATMIX TIMES H*Q(SAT) AT K-1 INTO Z4
CMIC$ PARALLEL SHARED(LEN, IAD, Z16, Z4, BBSCR, Z12, C3) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89470 IQ2W6E=1,LEN
         Z4(IAD+IQ2W6E-1)=C3*Z4(IAD+IQ2W6E-1)
89470 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89480 IQ2W6E=1,LEN
       IF ( BBSCR(IAD+IQ2W6E-1,1) ) THEN
         Z4(IAD+IQ2W6E-1)=Z4(IAD+IQ2W6E-1)/Z12(IAD+IQ2W6E-1)
       END IF
89480 CONTINUE
C            ESTABLISH 'SATURATED'  POINTS IN B3D
CMIC$ DO PARALLEL VECTOR
      DO 89490 IQ2W6E = 1, LEN
         BBSCR(IAD+IQ2W6E-1,3) = Z16(IAD+IQ2W6E-1) .GE. Z4(IAD+IQ2W6E-1)
         BBSCR(IAD+IQ2W6E-1,3) = BBSCR(IAD+IQ2W6E-1,3) .AND. BBSCR(IAD+
     1      IQ2W6E-1,1)
89490 CONTINUE
CMIC$ END PARALLEL
C        B3D=1 FOR SATURATED FORECAST POINTS. COUNT THEM
      NSATN = 0
      DO 9007 IQ2 = 1, LEN
         IF ( BBSCR(IAD+IQ2-1,3)) NSATN = NSATN + 1
9007  CONTINUE
      IF( NSATN .LE. 0 ) GO TO 310
C          SINCE THERE ARE SATURATED POINTS, MUST COMPUTE
C          AN ADJUSTMENT TO THE BUOYANCY IN LAYER K
C          BEFORE CALCULATING THE MIXING COEFFICIENT 'XM'
C
C              REPLACE TEMPERATURE IN Z3 BY 'TAU'
CMIC$ PARALLEL SHARED(LEN, IAD, Z22, Z11, BBSCR, C4, C5, IADH, C6, Z3, 
CMIC$1   WORK, Z12, Z17, Z18, Z14, Z16, VBL) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89510 IQ2W6E=1,LEN
       IF ( BBSCR(IAD+IQ2W6E-1,3) ) THEN
         Z3(IAD+IQ2W6E-1)=C4*Z3(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=C5*(WORK(IAD+IQ2W6E-1)-Z12(IAD+IQ2W6E-1))
         Z18(IAD+IQ2W6E-1)=WORK(IAD+IQ2W6E-1)+Z12(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)/Z18(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)*(1.E0-Z3(IAD+IQ2W6E-1))
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)*Z14(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)*Z16(IAD+IQ2W6E-1)
         Z3(IAD+IQ2W6E-1)=Z3(IAD+IQ2W6E-1)*Z3(IAD+IQ2W6E-1)
         Z3(IAD+IQ2W6E-1)=Z3(IAD+IQ2W6E-1)*VBL(IADH+IQ2W6E-1)
         Z18(IAD+IQ2W6E-1)=Z16(IAD+IQ2W6E-1)+C6*Z3(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)/Z18(IAD+IQ2W6E-1)
         Z22(IAD+IQ2W6E-1)=Z22(IAD+IQ2W6E-1)+Z17(IAD+IQ2W6E-1)
       END IF
89510 CONTINUE
C            MAKE SURE THAT CORRECTION IS NOT TOO DRASTIC
C              (COULD HAPPEN IF LAPSE RATE IS LT MST ADIABATIC))
CMIC$ DO PARALLEL VECTOR
      DO 89630 IQ2W6E = 1, LEN
         BBSCR(IAD+IQ2W6E-1,2)=Z22(IAD+IQ2W6E-1).LT.Z11(IAD+IQ2W6E-1)
         BBSCR(IAD+IQ2W6E-1,3) = BBSCR(IAD+IQ2W6E-1,2) .AND. BBSCR(IAD+
     1      IQ2W6E-1,3)
         IF(BBSCR(IAD+IQ2W6E-1,3))Z22(IAD+IQ2W6E-1)=Z11(IAD+IQ2W6E-1)
89630 CONTINUE
CMIC$ END PARALLEL
C            (THIS WILL KEEP XM FROM EXCEEDING 1 )
C
C            REJOIN REGULAR COMPUTATION
  310 CONTINUE
C
C          COMPUTE THE EXCHANGE PARAMETER XM
CMIC$ DO ALL VECTOR SHARED(LEN, IAD, BBSCR, Z11, Z22) PRIVATE(IQ2W6E)
      DO 89660 IQ2W6E=1,LEN
       IF ( BBSCR(IAD+IQ2W6E-1,1) ) THEN
         Z11(IAD+IQ2W6E-1)=Z11(IAD+IQ2W6E-1)/Z22(IAD+IQ2W6E-1)
       END IF
89660 CONTINUE
C
C--------- TEST THE RANGE OF XM
      XMMIN = 1.E+35
      XMMAX = -1.E+35
CMIC$ PARALLEL SHARED(LEN, IAD, XMMIN, XMMAX, BBSCR, Z11) PRIVATE(IQ2, 
CMIC$1   R1S, R2S, L1S)
      R1S = XMMIN
      R2S = XMMAX
CMIC$ DO PARALLEL VECTOR
      DO 7002 IQ2 = 1, LEN
         L1S = BBSCR(IAD+IQ2-1,1)
         IF (L1S) THEN
            R1S = AMIN1(Z11(IAD+IQ2-1),R1S)
            R2S = AMAX1(Z11(IAD+IQ2-1),R2S)
         ELSE
         ENDIF
 7002 CONTINUE
CMIC$ GUARD
      XMMAX = AMAX1(XMMAX,R2S)
CMIC$ END GUARD
CMIC$ GUARD
      XMMIN = AMIN1(XMMIN,R1S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
      IF( XMMIN .LT. -0.1E-4 ) PRINT 450,XMMIN,NG,ITIME
  450 FORMAT(1H ,2X,'**** IN SR SFCMIX, MIN XM =',E14.4,
     1  ' ON GRID',I4,' AT ITIME=',I8)
      IF( XMMAX .GT. 1.00001E0 ) PRINT 451,XMMAX,NG,ITIME
  451 FORMAT(1H ,2X,'**** IN SR SFCMIX, MAX XM =',E14.4,
     1  ' ON GRID',I4,' AT ITIME=',I8)
C
C-------------------------------------------------------
C------ COMPUTE NEW VALUES OF H*THETA FOR LVL K AND LVLS 1-(K-1)
C              PUT THE CHANGE IN H*THETA AT K INTO Z18
CMIC$ DO ALL VECTOR SHARED(LEN, IAD, BBSCR, Z14, Z13, Z17, Z11, Z18, Z20
CMIC$1   , Z1, Z19, Z16, Z15, Z2) PRIVATE(IQ2W6E)
      DO 89670 IQ2W6E=1,LEN
       IF ( BBSCR(IAD+IQ2W6E-1,1) ) THEN
         Z17(IAD+IQ2W6E-1)=Z14(IAD+IQ2W6E-1)-Z13(IAD+IQ2W6E-1)
         Z18(IAD+IQ2W6E-1)=Z11(IAD+IQ2W6E-1)*Z17(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=-Z20(IAD+IQ2W6E-1)*Z18(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)+Z1(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)*Z19(IAD+IQ2W6E-1)
         Z14(IAD+IQ2W6E-1)=Z14(IAD+IQ2W6E-1)+Z17(IAD+IQ2W6E-1)
         Z13(IAD+IQ2W6E-1)=Z13(IAD+IQ2W6E-1)+Z18(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z16(IAD+IQ2W6E-1)-Z15(IAD+IQ2W6E-1)
         Z18(IAD+IQ2W6E-1)=Z11(IAD+IQ2W6E-1)*Z17(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=-Z20(IAD+IQ2W6E-1)*Z18(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)+Z2(IAD+IQ2W6E-1)
         Z17(IAD+IQ2W6E-1)=Z17(IAD+IQ2W6E-1)*Z19(IAD+IQ2W6E-1)
         Z16(IAD+IQ2W6E-1)=Z16(IAD+IQ2W6E-1)+Z17(IAD+IQ2W6E-1)
         Z15(IAD+IQ2W6E-1)=Z15(IAD+IQ2W6E-1)+Z18(IAD+IQ2W6E-1)
       END IF
89670 CONTINUE
C
C---------------------------------------------------------
C              STORE THE ADJUSTED VALUES IN ARRAY VBL
C             WE STORE ONLY AT FORECAST H POINTS
C             ALSO ADD THE TURBULENT EFFECTS TO THE ADVECTIVE
C             CHANGES IN H*SPEC HUMID THAT ARE IN ARRAY CHGHQ.
C
C
C
C             (LEN IS ONE ROW TOO LONG, BUT BITGRDH SHOULD HAVE
C              ZEROS THERE)
C         ADDRESS TO ACCESS H*THETA IN ARRAY VBL
      JADTH = IADDRG(3,NG) - 1 + IAD -IJ
C         ADDRESS TO ACCESS H*Q IN ARRAY VBL
      JADQ = IADDRG(4,NG) - 1 + IAD - IJ
C         ADDRESS TO STORE IN ARRAY CHGHQ
      JCHQ = IAD - IJ
C--------------------------------------------------------
      DO 400 K = 1,LVLMAX
C           ADVANCE ADDRESSES
      JADTH = JADTH + IJ
      JADQ  = JADQ  + IJ
      JCHQ  = JCHQ  + IJ
C
C             STORE MIXED VALUES WHERE K .LT. KLVL
C            (CAN SKIP THIS FOR K=LVLMAX)
      IF( K .EQ. LVLMAX) GO TO 320
CMIC$ DO ALL VECTOR IF ((ABS(JADTH-JADQ).GE.LEN .OR. JADTH-JADQ.EQ.0)
CMIC$1    .AND. (ABS(JADTH-IADDML).GE.LEN .OR. JADTH-IADDML.EQ.0) .AND. 
CMIC$2   (ABS(JADQ-IADDML).GE.LEN .OR. JADQ-IADDML.EQ.0)) SHARED(LEN, 
CMIC$3   IAD, K, NPAIR, NG, JADTH, JADQ, IADDML, JCHQ, KLVL, BBSCR, 
CMIC$4   BITGRDH, Z14, VBL, Z16, CHGHQ) PRIVATE(IQ2W6E)
      DO 89810 IQ2W6E=1,LEN
         BBSCR(IAD+IQ2W6E-1,2)=KLVL(IAD+IQ2W6E-1).GT.K
C           ONLY FOR FORECAST H POINTS
         BBSCR(IAD+IQ2W6E-1,2)=BBSCR(IAD+IQ2W6E-1,2).AND.BITGRDH(
     *   IAD+IQ2W6E-1,NPAIR,NG)
       IF ( BBSCR(IAD+IQ2W6E-1,2) ) THEN
         VBL(JADTH+IQ2W6E-1)=Z14(IAD+IQ2W6E-1)
         VBL(IADDML+IQ2W6E-1)=Z16(IAD+IQ2W6E-1)-VBL(JADQ+IQ2W6E-1)
         CHGHQ(JCHQ+IQ2W6E-1)=CHGHQ(JCHQ+IQ2W6E-1)+VBL(IADDML+IQ2W6E-1
     *   )
         VBL(JADQ+IQ2W6E-1)=Z16(IAD+IQ2W6E-1)
       END IF
89810 CONTINUE
C
  320 CONTINUE
C            CONSIDER STORING NEW H*THETA,H*Q AND CHGHQ FOR KLVL = K
C             ( CAN SKIP THIS FOR K=1)
      IF ( K .EQ. 1 ) GO TO 400
CMIC$ DO ALL VECTOR IF ((ABS(JADTH-JADQ).GE.LEN .OR. JADTH-JADQ.EQ.0)
CMIC$1    .AND. (ABS(JADTH-IADDML).GE.LEN .OR. JADTH-IADDML.EQ.0) .AND. 
CMIC$2   (ABS(JADQ-IADDML).GE.LEN .OR. JADQ-IADDML.EQ.0)) SHARED(LEN, 
CMIC$3   IAD, K, NPAIR, NG, JADTH, JADQ, IADDML, JCHQ, KLVL, BBSCR, 
CMIC$4   BITGRDH, Z13, VBL, Z15, CHGHQ) PRIVATE(IQ2W6E)
      DO 89870 IQ2W6E=1,LEN
         BBSCR(IAD+IQ2W6E-1,2)=KLVL(IAD+IQ2W6E-1).EQ.K
C            ONLY FOR FORECAST H POINTS
         BBSCR(IAD+IQ2W6E-1,2)=BBSCR(IAD+IQ2W6E-1,2).AND.BITGRDH(
     *   IAD+IQ2W6E-1,NPAIR,NG)
       IF ( BBSCR(IAD+IQ2W6E-1,2) ) THEN
         VBL(JADTH+IQ2W6E-1)=Z13(IAD+IQ2W6E-1)
         VBL(IADDML+IQ2W6E-1)=Z15(IAD+IQ2W6E-1)-VBL(JADQ+IQ2W6E-1)
         CHGHQ(JCHQ+IQ2W6E-1)=CHGHQ(JCHQ+IQ2W6E-1)+VBL(IADDML+IQ2W6E-1
     *   )
         VBL(JADQ+IQ2W6E-1)=Z15(IAD+IQ2W6E-1)
       END IF
89870 CONTINUE
C
C              END OF K-LOOP FOR STORING THE NEW VALUES OF
C                    H*THETA, H*Q, AND
C                    THE VALUES OF THE CHANGE IN H*Q
C                    ( THE LAST INCLUDES BOTH ADVECTION
C                     AND SFC MIXING CHANGES )
  400 CONTINUE
C
C
C--------- RECORD THE NUMBER OF MIXED LAYERS AS HALF-PRECISION
C                WORD IN ARRAY PHYSDIAG
      IADDML = IADDRG(24,NG)
CMIC$ DO ALL VECTOR SHARED(IJ, NPAIR, NG, IADDML, BITGRDH, KLVL, VBL)
CMIC$1    PRIVATE(IQ2W6E)
      DO 89940 IQ2W6E=1,IJ
       IF ( BITGRDH(IQ2W6E,NPAIR,NG) ) THEN
         VBL(IADDML+IQ2W6E-1)=FLOAT(KLVL(IQ2W6E)) -1.E0
       ELSE
         VBL(IADDML+IQ2W6E-1)=0.
       END IF
89940 CONTINUE
C-------------------------
C--------- CONSIDER ASKING FOR COLUMN DIAGNOSTICS FROM MIXDIAG
      IF(NG .NE. NGRDUSE ) GO TO 410
      IF( ITIME .LE. ITDIAG ) GO TO 410
C           TIME TO GET THEM
      CALL MIXDIAG
C           ADVANCE ITDIAG FOR NEXT TIME
      ITDIAG = ITDIAG + IDTDIAG
C
  410 CONTINUE
C
C----------------------------------------------------------
C
C------ TO PRINT OUT KLVL-1 = NUMBER OF MIXED LAYERS
C                  THE GRID TO BE PRINTED
      NGKPRT = NGRDUSE
C               THE TIME DESIRED
      IT2C = 172801
      IF( ITIME .NE. IT2C ) GO TO 1000
      IF( NG .NE. NGKPRT ) GO TO 900
C             SAVE THIS GRID OF VALUES IN ARRAY KPRT
CMIC$ DO ALL VECTOR SHARED(IJ, NPAIR, NG, KPRT, BITGRDH, KLVL) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89950 IQ2W6E = 1, IJ
         KPRT(IQ2W6E) = 0
         IF (BITGRDH(IQ2W6E,NPAIR,NG)) KPRT(IQ2W6E) = KLVL(IQ2W6E) - 1
89950 CONTINUE
C         TEST FOR TIME TO PRINT (AFTER GRID A )
  900 IF( NG .NE. 1 ) GO TO 1000
      WRITE (IOUTUPRT, 902) NGKPRT,ITIME
  902 FORMAT(1H1,32X,'KLVL-1 FROM SFCMIX,FOR GRID',I3,
     1 ' AT ITIME=',I10,' SECS')
      IMP = IMG(NGKPRT)
      JMP = JMG(NGKPRT)
      IJP = IMP*JMP
      LVLMAX = KPRT(1)
      DO 5882 IQ2 = 1, IJP
         LVLMAX = AMAX0 ( KPRT(IQ2), LVLMAX )
5882  CONTINUE
      PRINT 903, LVLMAX
  903 FORMAT(1H0,45X,'MAXIMUM VALUE IS',I4)
      PRINT 904
  904 FORMAT(1H0,40X,'ALL VALUES OVER EIGHT ARE NOW SET EQUAL TO NINE')
C                CHANGE VALUES .GT. 8 TO 9
CMIC$ DO ALL VECTOR SHARED(IJP, KPRT) PRIVATE(IQ2W6E)
      DO 89970 IQ2W6E=1,IJP
         IF (KPRT(IQ2W6E).GT.8) KPRT(IQ2W6E)=9
89970 CONTINUE
C
C             PRINT KLVL-1 AND THEN BITSEA AS DENSE ARRAYS
      ILOOK = 1
  905 CONTINUE
      PRINT 906
  906 FORMAT(1H0,17X,'1',9X,'2',9X,'3',9X,'4',9X,'5',9X,'6',
     1 9X,'7',9X,'8',9X,'9',9X,'0',9X,'1')
      PRINT 908
  908 FORMAT(1H ,17X,'0',9X,'0',9X,'0',9X,'0',9X,'0',9X,'0',
     1 9X,'0',9X,'0',9X,'0',9X,'0',9X,'0')
      PRINT 910
  910 FORMAT(1H0,20X)
C
      IAD = (JMP-1)*IMP + 1
CMIC$ DO ALL VECTOR SHARED(KLP) PRIVATE(IQ2W6E)
      DO 89990 IQ2W6E=1,120
         KLP(IQ2W6E)=0
89990 CONTINUE
C
      DO 914 JJ= 1,JMP
CMIC$ DO ALL VECTOR SHARED(IMP, IAD, KPRT, KLP) PRIVATE(IQ2W6E)
      DO 90000 IQ2W6E=1,IMP
         KLP(IQ2W6E)=KPRT(IAD+IQ2W6E-1)
90000 CONTINUE
        J = JMP +1 - JJ
        PRINT 912,J,KLP
  912   FORMAT(1H ,2X,I4,2X,120I1)
C
        IAD = IAD - IMP
  914 CONTINUE
C
      ILOOK = ILOOK + 1
      IF( ILOOK .EQ. 3 ) GO TO 1000
C            ILOOK = 2,, PRINT OUT BITSEA
CMIC$ DO ALL VECTOR SHARED(IJP, NGKPRT, BITSEA, KPRT) PRIVATE(IQ2W6E)
      DO 90020 IQ2W6E=1,IJP
       IF ( BITSEA(IQ2W6E,NGKPRT) ) THEN
         KPRT(IQ2W6E)=1
       ELSE
         KPRT(IQ2W6E)=0
       END IF
90020 CONTINUE
      PRINT 916, NGKPRT
  916 FORMAT(1H1,40X,'BITSEA FOR GRID',I4)
C
      GO TO 905
C
C
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C
 1000 CONTINUE
C
      RETURN
      END
