      SUBROUTINE SOUNDING ( SPECS, INUSTA, IOUTUSND )
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    SOUNDING    TO OUTPUT SOUNDING INFORMATION
C   PRGMMR: J TUCCILLO       ORG: W/NMC4     DATE: 90-06-17
C
C ABSTRACT:    OUTPUTS SOUNDING INFORMATION
C   .
C PROGRAM HISTORY LOG:
C   90-06-17  J TUCCILLO
C   92-03-23  R WOBUS    COMBINE LW AND SW FLUXES, ADD OMEGA   
C   98-09-10  HANN-MING JUANG  MOFIDIED FOR Y2K
C
C USAGE:  CALL SOUNDING ( SPECS, INUSTA, IOUTUSND )
C   INPUT ARGUMENT LIST:
C     SPECS    - SPECS ARRAY
C     INUSTA   - UNIT NUMBER OF STATION LIST
C     IOUTUSND - UNIT NUMBER OF OUTPUT FILE
C
C   INPUT FILES:
C     INUSTA   - STATION LIST FILE
C
C   OUTPUT FILES:
C     IOUTUSND - OUTPUT FILE
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - LL2GR
C                  OUTSCALE
C     LIBRARY:
C       COMMON   - COMCONST
C                  COMBLANK
C                  COMDIAG
C
C REMARKS:
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES      MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----      ----------------------------------        ---------
C   .
C   .          ***  INPUT FROM UNIT NUMBER INUSTA   ***
C   .
C   VBL        ARRAY CONTAINING ALL FORECAST-TYPE        /COMVBLS/
C   .          VARIABLES FOR ALL GRIDS.
C   .
C   ITIME      FORECAST LENGTH IN SECS                   /COMCONST/
C   .
C   IMG        NUMBER OF X-POINTS ON THE GRIDS           /COMCONST/
C   .
C   JMG        NUMBER OF Y-POINTS ON THE GRIDS           /COMCONST/
C   .
C   IADDRG     STARTING ADDRESSES OF FIELDS IN VBL       /COMCONST/
C   .
C   LVLTOT     NUMBER OF 2-D SIZED ARRAYS IN VBL         /COMCONST/
C
C   SCR        SCRATCH SPACE                             /COMVBLS/
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   .
C   .          ***  OUTPUT TO UNIT NUMBER IOUTUSND  ***
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  14:51:20  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      LOGICAL L1S,L2S,L3S,L4S,L5S
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMDIAG/ CONTAINS QUANTITIES SAVED FOR
C          DIAGNOSTIC PURPOSES.
      COMMON /COMDIAG/  KADIAB( IKM, INGRDUSE ),
     1                  NPTSDHQ (2, INGRDUSE),
     2                  KKCLOUD2(2, INGRDUSE), NPTSBUOY(2, INGRDUSE),
     3                  NPTSWATR(2, INGRDUSE), NPTSCC  (2, INGRDUSE),
     4                  KKGSP2  (2, INGRDUSE),
     5                  KKGSE2  (2, INGRDUSE),
     6                  NPTSSAT (IKM, 2, INGRDUSE),
     7                  NPTSEVAP(IKM, 2, INGRDUSE),
     8                  NPTSGSP (2, INGRDUSE), NUMPROF,
     9                  PPTCC   (2, INGRDUSE), PPTGSP  (2, INGRDUSE),
     1                  ALATPR  (IMAXPROF),    ALONPR  (IMAXPROF),
     2                  DESCRP  (IMAXPROF)
C
      CHARACTER*24 DESCRP
C
C
      PARAMETER ( NUMPTMAX = 600,
     *            IACCMAX  = ( ILVLTOT - 3 ) )
C
      DIMENSION SPECS(*)
C
      DIMENSION ACCUM(IACCMAX),   ACCUMO(IACCMAX),
     *          ALATP(NUMPTMAX),  ALONP(NUMPTMAX),  ISTAP(NUMPTMAX),
     *          IN00H(NUMPTMAX),  IN00U(NUMPTMAX),  IN00V(NUMPTMAX),
     *          IN00M(NUMPTMAX),  
     *          NGRIDH(NUMPTMAX), NGRIDU(NUMPTMAX), NGRIDV(NUMPTMAX),
     *          NGRIDM(NUMPTMAX),
     *          CF00H(NUMPTMAX),  CF10H(NUMPTMAX),
     *          CF01H(NUMPTMAX),  CF11H(NUMPTMAX),
     *          CF00U(NUMPTMAX),  CF10U(NUMPTMAX),
     *          CF01U(NUMPTMAX),  CF11U(NUMPTMAX),
     *          CF00V(NUMPTMAX),  CF10V(NUMPTMAX),
     *          CF01V(NUMPTMAX),  CF11V(NUMPTMAX),
     *          CF00M(NUMPTMAX),  CF10M(NUMPTMAX),
     *          CF01M(NUMPTMAX),  CF11M(NUMPTMAX)
C
      CHARACTER*3  ID(NUMPTMAX)
      CHARACTER*3  IDRT
      CHARACTER*4  CPACK
      CHARACTER*26 NAME(NUMPTMAX)
      CHARACTER*26 NAMERT
C
      CHARACTER*1 NS,EW
C
      LOGICAL LFRST
C
C BEGIN INSERT FROM OUTOMEGA
C
C
C     COMMON BLOCK /COMOUT/ CONTAINS OUTPUT CODE PARAMETERS
C               AND ARRAYS.
C
      CHARACTER*20 DESCRIPT
C          DESCRIPTORS USED IN SR  OUTHORIZ
C
      COMMON /COMOUT/
C
C          THE FOLLOWING ARE STORED BY OUT2FILE FROM DATA CARDS.
C          (THE LAST 6 WILL BE OVERWRITTEN BY  OUTPUT  IF KGTYPE
C          IS 5 OR 26 (I.E. AN LFM GRID DEFINED IN TABLE 7 OF
C          OFFICE NOTE 84.))
C
     1     INUNIT, IOUTUNIT, IOUTGRIB,
     2     KGTYPE, IMOUT, JMOUT, DNPEQOUT, DLAMOUT, XIPOUT, YJPOUT,
C
C          THE FOLLOWING COME FROM  MAIN  READING THE DATA CARDS.
     2   LQTYPE(IMAXOUTV),   LSTYPE(IMAXOUTV),
     3   DESCRIPT(IMAXOUTV), LEVELS(ILMOUT,IMAXOUTV),  NOUTVBLS,
C
C          THE FOLLOWING ARE DERIVED BY   OUTPUT  .
     4       IJOUT, LMOUT, NFILLER, NS2, NS3NGM, NS3OUT,
     5       COSOUT,   SINOUT,    DXOUT,    ZSIGLYR(IKM),
C
C           ARRAYS  PLOUT  AND  HTFD  ARE SET BY DATA STATEMENTS IN
C           THE SR  OUTPUT  .  'PADDER' FILLS OUT TO FULL WORD BNDRY.
     6      PLOUT(ILMOUT),   HTFD( 6),  PADDER,
C
C          THE FOLLOWING ADDRESSES AND ADDRESS ARRAYS ARE SET UP
C          BY   OUTPREP  WHEN IT IS CALLED BY   OUTPUT  .
     7  J1(INGRDUSE),          J2(INGRDUSE),   JADDK2L(INGRDUSE,2),
     8  JADDFNGM(INGRDUSE), JHREC(INGRDUSE),   JHKAP(INGRDUSE),
     9  JSCR2(12),    JSCR3NGM(INGRDUSE,12),   JSCR3OUT(12),
     A  LENGD(INGRDUSE), LTYPE(ILMOUT,INGRDUSE), MB1, MB2, MINT,
     B   MSOUT1,  MSOUT2,  MZGNDOUT,  MNGM3,  MHOUT, MZFR, MZTRO,
     C      MSZGND(INGRDUSE), NGRIDATA(INGRDUSE),
C
C            NUMGDREQ, THE NUMBER OF NGM GRIDS NEEDED TO COVER THE
C            OUTPUT GRID, AND ZLOUT, ARE SET BY  OUTPREP  .
     D                NUMGDREQ,    ZLOUT(ILMOUT),
C
C          OUTPREP ALSO ASSIGNS THE FOLLOWING DESCRIPTORS TO BE
C          USED BY  OUTHORIZ  FOR HORIZONTAL INTERPOLATION.
     E    AHORD,BHORD,CHORD,DHORD, ILLD,IULD,  SCRHORD,  OUTHORD,
C
C
C          THE FOLLOWING ARRAY CONTAINS THE INTEGERS NEEDED TO
C          FORM THE LABEL THAT GOES WITH EACH OUTPUT ARRAY.
     F               LABEL84( 27 ),
C
C          THE FOLLOWING SYMBOLS REPRESENT TEMPORARY VALUES OF
C          INTEGERS TO GO INTO  LABEL84 WHEN THE OUTPUT ARRAY
C          HAS BEEN PREPARED FOR PACKING.
C
     G  LABQTYPE, LABSSUB1, LABTMARK,  S1VALUE,  S2VALUE,
     H  LABMLDIF, LABSSUB2, LABFSUB2, LABKGRID, LABNUMPT
C
C
      DIMENSION S(INSUMG), FNGM(INSUMG), IN(INSUMG)
C
      EQUIVALENCE ( SCR(1,1),S(1),FNGM(1), IN(1) )
C
C
C END INSERT FROM OUTOMEGA
C
      EQUIVALENCE ( IPACK, CPACK )
C
      DATA LFRST  / .TRUE. /,
     *     IUPRTR / 6 /
C
C***********************************************************************
C
C     IUPERR = 102
C
C***********************************************************************
C
      IF ( LFRST ) THEN
C
         WRITE ( IUPRTR , 2051)
C        WRITE ( IUPERR , 2051)
2051     FORMAT(1H1,'   ** BEGINNING SOUNDING OUTPUT PREPARATION **'/)
C
         NUMPT = 0
C
664      CONTINUE
         READ ( INUSTA, 2100, END=666)
     *          ISTAPRT, ALATPRT, NS, ALONPRT, EW,
     *          IDRT,NAMERT
2100     FORMAT (I5,1X,F5.2,A1,1X,F6.2,A1,1X,A3,1X,A26)
         NUMPT = NUMPT + 1
         IF ( NUMPT .GT. NUMPTMAX ) GOTO 665
         ISTAP(NUMPT) = ISTAPRT
         ALATP(NUMPT) = ALATPRT
         ALONP(NUMPT) = ALONPRT
         ID(NUMPT)    = IDRT
         NAME(NUMPT)  = NAMERT
         IF ( NS .EQ. 'S' ) ALATP(NUMPT) = - ALATP(NUMPT)
         IF ( EW .EQ. 'W' ) ALONP(NUMPT) = - ALONP(NUMPT)
         CALL LL2GR ( ALATP(NUMPT), ALONP(NUMPT), 0,
     *       DUM1,DUM2,IN00H(NUMPT),NGRIDH(NUMPT),
     *       CF00H(NUMPT),CF10H(NUMPT),CF01H(NUMPT),CF11H(NUMPT),IERRH)
         CALL LL2GR ( ALATP(NUMPT), ALONP(NUMPT), 1,
     *       DUM1,DUM2,IN00U(NUMPT),NGRIDU(NUMPT),
     *       CF00U(NUMPT),CF10U(NUMPT),CF01U(NUMPT),CF11U(NUMPT),IERRU)
         CALL LL2GR ( ALATP(NUMPT), ALONP(NUMPT), 2,
     *       DUM1,DUM2,IN00V(NUMPT),NGRIDV(NUMPT),
     *       CF00V(NUMPT),CF10V(NUMPT),CF01V(NUMPT),CF11V(NUMPT),IERRV)
         CALL LL2GR ( ALATP(NUMPT), ALONP(NUMPT), 3,
     *       DUM1,DUM2,IN00M(NUMPT),NGRIDM(NUMPT),
     *       CF00M(NUMPT),CF10M(NUMPT),CF01M(NUMPT),CF11M(NUMPT),IERRM)
         IF ( IERRH .NE. 0 .OR. IERRU .NE. 0 .OR. IERRV .NE. 0
     *                                       .OR. IERRM .NE. 0 ) THEN
            WRITE ( IUPRTR, 2300 ) IERRH, IERRU, IERRV, IERRM
2300        FORMAT(' LL2GR ERROR CODES ( H, U, V, M ) = ',2X,4(I5,2X))
            WRITE ( IUPRTR, 2310 ) ISTAP(NUMPT), ALATP(NUMPT),
     *            ALONP(NUMPT)
2310        FORMAT('     BAD STATION ID,LAT,LON=',2X,I5,2(F10.2,2X))
            NUMPT = NUMPT - 1
         END IF
         GOTO 664
665      CONTINUE
         WRITE ( IUPRTR, 2400 )
2400     FORMAT (' NUMPT IS GREATER THAN NUMPTMAX, NO MORE ROOM')
666      CONTINUE
         NUMPT = NUMPT 
         WRITE ( IUPRTR, 2500 ) NUMPT
2500     FORMAT (' THERE ARE ',1X,I5,1X,'STATIONS')
C
         WRITE ( IUPRTR , 2600 )
2600     FORMAT(' THE SOUNDING STATIONS ARE AS FOLLOWS :'/)
         WRITE ( IUPRTR , 2700 )
2700     FORMAT('/STATION ID  LATITUDE     LONGITUDE   GRID(H) ',
     *          'LL PT      CF00     CF10     CF01     CF11   ',
     *          'ID        NAME       ')
         WRITE ( IUPRTR , 2800 )
2800     FORMAT(' =============================================',
     *          '==============================================',
     *          '=====================')
C
         DO 1999 I = 1, NUMPT
         WRITE(IUPRTR, 2900) ISTAP(I),ALATP(I),ALONP(I), NGRIDH(I),
     *        IN00H(I), CF00H(I), CF10H(I), CF01H(I), CF11H(I),
     *        ID(I), NAME(I)
2900     FORMAT(1X,I5,4X,F10.2,4X,F10.2,4X,I3,4X,I5,4X,4(F7.2,2X),
     *          1X,A3,3X,A26)
1999     CONTINUE
C
         WRITE ( IUPRTR , 2050)
C        WRITE ( IUPERR , 2050)
2050     FORMAT('/    ** SOUNDING OUTPUT PREPARATION ENDED **'/)
C
         LFRST =.FALSE.
C
      END IF
C
C     WRITE (IUPERR,'('' BEGIN SOUNDING SCRATCH SETUP'')')
C
C     *** BRANCH TO HERE AFTER FIRST ENTRY ***
C
C SET UP SCRATCH SPACE FOR OMEGA CALCULATION
C USING SAME VARIABLE NAMES AS IN OUTPREP
C
C
      MS = 1
      MSIZE = KM * IJMAX
      DO 220 NJ=1,3
         DO 77059 NI=1,NGRDUSE
            JSCR3NGM(NI,NJ) = MS +MSIZE*(NGRDUSE*(NJ-1)+NI-1)
77059    CONTINUE
 220  CONTINUE
      MS = NGRDUSE * 3 * MSIZE + MS       
      DO 230 NI = 1, 3
         JSCR2(NI) = MS + IJMAX*(NI-1)
 230  CONTINUE
      MS = MS + 3 * IJMAX
      DO 240 N=1,NGRDUSE
         JHREC(NG) = MS
         MS = MS + IJMAX
 240  CONTINUE
      MNGM3 = MS
      MS = MS + KM * IJMAX
C
C     WRITE (IUPERR,'('' BEGIN SOUNDING GET U, V'')')
C
C BEGIN INSERT U,V CODE FOR OMEGA FROM OUTPUT
C
C--------------------------------------------------------
C
C          START WORK ON VELOCITY VARIABLES.  FIRST PUT
C          U ( AT HU PTS) AND V ( AT HV PTS ) FOR ALL NEEDED
C          NGM GRIDS INTO S(JSCR3NGM(NN,1)) AND S(JSCR3NGM(NN,2)).
C
      DO 370 NN=1,NGRDUSE
      NG=NN
      IM=IMG(NG)
      JM=JMG(NG)
      IJ=IM*JM
C          GET (1/H) ARRAYS TO FACTOR OUT H IN HU AND HV.
C          ADDRESS OF (1/H) AT H POINTS.
      IADHR=JHREC(NG)
C          1/H AT U PTS.  FIRST ROWS J=1,JM-1.
      LEN1=IJ-IM
      DO 89550 IQ2W6E=1,LEN1
         S(JSCR2(1)+IQ2W6E-1)=.5E0*(S(IADHR+IQ2W6E-1)+S(IADHR+IM+
     *   IQ2W6E-1))
89550 CONTINUE
C          FILL OUT TOP ROW WITH EXTRAPOLATED AVG OF (1/H).
      IAD1=JSCR2(1) + LEN1
      IAD2=IADHR + LEN1
      IAD3=IADHR + (JM-2)*IM
      DO 89560 IQ2W6E=1,IM
         S(IAD1+IQ2W6E-1)=1.5E0*S(IAD2+IQ2W6E-1)-.5E0*S(IAD3+IQ2W6E-1)
89560 CONTINUE
C          (1/H) AT V POINTS
      DO 89570 IQ2W6E=1,IJ
         S(JSCR2(2)+IQ2W6E-1)=.5E0*(S(IADHR+IQ2W6E-1)+S(IADHR+IQ2W6E))
89570 CONTINUE
C          MUST CORRECT THE I=IM POINTS.
      IADHR1=IADHR-1
      IAD1=JSCR2(2)-1
        DO 350 J=1,JM
        IADHR1=IADHR1+IM
        IAD1=IAD1+IM
        S(IAD1)=1.5E0*S(IADHR1) - .5E0*S(IADHR1-1)
  350   CONTINUE
C          CAN NOW CONVERT HU AND HV TO U AND V.
      IADHU=IADDRG(1,NG)-IJ
      IADHV=IADDRG(2,NG)-IJ
      IADU=JSCR3NGM(NN,1)-IJ
      IADV=JSCR3NGM(NN,2)-IJ
        DO 360 K=1,KM
        IADHU=IADHU+IJ
        IADHV=IADHV+IJ
        IADU=IADU+IJ
        IADV=IADV+IJ
      DO 89580 IQ2W6E=1,IJ
         S(IADU+IQ2W6E-1)=S(JSCR2(1)+IQ2W6E-1)*VBL(IADHU+IQ2W6E-1)
         S(IADV+IQ2W6E-1)=S(JSCR2(2)+IQ2W6E-1)*VBL(IADHV+IQ2W6E-1)
89580 CONTINUE
  360   CONTINUE
C
  370 CONTINUE
C
C     WRITE (IUPERR,'('' BEGIN SOUNDING OMEGA CALCULATION'')')
C
C-------------------------------------------------------
C
C
C BEGIN INSERT OMEGA CODE FROM OUTOMEGA
C
C  BEGIN OMEGA CALCULATION HERE
C
C          GRID SPACING FOR GRID A (NG=1)
      DXGDA=2.E0*RADIUS/( FLOAT(NH) + .5E0 )
C
      DO 100 NG=1,NGRDUSE
      IM=IMG(NG)
      JM=JMG(NG)
      IJ=IM*JM
C          GRID SPACING FOR THIS GRID
      DX=DXGDA
        DO 30 N=1,NGRDUSE
        IF(N .EQ. NG ) GO TO 35
        DX=.5E0 * DX
   30   CONTINUE
C
   35 CONTINUE
C
C
C          INITIAL ADDRESSES FOR HU,HV,AND H
      IADHU=IADDRG(1,NG)
      IADHV=IADDRG(2,NG)
      IADH=IADDRG(5,NG)
C          SCRATCH ADDRESSES
      I1=JSCR2(1)
      I2=JSCR2(2)
      I3=JSCR2(3)
C
C          PUT THE DIVERGENCE OF ( H * VELOCITY ) AT CENTER OF
C          INTO ARRAY S(MNGM3).
C
C          FIRST PUT (1/DX) TIMES 1/SCALE FACTOR AT HU AND HV
C          POINTS INTO ARRAYS S(I1) AND S(I2).
C
      CALL OUTSCALE( NG, 1, S(I1),S(I3) )
      C1=1.E0 / DX
CMIC$ DO ALL VECTOR SHARED(IJ, C1, I1, S) PRIVATE(IQ2W6E)
      DO 88890 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=C1/S(I1+IQ2W6E-1)
88890 CONTINUE
C
      CALL OUTSCALE( NG, 2, S(I2), S(I3) )
CMIC$ DO ALL VECTOR SHARED(IJ, C1, I2, S) PRIVATE(IQ2W6E)
      DO 88900 IQ2W6E=1,IJ
         S(I2+IQ2W6E-1)=C1/S(I2+IQ2W6E-1)
88900 CONTINUE
C
      IADU=IADHU-IJ
      IADV=IADHV-IJ
      IAD = MNGM3-IJ
        DO 40 K=1,KM
        IADU=IADU+IJ
        IADV=IADV+IJ
        IAD=IAD+IJ
CMIC$ DO ALL VECTOR IF (ABS(I1-I3).GE.IJ .OR. I1-I3.EQ.0) SHARED(IJ, I1
CMIC$1   , IADU, I3, S, VBL) PRIVATE(IQ2W6E)
      DO 88910 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=S(I1+IQ2W6E-1)*VBL(IADU+IQ2W6E-1)
88910 CONTINUE
CMIC$ DO ALL VECTOR IF ((ABS(I3+1-IAD).GE.IJ .OR. I3+1-IAD.EQ.0) .AND. (
CMIC$1   ABS(I3-IAD).GE.IJ .OR. I3-IAD.EQ.0)) SHARED(IJ, I3, IAD, S)
CMIC$2    PRIVATE(IQ2W6E)
      DO 88911 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(I3+IQ2W6E)-S(I3+IQ2W6E-1)
88911 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I2-I3).GE.IJ .OR. I2-I3.EQ.0) SHARED(IJ, I2
CMIC$1   , IADV, I3, S, VBL) PRIVATE(IQ2W6E)
      DO 88912 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=S(I2+IQ2W6E-1)*VBL(IADV+IQ2W6E-1)
88912 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IAD-IM-I3).GE.IJ .OR. IAD-IM-I3.EQ.0)
CMIC$1    SHARED(IJ, IAD, I3, IM, S) PRIVATE(IQ2W6E)
      DO 88913 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)+S(I3+IM+IQ2W6E-1)
88913 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IAD-I3).GE.IJ .OR. IAD-I3.EQ.0) SHARED(IJ, 
CMIC$1   IAD, I3, S) PRIVATE(IQ2W6E)
      DO 88914 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)-S(I3+IQ2W6E-1)
88914 CONTINUE
   40   CONTINUE
C          NEED SCALE FACTOR IN CENTER OF GRID SQUARE
C
      CALL OUTSCALE( NG, 4, S(I1), S(I3) )
C
C          SQUARE IT (IN S(I2) ) AND MULTIPLY THE S(MNGM3) ARRAY
C          WITH IT.
CMIC$ DO ALL VECTOR IF (ABS(I1-I2).GE.IJ .OR. I1-I2.EQ.0) SHARED(IJ, I1
CMIC$1   , I2, S) PRIVATE(IQ2W6E)
      DO 88960 IQ2W6E=1,IJ
         S(I2+IQ2W6E-1)=S(I1+IQ2W6E-1)*S(I1+IQ2W6E-1)
88960 CONTINUE
      IAD=MNGM3-IJ
        DO 50 K=1,KM
        IAD=IAD+IJ
CMIC$ DO ALL VECTOR IF (ABS(IAD-I2).GE.IJ .OR. IAD-I2.EQ.0) SHARED(IJ, 
CMIC$1   IAD, I2, S) PRIVATE(IQ2W6E)
      DO 88970 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)*S(I2+IQ2W6E-1)
88970 CONTINUE
   50   CONTINUE
C
C          STARTING AT THE TOP(KM) PUT OMEGA PRIME IN S(MNGM3).
      C1=-DELSIG(KM)
      IAD=MNGM3 + (KM-1)*IJ
CMIC$ DO ALL VECTOR SHARED(IJ, C1, IAD, S) PRIVATE(IQ2W6E)
      DO 88980 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=C1*S(IAD+IQ2W6E-1)
88980 CONTINUE
        DO 60 KK=2,KM
        K=-KK + KM + 1
        IAD=IAD-IJ
        C1=-DELSIG(K)
CMIC$ DO ALL VECTOR SHARED(IJ, IAD, C1, S) PRIVATE(IQ2W6E)
      DO 88990 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IJ+IQ2W6E-1)+C1*S(IAD+IQ2W6E-1)
88990 CONTINUE
   60   CONTINUE
C
C
C          AVERAGE OMEGA PRIME VERTICALLY TO MIDDLE OF LAYERS.
       IAD=MNGM3-IJ
        KMM1=KM-1
      IF (KMM1 .GT. 0) THEN
CMIC$    DO ALL IF (ABS(IJ).GE.KMM1*ABS(IJ) .OR. IJ.EQ.0) SHARED(KMM1, 
CMIC$1      IAD, IJ, S) PRIVATE(K, IQ2W6E)
         DO 70 K = 1, KMM1
            DO 77001 IQ2W6E = 1, IJ
               S(IAD+IQ2W6E-1+K*IJ) = .5E0*(S(IAD+IQ2W6E-1+K*IJ)+S(IAD+(
     1            K+1)*IJ+IQ2W6E-1))
77001       CONTINUE
   70    CONTINUE
         IAD = KMM1*IJ + IAD
      ENDIF
C          FINISH OFF THE TOP LAYER
      IAD=IAD+IJ
CMIC$ PARALLEL SHARED(IJ, IADH, IM, I3, VBL, S, IAD) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89030 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=.5E0*S(IAD+IQ2W6E-1)
89030 CONTINUE
C
C          CONVERT OMEGA PRIME TO OMEGA BY ADDING (1 - SIGMA)
C          TIMES ( VELOCITY DOT GRADIENT OF H ).
C
C          FIRST PUT SCALE FACTOR * DH/DX INTO S(I2)
CMIC$ DO PARALLEL VECTOR
      DO 89040 IQ2W6E=1,IJ
      S(I3+IQ2W6E-1)=.5E0*(VBL(IADH+IQ2W6E-1)+VBL(IADH+IM+IQ2W6E-1))
89040 CONTINUE
CMIC$ END PARALLEL
CMIC$ DO ALL VECTOR IF ((ABS(I3+1-I2).GE.IJ .OR. I3+1-I2.EQ.0) .AND. (
CMIC$1   ABS(I3-I2).GE.IJ .OR. I3-I2.EQ.0)) SHARED(IJ, I3, I2, S)
CMIC$2    PRIVATE(IQ2W6E)
      DO 89041 IQ2W6E=1,IJ
      S(I2+IQ2W6E-1)=S(I3+IQ2W6E)-S(I3+IQ2W6E-1)
89041 CONTINUE
      C1=1.E0/DX
CMIC$ DO ALL VECTOR IF (ABS(I2-I1).GE.IJ .OR. I2-I1.EQ.0) SHARED(IJ, C1
CMIC$1   , I2, I1, S) PRIVATE(IQ2W6E)
      DO 89060 IQ2W6E=1,IJ
         S(I2+IQ2W6E-1)=C1*S(I2+IQ2W6E-1)*S(I1+IQ2W6E-1)
89060 CONTINUE
C
C          THEN PUT SCALE FACTOR * DH/DY INTO S(I3)
CMIC$ DO ALL VECTOR SHARED(IJ, IADH, I3, VBL, S) PRIVATE(IQ2W6E)
      DO 89070 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=.5E0*(VBL(IADH+IQ2W6E-1)+VBL(IADH+IQ2W6E))
89070 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IM).GE.IJ .OR. IM.EQ.0) SHARED(IJ, I3, IM, S
CMIC$1   ) PRIVATE(IQ2W6E)
      DO 89071 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=S(I3+IM+IQ2W6E-1)-S(I3+IQ2W6E-1)
89071 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I3-I1).GE.IJ .OR. I3-I1.EQ.0) SHARED(IJ, C1
CMIC$1   , I3, I1, S) PRIVATE(IQ2W6E)
      DO 89072 IQ2W6E=1,IJ
         S(I3+IQ2W6E-1)=C1*S(I3+IQ2W6E-1)*S(I1+IQ2W6E-1)
89072 CONTINUE
C
C          USE U ( AT HU POINTS, IN S(JSCR3NGM(NG,1) ) ) AND
C          V ( AT HV POINTS, IN S(JSCR3NGM(NG,2) ) ) FOR THE
C          ADVECTING VELOCITIES.
C
      IADU=JSCR3NGM(NG,1)-IJ
      IADV=JSCR3NGM(NG,2)-IJ
      IAD=MNGM3-IJ
        DO 80 K=1,KM
        IADU=IADU+IJ
        IADV=IADV+IJ
        IAD=IAD + IJ
C          THE 1-SIGMA FACTOR TIMES 0.5
        C1=PRESS(K) * .5E0
C          THE MEAN U TIMES THE DH/DX TERM
CMIC$ DO ALL VECTOR IF ((ABS(IADU-1-I1).GE.IJ .OR. IADU-1-I1.EQ.0)
CMIC$1    .AND. (ABS(IADU-I1).GE.IJ .OR. IADU-I1.EQ.0)) SHARED(IJ, C1, 
CMIC$2   IADU, I1, S) PRIVATE(IQ2W6E)
      DO 89100 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=C1*(S(IADU+IQ2W6E-2)+S(IADU+IQ2W6E-1))
89100 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I2-I1).GE.IJ .OR. I2-I1.EQ.0) SHARED(IJ, I2
CMIC$1   , I1, S) PRIVATE(IQ2W6E)
      DO 89101 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=S(I2+IQ2W6E-1)*S(I1+IQ2W6E-1)
89101 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IAD-I1).GE.IJ .OR. IAD-I1.EQ.0) SHARED(IJ, 
CMIC$1   IAD, I1, S) PRIVATE(IQ2W6E)
      DO 89102 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)+S(I1+IQ2W6E-1)
89102 CONTINUE
C          THE MEAN V TIMES THE DH/DY TERM
CMIC$ DO ALL VECTOR IF ((ABS(IADV-I1).GE.IJ .OR. IADV-I1.EQ.0) .AND. (
CMIC$1   ABS(IADV+IM-I1).GE.IJ .OR. IADV+IM-I1.EQ.0)) SHARED(IJ, C1, 
CMIC$2   IADV, IM, I1, S) PRIVATE(IQ2W6E)
      DO 89130 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=C1*(S(IADV+IQ2W6E-1)+S(IADV+IM+IQ2W6E-1))
89130 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(I1-I3).GE.IJ .OR. I1-I3.EQ.0) SHARED(IJ, I1
CMIC$1   , I3, S) PRIVATE(IQ2W6E)
      DO 89131 IQ2W6E=1,IJ
         S(I1+IQ2W6E-1)=S(I1+IQ2W6E-1)*S(I3+IQ2W6E-1)
89131 CONTINUE
CMIC$ DO ALL VECTOR IF (ABS(IAD-I1).GE.IJ .OR. IAD-I1.EQ.0) SHARED(IJ, 
CMIC$1   IAD, I1, S) PRIVATE(IQ2W6E)
      DO 89132 IQ2W6E=1,IJ
         S(IAD+IQ2W6E-1)=S(IAD+IQ2W6E-1)+S(I1+IQ2W6E-1)
89132 CONTINUE
   80   CONTINUE
C
C          CONVERT H TO MB
C
      IAD1=MNGM3-IJ
      IAD2=JSCR3NGM(NG,3)-IJ
        DO 90 K=1,KM
        IAD1=IAD1+IJ
        IAD2=IAD2+IJ
        C1=1000.E0
CMIC$ DO ALL VECTOR IF (ABS(IAD2-IAD1).GE.IJ .OR.
CMIC$1   IAD2-IAD1.EQ.0) SHARED(IJ, C1, I1, 
CMIC$2   IM, IAD1, IAD2, S) PRIVATE(IQ2W6E)
      DO 89170 IQ2W6E=1,IJ
         S(IAD2+IQ2W6E-1)=C1*S(IAD1+IQ2W6E-1)
89170 CONTINUE
   90 CONTINUE
C
C          END OF THE NG LOOP,,GO TO NEXT GRID
  100 CONTINUE
C
C END INSERT OMEGA CODE FROM OUTOMEGA
C
C     WRITE (IUPERR,'('' BEGIN SOUNDING COLLECT AND WRITE'')')
C
      IF ( NUMPT .EQ. 0 ) RETURN
C
      IYR  = NINT(SPECS(5))
      IMN  = NINT(SPECS(4))
      IDY  = NINT(SPECS(3))
      IHR  = NINT(SPECS(2))
C
CHMHJ CALL W3FS11( CPACK, IYR, IMN, IDY, IHR, 0 )
      CALL W3YMDH4( CPACK, IYR, IMN, IDY, IHR, 0 )
C
      ISEC = ITIME
C
      DO 9000 ICNT = 1, NUMPT
C
         ISTA = ISTAP(ICNT)
         ALAT = ALATP(ICNT)
         ALON = ALONP(ICNT)
C
         NGH  = NGRIDH(ICNT)
         NGU  = NGRIDU(ICNT)
         NGV  = NGRIDV(ICNT)
         NGM  = NGRIDM(ICNT)
C
         IMH = IMG(NGH)
         IMU = IMG(NGU)
         IMV = IMG(NGV)
         IMM = IMG(NGM)
C
         JMH = JMG(NGH)
         JMU = JMG(NGU)
         JMV = JMG(NGV)
         JMM = JMG(NGM)
C
         IJH = IMH*JMH
         IJU = IMU*JMU
         IJV = IMV*JMV
         IJM = IMM*JMM
C
         C00H = CF00H(ICNT)
         C10H = CF10H(ICNT)
         C01H = CF01H(ICNT)
         C11H = CF11H(ICNT)
C
         C00U = CF00U(ICNT)
         C10U = CF10U(ICNT)
         C01U = CF01U(ICNT)
         C11U = CF11U(ICNT)
C
         C00V = CF00V(ICNT)
         C10V = CF10V(ICNT)
         C01V = CF01V(ICNT)
         C11V = CF11V(ICNT)
C
         C00M = CF00M(ICNT)
         C10M = CF10M(ICNT)
         C01M = CF01M(ICNT)
         C11M = CF11M(ICNT)
C
         I00H = IN00H(ICNT)
         I10H = I00H + 1
         I01H = I00H + IMH
         I11H = I00H + IMH + 1
C
         I00U = IN00U(ICNT)
         I10U = I00U + 1
         I01U = I00U + IMU
         I11U = I00U + IMU + 1
C
         I00V = IN00V(ICNT)
         I10V = I00V + 1
         I01V = I00V + IMV
         I11V = I00V + IMV + 1
C
         I00M = IN00M(ICNT)
         I10M = I00M + 1
         I01M = I00M + IMM
         I11M = I00M + IMM + 1
C
         MADH = IADDRG(1,NGH) - IJH - 1
         MADU = IADDRG(1,NGU) - IJU - 1
         MADV = IADDRG(1,NGV) - IJV - 1
         MADS = IADDRG(1,NGH) - IJH - 1
         MADL = IADDRG(1,NGH) - IJH - 1 + IJH * (KM*2 + 22)
         MADO = JSCR3NGM(NGM,3) - IJM - 1 - IJM * (KM*6 + 31)
         IACC = 0
C
CMIC$ DO ALL VECTOR SHARED(IACC, MADH, IJH, MADU, IJU, MADV, IJV, KM, 
CMIC$1   MADS, MADL, MADO, IJM,
CMIC$2   I00M, C00M, I10M, C10M, I01M, C01M, I11M, C11M, S,
CMIC$3   I00U, C00U, I10U, C10U, I01U, C01U, I11U, C11U, I00V, C00V, 
CMIC$4   I10V, C10V, I01V, C01V, I11V, C11V, I00H, C00H, I10H, C10H, 
CMIC$5   I01H, C01H, I11H, C11H, VBL, ACCUM) PRIVATE(IFLD, L1S, L2S,
CMIC$6   L3S, L4S, L5S)
      DO 400 IFLD = 1, 146
         L1S = .FALSE.
         L2S = .FALSE.
         L3S = .FALSE.
         L4S = .FALSE.
         L5S = .FALSE.
         IF (IFLD .LE. KM) THEN
            ACCUM(IACC+IFLD) = VBL(MADU+I00U+IFLD*IJU)*C00U + VBL(MADU+
     1         I10U+IFLD*IJU)*C10U + VBL(MADU+I01U+IFLD*IJU)*C01U + VBL(
     2         MADU+I11U+IFLD*IJU)*C11U
         ELSE
            L3S = IFLD.GT.KM .AND. IFLD.LE.2*KM
            L4S = IFLD.GT.4*KM+9 .AND. IFLD.LE.5*KM+9
            L5S = IFLD.GT.6*KM+31 .AND. IFLD.LE.7*KM+31
            L2S = .NOT.L3S .AND. .NOT.L4S .AND. .NOT.L5S
         ENDIF
         IF (L3S) ACCUM(IACC+IFLD) = VBL(MADV+I00V+IFLD*IJV)*C00V + VBL(
     1      MADV+I10V+IFLD*IJV)*C10V + VBL(MADV+I01V+IFLD*IJV)*C01V + 
     2      VBL(MADV+I11V+IFLD*IJV)*C11V
         IF (L2S) L1S = IFLD .GT. 2*KM
         IF (L1S) ACCUM(IACC+IFLD) = VBL(MADH+I00H+IFLD*IJH)*C00H + VBL(
     1      MADH+I10H+IFLD*IJH)*C10H + VBL(MADH+I01H+IFLD*IJH)*C01H + 
     2      VBL(MADH+I11H+IFLD*IJH)*C11H
         IF (L4S) ACCUM(IACC+IFLD) = 
     1       C00H * (VBL(MADL+I00H+IFLD*IJH)+VBL(MADS+I00H+IFLD*IJH))+
     2       C10H * (VBL(MADL+I10H+IFLD*IJH)+VBL(MADS+I10H+IFLD*IJH))+
     3       C01H * (VBL(MADL+I01H+IFLD*IJH)+VBL(MADS+I01H+IFLD*IJH))+
     4       C11H * (VBL(MADL+I11H+IFLD*IJH)+VBL(MADS+I11H+IFLD*IJH))
         IF (L5S) ACCUM(IACC+IFLD) = S(MADO+I00M+IFLD*IJM)*C00M + S(
     1      MADO+I10M+IFLD*IJM)*C10M + S(MADO+I01M+IFLD*IJM)*C01M + 
     2      S(MADO+I11M+IFLD*IJM)*C11M
C
  400 CONTINUE
C
      WRITE(IOUTUSND) CPACK,ISEC,ISTA,ALATP(ICNT),ALONP(ICNT),ACCUM
C
9000  CONTINUE
C
C     WRITE (IUPERR,'('' END SOUNDING WRITE'')') 
C
      RETURN
      END
