      SUBROUTINE SWRADIAT(DTC3,NOZ,S0,ALS,COSZ,PL20,DPL,TL,QL,O3L,CLD,
     *                    CLU,SWINC,DSWCLR,DSWTOP,SSCLR,SS,ASL)
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    SWRADIAT    PERFORMS SHORTWAVE RADIATION COMPUTATIONS
C   PRGMMR: J TUCCILLO       ORG: W/NMC4     DATE: 90-06-17
C
C ABSTRACT: PERFORMS SHORTWAVE RADIATION COMPUTATIONS
C   .       ( GLA SHORTWAVE CODE FROM DAVIES )
C   .
C   COMPUTES ATMOSPHERIC TEMPERATURE TENDENCIES FROM
C   SHORTWAVE RADIATION AND THE SHORTWAVE RADIATIVE FLUX
C   AT THE SURFACE OF THE EARTH FOR THE SURFACE ENERGY
C   BUDGET.
C   .
C PROGRAM HISTORY LOG:
C   90-06-17  J TUCCILLO
C
C USAGE:  CALL SWRADIAT(DTC3,NOZ,S0,ALS,COSZ,PL20,DPL,TL,QL,O3L,CLD,
C                       CLU,SWINC,DSWCLR,DSWTOP,SSCLR,SS,ASL)
C   INPUT ARGUMENT LIST:
C     DTC3     -  TIMESTEP IN SECS ( 1 IS USED )
C     NOZ      -  LOGICAL FOR WHETHER TO DO OZONE
C                 ( TRUE FOR NO OZONE CALCULATIONS )
C     S0       -  SOLAR CONSTANT ( WATTS / M**2 )
C     ALS      -  SURFACE ALBEDO ( 0 - 1 )
C     COSZ     -  COSINE OF THE ZENITH ANGLE
C     PL20     -  PRESSURE OF INTERFACES ( MBS )
C     DPL      -  PRESSURE DEPTH OF LAYERS ( MBS )
C     TL       -  TEMPERATURE OF LAYERS ( DEGS K )
C     QL       -  SPECIFIC HUMIDITY OF LAYERS ( GRMS/GRM )
C     O3L      -  OZONE OF LAYERS ( MIXING RATIO )
C     CLD      -  RANDOM OVERLAP CLOUD AMOUNTS ( 0 - 1 )
C     CLU      -  MAXIMUM OVERLAP CLOUD AMOUNTS ( 0 - 1 )
C
C   OUTPUT ARGUMENT LIST:
C     SWINC    -  DIAGNOSTIC QUANTITY
C     DSWCLR   -  DIAGNOSTIC QUANTITY
C     DSWTOP   -  DIAGNOSTIC QUANTITY
C     SSCLR    -  DIAGNOSTIC QUANTITY
C     SS       -  SHORTWAVE FLUX AT SURFACE OF THE EARTH
C                 ( WATTS / M**2 )
C     ASL      -  ATMOSPHERIC TEMPERATURE TENDENCIES FROM
C                 SHORTWAVE RADIATION ( DEGS K / DTC3 )
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - SWSET
C                  SWCLEAR
C                  SWCLOUDY
C     LIBRARY:
C       COMMON   - BLANK COMMON
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C
      PARAMETER (NIM= IIJRAD, NJM=46, NLM= IKM, NLS=02)
      PARAMETER (NNQFDS=5, NOFDS=2, NQIFDS=5, NOIFDS=8
     *,      NNQP3=21, NNQP2=59, N2DFDS=29, NEQO3O=01)
      PARAMETER (NIMP1=NIM+1,NIMP2=NIM+2,NIMP3=NIM+3,NIMD2=NIM/2+1/NIM
     *,     NLMM2=NLM-2, NLSP1=NLS+1, LMM1T2=(NLM-1)*2
     *,     IMD2P1=NIM/2+1, NJMM2=NJM-2, NLMP1=NLM+1, NLMM1=NLM-1
     *,     N1=NLM*NQIFDS+NOIFDS
     *,     N2=NLM*NNQFDS+NOFDS, N3=NIMP2*N2
     *,     NIMT2=NIM*2,N6=NIMP2*N1,NILPT=NIM*NLM
     *,     NNQPFD = NNQP3 + (NNQP2-1)/NLM + 1
     *,     NN5= NNQP3+ (NNQP2+(N2DFDS*NIM-1)/NIMP2)/NLM + 3
     *,     NN6 = NN5*NLM,NN1 = N1 - 1
     *,     N5= NIMP2*NN6, NTDSG =NLM-NLSP1
     *,     NNBITX=NIM*NLM
     *,     NPG=(NN1*NIMP2*NJMM2-1)/131072 + 1
     *,     N55=N5-2*NLM*NIMP2
     *,     NTL=(N55*NJMM2-1)/131072 + 1)
C
C
      PARAMETER (NNP=NLMP1+1,IMLMP1=NIM*NLMP1,IMNNP=NIM*NNP
     *,          ILP1=NIM*NLMP1)
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:01:30  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
      DIMENSION PL20(NIM,NLMP1),TL(NIM,NLM),QL(NIM,NLM),O3L(NIM,NLM)
     *,    CLD(NIM,NLM),CLU(NIM,NLM),DPL(NIM,NLM),SWINC(NIM)
     *,    DSWCLR(NIM),DSWTOP(NIM),SSCLR(NIM),SS(NIM),ASL(NIM,NLM)
     *,    ALS(NIM),COSZ(NIM)
C
      LOGICAL BITX(ILP1), BITC(IMNNP), BITD(IMNNP)
C
      COMMON  IM,NP,NPP1,LMP1,LS1,LS,NSOL,NSOLP1,NSLMP1,NSOLNP,DOOZ
     *,       SQRT3,GG,GGP,GGSQ,NCLD,NCLDP1,NCLMP1,NCLDNP,RCN1
     *,       ATHRD,TTHRD,RCN2
     *,       PU(IMNNP),TA(IMLMP1),WA(IMLMP1),OA(IMLMP1),E0(IMLMP1)
     *,       DP(IMLMP1),DPC(IMLMP1),W(IMNNP),DN(IMNNP),UP(IMNNP)
     *,       AG(NIM),RSURF(NIM),AGCD(NIM),RSRCD(NIM),VM(IMNNP)
     *,       SCOSZ(NIM),CMU(NIM),COSMAG(NIM),CSMCLD(NIM),SCZCD(NIM)
     *,       CMUC(NIM),SCOSC(NIM),CSS(IMLMP1),CCU(IMLMP1),VP(IMNNP)
     *,       SL(NIM),ACLR(IMLMP1),DSCLR(NIM),SC(NIM),ACLD(ILP1)
     *,       TAUC(IMLMP1),TAUT(NIM),RCO(NIM),RCG(NIM),CM(IMNNP)
     *,       OZALE(IMNNP),OZCD(IMNNP),RLO(NIM),RLG(NIM),DL(IMNNP)
     *,       SWIL(IMLMP1),SWALE(IMNNP),SWILC(IMLMP1),DEN(IMLMP1)
     *,       F2(IMLMP1),CR(IMNNP),E2(IMLMP1)
     *,       U1(IMLMP1),AK(IMLMP1),DA(IMLMP1),DB(IMLMP1)
     *,       ALF1(IMLMP1),ALF2(IMLMP1)
     *,       UL(IMNNP)
     *,       SOL(IMNNP),DSCLD(NIM),BITX,BITC,BITD
C
      LOGICAL FIRST, NOZ, DOOZ
C
      DATA FAC /8.441874377E0/, DAY /86400.0E0/, FIRST /.TRUE./
C
C
      IF (.NOT. FIRST) GOTO 5
C
      DOOZ   = (.NOT. NOZ)
      LM     = NLM
      IM     = NIM
      IMP2   = NIMP2
      NP     = NNP
      NPP1   = NP+1
      LMP1   = NLMP1
      LS1    = NLS+1
      LS     = NLS
      IMLM   = NNBITX
      ILTROP = NIM * (NLM - NLS)
      FAC    = 8.441874377E0 * DTC3 / DAY
      SQRT3  = SQRT(3.0E0)
      GG     = 0.85E0
      GGSQ   = GG  * GG
      GGP    = GG  / (1.0E0 + GG) * 0.75E0
      RCN1   = 1.0E0 / 6.55E0
      RCN2   = 1.0E0 / 4.354E0
      ATHRD  = 1.0E0 / 3.0E0
      TTHRD  = 2.0E0 / 3.0E0
C
    5 CONTINUE
C
C
C     SET BITS FOR DAYTIME GRID POINTS
C
CMIC$ DO ALL VECTOR SHARED(IM, COSZ, BITX) PRIVATE(IQ2W6E)
      DO 88890 IQ2W6E=1,IM
         BITX(IQ2W6E)=COSZ(IQ2W6E).GE.0.01E0
88890 CONTINUE
      NSOL = 0
      DO 1001 I = 1, IM
         IF ( BITX(I) ) NSOL= NSOL + 1
1001  CONTINUE
C
      IF (NSOL .EQ. 0) THEN
CMIC$ PARALLEL SHARED(IMLM, ASL, IM, SS, SWINC, SSCLR, DSWTOP, DSWCLR)
CMIC$1    PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 88900 IQ2W6E=1,IM
         SS(IQ2W6E)=0.0E0
         SWINC(IQ2W6E)=0.0E0
         SSCLR(IQ2W6E)=0.0E0
         DSWTOP(IQ2W6E)=0.0E0
         DSWCLR(IQ2W6E)=0.0E0
88900 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 88950 IQ2W6E=1,IMLM
         ASL(IQ2W6E,1)=0.0E0
88950 CONTINUE
CMIC$ END PARALLEL
         RETURN
      END IF
C
      NSOLP1     = NSOL   + 1
      NST2P1     = NSOL   + NSOLP1
      NSLMP1     = NSOL   * LMP1
      NSOLLM     = NSOL   * LM
      NSOLNP     = NSOL   * NP
      NZERCD     = NSOL   * LS1
      NLIMWA     = NSOL   * LS
      NRSTWA     = NSLMP1 - NLIMWA
      NWA1       = NLIMWA + 1
C
CMIC$ PARALLEL SHARED(NSOL, PU, LM, IM, BITX) PRIVATE(IQ2W6E, L, L1)
CMIC$ DO PARALLEL
      DO 10 L=1,LM
      L1 = L * IM + 1
      DO 88960 IQ2W6E=1,IM
         BITX(L1+IQ2W6E-1)=BITX(IQ2W6E)
88960 CONTINUE
   10 CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 88970 IQ2W6E=1,NSOL
         PU(IQ2W6E)=0.0E0
88970 CONTINUE
CMIC$ END PARALLEL
      IN = 1
CFPP$ NOCONCUR L
      DO 1003 I = 1, ILP1
         IF ( BITX(I) ) THEN
            PU(IN+NSOLP1-1) = PL20(I,1)
            IN = IN + 1
         END IF
1003  CONTINUE
      IN = 1
CFPP$ NOCONCUR L
      DO 1004 I = 1, IMLM
         IF ( BITX(I) ) THEN
            DP (IN+NSOLP1-1) = DPL(I,1)
            TA (IN+NSOLP1-1) = TL(I,1)
            WA (IN+NSOLP1-1) = QL(I,1)
            CSS(IN+NSOLP1-1) = CLD(I,1)
            CCU(IN+NSOLP1-1) = CLU(I,1)
            IN = IN + 1
         END IF
1004  CONTINUE
      IF (DOOZ) THEN
        IN= 1
CFPP$ NOCONCUR L
        DO 1005 I = 1, IMLM
           IF ( BITX(I) ) THEN
              OA(IN+NSOLP1-1) = O3L(I,1)
              IN = IN + 1
           END IF
1005    CONTINUE
CMIC$ PARALLEL SHARED(NSLMP1, OA, NSOL, NSOLP1) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 88980 IQ2W6E=1,NSOL
         OA(IQ2W6E)=OA(NSOLP1+IQ2W6E-1)
88980 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 88990 IQ2W6E=1,NSLMP1
         OA(IQ2W6E) = AMAX1(OA(IQ2W6E), 1.0E-10)
88990 CONTINUE
CMIC$ END PARALLEL
      END IF
C
      IN = 1
CFPP$ NOCONCUR L
      DO 8001 I = 1, IM
         IF ( BITX(I) ) THEN
            AG(IN) = ALS(I)
            CMU(IN) = COSZ(I)
            IN = IN + 1
         END IF
8001  CONTINUE
CMIC$ PARALLEL SHARED(NSOL, S0, CMU, COSMAG, SCOSZ, NRSTWA, NWA1, WA, 
CMIC$1   NLIMWA, NZERCD, CSS, CCU, NSLMP1, DP, DPC, NSOLP1, PU, TA)
CMIC$2    PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89000 IQ2W6E=1,NSOL
         DP(IQ2W6E)=PU(NSOLP1+IQ2W6E-1)
         TA(IQ2W6E)=TA(NSOLP1+IQ2W6E-1)
         WA(IQ2W6E)=WA(NSOLP1+IQ2W6E-1)
89000 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89030 IQ2W6E=1,NSLMP1
         DPC(IQ2W6E)=DP(IQ2W6E)
89030 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89040 IQ2W6E=1,NZERCD
         CSS(IQ2W6E)=0.0E0
         CCU(IQ2W6E)=0.0E0
89040 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89060 IQ2W6E=1,NLIMWA
         WA(IQ2W6E)=3.0E-6
89060 CONTINUE
C
CMIC$ DO PARALLEL VECTOR
      DO 89070 IQ2W6E=1,NRSTWA
         WA(NWA1+IQ2W6E-1) = AMAX1(WA(NWA1+IQ2W6E-1), 1.0E-23)
89070 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 89080 IQ2W6E=1,NSOL
         COSMAG(IQ2W6E)=35.0E0/
     *                  SQRT(1224.0E0*CMU(IQ2W6E)*CMU(IQ2W6E)+1.0E0)
         SCOSZ(IQ2W6E)=S0*CMU(IQ2W6E)
89080 CONTINUE
CMIC$ END PARALLEL
C
      IN = 1
CFPP$ NOCONCUR L
      DO 9001 I = 1, IM
         IF ( BITX(I) ) THEN
            SWINC(I) = SCOSZ(IN)
            IN = IN + 1
         ELSE
            SWINC(I) = 0.E0
         END IF
9001  CONTINUE
C
      CALL SWSET
C
      IN = 1
CFPP$ NOCONCUR L
      DO 9002 I = 1, IM
          IF ( BITX(I) ) THEN
             SSCLR(I) = SL(IN)
             DSWCLR(I) = DSCLR(IN)
             IN = IN + 1
          ELSE
             SSCLR(I) = 0.0E0
             DSWCLR(I) = 0.0E0
          END IF
9002  CONTINUE
C
      IF (NCLD .EQ. 0) GOTO 1000
C
CMIC$ PARALLEL SHARED(NSOL, BITD, SL, SC, DSCLR, DSCLD, NSLMP1, ACLR, 
CMIC$1   ACLD) PRIVATE(I, IQ2W6E)
C
CMIC$ DO PARALLEL VECTOR
      DO 89120 IQ2W6E = 1, NSLMP1
         BITD(IQ2W6E) = .NOT.BITD(IQ2W6E)
         IF (BITD(IQ2W6E)) ACLD(IQ2W6E) = ACLR(IQ2W6E)
89120 CONTINUE
CMIC$ DO PARALLEL VECTOR
      DO 5022 I = 1, NSOL
         IF ( BITD(I) ) THEN
            SC(I) = SL(I)
            DSCLD(I) = DSCLR(I)
         END IF
5022  CONTINUE
CMIC$ END PARALLEL
C
1000  CONTINUE
      IN = 1
CFPP$ NOCONCUR L
      DO 5023 I = 1, IM
         IF ( BITX(I) ) THEN
            SS(I) = SC(IN)
            DSWTOP(I) = DSCLD(IN)
            IN = IN + 1
         ELSE
            SS(I) = 0.0E0
            DSWTOP(I) = 0.0E0
         END IF
5023  CONTINUE
      IN = 1
CFPP$ NOCONCUR L
      DO 5024 I = 1, NNBITX
         IF ( BITX(I) ) THEN
            ASL(I,1) = ACLD(IN+NSOLP1-1)
            IN = IN + 1
         ELSE
            ASL(I,1) = 0.0E0
         END IF
5024  CONTINUE
C
CMIC$ DO ALL VECTOR SHARED(FAC, ASL, DPL) PRIVATE(IQ2W6E)
      DO 89130 IQ2W6E=1,NNBITX
         ASL(IQ2W6E,1)=ASL(IQ2W6E,1)*FAC/DPL(IQ2W6E,1)
89130 CONTINUE
C
      RETURN
      END
