      SUBROUTINE TOPRT25( Z, NG, ILEFT, JBOTT )
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    TOPRT25     ARRANGES A 25 X 25 PRINTOUT FROM ARRAY Z
C   PRGMMR: JIM TUCCILLO         ORG: W/NMC4     DATE: 90-06-18
C
C ABSTRACT: ARRANGES A 25 X 25 PRINTOUT FROM ARRAY Z
C   .       BEGINNING WITH PT (I,J0 = (ILEFT,JBOTT) ON GRID NG
C
C PROGRAM HISTORY LOG:
C   90-06-18  JIM TUCCILLO
C
C USAGE:    CALL TOPRT25 ( Z, NG, ILEFT, JBOTT )
C   INPUT ARGUMENT LIST:
C     Z        - INPUT ARRAY FROM WHICH THE PRINTOUT IS GENERATED
C     NG       - NGM GRID THAT ARRAY Z IS FROM
C     ILEFT    - INITIAL I VALUE ON NGM GRID NG TO BE PRINTED
C     JBOTT    - INITIAL J VALUE ON NGM GRID NG TO BE PRINTED
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - PRT25
C     LIBRARY:
C       COMMON   - COMCONST
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:04:51  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
      DIMENSION Z(1) , X(25,25)
C
      IM = IMG(NG)
      JM = JMG(NG)
C           INITIAL I VALUE ON NGM GRID NG
      IZ = ILEFT
C           INITIAL J VALUE ON NGM GRID NG
      JZ = JBOTT
C
C          COPY INTO ARRAY X(25,25)
CMIC$ DO ALL SHARED(JZ, IM, IZ, Z, X) PRIVATE(IAD, JX, IX)
      DO 50 JX = 1, 25
         DO 77001 IX = 1, 25
            X(IX,JX) = Z((JZ-2+JX)*IM+IZ+IX-1)
77001    CONTINUE
   50 CONTINUE
C
      CALL PRT25(X,25,25)
C
      RETURN
C
      END
