       SUBROUTINE W3FS11(IDATE,IYEAR,MONTH,IDAY,IHOUR,NN)
C$$$   SUBPROGRAM  DOCUMENTATION  BLOCK
C
C SUBPROGRAM: W3FS11         NMC DATE WORD PACKER OR UNPACKER
C   AUTHOR: JONES, R. E.     ORG: W342       DATE: 90-06-04
C
C ABSTRACT: OBTAINS THE COMPONENTS OF THE NMC DATE WORD (NMC OFFICE
C   NOTES 84 AND 85,, OR GIVEN ITS COMPONENTS, FORMS AN NMC TYPE DATE
C   WORD. W3FS11 IS THE SAME AS W3FS03 EXCEPT FOR THE ORDER OF THE
C   PARAMETERS.
C
C PROGRAM HISTORY LOG:
C   73-10-21  R.E.JONES
C   85-06-15  R.E.JONES   CONVERT TO FORTRAN 77
C   88-08-26  R.E.JONES   CLEAN UP SOURCE, PUT IN IF, THEN LOGIC
C   88-10-10  R.E.JONES   CHANGES FOR MICROSOFT 4.10 FORTRAN
C   90-06-11  R.E.JONES   CHANGES FOR SUN FORTRAN 1.3
C   91-03-29  R.E.JONES   CONVERT TO SiliconGraphics FORTRAN
C   93-03-29  R.E.JONES   ADD SAVE STATEMENT
C
C USAGE: CALL W3FS11 (IDATE, IYEAR, MONTH, IDAY, IHOUR, NN)
C
C   INPUT VARIABLES:
C     NAMES  INTERFACE DESCRIPTION OF VARIABLES AND TYPES
C     ------ --------- -----------------------------------------------
C     IDATE  ARG LIST  INTEGER*4 DATE WORD
C                      THIS SUBROUTINE USES IT AS CHARACTER*1  SIZE 4
C     IHOUR  ARG LIST  HOUR
C     IYEAR  ARG LIST  YEAR (2 DIGITS)
C     MONTH  ARG LIST  MONTH
C     IDAY   ARG LIST  DAY
C     NN     ARG LIST  CODE:
C                      = 0 PACK IHOUR, IYEAR, MONTH, IDAY, INTO IDATE
C                     .NE. 0 UNPACK IDATE INTO IHOUR, IYEAR, MONTH, IDAY
C
C   OUTPUT VARIABLES:
C     NAMES  INTERFACE DESCRIPTION OF VARIABLES AND TYPES
C     ------ --------- -----------------------------------------------
C     IDATE  ARG LIST  NMC DATE WORD (7TH WORD OF DATA OR 3RD WORD OF
C                      THE ID TABLE OF A BINARY FILE).
C     IHOUR  ARG LIST  HOUR
C     IYEAR  ARG LIST  YEAR (2 DIGITS)
C     MONTH  ARG LIST  MONTH
C     IDAY   ARG LIST  DAY
C
C   SUBPROGRAMS CALLED:
C     NAMES                                                   LIBRARY
C     ------------------------------------------------------- --------
C     NONE                                                    UNIQUE
C     ICHAR  CHAR                                             SYSTEM
C
C ATTRIBUTES:
C   LANGUAGE: SiliconGraphics 3.5 FORTRAN 77
C   MACHINE:  SiliconGraphics IRIS-4D/25, 35, INDIGO
C
C$$$
C
      CHARACTER*1  IDATE(4)
C
      SAVE
C
      IF (NN.NE.0) THEN
C
        IYEAR  = MOVA2I(IDATE(1))
        MONTH  = MOVA2I(IDATE(2))
        IDAY   = MOVA2I(IDATE(3))
        IHOUR  = MOVA2I(IDATE(4))
C
      ELSE
C
        IDATE(1) = CHAR(IYEAR)
        IDATE(2) = CHAR(MONTH)
        IDATE(3) = CHAR(IDAY)
        IDATE(4) = CHAR(IHOUR)
C
      ENDIF
C
      RETURN
      END
