      SUBROUTINE ZONEDIAG
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    ZONEDIAG    PRINTS ZONAL AVERAGES
C   PRGMMR: J TUCCILLO       ORG: W/NMC4     DATE: 90-05-19
C
C ABSTRACT: PRINTS ZONAL AVERAGES OF TEMPERATURES,
C   .       ZONAL AND MERIDIONAL VELOCITY COMPONENTS,
C   .       AND PLANETARY ALBEDO
C   .
C   OUTPUT VARIABLES ARE AVERAGED WITHIN LATITUDE
C   INTERVALS AND THEN PRINTED.
C   .
C
C PROGRAM HISTORY LOG:
C   90-05-19 J TUCCILLO
C
C USAGE:  CALL ZONEDIAG
C   OUTPUT FILES:
C     FT06F001 - FOR PRINTOUT
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - P2KAP
C                  VAPTAB
C     LIBRARY:
C       COMMON   - COMCONST
C                  COMBLANK
C                  COMDIAG
C
C REMARKS:
C   - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   .
C   HU,HV,HTHETA    NGM GRID VARIABLES                     COMMON
C   HQ
C   .
C   - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C   .
C   NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C   -----       ----------------------------------        ---------
C   TEMPERATURE AND RELATIVE HUMIDITY PLUS                 PRINTED
C   ZONAL AND MERIDIONAL VELOCITIES
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN
C   MACHINE:  CRAY Y-MP
C
C$$$
C
      INCLUDE 'parmodel'
C
      PARAMETER ( NLAT = 18, NLAT1=19)
C...TRANSLATED BY FPP 3.00Z36 11/09/90  15:10:27  
C...SWITCHES: OPTON=I47,OPTOFF=VAE0
      REAL R1S,R2S,R3S,R4S
      LOGICAL L1S
C
C     COMMON BLOCK /COMCONST/ CONTAINS GRID-RELATED PARAMETERS,
C          AND A FEW OTHER COMMON CONSTANTS.
      COMMON /COMCONST/ IJMAX, KM, LVLTOT, IJRAD, LOFCLDS(2,4),
     1                  ICALLRAD, IPHYSPL, NGRDUSE, NH,
     2                  NTIME, ITIME, NSTEPS,
     3                  IMG(INGRDUSE), JMG(INGRDUSE),
     4                  IAG(INGRDUS1), JAG(INGRDUS1),
     5                  IBG(INGRDUS1), JBG(INGRDUS1),
     6                  IADDRG(INIADDRS, INGRDUSE),
     7                  NPTSFH(2, INGRDUSE),
     8                  KUMULUS, LGRIDPPT, KLIFT1, KLIFT2, IBUCKET,
     9                  XPOLEH(INGRDUSE), YPOLEH(INGRDUSE), RADIUS,
     1                  DELSIG(IKM), PR(IKM), PRESS(IKM),
     2                  SIGINT(IKMP1),
     3                  DTOVDX, ANGVEL,
     4                  SIGMACC, SIGMAGSP, SIGMADHQ, CRITCONV,
     5                  SATDEL, RHFACTOR, QBOUND,
     6                  ANEM, BLKDR, CHARN, CONAUST, DDORF, PKATO,
     7                  SCALEHT, SIGDOT, DLAMNGM
C
C
      COMMON            SCR     (IIJMAX,  INSCR),
     1                  SCRGEOG (IIJMAX,  INSCRGEO),
     2                  SCR3    (IIJKMAX, INSCR3),
     3                  FILLER  (INFILLER),
     4                  VBL     (INVBL),
     5                  BITGRDH (IIJMAX, 2, INGRDUSE),
     6                  BITGRDU (IIJMAX, 2, INGRDUSE),
     7                  BITGRDV (IIJMAX, 2, INGRDUSE),
     8                  BITSEA  (IIJMAX, INGRDUSE),
     9                  BITSNO  (IIJMAX, INGRDUSE),
     1                  BITWVL  (IIJMAX, INGRDUSE)
C
      LOGICAL BITGRDH, BITGRDU, BITGRDV, BITSEA, BITSNO, BITWVL
C
C     COMMON BLOCK /COMDIAG/ CONTAINS QUANTITIES SAVED FOR
C          DIAGNOSTIC PURPOSES.
      COMMON /COMDIAG/  KADIAB( IKM, INGRDUSE ),
     1                  NPTSDHQ (2, INGRDUSE),
     2                  KKCLOUD2(2, INGRDUSE), NPTSBUOY(2, INGRDUSE),
     3                  NPTSWATR(2, INGRDUSE), NPTSCC  (2, INGRDUSE),
     4                  KKGSP2  (2, INGRDUSE),
     5                  KKGSE2  (2, INGRDUSE),
     6                  NPTSSAT (IKM, 2, INGRDUSE),
     7                  NPTSEVAP(IKM, 2, INGRDUSE),
     8                  NPTSGSP (2, INGRDUSE), NUMPROF,
     9                  PPTCC   (2, INGRDUSE), PPTGSP  (2, INGRDUSE),
     1                  ALATPR  (IMAXPROF),    ALONPR  (IMAXPROF),
     2                  DESCRP  (IMAXPROF)
C
      CHARACTER*24 DESCRP
C
      DIMENSION U(NLAT,IKM,INGRDUSE), V(NLAT,IKM,INGRDUSE),
     1 T(NLAT,IKM,INGRDUSE), JLAT(IIJMAX), NUMLBLT(NLAT,INGRDUSE),
     2 SUM(NLAT), W(INGRDUSE),WG(NLAT,INGRDUSE),YLAT(NLAT),P(NLAT),
     3 SINT(NLAT1), RH(NLAT,IKM,INGRDUSE), ALBEDO(NLAT,INGRDUSE)
C
C           ARRAY TO SAVE INITIAL CROSSECTION OF TEMPERATURE
      DIMENSION TZERO(NLAT,IKM)
      DIMENSION SINLAT(NLAT,INGRDUSE)
      DIMENSION B1 ( IIJMAX ), B2 ( IIJMAX )
      LOGICAL B1, B2
C
      EQUIVALENCE ( SCR(1,7),JLAT(1) )
C
      INTEGER I1X
      REAL COFD1,COFD2,COFD3,COFD4,COFN1,COFN2,COFN3
      PARAMETER (COFD1 = 1., COFD2 = 5.44053037, COFD3 = 2.27693825, 
     1   COFD4 = -0.0869930591, COFN1 = 0.34757549, COFN2 = 4.36732956, 
     2   COFN3 = 3.91557032)
      DATA ICALL /0/
C
C---------------------------------------------------------------
C
C
C---------------------------------------------------------------
C
      IF(ICALL .GT. 0 ) GO TO 3
C              ESTABLISH LATITUDE TABLES
      FLAT = 0.5 * 3.1415927 / FLOAT(NLAT)
      YLAT1 = 0.
      DO 2 J=1,NLAT
      SINT(J) = SIN(YLAT1)
      YLAT(J) =( YLAT1 + .5 * FLAT) * (180. / 3.1415927)
      YLAT1 = YLAT1 + FLAT
    2 CONTINUE
      SINT(NLAT+1) = 1.
C
    3 CONTINUE
C
C                ENTER GRID LOOP
C        WEIGHT FOR GRID DENSITY ( = 1 FOR GRID A,0.25 FOR GRID B,ETC)
      WW = 4.
C        INITIALIZE GSIZE = GRID INTERVAL / TWICE EARTH RADIUS
      DNH = FLOAT(NH)
      GSIZE = 2. / ( DNH + 0.5 )
C
C
      NG = 1
88100 IF ( NG .GT. NGRDUSE )  GOTO 99100
      WW = 0.25 * WW
      W(NG) = WW
      IM = IMG(NG)
      JM = JMG(NG)
      IJ = IM * JM
C            REDUCE GRID SIZE NUMBER
      GSIZE = 0.5 * GSIZE
C              SET UP XI AND ETA VALUES
      ETA = - YPOLEH(NG) * GSIZE
      IAD = 0
        DO 20 J = 1,JM
        ETA = ETA + GSIZE
        XI = - XPOLEH(NG) * GSIZE
          DO 15 I = 1,IM
          IAD = IAD + 1
          XI = XI + GSIZE
          SCR(IAD,1) = XI
          SCR(IAD,2) = ETA
   15     CONTINUE
   20   CONTINUE
C
C           COMPUTE SQUARE OF POLAR DISTANCE ( = 1 AT EQUATOR )
CMIC$ PARALLEL SHARED(IJ, B1, SCR, JLAT) PRIVATE(IQ2W6E)
C
C           COMPUTE SQUARE OF POLAR DISTANCE ( = 1 AT EQUATOR )
CMIC$ DO PARALLEL VECTOR
      DO 88890 IQ2W6E = 1, IJ
         SCR(IQ2W6E,3) = SCR(IQ2W6E,1)*SCR(IQ2W6E,1) + SCR(IQ2W6E,2)*SCR
     1      (IQ2W6E,2)
         SCR(IQ2W6E,4) = (1.-SCR(IQ2W6E,3))/(1.+SCR(IQ2W6E,3))
         SCR(IQ2W6E,3) = SQRT(SCR(IQ2W6E,3))
         B1(IQ2W6E) = SCR(IQ2W6E,3) .GT. 0.
         IF (B1(IQ2W6E)) THEN
            SCR(IQ2W6E,3) = 1./SCR(IQ2W6E,3)
            SCR(IQ2W6E,1) = SCR(IQ2W6E,1)*SCR(IQ2W6E,3)
            SCR(IQ2W6E,2) = SCR(IQ2W6E,2)*SCR(IQ2W6E,3)
         ENDIF
88890 CONTINUE
C            DO WE HAVE ANY POINTS AT THE POLE
CMIC$ DO PARALLEL VECTOR
      DO 88990 IQ2W6E = 1, IJ
         IF (.NOT.B1(IQ2W6E)) THEN
            SCR(IQ2W6E,1) = 1.
            SCR(IQ2W6E,2) = 0.
         ENDIF
         JLAT(IQ2W6E) = 0
88990 CONTINUE
CMIC$ END PARALLEL
C           THE LATITUDE INTERVAL
        DO 30 J = 1,NLAT
        SIN1 = SINT(J)
        SIN2 = SINT(J+1)
CMIC$ DO ALL VECTOR SHARED(IJ, SIN1, SIN2, NG, SCR, B1, B2, BITGRDH)
CMIC$1    PRIVATE(IQ2W6E)
      DO 89010 IQ2W6E = 1, IJ
         B1(IQ2W6E) = SCR(IQ2W6E,4) .GE. SIN1
         B2(IQ2W6E) = SCR(IQ2W6E,4) .LT. SIN2
         B1(IQ2W6E) = B1(IQ2W6E) .AND. B2(IQ2W6E)
         B1(IQ2W6E) = B1(IQ2W6E) .AND. BITGRDH(IQ2W6E,1,NG)
89010 CONTINUE
      NUMLBLT(J,NG)=0
      DO 762 I = 1, IJ
         IF ( B1(I) ) NUMLBLT(J,NG)=NUMLBLT(J,NG)+1
762   CONTINUE
C
C                SKIP PRINTING NOWADAYS
        IF(ICALL .GE. 0 ) GO TO 29
        PRINT 28,NG,J,SIN1,SIN2,NUMLBLT(J,NG)
   28   FORMAT(1H ,2X,'IN ZONEDIAG--NG,J=',2I5,' SIN1,SIN2=',
     1  2F9.5,' HAS NUMLBLT=',I6)
   29   CONTINUE
C
        IF(NUMLBLT(J,NG) .LE. 0 ) GO TO 30
C           STORE BIN  ASSIGNMENT
CMIC$ DO ALL VECTOR SHARED(IJ, J, B1, JLAT) PRIVATE(IQ2W6E)
      DO 89050 IQ2W6E=1,IJ
         IF ( B1 ( IQ2W6E ) ) THEN
            JLAT(IQ2W6E) = J
         END IF
89050 CONTINUE
C
   30   CONTINUE
C
C                   TEST WITH THE FIELD OF SINE(LATITUDE)
      IF(ICALL .GT. 0 ) GO TO 32
CMIC$ DO ALL VECTOR SHARED(IJ, SCR) PRIVATE(IQ2W6E)
      DO 89060 IQ2W6E=1,IJ
         SCR(IQ2W6E,5)=SCR(IQ2W6E,4)
89060 CONTINUE
      IRET = 4
      GO TO 200
   31 CONTINUE
CMIC$ DO ALL VECTOR SHARED(NG, SUM, SINLAT) PRIVATE(IQ2W6E)
      DO 89070 IQ2W6E=1,NLAT
         SINLAT(IQ2W6E,NG)=SUM(IQ2W6E)
89070 CONTINUE
   32 CONTINUE
C
C             CAN NOW DO THE TEMPERATURE AND REL HUMID FIELDS
C         FIRST PUT H**KAPPA INTO SCR(6)
C
      IADH = IADDRG(5,NG)
C
C*****  Code Expanded From Routine:  P2KAP
CMIC$ DO ALL VECTOR SHARED(IJ, IADH, VBL, SCR) PRIVATE(I1X)
      DO 77053 I1X = 1, IJ
         SCR(I1X,6) = (0.34757549+VBL(I1X+IADH-1)*(4.36732956+VBL(I1X+
     1      IADH-1)*3.91557032))/(1.+VBL(I1X+IADH-1)*(5.44053037+VBL(I1X
     2      +IADH-1)*(2.27693825+VBL(I1X+IADH-1)*(-0.0869930591))))
77053 CONTINUE
C*****  End of Code Expanded From Routine:  P2KAP
C           1/H AT H POINTS TO SCR(3)
CMIC$ DO ALL VECTOR SHARED(IJ, IADH, VBL, SCR) PRIVATE(IQ2W6E)
      DO 89080 IQ2W6E = 1, IJ
         SCR(IQ2W6E,3) = 1./VBL(IADH+IQ2W6E-1)
         SCR(IQ2W6E,6) = SCR(IQ2W6E,3)*SCR(IQ2W6E,6)
89080 CONTINUE
C
      EPS = 287.05 / 461.5
      IADT = IADDRG(3,NG) - IJ
      IADQ = IADDRG(4,NG) - IJ
C
        K = 1
 445     IF ( K .GT. KM ) GOTO 45
C       DO 45 K = 1,KM
        IADT = IADT + IJ
        IADQ = IADQ + IJ
        CONST = 2. * PR(K)
CMIC$ DO ALL VECTOR SHARED(IJ, CONST, IADT, VBL, SCR) PRIVATE(IQ2W6E)
      DO 89100 IQ2W6E=1,IJ
         SCR(IQ2W6E,5)=CONST*VBL(IADT+IQ2W6E-1)*SCR(IQ2W6E,6)
89100 CONTINUE
        IRET = 1
        GO TO 200
   40 CONTINUE
CMIC$ DO ALL VECTOR SHARED(K, NG, SUM, T) PRIVATE(IQ2W6E)
      DO 89120 IQ2W6E=1,NLAT
         T(IQ2W6E,K,NG)=SUM(IQ2W6E)
89120 CONTINUE
C         NOW GET THE RELATIVE HUMIDITY ( RANGE HERE IS 0 TO 1 )
C         SAT VAP PRESS(CBS) INTO SCR(13)
        CALL VAPTAB(SCR(1,5),SCR(1,13),IJ,1)
C         DENOMINATOR INTO SCR(9)
CMIC$ DO ALL VECTOR SHARED(IJ,EPS,IADH,IADQ,VBL,SCR)PRIVATE(IQ2W6E)
      DO 89130 IQ2W6E=1,IJ
         SCR(IQ2W6E,9)=EPS*(VBL(IADH+IQ2W6E-1)-VBL(IADQ+IQ2W6E-1))
     *                              *SCR(IQ2W6E,13)
89130 CONTINUE
C             DRY LAYER PRESS (CBS) INTO SCR(10)
        CONST= 100. * PRESS(K)
CMIC$ DO ALL VECTOR SHARED(IJ, CONST, IADH, IADQ, VBL, SCR) PRIVATE(
CMIC$1   IQ2W6E)
      DO 89150 IQ2W6E = 1, IJ
         SCR(IQ2W6E,10) = CONST*VBL(IADH+IQ2W6E-1) - SCR(IQ2W6E,13)
         SCR(IQ2W6E,10) = SCR(IQ2W6E,10)*VBL(IADQ+IQ2W6E-1)
         SCR(IQ2W6E,5) = SCR(IQ2W6E,10)/SCR(IQ2W6E,9)
89150 CONTINUE
        IRET = 5
        GO TO 200
   41 CONTINUE
CMIC$ DO ALL VECTOR SHARED(K, NG, SUM, RH) PRIVATE(IQ2W6E)
      DO 89180 IQ2W6E=1,NLAT
         RH(IQ2W6E,K,NG)=SUM(IQ2W6E)
89180 CONTINUE
C
      K = K + 1
      GOTO 445
   45   CONTINUE
C
C           DO ZONAL VELOCITY VALUES
C
      IADU = IADDRG(1,NG) - IJ
      IADV = IADDRG(2,NG) - IJ
      K = 1
88080 IF ( K .GT.KM ) GOTO 99080
        IADU = IADU + IJ
        IADV = IADV + IJ
C               HU AT H-POINTS TO SCR(4)
CMIC$ DO ALL VECTOR SHARED(IJ, IADU, IM, IADV, VBL, SCR) PRIVATE(IQ2W6E)
      DO 89190 IQ2W6E = 1, IJ
         SCR(IQ2W6E,4) = 0.5*(VBL(IADU+IQ2W6E-1)+VBL(IADU-IM+IQ2W6E-1))
         SCR(IQ2W6E,6) = 0.5*(VBL(IADV+IQ2W6E-1)+VBL(IADV-2+IQ2W6E))
         SCR(IQ2W6E,9) = -SCR(IQ2W6E,2)*SCR(IQ2W6E,4)
         SCR(IQ2W6E,10) = SCR(IQ2W6E,1)*SCR(IQ2W6E,6)
         SCR(IQ2W6E,5) = SCR(IQ2W6E,9) + SCR(IQ2W6E,10)
89190 CONTINUE
        IRET = 2
        GO TO 200
   60 CONTINUE
CMIC$ PARALLEL SHARED(IJ, SCR, K, NG, SUM, U) PRIVATE(IQ2W6E)
CMIC$ DO PARALLEL VECTOR
      DO 89240 IQ2W6E=1,NLAT
         U(IQ2W6E,K,NG)=SUM(IQ2W6E)
89240 CONTINUE
C              THE MERIDIONAL VELOCITY COMPONENT TIMES H
CMIC$ DO PARALLEL VECTOR
      DO 89250 IQ2W6E=1,IJ
         SCR(IQ2W6E,9)=-SCR(IQ2W6E,1)*SCR(IQ2W6E,4)
         SCR(IQ2W6E,10)=-SCR(IQ2W6E,2)*SCR(IQ2W6E,6)
         SCR(IQ2W6E,5)=SCR(IQ2W6E,9)+SCR(IQ2W6E,10)
89250 CONTINUE
CMIC$ END PARALLEL
        IRET = 3
        GO TO 200
   70 CONTINUE
CMIC$ DO ALL VECTOR SHARED(K, NG, SUM, V) PRIVATE(IQ2W6E)
      DO 89280 IQ2W6E=1,NLAT
         V(IQ2W6E,K,NG)=SUM(IQ2W6E)
89280 CONTINUE
C
80     K = K + 1
       GOTO 88080
99080  CONTINUE
CWA80   CONTINUE
C
C           AT 48 HOURS DO THE PLANETARY ALBEDO
        IF( ITIME .NE. 172800 ) GO TO 100
C          ARRAY NUMBERS FOR INCOMING AND OUTGOING SOLAR RADIATION
        IADOUT = IADDRG(40,NG)
        IADIN  = IADDRG(41,NG)
C*****
CMIC$ DO ALL VECTOR SHARED(IJ, NG, BITGRDH, B2) PRIVATE(IQ2W6E)
      DO 89290 IQ2W6E=1,IJ
         B2(IQ2W6E)=BITGRDH(IQ2W6E,1,NG)
89290 CONTINUE
        SINMIN =  1.E+35
        SOUMIN =  1.E+35
        SINMAX = -1.E+35
        SOUMAX = -1.E+35
CMIC$ PARALLEL SHARED(IJ, IADIN, SINMIN, SINMAX, IADOUT, SOUMIN, SOUMAX
CMIC$1   , B2, VBL) PRIVATE(I, R1S, R2S, R3S, R4S, L1S)
      R1S = SINMIN
      R2S = SINMAX
      R3S = SOUMIN
      R4S = SOUMAX
CMIC$ DO PARALLEL VECTOR
      DO 683 I = 1, IJ
         L1S = B2(I)
         IF (L1S) THEN
            R1S = AMIN1(VBL(IADIN+I-1),R1S)
            R2S = AMAX1(VBL(IADIN+I-1),R2S)
            R3S = AMIN1(VBL(IADOUT+I-1),R3S)
            R4S = AMAX1(VBL(IADOUT+I-1),R4S)
         ELSE
         ENDIF
  683 CONTINUE
CMIC$ GUARD
      SOUMAX = AMAX1(SOUMAX,R4S)
CMIC$ END GUARD
CMIC$ GUARD
      SOUMIN = AMIN1(SOUMIN,R3S)
CMIC$ END GUARD
CMIC$ GUARD
      SINMAX = AMAX1(SINMAX,R2S)
CMIC$ END GUARD
CMIC$ GUARD
      SINMIN = AMIN1(SINMIN,R1S)
CMIC$ END GUARD
CMIC$ END DO
CMIC$ END PARALLEL
        PRINT 85,NG,SINMIN,SINMAX,SOUMIN,SOUMAX
   85   FORMAT(1H0,2X,'GRID',I4,'HAS MIN,MAX INC SWRADIAT=',2E14.6,
     1                'MIN,MAX OUT SWRADIAT=',2E14.6)
C********
CMIC$ DO ALL VECTOR SHARED(IJ, IADIN, NG, IADOUT, VBL, B2, BITGRDH, SCR)
CMIC$1    PRIVATE(IQ2W6E)
      DO 89300 IQ2W6E = 1, IJ
         B2(IQ2W6E) = VBL(IADIN+IQ2W6E-1) .GT. 0.
         B2(IQ2W6E) = B2(IQ2W6E) .AND. BITGRDH(IQ2W6E,1,NG)
         SCR(IQ2W6E,5) = 0.
         IF (B2(IQ2W6E)) SCR(IQ2W6E,5) = VBL(IADOUT+IQ2W6E-1)/VBL(IADIN+
     1      IQ2W6E-1)
89300 CONTINUE
        IRET = 6
        GO TO 200
   90 CONTINUE
CMIC$ DO ALL VECTOR SHARED(NG, SUM, ALBEDO) PRIVATE(IQ2W6E)
      DO 89340 IQ2W6E=1,NLAT
         ALBEDO(IQ2W6E,NG)=SUM(IQ2W6E)
89340 CONTINUE
C
  100 NG = NG + 1
      GOTO 88100
99100 CONTINUE
C            DONE WITH STORING LATITUDE TOTALS FOR ALL GRIDS
C               NEED THE GRID AND LATITUDE WEIGHTS
      DO 120 J=1,NLAT
      DSUM = 0.
        DO 110 NG = 1,NGRDUSE
        DSUM = DSUM + W(NG) * FLOAT( NUMLBLT(J,NG) )
  110   CONTINUE
      DSUM = 1. / DSUM
        DO 115 NG = 1,NGRDUSE
        WG(J,NG) = W(NG) * DSUM
C            SKIP PRINTING NOWADAYS
        IF( ICALL .GE. 0 ) GO TO 115
        PRINT 114,NG,J,WG(J,NG)
  114   FORMAT(1H ,2X,'IN ZONEDIAG,NG AND J=',2I5,
     1         ' HAS WG(J,NG)=',E14.6)
  115   CONTINUE
C
  120 CONTINUE
C
      GO TO 220
C
C-------------------- COMPUTED GO TO ROUTINE FOR ZONAL INTEGRATION
C
  200 CONTINUE
C
CMIC$ DO ALL SHARED(IJ, SUM, JLAT, SCR) PRIVATE(B1, J, IQ2W6E) SAVELAST 
      DO 210 J = 1,NLAT
      SUM(J) = 0.
      DO 89350 IQ2W6E=1,IJ
         B1(IQ2W6E)=JLAT(IQ2W6E).EQ.J
         IF ( B1 ( IQ2W6E ) ) SUM(J) = SUM(J) + SCR(IQ2W6E,5 )
89350 CONTINUE
  210 CONTINUE
C
      GO TO ( 40, 60, 70 ,31, 41 , 90 ) , IRET
C
C----------------------------------------------------------------
C
  220 CONTINUE
C
C                  DO PRINTING
      IF( ICALL .GT. 0 ) GO TO 299
      PRINT 295
  295 FORMAT(1H0,30X,'SINE OF LATITUDE')
      PRINT 302,YLAT
CMIC$ DO ALL SHARED(NGRDUSE, WG, SINLAT, P, SINT, SUM) PRIVATE(PP, J, 
CMIC$1   TRSIN, NG)
      DO 297 J = 1,NLAT
      PP = 0.
        DO 296 NG = 1,NGRDUSE
        PP = PP + WG(J,NG) * SINLAT(J,NG)
  296   CONTINUE
      P(J) = PP
C             PUT PERCENTAGE SAMPLING ERROR INTO SUM(J)
      TRSIN = 0.5*(SINT(J) + SINT(J+1) )
      SUM(J) = 100.* ( (PP/TRSIN) - 1. )
  297 CONTINUE
      K4SIN = 0
      PRINT 320,K4SIN,P
      PRINT 298
  298 FORMAT(1H0, 30X,'PERCENT SAMPLING ERROR OF SINE(LAT)' )
      PRINT 320,K4SIN,SUM
C
  299 CONTINUE
C
      THOURS = FLOAT(ITIME) / 3600.
      PRINT 300, THOURS
  300 FORMAT(1H1,40X,'ZONAL DIAGNOSTICS FOR',F8.2,' HOURS')
C
      PRINT 301
  301 FORMAT(1H0,30X,'ZONAL AVERAGED TEMPERATURE IN CENTIGRADE' )
      PRINT 302,YLAT
  302 FORMAT(1H0,2X,' K',18F6.1)
C
      DO 340 KK = 1,KM
      K = KM + 1 - KK
CMIC$ DO ALL SHARED(NGRDUSE, K, WG, T, P) PRIVATE(PP, J, NG)
        DO 315 J = 1,NLAT
        PP = 0.
          DO 310 NG = 1,NGRDUSE
          PP = PP + WG(J,NG) * T(J,K,NG)
  310     CONTINUE
        P(J) = PP - 273.16
  315   CONTINUE
      PRINT 320,K,P
  320 FORMAT(1H ,2X,I2,18F6.2)
C          SAVE INITIAL TEMPERATURES ON FIRST CALL
      IF( ICALL .EQ. 0 )THEN
CMIC$ DO ALL VECTOR SHARED(K, P, TZERO) PRIVATE(IQ2W6E)
      DO 89360 IQ2W6E=1,NLAT
         TZERO(IQ2W6E,K)=P(IQ2W6E)
89360 CONTINUE
      END IF
C       WILL WANT TO PRINT 48-HR TEMP CHANGES AT 48 HOURS
      IF (ITIME .EQ. 172800 )THEN
CMIC$ DO ALL VECTOR SHARED(K, P, TZERO) PRIVATE(IQ2W6E)
      DO 89370 IQ2W6E=1,NLAT
         TZERO(IQ2W6E,K)=P(IQ2W6E)-TZERO(IQ2W6E,K)
89370 CONTINUE
      END IF
  340 CONTINUE
C
C                PRINT THE RELATIVE HUMIDITY ( RANGE WILL BE 0-100)
      PRINT 341
  341 FORMAT(1H0,30X,'ZONAL AVERAGED RELATIVE HUMIDITY')
      PRINT 302,YLAT
C
      DO 345 KK=1,KM
      K = KM+1-KK
CMIC$ DO ALL SHARED(NGRDUSE, K, WG, RH, P) PRIVATE(PP, J, NG)
        DO 343 J=1,NLAT
        PP = 0.
          DO 342 NG = 1,NGRDUSE
          PP = PP + WG(J,NG) * RH(J,K,NG)
  342     CONTINUE
        P(J) = 100. * PP
  343   CONTINUE
      PRINT 320,K,P
C
  345 CONTINUE
C
C                PRINT THE ZONAL VELOCITIES
      PRINT 350
  350 FORMAT(1H0,30X,'ZONAL AVERAGE OF ZONAL VELOCITY TIMES ',
     1      'SFC PRESS IN BARS')
      PRINT 302,YLAT
C
      DO 400 KK = 1,KM
      K = KM + 1 - KK
CMIC$ DO ALL SHARED(NGRDUSE, K, WG, U, P) PRIVATE(PP, J, NG)
        DO 370 J = 1,NLAT
        PP = 0.
          DO 360 NG = 1,NGRDUSE
          PP = PP + WG(J,NG) * U(J,K,NG)
  360     CONTINUE
        P(J) = PP
  370   CONTINUE
      PRINT 320,K,P
C
  400 CONTINUE
C
C             PRINT THE MERIDIONAL VELOCITIES
      PRINT 410
  410 FORMAT(1H0,30X,'ZONAL AVERAGE OF MERIDIONAL VELOCITY',
     1  ' TIMES SFC PRESS IN BARS')
C
      PRINT 302,YLAT
C
      DO 450 KK = 1,KM
      K = KM + 1 - KK
CMIC$ DO ALL SHARED(NGRDUSE, K, WG, V, P) PRIVATE(PP, J, NG)
        DO 430 J = 1,NLAT
        PP = 0.
          DO 420 NG = 1,NGRDUSE
          PP = PP + WG(J,NG) * V(J,K,NG)
  420     CONTINUE
        P(J) = PP
  430   CONTINUE
      PRINT 320,K,P
  450 CONTINUE
C
 
      ICALL = ICALL + 1
C
      IF( ITIME .LT. 172800 ) RETURN
C           PRINT TEMPERATURE CHANGES
      PRINT 460
  460 FORMAT(1H0,30X,'48-HOUR TEMPERATURE CHANGES')
C
      PRINT 302,YLAT
C
      DO 465 KK=1,KM
      K = KM+1-KK
      PRINT 320,K,(TZERO(L,K),L=1,18)
  465 CONTINUE
C
C              PRINT THE ALBEDO
      PRINT 470
  470 FORMAT(1H0,30X,'PLANETARY ALBEDO' )
      PRINT 302,YLAT
      ALBMEAN = 0.
      COSMEAN = 0.
        DO 472 J = 1,NLAT
        PP = 0.
          DO 471 NG=1,NGRDUSE
          PP = PP + WG(J,NG) * ALBEDO(J,NG)
  471     CONTINUE
        P(J) = PP
        ARG = 0.01745329 * YLAT(J)
        CCOS = COS(ARG)
        ALBMEAN = PP * CCOS + ALBMEAN
        COSMEAN = CCOS + COSMEAN
  472   CONTINUE
      PRINT 473,P
  473 FORMAT(1H0,4X,18F6.2 )
      ALBMEAN = ALBMEAN / COSMEAN
      PRINT 474,ALBMEAN
  474 FORMAT(1H0,10X,'HEMISPHERIC 2-DAY MEAN ALBEDO IS',F10.4)
C
      RETURN
      END
