       PROGRAM ICLFM4
C      PROGRAM ICLFM4(OUTPUT,WVLFMBND,WVLFMSIN,WVLFMS00,WVLFMS06,
C    &              WVLFMS12,WVFMVV06,WVFMVV12,UNIT6=OUTPUT,
C    &              UNIT20=WVLFMBND,UNIT21=WVLFMSIN,
C    &              UNIT30=WVLFMS00,UNIT31=WVLFMS06,UNIT32=WVLFMS12,
C    &              UNIT51=WVFMVV06,UNIT52=WVFMVV12)
C$$$  MAIN PROGRAM DOCUMENTATION BLOCK
C
C MAIN PROGRAM:  ICLFM4      FOURTH-ORDER LFM FCST MODEL
C   AUTHOR: DEAVEN             ORG: NMC22         DATE: 86-08-28
C
C MODIFIED BY DEAVEN ON 5/7/87 FOR FORTRAN 77 (FTNNEW)
C     PROGRAM CARD CHANGED FOR FORTRAN 77 FILE PRECONNECTS
C     NO OTHER SOURCE CODE CHANGES
C
C ABSTRACT: EXECUTES THE FORTH ORDER  VERSION OF THE
C   LFM FORECAST MODEL WITH 7 LAYERS ON THE 190.5 KM POLAR STERO
C   GRID.  FORECASTS FOR 12 HOURS.
C
C PROGRAM HISTORY LOG:
C   72-??-??  ORIGINAL AUTHOR(S): ????
C   92-06-15  R.E.JONES   CONVERT CRAY SOURCE TO RUN ON 32 BIT 
C                         WORKSTATIONS
C   93-05-14  R.E.JONES   CORRECTION IN TEND5 FOR OVERFLOW PROBLEM
C
C USAGE:
C   INPUT FILES:
C     UNIT20   -   BOUNDARY VALUES FROM SPECTRAL MODEL
C     UNIT21   -   INITIAL  VALUES FROM LFMINI
C     UNIT30   -   INITIAL  VALUE OF A 12 HOUR FORECAST SEGMENT
C
C   OUTPUT FILES:
C     UNIT53   -    6,18,30,42 HR HISTORY FILE
C     UNIT54   -   12,24,36,48 HR HISTORY FILE
C     UNIT51   -    6,18,30,42 HR VERTICAL VELOCITIES
C     UNIT52   -   12,24,36,48 HR VERTICAL VELOCITIES
C     OUTPUT   -   PRINT OUTPUT
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:     ABSH2O, ARYTOT, BLDBND, DSXDY,  TENXY,
C                 DSXY,   DSYDX,  ERREXT, FCST,   FTIME,
C                 INTBND, LCL,    NFB01,  PRECAL, RDBNDY(ZRBNDY),
C                 RDTAPE, SATM,   SOLDEC, STARTF, WRTAPE,
C                 TENDA,  TENDB,  STATS,  WATER,  SETBC, TSMO,
C                 TEND1,  TEND2,  TEND3,  TEND4,
C                 TEND5,  TEND6,  TENPT,  TENUV,
C                 TTOARY, UNPSEP, VVEL,   WKLOX
C
C     LIBRARY:
C       SPECIAL  - 
C
C   EXIT STATES:
C     COND = 0   SUCCESSFUL RUN
C          = 999 FAILURE
C          = 1607  DISASTER STOP FROM ERREXT.  SEE FT06 MESSAGES.
C
C
C   REMARKS: SEE DENNIS DEAVEN W/NMC23 DEVELOPMENT DIVISION FOR SCIENCE
C            MODIFICATION BY STACKPOLE W/NMC42 870602
C               TIME STEP SHORTENED FROM 9 STEPS PER HOUR TO 10 PER HOUR
C               IN AN ATTEMPT TO CURE S.W. CORNER JET BLOWUP
C               (GERRITY SAYS TO BLAME EL NINO - EVERYBODY ELSE DOES)
C               CHANGED CARDS ARE BRACKETED BY ***JDS*** COMMENTS
C
C
C ATTRIBUTES:
C   LANGUAGE: SiliconGraphics 3.5 FORTRAN 77
C   MACHINE:  SiliconGraphics IRIS-4D/25, 35, INDIGO
C
C$$$
      IMPLICIT    REAL (A-H,O-Z)
      REAL        BNDATE(9)
      REAL        HOUR1
      REAL        ICE, MF
      LOGICAL     RECV
      CHARACTER*4 LABSIN,LABBND,LABS00,LABS06,LABS12,LABV06,LABV12
      COMMON /INDEX/ LI,LJ,LK,LI1,LJ1,LK1,LI2,NIJ,LOLD,LMID,LNEW,
     1     K7OLD,K7MID,K7NEW,K3OLD,K3MID,K3NEW,K2OLD,K2MID,K2NEW,
     2     K,K1,K2,K3,KL,KH
      COMMON /FDATE/  IYEAR, IMO, IDAYMO, IZTIME, IHR1, IOUT
      COMMON /SVHOUR/ NWDS, IHOUR1( 1205 ), HOUR1(8)
      COMMON /TTME/   MNSTEP,IODD,IHOUR,IMONTH,ITSW,IVEL,NPHOUR,
     1                SSLDC,CSLDC,SSLHR,CSLHR,SHR,CHR,
     2                ALP,XDAYMO
      COMMON /FORTAP/ LUNBND,LUNSIN,LUNS00,LUNS06,LUNS12,LUNV06,LUNV12,
     A                LABSIN(8),LABBND(8),LABS00(8),LABS06(8),LABS12(8),
     B                LABV06(8),LABV12(8),PARM(25)
      COMMON /PBNDPE/ ALARGE( 53 ,12, 23 ), BLARGE( 12, 33 ,23 )
      COMMON /PBNDRY/ AA( 53 ,12, 23), BB( 12, 33 ,23 )
      COMMON /DEABLK/ US( 53 , 45 , 21 ),
     A     VS( 53 , 45 , 21 ),
     1     TS( 53 , 45 , 21 ),PSIG( 53 , 45 , 6 ),
     2     ST( 53 , 45 ),ICE( 53 , 45 ),
     3     COSZEN( 53 , 45 ),XM( 53 , 45 ),
     4     F( 53 , 45 ),CD( 53 , 45 ),
     5     SATW( 53 , 45 ,3),WS( 53 , 45 , 9 ),
     6     PREC( 53 , 45 ),ZSTAR( 53 , 45 ),
     7     ALON( 53 , 45 ),ALAT( 53 , 45 ),
     8     MF( 53 , 45 ),H2( 53 , 45 , 3 )
      COMMON /VERTV/ IVVEL( 53 , 45 , 8 )
      COMMON /CNST/ BTHICK,BTHIK1,BTHK3,DT,RDELX,
     1              DTDS0,DTDS1,DTDS2,DTDX,DS1DX,DS2DX,
     2              CP,R,ROCP,TSTRAT,CPTS,SATRH,RSAT60,
     3              RDT,BTHICH,BTHK3H,BTK398,RBT,A1BRN,
     4              A2BRN,TDTDX4,RPK,VVCNST
      COMMON /DIAG/ SUMK(8),SUMP1(8),SUMP2(8),SUMS(8),SUMF(8),SUMFD(8),
     1     SUMVOR(8),SUMDIV(8),DP(8),SUMP(8),SUMTS(8),SUMZ(8),
     2     SIGB1,SIGT1,SIGT2,SIGS1,SIGS2,RMSSFC,RMSTRP
      COMMON /FASTER/ PIE(1100),AX(120)
      COMMON /VTEMP/  SIGDOT( 53, 45, 5), VT( 53, 45, 25 )
C
      DATA RECV/.FALSE./
C
C     IRECT=RECOV.INT., IFTAPE=1 AT INITIAL PE READ
C
      DATA IRECT/6/,IFTAPE/1/
C
c     DOUBLE PRECISION INIT
c     DATA INIT/'LFMFXMP '/
c     CHARACTER*41 MYESLF/'LATERAL BOUNDARIES FROM PREVIOUS AVN RUN:'/
c     CHARACTER*41 MNOLFM/'LATERAL BOUNDARIES SET TO CONSTANT VALUE:'/
C
C        BEGIN THE WHOLE WORKS HERE
C-----------------------------------------------------------------------
C      CALL W3LOG('$S86240.72','ICLFM4  ')
!       CALL W3TAGB('ICLFM4  ',0093,0160,0072,'NMC22 ')
C-----------------------------------------------------------------------
C        INITIALZE TEMPORARY VECTOR  SPACE WITH NINES
C
C-------------------------------------------------------
C
C          
      DO K = 1,25
      DO J = 1,45
      DO I = 1,53
        VT(I,J,K) = 9.0E0
      END DO
      END DO
      END DO
C
      PRINT 5
 5    FORMAT (//,45X,'NMC LFM FORECAST MODEL  FORECAST SECTION')
C     PRINT 99
C  99 FORMAT (/55X,'(VERSION DATE 07 MAY 87)'//)
C
C    IHOUR = CURRENT FCST HOUR SET IN RDTAPE FROM CONTENT OF LUNS00 FILE
C      SET UNIT NO. FOR I/O FILES.
C
      LUNBND = 20
      LUNSIN = 21
      LUNS00 = 30
      LUNS06 = 53
      LUNS12 = 54
      LUNV06 = 51
      LUNV12 = 52
C
    6 CONTINUE
      PRINT 4,LUNBND,LUNSIN,LUNS00,LUNS06,LUNS12,LUNV06,LUNV12
    4 FORMAT(/,10X,'LOGICAL UNIT NOS. FOR ... ',/,5X,' BOUNDARY,',
     A     ' INPUT, 00HR, 06HR, 12HR SIGMA FIELDS ....',
     B     ' 06HR, 12HR VERT. VEL. FIELDS',/,
     C     8X,I4, 4(5X,I2), 19X,I2, 5X,I2,//)
C
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C                                 ***JDS***   START
C - - - - - NOTE NPHOUR = 3600/DT = 3600/360 = 10 TIME STEPS PER HOUR
C             NPHOUR MUST BE INTEGER AS MUST BE DT
C             SUCH THAT THEIR PRODUCT = 3600 SECONDS PER HOUR
C             TYPICAL CHOICES ARE 9 (400 SEC PER TIME STEP)
C                                10 (360 SEC PER TIME STEP)
C                                12 (300 SEC PER TIME STEP)
C                                  ***JDS***  END
C - - - - -      IORDER = 2  SECOND ORDER DIFFERENCES
C - - - - -             = 4  FOURTH ORDER DIFFERENCES
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C           IORDER =  4
C                                  ***JDS***  START
            NPHOUR =  10
C                                  ***JDS***  END
            SATRH = 0.90E0
C
      CALL STARTF
      CALL PRECAL
      CALL RDTAPE
C
C     REESTABLISH BOUNDARY (FIELD) VALUES FOR FORECAST
C     UP TO IHOUR (IHOUR SET IN RDTAPE).
C
      CALL INTBND
C ADDED ZRBNDY CALL TO TRY AND FORCE EXECUTION
C
c     CALL ZRBNDY
      IRC = IHOUR + IRECT
c     IF (IRC.NE.9999) GO TO 10
C
C        TOP OF MANY PASS LOOP ( ONLY TWO TIMES HERE)
C        EACH PASS FORECASTS FOR IRECT HOURS WORTH
C        LOOP TERMINATES WHEN 12 HOURS HAVE BEEN DONE
C
 15   IHR1 = IHOUR
      IF (IFTAPE.NE.1) GO TO 181
      IFTAPE = 0
      REWIND LUNBND
      READ (LUNBND,END=13) LABBND
C     IF (IHOUR.EQ.0) CALL W3LOG('$L',MYESLF)
         GO TO 12
   13      PRINT 14
C     IF (IHOUR.EQ.0) CALL W3LOG('$L',MNOLFM)
   14      FORMAT('0    EOF ENCOUNTERED READING LABEL ON BOUNDARY FILE')
C                          (CORRECTIVE ACTION TAKEN BELOW)
           REWIND LUNBND
   12 IF (IHR1.EQ.0) GO TO 70
C
C      SPACE LIVE BNDRY TAPE
C
      ILS = 0
   21 READ (LUNBND,END=17) BNDATE
   16 ILS = ILS + 1
      IHR = BNDATE(1)
      IF (IHR.EQ.IHOUR) GO TO 22
      GO TO 21
   17 PRINT 151,  ILS, IHR1
      REWIND LUNBND
  151 FORMAT('0 ENCOUNTERED EOF POSITIONING LUNBND, SKIPPED',I5,
     1' RECORDS TRYING TO GET TO HOUR',I5)
      IHR = 999
      GO TO 22
   18 PRINT 152,  ILS
  152 FORMAT('0 PARITY ERROR SKIPPING RECORD ', I5, 'ON LUNBND')
      GO TO 16
C
C        BNDRY TAPE POSITIONED SO NEXT READ WILL GET PROPER TEND VALUES
C
   22 RECV   = .TRUE.
   70 IZTIME = HOUR1(2)
      IDAYMO = HOUR1(5)
      IMO    = HOUR1(4)
      IYEAR  = HOUR1(3)
 181  IF (IRC.NE.IHR1) GO TO 406
      IRC    = IRC + IRECT
 406  CONTINUE
      IOUT   = IRC
      IF (RECV) GO TO 23
C
C      READ LIVE BNDRY TAPE  ONLY EVERY 6 HOURS
C
      IF (MOD(IHOUR,6).NE.0) GO TO 10
C
      READ (LUNBND,END=35) BNDATE
      IHR = BNDATE(1)
   23 CONTINUE
      IF (IHR.EQ.IHOUR) GO TO 31
 35   CALL ZRBNDY
      REWIND LUNBND
      GO TO 10
 31   CALL RDBNDY
      RECV = .FALSE.
   10 CONTINUE
C     ZERO VERTICAL VELOCITY STORAGE SHARED
      N8IJ = 8 * 2385
      DO 88900 IQ2W6E = 1,N8IJ
         IVVEL(IQ2W6E,1,1) = 0.0E0
88900 CONTINUE
C
C        FTIME WILL FORECAST FROM CURRENT TIME (IHOUR,IHR1)
C            UP TO IOUT HOUR  (IOUT AND IRC EQUAL)
C
      CALL FTIME
      IF (MNSTEP.EQ.0) GOTO 720
C
C        GET OUT OF LOOP AFTER 12 HOURS OF FORECASTING
C
         IF(MOD(IHOUR,12).NE.0)  GOTO 15
C
C        BOTTOM OF FORECAST LOOP
C
C-----------------------------------------------------------------------
C     CALL W3LOG('$E')
C-----------------------------------------------------------------------
      PRINT 715
 715  FORMAT('1 END OF NMC PRIMITIVE EQUATION FORECAST')
!      CALL W3TAGE('ICLFM4  ')
      STOP 0
C
C        DISASTER AREA
C
720   CONTINUE
C     CALL W3EXIT(999,'7 LAYER LFM MODEL FAILURE IN MAIN :',INIT)
      PRINT *,'7 LAYER LFM MODEL FAILURE IN MAIN :',INIT
      STOP 999
      END
