      SUBROUTINE STARTF
C$$$  SUBPROGRAM  DOCUMENTATION  BLOCK
C
C SUBPROGRAM: STARTF         INITIALZES CONSTANTS AND ARRAYS
C   AUTHOR: DENNIS DEAVEN    ORG: W/NMC23    DATE: 20 JUN 83
C
C ABSTRACT: INITIALZES MANY CONSTANTS AND LATERAL BOUNDARY COEF.
C   ARRAY (CONTROLS LINEAR DIFFUSION COEFFICIENT)....
C
C USAGE:  CALL STARTF
C
C - - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C
C     NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C
C     CP          SPECIFIC HEAT AT CONSTANT PRESSURE        /CNST/
C     R           UNIVERSAL GAS CONSTANT (J/(KG X K))       /CNST/
C     ROCP        R/CP  (KAPPA)                             /CNST/
C     RPK         1 / (1 + R/CP) FOR BROWN-PHILLIPS PI      /CNST/
C     LI,LJ,LK    GRID DOMIAN (USUALLY 53,45,7)             /INDEX/
C     LI1,LJ1     LI-1 AND LJ-1                             /INDEX/
C     LI2         /I/2
C     NWDS        BYTES PER STRIP  LI*(LK+2)*4              /SVHOUR/
C     NIJ         LI * LJ  LENGTH OF HORIZONTAL VECTORS     /INDEX/
C     DT          LENGTH OF TIME STEP (SECONDS)             /CNST/
C     DX          GRID INCREMENT (METERS)
C     VVCNST      SCALING CONSTANT FOR VERTICAL VELS
C     DS0         SIGMA INCREMENT B.L. ( EQUALS 1.0)
C     DS1             DITTO       TROPOSPHERE (EQUALS 1/3)
C     DS2             DITTO       STRATOSPHERE    DITTO
C     XBND        DIFFUSION COEF. ARRAY FOR BOUNDARY REGION
C     XDIF        DIFFUSION COEF. ARRAY FOR INTERIOR
C     BTHICK      BOUNDARY LAYER PRESS THICKNESS ( 50 MB)
C     MNSTEP      TIME STEP CONTOL
C     ALP         ALPHA FOR TIME SMOOTHER ( EQUALS 0.075)
C     A1BRN,A2BRN PRESSURE GRADIENT AVERAGE COEFFICIENTS
C
C     MANY MORE...... ALL FUNCTIONS OF ABOVE CONSTANTS
C
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C ATTRIBUTES:
C   LANGUAGE: SiliconGraphics 3.5 FORTRAN 77
C   MACHINE:  SiliconGraphics IRIS-4D/25, 35, INDIGO
C
C$$$
C
      IMPLICIT    REAL (A-H,O-Z)
      REAL        HOUR1
      CHARACTER*4 LABSIN,LABBND,LABS00,LABS06,LABS12,LABV06,LABV12
      COMMON /CNST/ BTHICK,BTHIK1,BTHK3,DT,RDELX,
     1              DTDS0,DTDS1,DTDS2,DTDX,DS1DX,DS2DX,
     2              CP,R,ROCP,TSTRAT,CPTS,SATRH,RSAT60,
     3              RDT,BTHICH,BTHK3H,BTK398,RBT,A1BRN,
     4              A2BRN,TDTDX4,RPK,VVCNST
      COMMON /DIAG/ SUMK(8),SUMP1(8),SUMP2(8),SUMS(8),SUMF(8),SUMFD(8),
     1     SUMVOR(8),SUMDIV(8),DP(8),SUMP(8),SUMTS(8),SUMZ(8),
     2     SIGB1,SIGT1,SIGT2,SIGS1,SIGS2,RMSSFC,RMSTRP
      COMMON /FASTER/ PIE(1100),AX(120)
      COMMON /INDEX/ LI,LJ,LK,LI1,LJ1,LK1,LI2,NIJ,LOLD,LMID,LNEW,
     1     K7OLD,K7MID,K7NEW,K3OLD,K3MID,K3NEW,K2OLD,K2MID,K2NEW,
     2     K,K1,K2,K3,KL,KH
      COMMON /FDATE/  IYEAR, IMO, IDAYMO, IZTIME, IHR1, IOUT
      COMMON /SVHOUR/ NWDS, IHOUR1( 1205 ), HOUR1(8)
      COMMON /TTME/   MNSTEP,IODD,IHOUR,IMONTH,ITSW,IVEL,NPHOUR,
     1                SSLDC,CSLDC,SSLHR,CSLHR,SHR,CHR,
     2                ALP,XDAYMO
      COMMON /FORTAP/ LUNBND,LUNSIN,LUNS00,LUNS06,LUNS12,LUNV06,LUNV12,
     A                LABSIN(8),LABBND(8),LABS00(8),LABS06(8),LABS12(8),
     B                LABV06(8),LABV12(8),PARM(25)
      COMMON /PBNDPE/ ALARGE( 53 ,12, 23 ), BLARGE( 12, 33 ,23 )
      COMMON /PBNDRY/ AA( 53 ,12, 23 ), BB( 12,33 ,23 )
      COMMON /BCOEF/  XDIF( 53 , 45 ), XBND( 53 , 45 )
      SAVE
C
      CP     = 1004.67E0
      R      = 287.04E0
      ROCP   = R/CP
      RPK    = 1.E0 / (1.E0  + ROCP)
      LI     = 53
      LJ     = 45
      LK     = 7
      LI1    = 53  - 1
      LJ1    = 45  - 1
      LI2    = 53 / 2
      NWDS   = 53 * (LK+2) * 4
      NIJ    = 2385
      DT     = 3600.E0/NPHOUR
      DX     = 190.5  * 1000.0E0
      VVCNST = 1.E6 * DT / 3600.0E0
      DS0    = 1.0E0
      DS1    = 1.0E0 / 3.0E0
      DS2    = 1.E0 / 3.E0
      RDELXS = 1.E0 /(DX * DX)
      VLM = 2.2E5 * 2.E0 * DT * RDELXS
      DO 88890 IQ2W6E = 1,NIJ
         XBND(IQ2W6E,1) = 0.E0
88890 CONTINUE
      DO 88900 IQ2W6E=1,5*LI
         XBND(IQ2W6E,1)=0.04E0
         XBND(IQ2W6E,LJ-4)=0.04E0
88900 CONTINUE
      JEND = LJ-5
      DO 334 J = 6,JEND
      DO 88920 IQ2W6E=1,5
         XBND(IQ2W6E,J)=0.04E0
         XBND(LI+IQ2W6E-5,J)=0.04E0
88920 CONTINUE
334   CONTINUE
      DO 88940 IQ2W6E=1,NIJ
         XDIF(IQ2W6E,1)=XBND(IQ2W6E,1)
88940 CONTINUE
C**** WHERE (XBND(1,1  ;  NIJ).EQ.0.E0)XDIF(1,1  ;  NIJ) = VLM
C**** DTDS0 = DT/DS0
         IQ2W6E=IQ2W6E
      DO 88950 IQ2W6E=1,NIJ
         IF (.NOT.(XBND(IQ2W6E,1).EQ.0.E0)) GO TO 88950
         XDIF(IQ2W6E,1)=VLM
88950 CONTINUE
      IQ2W6E = IQ2W6E
      DTDS0  = DT  / DS0
      DTDS1  = DT  / DS1
      DTDS2  = DT  / DS2
      DS1DX  = DS1 / DX
      DS2DX  = DS2 / DX
      BTHICK = 50.E0
      BTHK3  = BTHICK / 3.E0
      IODD   = 1
      MNSTEP = -1
      RDELX  = 1.E0 / DX
      DTDX   = DT/DX
      RSAT60 = -.6E0/SATRH
      RDT    = 1.E0/DT
      RBT    = -1.E0/BTHICK
      BTHICH =.5E0*BTHICK
      BTHK3H =.5E0*BTHK3
      BTK398 = BTHK3/.98E0
      BTHIK1 = BTHICK * .001E0
      ALP    = 0.075E0
      A1BRN  = 0.25E0*(ALP*ALP+1.0E0)*(ALP+1.0E0)
      A2BRN  = 1.0E0-2.E0*A1BRN
      RETURN
      END
