       SUBROUTINE TEND6
C$$$   SUBPROGRAM  DOCUMENTATION  BLOCK
C
C SUBPROGRAM: TEND6          MASS & MOISTURE TENDENCIES ADVANCED 1 STEP
C   AUTHOR: DENNIS DEAVEN    ORG: W/NMC23    DATE: 21 JUN 83
C
C ABSTRACT: COMPUTES FORTH ORDER BAR XY OF THE MASS AND MOISTURE
C   TIME TENDENCIES, ADDS THE LINEAR DIFFUSION TERM AND ADVANCES
C   FORWARD ONE TIME STEP.  LATERAL BOUNDARY CONDITION (DIFFUSIVE
C   NUDGE) IS ALSO CALCULATED HERE.  PERIMETER BOUNDARY VALUES ARE
C   RESTORED FOR TS, PSIG AND WS.
C
C USAGE:  CALL TEND6
C
C - - - - - - - - - I N P U T   V A R I A B L E S  - - - - - - - - -
C
C     NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C     US,VS..     FORECAST VARIABLES PLUS FIXED FIELDS      /DEABLK/
C     XDIF        ARRAY OF SCALED DIFFUSION COEFFICIENTS    /BCOEF/
C     ITSW        TIME STEP SWITCH                          /TTME/
C                       ITSW EQ 1 === FORWARD STEP
C                       ITSW NE 1 === CENTERED STEP
C 
C - - - - - - - - - O U T P U T   V A R I A B L E S - - - - - - - - - -
C
C     NAMES       MEANING/CONTENT/PURPOSE/UNITS/TYPE        INTERFACE
C     -----       ----------------------------------        ---------
C     TS,WS,PSIG  TAU + 1 LEVELS STORED AT LNEW LEVEL       /DEABLK/
C
C - - - - - - - - - S U B P R O G R A M S   C A L L E D - - - - - - - -
C     NAME(S)                                               LIBRARY
C     -------                                               -------
C     DEL2XY,TENXY,BNDLAP                                   LFM LIB
C
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C ATTRIBUTES:
C   LANGUAGE: SiliconGraphics 3.5 FORTRAN 77
C   MACHINE:  SiliconGraphics IRIS-4D/25, 35, INDIGO
C$$$
C
      IMPLICIT    REAL (A-H,O-Z)
      REAL        HOUR1
      REAL        ICE, MF
      CHARACTER*4 LABSIN,LABBND,LABS00,LABS06,LABS12,LABV06,LABV12
      COMMON /VTEMP/  SIGDOT( 53 , 45 , 5 ), VT( 53 , 45 ,25 )
      COMMON /DEABLK/ US( 53 , 45 , 21 ),
     A     VS( 53 , 45 , 21 ),
     1     TS( 53 , 45 , 21 ),PSIG( 53 , 45 ,6),
     2     ST( 53 , 45 ),ICE( 53 , 45 ),
     3     COSZEN( 53 , 45 ),XM( 53 , 45 ),
     4     F( 53 , 45 ),CD( 53 , 45 ),
     5     SATW( 53 , 45 ,3),WS( 53 , 45 , 9 ),
     6     PREC( 53 , 45 ),ZSTAR( 53 , 45 ),
     7     ALON( 53 , 45 ),ALAT( 53 , 45 ),
     8     MF( 53 , 45 ),H2( 53 , 45 , 3 )
      COMMON /VERTV/ IVVEL( 53 , 45 , 8 )
      COMMON /CNST/ BTHICK,BTHIK1,BTHK3,DT,RDELX,
     1              DTDS0,DTDS1,DTDS2,DTDX,DS1DX,DS2DX,
     2              CP,R,ROCP,TSTRAT,CPTS,SATRH,RSAT60,
     3              RDT,BTHICH,BTHK3H,BTK398,RBT,A1BRN,
     4              A2BRN,TDTDX4,RPK,VVCNST
      COMMON /DIAG/ SUMK(8),SUMP1(8),SUMP2(8),SUMS(8),SUMF(8),SUMFD(8),
     1     SUMVOR(8),SUMDIV(8),DP(8),SUMP(8),SUMTS(8),SUMZ(8),
     2     SIGB1,SIGT1,SIGT2,SIGS1,SIGS2,RMSSFC,RMSTRP
      COMMON /FASTER/ PIE(1100),AX(120)
      COMMON /INDEX/ LI,LJ,LK,LI1,LJ1,LK1,LI2,NIJ,LOLD,LMID,LNEW,
     1     K7OLD,K7MID,K7NEW,K3OLD,K3MID,K3NEW,K2OLD,K2MID,K2NEW,
     2     K,K1,K2,K3,KL,KH
      COMMON /FDATE/ IYEAR, IMO, IDAYMO, IZTIME, IHR1, IOUT
      COMMON /SVHOUR/ NWDS, IHOUR1( 1205 ), HOUR1(8)
      COMMON /TTME/ MNSTEP,IODD,IHOUR,IMONTH,ITSW,IVEL,NPHOUR,
     1     SSLDC,CSLDC,SSLHR,CSLHR,SHR,CHR,
     2     ALP,XDAYMO
      COMMON /FORTAP/ LUNBND,LUNSIN,LUNS00,LUNS06,LUNS12,LUNV06,LUNV12,
     A                LABSIN(8),LABBND(8),LABS00(8),LABS06(8),LABS12(8),
     B                LABV06(8),LABV12(8),PARM(25)
      COMMON /PBNDPE/ ALARGE( 53 ,12, 23 ), BLARGE( 12, 33 ,23 )
      COMMON /PBNDRY/ AA( 53 ,12, 23 ), BB(12, 33 ,23 )
      COMMON /BCOEF/  XDIF( 53 , 45 ), XBND( 53 , 45 )
      SAVE
C----------------------------------------------------------------------
C   FORM XY BAR ON THE TS, WS, AND PSIG TENDENCIES AND STORE THE RESULT
C   AT THE LNEW TIME LEVEL.  ALSO ADD THE LINEAR DIFFUSION TERM TO EACH
C   LNEW VALUE, XDIF TAKES CARE OF THE INTERIOR AND LATERAL BOUNDARY
C   REGION AUTOMATICALLY.
C   VT(24) AND VT(25) ARE NOT AVAILABLE FOR TEMPORAY SPACE SO
C   VT(16) AND VT(17) WILL BE USED
C----------------------------------------------------------------------
C
C  TS FIRST FOR ALL VALUES OF K
C
       C1 = 2.E0
       IF (ITSW .EQ. 1 ) C1 = 1.E0
       CALL DEL2XY(VT(1,1,16),TS(1,1,K7OLD))
       CALL TENXY(VT(1,1,17),TS(1,1,K7NEW))
      DO 88890 IQ2W6E=1,NIJ
         TS(IQ2W6E,1,K7NEW)=XDIF(IQ2W6E,1)*VT(IQ2W6E,1,16)+VT(IQ2W6E,1
     *   ,17)*C1+TS(IQ2W6E,1,K7OLD)
88890 CONTINUE
C
C  WS FOR K = 1,2,3
C
       IF ( K.GT.3 ) GO TO 100
       CALL DEL2XY(VT(1,1,16),WS(1,1,K3OLD + K - 1))
       CALL TENXY(VT(1,1,17),WS(1,1,K3NEW + K - 1))
      DO 88900 IQ2W6E=1,NIJ
         WS(IQ2W6E,1,K3NEW+K-1)=XDIF(IQ2W6E,1)*VT(IQ2W6E,1,16)+VT
     *   (IQ2W6E,1,17)*C1+WS(IQ2W6E,1,K3OLD+K-1)
88900 CONTINUE
         IQ2W6E=IQ2W6E
      DO 88910 IQ2W6E=1,NIJ
         IF(.NOT.(WS(IQ2W6E,1,K3NEW+K-1).LT..0E0))GO TO 88910
         WS(IQ2W6E,1,K3NEW+K-1)=0.E0
88910 CONTINUE
         IQ2W6E=IQ2W6E
C
C  PSIG FOR K = 1,2
C
C****  WHERE (WS(1,1,K3NEW+K-1  ;  NIJ) .LT..0E0)
C****A           WS(1,1,K3NEW+K-1  ;  NIJ) = 0.E0
       IF ( K.GT.2 ) GO TO 100
       CALL DEL2XY(VT(1,1,16),PSIG(1,1,K2OLD + K - 1))
       CALL TENXY(VT(1,1,17),PSIG(1,1,K2NEW + K - 1))
       PCKTRL = 50.E0
       PCKTRH = 300.E0
       IF ( K.EQ.2 ) PCKTRL = 15.E0
       IF ( K.EQ.2 ) PCKTRH = 150.E0
      DO 88920 IQ2W6E=1,NIJ
         PSIG(IQ2W6E,1,K2NEW+K-1)=XDIF(IQ2W6E,1)*VT(IQ2W6E,1,16)+
     *   VT(IQ2W6E,1,17)*C1+PSIG(IQ2W6E,1,K2OLD+K-1)
88920 CONTINUE
C****  WHERE(PSIG(1,1,K2NEW+K-1  ;  NIJ).GT.PCKTRH)
C****A        PSIG(1,1,K2NEW+K-1  ;  NIJ) = PCKTRH
         IQ2W6E=IQ2W6E
      DO 88930 IQ2W6E=1,NIJ
         IF(.NOT.(PSIG(IQ2W6E,1,K2NEW+K-1).GT.PCKTRH))GO TO 88930
         PSIG(IQ2W6E,1,K2NEW+K-1)=PCKTRH
88930 CONTINUE
         IQ2W6E=IQ2W6E
C****  WHERE (PSIG(1,1,K2NEW+K-1  ;  NIJ) .LT. PCKTRL)
C****A        PSIG(1,1,K2NEW+K-1  ;  NIJ) = PCKTRL
         IQ2W6E=IQ2W6E
      DO 88940 IQ2W6E=1,NIJ
         IF(.NOT.(PSIG(IQ2W6E,1,K2NEW+K-1).LT.PCKTRL))GO TO 88940
         PSIG(IQ2W6E,1,K2NEW+K-1)=PCKTRL
88940 CONTINUE
         IQ2W6E=IQ2W6E
100    CONTINUE
C
C  SETS LATERAL BOUNDARY CONDITIONS THRU CALLS TO BNDLAP FOR T,PSIG
C
       CALL BNDLAP(ALARGE(1,1,K+14),BLARGE(1,1,K+14),TS(1,1,K7NEW))
       IF( K.GT.2 ) GO TO 10
       L2 = K + LNEW * 2
       CALL BNDLAP(ALARGE(1,1,K+21),BLARGE(1,1,K+21),PSIG(1,1,L2))
10     CONTINUE
C-----------------------------------------------------------------------
C  RESTORE PERIMETER VALUES OF WS HERE FOR ALL THREE LAYERS
C  MOVE LOLD TO LNEW AROUND THE EDGES OF THE GRID
C-----------------------------------------------------------------------
       IF ( K .GT. 3 ) RETURN
       L3O = K + LOLD * 3
       L3N = K + LNEW * 3
      DO 88950 IQ2W6E=1,LI
         WS(IQ2W6E,1,L3N)=WS(IQ2W6E,1,L3O)
         WS(IQ2W6E,45,L3N)=WS(IQ2W6E,45,L3O)
88950 CONTINUE
       DO 34 J = 2,44
       WS(1,J,L3N)    = WS(1,J,L3O)
       WS( 53 ,J,L3N) = WS( 53 ,J,L3O)
34     CONTINUE
20     CONTINUE
       RETURN
       END
