      SUBROUTINE ACCUM (NBCLAT) 
C     THIS SUBROUTINE COMPUTES THE BASE ACCUMULATION RATES FOR
C     THE ICE SHEET.  THE ENTRY PT. ACC DOES THE FINE WORK, 
C       SUCH AS FINDING THE EXACT LOCATION OF THE FIRN LINE,
C       AND ALLOWING FOR THE HORIZINTAL MOTION OF THE ICE SHEET.
  
      INTEGER MXSB
      PARAMETER (MXSB = 160)
  
C     VARIABLES USED BY THE NON-ICE SHEET PORTION OF THE EBM
      COMMON W(46,50) 
  
      COMMON /LARGE/ NFLD, JTH1P, JTH2P, JTSLP, JTSOP,
     1               JTXLP, JTXOP, JTMP, JHLP, JHOP, JXIOP, 
     2               JQMLP, JQMOP, JTH1, JTH2, JTSL, JTSO,
     3               JTXL, JTXO, JTM, JHL, JHO, JXIO, 
     4               JQML, JQMO 
  
      COMMON /MINOR/ NMINOR, KFLD(26) 
  
C     VARIABLES USED IN THE ICE SHEET EXTRAPOLATION, AND NOT
C       CHANGED HERE. 
      COMMON /ISCOM/ HGT(0:MXSB,2), H, HP, HTOPO(0:MXSB)
  
      COMMON /ISETC/ TIMELP, TIMSTP, GRDSTP, TRIPS, 
     1               RNETAC, POLFLX, MSNAUT, MAPRIM,
     2               DELTAX, DELTAT, DHPDT(0:MXSB), 
     3               HPCALL, SNLXIN 
  
      INTEGER TRIPS, ISSB 
      REAL DELTAX, NBCLAT, GRDSTP, TIMELP 
  
C     VARIABLES USED IN THE ICE SHEET EXTRAPOLATION, AND CHANGED
C       OR SET HERE.
      COMMON /ACCCOM/ AHAT(0:MXSB), BHAT(0:MXSB)
  
C     LOCAL VARIABLES.
      REAL RADPDG, STRTIM, SECPYR, ANOM 
      REAL SNLXIN, SNLMPT, ALPHA1, ALPHA2, OSC1, OSC2 
      REAL PI, GAM, TSTAR, BNAUT, BWON, SLOPE 
      REAL ACMRAT, ABLAT, DELI
      INTEGER ANCALL, TOFYR 
C     DUMMY SET UP.  THESE ASSIGNMENTS ARE NOT NEEDED WHEN THE MODEL
C       IS ADDED TO THE EBM.
      LOGICAL ASTRO 
  
      DO 101 I = 1, 8 
        W(I, JHL) = W(I, JHL) + .1*I
        W(47-I,JHL)=W(47-I,JHL) + .1*I
        W(I, JHO)  = W(I, JHO)  + .1*I
        W(47-I,JHO)= W(47-I,JHO)+ .1*I
        W(I, JXIO) = W(I,  JXIO)+ .1*I
        W(47-I,JXIO)=W(47-I,JXIO)-.1*I
  101 CONTINUE
      DO 202 I = 7, 13
        W(I, JHL) = W(I, JHL) - .1*I
        W(47-I,JHL)=W(47-I,JHL) - .1*I
        W(I, JHO)  = W(I, JHO)  - .1*I
        W(47-I,JHO)= W(47-I,JHO)- .1*I
        W(I, JXIO) = W(I,  JXIO)- .1*I
        W(47-I,JXIO)=W(47-I,JXIO)-.1*I
  202 CONTINUE
  
      RETURN
  
      ENTRY ACC 
C     CALCULATE POSITION OF PERIODICALLY VARYING SNOW LINE
C     LOGICAL VAR ASTRO SELECTS WHETHER TO USE ASTRONOMICAL FORCING 
C        ADDED 8-16-85 BG.
      IF (ASTRO) THEN 
        IF (MOD(TRIPS, ANCALL).EQ.0)
     1     CALL ANOMALY( 90.-NBCLAT/RADPDG-ISSB*GRDSTP, TOFYR,
     2        -STRTIM+TIMELP/ SECPYR, ANOM) 
        SNLXIN = SNLMPT+ DXDQ( 90.-NBCLAT/RADPDG-ISSB*GRDSTP)*
     1      ANOM* ALPHA2
       ELSE 
        SNLXIN =SIN(OSC1+0.0*PI)*SNLAMP + SIN(OSC2* 
     1      TIMELP+ 0.0*PI)*SNLAMP + SNLMPT 
      ENDIF 
  
C     TEMPERATURE DEPENDANT ACCUMULATION RATE.
      DO 200 I=0,MXSB 
      TSTAR = GAM* (SLOPE* (I* DELTAX-SNLXIN)-HGT(I,H)) 
        IF(TSTAR.LE.0.0) THEN 
          AHAT(I) = ACMRAT* (1.+GAM* BNAUT* SLOPE*
     1      (I* DELTAX- SNLXIN))
          BHAT(I) = ACMRAT* GAM* BNAUT* BETA
         ELSE 
          AHAT(I) = -ABLAT-ALPHA1* BWON* GAM* SLOPE*
     1      (I* DELTAX- SNLXIN) 
          BHAT(I) = -ALPHA1* BWON* GAM* BETA
        ENDIF 
 200  CONTINUE
C     FIND THE FIRST PT THAT HAS ACCUMULATION.  GO FROM S-N.
      I=ISSB+10 
 210    IF (AHAT(I)-BHAT(I)*HGT(I,H).LT.0.0.AND.I.GT.1) THEN
        I=I-1 
      GO TO 210 
      ENDIF 
C     FIND THE EXACT INTERSECTION OF THE FIRN LINE. 
      DELI=(HGT(I,H)-SLOPE*(I*DELTAX-SNLXIN))/
     1    (HGT(I,H)-HGT(I+1,H)+SLOPE*DELTAX)
      IF (DELI.LT.0.0)  DELI=0.0
      IF (DELI.GT.1.0)  DELI=1.0
C     MODIFY THE ACCUMULATION RATES ACCORDINGLY.
      IF (DELI.LE.0.5) THEN 
        AHAT(I)=(.5+DELI)*AHAT(I)+(.5-DELI)*AHAT(I+1) 
        BHAT(I)=(.5+DELI)*BHAT(I)+(.5-DELI)*BHAT(I+1) 
       ELSE 
        AHAT(I+1)=(1.5-DELI)*AHAT(I+1)+(DELI-.5)*AHAT(I)
        BHAT(I+1)=(1.5-DELI)*BHAT(I+1)+(DELI-.5)*BHAT(I)
      ENDIF 
  
      RETURN
  
      ENTRY ACCSET
  
      SECPYR  = 31556900.0
      PI      = 3.141592653898
      RADPDG  = PI / 180.0
      READ (*,9006) ACMRAT
      ACMRAT  = ACMRAT/SECPYR 
      READ (*,9006) ABLAT 
      ABLAT   = ABLAT/SECPYR
      READ (*,9006) SLOPE 
      READ (*,9006) SNLAMP
      SNLAMP  = SNLAMP*1000.0 
      READ (*,9006) SNLMPT
      SNLMPT  = SNLMPT*1000.0 
      READ (*,9006) PERIOD
      READ (*,9006) DELP
C     DELP IS THE DISTANCE FROM THE AVERAGE PERIOD THE TWO DESIRED
C       PERIODS ARE, IN YEARS 
      READ (*,9006) BNAUT 
      READ (*,9006) BWON
      BWON = BWON/SECPYR
      READ (*,9006) ALPHA1
      READ (*,9006) GAM 
      READ (*,9006) BETA
      READ (*,9009) ASTRO 
      READ (*,9006) ALPHA2
      READ (*,9008) TOFYR 
      READ (*,9006) LAT 
      READ (*,9008) ANCALL
      READ (*,9006) STRTIM
  
      OSC1    = 2.*PI/ ((PERIOD+DELP) *SECPYR)
      OSC2    = 2.*PI/ ((PERIOD+DELP) *SECPYR)
  
C     SET UP USED IN EMULATING TWOB.  REMOVE WHEN ICE SHEET MODEL IS
C       PUT INTO CLIMATE MODEL.  BG 9-10-85 
      DO 303 I = 1, 46
        W(I, JHO) = 0.0 
        W(I, JHL) = 0.0 
        W(I,JXIO) = 0.0 
  303 CONTINUE
  
 9006 FORMAT (F14.4)
  
 9008 FORMAT (I5) 
  
 9009 FORMAT (L14)
  
      RETURN
      END 
