      BLOCK DATA CON2 
C     THIS IS USED TO CONTAIN 
C     DATA STATEMENTS INITIALIZING LABELED COMMON FROM ROUTINES 
C     SHIFTED TO A LIBRARY SEE THOSE ROUTINES FOR CONTEXT AND/OR
C     MORE COMMENTS 
     
      IMPLICIT none

C     SPECIFICATION STATMENTS 
C     EQCOM FROM EQTST

      INTEGER NMS, NMW, NMSKP, LNS, LNW, MZH
      REAL DTTST, DITST, QTST
      INTEGER IU
      LOGICAL LEQTST
      INTEGER KTNS, KINS, KTNW, KINW

      COMMON/EQCOM/NMS, NMW, NMSKP, 
     1  LNS, LNW, MZH, DTTST, DITST,
     2  QTST, KTNS, KINS, KTNW, KINW, 
     3  LEQTST, IU
  
C     DATA  STATMENTS 
C     EQCOM 
C     LIMITS FOR TESTS ON   T STAR OCEAN ,  SEA ICE , 
C     Q CONDUCTED THROUGH SEA ICE 
      DATA DTTST, DITST, QTST/.025, 0.25, 0.24   /
      DATA IU,LEQTST/16,.FALSE./
      END 
