      SUBROUTINE NOTEMZ(MZ) 
C     MODIFIED FOR MACHINE INDEPENDANCE 8/10/83.  BG
C     CLEARS ENTRIES IN NOTE AND SETS FLAGS IF THEY ARE NON-ZERO, 
C     FOR VARIOUS LATITUDES 
C     BE CAREFUL IN MAKING MODIFICATIONS
      COMMON/NOTE/NT(3) 
      COMMON/NOTETW/NTW(46,3),JNT 
      DATA JNT/3/,NTW/138*0/
      DO 10 L=1,JNT 
      IF (NT(L).NE.0) THEN
        NTW(MZ,L)=NTW(MZ,L)+1 
        NT(L)=0 
      ENDIF 
 10   CONTINUE
      RETURN
      END 
