      SUBROUTINE OUTITB(IUNIT)
C     MODIFIED FOR MACHINE INDEPENDANCE 8/12/83.  BOB GRUMBINE
C     PUNCH ALL MAJOR FIELDS IN A FORM
C     TO BE READ BY INITB ON A 4 DEGREE GRID. 
C     USE 4G20 FORMAT TO PRESERVE SIGNIFICANCE
C     SUBSTITUTE OTHER FORMATS IN FOR   -FOR READABILITY
      COMMON W(46,50) 
      COMMON/LARGE/NFLD,JFLD(12,2)
      COMMON/CONST/M,MM,MP,MPP,N,IDUM(42) 
      COMMON/TIMES/DAYTE,TYME 
      CHARACTER DAYTE*10,TYME*10
      CHARACTER IEND*10,FOR*10
      DATA IEND/'0123456789'/ 
      DATA FOR/'(4G20.12) ' / 
      DPHI=(180./MP)
C     IF TIME WAS CALLED BEFORE THE SAME VALUE IS RETURNED
      CALL TIMING 
      WRITE(IUNIT,11)DPHI,FOR,TYME,DAYTE
 11   FORMAT(F10.6,A10,40X,2A10)
      DO 20 L=1,NFLD
      JL=JFLD(L,2)
      WRITE(IUNIT,FOR)(W(MZ,JL),MZ=1,MPP) 
   20 CONTINUE
C     EXTRA CARD TO IDENTIFY END
      WRITE(IUNIT,30)(IEND,L=1,8) 
   30 FORMAT(8A10)
      ENDFILE IUNIT 
      RETURN
      END 
