      PROGRAM PCMA
C     MODIFIED TO SET UP FILE TO SEND DATA TO LOCY 11/10/83.
C     PROGRAM LOGIC CLEANED UP SOME. 10/23/83 
C     MONTHLY AVERAGING SHIFTED TO ARRAYS FOR SPEED.  10/12/83
C     COMPLETE CONVERSION TO BLOCK IF 10/6/83.
C     DONE CONVERTED TO BLOCK IF 9/29/83. 
C     PARTIAL CONVERSION TO BLOCK IF STRUCTURE 9/6/83.
C     MONTHLY AVERAGING ADDED 8/30/83.
C     FINE GRID REMOVED 8/24/83.
C     VERSION WITH ALL MAJOR MACHINE DEPENDANCIES CORRECTED. 8/12/83
C     CONVERTED TO FTN5 8/5/83. 
C     THIS IS FILE ZRABPR FOR VAR TOPOGRAPHY SENSITIVITY 05/11/83 
C     IN-LINE AVERAGING  9/24/79
C     USE ONLY ACC. RATE FROM SHORT TS IN ICE MODEL NOT  HL 10/1/79 
C     REVERSE INDEX LABELS ON HL ACC. AFTER INTSL  10/4/79
C     REMOVE SMALL ACC RATES 10/11/79 
C     PUNCH DECK EVERY CYCLE 10/11/79 
C     ZAP H SUB O AFTER A CYCLE   10/11/79
C     CHANGE ZERO TO ABLATION 11/10/79
C     DATA TRANSFER OF HI,DHLI 10/26/79 
C     ADD DHLZ ACC.RATE COMPUTATIONS    11/23/79
C     INTERPOLATE FM TO ICE MODEL SCALE      11/28/79 
C     ADD HP FIELD FOR ICE MODEL CA.6/20/80 
C     BLANK COMMON AND EXTERNAL CON2 FOR NCAR LOADER CA.6/24/80 
C     ADD HCONV,HELV FIELD CA. 7/23/80
C     COMPUTE A VARIABLE LAND ALBEDO 12/11/80 
C     JALBL,JALBO VARIABLE ALBEDO PARAMETERIZATION 1/16/81
C     BRUTE FORCE TEST OF MIDLATITUDE PLATEAU ON SENSITIVITY 9/12/81
C     ISHEET CHANGED BACK TO 181 PTS 8/24/83. 
C     BYPASS ISHEET SUBROUTINE CHANGE QUESTIONS/LOOK ONLY AT SHORT TS 
C     ADAPT CODE FOR ZONAL AVERAGE TOPOGRAPHY  10/12/81 
C     CHANGE HLI FIELD TO BE CALLED HI FIELD 10/13/81 
      COMMON W(46,50) 
C     COMMON MINOR REMOVED FROM PCMA 8/31/83, UNUSED HERE.
      EXTERNAL CON2 
      COMMON/WSPACE/ZAP(46) 
      COMMON/COMNT/LCOM(8)
C     COMMON NORBIT REMOVED FROM PCMA 8/31/83,UNUSED HERE.
C     SHORT TS SUBFIELDS
      DIMENSION HTOPO(46) 
C     AV4-8COM AND HLS FROM AV3COM COMBINED INTO AVCOM TO EASE TRACING. 
      COMMON/AV3COM/J,JON,MZERO,MPREF,LHLS,LHOS,LXIOS 
      COMMON/AVCOM/HLS(10),HOS(13),XIOS(13),DHLS(10),DHOS(13),DXIOS(13) 
      DIMENSION DHLSZ(23) 
C     ICE MODEL FIELDS LONG TS
      DIMENSION HI(181),DHLI(181) 
      DIMENSION HMI(181)
      DIMENSION HPI(181)
C     NUMBERS FOR DEGREE LABELS 
      DIMENSION EEGB(18),EGHLT(15)
      DIMENSION EEGI(181) 
C     PARAMETERS FOR TWOB CALLS.
      DIMENSION KP(7,3) 
C     KPI INTRODUCED TO ALLOW FOR FLAGS TO PASS TO CTWOUT.
      DOUBLE PRECISION KPI(2,3) 
C     COMMON CATFM REMOVED FROM PCMA 8/31/83, UNUSED HERE.
      COMMON/CONST/M,MM,MP,MPP,N,DPHIS,DTS,PI,DUMA(39)
      COMMON/LARGE/NFLD,JFLD(12,2)
      COMMON/MINOR/NMINOR,JFM,JRSN,JDUMMY(24) 
C     /TIMES/ ADDED TO IMPROVE COMPATABILITY.  SEE SBR NCAR.
      COMMON/TIMES/DAYTE,TYME 
      CHARACTER DAYTE*10,TYME*10
C     LENGTHS OF SHORT TS SUBFIELDS AVERAGED. 
      DATA LHLS/10/ 
C     LHLS IS TOTAL NO OF PTS ON SHORT TS GRID INCLUDED IN ISHEET GRID
C     LHOS IS LHLS +3 AS IS LXIOS.
      DATA LHOS/13/ 
      DATA LXIOS/13/
C     RATIO OF SHORT AND LONG A TS GRIDS
      DATA JON/3/ 
      DATA KRAT/20/ 
C     SOUTHERN LIMIT OF DATA SUBFIELDS
      DATA MZERO,MPREF/29,45/ 
      DATA IUPN/7/
C     STATEMENT FUNCTIONS DEFINED 
C     DEG(MP,MS)=180.*FLOAT(MZ-1)/MP-90.
C     DEGB(MP,L)=180.*FLOAT(L+MZERO-2)/MP-90. 
C     DEGI(L)=180.*FLOAT(LHLI-L+KRAT*(MZERO-1))/(MPREF*KRAT)-90.
C     DGHLT(L)=180.*FLOAT(LHLS-L+MZERO-1)/MPREF-90. 
C 
 152  FORMAT(BZ,4I5/3I5)
 153  FORMAT(BZ,D26.0/D26.0)
 141  FORMAT(//11X,5HTZERO,15X,5HDELTA,15X,5HTEND  ,
     1 10X,8HJOB SIZE/1X,3G20.12,I10/1X,8A10//) 
 142  FORMAT(///28H JOB SIZE EXIT  PUNCH CARDS  / 
     1 9H RAN FROM ,G15.8,3H TO ,G15.8/ 
     2 9H NEXT JOB/ 
     3 1X,3G15.8,I5/1X,8A10/) 
 143  FORMAT(G30.8/G30.8/G30.8/G30.8/8A10)
 145  FORMAT(///16H FINAL TIME EXIT  /
     1 9H RAN FROM ,G15.8,3H TO ,G15.8/1H1) 
 146  FORMAT (///' ABNORMAL EXIT NIX=',I10/ 
     1 36H CARDS PUNCHED BUT MAY NOT BE USABLE /
     2 21H ASTRONOMICAL TIME,T=,G15.8  /
     3 18H NUMBER OF CYCLES  ,I10)
 147  FORMAT(1X,I5,F7.2,2G15.8) 
 144  FORMAT(1X,I5,F7.2,3G15.8) 
 148  FORMAT(1X,I5,F7.2,G15.8)
 182  FORMAT(BZ,4G20.12)
 184  FORMAT(I5,10HH ICE      ,I5,10HHP ICE     ,30X,2A10)
 329  FORMAT(2X,F7.2,3G15.8)
 328  FORMAT('  H AND HP EVERYWHERE ZERO')
C     PRESET -IND CORE TO -IND WITH ADDRESS AT NCAR 6/19/80 
C     CALL CORSET 
      NCYC=0
C     READ SERIES USED TO COMPUTE ASTRO LPRAMETERS
      CALL ASTSET 
C     READ TABLES,INITIALIZE POINTERS AND CONSTANTS 
C     CALL TO TWOBIA REMOVED 10/23/83. BG 
      NMINOR=26 
      NFLD=12 
      CALL XPNT 
      CALL CON(JFM,JRSN)
C     READ IN 4 DEG GRID ZONAL MEAN TOPOGRAPHY, HTOPO 10/13/81
      MPPREF=MPREF+1
      READ (*,182,END=9500)(HTOPO(L),L=1,MPPREF)
C     HTOPO IS DEFINED TO BE THE UNDISTURBED TOPO ELEV 10/14/81 
C     LET HMI FIELD BE NEG OF HTOPO FIELD FOR ISHEET GRID 10/14/81
C     READ IN NEGATIVE OF HMI FIELD FOR ISHEET GRID 10/14/81
C     LHLI IS TOTAL NO OF ICESHEET GRID PTS, EG 181 
      LHLI=(LHLS-1)*KRAT+1
 9500 READ (*,182,END=9501)(HMI(L),L=1,LHLI)
C     READ IN BASIC CONTROL PARAMETERS
 9501 READ (*,154,END=9502)TZERO
 9502 READ (*,154,END=9503)DT 
 9503 READ (*,154,END=9504)TEND 
 9504 READ (*,154,END=9505)AJOBSZ 
 9505 READ (*,155,END=9506)LCOM 
 9506 JOBSZ=AJOBSZ
 154  FORMAT(BZ,E30.0)
 155  FORMAT(BZ,8A10) 
C     ASTRONOMICAL TIME-PAST TIME NEGATIVE
C     TZERO-INITIAL TIME
C     DT-DELTA T PER CYCLE
C     TEND-FINAL TIME 
C     JOBSZ-MAX NUMBER OF CYCLES THIS JOB 
C     LCOM-COMMENT CARD 
      WRITE(6,141)TZERO,DT,TEND,JOBSZ,LCOM
C     READ INITIAL CONDITIONS FOR SHORT  TS MODEL 
      CALL INITB
C     READ BLOCK CONTROL CARDS. 
C     BLOCK 1 ELIMINATED 8/30/83. 
C     READ FROM TWO TO THREE TO PRESERVE BLOCK NUMBERS. 
C     CARD 3 ELIMINATED 8/30/83.
      DO 160 J=2,3
      READ (*,152,END=9509) (KP(L,J),L=1,7) 
 9509 READ (*,153,END=160) KPI(1,J),KPI(2,J)
 160  CONTINUE
C     SET INITIAL TIME AND ORBITAL PARAMETERS 
      T=TZERO 
C     SECONDARY INITIALIZATION OF TWOB
C     ORBITAL PARAMETERS COMPUTED 
C     REMOVE NCYC=0 CALL TO TWOBIB. 
C     BLOCK 1 REMOVED 8/29/83 
C     COMPUTE LABELS IN DEG 
      DO 300 L=1,LXIOS
 300  EEGB(L)=180.*FLOAT(L+MZERO-2)/MPREF-90. 
      DO 301 L=1,LHLS 
 301  EGHLT(L)=180.*FLOAT(LHLS-L+MZERO-1)/MPREF-90. 
      DO 302 L=1,LHLI 
 302  EEGI(L)=180.*FLOAT(LHLI-L+KRAT*(MZERO-1))/(MPREF*KRAT)-90.
C     CHANGE SGN OF HMI AND REVERSE ORDER FROM READ IN. 10/16/81
      LHLI2=(LHLI-1)/2
      DO 100 L=1,LHLI2
      TEMP=-HMI(L)
      K=LHLI-(L-1)
      HMI(L)=-HMI(K)
      HMI(K)=TEMP 
 100  CONTINUE
      L=LHLI2+1 
      HMI(L)=-HMI(L)
C     READ H AND HP FOR ICEMODEL FROM CARDS. REMOVE PLATEAU 10/10/81
C     THESE ARE ALSO USED TO FILL IN 4 DEG GRID OVER ICE SHEET DOMAIN 
C     THAT IS THE HELV FIELD OVER DOMAIN OF ICE SHEET GRID 10/15/81 
C     SPECIAL ONE CYCLE TESTS BYPASS OF HI,HPI READ IN 10/15/81 
C     SET UP HI, HPI FOR NO ICE SHEET AND NO REBOUND 10/15/81 
      DO 101 L=1,LHLI 
      HPI(L)=HMI(L) 
      HI(L)=-HPI(L) 
 101  CONTINUE
      WRITE(6,144)(L,EEGI(L),HI(L),HPI(L),HMI(L),L=1,LHLI)
      CALL FMICE(LHLS,KRAT,MPREF,MZERO,NIX) 
      IF(NIX.NE.0) GO TO 900
      CALL ISEASET
C     ADD ZONAL MEAN TOPOGRAPHY FIELD HTOPO 10/10/81
      CALL HCONV(KRAT,HI,HPI,LHLI,.FALSE.,.TRUE.,NIX,HTOPO) 
      IF(NIX.NE.0) GO TO 900
C    TEST OF INTROD OF VARIABLE TOPO 10/15/81 
 103  FORMAT(' HELV FIELD TESTING') 
      WRITE(6,103)
      DO 102 MZ=1,MPP 
      WRITE(6,182) W(MZ,47) 
 102  CONTINUE
CEND TEST OF HELV FIELD 
C     MAIN CYCLE LOOP 
      DO 200 NCYC=1,JOBSZ 
C     SECONDARY INITIALIZATION
C     ORBITAL PARAMETERS COMPUTED 
C     SKIP TWOBIB WHEN NCYC.GT.1 AND DT.EQ.0        11/15/79
      IF((DT.NE.0.0).OR.(NCYC.LE.1)) CALL TWOBIB(NCYC,T)
C     LOOP THRU REPEATED
C     CALL TO TWOB
      DO 210 J=2,3
C     CALL TO TWOB-SHORT TS EXTRAPOLATION 
C     THE ENTIRE NON-ICE SHEET COMPONENT IS DONE HERE.
      CALL TWOB(KP(1,J),KP(2,J),KP(3,J),KP(4,J),
     1KP(5,J),KP(6,J),KP(7,J),
     2KPI(1,J),KPI(2,J))
 210  CONTINUE
C 
      CALL AV3CMP 
C     CALL TO CDCMP ADDED 11/10/83.  THIS SETS UP DATA FOR
C       TRANSMISSION TO LOCY. 
      CALL CDCMP
      WRITE(6,147)(L,EEGB(L), HLS(L), DHLS(L),L=1, LHLS)
      WRITE(6,147)(L,EEGB(L), HOS(L), DHOS(L),L=1, LHOS)
      WRITE(6,147)(L,EEGB(L),XIOS(L),DXIOS(L),L=1,LXIOS)
      CALL HLZOUT(DHLSZ)
      WRITE(6,148)(L,EEGB(L),DHLSZ(L),L=1,LHLS) 
      DO 170 LL=1,LHLS
      IF(ABS(DHLS(LL)).LE.0.1E-9.AND.HLS(LL).LE.10. 
     1.AND.HLS(MAX0(LL-1,1)).LE.10. 
     2.AND.HLS(MIN0(LL+1,LHLS)).LE.10.) 
     1  DHLS(LL)=DHLSZ(LL)
 170  CONTINUE
C     INTERPOLATE ACCUMULATION RATE 
      CALL INTSL(LHLS,KRAT,DHLS,DHLI,NIX) 
      WRITE(6,148)(L,EGHLT(L),DHLS(L),L=1,LHLS) 
      CALL ZEROSL(LHLS,LHLI,KRAT,DHLS,DHLI) 
      IF(NIX.NE.0) GO TO 900
      LL=0
      DO 330 L=1,LHLI 
      IF(HI(L).NE.0.OR.HPI(L).NE.0) THEN
        WRITE(6,329)EEGI(L),DHLI(L) 
        LL=1
      ENDIF 
 330  CONTINUE
      IF(LL.EQ.0) WRITE(6,328)
      CALL WRSD(DHLI,LHLI,'DHLI      ' ,17) 
C     CALL TO ISHEET REMOVED FROM HERE. 
      CALL WRSD(HI,LHLI,'HI        ',17)
      CALL WRSD(HPI,LHLI,'HPI       ',17) 
C     ENDFILE 17 REMOVED IN NCAR CODE PUT BACK AT NU ONLY 9/15/80 
      ENDFILE 17
      LL=0
      DO 340 L=1,LHLI 
      IF(HI(L).NE.0.OR.HPI(L).NE.0) THEN
        HTOTAL=HI(L)+HPI(L) 
        WRITE(6,329)EEGI(L),HI(L),HPI(L),HTOTAL 
        LL=1
      ENDIF 
 340  CONTINUE
      IF(LL.EQ.0) WRITE(6,328)
C     TRANSFER HL BACK TO SHORT TS
      CALL HCONV(KRAT,HI,HPI,LHLI,.TRUE.,.TRUE.,NIX,HTOPO)
      IF(NIX.NE.0) GO TO 900
C     ZAP H SUB O AFTER A CYCLE   10/11/79
      CALL PRESET(0.0,ZAP,MPREF+1)
      CALL PLGFLD(MPREF,9,1,MPREF+1,ZAP,NIX)
      IF(NIX.NE.0) GO TO 900
      CALL ISEA 
C     INCREMENT ASTRONOMICAL TIME 
      T=T+DT
      WRITE(IUPN,143) T,DT,TEND,AJOBSZ,LCOM 
C     PUNCH HL ON ICE MODEL SCALE 
C     PUNCH H AND HP FOR ICE MODEL
      CALL TIMING 
      WRITE(IUPN,184)LHLI,LHLI,TYME,DAYTE 
      WRITE(IUPN,182)(HI(L),L=1,LHLI) 
      WRITE(IUPN,182)(HPI(L),L=1,LHLI)
      CALL OUTITB(IUPN) 
C     CHECK FOR END(2 WAYS) 
      IF(T.GT.TEND) GO TO 920 
 200  CONTINUE
C     JOBSX END OF JOB EXIT 
      TL=T-DT 
      WRITE(6,142)TZERO,TL,T,DT,TEND,JOBSZ,LCOM 
      CALL REMARK(' PCM JOB SIZE NORMAL EXIT')
      CALL ENDIT
C     TEND FINAL TIME EXIT
 920  CONTINUE
      WRITE(6,145)TZERO,TL
      CALL REMARK(' PCM FINAL TIME NORMAL EXIT ') 
      CALL ENDIT
C     ABNORMAL EXIT (ERROR NIX.NE.0 RETURNED FROM SUBROUTINE) 
 900  WRITE(6,146) NIX,T,NCYC 
      WRITE(IUPN,143) T,DT,TEND,AJOBSZ,LCOM 
C     PUNCH HL ON ICE MODEL SCALE 
C     PUNCH H AND HP FOR ICE MODEL
      CALL TIMING 
      WRITE(IUPN,184)LHLI,LHLI,TYME,DAYTE 
      WRITE(IUPN,182)(HI(L),L=1,LHLI) 
      WRITE(IUPN,182)(HPI(L),L=1,LHLI)
      CALL OUTITB(IUPN) 
      CALL REMARK (' PCM,ABNORMAL END (SUB CALLS)') 
      CALL ENDIT
      END 
