       SUBROUTINE PLANAL(NS)
C      PLANETARY ALBEDO  FROM SPP,RSOUT,RLOUT FIELDS   11/5/79
C     COMMON CONST REMOVED FROM PLANAL 8/31/83, UNUSED HERE.
      COMMON/MINOR/NMINOR,JFM,JRSN,JPS,JSP,JSPP,JCZB,JCZBP,JQ1P,JQ2P
     1  ,JEXHT,JFSM(3,2),JTEQ,JXEIQ,JRSNL,JRSOUT,JRLOUT,DUMM(5) 
      COMMON W(46,50) 
       COMMON/CFCOM/NCG,NSC 
       COMMON/EQCOM/NMS,NMW,DUM(13) 
       MMOD(I,J)=MOD(J+MOD(I,J),J)
       NSM=NS-1 
       IF ((MMOD(NSM,NCG).NE.NMW) 
     1  .AND.(MMOD(NSM,NCG).NE.NMS))RETURN
C      INTEGRATE OVER SPACE 
       CALL SPNORM(JSPP,SPG,SPN,SPS,1,2)
       CALL SPNORM(JRSOUT,RASG,RASN,RASS,1,2) 
       CALL SPNORM(JRLOUT,RALG,RALN,RALS,1,2) 
C      IGNORE HEMISPHERE VALUES 
       PALG=RASG/SPG
       WRITE(6,10)NSM,SPG,RASG,RALG,PALG
 10    FORMAT( 1X,I7,'SWIN',G15.8,
     1  'SWOUT',G15.8,'LWOUT',G15.8,'PA',G15.8) 
       RETURN 
       END
