       SUBROUTINE PSWAP 
       COMMON /LARGE/NFLD,JFLD(12,2)
       COMMON/MINOR/NMINOR,JFM,JRSN,JPS,JSP,JSPP,JCZB,JCZBP,JQ1P,JQ2P,
     1  JEXHT,DUMM(16)
C      MINOR POINTS TO OTHER FIELDS IN W
C      NMINOR IS THE NUMBER OF POINTERS IN MINOR
C      SWAP POINTERS IN LARGE AND MINOR 
      DO 30 L=1,12
       JXX = JFLD(L,2)
       JFLD(L,2) = JFLD(L,1)
 30    JFLD(L,1) = JXX
       JXX = JSP
       JSP = JSPP 
       JSPP = JXX 
       JXX = JCZB 
       JCZB = JCZBP 
       JCZBP = JXX
       RETURN 
       END
