       FUNCTION RMIXL(T,PS) 
C      Albert Lunde
C      BOTH ENTRTY PTS  ARE LIQUID WATER 9/17/79
C      MIXING RATIO FUNCTION FOR LIQUID WATER 
C     T IS TEMPERATURE IN DEGREES KELVIN. 
C      PS SURFACE PRESSURE IN MILLIBARS 
       ENTRY RMIXI(T,PS)
       RMIXL = 3.79961 * EXP((17.2694 * T - 4714.54)
     1 /(T - 35.7))/PS
       RETURN 
       END      
