      SUBROUTINE SQADD(CARIN,CAROUT,LENIN,LENOUT) 
C     THIS SUBROUTINE TAKES A FIELD OF DATA THAT MAY HAVE MANY
C     CONSECUTIVE BLANKS AND REPLACES THE MULTIPLE BLANKS WITH
C     A SINGLE BLANK. 
C     WRITTEN TO BE MACHINE INDEPENDANT 8/9/83.  BOB GRUMBINE 
      CHARACTER CARIN*440,CAROUT*240
      IBLANK=0
      IPOSO=1 
 100  CONTINUE
      IPOSI=IPOSO+IBLANK
      IF(CARIN(IPOSI:IPOSI+1).EQ.'  ') THEN 
        CAROUT(IPOSO:IPOSO)=' ' 
        IBLANK=IBLANK+1 
 200    CONTINUE
C     REMOVE THE REPEATED BLANKS
        IPOSI=IPOSO+IBLANK+1
C     ADD 1 BECAUSE IPOSO HAS NOT BEEN INCREASED YET. 
        IF (CARIN(IPOSI:IPOSI).EQ.' ') THEN 
          IBLANK=IBLANK+1 
          GO TO 200 
        ENDIF 
       ELSE 
        CAROUT(IPOSO:IPOSO)=CARIN(IPOSI:IPOSI)
      ENDIF 
      IPOSO=IPOSO+1 
      IF (IPOSO+IBLANK.LT.LENIN) GO TO 100
C     UNTIL CLAUSE IN THE LOOP
      LENOUT=IPOSO
      RETURN
      END 
