      SUBROUTINE TWOB(KA,KB,KC,KD,KH,KI,KJ,KK,KL) 
C     KE-KG REMOVED 8/30/83, UNUSED.
C     NEW FILE,LOOP RECYCLE ADDED 5/11/79 
C     DOUBLE ITERATION FOR CENTERED Q 6/11/79 
C     SMOOTHING SUB ADDED    6/12/79
C     IN-LINE AVERAGING  9/24/79
C     FORCE GRID CONVERSION ,YRSET LNGEST CALLS NCYC=1   11/15/79 
C     ADD HCONV,HELV FIELD CA. 7/23/80
C     PUT LOCAL ALBEDO IN CZBP FIELD 7/29/80
C     COMPUTE A VARIABLE LAND ALBEDO 12/11/80 
C     JALBL,JALBO VARIABLE ALBEDO PARAMETERIZATION 1/16/81
      COMMON/NORBIT/ASTRO(5)
      COMMON/COMNT/LCOM(8)
      COMMON/CONST/ 
     1M,MM,MP,MPP,N,
     2DELPHI,DELT,PI,AEARTH,CA, 
     3CP,CO,CD,P00,P0,
     4SIGMA1,SIGMA2,XKAPPA,SIG,XLC, 
     5XLF,RHOW,RHOS,DIFF,XKS, 
     6XKI,XIMIN,SC, 
     7ITMAX,XLAM,XLS,PWLF,
     8PWLS,CDPW,CDCP,CDLC,CDLS, 
     9PWPS,XKSKI,RSEA,SGKP1,SGKP2,
     1ZSGKPA,ZSGKPB,CLRE,SQ1,SQ2
      DIMENSION LCONST(47)
      EQUIVALENCE (LCONST(1),M) 
      COMMON/LARGE/NFLD,
     1JTH1P,JTH2P,JTSLP,JTSOP,JTXLP,JTXOP,
     2JTMP,JHLP,JHOP,JXIOP,JQMLP,JQMOP, 
     3JTH1,JTH2,JTSL,JTSO,JTXL,JTXO,
     4JTM,JHL,JHO,JXIO,JQML,JQMO
C     LARGE CONTAINS THE POINTERS TO
C     THE PAIRS OF  'MAJOR' FIELDS IN W . VARIABLE
C     NAMES MADE BY ADDING J TO THE NAMES USED FOR THE DATA 
      EQUIVALENCE(JFLD(1,1),JTH1P)
      DIMENSION JFLD(12,2)
      COMMON/MINOR/NMINOR,
     1JFM,JRSN,JPS,JSP,JSPP,JCZB,JCZBP, 
     2JQ1P,JQ2P 
     3,JEXHT
     4,JFSM(3,2),JTEQ,JXIEQ,JRSNL,JRSOUT,JRLOUT 
     5,JDHLZ
     6,JHELV
     7,JALV 
     8,JALBL,JALBO
      DIMENSION KFLD(26)
      EQUIVALENCE (KFLD(1),JFM) 
C     MINOR POINTS TO OTHER FIELDS IN W 
C     NMINOR IS THE NUMBER OF POINTERS IN MINOR 
      COMMON W(46,50) 
      COMMON/AV3COM/J,JON,MZERO,MPREF,LHLS,LHOS,LXIOS 
      COMMON/CFCOM/NCG,NSC
      LOGICAL RECYC,EQSKP 
      DOUBLE PRECISION IOUTI,IOUTL,IOUTM,KK,KL
C     IOUTI,IOUTL,IOUTM SPECIFY WHICH FIELDS ARE PRINTED IN CTWOUT. 
C     ALBEDO PARAMETERIZATION 1/16/81.
      COMMON/ALCOM/ALPARA(5)
      DATA RECYC/.FALSE./ 
C     MLAST,XLMLS REMOVED 8/29/83, UNUSED.
 41   FORMAT(1X,16I5) 
 42   FORMAT(1X,5G15.8) 
 43   FORMAT(1X,D40.27) 
 44   FORMAT(1X,8A10) 
 45   FORMAT(1H1//1X,16I5)
 48   FORMAT(   /5I5,9(//5G17.10)//)
 49   FORMAT(1H1/5I5,5(//5G17.10)// 
     1G17.10,I17,3G17.10,3(//5G17.10)/) 
C     PARAMETERS FOR COMPUTATIONAL ENRTY POINT
C     (USED TO BE ON FIRST CARD)
      N1=KA 
      N2=KB 
      N3=KC 
      N4=KD 
C     SECOND CARD REMOVED 8/29/83, UNUSED.
C     (THIRD CARD) PRINTOUT LATITUDE SPACING
      MSAPR=KH
      MSBPR=KI
      MSCPR=KJ
C     FOURTH CARD) WHAT MAJOR FIELDS ARE PRINTED
      IOUTL=KK
C     (FIFTH CARD) WHAT MINOR FIELDS ARE PRINTED
      IOUTM=KL
      CALL CYCSUB(NSA,NSB,NSCRD,NSCPR,NSZ,N1,N2,N3,N4)
      WRITE(6,48)LCONST 
C     ALBEDO PARAMETERIZATION 1/16/81 
      WRITE(6,50) ALPARA
 50   FORMAT(/'  ALBEDO PARAMETERS'/(1X,5G15.8))
      WRITE(6,45)NSA,NSB,NSCRD,NSCPR
      WRITE(6,41)MSAPR,MSBPR,MSCPR
      WRITE(6,43)IOUTL,IOUTM
      IOUTI=IOUTM+10001000000001000000111.D0
      WRITE(6,42)ASTRO
      WRITE(6,44)LCOM 
      CALL CNSET
      IF(.NOT.RECYC)
     1  CALL YEAR(LCONST(4),NCG,W(1,JSP),W(1,JCZB),NSZ) 
      CALL CTWOUT(NSZ,NSZ,1,MSAPR,MSBPR,MSCPR,IOUTL,IOUTI)
      CALL AV3SET(NSZ)
      CALL HLZSET(NSZ)
      CALL PSWAP
      CALL TMSET
      CALL CDSET
      CALL PMSET
      CALL EQSETX(NS,NSZ) 
      CALL SMSET
      NSPRON=NSA
      IF(J.EQ.JON)NSPRON=NSA+NCG
      DO 60 NS=NSA,NSB,NSC
      CALL SMSTEP 
      CALL YEAR(LCONST(4),NCG,W(1,JSP),W(1,JCZB),NS)
      CALL DONE 
      CALL PLANAL(NS) 
C     PUT LOCAL ALBEDO IN CZBP FIELD 7/29/80
      DO 100 L=1,MPP
      IF(W(L,JSPP).NE.0.0) THEN 
        W(L,JCZBP)=W(L,JRSOUT)/W(L,JSPP)
       ELSE 
        W(L,JCZBP)=0.0
      ENDIF 
 100  CONTINUE
      IF(NS.GE.NSPRON)
     1  CALL CTWOUT(NS,NSZ,NSCPR,MSAPR,MSBPR,MSCPR,IOUTL,IOUTM) 
C     MONTHLY AVERAGES ADDED 8/30/83. 
      IF(J.EQ.JON.AND.NS.GE.NSPRON)  CALL CDAVE(NS) 
      IF (J.EQ.JON) THEN
C     CALL AVERAGING ROUTINES ONLY IF IN CORRECT BLOCK. 10/3/83 BG
        CALL AVE3(NS,JHL,JHO,JXIO)
        CALL TMEAN(NS,NSZ)
        CALL PLANM(NS,NSZ)
      ENDIF 
      CALL EQTSTX(NS,NSZ,EQSKP) 
      CALL PSWAP
      IF(EQSKP) GO TO 74
 60   CONTINUE
      NSZ=NSB 
 74   CALL PSWAP
      CALL HLZCON(NSZ)
      RECYC=.TRUE.
      RETURN
C 
C     SECONDARY INITIALIZATION
      ENTRY TWOBIB(NCYC,ATIME)
C     CALL TO TWOBIB AT NCYC=0 REMOVED 10/20/83.
      RECYC=.FALSE. 
      IF(NCYC.EQ.1) THEN
        NSZOLD =NSZ 
       ELSE 
        NSZ=NSZOLD
      ENDIF 
C     CALL ORBITAL PARAMETERS COMPUTATION 
      CALL ASTR(ATIME)
C     ASSIGNMENT OF ASTRO(2-4) AS CONSTANTS REMOVED 8/26/83.
C     ORBITAL PARAMETERS ARE IN COMMON NORBIT 
      CALL YRSET(LCONST(4),NCG,W(1,JSPP),W(1,JCZBP),0)
C     NO LNGSET CALL FOR NCYC=0 TO SIMPLIFY HCONV 
      CALL LNGSET 
      RETURN
      END 
