C
      SUBROUTINE FIXDAT (IYEAR,IMONTH,IDAY,IHHP,IYYF,IMMF,IDDF,IHHF)
C     ===========================================
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    FIXDAT
C   PRGMMR: RIVIN            ORG: W/NMC21    DATE: 00-11-01
C
C ABSTRACT: 
C
C PROGRAM HISTORY LOG:
C
C USAGE:    CALL FIXDAT (IYEAR,IMONTH,IDAY,IHHP,IYYF,IMMF,IDDF,IHHF)
C   INPUT ARGUMENT LIST:
C
C   OUTPUT ARGUMENT LIST:
C
C   SUBPROGRAMS CALLED
C     UNIQUE:
C      W3FS26
C
C ATTRIBUTES:
C   LANGUAGE: IBM 370 VS FORTRAN
C   MACHINE:  NAS, CRAY C-90, IBM SP
C
C$$$
C
      IYYF=IYEAR
      IMMF=IMONTH
      IDDF=IDAY
      IHHF=IHHP
      DO WHILE (IHHF.GE.24)
        IHHF=IHHF-24
        CALL W3FS26 ( JDN(IYYF,IMMF,IDDF)+1,
     &                  IYYF,IMMF,IDDF,IDAYWK,IDAYYR)
      ENDDO
      RETURN
      END
