C
      SUBROUTINE GENGDS(IGDS,IM,JM)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    GENGDS      GRIB EDITION 1 GRID DESCRIPTION SECTION
C   PRGMMR: BHAVANI.B        ORG: W/WD20     DATE: 00-18-12
C
C ABSTRACT: CREATE A GRID DESCRIPTION FOR EACH ANALYSIS OR FORE-
C   CAST SIGNIFICANT WAVE HEIGHT FIELD.
C
C PROGRAM HISTORY LOG:
C   96-08-12  BHAVANI
C
C USAGE:    CALL GENGDS(IGDS)
C   INPUT ARGUMENT LIST:
C     NONE
C
C   OUTPUT ARGUMENT LIST:
C     IGDS     - ARRAY WITH GRID DESCRIPTION INFORMATION
C     IGDS(1) = NO. OF VERTICAL COORDINATES
C     IGDS(2) = O.N. 29 GRID NO. 255=UNDEFINED
C     IGDS(3) = 0 = DATA REPRESENTATION TYPE (LAT/LONG)
C     IGDS(4) = 29 = NO. OF LONGITUDE POINTS
C     IGDS(5) = 17 = NO. OF LATITUDE POINTS
C     IGDS(6) = SOUTH LATITUDE * 1000.
C     IGDS(7) = WEST LONGITUDE * 1000
C     IGDS(8) = RESOLUTION FLAG (TABLE 7)
C     IGDS(9) = NORTH LATITUDE * 1000
C     IGDS(10) = NORTH LONGITUDE * 1000
C     IGDS(11) = LATITUDE INCREMENT * 1000
C     IGDS(12) = LONGITUDE INCREMENT * 1000
C     IGDS(13) = SCANNING MODE FLAG (TABLE 8)
C     IGDS(14),...,IGDS(18) ARE NOT USED HERE
C
C
C ATTRIBUTES:
C   LANGUAGE: IBM FORTRAN
C   MACHINE:  IBM SP
C
C$$$
C
      INTEGER IGDS(18)
C
      IGDS(1) = 0
      IGDS(2) = 255
      IGDS(3) = 0
      IGDS(4) = IM
      IGDS(5) = JM
      IGDS(6) = -30000
      IGDS(7) = 280000
      IGDS(8) = 128
      IGDS(9) = -50000
      IGDS(10) = 316000
      IGDS(11) = 200
      IGDS(12) = 200
      IGDS(13) = 0
      IGDS(14) = 0
      IGDS(15) = 0
      IGDS(16) = 0
      IGDS(17) = 0
      IGDS(18) = 0
      RETURN
      END
