C
      SUBROUTINE IN0 (LUN,IHHREF,IDDREF,IMMREF,IYYREF,IFT,IDGRD,
     &                 Z,H,FSM,DUM,DVM,ALON,ALAT,IM,JM,KB)
C     ===========================================
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    IN0    
C   PRGMMR: RIVIN            ORG: W/NMC21    DATE: 00-11-01
C
C ABSTRACT:
C
C PROGRAM HISTORY LOG:
C
C USAGE:    CALL IN0 (LUN,IHHREF,IDDREF,IMMREF,IYYREF,IFT,IDGRD,
C                       Z,H,FSM,DUM,DVM,ALON,ALAT,IM,JM,KB)
C
C   INPUT ARGUMENT LIST:
C     FT22F001 - yymmddhh.grd
C
C   OUTPUT ARGUMENT LIST:
C
C   SUBPROGRAMS CALLED
C     UNIQUE:
C      GETLBL
C
C ATTRIBUTES:
C   LANGUAGE: IBM 370 VS FORTRAN
C   MACHINE:  NAS, CRAY C-90, IBM SP
C
C$$$
C
      DIMENSION Z(KB),H(IM,JM),FSM(IM,JM),DUM(IM,JM),DVM(IM,JM)
      DIMENSION ALON(IM,JM),ALAT(IM,JM)
      LOGICAL KEND
      CALL GETLBL(LUN,IHHREF,IDDREF,IMMREF,IYYREF,IFT,IDGRD,IM,JM,
     &            KB,KEND)
      READ (LUN) Z
      Z=-Z
      READ (LUN) H,FSM,DUM,DVM,ALON,ALAT
      RETURN
      END
